### ISSUE TITLE
anvi-export-locus should generate a split contigs database instead of fasta file

### ISSUE THREAD

**Issue by ShaiberAlon** [merenlab/anvio#1000]
currently anvi-export-locus creates a fasta file for each locus (or one fasta file with all hits depending on whether `--separate-fasta` was invoked), it would be better if the output would be a new contigs database.

The purpose of this issue is so we could have a discussion on what this feature should look like. @meren, feel free to ignore these notes if they are not helpful. I only put these here, because when you wrote that this should be done, then I was tempted and went to look at how `anvi-split` works to see how hard this looks to me.

## Suggested features
 - **multiple or a single contigs database**: optionally, there could be a flag `--separate` that would determine if each hit would be in it's own contigs database, or if all hits would be included in the new contigs database as separate contigs.
 - **Reverse and complement**: similarly to the way `--never-reverse-complement` works right now, we will either reverse and compliment the sequence of a contig if the direction of the "hit" gene is reverse. This means that when we update the gene calls, we would have to take this into account.
 - **inheriting functions, hmms, taxonomy** - preferably, all gene related info from the original contigs database would also be inherited into the new contigs database.

## Some thoughts about the implementation
A few thoughts from my quick look at what `anvi-split` does:

The `splitter.BinSplitter` takes these tables (pasted some code below) and just copies the relevant splits, but most of these are gene-related tables, and hence accept a list of genes so in that sense we are pretty golden, since we could supply a list of genes, get all the info for these genes, then update anything that we need (i.e. we would need to change gene caller ids (or are we keeping the original gene caller ids?), contig names (we would have to update that in case of multiple loci in the same contig), and we would obviously have to update gene position info in `t.genes_in_contigs_table_name`, `t.genes_in_splits_table_name`.

As for the contigs and splits tables those would have to be generated (from scratch?), along with 

```
        tables = {
                    t.contig_sequences_table_name: ('contig', self.contig_names),
                    t.contigs_info_table_name: ('contig', self.contig_names),
                    t.gene_function_calls_table_name: ('gene_callers_id', self.gene_caller_ids),
                    t.gene_amino_acid_sequences_table_name: ('gene_callers_id', self.gene_caller_ids),
                    t.genes_in_contigs_table_name: ('gene_callers_id', self.gene_caller_ids),
                    t.genes_in_splits_table_name: ('gene_callers_id', self.gene_caller_ids),
                    t.genes_taxonomy_table_name: ('gene_callers_id', self.gene_caller_ids),
                    t.hmm_hits_table_name: ('gene_callers_id', self.gene_caller_ids),
                    t.hmm_hits_splits_table_name: ('split', self.split_names),
                    t.splits_info_table_name: ('split', self.split_names),
                    t.splits_taxonomy_table_name: ('split', self.split_names),
                    t.nt_position_info_table_name: ('contig_name', self.contig_names),
                    'kmer_contigs': ('contig', self.split_names),
                    'kmer_splits': ('contig', self.split_names),
                }
```

**Comment by ekiefl** [comment]
1000 issues! We did it everyone!

**Comment by ShaiberAlon** [comment]
oh yay, this is the 1000th issue for anvi'o :-)

**Comment by meren** [comment]
The new `anvi-export-locus` can do the following (running this example in a mini test output directory at `tests/sandbox/test-output`):

```
anvi-export-locus -c CONTIGS.db \
                  -O test \
                  -n 1,7 \
                  -s NusB
```

``` bash
$ ls -d test_0001*
test_0001-PROFILE/
test_0001.db
test_0001.fa
```

``` bash
anvi-interactive -c test_0001.db \
                 -p test_0001-PROFILE/PROFILE.db
```

Tataaa:

![image](https://user-images.githubusercontent.com/197307/46921402-62058700-cfc0-11e8-990c-d2c34d92a924.png)

**Comment by ShaiberAlon** [comment]
That's awesome Meren!!

**Comment by ShaiberAlon** [comment]
While you are on fire, do you feel like creating a genes database to store things like gene level coverage stats and mcgc output?
:-)

**Comment by meren** [comment]
I wish I remembered that today sometime. I totally would have worked on it. But now I am quite literally on fire in the form of fever and I should stop :(

**Comment by ShaiberAlon** [comment]
Oh no! Feel better!!

**Comment by meren** [comment]
Now we can do the following and I think we are ready for some testing:

 - [ ] ability to do complete rev-comp if the target gene is reverse: 51270c9d018f234a3fbc3c169037c3a2e3176204
 - [ ] carry functions into the new contigs database: 51270c9d018f234a3fbc3c169037c3a2e3176204
- [ ] carry amino acid sequences into the new contigs database: dba29f6bfc6206dd4cd993201f27e392555ceba3

Unfortunately there is no easy way to carry HMM and taxonomy hits into the new contigs database at the moment. but since we are accurately carrying over identical gene calls and amino acid sequences, it is rather straightforward to recover those even though it is not ideal. There were some serious design bottlenecks to do those and I gave up a little bit (but knowing myself I know I will go back to it later instead of doing more time-sensitive adult person stuff).

**Comment by meren** [comment]
This is how the output looks like:

```
$ anvi-export-locus -c p214V6-CONTIGS.db \
                    --num-genes 1,21 \
                    --search-term UpxZ \
                    --use-hmm \
                    --remove-partial-hits \
                    -O CPS

Input / Output
===============================================
Contigs DB ...................................: /Users/meren/Downloads/delete/p214V6-CONTIGS.db
Output directory .............................: /Users/meren/Downloads/delete
Genes to report ..............................: 1 genes before the matching gene, and 21 that follow
Rev-comp the locus sequence if necessary .....: True

Initialization bleep bloops
===============================================
Mode .........................................: HMM search
Search term ..................................: UpxZ
HMM sources being used .......................: CPSHMM
Matching genes ...............................: 8 genes matched your search


Exporting locus 1 of 8
===============================================
Contig name ..................................: p214-V6-GG-col1_contig_14
Contig length ................................: 316,788
Num genes in contig ..........................: 264
Target gene call .............................: 2,240
Target gene direction ........................: Reverse
First and last gene of the locus (raw) .......: 2219 and 2241
First and last gene of the locus (final) .....: 2219 and 2241
Locus gene call start/stops excess (nts) .....: 122,641
Reverse complementing everything .............: True
Output FASTA file ............................: /Users/meren/Downloads/delete/CPS_0001.fa
Output contigs DB path .......................: /Users/meren/Downloads/delete/CPS_0001.db
Output blank profile DB path .................: /Users/meren/Downloads/delete/CPS_0001-PROFILE/PROFILE.db

Exporting locus 2 of 8
===============================================
Contig name ..................................: p214-V6-GG-col1_contig_28
Contig length ................................: 243,441
Num genes in contig ..........................: 227
Target gene call .............................: 3,971
Target gene direction ........................: Forward
First and last gene of the locus (raw) .......: 3970 and 3992
First and last gene of the locus (final) .....: 3970 and 3992
Locus gene call start/stops excess (nts) .....: 145
Reverse complementing everything .............: False
Output FASTA file ............................: /Users/meren/Downloads/delete/CPS_0002.fa
Output contigs DB path .......................: /Users/meren/Downloads/delete/CPS_0002.db
Output blank profile DB path .................: /Users/meren/Downloads/delete/CPS_0002-PROFILE/PROFILE.db

(...)

Exporting locus 8 of 8
===============================================
Contig name ..................................: p214-V6-GG-col1_contig_8
Contig length ................................: 309,750
Num genes in contig ..........................: 247
Target gene call .............................: 1,621
Target gene direction ........................: Reverse
First and last gene of the locus (raw) .......: 1600 and 1622
First and last gene of the locus (final) .....: 1600 and 1622
Locus gene call start/stops excess (nts) .....: 123,563
Reverse complementing everything .............: True
Output FASTA file ............................: /Users/meren/Downloads/delete/CPS_0008.fa
Output contigs DB path .......................: /Users/meren/Downloads/delete/CPS_0008.db
Output blank profile DB path .................: /Users/meren/Downloads/delete/CPS_0008-PROFILE/PROFILE.db
```
