### ISSUE TITLE
Inspect split in collection mode

### ISSUE THREAD

**Issue by FlorianTrigodet** [merenlab/anvio#1001]
(anvio-master) -bash-4.2$ anvi-self-test --version
Anvi'o version ...............................: margaret (v5.1-master)
Profile DB version ...........................: 29
Contigs DB version ...........................: 12
Pan DB version ...............................: 12
Genome data storage version ..................: 6
Auxiliary data storage version ...............: 2
Structure DB version .........................: 1

In anvi-interactive, when I use collection mode, I can see `inspect split` in the right click context menu. 

![capture d ecran 2018-10-08 a 15 58 51](https://user-images.githubusercontent.com/10922896/46613286-2592e080-cb13-11e8-91c3-fc8447be5d38.png)

It is not working but I think it shoudn't work anyway, right ?

**Comment by meren** [comment]
Yes, you shouldn't see that item in that menu :) @ozcan may have already fixed it, but I will mention him her e so he can perhaps clarify.

Thanks!

**Comment by ozcan** [comment]
Thank you for reporting Florian!
