### ISSUE TITLE
problem with anvi-script-merge-collections

### ISSUE THREAD

**Issue by johanneswerner** [merenlab/anvio#1004]
Probably this is not really a problem, but I am not sure how to solve this. 

I want to integrate maxbin, metabat and groopm binning results in my analysis. This works well, but I don't know how to integrate the CONCOCT results (the other results run on contigs, but if I export the CONCOCT results, it uses splits, and thus `anvi-script-merge-collections` throws a `ConfigError`). 

How can I export CONCOCT results in a way that I can integrate the binning results as well?

Ubuntu 16.04.2 LTS, anvi'o installed via bioconda. 

```bash
$ anvi-self-test --version
Anvi'o version ...............................: margaret (vunknown)
Profile DB version ...........................: 29
Contigs DB version ...........................: 12
Pan DB version ...............................: 12
Genome data storage version ..................: 6
Auxiliary data storage version ...............: 2
Structure DB version .........................: 1
```

**Comment by meren** [comment]
Sorry for the late response.

One way you can do it is that you an import results from other binning approaches into your contigs database as new collections using the `--contigs-mode` flag, and then export them the way you are exporting CONCOCT results so all of them are using split names.


Best,

**Comment by johanneswerner** [comment]
Thank you for the helpful answer. 

```bash
$ head -n 2 *.txt
==> concoct.txt <==
c_000000149018_split_00001      Bin_2
c_000000036073_split_00001      Bin_2

==> maxbin.txt <==
c_000000141310_split_00001      maxbin_001
c_000000091274_split_00001      maxbin_001

==> metabat.txt <==
c_000000250824_split_00001      metabat_bin_100
c_000000034210_split_00001      metabat_bin_100
```

However, if I try to create the file `collection.tsv` as described [here](http://merenlab.org/tutorials/infant-gut/#comparing-multiple-binning-approaches), I get this error message. 

```bash
$ anvi-script-merge-collections -c ../contigs.db -i *.txt -o collections.tsv

Config Error: Oh. You have the wrong stuff. Probably. Because, the contig                   
              'c_000000203126_split_00001' does not match to any of the contig names in your
              database. Here is a random contig name you have in it in comparison:          
              'c_000000000026'.              
```

So as far as I understand it, it seems to be messing up between contigs and splits. Do you know how I can fix that?

Thank you very much for our help and your fascinating tool. :-)

**Comment by meren** [comment]
Confuses me as much as it does confusing you :p Maybe you should run this on every file and try again:

```
sed -i '' 's/_split_000..//g' FILENAME
```

(I would save a copy of my files before that though).

**Comment by johanneswerner** [comment]
Thank you, that solved my problem.
