### ISSUE TITLE
Add option to check which are the annotation sources for each genomes/bins

### ISSUE THREAD

**Issue by michoug** [merenlab/anvio#1006]
Hi, 
I was running the `anvi-run-pfams `command on 40 or so genomes and it apparently failed for some of them due to the same error as described here: https://github.com/merenlab/anvio/issues/967
Would it be possible to add an option somewhere to find out which genomes were annotated and which were not?
Sorry if it's already present!
Greg

**Comment by meren** [comment]
Hi Greg,

Do you mean you run `anvi-run-pfams` on 40 or so independent contigs databases? If that is the case, you can learn which ones were properly annotated using the following command:

```
anvi-db-info CONTIGS.db 2> >(grep gene_function_sources)
```
