### ISSUE TITLE
ValueError after anvi-display-pan (only after anvi-script-FASTA-to-contigs-db)

### ISSUE THREAD

**Issue by Arkadiy-Garber** [merenlab/anvio#1007]
Operating system macOS Sierra.
Painless installation with Conda completed successfully.

`anvi-self-test --version`
Anvi'o version ...............................: margaret (vunknown)
Profile DB version ...........................: 30
Contigs DB version ...........................: 12
Pan DB version ...............................: 12
Genome data storage version ..................: 6
Auxiliary data storage version ...............: 2
Structure DB version .........................: 1

`anvi-self-test --suite pangenomics` finished successfully.

Hello,

First, thanks for all that you do! I always feel bad starting issues since I am not sure whether the problem is something dumb on my end, or an actual bug. I tend to assume the former, but have not had any luck finding anything online about this

In an attempt to display a pan genome using the anvi-display-pan command, I am receiving this:

anvi-display-pan -g TREMBLAYA-GENOMES.db -p TREMBLAYA/Tremblaya_Pan-PAN.db

[13 Oct 18 00:44:18 Recovering additional data for layers] ...                                                                                                 Traceback (most recent call last):
  File "/anaconda3/bin/anvi-display-pan", line 72, in <module>
    d = interactive.Interactive(args)
  File "/anaconda3/lib/python3.6/site-packages/anvio/interactive.py", line 128, in __init__
    self.layers_additional_data_keys, self.layers_additional_data_dict = TableForLayerAdditionalData(self.args).get_all() if a_db_is_found else ([], {})
  File "/anaconda3/lib/python3.6/site-packages/anvio/tables/miscdata.py", line 723, in get_all
    keys_dict[group_name], data_dict[group_name] = self.get()
  File "/anaconda3/lib/python3.6/site-packages/anvio/tables/miscdata.py", line 598, in get
    d[additional_data_item_name][key] = eval(entry['data_type'])(value or self.nulls_per_type[entry['data_type']])
ValueError: invalid literal for int() with base 10: '0.719424460431655'

All commands prior to this (anvi-script-FASTA-to-contigs-db, anvi-gen-genomes-storage, and anvi-pan-genome) seemed to have finished without throwing any issues. I went back and, overcoming my inherent laziness, ran anvi-gen-contigs-database on all my genomes, instead of anvi-script-FASTA-to-contigs-db. This fixed the issue, and I was able to get a really nice pan genome visualized :)

Anyway, I just wanted to bring this to light in case anyone else has an issue like this.

Thanks!
Arkadiy

**Comment by Arkadiy-Garber** [comment]
Hey Meren,

Thanks a lot! Those commands resolved the issue for me.
Cheers,
Arkadiy

**Comment by Caizhaohui** [comment]
Hey Meren

I have a similar problem .
(anvio) czh@ubuntu:~/Desktop/anvio_work$ anvi-self-test --version
Anvi'o version ...............................: margaret (vunknown)
Profile DB version ...........................: 30
Contigs DB version ...........................: 12
Pan DB version ...............................: 12
Genome data storage version ..................: 6
Auxiliary data storage version ...............: 2
Structure DB version .........................: 1

When I want to  display a pan genome using the anvi-display-pan command, I am receiving this:

anvi-display-pan -p km_test_pan/km_test_pan-PAN.db -g km_test-GENOMES.db
[06 Jan 19 02:51:16 Recovering additional data for layers] ...                Traceback (most recent call last):
  File "/home/czh/miniconda3/envs/anvio/bin/anvi-display-pan", line 72, in <module>
    d = interactive.Interactive(args)
  File "/home/czh/miniconda3/envs/anvio/lib/python3.6/site-packages/anvio/interactive.py", line 128, in __init__
    self.layers_additional_data_keys, self.layers_additional_data_dict = TableForLayerAdditionalData(self.args).get_all() if a_db_is_found else ([], {})
  File "/home/czh/miniconda3/envs/anvio/lib/python3.6/site-packages/anvio/tables/miscdata.py", line 723, in get_all
    keys_dict[group_name], data_dict[group_name] = self.get()
  File "/home/czh/miniconda3/envs/anvio/lib/python3.6/site-packages/anvio/tables/miscdata.py", line 598, in get
    d[additional_data_item_name][key] = eval(entry['data_type'])(value or self.nulls_per_type[entry['data_type']])
ValueError: invalid literal for int() with base 10: '0.719424460431655'

 I am a newcomer in bioinformatics. I am sorry I can not solve this  issue by the way you provided.

Thanks!
Zhaohui Cai

**Comment by meren** [comment]
Hi @Caizhaohui,

We apologize for this bug and thank you for reaching out to us.

If you put your genomes storage and pan database files (only those two) into a new directory, and send a Dropbox download link for the _zipped directory_ to a.murat.eren and ozcanesen at gmail.com addresses we can try to take a look and tell you exactly how to fix this.


Best,

**Comment by Caizhaohui** [comment]
Hi @meren 
         I'm sorry to reply you so late. I re-run these commands (anvi-script-FASTA-to-contigs-db, anvi-gen-genomes-storage, anvi-pan-genome, sqlite3..... you provided and anvi-display-pan) without any issues. I also run the anvio following the way of Arkadiy-Garber and I get an interactive pan genome picture. I  found that anvi-script-FASTA-to-contigs-db contain three steps (anvi-script-reformat-fasta, anvi-gen-contigs-database and anvi-run-hmms) by browsing the code of anvi-script-FASTA-to-contigs-db. 
        Your prompt reply push me to solve the issue and learn more. Thanks for your excellent work and patience.

Best regards
Zhaohui Cai
