### ISSUE TITLE
Create a GENES.db for anvio

### ISSUE THREAD

**Issue by ShaiberAlon** [merenlab/anvio#1009]
This is related to #754, and #663.

We need a GENES.db so that when someone wants to use "gene mode" of the interactive interface they would be able to:
1. have all the gene stats stored so they don't have to be calculated on-the-fly (which could often take a long time).
2. be able to save states for "gene mode"
3. be able to save collections in gene-level
4. Anything else? Meren, any suggestions?

**Comment by meren** [comment]
Thanks for this, @ShaiberAlon :slightly_smiling_face:

I agree that this is very important, and I will try to schedule some time for it rather soon.

**Comment by meren** [comment]
@ShaiberAlon, we can close this one if you are happy.

**Comment by ShaiberAlon** [comment]
You asked me for a profile database for which this feature used to be slow.
I have it, but I had to upgrade it from version -12398, once it finishes, I'll give it a look, and then close this issue.

**Comment by meren** [comment]
hehe. thanks :)
