### ISSUE TITLE
Extract sequences of similar gene clusters in the phylogenomics workflow

### ISSUE THREAD

**Issue by johanneswerner** [merenlab/anvio#1012]
I have a question about the pangenomics workflow: 

If I look at the image from the phylogenome workflow (see below), I see the regions that show high similarity.

![image](https://user-images.githubusercontent.com/34099811/47015781-2d273a80-d14e-11e8-8445-38d1ca4c9233.png)

How can I extract these regions from all of those bacteria (I want to compare the gene clusters in this regions). 

Thank you for your help.

**Comment by meren** [comment]
As explained in the [tutorial](http://merenlab.org/2016/11/08/pangenomics-v2/), you can make selections through the interface to select gene clusters of interest:

![selection](http://merenlab.org/images/anvio/2016-11-08-pan-genomics/pc-selection.gif)

or use more advanced filters to identify gene clusters to focus, then store them as a collection, and use `anvi-summarize` to get the summary output to access to all gene clusters of interest along with their attributes.
