### ISSUE TITLE
Allow to set a max limit of threads to all rules

### ISSUE THREAD

**Issue by ShaiberAlon** [merenlab/anvio#1015]
This is an issue only because early on I made a design decision not to use the [cluster-config](https://snakemake.readthedocs.io/en/stable/snakefiles/configuration.html#cluster-configuration) option of snakemake, and instead to define the threads in the config file.

The problem is that now if we want the workflow to use up to 5 threads, we need to manually change each rule that uses more than 5 threads by default (for example, assembly uses 11 by default).

In order to make it easier I plan to add a general param to the config file: `max_threads`. By default it will be `None` and then there will be no limit. If the user sets `max_threads`, then the threads used for each rule, would be the minimum between what is set by default (or specified in the config file) and `max_threads`. So if for example, the config file looks like this:

```json
{
    "megahit": {
        "run": true,
        "threads": 10
    },
    "max_threads": 5
}
```

Then `megahit` will only use 5 threads.

**Comment by ShaiberAlon** [comment]
Ok, I now think about it, and maybe there is a way to do this using the already existing `resources.nodes` that we have.

**Comment by FlorianTrigodet** [comment]
Hi Alon, 
So far, I used the flag `--additional-params --jobs 5` with the `anvi-run-workflow` command to scale down the maximum threads used. What would be different with the max_threads param ?
I guess it is easier if every parameters are kept in the config file.

**Comment by ShaiberAlon** [comment]
Hi @FlorianTrigodet,
This question I posted on stackoverflow might clarify why I think I need this:
https://stackoverflow.com/questions/52879145/limit-total-thread-use-number-of-jobs-and-maximum-threads-per-rule-when-using

Please let me know if it doesn't clarify it.
