### ISSUE TITLE
Making anvi-gen-variability-profile to optionally report VCF files

### ISSUE THREAD

**Issue by meren** [merenlab/anvio#1021]
What `anvi-gen-variability-profile` reports is much more comprehensive than the VCF file format that is documented here:

http://samtools.github.io/hts-specs/VCFv4.3.pdf

However, this shall stay here as a small project for someone who has extra time and interest in contributing to anvi'o.

**Comment by evensannesriiser** [comment]
Hi @meren!

A good colleague of mine created a Python script for converting the output of `anvi-gen-variability-profile` to a .vcf file which may be used for different variant calling tools. By using the .vcf files as input in smartpca in the EIGENSOFT package, we were able to formally test the patterns seen in the heatmap created using your description "[Visualizing SNV profiles using R](http://merenlab.org/tutorials/infant-gut/#chapter-iv-microbial-population-genetics)", see attached heatmap. See also the attached PCA, where each dot represents a sample (column in heatmap). In this case, no differences in SNV distribution are observed between the two groups, which is also expected from eyeballing the heatmap.

Anvi'o users are free to use the script, please credit Srinidhi Varadharajan, Center for Ecological and Evolutionary Synthesis (CEES), University of Oslo, Norway.

Best,

Even Sannes Riiser,
PhD candidate,
University of Oslo, Norway

![snvs](https://user-images.githubusercontent.com/11213057/48490830-8a360f00-e826-11e8-859f-0d7199145856.png)

![smartpca](https://user-images.githubusercontent.com/11213057/48490483-d7fe4780-e825-11e8-9872-240402dc3c04.png)

**Comment by meren** [comment]
Hi @evensannesriiser,

Thank you very much for the heads-up and for your time. This is definitely excellent news!

We can add something to the variability tutorial and offer a link to Srinidhi's repository, so the users who are interested in generating VCFs could benefit from it. That is the simples and quickest solution. 

But I think a more appropriate way to include this addition to the standard workflow is to add this function into the variability module of anvi'o and associate it with a flag like `--report-vcf-output`. This way anvi'o can call it with its internal data structures, and it would reach to a larger number of users. I'm sure we can find multiple ways to credit Srinidhi.

Do you think Srinidhi would be interested in such a solution?

Best wishes,

**Comment by meren** [comment]
Ping!

**Comment by evensannesriiser** [comment]
Haha, I passed your request on to Srinidhi, and figured she had answered. I'll remind her! ;)

E

**Comment by srinidhi202** [comment]
Hi @meren,
As you mention, adding a link to the repository might be the good fix for now as I do not have time immediately to work on this.  I can get back to it sometime later. Meanwhile, if anyone else wants to take over, that would be great too. :)

Cheers,
Srinidhi

**Comment by meren** [comment]
Hi Srinidhi,

I understand the time limitations. As an alternative solution, I converted your Python file to an anvi'o script (added some controls and streamlined the code a bit while at it).

Please see the source code here:

https://gist.github.com/meren/47fae137e5d74922ea8853d1930b06dd

This file is ready to go into the anvi'o codebase next to [all the other scripts](https://github.com/merenlab/anvio/tree/master/sandbox), but I don't want to put it in there myself because if *I* do it, it will be registered as my contribution, but I want this to be associated with your name so we can add you into the [AUTHORS.txt](https://github.com/merenlab/anvio/blob/master/AUTHORS.txt) as a contributor.

So if you care, what I ask of you is this:

* Please fork the anvi'o repository,
* Get a local copy of it on your computer,
* Download [this file](https://gist.githubusercontent.com/meren/47fae137e5d74922ea8853d1930b06dd/raw/d887835aea21b213048449a86cb1aef4d81d9993/anvi-script-variability-to-vcf) into the `sandbox` directory
* Commit the change to your repository, and create a pull request to anvi'o `master` repository.

It will take less than 5 minutes, and you will be recognized for this :)


Thank you very much for your consideration,

**Comment by srinidhi202** [comment]
Hi @meren,
That was very nice of you to do that! :) Thanks, and  I  have created a pull request now.  :)

Best regards,

**Comment by meren** [comment]
Thank you very much, @srinidhi202!

**Comment by ekiefl** [comment]
Hi @srinidhi202,

I have a small request. I have used the new anvio script to generate an output that looks like this:

```
##fileformat=VCFv4.0
##fileDate=20181123
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
##FORMAT=<ID=DP,Number=1,Type=Integer,Description="Read Depth">
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	s05
recA_split_00001	30	0	C	G	99	PASS	.	DP:GT	41:0/1
recA_split_00001	35	1	A	T	99	PASS	.	DP:GT	48:0/1
recA_split_00001	40	2	A	T	99	PASS	.	DP:GT	54:0/1
recA_split_00002	13	3	C	G	99	PASS	.	DP:GT	82:0/1
recA_split_00002	18	4	A	T	99	PASS	.	DP:GT	86:0/1
recA_split_00002	23	5	A	T	99	PASS	.	DP:GT	91:0/1
recA_split_00002	28	6	C	G	99	PASS	.	DP:GT	93:0/1
recA_split_00002	33	7	G	A	99	PASS	.	DP:GT	98:0/1
recA_split_00002	38	8	T	C	99	PASS	.	DP:GT	102:0/1
recA_split_00002	43	9	C	G	99	PASS	.	DP:GT	107:0/1
recA_split_00002	48	10	G	A	99	PASS	.	DP:GT	108:0/1
recA_split_00002	53	11	T	C	99	PASS	.	DP:GT	104:0/1
recA_split_00002	58	12	G	A	99	PASS	.	DP:GT	100:0/1
recA_split_00002	73	13	A	T	99	PASS	.	DP:GT	95:0/1
recA_split_00002	74	14	T	C	99	PASS	.	DP:GT	96:0/1
recA_split_00002	75	15	G	A	99	PASS	.	DP:GT	88:0/1
recA_split_00002	76	16	C	G	99	PASS	.	DP:GT	92:0/1
recA_split_00002	77	17	C	A	99	PASS	.	DP:GT	90:0/1
recA_split_00002	78	18	G	A	99	PASS	.	DP:GT	94:0/1
recA_split_00002	79	19	C	G	99	PASS	.	DP:GT	92:0/1
recA_split_00002	80	20	A	T	99	PASS	.	DP:GT	100:0/1
recA_split_00002	81	21	C	G	99	PASS	.	DP:GT	101:0/1
recA_split_00002	82	22	T	C	99	PASS	.	DP:GT	99:0/1
```

When I try and load this file with IGV, I get the following error:


> Error loading /Users/evan/Software/anvio/anvio/tests/sandbox/test-output/variability.txt.vcf: The provided VCF file is malformed at approximately line number 6: Saw GT field at position 1, but it must be at the first position for genotypes when present, for input source: /Users/evan/Software/anvio/anvio/tests/sandbox/test-output/variability.txt.vcf

Do you see what might be wrong here?

Thanks very much making your script available to us.

Cheers,
Evan

**Comment by srinidhi202** [comment]
Hi @ekiefl,
The order in which I printed the genotype and depth columns seemed to be the problem. I have now changed that part and created a pull request. Please let me know if all goes well now :)

Best,

**Comment by ekiefl** [comment]
Hi @srinidhi202,

It looks like that fixed the error, however another has appeared.

> Error loading /Users/evan/Software/anvio/anvio/tests/sandbox/test-output/variability.txt.vcf: The provided VCF file is malformed at approximately line number 6: there are 1 genotypes while the header requires that 5 genotypes be present for all records at recA_split_00001:30, for input source: /Users/evan/Software/anvio/anvio/tests/sandbox/test-output/variability.txt.vcf

This error is produced from IGV when trying to load this 'VCF':

```
##fileformat=VCFv4.0
##fileDate=20181126
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
##FORMAT=<ID=DP,Number=1,Type=Integer,Description="Read Depth">
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	s01	s02	s04	s05	s03
recA_split_00001	30	0	C	G	99	PASS	.	GT:DP	0/1:41
recA_split_00001	35	1	A	T	99	PASS	.	GT:DP	0/1:48
recA_split_00001	40	2	A	T	99	PASS	.	GT:DP	0/1:54
recA_split_00002	13	3	C	G	99	PASS	.	GT:DP	0/1:82
recA_split_00002	18	4	A	T	99	PASS	.	GT:DP	0/1:86
recA_split_00002	23	5	A	T	99	PASS	.	GT:DP	0/1:91
recA_split_00002	28	6	C	G	99	PASS	.	GT:DP	0/1:93
recA_split_00002	33	7	G	A	99	PASS	.	GT:DP	0/1:98
recA_split_00002	38	8	T	C	99	PASS	.	GT:DP	0/1:102
recA_split_00002	43	9	C	G	99	PASS	.	GT:DP	0/1:107
recA_split_00002	48	10	G	A	99	PASS	.	GT:DP	0/1:108
recA_split_00002	53	11	T	C	99	PASS	.	GT:DP	0/1:104
recA_split_00002	58	12	G	A	99	PASS	.	GT:DP	0/1:100
recA_split_00002	73	13	A	T	99	PASS	.	GT:DP	0/1:95
recA_split_00002	74	14	T	C	99	PASS	.	GT:DP	0/1:96
recA_split_00002	75	15	G	A	99	PASS	.	GT:DP	0/1:88
recA_split_00002	76	16	C	G	99	PASS	.	GT:DP	0/1:92
recA_split_00002	77	17	C	G,A	99	PASS	.	GT:DP	0/2:90
recA_split_00002	78	18	G	A	99	PASS	.	GT:DP	0/1:94
recA_split_00002	79	19	C	G	99	PASS	.	GT:DP	0/1:92
recA_split_00002	80	20	A	T	99	PASS	.	GT:DP	0/1:100
recA_split_00002	81	21	C	G	99	PASS	.	GT:DP	0/1:101
recA_split_00002	82	22	T	C	99	PASS	.	GT:DP	0/1:99
```

To me it sounded like an issue with the number of samples, so I generated a new VCF from a variability table that contains only one sample. The resulting VCF correctly loaded into IGV. So it seems like currently the script only works for variability tables in which there is a single sample. By looking at your code, it seems like you designed this to work for multiple samples, so perhaps it's an easy fix like a column being overwritten. If you need it test case to work with, I made this set of commands which can be run to test things whenever you make changes:

```
cd $YOUR_ANVIO_DIRECTORY/anvio/tests/
bash run_variability_mock.sh new
cd sandbox/test-output/
anvi-script-add-default-collection -p SAMPLES-MERGED/PROFILE.db -c single_contig.db
anvi-gen-variability-profile -p SAMPLES-MERGED/PROFILE.db -c single_contig.db -C DEFAULT -b EVERYTHING --include-split -o variability_5_samples.txt
echo "s02" > samples_of_interest
anvi-gen-variability-profile -p SAMPLES-MERGED/PROFILE.db -c single_contig.db -C DEFAULT -b EVERYTHING --include-split -o variability_1_sample.txt --samples-of-interest samples_of_interest
anvi-script-variability-to-vcf -i variability_5_samples.txt
anvi-script-variability-to-vcf -i variability_1_sample.txt

```

If `variability_5_samples.txt` opens in IGV (which you can download here: http://software.broadinstitute.org/software/igv/download) I guess it is properly formatted. Let me know if you need any help.

Cheers,
Evan

**Comment by evensannesriiser** [comment]
Hi guys,

Using Srinidhis script alone (the original version supplied to anvi'o), and without any other tweaking, I was perfectly able to produce a .vcf file for an anvi'o output containing 19 different samples.

`python3 ./anvi_reformatting_v1.py --input NZ_LN794352_snvs.txt --output $SNV_VCF_OUT/NZ_LN794352.vcf`

See attachments for input and output files.

Even

[NZ_LN794352_snvs.txt](https://github.com/merenlab/anvio/files/2618870/NZ_LN794352_snvs.txt)

[NZ_LN794352.vcf.txt](https://github.com/merenlab/anvio/files/2618859/NZ_LN794352.vcf.txt)

**Comment by srinidhi202** [comment]
Hello @ekiefl, 
The script was indeed meant for multiple sample, however,  it was  also made for  `--quince-mode` output. I have now made some changes to the script to add "./."  (missing data) when some samples do not have entries for the particular position, in the default table output from  `anvi-gen-variability-profile`.  For example, here is how the output now looks like for the test file. 

```
##fileformat=VCFv4.0
##fileDate=20181206
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
##FORMAT=<ID=DP,Number=1,Type=Integer,Description="Read Depth">
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	s01	s02	s03	s04	s05
recA_split_00001	30	0	C	G	99	PASS	.	GT:DP	0/1:26	0/1:39	0/1:52	./.	./.
recA_split_00001	35	1	A	T	99	PASS	.	GT:DP	0/1:32	0/1:46	0/1:57	./.	0/1:35
recA_split_00001	40	2	A	T	99	PASS	.	GT:DP	0/1:36	0/1:52	0/1:63	0/1:38	0/1:42
recA_split_00002	13	19	C	G	99	PASS	.	GT:DP	./.	0/1:86	0/1:112	0/1:64	0/1:66
recA_split_00002	18	3	A	T	99	PASS	.	GT:DP	0/1:72	0/1:92	0/1:117	0/1:68	0/1:75
recA_split_00002	23	4	A	T	99	PASS	.	GT:DP	0/1:76	0/1:102	0/1:124	0/1:74	0/1:81
recA_split_00002	28	5	C	G	99	PASS	.	GT:DP	0/1:80	0/1:108	0/1:134	0/1:77	0/1:87
recA_split_00002	33	6	G	A	99	PASS	.	GT:DP	0/1:83	0/1:111	0/1:147	0/1:84	0/1:96
recA_split_00002	38	7	T	C	99	PASS	.	GT:DP	0/1:87	0/1:118	0/1:157	0/1:88	0/1:103
recA_split_00002	43	8	C	G	99	PASS	.	GT:DP	0/1:90	0/1:128	0/1:167	0/1:92	0/1:105
recA_split_00002	48	9	G	A	99	PASS	.	GT:DP	0/1:92	0/1:127	0/1:160	0/1:94	0/1:103
recA_split_00002	53	10	T	C	99	PASS	.	GT:DP	0/1:90	0/1:125	0/1:157	0/1:91	0/1:100
recA_split_00002	58	11	G	A	99	PASS	.	GT:DP	1/1:95	0/1:133	0/1:162	0/1:92	0/1:98
recA_split_00002	73	12	A	T	99	PASS	.	GT:DP	0/1:87	0/1:134	0/1:152	0/1:97	0/1:82
recA_split_00002	74	13	T	C	99	PASS	.	GT:DP	0/1:84	0/1:115	0/1:147	0/1:94	0/1:89
recA_split_00002	75	14	G	A	99	PASS	.	GT:DP	0/1:84	0/1:110	0/1:136	0/1:88	0/1:80
recA_split_00002	76	15	C	G	99	PASS	.	GT:DP	0/1:87	0/1:127	0/1:151	0/1:98	0/1:91
recA_split_00002	77	16	C	G,A	99	PASS	.	GT:DP	0/1:87	0/1:131	0/2:148	0/2:94	0/2:86
```

Best,
Srinidhi

**Comment by ekiefl** [comment]
Hi, thank you so much for addressing these problems. I also noticed you cleaned up the code significantly, I'm guessing it runs about twice as fast as it did since now the data is looped through only once.

In the future I'm planning on porting your code directly into an anvio module so that `anvi-gen-variablity-profile` can report VCF format directly. You can follow that branch here: https://github.com/merenlab/anvio/tree/vcf_variability . Thanks to your efforts, adding this feature is basically just semantics.
