### ISSUE TITLE
Additional data layers in gene mode

### ISSUE THREAD

**Issue by xvazquezc** [merenlab/anvio#1033]
Hi there,

I'm trying to incorporate metaproteomics data into anvi'o but I'm having problems displaying it. So, any suggestion is welcomed.

---
Using `-A ` with `anvi-interactive` in `--gene-mode`, anvi'o loads the data but it shows the following message and the layers for the metaprot can only be displayed as text or colour (only two options in the interactive interface), which doesn't make a lot of sense for a float type

```
$ anvi-interactive --browser-path /usr/bin/chromium-browser -p PROFILE.db -c contigs.db --gene-mode -C default -b Bin_1 -A ../../../../metaprot/metaprot2.tsv

[........]

WARNING
===============================================
OK. While working on the layer 'Iso_4', which actually looked like a numerical
layer, anvi'o realized that 1890 of your items (for instance '5933' was one of
them) did not have a value for this layer. To make sure things will continue
working in the interface, anvi'o took the liberty of adding zeros as values for
these items. Which is not the smartest thing to do, but we unfortunately do not
support empty values for numerical layers yet. In MetalBeard's voice: things
shall continue to work, but ye here be warned. Back to anvi'o regular voice:
Please keep this in mind while you are studying the interactive interface be
extra careful how to interpret your analysis when you see zero values in the
layer 'Iso_4'.
```

Having so many items with no values is normal given the sparsity of any proteomic dataset.

This is a sample of the additional layer file sample lines, where `item_name` is the gene/protein id from the anvi'o gene calling:
```
item_name       H2_HCO3_1       H2_HCO3_2       H2_HCO3_3       H2_HCO3_4       Iso_1   Iso_2   Iso_3   Iso_4
2       1.0721  0       0.9196  0.96816 0       0       0       0
23      0       0       0       0       0       0       0.95913 0
24      0       0       1.8392  0       1.4378  0.93081 1.9183  0
32      1.0721  0.97968 0.9196  0.96816 0       0       0       0
46      0       0       0.9196  2.9045  1.4378  0.93081 0.95913 0.89786
47      0       0       0.9196  0       0       0       0       0.89786
48      1.0721  0.97968 0       0       0       0       0       0
49      1.0721  0       0       0.96816 0       0       0.95913 0.89786
53      1.0721  0       2.7588  2.9045  0       0.93081 1.9183  2.6936
54      2.1443  3.9187  1.8392  1.9363  0       0.93081 0.95913 1.7957
55      4.2885  2.939   1.8392  1.9363  8.6266  2.7924  2.8774  2.6936
56      1.0721  0       0.9196  0       1.4378  0.93081 0.95913 0.89786
71      1.0721  0.97968 0.9196  0       1.4378  1.8616  5.7548  0.89786
72      0       0       0       0.96816 0       0.93081 4.7957  0
74      0       0       0       0       0       0       2.8774  0
```
----
I have also tried following the Python instructions from [here](http://merenlab.org/2017/12/11/additional-data-tables/#dealing-with-item-additional-data-tables-as-a-programmer):

```
import argparse

import anvio.dbops as dbops
import anvio.utils as utils

args = argparse.Namespace(profile_db="PROFILE.db")

# get some data:
keys = utils.get_columns_of_TAB_delim_file('../../../../metaprot/metaprot2.tsv')
data = utils.get_TAB_delimited_file_as_dictionary('../../../../metaprot/metaprot2.tsv')

# add data
dbops.TableForItemAdditionalData(args).add(data, keys, skip_check_names=True)
```
and indeed I got the data into the PROFILE.db but, again, the data isn't displayed with `anvi-interactive`.
```
$ sqlite3 -column -header PROFILE.db
sqlite> SELECT * FROM item_additional_data LIMIT 10;
entry_id    item_name   data_key    data_value  data_type   data_group
----------  ----------  ----------  ----------  ----------  ----------
0           2           H2_HCO3_1   1.0721      float       default   
1           2           H2_HCO3_2   0           float       default   
2           2           H2_HCO3_3   0.9196      float       default   
3           2           H2_HCO3_4   0.96816     float       default   
4           2           Iso_1       0           float       default   
5           2           Iso_2       0           float       default   
6           2           Iso_3       0           float       default   
7           2           Iso_4       0           float       default   
```

With this option the layers are only displayed in the normal (not `--gene-mode`) mode, but they show up as empty layers (no values for any split).... kinda obvious as they map info onto gene calls not onto splits

---
I tested this on anvi'o 5.1.0 and 5.2.0 installed with conda on Ubuntu 16.04

Cheers,
Xabi

**Comment by meren** [comment]
Thank you for this report, Xabi. We should look into this carefully.

Additional data tables work at the level of `splits`, and I am not sure whether we should expect them to accept gene-level data so things can be shown in the `--gene-mode`. That said, in the current `master` we have a new database called genes database, that is automatically generated when the user runs `anvi-interactive` in `--gene-mode` for a given bin/collection. The additional data tables in the resulting genes database would be the most appropriate place to add the gene-level hit data from the metaproteomics.

I think displaying these values at the contig-level would be extremely useful, too, but I think that will require all of us to think carefully what kind of design would give us that in an elegant way.


Best,

**Comment by meren** [comment]
@xvazquezc, it would be excellent if you were to try the `master` so we can find out if there are improvements to be made, or bugs to fix when this new feature is used for something serious. This way the version in the release would be much better, too :)

**Comment by meren** [comment]
Hi @xvazquezc, I just merged the PR #1039 into `master`. If you update your `master`, you will be able to use `anvi-*-misc-data` programs (or the Python API as you tried before) to add remove additional data to genes databases.

**Comment by xvazquezc** [comment]
I think something broke in the repo... I tried to upgrade my installation (didn't work) and then do a clean installation a couple of times, but I keep getting this type of error no matter if I use `--gene-mode` or not:

```
$ anvi-interactive --browser-path /usr/bin/chromium-browser -p ../SAMPLES_MERGED/PROFILE.db -c ../contigs.db 
Traceback (most recent call last):
  File "/home/xabi/anaconda2/envs/anvi-master/bin/anvi-interactive", line 4, in <module>
    __import__('pkg_resources').run_script('anvio===5.2-master', 'anvi-interactive')
  File "/home/xabi/anaconda2/envs/anvi-master/lib/python3.6/site-packages/pkg_resources/__init__.py", line 664, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/xabi/anaconda2/envs/anvi-master/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1444, in run_script
    exec(code, namespace, namespace)
  File "/home/xabi/anaconda2/envs/anvi-master/lib/python3.6/site-packages/anvio-5.2_master-py3.6-linux-x86_64.egg/EGG-INFO/scripts/anvi-interactive", line 15, in <module>
    from anvio.bottleroutes import BottleApplication
  File "/home/xabi/Desktop/sandbox/anvi-master/anvio/anvio/bottleroutes.py", line 26, in <module>
    from bottle import Bottle
  File "/home/xabi/anaconda2/envs/anvi-master/bin/bottle.py", line 4, in <module>
    __import__('pkg_resources').run_script('bottle==0.12.13', 'bottle.py')
  File "/home/xabi/anaconda2/envs/anvi-master/lib/python3.6/site-packages/pkg_resources/__init__.py", line 664, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/xabi/anaconda2/envs/anvi-master/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1435, in run_script
    .format(**locals()),
pkg_resources.ResolutionError: Script 'scripts/bottle.py' not found in metadata at '/home/xabi/anaconda2/envs/anvi-master/lib/python3.6/site-packages/bottle-0.12.13-py2.7.egg-info'
```
---

Because the data table is from metaproteomics and the `genes.db` are specific for a bin, whenever I try to incorporate the table into the `genes.db` it complains about many of the item names are only in my data but not in the db (duh..) 

```
Config Error: Well. 498 of 2236 item names in your additional data are only in your data      
              (which that they are not in the genes database you are working with (which means
              bad news)). Since there is no reason to add additional data for items that do   
              not exist in your database, anvi'o will stop you right there. Please fix your   
              data and come again. In case you want to see a random item that is only in your 
              data, here is one: 2086. Stuff in your db looks like this: 5837.                
```

Good news: it is possible to filter them and then successfully import the corresponding proteins into the `genes.db`!! It might be good that this could become an option for any annotation/additional data mapped into the whole metagenome but that it is meant to be displayed at gene-level

```
$ sqlite3 -column GENES/default-Bin_1.db "SELECT DISTINCT gene_callers_id FROM gene_level_coverage_stats;" > bin2genes.txt
$ for i in $(cat bin2genes.txt) ; do awk -v i=$i '$1==i' metaprot2.tsv >> test2.txt; done
$ head -n1 metaprot2.tsv > test2-whead.tsv
$ cat test2.txt  >> test2-whead.tsv 
$ anvi-import-misc-data test2-whead.tsv -p GENES/default-Bin_1.db -t items

New data for 'items' in data group 'default'
===============================================
Data key "H2_HCO3_1" .........................: Predicted type: float
Data key "H2_HCO3_2" .........................: Predicted type: float
Data key "H2_HCO3_3" .........................: Predicted type: float
Data key "H2_HCO3_4" .........................: Predicted type: float
Data key "Iso_1" .............................: Predicted type: float
Data key "Iso_2" .............................: Predicted type: float
Data key "Iso_3" .............................: Predicted type: float
Data key "Iso_4" .............................: Predicted type: float


WARNING
===============================================
Your input contains additional data for only 1738 of 3628 total number of items
in your genes database. Just wanted to make sure you know what's up, but we
cool.


NEW DATA
===============================================
Database .....................................: genes
Data group ...................................: default
Data table ...................................: items
New data keys ................................: H2_HCO3_1, H2_HCO3_2, H2_HCO3_3, H2_HCO3_4, Iso_1, Iso_2, Iso_3, Iso_4.
```

Thanks,
Xabi

**Comment by meren** [comment]
> I think something broke in the repo...

I know that error, Xabi. I caused that error, but fixed it after an hour or so, you shouldn't get it if you have an up-to-date master :/


> Because the data table is from metaproteomics and the `genes.db` are specific for a bin, whenever I try to incorporate the table into the `genes.db` it complains about many of the item names are only in my data but not in the db

We can add a flag to `anvi-import-misc-data`, something like, `--import-only-if-relevant`, which would only import the part of the input data that matches to the items in the target database. Would it help?

**Comment by xvazquezc** [comment]
> I know that error, Xabi. I caused that error, but fixed it after an hour or so, you shouldn't get it if you have an up-to-date master :/

I reinstalled from `master` less than 1 h ago :/


> We can add a flag to `anvi-import-misc-data`, something like, `--import-only-if-relevant`, which would only import the part of the input data that matches to the items in the target database. Would it help?

Yeah, that should do

**Comment by meren** [comment]
> I reinstalled from `master` less than 1 h ago :/

What is the output when you run this:

``` bash
grep -B 2 pkg_resources `python -c 'import anvio; print(anvio.__file__)'`
```

**Comment by xvazquezc** [comment]
```
# yes, this library is imported but never used, but don't remove it
# unless you want to explode `bottle`:
import pkg_resources
```

**Comment by meren** [comment]
Well :( Then I have absolutely 0 idea where is that error coming from :(

**Comment by xvazquezc** [comment]
I'll try. Otherwise, I'll clear all dependencies and redo the virtual environment.

**Comment by meren** [comment]
Woohooo :)

**Comment by xvazquezc** [comment]
Hey @meren , is it possible to do clustering on the additional layers? So that would make easier to find groups of prots expressed differently in the diff treatments

**Comment by meren** [comment]
Indeed. There is already a not-so-elegant way to do it:

* Export additional layers of interest as a matrix.
* Use `anvi-matrix-to-newick` to create a tree of items (it may require you to do it with the `--transpose` flag).
* Use the tree with `anvi-interactive` with the `--tree` parameter, and select it from the combo in the interface (we can also implement a new program, i.e., `anvi-import-items-order`, to import the tree directly to the genes database). I am not sure whether this step will work, but if you get this far, I promise I will help you.

**Comment by xvazquezc** [comment]
Yeah, I saw it. Thanks @meren !!

I'm getting into this step right now. I'll let you know for sure :)

**Comment by xvazquezc** [comment]
Nice :sunglasses:

You guys are amazing!

![screenshot from 2018-11-23 11-01-20](https://user-images.githubusercontent.com/14157565/48924732-7158e800-ef0f-11e8-8895-de94d5a33053.png)

**Comment by meren** [comment]
Awesome!!! Thank you for your patience :)

**Comment by xvazquezc** [comment]
Hi @meren ,
I've been finally tackling the stats on the metaproteomics data and I'm trying to figure out the best way to draw the results. After all, the strength of proteomics is doing differential analyses...

So, in case you are not familiar with differential expression analysis, what you get at the end is a p-value and a log of the fold change of the expression, either prots or RNA. And that's what is drawn in the typical volcano plots.

So, my idea is to add a layer plotting the logFC and colour them based on the -log(pvalue) and logFC, so anything with pvalue <=0.05 and abs(logFC) > 2 would be easily spotted. Something like the colour schemes in the volcano plots.

The input structure could be something like:

| item_name | bars_categorical!A;B |
| -- | -- |
| backrest | 278;A |
| backward | 249;B |

So, while plotting the numerical values as normal barplot, it should apply colours based on A and B like in a categorical variable. Not sure if this would be doable though.

Otherwise I'll plot the pass/fail for the thresholds as a categorical layer

BTW, does the bar type handle negative values?

Thanks,
Xabi

**Comment by xvazquezc** [comment]
Thanks @meren , I want to try a couple of things first, otherwise I'll send you what I have in private later today.

**Comment by meren** [comment]
Hey @xvazquezc, here I will ping @ozcan and ask his opinion whether we can update the interface code to display negative values in 0-centered displays for bars. This wouldn't work for intensity, but should be doable for bars and lines.


Best,

**Comment by ozcan** [comment]
I will look into this in more detail, whether can we change the default behavior easily or is it easier to implement a new layer type for this purpose.

But in a meantime, our stack bar data type is pretty flexible and can be used for this purpose.
I have created a layer like below:
<img width="885" alt="screen shot 2018-12-16 at 12 31 36 pm" src="https://user-images.githubusercontent.com/940884/50057337-97e4fa00-012e-11e9-8cca-55b01d85b676.png">

Here is the script I have used:
```python
import pandas as pd

column = 'c2'
view_data = 'view_data.txt'

df = pd.read_csv(view_data, sep='\t')

df[column + '!negative_complement'] = df[column]
df[column + '!negative'] = df[column]
df[column + '!positive'] = df[column]
df[column + '!positive_complement'] = df[column]

df[column + '!positive'][df[column + '!positive'] < 0] = 0
df[column + '!negative'][df[column + '!negative'] > 0] = 0
df[column + '!negative'] = df[column + '!negative'].abs()

df[column + '!positive_complement'] = df[column].max() - df[column + '!positive']
df[column + '!negative_complement'] = abs(df[column].min()) - abs(df[column + '!negative'])

del df[column]

df.to_csv(view_data + '_negative_values', sep='\t', index=False)
```

And using the interface, you need to pick background color for items ending with `_complement`, and bar color for the others as below:
<img width="476" alt="screen shot 2018-12-16 at 12 34 16 pm" src="https://user-images.githubusercontent.com/940884/50057360-ee523880-012e-11e9-940a-cc318ada23c8.png">

I will reply again once I have better understanding of limitations we have for this feature.
Best,
Ozcan

**Comment by meren** [comment]
This is an ingenious workaround, @ozcan. Although it may be too much to expect users to go through this every time their data contains negative values.
