### ISSUE TITLE
eggNOG mapper issue with parsing output from recent version

### ISSUE THREAD

**Issue by jzrapp** [merenlab/anvio#1036]
Hi anvio team,

I've been using eggNOG 4.5 for the annotation of functions in my exported .fa file, however, realized that the parser in anvio5 currently only handles a previous version of the output and the emapper.py. It is not prepared to use the BiGG metabolic reactions annotations that are being produced when running eggNOG. For now, I just deleted this column for parsing the info, but wanted to let you know/ask if this will be included in a future release?

Thanks so much for anvio! Makes my life so much easier :)

**Comment by meren** [comment]
Hi @jzrapp,

Thanks for the report. Can you please take the attached contigs database, run exactly the steps you run to generate eggnog output for your own contigs database, and then send me the eggnog output as well as the list of each commands you run throughout the process?

If you can provide that we can fix the parser and send you a solution :)


Best,

[CONTIGS.db.zip](https://github.com/merenlab/anvio/files/2601437/CONTIGS.db.zip)

**Comment by jzrapp** [comment]
Hi @meren, 
thanks for answering so quickly!

Sorry, I was not really clear in my previous comment: I used the webservice emapper v.4.5 and tried to feet this output into anvio. This can be achived by using 
anvi-script-run-eggnog-mapper and specifying the --annotation and --use-version, I think. However, the anvi-script-run-eggnog-mapper expects an input file with 12 columns, while the eggNOG now also produces BiGG metabolic reactions annotations, ending up with 13 columns. Also the anvi-script-run-eggnog-mapper expects gene_call_ids with a 'g' prefix. And it is build for the emapper version 0.12.6, which seems relatively old, my newly installed version is 1.0.3.

For now, I just deleted the column for BiGG from my output, and added a g in front of all gene calls, and just claimed that I used emapper version 0.12.6... 

anvi-script-run-eggnog-mapper -c contigs.db --cog-data-dir /scratch2/db/dset/COG_anvio --annotation EggNOG-4.5/CBIW_anvio_assembly_amino_acid_fa_for_anvio.txt --use-version 0.12.6

**Comment by meren** [comment]
Hi @jzrapp,

No, it was clear :) You know how you have this file for your own contigs database:

```
EggNOG-4.5/CBIW_anvio_assembly_amino_acid_fa_for_anvio.txt
```

I was asking the equivalent file for the contigs database I sent :) So you should do whatever you did to get the file above for your contigs database, to get the same file for the contigs database I sent. So I can test it.


Best,

**Comment by jzrapp** [comment]
Hi @meren,

so here it is!
The original emapper annotation output can be found here: http://eggnogdb.embl.de/#/app/emapper?jobname=MM_xjsTNB
and here are the ones that I modified so that anvio likes them:
[amino-acid-sequences_fa_emapper_annotations_mod1.txt](https://github.com/merenlab/anvio/files/2602032/amino-acid-sequences_fa_emapper_annotations_mod1.txt)
[amino-acid-sequences_fa_emapper_annotations_mod2.txt](https://github.com/merenlab/anvio/files/2602033/amino-acid-sequences_fa_emapper_annotations_mod2.txt)

My steps to get there are documented here:
[anvio_eggNOG_test.txt](https://github.com/merenlab/anvio/files/2602043/anvio_eggNOG_test.txt)

Best,
Josephine

**Comment by meren** [comment]
Hi Josephine,

This is done in the `master` and will be in the next release if you don't want to use the `master` repository.

Now we have a parser for `v1.0.3` that also adds BiGG reactions to the contigs database.

Thank you for your help.
