### ISSUE TITLE
Taxonomy as last layer by default?

### ISSUE THREAD

**Issue by tdelmont** [merenlab/anvio#1048]
Hi,

this is not a bug, but a requests:
would it be possible to set taxonomy as last layer by default?

During binning when >20 metagenomes are involved, taxonomy is barely visible when close to the inner tree (default). I personally drag it as last layer every time, which involves manual labor...

Note that even in the anvi'o tutorial for the infant gut we ask the user to put it as last layer. It improves visibility of this key feature. 

Thanks for considering this request!

Best,

Tom

**Comment by tdelmont** [comment]
and yes, this means I am binning on a Sunday morning...

**Comment by meren** [comment]
Hey @ozcan,

Can we put the named layer 'taxonomy' as the most outer layer unless a specific organization is stored in the state file? I think this would make things simpler for lots of people :)


Thanks,

**Comment by tdelmont** [comment]
Many thanks @ozcan !!!!
