### ISSUE TITLE
Bugs in the parser for emapper 1.0.3 annotation files

### ISSUE THREAD

**Issue by Monchun** [merenlab/anvio#1049]
Hi @meren 
Recently you have updated the emapper parser for version 1.0.3. I tried to use emapper parser to import functions into the contig database following your tutorial. However, there raised a config error. Then I looked into the code you added. I think there is a small issue in the parser 2.
According to your code, you want to parse
 """
            0          1                    2                    3                   4                   5                     6                 7                    7                    8                                                    9                    10      11
            query_name seed_eggNOG_ortholog seed_ortholog_evalue seed_ortholog_score predicted_gene_name GO_terms              KEGG_pathways     BiGG_Reactions       Annotation_tax_scope OGs                                                  bestOG|evalue|score  COG_cat eggNOG_annot
            0          367928.BAD_0533      4.3e-211             696.2               TUF                 GO:0001666,GO:0003674 K02358            SADT2                bactNOG[38]          00BM5@actNOG,05CGV@bactNOG,COG0050@NOG               05CGV|2.1e-158|530.1       J This protein promotes the GTP-dependent binding of aminoacyl-tRNA to the A-site of ribosomes during protein biosynthesis (By similarity)[201~]]
        """
But if not fields[0].startswith(self.gene_caller_id_prefix) would require a prefix g same as parser1 which is not right for the parser2.

**Comment by meren** [comment]
I see. So the requirement for `g` is missing from the parser 2. Can you confirm?

Sorry I'm confused a bit :) Long day.

**Comment by Monchun** [comment]
Sorry, I didn't make it clear. anvi-export-gene-calls gave me amino acid sequence with headers (>0, >1, >2, e.g.). So, feeding this aa file, Emapper gave me the annotation like
| query_name 	| seed_eggNOG_ortholog 	| seed_ortholog_evalue 	| seed_ortholog_score 	| predicted_gene_name 	|        GO_terms       	| KEGG_pathways 	| BiGG_Reactions 	| Annotation_tax_scope 	| OGs                                    	| bestOG|evalue|score  	| COG_cat 	| eggNOG_annot 
|------------	|:--------------------:	|:--------------------:	|:-------------------:	|:-------------------:	|:---------------------:	|---------------	|----------------	|----------------------	|----------------------------------------	|----------------------	|---------	|-------------------------------------------------------------------------------------------------------------------------------------------------	|                                                                                                                    	|
| 0          	|  632245.CLP_3059  	|       1e-77       	|      258.7      	|                  	| GO:0001666,GO:0003674 	|        	| SADT2          	| bactNOG[38]          	| 07Z85@bactNOG,0ESYF@cloNOG,0NIPF@firmNOG,COG4753@NOG 	| COG4753|1.95270971567e-77|264.347320557 	| T     	| Transcriptional regulator (AraC family)	|

I ran anvi-script-run-eggnog-mapper using parser for version 1.0.3, which raise a config error stating that I should add a prefix 'g' to every query_name. I suppose if I add a g to every query_name, it will work. However, looking into the code, I think the intent is to parse the query_name without 'g' prefix. Therefore, the exceptional handling same as parser 1 does not work. So I commented on the
if not fields[0].startswith(self.gene_caller_id_prefix) block and changed gene_callers_id = int(fields[0][len(self.gene_caller_id_prefix):]) to gene_callers_id = int(fields[0]). And it worked. 
Don't know if I am a special case.

**Comment by meren** [comment]
hi @Monchun,

I just made sure both parsers learn the gene caller id the same way (they both expect it to have the prefix).

Can you please try with the current `master`?


Thank you,
