### ISSUE TITLE
Performance bottleneck in anvi-profile 

### ISSUE THREAD

**Issue by meren** [merenlab/anvio#1051]
Dear @ozcan and @ShaiberAlon,

I uploaded one of Alon's extremely slow profiling jobs to a server that has impeccable I/O speed,  and edited the profile progress bar in the anvi’o codebase (5f3e3775cede776f27445affe73faf568fc9aa1c) so we can better see which step takes the most amount of time.

I set the parameter `--write-buffer-size 1` to see every step per contig. Take a look at the gif below:

![ezgif-4-cf03de5901d1](https://user-images.githubusercontent.com/197307/49332180-c3cc8100-f56d-11e8-8b10-18de1db46251.gif)

We assumed the disk I/O was responsible for the significant speed losses, but now I see that computing the SCVs is what takes the most significant amount of time. We are not doing any multi-threading for that part of the code. Maybe we should consider taking a look into this? :( What do you think, Ozcan?

**Comment by ozcan** [comment]
Okay, I will look into parallelizing that part. But I am quite confused about how to read new progress bar? Would you mind explaining what does each part mean? When I see SCVs there does it mean computing scv is done for that batch? And when I see diskette it means it is writing results for that batch?

**Comment by meren** [comment]
Sorry. The last thing you see indicates the current process.

The floppy appears during disk write operation for split coverages (SNVs and SCVs are doing their own disk write operations).

**Comment by meren** [comment]
Side note, with 6766ae90e4b7bda28ad35586b3c063d7ba89246c, what is in progress is denoted with a ⚙️until its done, and then replaced with a 👍

![image](https://user-images.githubusercontent.com/197307/49335264-e5e6f300-f5af-11e8-9b4f-32a581800d24.png)

This is done through the new `step_start` and `step_end` functions in `Progress` (a96906f924f084bf1ed2dfbdcfdb342910287f63) (because why not).

Here is an example code:

``` python
import time
import anvio.terminal as terminal

progress = terminal.Progress()

progress.new('New progress')
progress.update('An update to the progress')

# site step?
progress.step_start('TASK 01')
time.sleep(2)
progress.step_end()

# another one?
progress.step_start('TASK 02')
time.sleep(5)
progress.step_end()

progress.end()
```

and what it does :)

![image](https://user-images.githubusercontent.com/197307/49335327-0794aa00-f5b1-11e8-9356-ca64c59c7ec7.png)

**Comment by ozcan** [comment]
This has been fixed on branch `parallel-SCVs`, now codon variability is computed in parallel in function `BAMProfiler.profile_contig_worker`.
