### ISSUE TITLE
anvio doesn't show completion nor redundancy for a bin

### ISSUE THREAD

**Issue by ShaiberAlon** [merenlab/anvio#1054]

**Comment by ozcan** [comment]
I am going to have a blind guess about this as recently @watsonar reported the same thing. If there are multiple domains with more than 100% completion in the bin, anvi'o does not know which domain to pick and report. But if you click to button, you should be able to see individual domains with their completion and redundancy.  I have discussed this problem with @meren this Friday and he has a plan to solve it.

**Comment by meren** [comment]
That is all very true :)

May I have access to that DB, @alon? 

(this issue is the only thing I checked at this point, I apologize if you've already made it available by other means).

**Comment by meren** [comment]
This is associated with #1078.
