### ISSUE TITLE
anvi-self-test traceback and import error 

### ISSUE THREAD

**Issue by nakeene** [merenlab/anvio#1070]
Output from anvi-self-test --version 

`$ anvi-self-test --version
Anvi'o version ...............................: margaret (vunknown)
Profile DB version ...........................: 30
Contigs DB version ...........................: 12
Pan DB version ...............................: 12
Genome data storage version ..................: 6
Auxiliary data storage version ...............: 2
Structure DB version .........................: 1
`
Hello, I am trying to install the latest Anvio version (5.2) on an HPC system using Conda and Linuxbrew and am having a pysam traceback and import error during the anvi-self-test every time that looks a little different than those reported elsewhere. I have used the following instructions for installation (in addition to linuxbrew):
```
conda create -y --name anvio5 python=3.6
conda install -y --name anvio5 django=2.0.2
conda install -y --name anvio5 -c bioconda -c conda-forge anvio=5 diamond bwa 
```

and I've tried: 
`conda install -n anvio5 -c bioconda -c conda-forge anvio=5.2.0 diamond bwa`

and I've tried: 
`brew tap merenlab/anvio`
`brew install merenlab/anvio/anvio`

I have also tried installing with different versions of pysam and nothing has worked so far. 
Everytime, no matter the method of installation (so far) the output of anvi-self-test is below, and I don't know how to fix it! Please help!  

```
$ anvi-self-test --suite mini

:: Output directory ...

/tmp/tmpjcn5r4m5/test-output

:: Anvo'o version ...

Anvi'o version ...............................: margaret (vunknown)
Profile DB version ...........................: 30
Contigs DB version ...........................: 12
Pan DB version ...............................: 12
Genome data storage version ..................: 6
Auxiliary data storage version ...............: 2
Structure DB version .........................: 1

:: Initializing raw BAM files ...

Traceback (most recent call last):
  File "/home/GLBRCORG/nakeene/bin/miniconda3/envs/anvio5/bin/anvi-init-bam", line 6, in <module>
    import pysam
  File "/opt/bifxapps/python/lib/python2.7/site-packages/CrossMap-0.2.2-py2.7-linux-x86_64.egg/pysam/__init__.py", line 1, in <module>
    from pysam.csamtools import *
ImportError: /opt/bifxapps/python/lib/python2.7/site-packages/CrossMap-0.2.2-py2.7-linux-x86_64.egg/pysam/csamtools.so: undefined symbol: _Py_ZeroStruct


Config Error: It seems something went wrong while running your tests :/ Anvi'o hopes that the
              reason is clear from the lines above.                                          


(anvio5) 

```

Help!

**Comment by meren** [comment]
Your error log suggests the import request from anvi-init-bam, running by Python3, is responded by a package compiled with Python2 (and causing linkage errors, as you would expect). This should never happen in a properly configured system.

**Comment by nakeene** [comment]
What do you suggest that I do to prevent this from happening? 
I am running Python 3 in every virtual environment I've tried but it seems to be using Python 2 anyway?

**Comment by meren** [comment]
The best solution will require much more knowledge about the system. For instance the best solution very well could be

```
rm -rf /opt/bifxapps/python/
```

On the other hand by doing so you may make many people upset (but then why should they be happy if they are using Python2?).

**Comment by nakeene** [comment]
Yes, the entire HPC system is still using python 2. I cannot delete that version but I have contacted the IT department. 

Is there any other way around this that you can think of.. or that has worked for others?

**Comment by meren** [comment]
Here is a suggestion. Remove all anvi'o you installed with brew or conda. And then follow this tutorial:

http://merenlab.org/2016/06/26/installation-v2/#installing-the-latest-stable-release-safe-mode

**Comment by ozcan** [comment]
Hi @nakeene, how does your `PYTHONPATH` looks like? Python searches for modules using that environment variable, if you change the order of directories inside that variable, you can make conda preferred. Conda installation script should prepend its path to there but it seems it didn't in your case.

You can check that using `env | grep PYTHONPATH`.

**Comment by xvazquezc** [comment]
Dumb question but, is conda in your PATH? You need to request the installer to add conda to it

**Comment by nakeene** [comment]
@xvazquezc Yes, conda is in my PATH. I think the issue is related to Python like @ozcan said previously. 

Here is the output of `PYTHONPATH` 
`$ env | grep PYTHONPATH
PYTHONPATH=/opt/bifxapps/python/lib64/python2.6/site-packages/:/opt/bifxapps/python/lib/python2.6/site-packages/:/opt/bifxapps/python/lib/python2.7/site-packages/:/opt/bifxapps/python/lib/python3.4/site-packages/
(anvio5) `

Clearly, it does not seem to be referencing the conda directory for python.

These are the results when I run `env | grep conda` 
`CONDA_EXE=/home/GLBRCORG/nakeene/bin/miniconda3/bin/conda
PATH=/home/GLBRCORG/nakeene/bin/miniconda3/envs/anvio5/bin:/mnt/bigdata/linuxhome/nakeene/bin/homebrew/bin:/home/GLBRCORG/nakeene/bin/diamond:/home/GLBRCORG/nakeene/bin/NCyc-master:/home/GLBRCORG/nakeene/bin/SPAdes-3.13.0-Linux/bin:/opt/bifxapps/mothur:/home/GLBRCORG/nakeene/bin/blast-2.2.25/bin:/home/GLBRCORG/nakeene/bin/cdbfasta:/home/GLBRCORG/nakeene/bin/microbiomeutil_20101212/ChimeraSlayer:/home/GLBRCORG/nakeene/bin/ea-utils.1.1.2-806:/opt/bifxapps/hmmer:/opt/bifxapps/ncbi-blast-2.2.29+/bin:/home/GLBRCORG/nakeene/bin:/opt/bifxapps/bin:home/GLBRCORG/nakeene/src/edirect:/home/GLBRCORG/nakeene/bin/miniconda3/bin:/home/GLBRCORG/nakeene/bin:/usr/local/rvm/gems/ruby-2.4.1/bin:/usr/local/rvm/gems/ruby-2.4.1@global/bin:/usr/local/rvm/rubies/ruby-2.4.1/bin:/usr/lib64/qt-3.3/bin:/usr/lib64/mpich/bin:/usr/java/latest/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:/opt/bifxapps/bin:/usr/local/cuda-6.5/bin:/opt/bifxapps/gmap/util:/opt/bifxapps/matlab/bin:/usr/lib64/openmpi/bin:/opt/bifxapps/rsem:/usr/local/rvm/bin
CONDA_PREFIX=/home/GLBRCORG/nakeene/bin/miniconda3/envs/anvio5
CONDA_PYTHON_EXE=/home/GLBRCORG/nakeene/bin/miniconda3/bin/python
(anvio5) `

@ozcan How do I make the version of python specified by my Conda environment (which could be different in each Conda environment I create) the preferred version?

**Comment by nakeene** [comment]
@ozcan @meren @xvazquezc I fixed it! 
I simply added 
`export PYTHONPATH=/home/GLBRCORG/nakeene/bin/miniconda3/bin/python` 
to my PATH and now it defaults to the correct version. 

Thanks again for the help everyone!

**Comment by ozcan** [comment]
Hi @nakeene,
Yes, I can see what you did might solve the issue. In your original `PYTHONPATH`, `/opt/bifxapps/python/lib/*` paths were prioritized. By simply removing them you let Python find modules in relative locations to your conda's python binary.

But the path you had put there has no effect because it is not a valid python path, it is the path of the python binary/executable that comes with conda but python path actually is the path that contains python modules.

The actual python path in conda should something similar to `/home/GLBRCORG/nakeene/bin/miniconda3/lib/python3.6`. But there is no need to change it in your case, as removing that env variable or putting random letters will have the same effect. I have just wanted add side note to make this information available for future users who will end up here with google searches.

Best,
