### ISSUE TITLE
Update gene annotations after database is generated?

### ISSUE THREAD

**Issue by evensannesriiser** [merenlab/anvio#1072]
Dear anvi'o people,

After creating a database with `anvi-gen-contigs-database` with `--external-gene-calls` (during the Snakemake workflow), I realized some gene annotations were missing from the annotations file supplied with the NCBI reference genome I am using. I identified these genes (and their location) in the reference genome myself by blasting, and I now want to include these into the anvio database.

After a tip from Meren at Slack, I managed to add the new annotations to the contigs database using the “DB Browser for SQLite”. This involved blasting my genes of interest (the ones I want annotated) to both the contigs and splits (to retrieve their locations), and then editing database records in "genes_in_contigs", "genes_in_splits" and "gene_functions". This is a very manual and exhausting way of updating annotations, though.

Is there an easy way to update the gene calls/annotations of my database after finishing the database generation/Snakemake workflow?

Best,

Even Sannes Riiser,
PhD candidate, University of Oslo,
Norway

**Comment by meren** [comment]
Hi @evensannesriiser. Sorry it took this long to get a response for this. I think we are going to have to be realistic and classify this as a "very special case". In the never-ending struggle to assign our scarce time resources to where they are most needed, I will close this issue admitting with a broken-heart that we will not address it.

I hope all is well.
