### ISSUE TITLE
anvi-script-process-genbank-metadata should check for bad characters in organism_name column

### ISSUE THREAD

**Issue by ShaiberAlon** [merenlab/anvio#1077]
For example:

``` bash
# download genomes
ncbi-genome-download bacteria \
                     --taxid 743966 \
                     --metadata-table metadata.txt

# work with the metadata.txt
anvi-script-process-genbank-metadata -m metadata.txt \
                                     -o output
```

Then you will get the error:

```
File/Path Error: You do not have permission to generate the output file '~/output/Mycoplasma_bovoculi_M165/69_GCF_0005245551-contigs.fa'
```

And this is because the `organism_name` is `Mycoplasma bovoculi M165/69`. So the `/` is killing everything. This is easy to fix manually, which is what I did for now, but I figured I would make an issue.

**Comment by meren** [comment]
I've been making small changes lately, but I agree that we need to have a foolproof method to do this. I will take a look.

**Comment by meren** [comment]
I didn't test it utterly well, but I hope this solves it, Alon.
