### ISSUE TITLE
Real-time completion during binning: strange behavior using the Master 

### ISSUE THREAD

**Issue by tdelmont** [merenlab/anvio#1078]
On the master.

I have been doing extensive binning using the master of anvi'o, and I identified a strange behavior, which might be due to ongoing efforts to better identify eukaryotic MAGs. 

I finally got a good example and here I am, sharing it here:

This is what I get with this first selection:

<img width="1077" alt="screen shot 2018-12-26 at 1 25 51 pm" src="https://user-images.githubusercontent.com/8332889/50445929-3719a680-0912-11e9-8251-e50437625366.png">

and then when adding more contigs:

<img width="1081" alt="screen shot 2018-12-26 at 1 26 07 pm" src="https://user-images.githubusercontent.com/8332889/50445946-56b0cf00-0912-11e9-92b2-d8f3ca3ccb33.png">

The score becomes 0, even though there are many sccgs. I assume it is because anvi'o does not know with confidence which collection to use, yet it creates a new problem: now the user needs to test many small selections on the interface in order not to miss entire genomes. I might have missed some, so I am not sure this is the way to go.

Best,

Tom

**Comment by meren** [comment]
(I will work on this at some point before the next small release)

**Comment by meren** [comment]
I think this is all addressed.
