### ISSUE TITLE
anvi-script-process-genbank-metadata shouldn't generate external gene calls for genebank entries with no gene calls

### ISSUE THREAD

**Issue by ShaiberAlon** [merenlab/anvio#1079]
For example:

```
## download a silly genome with no gene calls
$ ncbi-genome-download -A GCA_003251355.1 bacteria -s genbank -o temp -m temp-metadata.txt

## process
$ anvi-script-process-genbank-metadata -m temp-metadata.txt -o tempytemp --output-fasta-txt temp-fasta.txt

## print the gene calls file
$ cat `cut -f 3 temp-fasta.txt | tail -n 1`

name	path	external_gene_calls	gene_functional_annotation
```

If there are no gene calls then I think the best behavior is to warn the user with a `run.warning` message, and then in the `fasta.txt` file there wouldn't be entries for the external gene calls and the external functions.

**Comment by meren** [comment]
This is now addressed. If there are no gene calls in GBK file, 

* `anvi-script-process-genbank`  shows a warning, and does not generate any output files for gene calls or functions,
* `anvi-script-process-genbank-metadata` does not show any warning, but does put `None` for columns external gene calls and functions in `FASTA_TXT` output.

I hope this is useful.

**Comment by ShaiberAlon** [comment]
Great. Thank you!
