### ISSUE TITLE
Need for an anvi'o script to change the SAMPLE ID of a completed profile DB

### ISSUE THREAD

**Issue by tdelmont** [merenlab/anvio#1081]
In an ideal world, anvi'o users would carefully read options and never make the mistake of generating multiple profile databases with the same SAMPLE Id prior to merging them. Such situation is problematic, and currently the only option is to re-do the profiling effort. This can be a significant burden for large metagenomic projects, and I came across this unpleasant situation recently.

One option could be to have a an anvi-script dedicated to changing the SAMPLE Id of a profile database. Thank you very much, anvi'o developer, for considering this request. 

Tom

**Comment by meren** [comment]
In the current `master` you can run this command:

```
anvi-db-info PROFILE.db --self-key sample_id --self-value NEW_SAMPLE_NAME
```

I hope this works.

**Comment by tdelmont** [comment]
Was not sure where to put it but this script saved my life, once again... 

THANK YOU MEREN

**Comment by meren** [comment]
Haha :) Thank you for pushing for it!
