### ISSUE TITLE
Not all legend options are displayed if misc-data is imported after state exists

### ISSUE THREAD

**Issue by ShaiberAlon** [merenlab/anvio#1082]
If a state is created before importing misc-data (I had the problem specifically when importing layers information (i.e. `anvi-import-misc-data -t layers`), then the legends tab doesn't show the options for the new layers (even though the new layers are seen in the interactive interface).

To reproduce this you can take any profile/pan database which already has a default state, and then import something using `anvi-import-misc-data -t layers`, start the interactive interface and go to the legends tab to search for the colors of the new misc data. If you want concrete data to work with, let me know please.

**Comment by ozcan** [comment]
Thanks for catching and reporting this @ShaiberAlon, the commit solves the issue but control flow is bit complex there, I will try to simplify it further.

**Comment by ShaiberAlon** [comment]
Thanks for solving it @ozcan .

**Comment by ShaiberAlon** [comment]
Hi @ozcan, I found another case in which this happens so I am reopening this issue. I will share the pan database with you.

**Comment by meren** [comment]
Any news on this?

**Comment by ShaiberAlon** [comment]
I'm going to close this for now because I can't reproduce it.

**Comment by ShaiberAlon** [comment]
@ozcan, I just reproduced it again. I will send you a PAN database in a separate private email.
