### ISSUE TITLE
anvi-pan-genome should include the number of singletons in the misc data table even if --min-occurrence is used

### ISSUE THREAD

**Issue by ShaiberAlon** [merenlab/anvio#1084]
Currently, if `--min-occurrence` is used (with value higher than 1), then the number of singletons is set to zero for all genomes.

**Comment by ShaiberAlon** [comment]
@meren, if this is not too hard, then I think it would be nice to have this for the next version. I added the milestone. If you don't agree, then feel free to remove.

**Comment by meren** [comment]
I thought @ozcan fixed this. @ozcan, any comment? :)

**Comment by ozcan** [comment]
I have no idea about this issue, but I can take a look at it

**Comment by ozcan** [comment]
@meren , what about `num_gene_clusters`, should it report number gene cluster per genome before filtering or after filtering?

**Comment by meren** [comment]
Great idea.

How about this to meet your suggestion: If there is filtering, we can have two metrics, `num_gene_clusters` (final number of GCs), and `num_gene_clusters_raw` (actual number of GCs before any of the filters were applied)?
