### ISSUE TITLE
Add feature to count taxonomic annotations (through Kaiju/Centrifuge) for bin(s) in interactive mode

### ISSUE THREAD

**Issue by petersonben50** [merenlab/anvio#1085]
Hello all! Thanks to Jarrod and the anvio team for developing the Kaiju parser, I’m really enjoying that, especially the breakdown of contigs within each taxonomic group (under Legends). 

I would like to request a feature that breaks down this taxonomic affiliation by the bins that are being viewed in the interactive mode. It should recalculate the values as the bins are refined further. I think this would prove a convenient tool to people who are trying to decide if certain clusters belong with a bin or not, or just want to get a feel for what their bin might be related to without mousing over each contig. 

Thanks again!

**Comment by meren** [comment]
Hi @petersonben50,

We thought about this request today and will try to address it under #1099 :)

Best wishes,
