### ISSUE TITLE
anvi-import-taxonomy-for-layers error using krakenuniq output

### ISSUE THREAD

**Issue by jarrodscott** [merenlab/anvio#1086]
As some of you know, krakenhll in now krakenuniq (https://github.com/fbreitwieser/krakenuniq). If you set up the kraken DB like I did using something like `krakenuniq-download --db DB --taxa "archaea,bacteria,viral,fungi,protozoa"` you will of course get fungi in the db.

Next, you classify using `krakenuniq` and `krakenuniq-mpa-report` to generate the report to use to import to layers in anvio. If you have any fungi you will get an extra kingdom level as in `d__Eukaryota|k__Fungi| etc.`. So instead of at most 7 taxonomic levels (d__*|p__*|c__*|o__*|f__*|g__*|s__*) kraken throws in a 8th for fungi (k__*).

`anvi-import-taxonomy-for-layers` will trip on this and throw a `IndexError: list index out of range` error. I cannot say for sure if this is the problem but when I get rid of say the species rank for fungi in the `krakenuniq-mpa-report`, `anvi-import-taxonomy-for-layers` works just fine.

**Comment by meren** [comment]
Hey @jarrodscott, can you please send us an example report so we can see whether the parser is working properly?

Thank you :)

**Comment by jarrodscott** [comment]
here you go. I believe the offending lines are 5810-5819. This is raw. I was able to get it to work by removing `k__Fungi|` from those lines. But of course there are other lines with `k__Fungi|` but they don't seem to upset anvio.
[WAR_SCR-kraken_mpa_report.txt](https://github.com/merenlab/anvio/files/2847323/WAR_SCR-kraken_mpa_report.txt)

**Comment by meren** [comment]
Hey @jarrodscott, 

Thank you very much for sending the example file. This is now fixed in `master`, but unfortunately it didn't make it into `v5.3` which we released just a couple of days ago :(

**Comment by jarrodscott** [comment]
Nice! It works great off the master but good to know :)

**Comment by jarrodscott** [comment]
And you thought this was done :)

I just rebuilt my kraken db using these commands

`krakenuniq-download --db DB --dust  --exclude-environmental-taxa --threads $NSLOTS microbial-nt`
`krakenuniq-build --db DB --kmer-len 31 --threads $NSLOTS --taxids-for-genomes --taxids-for-sequences` 

And then tried to import the taxonomy and I got this...

```
[09 Mar 20 09:15:52 Bleep kraken stuff bloop] Processing the input data ...                                                                                              Traceback (most recent call last):
  File "/home/scottjj/github/anvio/bin/anvi-import-taxonomy-for-layers", line 118, in <module>
    main(args)
  File "/home/scottjj/github/anvio/bin/anvi-import-taxonomy-for-layers", line 55, in main
    taxonomy_dict = parser.process()
  File "/home/scottjj/github/anvio/anvio/parsers/krakenuniq.py", line 96, in process
    tax_level_described = constants.levels_of_taxonomy[num_levels_tax_entry - 1]
IndexError: list index out of range
```
Pretty sure the culprit is `k__Viridiplantae`. Not sure what thats doing in there--most of the taxa look like green algae. Anyway, on line 87 of my `krakenuniq.py` file  I changed `k__Fungi` to `k__`  and it worked just fine :)

**Comment by meren** [comment]
hey @jarrodscott :) Would you mind sharing with me the contigs database and the file for import along with the command? :)

**Comment by meren** [comment]
(you can send a private e-mail)

**Comment by jarrodscott** [comment]
You mean the profile. db? I am running `anvi-import-taxonomy-for-layers` like so....

```anvi-import-taxonomy-for-layers -p WAM_SIS/PROFILE.db --parse krakenuniq -i WAM_SIS-kraken_mpa_report2.txt```

**Comment by meren** [comment]
aha. sure :)

**Comment by meren** [comment]
This is what I got but using `master` and `v6.1`:

I wonder if you sent me the fixed file :)

```
anvi-import-taxonomy-for-layers -p PROFILE.db --parse krakenuniq -i WAM_SIS-kraken_mpa_report.txt

Total num hits found .........................: 10,377
Total num non-zero-count hits ................: 10,377
* 3 entries added into layers additional data as data group 't_domain'
* 39 entries added into layers additional data as data group 't_phylum'

WARNING
===============================================
A total of 1047 taxon names, which made up 6.81% of the input data altogether
were excluded from this import due to the min abundance criterion of 0.1% for
inclusion.

* 49 entries added into layers additional data as data group 't_class'

WARNING
===============================================
A total of 1281 taxon names, which made up 7.81% of the input data altogether
were excluded from this import due to the min abundance criterion of 0.1% for
inclusion.

* 106 entries added into layers additional data as data group 't_order'

WARNING
===============================================
A total of 1940 taxon names, which made up 12.19% of the input data altogether
were excluded from this import due to the min abundance criterion of 0.1% for
inclusion.

* 119 entries added into layers additional data as data group 't_family'

WARNING
===============================================
A total of 2370 taxon names, which made up 16.04% of the input data altogether
were excluded from this import due to the min abundance criterion of 0.1% for
inclusion.

* 124 entries added into layers additional data as data group 't_genus'

WARNING
===============================================
A total of 3975 taxon names, which made up 25.52% of the input data altogether
were excluded from this import due to the min abundance criterion of 0.1% for
inclusion.

* 107 entries added into layers additional data as data group 't_species'

WARNING
===============================================
A total of 8552 taxon names, which made up 32.75% of the input data altogether
were excluded from this import due to the min abundance criterion of 0.1% for
inclusion.
```

**Comment by jarrodscott** [comment]
hum. one second. I too am using `master`

**Comment by meren** [comment]
BY THE WAY, I think you should also try `anvi-estimate-genome-taxonomy` program to import taxonomy information for layers just to see how it compares :)

For instance, this is what I run on Infant Gut dataset;

```
anvi-estimate-genome-taxonomy -p PROFILE.db -c CONTIGS.db --compute-scg-coverages --metagenome-mode --update-profile-db-with-taxonomy
```

And this is what I get in `Layers`:

![image](https://user-images.githubusercontent.com/197307/76221215-bed19500-61e6-11ea-9b01-35b783f0ae81.png)

:)

**Comment by jarrodscott** [comment]
But I didn't fix the file. I messed with the script. 

Oh! good call!

**Comment by meren** [comment]
I found the bug :) I hope this fixes it for you in `master`.

**Comment by jarrodscott** [comment]
That is exactly what I did to fix the problem :) Thanks Meren

**Comment by meren** [comment]
Ah, just saw it:

> Pretty sure the culprit is `k__Viridiplantae`. Not sure what thats doing in there--most of the taxa look like green algae. Anyway, on line 87 of my krakenuniq.py file I changed `k__Fungi` to `k__` and it worked just fine :)

I wish you sent a pull request :)

**Comment by meren** [comment]
I mean, I of course read it, but it didn't register until I saw it in the code myself .. and by then I had already forgotten that I read this here and thought that it was a weird deja vu.

**Comment by jarrodscott** [comment]
haha! I am still working on  understanding the whole github thing with pull requests and what not ;)
