### ISSUE TITLE
Display helpful error when there is a duplicate in the samples.txt file

### ISSUE THREAD

**Issue by efogarty11** [merenlab/anvio#1097]
```
Anvi'o version ...............................: margaret (v5.2-master)
Profile DB version ...........................: 31
Contigs DB version ...........................: 12
Pan DB version ...............................: 13
Genome data storage version ..................: 6
Auxiliary data storage version ...............: 2
Structure DB version .........................: 1
```

@ShaiberAlon this is the issue you asked me to submit. I tried to run a metagenomics snakemake workflow in references mode. I got this error:
![screen shot 2019-02-08 at 10 13 32 am](https://user-images.githubusercontent.com/38365171/52491484-d75b2000-2b8c-11e9-9001-1cf1cb03f757.png)
which I didn't realize meant that I had a duplicate in my samples.txt file. You said that you wanted to include a helpful error to tell people that this is why they were seeing this error. 

Thank you! The path and command I ran are on slack :)

**Comment by ShaiberAlon** [comment]
closed via #1105. Thank you @efogarty11 for reporting this.
