### ISSUE TITLE
Error while trying to rotate items tree at the root node

### ISSUE THREAD

**Issue by ShaiberAlon** [merenlab/anvio#1101]
![image](https://user-images.githubusercontent.com/17661044/52500546-ded9f380-2ba3-11e9-9701-db850f065f59.png)

**Comment by ozcan** [comment]
Hey Alon, I wanted to fix this before the release but could not reproduce it. On main tree, selections/right click menu disabled by design, and on the layers additional tree rotate works. Do you mind sharing the project with me on slack?

**Comment by meren** [comment]
Is this now fixed?

**Comment by ozcan** [comment]
@ShaiberAlon, I can not reproduce this on the project you have shared. This might be related to the bug you have reported a while ago where the root node label gets replaced with `base64.....` after re-rooting, so it would be impossible to rotate after that. It should be fixed now but if you see this problem again, please re-open, I am closing this for now.

**Comment by ShaiberAlon** [comment]
Thank you @ozcan !
