### ISSUE TITLE
missing annotations after  running anvi-gen-genomes-storage

### ISSUE THREAD

**Issue by xvazquezc** [merenlab/anvio#1108]
Hi folks,

I was trying to run a pangenomic analysis and I noticed something weird: the functional annotations from certain sources and genomes disappeared.

The pangenome contains 9 genomes, 3 from NCBI and 6 from metagenomes. But the later ones were exported into individual dbs. Therefore I included all of them as external genomes because there are no separated contig and profile dbs anymore.

All genomes except one of the derived from NCBI, were upgraded from version 8 contigs db to version 12. I tested it with anvio 5.1.0 and anvio 5.2.0, both under conda in Linux with the same results.

So,  `anvi-gen-genomes-storage` detects all the annotation sources in all genomes as I expected:

```bash
$ anvi-gen-genomes-storage -e genomes.tsv -o ANME2D-GENOMES.db

WARNING
===============================================
Good news! Anvi'o found all these functions that are common to all of your
genomes and will use them for downstream analyses and is very proud of you:
'InterPro, ProSitePatterns, TIGRFAM, Pfam, SUPERFAMILY, CDD, GO, Hamap,
ProSiteProfiles, PANTHER, SFLD, PRINTS, COG_FUNCTION, COG_CATEGORY, Gene3D,
PIRSF, SMART, ProDom'.

Internal genomes .............................: 0 have been initialized.                                                                                   
External genomes .............................: 9 found.                                                                                                   

PLEASE READ CAREFULLY
===============================================
Some of your genomes had gene calls identified by gene callers other than the
gene caller anvi'o used, which was set to 'prodigal' either by default, or
because you asked for it. The following genomes contained genes that were not
processed (this may be exactly what you expect to happen, but if was not, you
may need to use the `--gene-caller` flag to make sure anvi'o is using the gene
caller it should be using): Methanoperedens_ferrireducens (1 gene calls by
"Ribosomal_RNAs").

                                                                                                                                                           
* LFW_24 is stored with 3,234 genes (154 of which were partial)
* LFW_280_1_1 is stored with 2,033 genes (322 of which were partial)                                                                                       
* LFW_280_2_2 is stored with 2,534 genes (391 of which were partial)                                                                                       
* LFW_280_3_1 is stored with 3,546 genes (133 of which were partial)                                                                                       
* LFW_280_3_2 is stored with 2,983 genes (79 of which were partial)                                                                                        
* LFW_280_4 is stored with 2,917 genes (145 of which were partial)                                                                                         
* Methanoperedens_ferrireducens is stored with 2,988 genes (38 of which were partial)                                                                      
* Methanoperedens_nitroreducens is stored with 3,375 genes (9 of which were partial)                                                                       
* Methanoperedens_sp_BLZ1 is stored with 4,530 genes (599 of which were partial)                                                                           

The new genomes storage ......................: ANME2D-GENOMES.db (v6, signature: hashfe0c8ff1)
Number of genomes ............................: 9 (internal: 0, external: 9)
Number of gene calls .........................: 28,140
Number of partial gene calls .................: 1,870
```

However, if I look inside the genomes storage db, all my MAGs got stripped from any annotations aside of COG.

```
$ sqlite3 ANME2D-GENOMES.db -header
SQLite version 3.24.0 2018-06-04 19:24:41
Enter ".help" for usage hints.
sqlite> SELECT DISTINCT source from gene_function_calls WHERE genome_name = 'LFW_24';
source
COG_FUNCTION
COG_CATEGORY
sqlite> SELECT DISTINCT source from gene_function_calls WHERE genome_name = 'Methanoperedens_ferrireducens';
source
InterPro
SUPERFAMILY
GO
COG_FUNCTION
COG_CATEGORY
Gene3D
ProSiteProfiles
ProSitePatterns
TIGRFAM
Pfam
CDD
PANTHER
PRINTS
SFLD
SMART
ProDom
PIRSF
Hamap
```

On top of that, the `gene_callers_id` were resetted, i.e. they were re-numbered and they don't match the original `gene_callers_id` from their individual dbs:

```
$ sqlite3 ANME2D-GENOMES.db
sqlite> select max(gene_callers_id ) from gene_function_calls WHERE genome_name = 'LFW_24';
max(gene_callers_id )
3233

$ sqlite3 genomes/LFW_Bin_00024.db
sqlite> select max(gene_callers_id ) from gene_functions ;
max(gene_callers_id )
1363304
```

Any idea about what could be happening?

Cheers,
Xabi

**Comment by meren** [comment]
This is very interesting (and a bit concerning). First of all, the gene calls should never change :/ I have no idea how/why is that happening. And we would need to find out when the common functions to all genomes are being dropped.

How can we recapitulate this? Would you mind sending your contigs databases and the genome storage to @ozcan and I through a Dropbox download so we can play?

Apologies for the frustration, and thanks for the report.


Best,

**Comment by xvazquezc** [comment]
I just shared the files with both of you.
Cheers,

**Comment by meren** [comment]
Hey @xvazquezc, 

Thank you very much for sharing them. I did some tests.

There is definitely something wrong with the functions tables of your bins. Take `LFW_Bin_00024.db`. The number of gene calls in this contigs database differ for different tables:

``` bash
 $ sqlite3 LFW_Bin_00024.db 'select MAX(gene_callers_id) from genes_in_contigs'
   3233

 $ sqlite3 LFW_Bin_00024.db 'select MAX(gene_callers_id) from gene_functions'
1363304
```

Function calls until `3233` only includes COGs:

```
 $ sqlite3 LFW_Bin_00024.db 'select DISTINCT(source) from gene_functions where gene_callers_id < 3233'
COG_FUNCTION
COG_CATEGORY
```

In contrast, gene calls after 3233 seems to be including all others but COGs:

```
 $ sqlite3 LFW_Bin_00024.db 'select DISTINCT(source) from gene_functions where gene_callers_id > 3233'
CDD
Gene3D
GO
Hamap
InterPro
PANTHER
Pfam
PIRSF
PRINTS
ProDom
ProSitePatterns
ProSiteProfiles
SFLD
SMART
SUPERFAMILY
TIGRFAM
```

I have some questions. The bins you have .. are they coming from `anvi-split`?  Did you import functions from InterPro to the mother contigs database? If they are not coming from `anvi-split`, can you double-check InterPro file to make sure gene caller ids match to what you expect to see? The funny thing is there is no problem with the genomes you have downloaded from the NCBI.

A note for myself and @ozcan, `gene_functions` table should never include function entries `gene_callers_id`s of which are missing in `genes_in_contigs`.

A second note for us to think: when anvi'o says "these functions match across all contigs dbs, it in fact does not attempt to make sure entries with those function names in fact have gene caller ids that are relevant to the gene calls stored in that contigs database. we could do that, but it would be a significant performance bottleneck. instead, perhaps we can reject function calls during import if gene call doesn't match (in which case probably there something even worse going on, because it is likely that the user is importing functions that are quite irrelevant to the contigs database).


Thank you!

**Comment by xvazquezc** [comment]
I think the bins derive from `anvi-split` (it's been a while...). Indeed the `gene_callers_id` from the bin don't match the InterProScan IDs. So, does `anvi-split` resets the gene numbering automatically?

Weird thing that I was allowed to import annotations for genes not present in the contigs db.

**Comment by meren** [comment]
> Weird thing that I was allowed to import annotations for genes not present in the contigs db.

Did you import these functions into the main contigs db from which you split these guys, or did you import functions into individual split contigs databases?

**Comment by xvazquezc** [comment]
I imported the functions into the individual split databases. But I ran IPS on the protein files exported directly from the main `contigs.db`.

I found the old master `contigs.db` and after importing the annotations into it and running my bins as internal genomes, it worked without a problem. I had to migrate all dbs to the new versions but aside of that all very straight forward.
