### ISSUE TITLE
anvi-export-items-order is missing

### ISSUE THREAD

**Issue by ShaiberAlon** [merenlab/anvio#1109]
There is an `anvi-import-items-order`, and also there is a way to edit AND SAVE into the pan/profile database the items tree in the interactive interface. What is missing is an `anvi-export-items-order` so that a tree that was edited (and saved) in the interatvie session would later be exported from the database.

@ozcan, are you willing to implement such a thing? it would be very helpful because I edit a tree in the interactive, but then when I want to create a reproducible workflow for it I can't...

**Comment by meren** [comment]
this now exists.
