### ISSUE TITLE
anvi-compute-ani puts alignment coverage as 1 whenever percent identity is 0?

### ISSUE THREAD

**Issue by ShaiberAlon** [merenlab/anvio#1110]
This is a minor issue:
I used anvi-compute-ani with `--method ANIm`, and I notice that whenever the percent identity is 0 then the alignment coverage is 1. That doesn't make sense to me... I think if the percent identity is 0 then alignment coverage should also be 0.

**Comment by ozcan** [comment]
Hmm, if this is the case in output files we get from PyANI, this needs to be solved on upstream.

**Comment by ShaiberAlon** [comment]
That's a good point @ozcan. I will take a look.

**Comment by meren** [comment]
Any updates, @ShaiberAlon?
