### ISSUE TITLE
anvi-compute-ani memory usage with internal genomes

### ISSUE THREAD

**Issue by xvazquezc** [merenlab/anvio#1112]
Hi there,

I ran `anvi-compute-ani` on my pangenome using only external genomes and `-T 4` without problem (9 genomes in total). After fixing the reported issue with the numbering of the `gene_callers_id` (see #1108) by using my bins as internal genomes, `anvi-compute-ani` could not be completed due to lack of memory.

My master `contigs.db` is rather big and even with 32GB of memory it isn't able to fulfil the task even when limited to a single thread. I don't know if it's because anvi'o might be loading the whole `contigs.db` in the memory instead of just loading the required bins...

If this is the intended way of working, seems to be rather wasteful in terms of resources, especially when pyani is intended to work with rather modest computational resources.

Cheers,
Xabi

**Comment by meren** [comment]
Aha! Great catch, @xvazquezc. Thank you.

@ozcan, can you please consider testing this with the INFANT-GUT-DATASET? If we are not running ANI calculations only with contigs relevant to internal genome bins, that is a bug we need to fix :)

(and maybe after this fix we can try the `anvi-upgrade` magic :)).

**Comment by ozcan** [comment]
@meren I have tested this and calculations are correct, it exports the correct sequence. The problem here is that in order to avoid re-summarizing and wasting time I cache summaries of collections for internal genomes. This is a huge issue if the contigs database is big. I am going to optimize this.

**Comment by meren** [comment]
This is great, @ozcan. Thank you very much for looking into the optimization issue.

**Comment by ozcan** [comment]
Thank you for reporting @xvazquezc, this is now fixed and `anvi-compute-ani` has constant memory usage. However, I am not so sure about the scenario in which contigs database is much larger than the memory, please let us know.
![image](https://user-images.githubusercontent.com/940884/53587422-eb70bc80-3b4f-11e9-9b6f-6d3eba6c2fc8.png)
(black: old, blue: new)

**Comment by meren** [comment]
🥇

**Comment by xvazquezc** [comment]
I just wanted to let you know that I was able to run the same data locally after @ozcan code mods (using anvi'o 5.4.0). It still peaked at 12.8GB with 6 internal + 4 external genomes, but it is way better than before.

As reference, the pangenome db in use is 8.3MB and the `contigs.db`, 630MB. I ran pyANI standalone for reference and all processes add up to <1GB.
