### ISSUE TITLE
anvi-gen-genomes-storage imports incorrect genome_info for internal genomes

### ISSUE THREAD

**Issue by xvazquezc** [merenlab/anvio#1113]
Hi again,

I don't think this is expected but the `num_contigs` and `num_splits` from the `genome_info` of the `GENOMES.db` has the info from the db they derive not the info of the bins themselves.

Probably a minor thing though. All the other info in the whole `GENOMES.db` seems right.

Cheers,
Xabi

**Comment by xvazquezc** [comment]
PS:
```
sqlite> SELECT genome_name, num_contigs, num_splits from genome_info ;
genome_name  num_contigs  num_splits
-----------  -----------  ----------
LFW_24       187416       197263    
LFW_280_1_1  187416       197263    
LFW_280_2_2  187416       197263    
LFW_280_3_1  187416       197263    
LFW_280_3_2  187416       197263    
LFW_280_4    187416       197263    
Methanopere  59           582       
Methanopere  10           641       
Methanopere  514          921       

```

**Comment by meren** [comment]
Excellent report. Thank you very much for catching this and reporting it.


Best,

**Comment by ozcan** [comment]
Thank you @xvazquezc for the detailed report! This is now fixed on master.
