### ISSUE TITLE
How does completeness/redundancy relate to checkm completeness/contamination?

### ISSUE THREAD

**Issue by johanneswerner** [merenlab/anvio#1118]
(I think this is a technical issue)

How do the values of completeness/redundancy that I get via anvi'o relate to what I receive when I analyze my bins in an analysis with checkm for completeness/contamination?

I find **huge** differences (I have refined my bins and analyzed the refined bins with anvi'o and checkm). I can share the entire table, but just to give one example. 

| bin | anvi'o completeness | anvi'o redundancy | checkm completeness | checkm contamination |
|--|--|--|--|--|
| Bin_68 | 8.4 | 6.0 | 100.00 | 214.66 |

Can you help me out? Is here something wrong with my data, or are these not comparable concepts? After reading #177 I thought these were comparable. Any input would be highly appreciated.

```
anvi-self-test --version
Anvi'o version ...............................: margaret (v5.4)
Profile DB version ...........................: 31
Contigs DB version ...........................: 12
Pan DB version ...............................: 13
Genome data storage version ..................: 6
Auxiliary data storage version ...............: 2
Structure DB version .........................: 1
```

**Comment by johanneswerner** [comment]
Okay, a quick check on the rest of the bins revealed that this issue does not seem to occur with high quality bins, but I still would like to understand what is going on here.

**Comment by tdelmont** [comment]
Hi,

This relates to ongoing bug reports regarding domain anvi'o considers for
reporting completion/redundancy.
It is likely that anvi'o considered Eukarya as the domain for this
contaminated bin, which resulted is low scores for both completion and
redundancy.

Such bug indeed does not occur for bins corresponding to sufficiently
complete genomes from any of the 3 domains of life.

Tom

**Comment by tdelmont** [comment]
To clarify, checkM only works with Bacteria and Archaea. Anvi'o is now also compatible with eukaryotes and random forest is used to decide which domain to consider (Bacteria versus Archaea versus Eukarya) based on the occurence of single copy core genes from 3 distinct collections. The random forest strategy is currently being improved by Meren, and bug you reported will hopefully be soon resolved, allowing better assessment of completion/redundancy even when bins are highly contaminated.

Tom

**Comment by johanneswerner** [comment]
Ah, that is great, thank you for your help and all your explanations.

**Comment by meren** [comment]
Tom is correct. In addition we hope that we will address this with `v6.0`.
