### ISSUE TITLE
Determining which genes were excluded in phylogenomic concatenation

### ISSUE THREAD

**Issue by jcthrash** [merenlab/anvio#1120]
```
$ anvi-self-test --version
Anvi'o version ...............................: margaret (v5.3)
Profile DB version ...........................: 31
Contigs DB version ...........................: 12
Pan DB version ...............................: 13
Genome data storage version ..................: 6
Auxiliary data storage version ...............: 2
Structure DB version .........................: 1
```

I've been running the phylogenomics tutorial here:
```
http://merenlab.org/2017/06/07/phylogenomics/
```

It seems to be working great, although it's a little challenging to determine which genes are getting excluded from the concatenation. I can manually compare the header list from the first line of the concatenated alignment file with the overall list, but it would be very convenient if Anvi'o could list not just the genes that were kept in the concatenated alignment, but also the genes that removed, possibly as part of STDOUT.

Thanks!

**Comment by meren** [comment]
(I looked at this, realized that it is much more challenging than I though given the complexity of the design of that part of the code, but will get back to it again at some point).
