### ISSUE TITLE
Problem with CONCOCT

### ISSUE THREAD

**Issue by andressanchez1** [merenlab/anvio#1128]
=============================================
PLEASE READ THIS BEFORE SUBMITTING YOUR ISSUE
=============================================

Read the following text carefully, and remove it before submitting your issue.

THIS *IS* A TECHNICAL ISSUE
---------------------------------------------
We thank you in advance for your report. Please take a look at the items down below:

 * If this is a technical issue, please run the command `anvi-self-test --version` in your terminal and paste the output at the beginning of your report. If you fail to do this we will likely close the issue without addressing it, and wait for someone else to report it :(
 
 * Paste your `anvi-self-test --version` output as well as other logs in between ``` characters like this:
 
     ```
     Many many lines
     coming from your logs
Anvi'o version ...............................: 2.3.2
Profile DB version ...........................: 20
Contigs DB version ...........................: 8
Pan DB version ...............................: 5
Samples information DB version ...............: 2
Genome data storage version ..................: 1
Auxiliary data storage version ...............: 3
Anvi'server users data storage version .......: 1

     ```
     
 * If you are not sure about your formatting, you can always use the 'Preview' button to see how youre message will look like upon submission.

 * If this is a technical issue, please mention which operating system you are using, and how did you install anvi'o. Copy-paste exact command lines you used before observing the error.
I am using anvio 2.3.2 and this was the command before the error :+1: 
anvi-merge *ANVIO_PROFILE/PROFILE.db -o MERGED-SAMPLES -c anvio-contigs.db --enforce-hierarchical-clustering
this is the error:
WARNING
===============================================
The CONCOCT module could not be imported :( Anvi'o will still be able to perform
the merging, however, the unsupervised binning results will not be available to
you in the resulting merged profile database. This is what the module was upset
about: '''libgsl.so.19: cannot open shared object file: No such file or
directory''', in case you would like to fix this problem.

 
 * We may need example files to reproduce your issue. Best issues have files to reproduce them. If this is applicable to your case, please make those files available in advance and include direct download links (Dropbox or Google Drive could help).

 * If this is a feature request, please do not forget to include why do you think the community may benefit from the addition of the proposed feature to anvi'o.

THIS IS *NOT* A TECHNICAL ISSUE
---------------------------------------------
That's OK. We are more than happy to help. But GitHub Issues is not the right place for those questions. Instead, please use our Slack channel, or anvi'o Google Groups to send your question. You can get an invitation to our Slack channel from here: https://slackin-ezbpfhwsmh.now.sh/

Thanks,

**Comment by meren** [comment]
FFS.
