### ISSUE TITLE
anvi-interactive error - KeyError: 'eukarya'

### ISSUE THREAD

**Issue by watsonar** [merenlab/anvio#1132]
```
Anvi'o version ...............................: margaret (v5.4-master)
Profile DB version ...........................: 31
Contigs DB version ...........................: 12
Pan DB version ...............................: 13
Genome data storage version ..................: 6
Auxiliary data storage version ...............: 2
Structure DB version .........................: 1
```
When I try to run an anvi-interactive command which I have successfully run in the past, I get the following error:
```
raceback (most recent call last):
  File "/groups/merenlab/virtual-envs/anvio-master/anvio/bin/anvi-interactive", line 105, in <module>
    d = interactive.Interactive(args)
  File "/groups/merenlab/virtual-envs/anvio-master/anvio/anvio/interactive.py", line 206, in __init__
    self.load_collection_mode()
  File "/groups/merenlab/virtual-envs/anvio-master/anvio/anvio/interactive.py", line 850, in load_collection_mode
    p_completion, p_redundancy, domain, domain_confidence, results_dict = completeness.get_info_for_splits(set(self.collection[bin_id]))
  File "/groups/merenlab/virtual-envs/anvio-master/anvio/anvio/completeness.py", line 316, in get_info_for_splits
    best_matching_domain, domain_matching_confidence, info_text = self.get_best_matching_domain(results_dict, observed_genes_per_domain)
  File "/groups/merenlab/virtual-envs/anvio-master/anvio/anvio/completeness.py", line 159, in get_best_matching_domain
    domain_cr[domain] = {'percent_completion': d[domain][source]['percent_completion'],
KeyError: 'eukarya'
```
The command I am using is this:
```
anvi-interactive -c 03_CONTIGS/CP-contigs.db -p 07_MERGED_RERUN_KRAKEN_ACTUAL_FINAL/CP/PROFILE.db -t CP_MAGs_detection_FINAL.newick -C CP_MAGs_collection
```

I am getting this error both on my computer and on barhal, and will comment on this issue in Slack with the working directory from which to run this command.

@meren Özcan said this might be related to some stuff you have been working on recently.

You guys are my heroes! :)

Andrea

**Comment by meren** [comment]
@ozcan is right. this it totally on me :) thanks for reporting.

**Comment by meren** [comment]
3 hours and still working on it ... but it is good because this forced me to change the design a bit.

You get an error because your contigs database is too old and does not have BUSCO HMMs. But it shouldn't explode things like this.

To prevent such issues I'm changing the design, which will also address what @tdelmont had complained about on Slack about having to run all SCG domain HMMs on contigs databases even when you don't need some of them.

**Comment by meren** [comment]
OK. @watsonar, can you please try again and let me know if it is now working?

@ozcan, I hope we can spend 2 minutes sometime tomorrow to revamp the Bins panel. we are now sending some extra information that can be shown in the completion panel :)

**Comment by meren** [comment]
@tdelmont, with this change `master` should not complain about missing HMMs for SCGs and still give a reasonable C/R estimate for bins. let me know if you test it and found a problem.

**Comment by watsonar** [comment]
@meren I tried again and it worked this time, thank you! However, @efogarty11 seems to be getting the same error now but with anvi-summarize. :(

**Comment by efogarty11** [comment]
This is the command I ran: 
```bash
anvi-summarize -p 06_MERGED/SWE_0019M_000D/PROFILE.db -c 03_CONTIGS/SWE_0019M_000D-contigs.db -o summarize/ -C CONCOCT
```
In this directory: `/storage2/tmp/analysis/GUT_PLASMIDS/fin_swe_infant_pBI143/swe0019_assembly`

And this is the error I got:
```Contigs DB ...................................: Initialized: 03_CONTIGS/SWE_0019M_000D-contigs.db (v. 12)

WARNING
===============================================
ProfileSuperClass found a collection focus, which means it will be initialized
using only the splits in the profile database that are affiliated with the
collection CONCOCT and all bins it describes.

Auxiliary Data ...............................: Found: 06_MERGED/SWE_0019M_000D/AUXILIARY-DATA.db (v. 2)
Profile Super ................................: Initialized with 15525 of 15525 splits: 06_MERGED/SWE_0019M_000D/PROFILE.db (v. 31)
Splits taxonomy ..............................: Initiated for taxonomic level for "t_genus"
[04 Apr 19 13:45:20 [Processing "Bin_21" (1 of 56)]] Accessing completeness scores ...                                                                                                                                                       Traceback (most recent call last):
  File "/groups/merenlab/virtual-envs/anvio-master/anvio/bin/anvi-summarize", line 100, in <module>
    main(args)
  File "/groups/merenlab/virtual-envs/anvio-master/anvio/bin/anvi-summarize", line 62, in main
    summary.process()
  File "/groups/merenlab/virtual-envs/anvio-master/anvio/anvio/summarizer.py", line 1147, in process
    self.summary['collection'][bin_id] = bin.create()
  File "/groups/merenlab/virtual-envs/anvio-master/anvio/anvio/summarizer.py", line 1498, in create
    self.access_completeness_scores()
  File "/groups/merenlab/virtual-envs/anvio-master/anvio/anvio/summarizer.py", line 1529, in access_completeness_scores
    p_completion, p_redundancy, domain, domain_probabilities, info_text, results_dict = self.summary.completeness.get_info_for_splits(set(self.split_names))
  File "/groups/merenlab/virtual-envs/anvio-master/anvio/anvio/completeness.py", line 316, in get_info_for_splits
    percent_completion = scg_hmm_hits[best_matching_domain][source]['percent_completion']
KeyError: 'BUSCO_83_Protista'
```
It won't let me summarize, but it also means that when I open the interactive interface to bin it won't give me completion and redundancy for the things I'm binning.

**Comment by watsonar** [comment]
I'm getting another "KeyError", this time with anvi-inspect. I thought maybe because of the similarity to the above errors it might be relevant to this issue, but I have never run this command before so it might be something on my end.

Command is this:
```bash
anvi-inspect -c 03_CONTIGS/CP-contigs.db -p 07_MERGED_RERUN_KRAKEN_ACTUAL_FINAL/CP/PROFILE.db --split-name CP_000000000386_split_00003
```

And the directory will be in a Slack comment.

**Comment by meren** [comment]
Is this still an error, @watsonar?

**Comment by watsonar** [comment]
@meren sadly yes :(

**Comment by meren** [comment]
I fixed the error, but this time it is giving an error at the interface, @watsonar. can you please take your computer and bring it to @ozcan when you have run the same command line and get a never-ending loading gif on your browser so he can see the exact line that causes this? :)

**Comment by watsonar** [comment]
@meren and @ozcan sorry it took so long for me to test this, but it works just fine for me now! :)
