### ISSUE TITLE
Pangenome analysis display error

### ISSUE THREAD

**Issue by pavlo888** [merenlab/anvio#1134]
Hi, 

I have a problem in the last step of the pan genome analysis workflow, right before displaying the results I believe. Below you can see what my log shows and then when it opens the chrome browser, it says there is an error loading the page :( 

I could send you the input I use for the analysis if necessary. 

Thanks a lot in advance. 

Cheers, 
Pablo 

``

Anvi'o version ...............................: margaret (v5.4)
Profile DB version ...........................: 31
Contigs DB version ...........................: 12
Pan DB version ...............................: 13
Genome data storage version ..................: 6
Auxiliary data storage version ...............: 2
Structure DB version .........................: 1

(anvio5) Pablos-MacBook-Air:WGS_PVA_assemblies_fasta pablovargas$ anvi-display-pan -p /Users/pablovargas/Desktop/WGS_PVA_assemblies_fasta/AGRO-PAN/Rhizogenic_Agrobacterium_Pan-PAN.db -g AGRO-GENOMES.db

Process Process-1:           
Traceback (most recent call last):
  File "/anaconda3/envs/anvio5/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/anaconda3/envs/anvio5/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/anaconda3/envs/anvio5/bin/bottle.py", line 755, in run
    run(self, **kwargs)
  File "/anaconda3/envs/anvio5/bin/bottle.py", line 3127, in run
    server.run(app)
  File "/anaconda3/envs/anvio5/bin/bottle.py", line 2805, in run
    server.start()
  File "/anaconda3/envs/anvio5/lib/python3.6/site-packages/cherrypy/wsgiserver/__init__.py", line 2006, in start
    raise socket.error(msg)
OSError: No socket could be created -- (('0.0.0.0', 8080): [Errno 48] Address already in use)

* The server is now listening the port number "8080". When you are finished, press
CTRL+C to terminate the server.

``

Thanks,

**Comment by meren** [comment]
Hi @pavlo888,

There seems to be an anvi'o server is already running as a background process that occupies port 8080. You can try to find it (by typing `fg` in all terminals until you find it) and kill it. Or you can restart your computer if you can't sort it out. Alternatively, you can run `anvi-display-pan` with an additional parameter `-P 8081`, so anvi'o would use the port number `8081`.


Best,

**Comment by pavlo888** [comment]
Hi Murat,

Thank you very much for your fast response. Just wanted to let you know
that it works.

Cheers,
Pablo
