### ISSUE TITLE
Installation with conda

### ISSUE THREAD

**Issue by leefarg** [merenlab/anvio#1137]
Sorry if I am missing something basic here...
I am trying to install anvio on a Windows 10 machine. I have successfully installed Anaconda 4.6.11.

When I try any of the following, as directed by the Installation page:
conda install -c bioconda -c conda-forge anvio
conda install -n anvio5 -c bioconda -c conda-forge anvio=5.4.0
conda create -n anvio5 -c bioconda -c conda-forge anvio=5.4.0

I get the following error:

PackagesNotFoundError: The following packages are not available from current channels:

  - anvio

Similarly, if I use conda to search for anvio:
conda search anvio

I get a similar error.

What am I missing here?? Thanks in advance!

**Comment by ozcan** [comment]
Hi @leefarg,

Even though conda claims it works on Windows, that only applies to a handful of general purpose packages. Many packages, especially in bioinformatics, are not compatible with windows. I just installed Windows on a virtual machine to test if it would be to make anvio recipe with windows but almost all dependencies I have tested was missing on anaconda windows like blast, bowtie2, prodigal. 
I think it would be more straightforward to set up a Linux-like environment on windows for you. I am going to put a tutorial link below.

All the best.

https://github.com/kapsakcj/win10-linux-conda-how-to
