### ISSUE TITLE
Concatenation with genes from different HMM sources

### ISSUE THREAD

**Issue by tdelmont** [merenlab/anvio#1153]
From Master,

So, I tried to concatenate genes from different HMM sources and got this very clear error message:

```
Config Error: If you want your genes to be concatenated, you should be requesting a single HMM
              source. Why? In fact we are not exactly sure why. But when we think of it, we
              couldn't come up with a scenario where the user might truly be interested in
              concatenating genes from multiple HMM sources, and we wanted to add a control in
              case they are making a mistake w/o realizing. If you are sure this is what you
              must do for the question you are interested in, please send an e-mail to the
              anvi'o discussion group, and convince us .. or you can just delete this if block
              to avoid this check if you are not in the mood. We know the feeling.
```

Here I am trying to convince developers to allow concatenation of genes from different HMM sources:

I use 8 HMM sources for a single gene each. This allows me to control e-value cut-off for each gene (e.g., e-10 for gene A and e-50 for gene B). As a second advantage, this allows we to visualize each gene as a layer in the interface for binning (useful to detect small targets of interest). Now I would like to move into phylogenomics with these 8 markers, and providing option to allow concatenation of genes from different HMM sources would be much appreciated.

As an alternative, I could create a single HMM source with all genes, and then the ```--return-best-hit``` option might render my efforts optimizing e-value irrelevant, however I would rather have more freedom within the platform. 

Thoughts?

Thanks for considering this,

Tom

**Comment by meren** [comment]
Important. I will look into this.

**Comment by meren** [comment]
This is done.
