### ISSUE TITLE
blastn hit ring visualize in anvio5

### ISSUE THREAD

**Issue by YU-DENG** [merenlab/anvio#1156]
Hi,

I am very impressed by the figure (Alignment of MinION long reads to pWCP) in your recent publication related  to  the pWCP.

I read the blog and found the individual blastn results were visualized in Kablammo, and my question is can anvio5 generate the blastn hit ring image like in this figure ?

Thanks a lot for the help !

![image](https://user-images.githubusercontent.com/48442578/57297010-0b4ccf80-7101-11e9-87d7-1e8b77b758d8.png)

Best regards
Yu DENG

**Comment by meren** [comment]
Dear @YU-DENG, unfortunately there is no script in anvi'o to generate similar figures. I did this semi-manually, and I wish I had extra time to put into a single, generalized program.

It is not very hard to code this functionality in reality, but given how specific it is (i.e., it will only work for a small number of BLAST hits that nearly cover the entire contig of interest), it may be reasonable to do it manually every time :)

Thank you very much for your interest,
Best wishes.
