### ISSUE TITLE
pkg_resources.DistributionNotFound: The 'portend>=2.1.1' distribution was not found and is required by cherrypy

### ISSUE THREAD

**Issue by jolespin** [merenlab/anvio#1162]
I'm working on a pipeline and would like to include `anvio` in the mix.  Unfortunately, it relies on a few tools that depend on `python2` (I use Python 3 for everything else) so I cannot upgrade to the current version of `anvio` for this environment without making things extremely complicated.  

Does anyone have any insight on how I can get this installed correctly?  I did a conda install but cherrypy is throwing errors even though portend is installed.

```
(pipeline_env) -bash-4.1$ conda install anvio
Collecting package metadata: done
Solving environment: done

## Package Plan ##

  environment location: /usr/local/devel/ANNOTATION/jespinoz/anaconda/envs/pipeline_env

  added / updated specs:
    - anvio


The following NEW packages will be INSTALLED:

  anvio              bioconda/linux-64::anvio-2.1.0-py27_0
  cherrypy           conda-forge/linux-64::cherrypy-17.3.0-py27_1
  portend            conda-forge/noarch::portend-2.2-py_0


Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
(pipeline_env) -bash-4.1$ anvi-profile --version
Traceback (most recent call last):
  File "/usr/local/devel/ANNOTATION/jespinoz/anaconda/envs/pipeline_env/bin/anvi-profile", line 4, in <module>
    __import__('pkg_resources').run_script('anvio==2.1.0', 'anvi-profile')
  File "/usr/local/devel/ANNOTATION/jespinoz/anaconda/envs/pipeline_env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3191, in <module>
    @_call_aside
  File "/usr/local/devel/ANNOTATION/jespinoz/anaconda/envs/pipeline_env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3175, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/devel/ANNOTATION/jespinoz/anaconda/envs/pipeline_env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3204, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/devel/ANNOTATION/jespinoz/anaconda/envs/pipeline_env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 585, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/local/devel/ANNOTATION/jespinoz/anaconda/envs/pipeline_env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 598, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/local/devel/ANNOTATION/jespinoz/anaconda/envs/pipeline_env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'portend>=2.1.1' distribution was not found and is required by cherrypy
```

**Comment by xvazquezc** [comment]
For what I see it's trying to install anvi'o v2 because you have Python 2.7 in your environment. Note that anvi'o 2 is really old and lacks of many of the current tools available. Also, all later versions of anvi'o use Python 3, so I don't know if it would be more appropriate to switch your env to Python 3...

Some programs work well from outside the environment if you give the full path. You may want to look into that

**Comment by jolespin** [comment]
Do you know of any ways to get python2 and python3 in the same conda environment?

**Comment by jolespin** [comment]
Also, how do you get around using `checkm` if `anvio` uses `python3`?

**Comment by xvazquezc** [comment]
I don't even know if it's even possible to have a single conda environment with both Python versions. The idea is having isolated environments after all.

AFAIK anvi'o does not run CheckM, it uses it's own SCG libraries for C/R estimates. I think you can import some of the CheckM output but that's run separately.

**Comment by jolespin** [comment]
Good to know.  I can hack something up in the meantime.  Right now, `checkm` is the limiting factor to extending the pipeline out.  They are working on a Python3 compatible version but it may not be out until next year.

**Comment by meren** [comment]
Dear @jolespin, as @xvazquezc anvi'o `v2.1` is very very old at this point. We are at `v5.5`. I hope you can solve this by using multiple virtual environments for different Python versions and switch between them depending on the analysis step.

I am closing this issue for now as there is nothing to address on anvi'o side as far as I can see, but we can continue the discussion.


Best,

PS: I sent you an e-mail a while ago, did you get it? If not, can you please send me an e-mail so I have your e-mail address?
