### ISSUE TITLE
Anvio merging error due to profiling issue

### ISSUE THREAD

**Issue by themarczi** [merenlab/anvio#1163]
Tryting to see what went wrong...
These are the steps i toke.
1- cat *.fasta > Pseudo.fasta
2- anvi-script-reformat-fasta Pseudo.fasta -o Pseudo1.fasta -l 0 --simplify-names
3- anvi-gen-contigs-database -f Pseudo1.fasta -o Pseudo.db
4- anvi-run-hmms -c Pseudo.db
5- anvi-run-ncbi-cogs -c Pseudo.db
6- 
anvi-init-bam SAMPLE-01.bam -o PSAMPLE-01.bam

anvi-init-bam SAMPLE-02.bam -o PSAMPLE-02.bam

anvi-init-bam SAMPLE-03.bam -o PSAMPLE-03.bam

anvi-init-bam SAMPLE-04.bam -o PSAMPLE-04.bam

anvi-init-bam SAMPLE-05.bam -o PSAMPLE-05.bam

anvi-init-bam SAMPLE-06.bam -o PSAMPLE-06.bam

anvi-init-bam SAMPLE-07.bam -o PSAMPLE-07.bam

anvi-init-bam SAMPLE-08.bam -o PSAMPLE-08.bam

anvi-init-bam SAMPLE-09.bam -o PSAMPLE-09.bam

anvi-init-bam SAMPLE-10.bam -o PSAMPLE-10.bam

anvi-init-bam SAMPLE-11.bam -o PSAMPLE-11.bam

anvi-init-bam SAMPLE-12.bam -o PSAMPLE-12.bam

anvi-init-bam SAMPLE-13.bam -o PSAMPLE-13.bam

anvi-init-bam SAMPLE-14.bam -o PSAMPLE-14.bam

anvi-init-bam SAMPLE-15.bam -o PSAMPLE-15.bam

anvi-init-bam SAMPLE-16.bam -o PSAMPLE-16.bam

**Untill now alll is okay,, step 7 is where thing start to go wrong, each process takes a few seconds, even though it must take much more time...**

7- for x in *.bam
do
	anvi-profile -i $x -M 1000 -c Pseudo.db
done
8-anvi-merge */PROFILE.db -o SAMPLES-MERGED -c Pseudo.db
→ Config Error: There is something wrong with your input databases. The group name 'default'   
              should be common to all of them, but it doesn't seem to be the case :/ How did 
              you end up with an anvi'o single profile database that doesn't have the        
              'default' group in its additional layer data table? It is very likely that your
              profiling step failed for some reason for one or more of your databases :(  
8- To check:
(anvio5) marczi@Minux:~/Desktop/Pseudo-final-fasta$ cd SAMPLE-01.bam-ANVIO_PROFILE
(anvio5) marczi@Minux:~/Desktop/Pseudo-final-fasta/SAMPLE-01.bam-ANVIO_PROFILE$ anvi-show-misc-data -p profile.db

File/Path Error: No such file: 'profile.db' :/

(anvio5) marczi@Minux:~/Desktop/Pseudo-final-fasta/SAMPLE-01.bam-ANVIO_PROFILE$ anvi-show-misc-data -p PROFILE.db

* There are no additional data for 'items' in this database :/

* There are no additional data for 'layers' in this database :/

* There are no additional data for 'layer_orders' in this database :/

**I do not know what i am doing wrong...**

**Comment by meren** [comment]
> I do not know what i am doing wrong...

I am sure one of the things you are doing wrong is not reading the questionnaire that shows up when you click the "new issue" button so we have a better idea about your anvi'o installation, etc.

**Comment by themarczi** [comment]
'''
(anvio5) marczi@Minux:~/Desktop/Pseudo-final-fasta/SAMPLE-01.bam-ANVIO_PROFILE$ anvi-self-test --version
Anvi'o version ...............................: margaret (v5.5)
Profile DB version ...........................: 31
Contigs DB version ...........................: 12
Pan DB version ...............................: 13
Genome data storage version ..................: 6
Auxiliary data storage version ...............: 2
Structure DB version .........................: 1
'''

OS: Linux Minux 4.18.0-10-generic #11-Ubuntu SMP Thu Oct 11 15:13:55 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

Installation process: 
conda create -y --name anvio5 python=3.6
conda install -y --name anvio5 -c bioconda -c conda-forge anvio=5.5.0

**Comment by meren** [comment]
Do you see anything in the output messages of `anvi-profile` step (step 7)? Can you copy paste one of the `anvi-profile` output?

**Comment by themarczi** [comment]
I sent the files to you by email because i couldnt upload .db files here..

**Comment by meren** [comment]
When I try to profile the sample you sent me, this is the error I get from anvi'o:

```
Config Error: At least one contig name in your BAM file does not match contig names stored in
              the contigs database. For instance, this is one contig name found in your BAM
              file: 'NZ_CP010555.1', and this is another one found in your contigs database:
              'c_000000018616'. You may be using an contigs database for profiling that has
              nothing to do with the BAM file you are trying to profile, or you may have
              failed to fix your contig names in your FASTA file prior to mapping, which is
              described here: http://goo.gl/Q9ChpS
```

I think this is an issue on your end that could be resolved by following the tutorial a bit more carefully.
