### ISSUE TITLE
Feature to make png (or equivalent) version of the inspect page from the command line

### ISSUE THREAD

**Issue by efogarty11** [merenlab/anvio#1170]
This is a feature request. I am visualizing mapping from a ton of metagenomes (+2000) and it takes a very long time to load the interactive interface, and then from there takes a long time to inspect a split. I talked to Meren yesterday about the possibility of implementing a command-line way to generate a png (or something like that) to be able to visualize the inspect page without having to load the interface every time. It's not a high priority but I thought I'd make an issue about it so we don't forget for the future :)

**Comment by meren** [comment]
I think we have everything for this. Almost. Here is a small test to demonstrate that. Using `master`, I run the mini test:

```
cd $anvio/anvio/tests
./run_mini_test.sh
```

Once this is done, I took a look at the split names just to find one random to play with:

```
anvi-get-split-coverages -p sandbox/test-output/SAMPLES-MERGED/PROFILE.db --list-splits
Auxiliary Data ...............................: Found: sandbox/test-output/SAMPLES-MERGED/AUXILIARY-DATA.db (v. 2)
Profile Super ................................: Initialized with all 35 splits: sandbox/test-output/SAMPLES-MERGED/PROFILE.db (v. 31)
204_10M_MERGED.PERFECT.gz.keep_contig_1720_split_00001
204_10M_MERGED.PERFECT.gz.keep_contig_1720_split_00002
204_10M_MERGED.PERFECT.gz.keep_contig_1720_split_00003
204_10M_MERGED.PERFECT.gz.keep_contig_1720_split_00004
204_10M_MERGED.PERFECT.gz.keep_contig_1720_split_00005
204_10M_MERGED.PERFECT.gz.keep_contig_1720_split_00006
204_10M_MERGED.PERFECT.gz.keep_contig_1720_split_00007
204_10M_MERGED.PERFECT.gz.keep_contig_1720_split_00008
204_10M_MERGED.PERFECT.gz.keep_contig_1720_split_00009
204_10M_MERGED.PERFECT.gz.keep_contig_6515_split_00001
204_10M_MERGED.PERFECT.gz.keep_contig_6515_split_00002
204_10M_MERGED.PERFECT.gz.keep_contig_6515_split_00003
204_10M_MERGED.PERFECT.gz.keep_contig_6515_split_00004
204_10M_MERGED.PERFECT.gz.keep_contig_6515_split_00005
204_10M_MERGED.PERFECT.gz.keep_contig_6515_split_00006
204_10M_MERGED.PERFECT.gz.keep_contig_6515_split_00007
204_10M_MERGED.PERFECT.gz.keep_contig_6515_split_00008
204_10M_MERGED.PERFECT.gz.keep_contig_878_split_00001
204_10M_MERGED.PERFECT.gz.keep_contig_878_split_00002
204_10M_MERGED.PERFECT.gz.keep_contig_878_split_00003
204_10M_MERGED.PERFECT.gz.keep_contig_878_split_00004
204_10M_MERGED.PERFECT.gz.keep_contig_878_split_00005
204_10M_MERGED.PERFECT.gz.keep_contig_878_split_00006
204_10M_MERGED.PERFECT.gz.keep_contig_878_split_00007
204_10M_MERGED.PERFECT.gz.keep_contig_878_split_00008
204_10M_MERGED.PERFECT.gz.keep_contig_878_split_00009
204_10M_MERGED.PERFECT.gz.keep_contig_878_split_00010
204_10M_MERGED.PERFECT.gz.keep_contig_878_split_00011
204_10M_MERGED.PERFECT.gz.keep_contig_878_split_00012
204_10M_MERGED.PERFECT.gz.keep_contig_878_split_00013
204_10M_MERGED.PERFECT.gz.keep_contig_878_split_00014
204_10M_MERGED.PERFECT.gz.keep_contig_878_split_00015
204_10M_MERGED.PERFECT.gz.keep_contig_878_split_00016
204_10M_MERGED.PERFECT.gz.keep_contig_878_split_00017
204_10M_MERGED.PERFECT.gz.keep_contig_878_split_00018
```

Asked anvi'o to give me coverages for one:

```
anvi-get-split-coverages -p sandbox/test-output/SAMPLES-MERGED/PROFILE.db \
                         --split-name 204_10M_MERGED.PERFECT.gz.keep_contig_1720_split_00001 \
                         -o ~/Downloads/TEST-SPLIT-COVs.txt
```

Then I used the following R code in RStudio to get the following output:

``` R
library(ggplot2)

d <- read.table('~/Downloads/TEST-SPLIT-COVs.txt', header = TRUE, sep="\t")

p <- ggplot(d, aes(x = nt_position, y = coverage, group=sample_name))
p <- p + geom_area()
p <- p + theme_bw()
p <- p + theme(legend.position="none")
p <- p + theme(axis.text.x=element_text(angle=90, hjust=1))
p <- p + facet_grid(sample_name ~ .)

pdf('~/Downloads/TEST-SPLIT-COVs.pdf', width=10, height = 2 * length(levels(d$sample_name)))
print(p)
dev.off()

```

![image](https://user-images.githubusercontent.com/197307/59365809-cf5bea00-8cfe-11e9-953e-e80e466e7c05.png)

So I think **we could add an R script to anvi'o**, that takes in the path for the coverages output (i.e., `~/Downloads/TEST-SPLIT-COVs.txt`), creates a PDF output (i.e., `~/Downloads/TEST-SPLIT-COVs.pdf`), while checking all input parameters. This script could be called `anvi-script-visualize-split-coverages` and explain in its help menu that the input file required for this is the output of the program `anvi-get-split-coverages`.

We could also make `anvi-get-split-coverages` to export a separate TAB-delmited text *if* there is a `default` state available in the profile database, so the color of each sample and whether they should be displayed or not can be learned. That part is easy, but we would need an R expert to write this script. Here is an example output file if someone wants to take this upon themselves to implement `anvi-script-visualize-split-coverages` that starts with the header `#!/usr/bin/env Rscript`:

[TEST-SPLIT-COVs.txt](https://github.com/merenlab/anvio/files/3282132/TEST-SPLIT-COVs.txt)

:)

**Comment by mooreryan** [comment]
I can work on wrapping this in a script.

**Comment by meren** [comment]
@mooreryan, thank you very much for sending this. I truly appreciate your effort, however, I feel that what we need is more than a wrapper for that `ggplot` function call. I think an R program with room for evolution would be much more appropriate for the long run.

For instance, while I also am not an R expert, I believe there should be no hard-coded defaults in the code, and the current visualization with facets should be encapsulated within a single function so in the future we can parameterize this if others come up with different visualization strategies (so in the future there may be an option to visualize the same data differently in the same code by just adding a new function). So overall, I think we need a bit more design in this program beyond a simple CLI (which can be very useful for single projects, but for things like anvi'o that serve many different user types and needs even the simplest things quickly get more complex).

I updated the suggestions in the previous message to make sure they capture these points so these points are cleared in case you would like to revise your PR or for those who will follow. Regardless, I appreciate very much your response to this call, and I would like to send you an anvi'o t-shirt and a bunch of stickers if you care. Please send me an e-mail via meren AT uchicago DOT edu and let me know your t-shirt size and shipping address :)


Best wishes,

**Comment by mooreryan** [comment]
Thanks for the response, I see what you're looking for now.  I will play around with it some more, and I will either update the pull request or close it by the end of today.

**Comment by meren** [comment]
@efogarty11, thanks to @mooreryan's contribution via the PR #1171, the `master` has now a program called `anvi-script-visualize-split-coverages`. Please feel free to test it on your gazillion samples (if you are interested, you can consider adding ridge line plots to this program for a compact alternative :)).

**Comment by efogarty11** [comment]
That is amazing to hear! Thank you so much @mooreryan! This is going to make my life infinitely better 😄
