### ISSUE TITLE
anvi-script-visualize-split-coverages cannot handle files with multiple split_names/contigs

### ISSUE THREAD

**Issue by mooreryan** [merenlab/anvio#1175]
## Version

anvio git repo version/commit: bfbcbb3592dfd18bd7ffc9880c5dac1e88bb37fb

## Problem

I was doing more work on the `anvi-script-visualize-split-coverages` script when I realized that multiple contigs/split_names per split coverages file will break the program.

I made a toy dataset to recreate the issue.

### Test data

Command run: 

```
./anvi-script-visualize-split-coverages -i multi_contig_multi_sample.split_cov.txt -o multi_contig_multi_sample.split_cov.pdf
```

Input text file: 
[multi_contig_multi_sample.split_cov.txt](https://github.com/merenlab/anvio/files/3302920/multi_contig_multi_sample.split_cov.txt)

Output PDF: 
[multi_contig_multi_sample.split_cov.pdf](https://github.com/merenlab/anvio/files/3302921/multi_contig_multi_sample.split_cov.pdf)

## Solutions?

Not sure the best way to fix this, but here are a couple possible fixes....

* Output a new PDF for each contig
* Add panels for each contig-sample pair, all in the same PDF
  * Grouped by sample: [multi_contig_multi_sample.split_cov.sample_name_by_split_name.pdf](https://github.com/merenlab/anvio/files/3302928/multi_contig_multi_sample.split_cov.sample_name_by_split_name.pdf)
  * Grouped by contig/split_name: 
 [multi_contig_multi_sample.split_cov.split_name_by_sample_name.pdf](https://github.com/merenlab/anvio/files/3302931/multi_contig_multi_sample.split_cov.split_name_by_sample_name.pdf)

**Comment by meren** [comment]
Hey @mooreryan,

Thank you for catching this! Indeed, `anvi-get-split-coverages` can report all splits in a bin/collection .... I totally forgot about this :/

My 2 cents suggestion is to have an additional flag (i.e., '`--report-each-split-separately`') --when declared, the program would report an independent PDF file for each split. Otherwise it would merge coverage values for ALL splits in alphabetical order, and display merged coverages all at once (so the number of nucleotides displayed in the X-axis would be equivalent to the total number of nucleotides in all splits per sample). If doing this is too much of a pain, reporting multiple PDF files in the presence of multiple splits is perfectly acceptable, in my opinion :)

Thank you very much regardless.

Best wishes,

**Comment by meren** [comment]
Here is a little test after @mooreryan's latest PR #1177. I made a small addition in 080db464e632eb5f6ef5982b9d58d8eae41e0ea0 to show the date and time, and then used the [Infant Gut Dataset](http://merenlab.org/tutorials/infant-gut/) to put the new feature up to a significant real-world challenge: visualizing the coverage patterns of an entire genome. After downloading the Infant gut dataset:

```
anvi-get-split-coverages -p PROFILE.db \
                         -c CONTIGS.db \
                         -C default \
                         --bin-id E_facealis \
                         -o E_facealis.txt
```

I run updated `anvi-script-visualize-split-coverages`:

```
anvi-script-visualize-split-coverages -i E_facealis.txt \
                                      -o E_facealis.pdf

INFO [06/20/19 16:24:50] -- Checking options
INFO [06/20/19 16:24:50] -- Parsing input data
INFO [06/20/19 16:26:33] -- Automatically setting the window size.
INFO [06/20/19 16:26:33] -- Largest sample is 2865861
INFO [06/20/19 16:26:33] -- Compressing samples.  Window size is 8597
INFO [06/20/19 16:26:33] -- Total data points before compression: 31524471
INFO [06/20/19 16:29:04] -- Total data points after compression: 3685
INFO [06/20/19 16:29:04] -- Coverage will be capped at 1000
INFO [06/20/19 16:29:04] -- Making coverage plots
INFO [06/20/19 16:29:04] -- Writing coverage plots
```

After about 5 minutes, 31,524,471 data points were parsed, compressed to 3,685, and the PDF was ready:
 
![image](https://user-images.githubusercontent.com/197307/59882900-125e3300-9379-11e9-8a67-3522643e2d61.png)

In fact I got a biological insight into this dataset that I did not have before :)


Thank you very much, Ryan!

**Comment by meren** [comment]
I am also realizing that an option for free y-scales is a necessity. So I implemented it in 9225ab14cff72dd8d561e56b3bab716a5e74e05b and this is how things look like now for the same data:

```
anvi-script-visualize-split-coverages -i E_facealis.txt \
                                      -o E_facealis.pdf
                                      --free-y-scale

INFO [06/20/19 16:53:57] -- Checking options
INFO [06/20/19 16:53:57] -- Parsing input data
INFO [06/20/19 16:55:40] -- Automatically setting the window size.
INFO [06/20/19 16:55:40] -- Largest sample is 2865861
INFO [06/20/19 16:55:40] -- Compressing samples.  Window size is 8597
INFO [06/20/19 16:55:40] -- Total data points before compression: 31524471
INFO [06/20/19 16:58:13] -- Total data points after compression: 3685
INFO [06/20/19 16:58:13] -- Coverage will be capped at 1000
INFO [06/20/19 16:58:13] -- Making coverage plots
INFO [06/20/19 16:58:13] -- Writing coverage plots
```

![image](https://user-images.githubusercontent.com/197307/59884089-cad9a600-937c-11e9-9c1a-d780690bae4a.png)


Pinging @efogarty11 so she knows that this is an option now.

**Comment by efogarty11** [comment]
Thank you both so much!! This is amazing 😄

**Comment by mooreryan** [comment]
This is working properly now, so I will close this issue.
