### ISSUE TITLE
IndexError: list index out of range when running anvi-setup-ncbi-cogs

### ISSUE THREAD

**Issue by YiweiNiu** [merenlab/anvio#1183]
Hi,

I got the following error messages when running `anvi-setup-ncbi-cogs`

```shell
$ ~/software/anaconda3/bin/anvi-setup-ncbi-cogs -T 2 --just-do-it
COG data directory ...........................: /home/niuyw/software/anaconda3/lib/python3.5/site-packages/anvio/data/misc/COG
COG data source ..............................: The anvi'o default.
COG data dir .................................: /home/niuyw/software/anaconda3/lib/python3.5/site-packages/anvio/data/misc/COG

WARNING
===============================================
This program will first check whether you have all the raw files, and then will
attempt to regenerate everything that is necessary from them.

[30 Jun 19 13:57:25 Formatting protein ids to COG ids file] ...                                                                                                            Traceback (most recent call last):
  File "/home/niuyw/software/anaconda3/bin/anvi-setup-ncbi-cogs", line 46, in <module>
    setup.create()
  File "/home/niuyw/software/anaconda3/lib/python3.5/site-packages/anvio/cogs.py", line 466, in create
    self.setup_raw_data()
  File "/home/niuyw/software/anaconda3/lib/python3.5/site-packages/anvio/cogs.py", line 628, in setup_raw_data
    self.files[file_name]['func'](file_path, J(self.COG_data_dir, self.files[file_name]['formatted_file_name']))
  File "/home/niuyw/software/anaconda3/lib/python3.5/site-packages/anvio/cogs.py", line 494, in format_p_id_to_cog_id_cPickle
    COG = fields[6]
IndexError: list index out of range
```

Here is the version information.

```shell
$ ~/software/anaconda3/bin/anvi-self-test --version
Anvi'o version ...............................: margaret (v5.5)
Profile DB version ...........................: 31
Contigs DB version ...........................: 12
Pan DB version ...............................: 13
Genome data storage version ..................: 6
Auxiliary data storage version ...............: 2
Structure DB version .........................: 1
```

Do you know how to solve this? I appreciate the help you could provide.

Bests,
Yiwei Niu

**Comment by meren** [comment]
Hi @YiweiNiu,

I can't reproduce this error. Both `master` and `v5.5` seem to be working.

Please rerun the same command with the flag `--reset` so it removes files from your previous attempt of setting them up. Basically run this:

```
anvi-setup-ncbi-cogs -T 2 --just-do-it --reset
```

Best,

**Comment by YiweiNiu** [comment]
Hi,

I used `pip` under Anaconda to install `anvio` .

I tried `--reset` but still got the same error. I would try `EggNOG` for alternative. Thank you for your help.

Another quick question: does `anvi-import-taxonomy-for-genes` support importing data from multiple sources (e.g. I want to run Kaiju on two databases) like `anvi-import-functions`?

**Comment by meren** [comment]
> does anvi-import-taxonomy-for-genes support importing data from multiple sources

No, unfortunately :/ But you can always create a copy of your contigs database. Although you should keep in mind that gene-level taxonomic annotation is only good for binning efforts and can be quite unreliable to estimate taxonomy of final genomes depending on the environment you are studying.

> I tried --reset but still got the same error.

Can you please try one more time after manually deleting that directory and running `anvi-setup-cogs` again?:

```
/home/niuyw/software/anaconda3/lib/python3.5/site-packages/anvio/data/misc/COG
```

This should not be happening.

**Comment by YiweiNiu** [comment]
Thank you for your quick reply.

I still got the same error after removing this directory. But I solved this by downloading files from `ftp://ftp.ncbi.nih.gov/pub/COG/COG2014/data/` to `~/software/anaconda3/lib/python3.5/site-packages/anvio/data/misc/COG/RAW_DATA_FROM_NCBI`. So, I suspect that it's due to our bad network connection. And the script does not check the completeness of the files.

But, I got another error when importing the `eggnog-mapper` annotations into contigs.db. I did not know if it's because of the way I installed COG database. The commands:

```bash
$TOOLDIR/anaconda3/bin/anvi-get-sequences-for-gene-calls -c $WORKDIR/anvi/$dataset/contigs.db --get-aa-sequences -o $WORKDIR/anvi/$dataset/amino-acid-sequences.fa
$path2pathon /home/luohx/software/src/eggnog-mapper-1.0.3/emapper.py -m diamond -i $WORKDIR/anvi/$dataset/amino-acid-sequences.fa --output $WORKDIR/anvi/$dataset/amino-acid-sequences
$TOOLDIR/anaconda3/bin/anvi-script-run-eggnog-mapper -T 8 -c $WORKDIR/anvi/$dataset/contigs.db --annotation amino-acid-sequences.emapper.annotations --use-version 1.0.3
```

And the error message:

```bash
COG data directory ...........................: /home/niuyw/software/anaconda3/lib/python3.5/site-packages/anvio/data/misc/COG
COG data source ..............................: The anvi'o default.
                                                                                                                         

Config Error: Gene caller ids found in this annotation file does not start with the expected 
              prefix. This is a historical glitch that is not quite easy to address          
              programmatically, so anvi'o asks you to add the expected prefix as the first   
              character of every gene call in your annotations file. This is the prefix what 
              you need to add manually to the very beginning of every line (anvi'o developers
              are very sorry for this step): 'g'.
```

I have two questions about this:

1. Why the COG database is needed by `anvi-script-run-eggnog-mapper` when importing the annotations from `eggnog-mapper`, which used EggNOG database?

2. Which file should I add 'g' in each line?

Sorry if my questions are too obvious. Thank you again for your inputs.

**Comment by meren** [comment]
> Why the COG database is needed by anvi-script-run-eggnog-mapper when importing the annotations from eggnog-mapper, which used EggNOG database?

Because the only information in the output file was COG ids without full functional annotations, if I remember correctly. Having COGs enable us to resolve the function long name on the fly.

> Which file should I add 'g' in each line?

`amino-acid-sequences.emapper.annotations` :)

**Comment by YiweiNiu** [comment]
Thank you very much. The problem was solved.
