### ISSUE TITLE
anvi-run-hmms raises Config error 

### ISSUE THREAD

**Issue by auslandc** [merenlab/anvio#1186]
Output from `anvi-self-test --version`:

```
Anvi'o version ...............................: margaret (v5.5)
Profile DB version ...........................: 31
Contigs DB version ...........................: 12
Pan DB version ...............................: 13
Genome data storage version ..................: 6
Auxiliary data storage version ...............: 2
Structure DB version .........................: 1
```
Running on Ubuntu 16, installed with conda *painless* install. 

Tried running `anvi-run-hmms -c GCF_000009045.1_ASM904v1_genomic.fna.fa.db` (as well as  `anvi-run-ncbi-cogs` separately) but received the following error:

`Config Error: A value for 'genes_are_called' does not seem to be set in table 'self'.`

When I created the contigs-db with `anvi-gen-contigs-database`, I did have output indicating external gene calls were provided:

```
Input FASTA file .............................: /disk2/catie/bacillus/jul-9-anvio-build/genomes/GCF_000009045.1_ASM904v1_genomic.fna.fa
Name .........................................: comparative analysis
Description ..................................: No description is given
Split Length .................................: 20,000                                                                                                                                                         
K-mer size ...................................: 4
Skip gene calling? ...........................: False
External gene calls provided? ................: GCF_000009045.1_ASM904v1_external_gene_calls
Ignoring internal stop codons? ...............: True
Splitting pays attention to gene calls? ......: True
External gene calls ..........................: 4039 gene calls recovered and will be processed.
```

I tried searching the interwebs for this error but could not find anything. 

I ran `anvi-db-info GCF_000009045.1_ASM904v1_genomic.fna.fa.db` on the database and received the following ouput:

```DB Info (no touch)
===============================================
Database Path ................................: GCF_000009045.1_ASM904v1_genomic.fna.fa.db
Description ..................................: [Not found, but it's OK]
Type .........................................: contigs
Version ......................................: 12


DB Info (no touch also)
===============================================
project_name .................................: comparative analysis
contigs_db_hash ..............................: hash6d7fa5d5
split_length .................................: 20000
```
Which, compared to say the output of the mini self-test or the database creation, is missing information like k-mer size, external gene calls provided, etc. 

I tried re-running the command and re-installing anvio to no avail. 
Any help/input much appreciated!

**Comment by meren** [comment]
Very sorry for the late response :( Things sometime fall through the cracks.

It seems your contigs database was an unfinished one as it is missing many values as seen from the `anvi-db-info` output :( The correct response to this issue was to suggest that you should re-generate the contigs db, but since it is almost a month ago, I believe you moved on from this.

Apologies again.
