### ISSUE TITLE
acceptable parameters for workflows

### ISSUE THREAD

**Issue by ShaiberAlon** [merenlab/anvio#1188]
@ozcan , @meren, there is a minor design issue that I wanted to discuss with you.

Currently, if a parameter is added (or removed) from one the anvio software that are included in the workflows then it means the workflow must be updated.
For example, `anvi-profile` in v5.3 had `--include-orphans` and in `master` it is now changed to `--ignore-orphans`, while the metagenomics workflow was not update for either of these at any point.

Fixing this is very easy:
https://github.com/merenlab/anvio/commit/46f9bcc6edf9f43c5c927f8681cc3f6b02d9d3a4

But it requires us to remember to do it, and I am not always aware of these changes when they happen.

So a way to go around this would be to just allow the rules to accept some basic parameters that we will likely never touch (e.g. `--min-contig-length`), but as for the rest of the parameters, all rules would accept a `additional-params` that would allow the user to insert whatever they want there. The only issue with this design is that now we lose the step of sanity checking that the config file doesn't include garbage parameters, and the user will only find out about these garbage parameters when their workflow reaches the step with the garbage and fails.

**Comment by ozcan** [comment]
I am in favor of keeping the sanity checking, these parameter changes happen quite rarely we were just not aware this time. And most parameters already in workflows, so why remove them? 
When I added this parameter, workflows were not in my mind so I didn't ping you or let you know but after this instance, I am sure we will be more conscious about these changes and let you know.

**Comment by ShaiberAlon** [comment]
That sounds good @ozcan. Thank you!
