### ISSUE TITLE
Feature request -- test for enrichment of gene clusters independently from functional annotations

### ISSUE THREAD

**Issue by sminot** [merenlab/anvio#1196]
The current behavior of the anvi-get-enriched-functions-per-pan-group function is to calculate enrichment scores _per functional group_ within a given category of genomes, grouping together gene clusters which have the same functional annotation. 

While this behavior is very useful, I would like to request an augmentation of this function which would allow the user to calculate enrichment scores independently for every gene cluster, regardless of whether they have any functional annotation or whether two gene clusters have the same functional annotation. Another way to put it is that I was hoping for an analysis in which the results table has a single line for every single gene cluster, instead of the current output which has a line for every COG function (some of which may contain multiple gene clusters)

The justification for this request is that functional annotations can be lacking, and that users may often be interested in identifying genes associated with a particular group of genomes without relying on a functional annotation system like COG. This type of analysis can often be used to identify new functions, which would be a great addition to the functionality of the anvi'o ecosystem of tooling.

**Comment by meren** [comment]
Hi @sminot,


Thank you very much for the suggestion.

I solved this problem by implementing a new flag, that on the fly adds a new (well, 'fake') functional source called `IDENTITY`, which annotates each gene cluster with their name as a function:

https://github.com/merenlab/anvio/commit/92f34bf20194024e55e9339df70389ff0c0aee91

This way you can achieve exactly what you want by including `--include-gc-identity-as-function` and `--annotation-source 'IDENTITY'` to your command line when you are using the program `anvi-get-enriched-functions-per-pan-group`.

Please let me know if this makes sense.


​Best wishes,

**Comment by sminot** [comment]
This makes great sense, thank you!

Can I expect that this will be included in the next release of anvi'o?

**Comment by meren** [comment]
Yes! Along with a much improved functional enrichment workflow thanks to @ShaiberAlon and Amy Willis' efforts.

If you want to test it immediately, you can switch to the `master` branch:

http://merenlab.org/2016/06/26/installation-v2/#installing-or-updating-from-the-active-codebase-because-why-not

**Comment by TonyMane** [comment]
Greetings, i'm using the master branch, but when I used the 'IDENTITY' flag, i get back the following error (below). How do you add this to a database (or databases)? thank you (fyi would add my files, but they are rather large).

(anvio-master) (anvio-master) -bash-4.2$ anvi-get-enriched-functions-per-pan-group -p ./Nitrospina_noOutgroup/Nitrospina_pan-PAN.db \
> -g NITROSPINA-GENOMES.db \
> --category light \
> --annotation-source IDENTITY \
> -o Nitrospina-enriched-oxygen-cluster.txt \
> --functional-occurrence-table-output  Nitrospina-functions-occurrence-frequency.txt


Genomes storage .............................................: Initialized (storage hash: hash334baf56)                                                                                                   
Num genomes in storage ......................................: 24
Num genomes will be used ....................................: 24
Pan DB ......................................................: Initialized: ./Nitrospina_noOutgroup/Nitrospina_pan-PAN.db (v. 14)
Gene cluster homogeneity estimates ..........................: Functional: [YES]; Geometric: [YES]; Combined: [YES]
                                                                                                                                                                                                          
* Gene clusters are initialized for all 10794 gene clusters in the database.

                                                                                                                                                                                                          

Config Error: Your favorite functional annotation source 'IDENTITY' does not seem to be among
              one of the sources that are available to you. Here are the ones you should     
              choose from: COG_CATEGORY, COG_FUNCTION.

**Comment by meren** [comment]
Hi @TonyMane,

Sorry for the late response.

Your command will work if you add `--include-gc-identity-as-function` to your command :)
