### ISSUE TITLE
Pangenome functional enrichment

### ISSUE THREAD

**Issue by pbravakos** [merenlab/anvio#1201]
Hi,
I am running a functional enrichment analysis with anvi-get-enriched-functions-per-pan-group. I get the output without any errors. From the output i select a gene cluster that in the "core" column has the value "True" and copy it. Then i search the pangenome database for the particular gene cluster but it does not belong to the core pangenome. This happens for multiple gene clusters not a particular one.
Is this a bug or do i make some sort of mistake?
Thanks
Panos

```
    Anvi'o version ...............................: margaret (v5.4-master)
Profile DB version ...........................: 31
Contigs DB version ...........................: 12
Pan DB version ...............................: 13
Genome data storage version ..................: 6
Auxiliary data storage version ...............: 2
Structure DB version .........................: 1
    
```

**Comment by meren** [comment]
This is very concerning indeed, @pbravakos :)

But I realize you are working with the `v5.4`, and I am not sure if this is a bug that was fixed in `v5.5`. I would appreciate very much if you would consider trying it again with the latest version and re-open this issue if it is still there.
