### ISSUE TITLE
anvi-migrate-db stuck at v5 to v6

### ISSUE THREAD

**Issue by biotemon** [merenlab/anvio#1208]
Hello, 

This is a techincal issue which I don't know where else to find a solution. 

As requested here it is the `anvi-self-test --version` output. 

```
Anvi'o version ...............................: margaret (v5.5-master)
Profile DB version ...........................: 31
Contigs DB version ...........................: 13
Pan DB version ...............................: 13
Genome data storage version ..................: 6
Auxiliary data storage version ...............: 2
Structure DB version .........................: 1
```

Issue description: I am trying to reproduce a previous study. The PROFILE.db is version 5 apparently.
 
When I do:

```
anvi-migrate-db PROFILE.db
```
I get.
 
```
Config Error: Anvi'o can not find a migrate script required for this operation. (DB Type: profile, Script name: v5_to_v6)
```

Operating system: macOS Mojave, version 10.14.6

Files to reproduce the issue: 
https://figshare.com/articles/Mason_Data/1499246
https://figshare.com/articles/Mason_et_al_SAGs/1499235

Could you please help me with this. 

Thanks in advance!

**Comment by ozcan** [comment]
Hi @biotemon,

Unfortunately there is no way to migrate v5 to current version v31. That version belongs to one of the earliest releases of anvi'o that released almost three years ago. Anvi'o is backwards compatible  with any profile db above v13. You can always generate profile db from scratch using new version if you have access to raw data.

Best,
