### ISSUE TITLE
anvi-compute-ani distance and linkage flag error

### ISSUE THREAD

**Issue by rbartelme** [merenlab/anvio#1211]
When specifying alternate distances and linkages to PyANI via anvi-compute-ani, and error occurs

`anvi-compute-ani -p PAN.db -e my-external-genomes.txt --distance hamming --linkage centroid -o Output_ANI`

This gives this following error:

```
Config Error: Bad news :/ Something went wrong while anvi'o was processing the output for
              'alignment_coverage'. You can find the offending file if you search for the
              output file in the temporary output directory                              
              '/var/folders/_2/20vp5k8j5jd09t2crgtrxlgr0000gr/T/tmpup2j50jn/output'.
```

**Comment by ozcan** [comment]
Thank you for reporting @rbartelme, It seems anvi'o was silently failing if distance and linkage is not compatible, now there is a check for it.

**Comment by ozcan** [comment]
You can manually check compatibility until the next release using the snippet below

```
from scipy.cluster import hierarchy
hierarchy.linkage([(1, 0), (0, 1), (1, 1)], metric='hamming', method='centroid')
```
It will raise an exception if they are not compatible.
