### ISSUE TITLE
Pangenome functional enrichment

### ISSUE THREAD

**Issue by pbravakos** [merenlab/anvio#1213]
Hi,
I am running a functional enrichment analysis with anvi-get-enriched-functions-per-pan-group. I get the output without any errors. From the output i select a gene cluster that in the "core" column has the value "True" and copy it. Then i search the pangenome database for the particular gene cluster but it does not belong to the core pangenome. This happens for multiple gene clusters not a particular one.
I have posted the same issue before with a previous version of Anvi'o (v.5.4) but now i am having the same issue with the latest version.
Thanks
Panos

```
Anvi'o version ...............................: margaret (v5.5-master)
Profile DB version ...........................: 31
Contigs DB version ...........................: 13
Pan DB version ...............................: 13
Genome data storage version ..................: 6
Auxiliary data storage version ...............: 2
Structure DB version .........................: 1

```

**Comment by meren** [comment]
Thank you very much for trying this again the latest version, @pbravakos :)

I will ping @ShaiberAlon here in case he sees immediately the explanation for it.

**Comment by ShaiberAlon** [comment]
Hi,
The “core” in this case refers to a core function and not a core gene cluster. I believe that for each of those core function that don’t correspond to a core gene cluster, you would see that these functions each correspond to multiple gene clusters (you can see that in the output of the enrichment analysis). I think this subtlety is explained in the tutorial. Please let me know if you need further clarification.

**Comment by meren** [comment]
Thank you very much for the clarification, @ShaiberAlon.

2 cents: Perhaps we should change the word in the output to "CORE_FUNCTION" to avoid future confusions :)

**Comment by pbravakos** [comment]
Thanks for the response. Now it all makes sense.
It would be nice for my work -and i am posting it here as a feature request- to have a column where the actual number of GC clusters belonging to the core pangenome is shown. For example if i get in the "gene_clusters_ids" column 6 GCs, i would like to have an additional column that would indicate how many of them belong to the core pangenome. I am not interested that much in which of them belong to the core, since i already know the associated function, just how many of them.
Best
Panos

**Comment by meren** [comment]
Hi Panos,

I can see a solution to your need that meets high design standards of anvi'o codebase, but since (1) it requires so much work while (2) not essential most analyses and (3) the information is recoverable by using functional output in conjunction with other anvi'o outputs (i.e., anvi-summarize or anvi-export-collection after binning GSs into logical groups (i.e., core, accessory, etc)), I don't think we can do it anytime soon due to the fact that we are an extremely small team :)

But I am marking this issue with a special label that will help us remember it.

**Comment by pbravakos** [comment]
Hi Meren,
Thanks a lot for the response.
I have found a workaround by using a small script to do exactly what i need. My only issue is i haven't found a command line program to "search the gene clusters using filters" in order to extract the core gene clusters to a text file and i have to do it manually from the interactive mode. Is there such a program?
I know that probably this is not the best place to ask such questions, so if you tell me i can post the same question to the Anvi'o forum or anywherere appropriate.
Best
Panos

**Comment by pbravakos** [comment]
Sorry for bothering you again but I think i found something related to the functional enrichment analysis that seems to me as a bug but I am certainly not sure. I have 23 genomes in my pangenome and have separated them into two groups for the functional enrichment analysis; one consisting of 8 genomes and one consisting of 15 genomes. My understanding is that when the column "core in group" has the value "true" at least one of the listed gene clusters in the column "gene_clusters_ids" has to be found in all genomes of that particular group. In my case, i have a row which has the values "true" and "false" in the columns "core_in_group" and "core" correspondingly and lists 5 gene clusters in the column "gene_cluster_ids" but none of the listed gene clusters seems to occur in all 15 genomes of the particular group. I am missing something?
Thanks
Panos

**Comment by ShaiberAlon** [comment]
Hi Panos,

I apologize for the confusing terms, but “core in group” once again refers to the function and not to a particular gene cluster. I am away from the office so as for your other question, I will either get back to you next week or leave it for Meren to respond.

**Comment by pbravakos** [comment]
Thanks very much for the response and sorry if i keep bothering you with questions that seem trivial but really now I am confused. I do not understand how a function can be in the core of a group without having a single gene cluster belonging to the core?

**Comment by ShaiberAlon** [comment]
I apologize. This time I was the one to be confused. I thought you meant that the genomes in the group have gene clusters with that function, but the there is no single gene cluster that is shared by all the members of the group.

So what you really mean is that none of the gene clusters with this function is occurring in any of the members of the group? So this function actually seems to be absent completely from genomes in the group?

I’m sorry if I’m still misunderstanding.

**Comment by ShaiberAlon** [comment]
Now just to make sure, when you say “gene cluster belonging to the core”. You mean a gene cluster that is in all genomes, right?

Multiple gene clusters can be annotated with the same function. Hence two genomes can have the same function without sharing any gene clusters. 

My definition for “core in group” in the context of the functional enrichment refers to a function that is found in all the genomes of the group.

So a function could be found in all the genomes, but not associated with a gene cluster that is in all members of the group, but instead be associated with multiple gene clusters, each associated with some (or even just one) of the genomes in the group.

**Comment by pbravakos** [comment]
Thanks once again. One question to make sure i understand correctly:
In my example with the 15 genomes that form one group, and the 5 gene clusters that are associated with a particular function, each of the 15 genomes must be represented in at least one of those gene clusters in order to be in the core of the group?

**Comment by ShaiberAlon** [comment]
That’s correct. I’m happy to help with any other question.

**Comment by pbravakos** [comment]
Thanks for your time and patience @ShaiberAlon. I think now I have the basic understanding of how things work, so no more questions! 
Best regards
Panos
