### ISSUE TITLE
Feature Request -- having anvi-split split off a collection, but keep all the bins together

### ISSUE THREAD

**Issue by AstrobioMike** [merenlab/anvio#1235]
Hiya!

Right now the glorious `anvi-split` takes the collection you want and makes individual profile databases for each of the bins in that collection. I have often wanted to visualize just the bins i care about, but all together still, not each by itself, and have a workaround i recently shared with someone else trying to do this. The workaround just involves making a new collection that holds all of the desired bins in one bin, running `anvi-split` on that, and then importing the collection that has all those contigs/splits delineated in different bins into the new subset db. But now that i've seen i'm not the only one who would want to do this, thought maybe a flag could be added to `anvi-split` that would tell it to do this rather than making one for each bin. 

I'm fairly confident this wouldn't be too hard to implement, and in a moment of bravery i found and opened up the [splitter library](https://github.com/merenlab/anvio/blob/master/anvio/splitter.py) to think about trying, but realized it would probably take me months 😬

So figured i'd post here too and hope someone else does it before then 💩

**Comment by meren** [comment]
This sounds like too much design for something that anvi'o can already do with the combined use of `anvi-merge-bins`, `anvi-export-collection`, `anvi-import-collection`, and `anvi-split` :)

**Comment by AstrobioMike** [comment]
Okkaayyyyy, i guess you can't spoil us too much :)

**Comment by meren** [comment]
I love spoiling you, but then I also have to protect the sanity of future developers. Otherwise when it is time for others to maintain anvi'o, we will find no one around who can understand its codebase :)
