### ISSUE TITLE
In v5.5: if anvi-run-ncbi-cogs doesn't find any hits then it doesn't list as a source

### ISSUE THREAD

**Issue by ShaiberAlon** [merenlab/anvio#1237]
If no hits were found, then it should still be listed as a source, so that if the contigs database is used for pangenomics then the genomes storage would still be able to merge functional annotations from all contigs databases.

**Comment by meren** [comment]
I agree.

**Comment by ShaiberAlon** [comment]
This commit solves this: 7b8b8a74. Once we merge the branch then I will close this issue.

**Comment by meren** [comment]
Thank you, Alon. Please feel free to merge it and close the issue.

**Comment by ShaiberAlon** [comment]
Will do!
