### ISSUE TITLE
Urgent online documentation needs for v6

### ISSUE THREAD

**Issue by meren** [merenlab/anvio#1243]
Our online documentation is falling behind. I see multiple critical needs there. Note: All these updates should be submitted to [this](https://github.com/merenlab/web/tree/anvio-v6) branch of our web so everything goes out all at once with `v6`.

Those who write documentations can be different than those who wrote the programs (so I randomly tagged as many people as I could), but the urgent needs I can see include,

- [x] The new binning framework should have a tutorial. `anvi-cluster-with-concoct` is gone, and instead we have `anvi-cluster-contigs` that relies on existing binning algorithms installed on user's computer. But our online material is unaware of that.

- [x] `anvi-export-locus` needs a tutorial (@mschecht proposed to help with that).

- [ ] `anvi-dereplicate-genomes` needs a tutorial (@mahmoudyousef98 proposed to take an initial stab at it). in which it would be great to talk about the functionality of `anvi-compute-genome-similarity` since it is now much more talented than the previous `anvi-compute-ani`.

- [x] `anvi-estimate-taxonomy` needs a comprehensive tutorial (it is on @meren).

- [x] `anvi-inspect` needs to be mentioned / demonstrated somewhere. Probably the best place would be somewhere [here](http://merenlab.org/tutorials/infant-gut/). _Update: @efogarty11 took this one._

- [x] `anvi-google` program needs to be mentioned somewhere. Perhaps an entirely new post on "how to find your way around anvi'o" that lists helpful resources that include not only `anvi-google` but also the vignette, slack, google groups, would be a good future investment. IDK.

- [x] `anvi-gen-fixation-index-matrix` should be mentioned somewhere. A new subsection here would be the best way to do it, in my opinion: http://merenlab.org/tutorials/infant-gut/#chapter-iv-microbial-population-genetics. @ekiefl would be the best person to do it.

- [x] Very critically, our installation documentation needs to be updated and made completely fool-proof. We will walk people through step by step how they can install anvi'o `v6` through conda. @ozcan is the best candidate for this.

Any help is most welcome. Thank you all very much for your consideration in advance!

**Comment by efogarty11** [comment]
I can do `anvi-inspect`! Unless someone already is. @meren should I write something for `anvi-script-visualize-split-coverages` or is that unlikely to make it into v6?

**Comment by meren** [comment]
Thank you very much, @efogarty11! 

I think that would be great to write a post that talks about visualizing coverages and SNVs. Something that is quite rarely done in genome-resolved metagenomics. @mooreryan would be a good person to ask an opinion once there is something or to collaborate throughout.

I think a great resource could have the following major sections (and can use public data, we can talk more if you want):

- metagenomic read recruitment is fun, but visualizing coverages is funner.
- anvi interactive interface does a great job helping us do that in context (as you know from this tutorial and that post), but it is not feasible for all cases. especially when there are too many splits to initiate an interface when you have to do it a million times.
- `anvi-inspect` partially solves this problem. it does this and that. here is an example from the plasmid work from that recent PNAS publication I gracefully and nonchalantly reanalyzed like boss. yah. because cool.
- but even then it can take a looooooon time to load the interface if there are too many samples with lots of SNVs. Let alone exporting SVGs from the anvi-inspect and working on it effectively to create publication-ready figures. but thanks to Ryan's help, we now have `anvi-script-visualize-split-coverages`. it's lit. here are some example ways to use it. bam.

it is work, but worthwhile work.

**Comment by ivagljiva** [comment]
I would be happy to do the `anvi-google` post, and I could also give `anvi-cluster-contigs` a go. I haven't used either of these yet, but I would like to learn them. If I could sit down with the people who wrote these programs for a brief overview, then I can try these out and write a first pass of the tutorials from a beginner's perspective. Then the experts could come in and add anything I missed. Does that sound reasonable, @meren?

**Comment by meren** [comment]
Hey @ivagljiva, thank you very much :) It would be great if you were to help us with a resource on "how to find your way around anvi'o" and `anvi-google` could be a part of it. I think you, @ekiefl and I can talk about this a bit to brainstorm about what it could look like )

**Comment by ekiefl** [comment]
https://github.com/merenlab/anvio/commit/eddb1e75ebe779622d9b79a3183a2aff370edb90

As for fixation index, some information is already on the website. I've linked it with the resources meta-tag. I'm the first to admit it's a meager amount of information, but I have enough on my plate.

**Comment by ekiefl** [comment]
Just completed updating online documentation of `anvi-cluster-with-concoct`: https://github.com/merenlab/web/commit/84fbcff284f51d9ef61a6861b2a4b7d5a2457504

The only remaining item is a tutorial for `anvi-dereplicate-genomes`. This would certainly be nice to have, but in lieu of a tutorial, we now have a great help doc thanks to @Jessica-Pan that details `anvi-dereplicate-genomes`.

Closing this issue.
