### ISSUE TITLE
[solved] anvi-run-scg-taxonomy fails with ValueError

### ISSUE THREAD

**Issue by meren** [merenlab/anvio#1259]
This happens in `v6`. When it is run on a fresh conda installation, `anvi-run-scg-taxonomy` dies with this:

```
Traceback (most recent call last):
  File "/opt/conda/envs/anvioenv/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/opt/conda/envs/anvioenv/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/envs/anvioenv/lib/python3.6/site-packages/anvio/scgtaxonomyops.py", line 1396, in blast_search_scgs_worker
    gene_callers_id = int(fields[0])
ValueError: invalid literal for int() with base 10: 'diamond v0.9.26.127 | (...)'
```

**Comment by meren** [comment]
This is happening because conda installs a different version of `diamond` then the version anvi'o wants to work with :/ However, a solution exists. 

You need `diamond` version `0.9.14`. In your conda environment you can install it the following way:

```
conda install diamond=0.9.14
```

This is what you should see:

```
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /opt/conda/envs/anvioenv

  added / updated specs:
    - diamond=0.9.14


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    diamond-0.9.14             |       hd28b015_2         556 KB  bioconda
    ------------------------------------------------------------
                                           Total:         556 KB

The following packages will be DOWNGRADED:

  diamond                                 0.9.26-hfb76ee0_0 --> 0.9.14-hd28b015_2


Proceed ([y]/n)? y
```

Don't continue unless you see this output when you take a look at the diamond version number:

```
diamond --version

diamond version 0.9.14
```

Then you want to remove all the previous databases built with the previous version of `diamond`. First, run this:

``` python
python -c 'import anvio; \
           import os; \
           import glob; \
           [os.remove(x) for x in glob.glob(os.path.join(os.path.dirname(anvio.__file__), \
                                            "data/misc/SCG_TAXONOMY/GTDB/SCG_SEARCH_DATABASES/") + "*.dmnd")]'
```

Then, run the following command to re-create your databases:

```
anvi-setup-scg-databases
```

Now you must be golden. Run this on any contigs database to run scg-taxonomy:

```
anvi-run-scg-taxonomy -c CONTIGS.db -T 3 -P 3
```

And then this to estimate taxonomy:

```
anvi-estimate-genome-taxonomy -c CONTIGS.db
```

Many apologies for this error :(

**Comment by jarrodscott** [comment]
tested successfully on v6 master (Centos and Mac)

**Comment by meren** [comment]
tank you very very much, @jarrodscott. I have updated the installation document and the [scg-taxonomy article](http://merenlab.org/2019/10/08/anvio-scg-taxonomy/). But it is very sad nevertheless that we missed this one since it is pretty critical.

**Comment by jarrodscott** [comment]
@meren I think the awesomeness of a new anvio release overshadows a small oversight.
