### ISSUE TITLE
How to construct genome storge and do pangenome analysis WITH FUNCTION ANNOTATIONS

### ISSUE THREAD

**Issue by anzhangli84** [merenlab/anvio#1280]
Anvi'o version ...............................: margaret (v5.5)
Profile DB version ...........................: 31
Contigs DB version ...........................: 12
Pan DB version ...............................: 13
Genome data storage version ..................: 6
Auxiliary data storage version ...............: 2
Structure DB version .........................: 1

(When performing anvi-get-enriched-functions-per-pan-group, the log is below:)

WARNING
==============================================================
Genomes storage does not have any info about gene functions. Certain parts of
the pangenomic workflow will not be accessible.

Config Error: For some reason funtions are not initialized for this pan class instance. We
              can't summarize functional enrichment stats without that :/ 
     ```
     Using Ubuntu 18.04LTS. 
     Anvi'o was installed by conda.

Command lines used before found error:
(anvio5) dell@dell-Precision-Tower-7910:~$ anvi-get-enriched-functions-per-pan-group -p /home/dell/anvio/Arenibacter-minbit0.3/Arenibacter_with_anno-minbit03-PAN.db \
>                                           -g /home/dell/anvio/Arenibacter_with_anno-GENOMES.db  \
>                                           --category B \
>                                           -l \
>                                           -o /home/dell/anvio/function/enriched-functions-B.txt \
>                                           --functional-occurrence-table-output /home/dell/anvio/function/functions-occurrence-frequency-B.txt




   Hi, meren, thanks for anvi'o. It's very awesome.
   I imported a simple matrix of functional annotation into contig databases, and I can find the annotation when

> anvi-export-functions -c /home/dell/anvio/Arenibacter_algicola_C-21.db -l
  
  Then created genomes storage and performed pan genome analysis by:

> anvi-gen-genomes-storage -e /home/dell/anvio/list -o /home/dell/anvio/Arenibacter_with_anno-GENOMES.db

> anvi-pan-genome -g /home/dell/anvio/Arenibacter_with_anno-GENOMES.db \
                 --project-name "Arenibacter_with_anno-minbit03" \
                 --output-dir /home/dell/anvio/Arenibacter-minbit0.3 \
                 --num-threads 56 \
                 --minbit 0.3 \
                 --mcl-inflation 5 \
                 --use-ncbi-blast

   However, when run "anvi-get-enriched-functions-per-pan-group", anvi'o said no info about gene functions. 

   It seems one could only import functional info into contig database, but NOT genome storage or anvi'o project databases? 
   
   I read the parameters and options of "anvi-gen-genomes-storage" and "anvi-pan-genome", and didn't found how to transfer gene function annotations withing contig databases into genome storage (GENOMES.db) or project databases (-PAN.db)?

   So, how can I import gene functions directly into genome storage (GENOMES.db) or project databases (-PAN.db)? OR, how can I keep the gene function annotations of contig database still in genome storage (GENOMES.db) or project databases (-PAN.db)?

   Thank you for your time and I look forward to your reply.

 An-Zhang Li

**Comment by meren** [comment]
Dear An-Zhang,

Thank you very much for reaching out to us. Two things: I think you should update your anvi'o to `v6`. We have a much better framework to study functional enrichment in this version.

What is your functional annotation source? When you import your simple matrix you must have given it a name. You should declare that name to with `--annotation-source` when you are running `anvi-get-enriched-functions-per-pan-group`.


Best wishes,

**Comment by anzhangli84** [comment]
Thanks very much!! 
I succeeded with your "given it a name" advice. Thank you meren. I would install version 6 asap.
