### ISSUE TITLE
Convention for docstring indentation

### ISSUE THREAD

**Issue by ekiefl** [merenlab/anvio#1282]
How should we format our docstring indentation?

Every time I write a method I feel awkward about how I'm formatting my doc string. Can we please get a convention down if it doesn't already exist? My instinct is:

## one liners

```python
def func():
    """ docstring """
    pass
```

## multi line

```python
def func():
    """ 
    etiusto odio dignissimos
    ducimus qui blanditii 
    """
    pass
```

These are in line with PEP 257 https://www.python.org/dev/peps/pep-0257/#multi-line-docstrings

What do you guys think? What convention do you like? I am not proposing we retroactively change things, but rather move forward with a convention.

**Comment by ShaiberAlon** [comment]
I have been using:

## one liners

```python
def func():
    """ docstring """
    pass
```

## multi line

```python
def func():
    """ 
        etiusto odio dignissimos
        ducimus qui blanditii 
    """
    pass
```

But I am fine with your way.

**Comment by meren** [comment]
I guess the one liners are pretty obvious and there is an agreement. I've been using this for multi lines:

``` python
def func():
    """Often a single line brief description.

       More lines talking about other things and giving examples for
       use cases and parameters. Like this is how you would have done
       if you had to use this function:

           >>> import anvio
           >>> print(anvio.__version__)

       And so on.
    """

    pass
```

I can live with this, which is more in line with PEP 257:

``` python
def fun(x, y):
    """A single line description.

    But then everything is just a single indentation level. Examples and everything else
    obeys that, including use case scenarios that show how you would have done
    something if you had to use this function:

    >>> import anvio
    >>> print(anvio.__version__)

    And so on. But then we always include a single blank line after the docstring.
    """

    if x == y:
        return "silly goose"
    ...
```

But either of these would kill me I'm afraid :(

``` python
def func():
    """ 
    etiusto odio dignissimos
    ducimus qui blanditii 
    """
    pass
```

``` python
def func():
    """ 
        etiusto odio dignissimos
        ducimus qui blanditii 
    """
    pass
```

**Comment by ekiefl** [comment]
I can also live with this:

```python
def fun(x, y):
    """A single line description.

    But then everything is just a single indentation level. Examples and everything else
    obeys that, including use case scenarios that show how you would have done
    something if you had to use this function:

    >>> import anvio
    >>> print(anvio.__version__)

    And so on. But then we always include a single blank line after the docstring.
    """

    if x == y:
        return "silly goose"
    ...
```

**Comment by meren** [comment]
> I can also live with this

Great. I suggest if there are no objections from anyone, especially @ozcan and @ShaiberAlon by tomorrow evening let's settle on this then.

**Comment by ShaiberAlon** [comment]
I will follow this from here on :-)

**Comment by ozcan** [comment]
> I can also live with this:
+1

**Comment by ekiefl** [comment]
Ok. Sounds like we're all on board. Further info before closing, if it is a class docstring, please place it in the class, not the `__init__`. This guarantees that `ExampleClass.__doc__` is populated, which is used for autocompletion software such as jedi-vim.

Example:

```python
class Read:
    """Class for manipulating reads

    Parameters
    ==========
    read : pysam.AlignedSegment
    """

    def __init__(self, read):
        self.r = read
        self.cigarops = Cigar()
```

**Comment by meren** [comment]
👍

**Comment by ekiefl** [comment]
# Anvi'o docstrings

I decided to write up a small document for current/future contributors of anvi'o regarding docstrings. Why docstrings in particular? I feel docstrings are the best promoters for using currently existing features in anvi'o rather than rewriting things from scratch for each application. In that sense, they are the cornerstone for interacting with anvi'o as an API. I've assigned all contributors I can think of off the top of my head.

**Author's disclaimer**: While many of these specifications have been explicitly decided upon in this thread, many have not, and represent my opinion of what makes sense, what I've seen others doing, and what I prefer to do. This is not a closed discussion, although this github issue may spend most of its time "closed". Please feel free to re-open this issue at any point to critique or suggest alterations.

# Philosophy

**If you write a function it is accessible to others. If you write a docstring, it is usable by others**. These conventions have been designed to create uniformity across the codebase and increase the breadth of the anvi'o API. The anvi'o API is perhaps the most important tool for anvi'o developers and 3rd party developers, and it is learned through its docstrings.

Sadly, the majority of the codebase does not have documentation, or if it does, it does not conform to these standards. However things are changing. Please model your docstrings after these conventions, not after conventions you find in the codebase, as they may have been written from the pre-convention era.

# Examples

Let's jump straight into examples, for technical specifications, see "Docstring Blueprint" below.

## Single line docstring

This is appropriate for functions that require little documentation. Example:

```python
def get_description_in_db(anvio_db_path, run=run):
    """Reads the description in an anvi'o database"""

    anvio_db = db.DB(anvio_db_path, None, ignore_version=True)
    description = None
    try:
        description = anvio_db.get_meta_value('description')
    except ConfigError:
        description = '_No description is available_'

    anvio_db.disconnect()
    return description
```

## Multi-line docstring--strive for at least this

We should strive for at least `<one_line_brief_description>`, `[multi_line_extended_description]`, `Parameters`, and `Returns`. Here is a nice example:

```python
def check_MODELLER(executable=None):
    """Test if MODELLER is going to work.

    Checks the executable exists, that a license exists, and can produce the expected output of a
    modeller executable. Exists outside of the class MODELLER so it does not have to be checked
    everytime the class is initialized. 

    Parameters
    ==========
    executable : str, None
        The string representation of a binary MODELLER program. E.g "mod9.21". If None,
        up_to_date_modeller_exec is chosen and tested.

    Returns
    =======
    executable : str
        Returns the executable that you _should_ use, which is not necessarily what is input
    """

    executable = executable if executable else up_to_date_modeller_exec

    scripts_folder = J(os.path.dirname(anvio.__file__), 'data/misc/MODELLER/scripts')
    if utils.filesnpaths.is_dir_empty(scripts_folder):
        raise ConfigError("Anvi'o houses all its MODELLER scripts in %s, but your directory "
                          "contains no scripts. Why you did dat?" % scripts_folder)

    try:
        utils.is_program_exists(executable)
    except ConfigError as e:
    ...
    ...
    ...
```

## Multi-line docstring--The poster child

Here is an excellent docstring that utilizes all the features:

```python
def get_list_of_outliers(values, threshold=None, zeros_are_outliers=False, median=None):
    """Return boolean array of whether values are outliers (True means outlier)

    Modified from Joe Kington's (https://stackoverflow.com/users/325565/joe-kington)
    implementation computing absolute deviation around the median.

    Parameters
    ==========
    values : array-like
        A num_observations by num_dimensions array of observations.

    threshold : number, None
        The modified z-score to use as a thresholdold. Observations with
        a modified z-score (based on the median absolute deviation) greater
        than this value will be classified as outliers.

    median : array-like, None
        Pass median of values if you already calculated it to save time.

    Returns
    =======
    mask : numpy array (dtype=bool)
        A num_observations-length boolean array. True means outlier

    Examples
    ========

    Create an array with 5 manually created outliers:

    >>> import numpy as np
    >>> import anvio.utils as utils
    >>> array = 10*np.ones(30) + np.random.rand(30)
    >>> array[5] = -10
    >>> array[9] = -10
    >>> array[12] = -10
    >>> array[15] = -10
    >>> array[23] = -10
    >>> mask = utils.get_list_of_outliers(array, threshold=5)
    >>> print(mask)
    [False False False False False  True False False False  True False False
     True False False  True False False False False False False False  True
     False False False False False False]

    As can be seen, mask returns a numpy array of True/False values, where True corresponds to
    outlier values.

    >>> print(outlier_indices)
    >>> outlier_indices = np.where(mask == True)[0]
    [ 5  9 12 15 23]

    The `True` values indeed occur at the indices where the values hand been manually changed to
    represent outliers.

    References
    ==========
    Boris Iglewicz and David Hoaglin (1993), "Volume 16: How to Detect and
    Handle Outliers", The ASQC Basic References in Quality Control:
    Statistical Techniques, Edward F. Mykytka, Ph.D., Editor.

    http://www.sciencedirect.com/science/article/pii/S0022103113000668
    """

    if threshold is None:
        threshold = 1.5

    if len(values.shape) == 1:
        values = values[:, None]

    if not median: median = np.median(values, axis=0)
    ...
    ...
    ...
```

## Class docstrings

If it is a class docstring, please place it in the class, not the `__init__`. This guarantees that `ExampleClass.__doc__` is populated, which is used for autocompletion software such as jedi-vim.

Furthermore, there should be no need for a `Returns` category, since `__init__` functions typically they return `None`.

```python
class Read:
    """Class for manipulating reads

    Parameters
    ==========
    read : pysam.AlignedSegment
    """

    def __init__(self, read):
        self.r = read
        self.cigarops = Cigar()
    ...
    ...
    ...
```

# Docstring Blueprint

These are technical details. If you would prefer learning by example, please see the "Examples" section above.

Those surrounded by `<...>` are mandatory, those surrounded by `[...]` are optional.

```python
def function(foo, bar):
    """<one_line_brief_description>

    [multi_line_extended_description]

    [
    Parameters
    ==========
    <parameter_name> : <data_type>[, default_value]
        <parameter_description>

    <parameter_name> : <data_type>[, default_value]
        <parameter_description>
    ]

    [
    Returns
    =======
    <output_name> : <data_type>
        <output_description>
    ]

    [
    Examples
    ========
    <example_description>
    <example>

    <example_description>
    <example>
    ]

    [
    Notes
    =====
    - <notes>
    - <notes>
    ]

    [
    References
    ==========
    <references_text>
    ]
    """

    # There is a new line between the first line of the function body and the """
    return foo + bar
```

Remarks:

1. The start and end of the docstring are specified with triple double-quotes, not triple single-quotes.

2. Both `"""` are one indentation level in from the function definition. The first `"""` is accompanied by `<one_line_brief_description>`, the second `"""` exists by itself and a new line separates it from the function body.

3. Besides `<one_line_brief_description>`, all text is justified one indentation level in from the function definition.

4. `<one_line_brief_description>` is the only required format but we encourage including `Parameters` and `Returns` as well. If `<one_line_brief_description` is all that is provided, the docstring's second `"""` should be placed on the same line as the first `"""`. E.g. `"""<one_line_brief_description>"""`.

Specifications:
- `<one_line_brief_description>`. This exists on the same line as the opening `"""`. No space between `<one_line_brief_description>` and `"""`.

- `[multi_line_extended_description]`. This can be a multi-paragraph description of the program what the program does. It can mention parameters and outputs, but should not mention the specifications of the parameters and outputs, which should be done in `Parameters` and `Returns` instead.

- `Parameters`. Underlined with `==========`.  Parameters should be separated with a newline.

- `<parameter_name>`. The name of the parameter. Same indentation as `Parameters`.

- `<data_type>`. The accepted input types of the parameter. Multiple types can be strung together with `OR`. It doesn't have to be exhaustive, just try your best.

- `[default_value]`. If a default value exists, you can put it here.

- `<parameter_description>`. A description of what the parameter does. It should be indented from the <parameter_name> by one level.

- `Returns`. Underlined with `=======`.

- `<output_name>`. If there is no name you would like to mention, use `output` as the name. If there are multiple outputs, put them in parentheses, i.e. `(output1, output2, output2)`.

- `<output_description>`. Same as `<parameter_description>`.

- `Examples`. You are writing code examples to demonstrate how your function works? You are doing God's work, seriously.

- `<example_description>`. This is a freeform text to setup context for your example. Example:

- `<example>`. Code lines are prepended with `>>>` and output lines are not prepended with anything. Example:
```python
>>> a = np.array([47, 47, 47, 49, 50, 47, 47, 99])
>>> for i in get_constant_value_blocks(a, 47): print(i)
(0, 3)
(5, 7)
```

- `Notes`. This is a place to put miscellaneous information about the function. Does it have shortcomings that could be addressed in the future? Are there related functions the user should know about? Are there github issues associated with it? Does it replace the functionality of a relegated function? Were other algorithms tried but found to be inferior to the current implementation? Is there information online that provides more info on the topic? Everything that does not describe the functionality, but it is otherwise important, should go here.

- `References`. Things that deserve citation should go here.

- `references_text`. We do not have a convention, just cite everything as neatly as you can.

# Conclusion

Hopefully one day anvi'o's codebase will have docstrings for each function. And hopefully this document is useful in defining standards of uniformity.

**Comment by ekiefl** [comment]
@meren, what do you think about having a "contributing to anvi'o" portion to either the merenlab website, or as a wiki to the anvi'o github repo? This post could be one of the many topics covered.

**Comment by mooreryan** [comment]
@ekiefl A contribution guidelines doc would be nice...I was actually just searching around yesterday to see if there was one!

**Comment by mooreryan** [comment]
Another thing I was wondering, is anvio using something to auto-generate API docs from the docstrings?  If not, it may be a good idea to choose docstring conventions that work with a documentation generator.

Since I'm mainly coming from languages other than Python, I'm not really sure if there is a consensus "Pythonic" way to do API docs, or if you all would want them or not, but I did see a bunch of options here: https://wiki.python.org/moin/DocumentationTools.  The API documentation tools I've used in the past that use tags have been particularly nice to work with.  Something to consider!

**Comment by ekiefl** [comment]
That's a really good point. Maybe we could even scrap the conventions I mentioned and use a standard. That way, we can simply point to the standard. If anvi'o could get to API docs to this level it would help things immensely: https://pysam.readthedocs.io/en/latest/api.html

**Comment by meren** [comment]
> @meren, what do you think about having a "contributing to anvi'o" portion to either the merenlab website, or as a wiki to the anvi'o github repo? 

I think we can use the GitHub repo to develop one. Once the content is there, we can give links to it from everywhere.

> Another thing I was wondering, is anvio using something to auto-generate API docs from the docstrings?

This might be very useful indeed. I tried `pdoc`. It looks promising, but we may need to develop a template for it to match to Evan's dosctring standard (which I think pretty readable, intuitive, and close to other good examples).

If you would like to take a quick look,

```
pip install pdoc
cd /tmp
pdoc --html anvio.dbops
open anvio/dbops.m.html
```


Best,

**Comment by meren** [comment]
On the other hand, we have a very robust framework to generate user documentation for anvi'o artifacts and programs:

http://merenlab.org/software/anvio/help/

I have been recently thinking about extending it to developers with popular examples, too. For instance the artifact pan-db is an example:

http://merenlab.org/software/anvio/help/artifacts/pan-db/

I wonder we could somehow merge the two (i.e., `pan-db` artifact is associated with `dbops.PanDatabase` class, so the class and member funciton docstrings could be also collected to generate the help page for the `pan-db` artifact).

Just thinking out loud under an issue that is not most appropriate for this discussion :)
