### ISSUE TITLE
Clustering layer generated using anvi-experimental-organization not displayed in anvi-refined

### ISSUE THREAD

**Issue by cssulliv** [merenlab/anvio#1284]
Hi,

Details of my Anvi'o version/installation and  computer specifications  are described below for your reference.

```
Anvi'o version ...............................: margaret (v5.5)
Profile DB version ...........................: 31
Contigs DB version ...........................: 12
Pan DB version ...............................: 13
Genome data storage version ..................: 6
Auxiliary data storage version ...............: 2
Structure DB version .........................: 1
```

Anvi'o was installed using the following script: 

`conda create -n anvio5.5 -c bioconda -c conda-forge anvio=5.5.0`

My MacBook Pro (Retina, 15-inch, Mid-2015) runs on OSX 10.14.6 (Mojave).

Issue:

I essentially generated another cluster layer using `anvi-experimental-organization`
(full script shown below) so that I could cluster my splits, which are in a single profile, using kmers, coverage and gc content.

`anvi-experimental-organization 08_ANVIPROFILE_1362A_ver2/my_cluster_config.ini -i 08_ANVIPROFILE_1362A_ver2/ -c 06_CONTIGS_DB/metaspades_sample1_scaffold_1500.db -p 08_ANVIPROFILE_1362A_ver2/PROFILE.db  --name tnf_cov_gc -o 08_ANVIPROFILE_1362A_ver2/new_newick_tree_ver2.txt`

Within `anvi-interactive` I am able to see/use my clustering layer, tnf-cov-gc, as well as `Sequence Composition` and `tnf-ab-cov`. However, in the `anvi-refine` interface I am only able to see/use `Sequence Composition` and `tnf-ab-cov`. I have attached screen shots of my anvi-interactive and anvi-refine display and my_cluster_config.ini file.

Any suggestions on what could be causing this would be helpful. 

Thank you!

PS Anvio is great and this issue no way hinders the current analysis I am doing but am just curious if anyone else has attempted to generate their own clustering layer and utilized it with success in anvi-refine (and other modes). :)

  
[my_cluster_config.ini.zip](https://github.com/merenlab/anvio/files/3769448/my_cluster_config.ini.zip)

<img width="1161" alt="Anvi-interactive-display" src="https://user-images.githubusercontent.com/41393799/67524968-7c4f5780-f64d-11e9-9692-9e49af1188a5.png">
<img width="1273" alt="Anvi-refine-display" src="https://user-images.githubusercontent.com/41393799/67524969-7ce7ee00-f64d-11e9-8fba-b08e2e7bc4ad.png">

**Comment by meren** [comment]
Hi @cssulliv,

Interesting question, and I think there is a straightforward solution.

Briefly, `anvi-experimental-organization` works with additional recipes that are not recognized by the codebase as default. So for anvi'o to automatically utilize them, one must to put them in a relevant codebase directory. Which is simple, actually. For instance you are using your recipe with a single profile database.

So I assume you can run the following command to learn the relevant directory path on your own computer, and copy paste your clustering recipe into it:

```
python -c 'import anvio.data as d; import os; print(os.path.join(os.path.dirname(d.__file__), "clusterconfigs/single"))'
```

I believe, if you run `anvi-refine` after that, you will see your clustering in the combo box.

Please let me know if you try this.


Best,
