### ISSUE TITLE
Metagenomics workflow stops if bowtie2-build generates large index files with .bt2l extension

### ISSUE THREAD

**Issue by ozcan** [merenlab/anvio#1287]
In some cases explained in `bowtie2` documentation here[1] `bowtie2-build` creates long index files with `.bt2l` extension instead of `.bt2`. This case is not handled in our workflows. We could force `bowtie2-build` to always create long index files using ` --large-index` flag but that would cause too much memory consumption even though it is unnecessary.

[1] http://bowtie-bio.sourceforge.net/bowtie2/manual.shtml#small-and-large-indexes

**Comment by ShaiberAlon** [comment]
Thanks for figuring this out @ozcan. Is this an urgent issue or could this wait ?

**Comment by ozcan** [comment]
This is not urgent @ShaiberAlon, just wanted to note it here.

**Comment by ekiefl** [comment]
I solved this issue a while ago. If `--large-index` is passed as a bowtie parameter, `.bt2l` files are passed and handled.

**Comment by ShaiberAlon** [comment]
Thank you @ekiefl !

**Comment by ozcan** [comment]
Thank you @ekiefl, This is a good workaround but unfortunately it comes with a cost, most of the time only couple of bam files will exceed the large bam file threshold. If you provide `--large-index` bowtie will force/treat every bam file as they are above the size threshold. Which will cost memory consumption and slow down the process in general, otherwise this flag would be default in bowtie2.

While first I got told about this problem during EBAME I found the link below:
https://github.com/EnvGen/snakemake-workflows/blob/master/bio/ngs/rules/mapping/bowtie2.rules
which forks the workflow to two different paths regarding of the bowtie output. Unfortunately I have no experience with snakemake. If you understand what is going on there, this implementation makes much more sense to me, What do you guys think?

**Comment by ekiefl** [comment]
@ozcan, `--large-index` is a flag for the build (i.e what is being mapped onto). It has nothing to do with the size of `.bam` files.

But this could be a problem if the user has many fasta files they want to map onto. Since `--large-index` is passed for the whole workflow, all of the `bowtie-build`s will be `.bt2`. In an ideal world, we would try `bowtie-build`. If it fails because index is too large, then we re-run with `--large-index` so `.bt2l` files are created.

But the case of multiple fasta files is somewhat rare, because typically if the user has many fasta files they want to map onto, they want to map competitively (which requires all the fastas are merged into one, so no problems). If they really want multiple fasta files, and some would require `--large-index` and others would not, as a work around they can them separately.

**Comment by ozcan** [comment]
@ekiefl From the manual:
Small and large indexes
bowtie2-build can index reference genomes of any size. For genomes less than about 4 billion nucleotides in length, bowtie2-build builds a “small” index using 32-bit numbers in various parts of the index. When the genome is longer, bowtie2-build builds a “large” index using 64-bit numbers. 

So with passing `--large-index` always, you are assuming every input file has greater than 4 billion nucleotides in it. Which is not the case for many projects. In a regular project only fraction of the inputs will exceed 4 billion nucleotides as we almost never ran into this problem before. The rest could be indexed using 32bit numbers. 

So my suggestion is that instead of forcing bowtie to use 64 bit always with a flag, snakemake workflow should pick up what bowtie determined by itself and just use it as it is.

Also I am little confused about single/multiple fasta thing, even if you have single fasta if you have >4b nts you need large indexes. Am I getting this wrong?

**Comment by ShaiberAlon** [comment]
I agree with @ozcan that the current solution is not ideal. I missed that point when I looked at your solution.

I think we should adopt the design in the link that Ozcan provided. I think that I understand the design in that link, but I admit that I’m not 100% sure that I understand it correctly.

**Comment by ekiefl** [comment]
@ozcan I think we are saying the same thing now. It's an issue of reference genomes, not bam files.

I think a new issue should be made. This issue has been resolved if you read the title @ShaiberAlon.

**Comment by ozcan** [comment]
I also do not understand that solution but seems more generalized. I thought Evan or You might understand.
