### ISSUE TITLE
Issues during the Pangenomic workflow

### ISSUE THREAD

**Issue by kevin-lab** [merenlab/anvio#1288]
Hey anvio-Team,

I actually have a list of some errors I was running though when I try to do my work.

Current setup: anvio5.5 on my laptop ; anvio6 on my desktop computer

Basically the errors occurred during my work with pangenomic workflow:

I did the whole analysis from $ anvi-gen-contigs-database until $ anvi-pan-genome.
Everything worked well so far.

Now I wanted to run anvi-display-pan on PROJECT-MY-GENOME.db  as shown here:

$ anvi-display-pan -p '/media/kevin/DATA/OUTPUT2/BacteroidesTest/Bacteroides-PAN.db' -g '/media/kevin/DATA/OUTPUT2/BacteroidesTest/Bacteroides-PAN.db' 

and I get the following error message: 

``` 
Interactive mode .............................: pan  
        
Config Error: Bad news of the day: the database at                                            
              /media/kevin/DATA/OUTPUT2/BacteroidesTest/Bacteroides-PAN.db was generated with 
              an anvi'o version that is 'newer' than the one you are actively using right now.
              We know, you hate to hear this, but you need to upgrade your anvi'o :(     
```

Afterwards I did the whole analysis on my laptop as well and I gives me the same error message.
Even when the Analysis is done, the command before in the terminal. (which actually shows that it is the same version)

I decided to install the latest version (6.1) on my laptop though the easy conda install guide (http://merenlab.org/2016/06/26/installation-v2/ ) and it keeps installing the 5.5 Version.

```
(anvio-6.1) kevin@kevin-G73Jh:~$ anvi-self-test --version
Anvi'o version ...............................: margaret (v5.5)
Profile DB version ...........................: 31
Contigs DB version ...........................: 12
Pan DB version ...............................: 13
Genome data storage version ..................: 6
Auxiliary data storage version ...............: 2
Structure DB version .........................: 1

```

```
And when I run the $ anvi-self-test –suite mini I m facing this issue: 

Traceback (most recent call last):
  File "/home/kevin/miniconda3/envs/anvio-6.1/bin/anvi-run-hmms", line 17, in <module>
    from anvio.terminal import time_program
ImportError: cannot import name 'time_program'

```

For my Computer, the Installation of anvio6 worked when I tried the conda easy install guide.
(Back when it was 6.0, didnt try the Installation of the 6.1 version)

Now, I did the anvio-master installation(on my laptop), also provided under the same link.
It worked so far and it installed the correct version.

```
(anvio-master) (anvio-master) kevin@kevin-G73Jh:~$ anvi-self-test --version
Anvi'o version ...............................: esther (v6.1-master)
Profile DB version ...........................: 31
Contigs DB version ...........................: 14
Pan DB version ...............................: 13
Genome data storage version ..................: 6
Auxiliary data storage version ...............: 2
Structure DB version .........................: 1
```

But when I try to run: anvi-self-test –suite mini 
I get the following error:

``` Traceback (most recent call last):
  File "/home/kevin/.local/bin/anvi-profile", line 56, in <module>
    groupM.add_argument(*anvio.A('include-orphans'), **anvio.K('include-orphans'))
  File "/home/kevin/github/anvio/anvio/__init__.py", line 2113, in A
    return D[param_id][0]
KeyError: 'include-orphans'


Config Error: According to the exit code ('1'), anvi'o suspects that something may have gone
              wrong while running your tests :/ We hope that the reason is clear to you from
              the lines above. But if you don't see anything obvious, and especially if the 
              test ended up running until the end with reasonable looking final results, you
              shouldn't worry too much about this error. Life is short and we all can worry 
              just a bit less.   ```

Thanks,

**Comment by meren** [comment]
Hi @kevin-lab,

It seems your computer is confused with multiple installations of anvi'o as they keep interfering with each other. It is very hard to address this from here.

One of the things you can do is to find all anvi'o installations and remove them until there is nothing left on your computer that is anvi'o related. Then install it by following the online guide to install it.


Best wishes,
