### ISSUE TITLE
Homogeneity indices of some genes with conserved motifs being -1

### ISSUE THREAD

**Issue by AKBode** [merenlab/anvio#1291]
Hi Anvio developers,

In the pangenome of 16 strains, the homogeneity indices (both geometric and functional) of genes I'm interested in are all -1. These genes encode non-ribosomal peptide synthetases with highly conserved motifs exist across every single strain. The version I used is 6.1. 

With thanks in advance,

Albert E

**Comment by meren** [comment]
Dear @AKBode,

Thank you very much for taking the time to report this. The `-1` value in summary outputs and in the interface represents gene clusters for which the alignment failed for some reason. Unfortunately there is nothing much we can do about this :/


Best wishes,
