### ISSUE TITLE
anvi-summarize should allow to reformat contig names

### ISSUE THREAD

**Issue by ShaiberAlon** [merenlab/anvio#1292]
This is a suggested feature:

When running a summarize on a PROFILE database, it would be nice if there was a flag `--reformat-contig-names` that makes it so that the FASTA files generated for each bin in the collection would have headers with format: `bin_name_0000000000001`, `bin_name_0000000000002`, etc. 

This would be an easy way to make sure that when you are done with a project you have nice FASTA files with contig names that match the MAG name.

**Comment by meren** [comment]
I think it is a risk to have contig names in summary output that don't match to the contig names in the contigs database, but an optional flag wouldn't hurt, especially also if we provide a report file in the summary output directory regarding name changes.

**Comment by meren** [comment]
I HOPE YOU'RE HAPPY, ALON.

**Comment by ShaiberAlon** [comment]
I'm happy :-)

Thank you Meren!

There is one thing that confused me though. I wanted to add this to `run_all_tests.sh`:

```bash
INFO "Run quick summary of CONCOCT results"
anvi-summarize -p $output_dir/SAMPLES-MERGED/PROFILE.db \
               -c $output_dir/CONTIGS.db \
               -o $output_dir/SAMPLES-MERGED-SUMMARY-QUICK \
               -C 'cmdline_concoct_RENAMED' \
               --reformat-contig-names \
               --quick-summary
```

I always thought that the quick summary generated FASTA files, but this is all I found:

```
$ ls -R sandbox/test-output/temp/
bin_by_bin	index.html

sandbox/test-output/temp//bin_by_bin:
PSAMPLES_Bin_00001	PSAMPLES_Bin_00002	PSAMPLES_Bin_00003

sandbox/test-output/temp//bin_by_bin/PSAMPLES_Bin_00001:
PSAMPLES_Bin_00001-GC_content.txt		PSAMPLES_Bin_00001-percent_completion.txt	PSAMPLES_Bin_00001-scg_domain.txt
PSAMPLES_Bin_00001-N50.txt			PSAMPLES_Bin_00001-percent_redundancy.txt	PSAMPLES_Bin_00001-scg_domain_confidence.txt

sandbox/test-output/temp//bin_by_bin/PSAMPLES_Bin_00002:
PSAMPLES_Bin_00002-GC_content.txt		PSAMPLES_Bin_00002-percent_completion.txt	PSAMPLES_Bin_00002-scg_domain.txt
PSAMPLES_Bin_00002-N50.txt			PSAMPLES_Bin_00002-percent_redundancy.txt	PSAMPLES_Bin_00002-scg_domain_confidence.txt

sandbox/test-output/temp//bin_by_bin/PSAMPLES_Bin_00003:
PSAMPLES_Bin_00003-GC_content.txt		PSAMPLES_Bin_00003-percent_completion.txt	PSAMPLES_Bin_00003-scg_domain.txt
PSAMPLES_Bin_00003-N50.txt			PSAMPLES_Bin_00003-percent_redundancy.txt	PSAMPLES_Bin_00003-scg_domain_confidence.txt
```

Is this what's supposed to happen?

**Comment by meren** [comment]
No, quick summary does not generate FASTA files. It is a stupid flag as it is now because thanks to `anvi-estimate-genome-completeness`, it became irrelevant. Perhaps it _should_ now generate FASTA files though so it is useful for something :)
