### ISSUE TITLE
Add "Workflow version" to anvi'o versioning system.

### ISSUE THREAD

**Issue by ShaiberAlon** [merenlab/anvio#1307]
Inspired by [Sunbeam](https://sunbeam.readthedocs.io/en/latest/index.html)'s versioning approach, I wonder if we should add a versioning scheme for our workflows.

Similar to database versions, anvi'o could have `Workflows version`. We can then add a `version` value to config files so that we can track compatibility.

We can then choose how comprehensive we want to be, and implement one of the following options:
1. Provide upgrade scripts.
2. Provide a warning saying to proceed with care since things changed.
3. Raise an error and tell the user to create a new config file.

With this versioning system, similar to our database versions, minor enhancements and bug fixes would not change workflow versions, but things that could make old config files incompatible would change the workflow version.

**Comment by meren** [comment]
Absolutely :)

The version of the workflows can follow the template in `anvio/__init__.py`, which can be checked in the workflows base class.

We will then have to make a small adjustment to `anvi-migrate` so it doesn't complain when it sees JSON files.

**Comment by ekiefl** [comment]
What is the status on this? I think this is now implemented.

**Comment by meren** [comment]
It is! :)
