### ISSUE TITLE
 anvi-delete-misc-data: Removing keys that have a space in the name. 

### ISSUE THREAD

**Issue by cssulliv** [merenlab/anvio#1308]
Hi, 

Anvio information on local computer (MacBook, OSX Mojave)
```
Anvi'o version ...............................: esther (v6.1-master)
Profile DB version ...........................: 31
Contigs DB version ...........................: 14
Pan DB version ...............................: 13
Genome data storage version ..................: 6
Auxiliary data storage version ...............: 2
Structure DB version .........................: 1
```

I am trying to delete some misc. layer data from my pangenome. The key I would like to remove unfortunately has a space at the end ( ex. categorical ). I’ve tried running the `anvi-delete-misc-data` with the following flag `--keys-to-remove 'categorical '` but that did not work. I’ve also tried it with `--keys-to-remove "categorical "` and that didn’t work either. 

Luckily this was a test run on a pangenome that hasn't been fully analyzed and I was able to start over. But I just wanted to document and submit this in case anyone else has experienced something similar. 

Best,
cssulliv

**Comment by meren** [comment]
Thank you very much for your report, @cssulliv. This is now fixed in `master`.
