### ISSUE TITLE
add anvi-cluster-contigs to the metagenomics workflow

### ISSUE THREAD

**Issue by ShaiberAlon** [merenlab/anvio#1309]
Here is the description of what I want:
This grants the option to specify one or more clustering algorithms.

The config parameters would look like this:
```json
    "anvi_cluster_contigs": {
        "----collection-name": "{driver}",
        "--driver": [ "concoct", "metabat2", "maxbin2", "dastool", "binsanity" ], # users should only include the clustering algorithm/s that they want
        "--just-do-it": false,
        "--additional-params-ALGORITHM-NAME": ""
```

We will learn which modules are available by reading `driver_modules['binning'].keys()`, and hence we will provide an option to provide `--additional-params` for each (for example `--additional-params-concoct`).

There will be a sanity check that makes sure that additional params have only been provided for algorithms that are listed in `--driver`.

**Comment by ShaiberAlon** [comment]
So implemented this, and this is how the rule looks like in the config:
```
    "anvi_cluster_contigs": {
        "--collection-name": "{driver}",
        "run": "",
        "--driver": "",
        "--just-do-it": "",
        "--additional-params-concoct": "",
        "--additional-params-metabat2": "",
        "--additional-params-maxbin2": "",
        "--additional-params-dastool": "",
        "--additional-params-binsanity": "",
        "threads": ""
    },
```

**Comment by meren** [comment]
Why not a single additional-params parameter?

**Comment by ShaiberAlon** [comment]
The user can specify multiple algorithms to run on their profile database. Each of these have their own parameters and so the user would have to specify parameters separately for each algorithm.

Does that make sense?

**Comment by ShaiberAlon** [comment]
This was closed via #1310

**Comment by meren** [comment]
Ah, sorry, I didn't realize the driver parameter was accepting a list.

**Comment by ShaiberAlon** [comment]
Ok, I was too quick to merge and declare success. I don't know why but all three clustering algorithms that I have tried seem to be broken on my local (`concoct`, `metabat2`, `maxbin2`). I installed `metabat2` and `maxbin2` just now with conda, but they don't seem to work.

@meren, would you mind saving and running the following test in your `anvio/tests` directory:

```
#!/bin/bash
source 00.sh

# Setup #############################
SETUP_WITH_OUTPUT_DIR $1
#####################################

INFO "Setting up the metagenomics analysis directory"
mkdir $output_dir/workflow_test
cp -r $files/workflows/metagenomics/* $output_dir/workflow_test/
cd $output_dir/workflow_test

anvi-run-workflow -w metagenomics --config config-references-mode.json
```

It expects you to have `concoct` and `maxbin2`, which I think you have on your local. I couldn't get either to work right now...

**Comment by ShaiberAlon** [comment]
This feature is now documented in the tutorial here: http://merenlab.org/2018/07/09/anvio-snakemake-workflows/#running-binning-algorithms
