### ISSUE TITLE
Can't open anvi-interactive without running default HMMs, can't distinguish anvi 5.5 and anvi 6 HMMs in anvi-refine

### ISSUE THREAD

**Issue by watsonar** [merenlab/anvio#1311]
Hello friends,

I am using anvio v6.1-master. However, I am trying to use the SCG collections from anvio 5.5. I used anvio master to run anvio 5.5 HMMs like this:

```bash
anvi-run-hmms -c contigs.db -H anvi-5.5-hmms/Campbell_et_al/
```

This worked great! But when I tried to look at these contigs in anvi-interactive with the following command:
```bash
anvi-interactive -c contigs.db -p PROFILE.db -C MAGs_collection
```
I received the following error:
```
[05 Dec 19 13:37:57 Additional layers for bins] 1 of 128 :: CP_MAG_00107 ...                                                                                               Traceback (most recent call last):
  File "/project2/meren/VIRTUAL-ENVS/anvio-master/anvio/bin/anvi-interactive", line 120, in <module>
    d = interactive.Interactive(args)
  File "/project2/meren/VIRTUAL-ENVS/anvio-master/anvio/anvio/interactive.py", line 212, in __init__
    self.load_collection_mode()
  File "/project2/meren/VIRTUAL-ENVS/anvio-master/anvio/anvio/interactive.py", line 877, in load_collection_mode
    p_completion, p_redundancy, domain, domain_probabilities, info_text, _ = completeness.get_info_for_splits(set(self.collection[bin_id]))
  File "/project2/meren/VIRTUAL-ENVS/anvio-master/anvio/anvio/completeness.py", line 389, in get_info_for_splits
    best_matching_domain, domain_probabilities, control_domains, info_text = self.get_best_matching_domain(scg_hmm_hits, observed_genes_per_domain, bin_name)
  File "/project2/meren/VIRTUAL-ENVS/anvio-master/anvio/anvio/completeness.py", line 215, in get_best_matching_domain
    best_mathcing_domain_completion, best_matching_domain_redundancy = hmm_hits[best_matching_domain][source]['percent_completion'], \
KeyError: 'Bacteria_71'
```

To get around this, I had to run anvio master's default HMMs on my contigs db as well. Should this have been necessary?

At this point, the HMM sources in my contigs database are these:
```
* sialic_acid_hmms [type: sialic_acid] [num genes: 10]
* Campbell_et_al [type: singlecopy] [num genes: 139]
* BUSCO_83_Protista [type: singlecopy] [num genes: 83]
* Rinke_et_al [type: singlecopy] [num genes: 162]
* Ribosomal_RNAs [type: Ribosomal_RNAs] [num genes: 12]
* Protista_83 [type: singlecopy] [num genes: 83]
* Bacteria_71 [type: singlecopy] [num genes: 71]
* Archaea_76 [type: singlecopy] [num genes: 76]
```

This led me to discover something strange in anvi-refine. When I open at a bin from this contigs db in anvi-refine, select some splits, and then click on the completion and redundancy percentages in the 'Bins' tab, I get a pop-up that looks like this:

![image](https://user-images.githubusercontent.com/31998264/70341010-92892f80-1817-11ea-9999-88518726a1ef.png)

I can't tell which bacteria or archaea HMM source is which (the eukarya ones are the same, that was my bad for not noticing that the eukarya SCG collection remained the same between anvio 5.5 and 6).

I feel like the anvio 5.5 HMMs shouldn't be displayed in this panel, just like the sialic acid HMMs are not shown. Alternatively, it would be really nice if I could have opened anvi-interactive and anvi-refine without running the new anvio 6 default HMMs, and just seen this information for the old anvio 5.5 SCG collections.

I recognize that I'm doing something a bit weird here, using the anvio 5.5 SCG collections in anvio 6, so this might not be a high priority issue. But I'm trying to avoid re-doing the binning I did with the old SCG collections while also taking advantage of anvio 6's sweet new features. So I figured I'd document it anyway. :) 

Note: I will provide the exact commands and directory paths as a comment on this issue in the Meren lab slack github channel.

**Comment by meren** [comment]
You are completely right on a bunch of things, @watsonar.

> I can't tell which bacteria or archaea HMM source is which

you should be able to: we should update the codebase so if there are multiple, anvi'o shows origin of the SCGs.

> I feel like the anvio 5.5 HMMs shouldn't be displayed in this panel, just like the sialic acid HMMs are not shown

I don't think this is a good idea. because this would prevent people to be able to come up with their own SCGs and see them here. any HMM that declares itself as a 'singlecopy' like [this](https://github.com/merenlab/anvio/blob/master/anvio/data/hmm/Bacteria_71/kind.txt), is treated as such and shown everywhere. but,

> But I'm trying to avoid re-doing the binning I did with the old SCG collections while also taking advantage of anvio 6's sweet new features

anvi'o should not prevent this.

Can you tell me what happens when you run `anvi-estimate-genome-completion` on the terminal?

**Comment by watsonar** [comment]
When I run anvi-estimate-genome-completion on the collection, I get a normal looking output, like this:
```
Bins in collection "CP_MAGs_collection"
===============================================
╒══════════════╤══════════╤══════════════╤════════════════╤════════════════╤══════════════╤════════════════╕
│ bin name     │ domain   │   confidence │   % completion │   % redundancy │   num_splits │   total length │
╞══════════════╪══════════╪══════════════╪════════════════╪════════════════╪══════════════╪════════════════╡
│ CP_MAG_00107 │ BACTERIA │            1 │          87.32 │           4.23 │          180 │        1151945 │
├──────────────┼──────────┼──────────────┼────────────────┼────────────────┼──────────────┼────────────────┤
```
etc. and no errors. I don't know which SCGs are being used to show completeness and redundancy here, but I assume it's the anvio 6 ones, because some of my genomes are less than 70% complete, which I'm pretty sure was my cutoff for classifying bins as MAGs when using the anvio 5.5 SCGs.

**Comment by meren** [comment]
Hey Andrea,

I did my best to solve this issue. Now when you have old and new HMM sources together, this is what you see in the interface:

![image](https://user-images.githubusercontent.com/197307/70658288-4e38cd80-1c23-11ea-871d-ac4b84d24a24.png)

When you have only the old ones, you still can visualize things, and this is what you see (anvi'o just doesn't know how to predict the domain):

![image](https://user-images.githubusercontent.com/197307/70658342-6872ab80-1c23-11ea-9b71-e2e355f4eb20.png)

And in the case you only have the old ones, this is what the command line shows:

```
Salmonella_bongori_21111-OLD (num_splits: 2; total_length: 4,773,537)
==============================================================
╒══════════╤═══════════════════╤════════════════╤════════════════╕
│ domain   │ source            │   % completion │   % redundancy │
╞══════════╪═══════════════════╪════════════════╪════════════════╡
│ ARCHAEA  │ Rinke_et_al       │          48.77 │           6.79 │
├──────────┼───────────────────┼────────────────┼────────────────┤
│ EUKARYA  │ BUSCO_83_Protista │           6.02 │              0 │
├──────────┼───────────────────┼────────────────┼────────────────┤
│ BACTERIA │ Campbell_et_al    │          98.56 │              0 │
╘══════════╧═══════════════════╧════════════════╧════════════════╛
```

Please test it and let me know if it is working as expected when you only have `v5.5` HMMs in your contigs database.

Thank you!

**Comment by watsonar** [comment]
Thank you, Meren! It is working as expected, I see what you do when using anvi-refine, and my anvi-estimate-genome-completeness output is very similar:
```
CP_MAG_00107 (num_splits: 180; total_length: 1,151,945)
==============================================================
╒══════════╤════════════════╤════════════════╤════════════════╕
│ domain   │ source         │   % completion │   % redundancy │
╞══════════╪════════════════╪════════════════╪════════════════╡
│ ARCHAEA  │ Rinke_et_al    │          32.72 │            3.7 │
├──────────┼────────────────┼────────────────┼────────────────┤
│ BACTERIA │ Campbell_et_al │          81.29 │            3.6 │
╘══════════╧════════════════╧════════════════╧════════════════╛
```
etc. :)

**Comment by meren** [comment]
👍
