### ISSUE TITLE
Config Error: Something is wrong. For each domain, there must be a single sinlge-copy core               gene source. 

### ISSUE THREAD

**Issue by sneupane04** [merenlab/anvio#1314]
Hi,
I am using: 
Anvi'o version ...............................: esther (v6)
Profile DB version ...........................: 31
Contigs DB version ...........................: 14
Pan DB version ...............................: 13
Genome data storage version ..................: 6
Auxiliary data storage version ...............: 2
Structure DB version .........................: 1

I am using example from http://merenlab.org/2017/06/07/phylogenomics/

But pangenomics is not being run and showing following error:
anvi-gen-genomes-storage -e external-genomes.txt \
>                          -o Salmonella-GENOMES.db

WARNING
===============================================
None of your genomes seem to have any functional annotation. No biggie. Things
will continue to work. But then your genomes have no functional annotation. SAD.

Internal genomes .............................: 0 have been initialized.                                                             
[10 Dec 19 23:20:12 Initializing external genomes] working on S_enterica_01                                                          

**Config Error: Something is wrong. For each domain, there must be a single sinlge-copy core
              gene source.**                  

What could be the reason? And please suggest me solving this.

Thank You

**Comment by meren** [comment]
Did you run `anvi-run-hmms` on each contigs database?

What is the output of this command when you run on one of the contigs databases described in external-genomes.txt?

```
anvi-delete-hmms -c SOMETHING-contigs.db --list
```
