### ISSUE TITLE
warning about needed and missing programs in anvio workflows is missleading

### ISSUE THREAD

**Issue by ShaiberAlon** [merenlab/anvio#1316]
Since the program doesn't check your specific DAG, it always warns about ALL programs that could potentially be used by the workflow (in fact, not even all, because there are some potential dependencies such as FastANI, pyANI, METABAT2, etc which it doesn't check for.

In any case, the warning should change so that the user know that it doesn't necessarily apply to their specific config. Alternatively, we could check what the DAG includes, but that would require much more work.

**Comment by ekiefl** [comment]
I took a quick look but as you say @ShaiberAlon, it requires first building the DAG and would require a lot more effort.
