### ISSUE TITLE
Docker image for anvi'o: write /var/lib/docker/tmp/GetImageBlob436185000: no space left on device

### ISSUE THREAD

**Issue by 473021677** [merenlab/anvio#1319]
Hi:
I am trying to use anvi'o without installing it. The Linux server operating system is centos. I have run an anvi'o container as follows:
     ```
docker --version
Docker version 1.13.1, build b2f74b2/1.13.1
docker pull meren/anvio
Trying to pull repository docker.io/meren/anvio ... 
latest: Pulling from docker.io/meren/anvio
1ab2bdfe9778: Pull complete 
dd7d28bd8be5: Downloading [==================>                                ]  30.1 MB/80.01 MB
af998e3a361b: Downloading [================================================>  ] 53.39 MB/55 MB
31c72f120452: Download complete 
22e1de242342: Downloading [==================================================>]    170 B/170 B
e399a0d89947: Downloading [>                                                  ] 2.669 MB/166.1 MB
c071a9e3f486: Waiting 
32c497e94677: Waiting 
c00075914c29: Waiting 
cc525c668a42: Pulling fs layer 
9649be1b1081: Waiting 
f8a9f044a900: Waiting 
b9968d86ce36: Waiting 
68e6ea52c1a5: Waiting 
b99b02eba0ea: Waiting 
3c62a743112e: Pulling fs layer 
8f6b016bd9bf: Waiting 
336a6ba11fc8: Waiting 
a2eac5327b92: Waiting 
4e2bbd75048b: Pulling fs layer 
a7284029fb3c: Waiting 
240e2261ccaf: Waiting 
f89cc23ae093: Pulling fs layer 
34430219a86a: Waiting 
1bcbdf133c24: Pulling fs layer 
3c413e2bff50: Waiting 
b4773531cce5: Pulling fs layer 
03919f99a132: Pulling fs layer 
write /var/lib/docker/tmp/GetImageBlob436185000: no space left on device
      ```
So I typed "df -h" and the following things showed:
 Filesystem               Size  Used Avail Use% Mounted on
/dev/mapper/centos-root   50G   49G  1.9G  97% /
devtmpfs                 756G     0  756G   0% /dev
tmpfs                    756G   60M  756G   1% /dev/shm
tmpfs                    756G  733M  756G   1% /run
tmpfs                    756G     0  756G   0% /sys/fs/cgroup
/dev/sda2                497M  259M  238M  53% /boot
/dev/sda1                200M  9.5M  191M   5% /boot/efi
/dev/mapper/centos-root  100G   16M  100G   1% /tmp
/dev/mapper/centos-home  224G  220G  4.4G  99% /home
tmpfs                    152G   16K  152G   1% /run/user/42
/dev/sdd1                 41T   41T  378G 100% /data
/dev/sdc1                 10T  9.9T  167G  99% /software
tmpfs                    152G     0  152G   0% /run/user/0
tmpfs                    152G  4.0K  152G   1% /run/user/1035
tmpfs                    152G     0  152G   0% /run/user/1021
tmpfs                    152G     0  152G   0% /run/user/1010
tmpfs                    152G     0  152G   0% /run/user/1022
tmpfs                    152G     0  152G   0% /run/user/1031
tmpfs                    152G     0  152G   0% /run/user/1002
tmpfs                    152G     0  152G   0% /run/user/1050
tmpfs                    152G     0  152G   0% /run/user/1036
tmpfs                    152G     0  152G   0% /run/user/1003
You have mail in /var/spool/mail/root
There is only 1.9G available for the directory "/" but the latest docker images are quite big(~8 Gb). This maybe the reason for the failure. Could you tell me how I could solve this problem? Thanks!

Best regards,
Yuan

**Comment by meren** [comment]
Please talk to your local bioinformatics guru.
