### ISSUE TITLE
How to merge Profile.db obtained from different contigs.db

### ISSUE THREAD

**Issue by Adarsh931** [merenlab/anvio#1321]
Hello,
I recently started using anvi'o tool for metagenomic analysis. I have 4 assembled reads, obtained from the same sample, but using different purification methods or assemblers. I was wondering if we can use anvi'o to merge all the profile.db (4 in this case) to obtain a single profile.db file using all the contig.db (4 in this case), or if a similar thing can be done for contig.db files. This will help me to get all the features in a single contig.db and profile.db which will make analysis easier (to get whole genome in this case).

Thanks in advance!

**Comment by meren** [comment]
Hi @Adarsh931,

You can only merge profile databases associated with a single contigs database.

Take a look at these two papers that had to solve a similar problem with anvi'o (i.e., having multiple contigs databases):

- https://www.nature.com/articles/s41467-019-08973-w
- https://www.nature.com/articles/s41564-018-0176-9

They both have reproducible workflows to clarify analysis steps. If you need any help with those feel free to write to us on Slack or Google Forums ([more info on ways to reach us](http://merenlab.org/2019/10/07/getting-help/)) as we try to keep GitHub for technical issues.

Best wishes,
