### ISSUE TITLE
anvi-run-workflow ignores --external-gene-calls in config.json

### ISSUE THREAD

**Issue by ekiefl** [merenlab/anvio#1323]
On master, the external genes file parameter supplied in the `config.json` is not respected in `anvi-run-workflow -w contigs`. Here is the `config.json`:

```
{
    "workflow_name": "contigs",
    "fasta_txt": "fasta_chimera_test.txt",
    "anvi_gen_contigs_database": {
        "--project-name": "{group}",
        "--description": "",
        "--skip-gene-calling": "",
        "--external-gene-calls": "10_GENOME_CLUSTER_PANGENOMES/{group}/CHIMERA/gene_calls.txt",
        "--ignore-internal-stop-codons": true,
        "--skip-mindful-splitting": "",
        "--contigs-fasta": "",
        "--split-length": "",
        "--kmer-size": "",
        "--prodigal-translation-table": "",
        "threads": ""
    },
    "output_dirs": {
        "CONTIGS_DIR": "00_DELETE",
        "LOGS_DIR": "00_DELETE2"
    },
    "config_version": "1"
}
```

And here is one of the commands submitted by snakemake:

```
[Sun Jan  5 21:02:36 2020]
rule anvi_gen_contigs_database:
    input: 10_GENOME_CLUSTER_PANGENOMES/cluster_000002/CHIMERA/chimeric_genome.fa
    output: 00_DELETE/cluster_000002-contigs.db
    log: 00_DELETE2/cluster_000002-anvi_gen_contigs_database.log
    jobid: 4
    wildcards: group=cluster_000002
    resources: nodes=1
anvi-gen-contigs-database -f 10_GENOME_CLUSTER_PANGENOMES/cluster_000001/CHIMERA/chimeric_genome.fa -o 00_DELETE/cluster_000001-contigs.db   --project-name cluster_000001   --ignore-internal-stop-codons     >> 00_DELETE2/cluster_000001-anvi_gen_contigs_database.log 2>&1
```

You can see that the `--external-gene-calls` parameter is never passed to snakemake.

Script for reproducing can be found on merenlab #github channel.

**Comment by ShaiberAlon** [comment]
@ekiefl, just wanted to let you know that I saw this. I will probably be able to take a look at this in about two weeks, but not likely that I will get to this beforehand.

**Comment by ekiefl** [comment]
The workaround is to add another column to the fasta.txt with the header `external_gene_calls`.

**Comment by meren** [comment]
> When you specify an external gene calls file in your fasta.txt file, then anvi-run-workflow will use these gene calls instead of running Prodigal.

From [here](http://merenlab.org/2019/03/14/ncbi-genome-download-magic/#excluding-the-gene-calls-from-the-fastatxt-file). When you test the workflow described there, is it no longer working?

**Comment by ekiefl** [comment]
hey @meren. The use case in the example you point out is what does work, i.e. specifying external gene calls via the fasta.txt. What doesn't work is passing wildcards to the "--external-gene-calls" parameter provided in the default config json, like in the above config.json I posted. Does this answer your question?

I think the solution is to remove "--external-gene-calls" parameter from the config, since anvi'o never reads it. I considered removing it, but it looks like these parameters are generated programmatically and I don't feel equipped to start messing around with that.

**Comment by meren** [comment]
Ah, sorry I missed the beginning of the convo. Yes, it makes perfect sense to remove `--external-gene-calls` from the config for contigs workflow.

**Comment by ShaiberAlon** [comment]
Has it already been two weeks? ;-)

**Comment by meren** [comment]
> Has it already been two weeks?

I am not sure about this one but it certainly has been more than 2 weeks since you said it would be about 2 weeks for something else :p

Something else that will be public on December 16.

**Comment by ekiefl** [comment]
> Has it already been two weeks? ;-)

Haha this is why putting things in writing is always a bad idea.
