### ISSUE TITLE
for anvi-compute-genome-similarity: --min-alignment-fraction should only affect what is imported into the pangenome

### ISSUE THREAD

**Issue by ShaiberAlon** [merenlab/anvio#1327]
I suggest to change the behaviour of the flag `--min-alignment-fraction` for `anvi-compute-genome-similarity`.

I suggest the following changes:
1. I think this flag should only be relevant when importing the info into the PAN database.
2. The flag should only impact the values that are imported into the PAN database.
3. It should leave the raw tables from the ANI (or whatever genome similarity statistic was computed) as-is without changing them so that the user has the full results to explore (and to report).

I think it is important to report the full results of ANI, and that the `--min-alignment-fraction` is most important for the visualization, but that the raw results are in fact more useful for the data tables.

I acknowledge that this is a subjective issue, and feel free to close it if you disagree.

**Comment by ekiefl** [comment]
I see your concern. Yet many people will run `anvi-compute-genome-similarity` without providing a pangenome and will rightfully assume those filters are applied to the output data. I like the current implementation, as you get what you ask for. I think any filtering of this data solely for the purpose of visualization should be done by visualization code. I will close this for now.

**Comment by ShaiberAlon** [comment]
Makes sense.
