### ISSUE TITLE
String continuation across lines

### ISSUE THREAD

**Issue by semiller10** [merenlab/anvio#1330]
When strings are continued across lines in Anvi'o, they are split by the line continuation backslash symbol and the strings are aligned, as seen in the following example:

```python
raise ConfigError("A mighty creature is the germ, \
                   Though smaller than the pachyderm.")
```

This has been causing me some irritation using VSCode, as the default behavior when hitting return after the backslash is a single indent, not alignment with the previous string. And I haven't found an extension with a quick fix.

This style is not endorsed by PEP 8 ([Maximum Line Length](https://www.python.org/dev/peps/pep-0008/#maximum-line-length)), which states:
> The preferred way of wrapping long lines is by using Python's implied line continuation inside parentheses, brackets and braces. Long lines can be broken over multiple lines by wrapping expressions in parentheses. These should be used in preference to using a backslash for line continuation.

Here are examples of this style:

```python
raise ConfigError("His customary dwelling place "
                  "Is deep within the human race.")
```

```python
ogdennash = ("His childish pride he often pleases "
             "By giving people strange diseases.")
```

Meren prefers to keep the Anvi'o codebase consistent and has suggested the possibility of updating it with the PEP-compliant style. This would require a little script to update the codebase -- and the approval of you, the developers. Looking forward to hearing your opinions!

```python
postscript = ("Do you, my poppet, feel infirm? "
              "You probably contain a germ.")
```

**Comment by ekiefl** [comment]
I find it hard to remember or see whether a lines with a space, so does anyone have a problem with this:

```
postscript = ("Do you, my poppet, feel infirm?"
              " You probably contain a germ.")
```

instead of

```
postscript = ("Do you, my poppet, feel infirm? "
              "You probably contain a germ.")
```

**Comment by meren** [comment]
I don't have a problem with the previous one, @ekiefl, but since the latter seems to be what others outside of our group have also proposed, I say let's go with it.

**Comment by meren** [comment]
My proposed changes are now in PR #1331.

**Comment by meren** [comment]
With Evan's updates, I merged the changes.

Thank you all very much!
