### ISSUE TITLE
SCVs are currently ALWAYS calculated. --profile-SCVs only controls whether or not they are stored

### ISSUE THREAD

**Issue by ekiefl** [merenlab/anvio#1341]
https://github.com/merenlab/anvio/blob/6f99da878519fe9879fa8f190413949a62498231/anvio/profiler.py#L630

The only thing that prevents this line from running is --skip-SNVs

**Comment by meren** [comment]
Evan Kiefl of the House Boiphargaryen, First of His name, King of Anvians, and catcher of the biggest bugs.

**Comment by ekiefl** [comment]
fixed
