### ISSUE TITLE
anvi-cluster-contigs doesn't use split files it makes

### ISSUE THREAD

**Issue by kyakimovich** [merenlab/anvio#1347]
Hello, 

I have a question about the behaviour of anvi-cluster-contigs. I see anvio makes a bunch of input files, including the contigs and sequence_split fasta and txt files. But then when it goes to pass things to the cluster program im using, in this case concoct, it passes the non-split files. I have some super long contigs, so I'm wondering why anvi-cluster-contigs is not using the nice split files it made to run concoct. 

It runs this code:
concoct --coverage_file /home/kyak18/scratch/tempy/tmpea4wnoi6/contig_coverages.txt --composition_file /home/kyak18/scratch/tempy/tmpea4wnoi6/sequence_contigs.fa --basename /home/kyak18/scratch/tempy/tmpea4wnoi6 --threads 24

Doesn't use the sequence_splits.fa and split_coverages.txt files it makes. 

So then in the results files from concoct (looking at clustering_gt1000.csv) there is no info on the splits. 

Best,
Kurt

Anvi'o version ...............................: esther (v6.1-master)
Profile DB version ...........................: 31
Contigs DB version ...........................: 14
Pan DB version ...............................: 13
Genome data storage version ..................: 6
Auxiliary data storage version ...............: 2
Structure DB version .........................: 1

I am running a version I just compiled last week from the github files

Running on CentOS Linux 7

**Comment by ozcan** [comment]
Hi @kyakimovich,

`anvi-cluster-contigs` generates every possible input file in the beginning even before branching into a specific binning algorithm. So some files might be created even though they are not necessary. They will be removed unless `--debug` is passed.

If you think results are accurate you may just ignore extra input files. After making sure none of the algorithms need it we can remove them. But I am still in favor of keeping them as in future we might add another algorithm that utilizes them. Also, with a quick glance I can see that DasTool driver uses some split level data tables.

Do you think your results might be affected by this?

In the `concoct` tutorial, example usage shown as below:
```
concoct --composition_file contigs_10K.fa --coverage_file coverage_table.tsv -b concoct_output/
```
Which looks the same as what you posted
Best,
