### ISSUE TITLE
anvi-display-pan result does not show up in Chrome browser 

### ISSUE THREAD

**Issue by junglee0713** [merenlab/anvio#1351]
Hi, 

First of all, thank you for sharing this wonderful software! I am using anvio-6.1 with my MacBook Pro (macOS Catalina, version 10.15.2) which was installed via conda by following 

```
conda create -n anvio-6.1 python=3.6
conda activate anvio-6.1
conda install -y -c conda-forge -c bioconda anvio=6.1
conda install -y diamond=0.9.14
```
and Chrome is my default browser. Also the following is what I have when I run `anvi-self-test --version`:

```
Anvi'o version ...............................: esther (v6.1)
Profile DB version ...........................: 31
Contigs DB version ...........................: 14
Pan DB version ...............................: 13
Genome data storage version ..................: 6
Auxiliary data storage version ...............: 2
Structure DB version .........................: 1
```

So my problem is... when I ran 

```
anvi-display-pan -p Redding_OSU-PAN.db -g Redding_OSU_Cdiff-GENOMES.db
```
under `anvio-6.1` environment, the software seems to be running and a Chrome tab automatically opens up with `http://0.0.0.0:8080/app/index.html?rand=056f4040` in the address bar. However, I keep seeing "Loading" and nothing really happens. 

When I run the command `anvi-display-pan -p Redding_OSU-PAN.db -g Redding_OSU_Cdiff-GENOMES.db`, I do see a message `The server is now listening the port number "8080". When you are finished, press CTRL+C to terminate the server.` but it immediately shows a bash prompt `(anvio-6.1) 8c8590284d91:anvio_result leej39$`, although I didn't hit CTRL+C.

I would really appreciate it if you could please share your input regarding this problem.  Thank you!

**Comment by meren** [comment]
Hi @junglee0713, 

Please try this command instead:

```
sudo anvi-display-pan -p Redding_OSU-PAN.db -g Redding_OSU_Cdiff-GENOMES.db
```

**Comment by meren** [comment]
(it is about the operating system, and not anvi'o :))

**Comment by junglee0713** [comment]
Dear Dr. Eren,

It solved my issue like a magic! Thank you so much for your help!

Best,
Jung-Jin
