### ISSUE TITLE
Determining and collapsing redundancy- KeyError: 'average_nucleotide_identity'  

### ISSUE THREAD

**Issue by cssulliv** [merenlab/anvio#1353]
```
Anvi'o version ...............................: esther (v6.1)
Profile DB version ...........................: 31
Contigs DB version ...........................: 14
Pan DB version ...............................: 13
Genome data storage version ..................: 6
Auxiliary data storage version ...............: 2
Structure DB version .........................: 1
```

I am currently following the Recovering Microbial Genomes from TARA Oceans Metagenomes tutorial in the 'Determining and collapsing redundancy' section. When I run python` 03-gen-table-for-redundancy-analysis.py -m REDUNDANT-MAGs-STATS.txt -C REDUNDANT-MAGs-PEARSON.txt -i REDUNDANT-MAGs-ANI.txt -o MAGs-PAIRWISE-DATA.txt
` I get the following error:

```
Traceback (most recent call last):
  

  File "03-gen-table-for-redundancy-analysis.py", line 36, in <module>
    d = r.Redundancy(args)
  File "/tank/cssulliv_data/16_SNV_ANALYSIS_ANVIO6.1_redo/redundancy.py", line 119, in __init__
    self.create_data_from_tables(args)
  File "/tank/cssulliv_data/16_SNV_ANALYSIS_ANVIO6.1_redo/redundancy.py", line 157, in create_data_from_tables
    matching = my_dictionary(A('matching'), 'matching')
  File "/tank/cssulliv_data/16_SNV_ANALYSIS_ANVIO6.1_redo/redundancy.py", line 347, in __init__
    self.add_matching_results_to_dictionary(row)
  File "/tank/cssulliv_data/16_SNV_ANALYSIS_ANVIO6.1_redo/redundancy.py", line 354, in add_matching_results_to_dictionary
    d['average_nucleotide_identity'] = float(row['average_nucleotide_identity'])
KeyError: 'average_nucleotide_identity'  
```

I am running the script on our lab server. According to the interwebs KeyErrors occur when a key is not in a dictionary although I am not  sure how to implement changes to the script to remove the error. Also, I have attached the text files I used to run the above command just in case it is needed for reference. 

Thank you in advance for the help! 

[REDUNDANT-MAGs-STATS.txt](https://github.com/merenlab/anvio/files/4190727/REDUNDANT-MAGs-STATS.txt)
[REDUNDANT-MAGs-PEARSON.txt](https://github.com/merenlab/anvio/files/4190732/REDUNDANT-MAGs-PEARSON.txt)
[REDUNDANT-MAGs-ANI.txt](https://github.com/merenlab/anvio/files/4190737/REDUNDANT-MAGs-ANI.txt)

**Comment by meren** [comment]
That tutorial is only relevant for earlier versions of anvi'o (i.e., the exact version used for the study the reproducible workflow is for). We have a new program for these tasks now thanks to @ekiefl and @mahmoudyousef98's efforts: [anvi-dereplicate-genomes](http://merenlab.org/software/anvio/vignette/#anvi-dereplicate-genomes).

**Comment by cssulliv** [comment]
Oh how wonderful! Thank you @mahmoudyousef98 @ekiefl and the Anvio team! :)
