### ISSUE TITLE
add feature to anvi-refine to take a split name instead of bin name

### ISSUE THREAD

**Issue by kyakimovich** [merenlab/anvio#1354]
Following up on a convo on the google help group, summary pasted below:

Kurt: I've been exporting the collection info, searching it with grep, and then refining the bins that contain my contigs of interest. I was hoping there was a shortcut for this, as I have to re-export the collection info every time I refine some bins. I have a couple hundred bins, so this would help with my search for ones of interest. 

Meren: We can add a new parameter to `anvi-refine` that would take a collection name, and instead of a bin name a split name, so it would automatically resolve the split name to bin name and take you to refine it. Can you enter this as an issue so we can take care of this feature request?

Thanks,
Kurt

**Comment by meren** [comment]
#1355, which is now in `master` fixes this :) As described in #1355, one can use `anvi-refine` with a split name using the new parameter `--find-from-split-name` rather than using an explicit bin name.

Thank you very much for the feature request!


Best,
