### ISSUE TITLE
anvi-scan-trnas is missing from anvio/programs.py

### ISSUE THREAD

**Issue by FlorianTrigodet** [merenlab/anvio#1359]
Using the master version.

When running `anvi-help` command, I had this error:

```
Main anvi'o programs found ...................: 93
Anvi'o ad hoc scripts found ..................: 32
[19 Feb 20 08:08:22 Characterizing program] anvi-scan-trnas                                                                                   ETA: 28s

Config Error: Ehem. Anvi'o does not know about item 'trna-genes'. There are two was this could
              happen: one, you made a type (easy to fix), two, you just added a new program
              into anvi'o but have not yet updated `anvio/programs.py`.

**Comment by ReneKat** [comment]
Hello @FlorianTrigodet 
Try: 
`conda install -c bioconda trnascan-se`
See [issue #1279 ](https://github.com/merenlab/anvio/issues/1279#issuecomment-583860752). 

Hope that helps,
René

**Comment by meren** [comment]
Hi @ReneKat,

I'm afraid this particular issue is due to the missing information in one of the anvi'o modules, and this commit should be fixing it: 639466c2a8cb03750095ac809252abfa9559ec5f.

@FlorianTrigodet, can you please confirm and close the issue?

Thank you both very much.

**Comment by FlorianTrigodet** [comment]
It is working very well now!
Thank you very much @ReneKat and @meren.
