### ISSUE TITLE
Feature request:  support multi-threading in anvi-initi-bam

### ISSUE THREAD

**Issue by jaybake5** [merenlab/anvio#1360]
Hello Anvi'o team,
I am wondering if a possible future feature that may be useful would be the option to use multiple threads for anvi-init-bam, since the alternative, samtools sort and samtools index, do allow multithreading with the -@ flag.  Certainly not urgent or groundbreaking, but could be useful to reduce the time for huge metagenome .bam files.
As always, thanks very much for a great suite of tools.
Cheers,

Jon

```
$ anvi-init-bam --help
usage: anvi-init-bam [-h] [-o FILE_PATH] BAM_FILE

Sort/Index BAM files

positional arguments:
  BAM_FILE              BAM file to analyze

optional arguments:
  -h, --help            show this help message and exit
  -o FILE_PATH, --output-file FILE_PATH
                        File path to store results.
```

**Comment by ekiefl** [comment]
Hey @jaybake5, are you working on a dataset where this is taking a significant amount of time?

**Comment by jaybake5** [comment]
It's not an urgent request, but I have had situations where the .bam file was especially large (~40-100GB) and it did take a long time.  In those cases I ended up manually doing samtools index and sort with the -@ option to use many threads instead of doing `anvi-init-bam`.  If there was the option to multithread with `anvi-init-bam`, one could keep the same pipeline for the larger .bam files.

**Comment by ekiefl** [comment]
Ok thanks, that gives me some perspective. I will add this to the current branch I am working on and comment here once it's merged

**Comment by ekiefl** [comment]
Hey @jaybake5, as of 2c5fd15, `anvi-init-bam` now supports multi-threading. This will soon be merged into master. Thanks for taking the time to request this feature.

**Comment by jaybake5** [comment]
That's awesome!  Thank you so much!
