### ISSUE TITLE
Add option to omit progress bar

### ISSUE THREAD

**Issue by igorspp** [merenlab/anvio#1363]
Hi Meren et al.,

I was suggesting to Meren the other day that I would appreciate if there would be a way to omit the progress bar e.g. when submitting cluster jobs. The log files become very large and readability poor sometimes. So here is a suggestion to maybe add a global option such as "--omit-progress-bar". In this case maybe the output could also be in B&W, as if I'm not mistaken they end up as things like [0;33 in the log files.

Thank you very much!

Igor Pessi

**Comment by meren** [comment]
Hey @igorspp,

Thank you for the report :)

Now in `master` there are two flags that will be accepted by any anvi'o program: `--quiet` `--no-progress`. The latter omits the progress bar outputs. The former omits all terminal outputs.

I hope this works for you.


Best wishes,

**Comment by igorspp** [comment]
Wow @meren that was fast! Thanks a lot, that will make my log files considerably smaller :)
