### ISSUE TITLE
anvi-run-ncbi-cogs on partial gene calls

### ISSUE THREAD

**Issue by sarah872** [merenlab/anvio#1364]
Hi,
I am not sure if this is a bug or another type of issue, but I am running

```
Anvi'o version ...............................: esther (v6.1)
Profile DB version ...........................: 31
Contigs DB version ...........................: 14
Pan DB version ...............................: 13
Genome data storage version ..................: 6
Auxiliary data storage version ...............: 2
Structure DB version .........................: 1
```
and I would like to have COG annotations for my sequences. My external gene calls are from microscope/genoscope that I want to use. Since it's SAG/MDA data, my genomes are pretty crappy and hence I have a lot of genes without a STOP codon (microscope apparently does gene calls in a certain way...).
When running `anvi-run-ncbi-cogs` anvi'o complains that there is a significant fraction of blank sequences (which equals the number of _partial_ gene calls that I have).
Is there are way to include partial sequences in my COG annotations? Other than providing external annotations?

**Comment by ekiefl** [comment]
Is there a fundamental reason that ncbi COGs cannot accept partial gcs, or is this a design decision on our behalf?

**Comment by meren** [comment]
@ekiefl, it is because we don't always know what is the amino acid sequence for partial Gene calls. It is a design issue on our part. We still could have reported partial amino acid sequences (as best as we can) and have annotations for them.
