### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'split' anvi-profile

### ISSUE THREAD

**Issue by mijiandui** [merenlab/anvio#1376]
when i run anvi-profile with master anvio. it always show the following error no mater i use single or multi threads. Please help me to find where is wrong. Thanks a lot.

Process Process-13:
Traceback (most recent call last):
  File "/home/ubuntu/miniconda2/envs/anvio-master/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/ubuntu/miniconda2/envs/anvio-master/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ubuntu/github/anvio/anvio/profiler.py", line 602, in profile_contig_worker
    del split.auxiliary.split.SNV_profiles
AttributeError: 'NoneType' object has no attribute 'split'

the following information is the error when i use single thread. i used the .db constructed by anvio-6.1 stable version. That maybe caused this error ?
✖ anvi-profile encountered an error after 0:02:15.146499
Traceback (most recent call last):
  File "/home/ubuntu/github/anvio/bin/anvi-profile", line 93, in <module>
    main(args)
  File "/home/ubuntu/github/anvio/anvio/terminal.py", line 745, in wrapper
    program_method(*args, **kwargs)
  File "/home/ubuntu/github/anvio/bin/anvi-profile", line 33, in main
    profiler.BAMProfiler(args)._run()
  File "/home/ubuntu/github/anvio/anvio/profiler.py", line 271, in _run
    self.profile_single_thread()
  File "/home/ubuntu/github/anvio/anvio/profiler.py", line 734, in profile_single_thread
    del split.auxiliary.split.SNV_profiles
AttributeError: 'NoneType' object has no attribute 'split'

**Comment by ekiefl** [comment]
Hi, thank you for the report. Could you please send me a copy of the BAM file and contigs database that cause this error? My email is kiefl.evan _at_ gmail.com

Constructing the db with the stable version should not cause this.

Cheers.

**Comment by mijiandui** [comment]
Dear ekiefl, thanks a lot for your quick and kind response. However, the contigs.db is 6.0Gb，one BAM file is around 3Gb. So it was different to send email to you. Have any other way?
    When i used same BAM file and contigs databse runing with stable version, that worked well. But one sample taken 6 hours with 30 threads. That speed was same with master version?

     Thanks again.

**Comment by mijiandui** [comment]
> Hi, thank you for the report. Could you please send me a copy of the BAM file and contigs database that cause this error? My email is kiefl.evan _at_ gmail.com
> 
> Constructing the db with the stable version should not cause this.
> 
> Cheers.


Dear ekiefl, thanks a lot for your quick and kind response. However, the contigs.db is 6.0Gb，one BAM file is around 3Gb. So it was different to send email to you. Have any other way?
When i used same BAM file and contigs databse runing with stable version, that worked well. But one sample taken 6 hours with 30 threads. That speed was same with master version?

 Thanks again.

**Comment by ekiefl** [comment]
It should take less than 10 minutes with 10 threads on master.

Please try and find a way to host the files so I can download them and test.

**Comment by mijiandui** [comment]
> It should take less than 10 minutes with 10 threads on master.
> 
> Please try and find a way to host the files so I can download them and test.

Dear ekiefl, that sounds great for master version！I have sent two emails to you with two different emails addresses(mijiandui at 163.com and 415151735 at qq.com). Please check, if have any downloading problem, please tell me. Thanks for  your kind help!

**Comment by ekiefl** [comment]
Thanks for sending these. The 163.com file is downloading very slow (ETA 5 hours) but once it finishes I'll address this (and hopefully fix it)

**Comment by mijiandui** [comment]
> Thanks for sending these. The 163.com file is downloading very slow (ETA 5 hours) but once it finishes I'll address this (and hopefully fix it)

Dear ekiefl, do you have any problem to download the file from 163.com? If you have downloaded the qq.com one, i can send the 163.com file with qq.com again. Thanks.

**Comment by ekiefl** [comment]
Hi @mijiandui 

Using the bam and contigs db you sent me, I ran the following command:

```
anvi-profile -i M-A1-1.bam -c contigs.db -o TEST --debug -T 6
```

It ran successfully without error in 45 minutes (it took longer than I thought based just off of the BAM size because there are 686K contigs)

Is it possible you sent me a different BAM file?

**Comment by mijiandui** [comment]
> Hi @mijiandui
> 
> Using the bam and contigs db you sent me, I ran the following command:
> 
> ```
> anvi-profile -i M-A1-1.bam -c contigs.db -o TEST --debug -T 6
> ```
> 
> It ran successfully without error in 45 minutes (it took longer than I thought based just off of the BAM size because there are 686K contigs)
> 
> Is it possible you sent me a different BAM file?
> 
> If you're sure this is the BAM file, what command did you run? Maybe you set different minimum contig lengths or supplied contigs of interest? Something like this?

Dear ekiefl, thanks a lot for your kind help. Today, i reinstalled the anvio-master. But use the different directory to store .git.  not the home directory. The script is below. That works, when i used the following script: 
for i in $(cat samples.txt)
do 
  anvi-profile -i "$i".bam -c contigs.db -T 5 --write-buffer-size 20000
done
Each Bam file (about 2.5 Gb) costed around 40 min.  That produced a profile.db with about 200MB. I hope that is the correct result. Thanks again.




echo -e "\n# >>> ANVI'O STUFF >>>" >> /media/ubuntu/f0dddfea-0944-4c77-9973-120e8a99d7b5/anvi/github/virtual-envs/anvio-master/bin/activate
echo 'export PYTHONPATH=$PYTHONPATH:~/github/anvio/' >> /media/ubuntu/f0dddfea-0944-4c77-9973-120e8a99d7b5/anvi/github//virtual-envs/anvio-master/bin/activate
echo 'export PATH=$PATH:~/github/anvio/bin:~/github/anvio/sandbox' >> /media/ubuntu/f0dddfea-0944-4c77-9973-120e8a99d7b5/anvi/github//virtual-envs/anvio-master/bin/activate
echo 'cd ~/github/anvio && git pull && cd -' >> /media/ubuntu/f0dddfea-0944-4c77-9973-120e8a99d7b5/anvi/github//virtual-envs/anvio-master/bin/activate
echo "# <<< ANVI'O STUFF <<<" >> /media/ubuntu/f0dddfea-0944-4c77-9973-120e8a99d7b5/anvi/github//virtual-envs/anvio-master/bin/activate

echo -e "\n# >>> ANVI'O STUFF >>>" >> /media/ubuntu/f0dddfea-0944-4c77-9973-120e8a99d7b5/anvi/.bash_profile
echo 'alias anvi-activate-master="source ~/virtual-envs/anvio-master/bin/activate"' >> /media/ubuntu/f0dddfea-0944-4c77-9973-120e8a99d7b5/anvi/.bash_profile
echo "# <<< ANVI'O STUFF <<<" >> /media/ubuntu/f0dddfea-0944-4c77-9973-120e8a99d7b5/anvi/.bash_profile
source /media/ubuntu/f0dddfea-0944-4c77-9973-120e8a99d7b5/anvi/.bash_profile

**Comment by ekiefl** [comment]
It sounds like the problem may have fixed itself. I will tentatively close this issue.

Thanks for your report.

**Comment by fconstancias** [comment]
Hi guys, hi @ekiefl ,

I experienced exactly the same error profiling .bam files and trying to skip SNV profiling:

`anvi-profile -i ${MAP}${sample}.bam     -c ${CONT_DB}      --output-dir ${PROF}$sample --sample-name $sample     -T ${NSLOTS}  --write-buffer-size 10000     --skip-SNV-profiling`

> AttributeError: 'NoneType' object has no attribute 'split'
> [19 Jun 20 04:20:52 Profiling w/26 threads] 23/1291059 contigs ⚙  | MEMORY 🧠  76.53 GB (+??)                                                                                                                            EETA: ∞:∞:Process Process-24:
> Traceback (most recent call last):
>   File "/home/constancias/miniconda3/envs/anvio-6.2/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
>     self.run()
>   File "/home/constancias/miniconda3/envs/anvio-6.2/lib/python3.6/multiprocessing/process.py", line 93, in run
>     self._target(*self._args, **self._kwargs)
>   File "/home/constancias/miniconda3/envs/anvio-6.2/lib/python3.6/site-packages/anvio/profiler.py", line 602, in profile_contig_worker
>     del split.auxiliary.split.SNV_profiles
> AttributeError: 'NoneType' object has no attribute 'split'
> [19 Jun 20 04:20:52 Profiling w/26 threads] 24/1291059 contigs ⚙  | MEMORY 🧠  76.53 GB (+??)                                                                                                                            EETA: ∞:∞:Process Process-25:
> Traceback (most recent call last):
>   File "/home/constancias/miniconda3/envs/anvio-6.2/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
>     self.run()
>   File "/home/constancias/miniconda3/envs/anvio-6.2/lib/python3.6/multiprocessing/process.py", line 93, in run
>     self._target(*self._args, **self._kwargs)
>   File "/home/constancias/miniconda3/envs/anvio-6.2/lib/python3.6/site-packages/anvio/profiler.py", line 602, in profile_contig_worker
>     del split.auxiliary.split.SNV_profiles
> AttributeError: 'NoneType' object has no attribute 'split'
> [19 Jun 20 04:20:52 Profiling w/26 threads] 25/1291059 contigs ⚙  | MEMORY 🧠  76.53 GB (+??)                                                                                                                            EETA: ∞:∞:Process Process-26:
> 

However, everything is going smooth if I let anvi-profile profile the SNV:

`anvi-profile -i ${MAP}${sample}.bam     -c ${CONT_DB}    --output-dir ${PROF}$sample --sample-name $sample     -T ${NSLOTS} --write-buffer-size 10000`


I am using anvio v6.2, installed through conda:
> anvi-self-test --version
> Anvi'o version ...............................: esther (v6.2)
> Profile DB version ...........................: 31
> Contigs DB version ...........................: 14
> Pan DB version ...............................: 13
> Genome data storage version ..................: 6
> Auxiliary data storage version ...............: 2
> Structure DB version .........................: 1
> 
>

**Comment by ekiefl** [comment]
Hi @fconstancias :))

The bug you're experiencing is fixed in the `master` branch of the repository. Soon we will plan a release. Hopefully things are not too slow to profile SNVs

**Comment by fconstancias** [comment]
Will use the master branch then ! 
Thanks Evan
