### ISSUE TITLE
re-running anvi-pan-genome on old results

### ISSUE THREAD

**Issue by TonyMane** [merenlab/anvio#1379]
```
(anvio-master) (anvio-master) -bash-4.2$ anvi-self-test --version
Anvi'o version ...............................: esther (v6.1-master)
Profile DB version ...........................: 31
Contigs DB version ...........................: 14
Pan DB version ...............................: 13
Genome data storage version ..................: 6
Auxiliary data storage version ...............: 2
Structure DB version .........................: 1
```

Greetings, I have a question regarding anvi-pan-genome analysis. Specifically, i ran anvi-pan-genome with the default settings used for the Prochlorococcus tutorial.  After re-reading the tutorial, it mentions "Try to utilize previous search results if there is already a directory. This way you can play with the --minbit, --mcl-inflation, or --min-occurrence parameters without having to re-do the amino acid seqeunce search". I would like to re-run the pan-genome analysis on previously produced pan-genome database and and blast-output, but increase the number of occurrences observed (--min-occurrence 2). However, i am not sure how to re-run the analysis without overwriting the original pan-database. An example would be useful.

I am running anvio-master on a:
Model name:            Intel(R) Xeon(R) CPU           X5650  @ 2.67GHz
running Linux

**Comment by meren** [comment]
If I remember correctly, all you need to do is to use the same output directory with the existing Pan database, but with a different project name.
