### ISSUE TITLE
Anvio interactive server terminates prematurely

### ISSUE THREAD

**Issue by micro-phia** [merenlab/anvio#1380]
THIS IS A TECHNICAL ISSUE:

```
(anvio-6.1) phia@Sophias-MacBook-Pro LM1 % anvi-self-test --version
Anvi'o version ...............................: esther (v6.1)
Profile DB version ...........................: 31
Contigs DB version ...........................: 14
Pan DB version ...............................: 13
Genome data storage version ..................: 6
Auxiliary data storage version ...............: 2
Structure DB version .........................: 1
```

OPERATING SYSTEM: macOS Catalina (v10.15.3)

ANVIO INSTALLATION: 
conda create -n anvio-6.1 python=3.6
conda activate anvio-6.1
conda install -y -c conda-forge -c bioconda anvio=6.1
conda install -y diamond=0.9.14
anvi-self-test --suite mini

DESCRIPTION OF ISSUE: 
Any time the Anvio interactive interface is called (i.e with anvi-interactive, anvi-refine, anvi-self-test) the server prematurely disconnects, so that I may not interact with the interface. Immediately after launching the server, I receive the following notification in red at the top right of the browser screen:

 "It seems the server that's been serving this page is no longer accessible.  You may lose your unsaved changes in this window".

In the terminal, I initially see the following notification:

"* The server is now listening the port number "8080". When you are finished, press
CTRL+C to terminate the server."

However, the server terminates immediately afterwards, without my using CTRL+C.

Other functionalities that do not require the interactive interface (i.e. anvi-run-hmms, or anvi-merge-bins) remain functional. 

The latest version of Chrome is my default browser.  I've tried using both .bash and .zsh terminals. 

Thank you in advance,
Phia

**Comment by meren** [comment]
Can you please run `anvi-interactive` with `sudo`?

```
sudo anvi-interactive ...
```

**Comment by micro-phia** [comment]
This was successful.  Thank you!
