### ISSUE TITLE
Error when installing latest codebase v6.1-master

### ISSUE THREAD

**Issue by elizabethmcd** [merenlab/anvio#1381]
Hi,

I installed the latest codebase version of anvi'o using the "wizard" installation instructions. I also updated to the latest version of conda. Everything seemed to install ok until I ran the `anvi-self-test --suite mini` and got an error from what seems to be sqlite:

Anvi'o version:
```
Anvi'o version ...............................: esther (v6.1-master)
Profile DB version ...........................: 31
Contigs DB version ...........................: 14
Pan DB version ...............................: 13
Genome data storage version ..................: 6
Auxiliary data storage version ...............: 2
Structure DB version .........................: 1
```
Error log: 
```
dyld: Library not loaded: @rpath/libedit.0.dylib
  Referenced from: /Users/emcdaniel/anaconda2/bin/sqlite3
  Reason: no suitable image found.  Did find:
	/Users/emcdaniel/anaconda2/lib/libedit.0.dylib: file too short
	/Users/emcdaniel/anaconda2/bin/../lib/libedit.0.dylib: file too short
./run_mini_test.sh: line 29: 53828 Abort trap: 6           sqlite3 $output_dir/CONTIGS.db '.tables'


Config Error: According to the exit code ('134'), anvi'o suspects that something may have gone
              wrong while running your tests :/ We hope that the reason is clear to you from
              the lines above. But if you don't see anything obvious, and especially if the
              test ended up running until the end with reasonable looking final results, you
              shouldn't worry too much about this error. Life is short and we all can worry
              just a bit less.
```

I haven't tried actually running any anvi'o scripts yet, as it's always been my practice to run the mini test suite when updating anvi'o, installing on a new machine, so I'm not sure if this effects anything or not. 

Thanks!

**Comment by elizabethmcd** [comment]
Apologies, this was entirely a me problem. I had a version of anaconda2 sitting around for some reason and that seemed to confuse things. Got rid of the old version and everything works perfectly.

**Comment by meren** [comment]
Ah, we love issues that resolve themselves :) thanks for going after it.
