### ISSUE TITLE
anvi-merge error: The number of nucleotides are not identical for all profiles to be merged, 

### ISSUE THREAD

**Issue by FengqingWang0712** [merenlab/anvio#1388]
Hi. I am new to anvi'o. I used anvi-merge, and there is an error: The number of nucleotides are not identical for all profiles to be merged, which is a deal breaker. All profiles that are going to be merged must be run with identical flags and parameters .....
I think if it is the problem of my contigs.db. For anvi-merge, in the contigs.db, the input fasta file should be co-assembly fasta, if I didn't do co-assembly, if I merged those assembly fasta files, is it ok?

Thanks very much.

**Comment by meren** [comment]
This issue may be relevant to this one:

#1403.
