### ISSUE TITLE
anvi-merge

### ISSUE THREAD

**Issue by lichengpeng419** [merenlab/anvio#1399]
Hi there,
Anvi'o version ...............................: esther (v6.1)
Profile DB version ...........................: 31
Contigs DB version ...........................: 14
Pan DB version ...............................: 13
Genome data storage version ..................: 6
Auxiliary data storage version ...............: 2
Structure DB version .........................: 1

I run anvio-6.1 on my computer with Ubuntu 19.04 using the following command:

anvi-merge BYH1/PROFILE.db BYH2/PROFILE.db -o BXH1-MERGED -c contigs.db --skip-hierarchical-clustering
Then there is an issue:
Config Error: profile/PROFILE.db does not seem to be a database generated by anvi'o :/

Thanks,

**Comment by meren** [comment]
```
Config Error: profile/PROFILE.db does not seem to be a database generated by anvi'o :/
```

Probably the process that meant to generate `profile/PROFILE.db` was killed abruptly leaving behind an unfinished profile database. Please delete it and re-profile.

**Comment by lichengpeng419** [comment]
[04 Apr 20 09:02:38] input_bam ..........................: /data/home/cuixiaolong/meta1/lianxi/BXH/BXH1.bam
[04 Apr 20 09:02:38] output_dir .........................: /data/home/cuixiaolong/meta1/lianxi/BXH/BXH1
[04 Apr 20 09:02:38] total_reads_mapped .................: 27,321,478
[04 Apr 20 09:02:38] num_contigs ........................: 191,987
[04 Apr 20 09:02:39] num_contigs_after_M ................: 191,987
[04 Apr 20 09:02:39] num_contigs ........................: 191,987
[04 Apr 20 09:02:39] num_splits .........................: 192,511
[04 Apr 20 09:02:39] total_length .......................: 435,125,680
[04 Apr 20 09:02:39] max_coverage_depth .................: 8,000
[04 Apr 20 10:01:25] New data for 'layers' in data group 'default'
=====================================
[04 Apr 20 10:01:25] Data key "total_reads_mapped" ......: Predicted type: int
[04 Apr 20 10:01:25] NEW DATA
=====================================
[04 Apr 20 10:01:25] Database ...........................: profile
[04 Apr 20 10:01:25] Data group .........................: default
[04 Apr 20 10:01:25] Data table .........................: layers
[04 Apr 20 10:01:25] New data keys ......................: total_reads_mapped.
[04 Apr 20 10:01:25] * Happy 
[04 Apr 20 10:01:25] Bye.

Thank you for your kind help, but I found that the working log&nbsp; shows that the related process has been completed. And my split are 192,511, I wonder if it will affect anvio performance 





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"A. Murat Eren"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月5日(星期天) 晚上11:01
收件人:&nbsp;"merenlab/anvio"<anvio@noreply.github.com&gt;;
抄送:&nbsp;"你好"<610054483@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [merenlab/anvio] anvi-merge (#1399)





 Config Error: profile/PROFILE.db does not seem to be a database generated by anvi'o :/  
Probably the process that meant to generate profile/PROFILE.db was killed abruptly leaving behind an unfinished profile database. Please delete it and re-profile.

**Comment by meren** [comment]
Hi @lichengpeng419, I don't think you have sent the entire list of commands.

Names in this one,

```
anvi-merge BYH1/PROFILE.db BYH2/PROFILE.db -o BXH1-MERGED -c contigs.db --skip-hierarchical-clustering
```

Does not match the name here:

```
Config Error: profile/PROFILE.db does not seem to be a database generated by anvi'o :/
```

And the output directory here, 

```
[04 Apr 20 09:02:38] output_dir ..............: /data/home/cuixiaolong/meta1/lianxi/BXH/BXH1
```

Has nothing to do with any other. Which program is this error is even coming from?

```
Config Error: profile/PROFILE.db does not seem to be a database generated by anvi'o :/
```

The error report does not have any information for us to work with. But the bottomline is, profiles and merged profiles with hundreds of thousands of splits are often used by many without anvi'o complaining about a database not being an anvi'o database. So the problem is somewhere there.

Best,

**Comment by lichengpeng419** [comment]
Hi A. Murat Eren
Thank you for your prompt reply. This is my code to generate profile/PROFILE.db . It seems the&nbsp; profile database was finished.please see the&nbsp;appendix.


Thanks






------------------ 原始邮件 ------------------
发件人:&nbsp;"A. Murat Eren"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月6日(星期一) 上午8:06
收件人:&nbsp;"merenlab/anvio"<anvio@noreply.github.com&gt;;
抄送:&nbsp;"你好"<610054483@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [merenlab/anvio] anvi-merge (#1399)





 
Hi @lichengpeng419, I don't think you have sent the entire list of commands.
 
Names in this one,
 anvi-merge BYH1/PROFILE.db BYH2/PROFILE.db -o BXH1-MERGED -c contigs.db --skip-hierarchical-clustering  
Does not match the name here:
 Config Error: profile/PROFILE.db does not seem to be a database generated by anvi'o :/  
And the output directory here,
 [04 Apr 20 09:02:38] output_dir ..............: /data/home/cuixiaolong/meta1/lianxi/BXH/BXH1  
Has nothing to do with any other. Which program is this error is even coming from?
 Config Error: profile/PROFILE.db does not seem to be a database generated by anvi'o :/  
The error report does not have any information for us to work with. But the bottomline is, profiles and merged profiles with hundreds of thousands of splits are often used by many without anvi'o complaining about a database not being an anvi'o database. So the problem is somewhere there.
 
Best,
