### ISSUE TITLE
Bacterial and archaeal HMMs for 16S rRNA genes should be merged

### ISSUE THREAD

**Issue by igorspp** [merenlab/anvio#1411]
Hi Meren et al.

This is another issue originally reported in the Google group.
It is a bit old (sorry for the delay), so it might have been fixed already?
Please delete this if that's the case.

Running the master branch, I've download all Acidobacteria genomes from GenBank and done the following:

```
anvi-script-reformat-fasta
anvi-gen-contigs-database
anvi-run-hmms
```

I then wanted to get the 16S rRNA gene sequence from them, like so:

```
anvi-get-sequences-for-hmm-hits --external-genomes NCBI_contigsDB.txt \
                                --output-file SSU.fa \
                                --hmm-source Ribosomal_RNAs \
                                --gene-names Bacterial_16S_rRNA \
                                --return-best-hit
```
And was surprised that out of the ~1000 genomes from GenBank, ANVIO reported the 16S gene for only 20 of them.

I then went to look closer at a complete, high quality genome that I know contains the 16S:

```
anvi-get-sequences-for-hmm-hits --contigs-db CONTIGSDB/Granulicella_mallensis_MP5ACTX8_GCA_000178955.2.db \
                                --output-file GCA_000178955_ribosomal.fa \
                                --hmm-sources Ribosomal_RNAs
```

And to my surprise, I see it was annotated as Archaeal_16S_rRNA.

```
>Archaeal_16S_rRNA___Ribosomal_RNAs___24bc7492fe6dbe83ed66464d5462c41ed9d1865c798db45501581a54 bin_id:Granulicella_mallensis_MP5ACTX8_GCA_000178955.2|source:Ribosomal_RNAs|e_value:3.1e-233|contig:c_000000000001|gene_callers_id:4857|start:691201|stop:692687|length:1486
```

Cheers

**Comment by meren** [comment]
Thank you very much for documenting this, @igorspp! I had totally forgotten about it.

What we need to do is to merge all 16S models into a single file to avoid such sensitivity/specificity issues.

**Comment by Luyang-1987** [comment]
sorry to bother, but how can Bacterial and archaeal HMMs for 16S rRNA genes be merged, and how to add new hmm sources like Campbell_et_al into my hmm profiles, every time i run hmm source list, i only get the default 4 sources

**Comment by meren** [comment]
I finally was able to address this, @igorspp, and it will be in `v7`. Thank you very much for the report. 

Now you will get all 16S hits when you run this command:

```
anvi-get-sequences-for-hmm-hits --external-genomes NCBI_contigsDB.txt \
                                --output-file SSU.fa \
                                --hmm-source Ribosomal_RNA_16S \
```
