### ISSUE TITLE
Suggestion/request for when an existing output directory is a show-stopper

### ISSUE THREAD

**Issue by AstrobioMike** [merenlab/anvio#1430]
I tried to look into this to suggest a change myself, but I still don't have the chops to really navigate the codebase :/ 

When running `anvi-summarize`, if the output directory exists, we get an error telling us that's no bueno (i believe from [this guy](https://github.com/merenlab/anvio/blob/2747c28237694401351b8924c5feaebb2944ba4f/anvio/filesnpaths.py#L315)). Currently, it will run the entire process first, and then do that check at the end. Depending on database size and if pulling out gene coverages and whatnot, this can be upwards of an hour of processing before finding out that you specified a directory that already exists (like i'm a fan of doing for some reason) and the program quits.

Is it straightforward to move that output-directory check up to the front of the process, so it'd quit before doing the work?

**Comment by meren** [comment]
that's a great point. thanks, @AstrobioMike, and apologies for the frustration :)

**Comment by AstrobioMike** [comment]
Now that’s service! 🤗
