### ISSUE TITLE
self-test --suite full fails at "A dry run in 'gene-mode'..."

### ISSUE THREAD

**Issue by jarrodscott** [merenlab/anvio#1439]
hello!!

Hope you all are good. I was doing a routine test drive (`anvi-self-test --suite full`) of my anvi'o install (like all good users should do :) and encountered this message. 

```
File/Path Error: Your tree contains names that are composed of only digits (like this one: '21').
                 Sadly, anvi'o is not happy with such names in newick trees or clustering
                 dendrograms :( Anvi'o developers apologize for the inconvenience.

Config Error: According to the exit code ('254'), anvi'o suspects that something may have gone
              wrong while running your tests :/ We hope that the reason is clear to you from
              the lines above. But if you don't see anything obvious, and especially if the
              test ended up running until the end with reasonable looking final results, you
              shouldn't worry too much about this error. Life is short and we all can worry
              just a bit less.
```

Despite anvio's words of encouragement, the reason for the error was not clear to me. I attached the terminal output and what seems to be the offending db. Neither the `items_orders` or the `layer_orders` tables are populated---judging by the way anvio was yelling about newick trees I thought the problem would be there for sure.  In fact only `layer_additional_data` and `gene_level_coverage_stats` have data. Wish I could be more help :)
 
[full_suite.log](https://github.com/merenlab/anvio/files/4755052/full_suite.log)
[CONCOCT-Bin_1.db.zip](https://github.com/merenlab/anvio/files/4755056/CONCOCT-Bin_1.db.zip)

```
Anvi'o version ...............................: esther (v6.2-master)
Profile DB version ...........................: 33
Contigs DB version ...........................: 16
Pan DB version ...............................: 13
Genome data storage version ..................: 6
Auxiliary data storage version ...............: 2
Structure DB version .........................: 1
Kegg Modules DB version ......................: 1
```

**Comment by meren** [comment]
Thank you for reporting this! This was due to a glitch due to a recent commit and was entirely my fault. Apologies. It should be fixed now :)

**Comment by jarrodscott** [comment]
Works like a charm. You're a ninja
 `Anvi'o's self-test is done, and the temporary output files are cleaned.`
