### ISSUE TITLE
anvi'o (conda install -y -c conda-forge -c bioconda anvio==6.2 not working) code

### ISSUE THREAD

**Issue by acnaria** [merenlab/anvio#1451]
HI 
For some reason I've not been able to install anvi’o. It shows the following result:
"anvio-6.2) PS C:\> conda install -y -c conda-forge -c bioconda anvio==6.2
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: /
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions"

Appreciate your suggestions

**Comment by meren** [comment]
Did you follow the installation instructions? Because the reason is right there:

![image](https://user-images.githubusercontent.com/197307/85860452-708bd600-b784-11ea-8e72-88a6be7e9b2f.png)

**Comment by acnaria** [comment]
Dear Meren,
I did install the Linux subsystem for windows. Thanks for your help
