### ISSUE TITLE
problem generating an anvi’o genomes storage

### ISSUE THREAD

**Issue by ziphra** [merenlab/anvio#1456]
Hi, 

I'm having trouble while running the pangenomic workflow.

this command ``` anvi-gen-genomes-storage -e external-genomes.txt -i internal-genomes.txt -o electrogenes-GENOMES.db ```
gives me 
```Config Error: The database at electrogenes-GENOMES.db does seem to have a table `genome_info`
              :/ Here is a list of table names this database knows: ``` (and no list printed after), even thought it seemed to work ok since all of my genomes were proceed during the program. 

Then, after trying 
```anvi-pan-genome -g electrogenes-GENOMES.db  -n electrogenes_pang ```

I get: 

```  Config Error: Query on genome_info with the where clause of 'genome_name IN ()' did not return anything. ```

I may have to tell that I updated my contigs database (that I made with Anvi’o) using the --just-do-it flag (I am so ashamed......) because I had sqlite3 version 28 instead of version 30 required at that moment.... And I believe sqlite3 has to do with making databases, now... 
I since updated to sqlite3 version 31. 

But still, the pangenomic self test gives me the same error: 

```
Config Error: The database at TEST-GENOMES.db does seem to have a table `genome_info` :/ Here
              is a list of table names this database knows:                                  




Config Error: According to the exit code ('255'), anvi'o suspects that something may have gone
              wrong while running your tests :/ We hope that the reason is clear to you from  
              the lines above. But if you don't see anything obvious, and especially if the   
              test ended up running until the end with reasonable looking final results, you  
              shouldn't worry too much about this error. Life is short and we all can worry   
              just a bit less. 
```

Here, my ```anvi-self-test --version``` : 

``` Anvi'o version ...............................: esther (v6.2-master)
Profile DB version ...........................: 34
Contigs DB version ...........................: 18
Pan DB version ...............................: 14
Genome data storage version ..................: 7
Auxiliary data storage version ...............: 2
Structure DB version .........................: 2
Kegg Modules DB version ......................: 2  
```

I am running macOS Catalina version 10.15.4. 

In advance, thanks for any help. 

Euphrasie

**Comment by ivagljiva** [comment]
@ziphra, I am sorry that you have been having troubles. I reproduced your error and it was due to a bug in which we did not update the list of tables in the database after creating those tables. 

I fixed the bug and was able to run `anvi-self-test --suite pangenomics` without getting that error anymore. If you do a `git pull` to update your anvi'o master your commands should work now, but please let us know if you run into any more issues. :)

**Comment by ziphra** [comment]
It works perfectly! 
Thank you very much for the quick reply :)
