### ISSUE TITLE
Migrating profile db from 32 to 33: "near "COLUMN": syntax error"

### ISSUE THREAD

**Issue by ubmallick** [merenlab/anvio#1462]
Hi team! We recently updated anvio to the github master v6.2 in order to run anvi-refine/interactive and also updated sqlite3 to the 3.32.3 version. However, using anvi-migrate for our databases, like `anvi-migrate --migrate-dbs-safely CO-DNA_9.1_R1_Stable_site-2500-MERGED/PROFILE.db -t 33` is causing the error below:
```
Database Path ................................: CO-DNA_9.1_R1_Stable_site-2500-MERGED/PROFILE.db
Detected Type ................................: profile
Current Version ..............................: 32
Target Version ...............................: 33
Migration mode ...............................: Safe

SQLite Version ...............................: 3.32.3

Config Error: Something went wrong during the migration of your database :( But anvi'o was
              able to restore your original database, and stored the unfinished upgrade in the
              same directory with the '.broken' in case you may need it for debugging
              purposes. Please feel free to get in touch with the developers, who may ask you
              to make available the original database to reproduce the problem. This was the
              original error message that caused this: 'near "COLUMN": syntax error'.
```
For reference, we are on Anvi'o version esther (v6.2-master). 

Any ideas for what might be causing this? Thanks!

**Comment by meren** [comment]
This is due to an old SQLite version. If you upgrade your sqlite (for instance to `3.31.1`), the problem will be solved :)

Check your version by typing,

```
sqlite3 --version
```

Best wishes,

**Comment by dutter** [comment]
Hi meren! Thanks for the quick response :) I'm working with Urmila on this project, so I just wanted to jump in and clarify something really quick: the sqlite3 installed is version `3.32.3` - should we try downgrading it to a `3.31.x` version?

**Comment by dutter** [comment]
It's also entirely possible that some part of the sqlite3 update didn't get installed, but as far as we can tell sqlite3 v3.32.3 is working and anvi'o finds the updated one happily enough

**Comment by meren** [comment]
Crap. I'm sorry, I didn't check the output very carefully :/ This is master, right? I think we fixed in one of our branches that is yet to be merged to `master` :/

Would you mind making the profile db available to me privately so I can double check?

Best,

**Comment by ubmallick** [comment]
Thank you so much for the quick response! I have emailed you the profile db and some related information.

**Comment by meren** [comment]
(revisiting old issues, I just realized I never got this e-mail)
