### ISSUE TITLE
anvi'o interactive server closes when storing bin collection

### ISSUE THREAD

**Issue by laj873** [merenlab/anvio#1463]
Hello,

I'm having an issue with trying to save bin collections when looking at a pangenome with the `anvi-display-pan` command. Every time that I create bins and try to save the collection, a red box pops up and states: "It seems the server that's been serving this page is no longer accessible. You may lose your unsaved changes in this window."

How can I stop the interactive server from losing connection? I'm trying to save bins so that I can use `anvi-split` to split the bins.

Thanks!

**Comment by meren** [comment]
Hi @laj873,

We ask people to report the version of anvi'o and the operating system they are using in the issue template, basically BEGGING them to read it first before submitting their issue. It starts with these lines:

> 
> PLEASE READ THIS BEFORE SUBMITTING YOUR ISSUE
> =============================================
> 
> Read the following text carefully, and remove it before submitting your issue.
> 
> We thank you in advance for your report. Please take a look at the items down below:
> 
>  * If this is a technical issue, please run the command `anvi-self-test --version` in your terminal and paste the output at the beginning of your report. If you fail to do this we will likely close the issue without addressing it, and wait for someone else to report it :(
>
> (...)


Yet, people often find it OK to completely ignore these requests, remove the text that essentially begs them to include, and submit their issue without key information anyway. By doing so these people force the developers (who are already under tremendous time pressure to help the community in parallel to keeping up with their own science) to ask the same questions the issue template already has asked.

I often ignore this and basically waste another three minutes of my life for someone who didn't have 10 seconds to read a piece of text. But every once in a while I clearly see the amount of lack of respect to open-source software developers to be able to do ignore their simplest requests. Then I have 0 motivation to help you or the next person.
