### ISSUE TITLE
"anvi-setup-kegg-kofams" is not running

### ISSUE THREAD

**Issue by choon-sim** [merenlab/anvio#1464]
Hi, I am a beginner to anvi'o. I am interested to perform functional/pathway analysis on my contigs. 
http://merenlab.org/software/anvio/help/programs/anvi-setup-kegg-kofams/
However, "anvi-setup-kegg-kofams" is not running when i type in the command.

I installed my anvi'o using standard way:
conda create -y --name anvio-6.2 python=3.6

Thanks for any help!

Choon
(I should add that other anvi commands are running fine. I could get my contig into anvi-interactive, for example.)

**Comment by ivagljiva** [comment]
Hi @choon-sim, 

`anvi-setup-kegg-kofams` and the other KEGG-related scripts are not part of anvi'o version 6.2. 
 If you want to use these programs, you will need to install our development version by following the instructions here: http://merenlab.org/2016/06/26/installation-v2/#following-the-active-codebase-youre-a-wizard-arry
:)
