### ISSUE TITLE
[FEATURE] gff_parser.py matching anvi'o v.>6.0 requirements

### ISSUE THREAD

**Issue by dbenitom** [merenlab/anvio#1467]
## The need

Anvi'o versions above 6.2 require an external `gene-calls.txt` including the [column `call_type`](http://merenlab.org/software/anvio/help/artifacts/external-gene-calls/#call-type). The current version of [`gff_parser.py`](https://github.com/karkman/gff_parser) doesn't generate this column when parsing `.gff` files obtained with Prokka.

## The solution

Update `gff_parser.py` to match the new anvi'o requirements.

## Beneficiaries

Every Prokka-using anvi'o lover 😃 (Thanks in advance!!)

**Comment by meren** [comment]
Thank you very much for taking the time to report this, @dbenitom. Let's see if @karkman is around and willing to take a look.

If he has no time, I will try to find another solution. Meanwhile, can you please send an example GFF file for us to test along with a FASTA file and the exact set of commands you run?

Thank you!

**Comment by dbenitom** [comment]
Thanks for the reply, @meren! Attached are the GFF, and FASTA files. 

For Prokka annotation I ran:

```
prokka --prefix PROKKA \
       --outdir ./binning_anvio/PROKKA \
       --cpus 20 \
       --kingdom Archaea \
       ./binning_anvio/contigs.fa
```

And the command for parsing:

```
python gff_parser.py --gene-calls ./binning_anvio/gene-calls.txt \
                      --annotation ./binning_anvio/gene-annot.txt \
                      --process-all \
                      ./binning_anvio/PROKKA/PROKKA.gff  
```

Please tell me if you need anything else!

**Comment by meren** [comment]
Hey @dbenitom, thank you very much for these files. The following version of the `gff_parser.py` script should work well with `call_type` column.

I am going to also send a PR for @karkman to consider, but you can start using it immediately:

https://gist.github.com/meren/82a044bee86b8c5568669695c12575cc

**Comment by meren** [comment]
Please let me know how it goes.

Plus, there are WAY too many extremely short contigs in your FASTA file. I think you should consider removing them from your data first since they will cost a lot of computational resources for no good reason (or perhaps you have a good reason to keep them, in which case please ignore my note).

**Comment by dbenitom** [comment]
Hi @meren! 
Unfortunately, I don't see the `call_type` column in the output:

```
$ head test_calls.txt 
gene_callers_id	contig	start	stop	direction	partial	source	version
1	c_000000000001	170	605	r	0	1	Prodigal	2.6
2	c_000000000001	879	954	f	0	2	Aragorn	1.2
3	c_000000000001	1009	1516	f	0	1	Prodigal	2.6
4	c_000000000001	1564	2725	r	0	1	Prodigal	2.6
5	c_000000000001	2727	3744	r	0	1	Prodigal	2.6
6	c_000000000001	3839	5387	f	0	1	Prodigal	2.6
7	c_000000000001	5448	7884	f	0	1	Prodigal	2.6
8	c_000000000001	7892	8576	r	0	1	Prodigal	2.6
9	c_000000000001	8655	9489	r	0	1	Prodigal	2.6
```

The same [command as above](https://github.com/merenlab/anvio/issues/1467#issuecomment-660924295) was used with the new script. I execute this from my `anvio-master` virtual environment (Python 3.6.10, in case this makes any difference). Here are the differences between the new and old scripts, in case they might help:

```
$ diff gff_parser_new.py gff_parser_old.py 
11,12d10
< from collections import Counter
< 
14c12
< parser = argparse.ArgumentParser(description="""Parse Prokka annotated genome/metagenome to add external gene calls and functions to anvi'o.
---
> parser = argparse.ArgumentParser(description="""Parse Prokka annotated genome/metagenome to add external gene calls and functions to anvi'o. 
17,18c15,16
< parser.add_argument('--gene-calls', default='gene_calls.txt', help='Output: External gene calls (Default: gene_calls.txt)')
< parser.add_argument('--annotation', default='gene_annot.txt', help='Output: Functional annotation for external gene calls (Default: gene_annot.txt)')
---
> parser.add_argument('--gene-calls', default='gene-calls.txt', help='Output: External gene calls (Default: gene-calls.txt)')
> parser.add_argument('--annotation', default='gene-annot.txt', help='Output: Functional annotation for external gene calls (Default: gene-annot.txt)')
42,47d39
< # keping track of things we haven't processed
< feature_types = Counter()
< call_types = Counter()
< total_num_features = 0
< features_missing_product_or_note = 0
< 
50d41
<     total_num_features += 1
62,72d52
<     feature_types[feature.featuretype] += 1
<     if feature.featuretype == 'CDS':
<         call_type = 1
<         call_types['CDS'] += 1
<     elif 'RNA' in feature.featuretype:
<         call_type = 2
<         call_types['RNA'] += 1
<     else:
<         call_type = 3
<         call_types['unknown'] += 1
< 
83,87d62
<     # if a feature is missing both, move on.
<     if 'product' not in feature.attributes.keys() and 'note' not in feature.attributes.keys():
<         features_missing_product_or_note += 1
<         continue
< 
106,107c81,82
< 
<     OUT_CDS.write('%d\t%s\t%d\t%d\t%s\t%s\t%d\t%s\t%s\n' % (gene_id, feature.seqid, start, stop, direction, partial, call_type, source, version))
---
>     
>     OUT_CDS.write('%d\t%s\t%d\t%d\t%s\t%s\t%s\t%s\n' %(gene_id, feature.seqid, start, stop, direction, partial, source, version))
111,118d85
< 
< print(f"Done. All {total_num_features} have been processed succesfully. There were {call_types['CDS']} coding "
<       f"sequences, {call_types['RNA']} RNAs, and {call_types['unknown']} unknown features.")
< 
< if features_missing_product_or_note:
<     print()
<     print(f"Please note that we discarded {features_missing_product_or_note} features described in this file "
<           f"since they did not contain any products or notes :/")
\ No newline at end of file
```

Do you have any idea of what might be wrong? Thank you in advance!

(and about the too many short contigs -  I was missing some interesting contigs in previous analyses, that's why I decided to keep them. Although this was just a quick and easy solution and you're absolutely right about the use of resources)

**Comment by meren** [comment]
Crap :) I've made a mistake. Sorry about that! I'll send something in a minute.

**Comment by meren** [comment]
OK. The updated version is here:

https://gist.github.com/meren/82a044bee86b8c5568669695c12575cc

I forgot to update the header in the previous attempt :/ Apologies. It looks alright now:

```
column -t gene-calls.txt | head
gene_callers_id  contig          start    stop     direction  partial  call_type  source    version
1                c_000000000001  170      605      r          0        1          Prodigal  2.6
2                c_000000000001  879      954      f          0        2          Aragorn   1.2
3                c_000000000001  1009     1516     f          0        1          Prodigal  2.6
4                c_000000000001  1564     2725     r          0        1          Prodigal  2.6
5                c_000000000001  2727     3744     r          0        1          Prodigal  2.6
6                c_000000000001  3839     5387     f          0        1          Prodigal  2.6
7                c_000000000001  5448     7884     f          0        1          Prodigal  2.6
8                c_000000000001  7892     8576     r          0        1          Prodigal  2.6
9                c_000000000001  8655     9489     r          0        1          Prodigal  2.6
```

**Comment by dbenitom** [comment]
This worked perfectly, thanks a lot!
