### ISSUE TITLE
String formatting conventions

### ISSUE THREAD

**Issue by meren** [merenlab/anvio#1469]
"String" in this context means anything anvi'o reports into the terminal window or log files for users and developers to read. String formatting is meant to describe how code dynamic expressions or variables in anvi'o string literals.

Here I propose a change to the convention we had been using in the code. This is not urgent and does not require a complete change in the codebase, but should affect new code to be written.

# The current way of dealing with strings in anvi'o codebase

So far we had been using the %-formatting which is the oldest form of dealing with strings in Python as far as I know. This is how it looks:

``` python
    run.info_single("The anvi'o %s database has just been updated with a description that contains %d words "
                    "and %d characters." % (db_type, len(description.split()), len(description)))
```

The downside of this approach is two folds: can become impossible to read the code quickly, adding/removing/editing a variable can be very time-consuming and error-prone.

# An alternative way of formatting strings we skipped

A more talented way of dealing with string literals, `str.format()`, was introduced in Python 2.6 to solve some of the historical issues with Python's dealing with strings. But it didn't address all the downsides of %-formatting, especially those related to the readability and maintainability of the code. For instance, the string above would have looked like this with `str.format()`:

``` python
    run.info_single("The anvi'o {} database has just been updated with a description that contains {} words "
                    "and {} characters.".format(db_type, len(description.split()), len(description)))
```

There was no reason to switch to this more-talented but equally difficult to read format.

# A proposal for the future: f-Strings

With Python 3.6 came the implementation of the fancy [literal string interpolation](https://www.python.org/dev/peps/pep-0498/), or f-Strings. The same code looks like this with f-Strings:

``` python
    run.info_single(f"The anvi'o {db_type} database has just been updated with a description that contains "
                    f"{len(description.split())} words and {len(description} characters."))
```

I suggest we adopt f-Strings for all future code additions to the anvi'o codebase. When we are editing a piece of code we can reformat the strings around it to adopt the new strategy, but I don't suggest we try to do it for the entire codebase since it is a boring and tedious task and can be error prone with an automated way to update all strings.

# Things to avoid with f-Strings

These are some suggestions. We can expand or change them.

### Loooooong expressions

Now expressions can be used in situ (hehe), in some cases we will see things like this:

``` python
    run.info_single(f"Your success rate is {num_contigs_passed_quality_filtering * 100 / total_num_conitgs}%")
```

Which defeats the purpose of improved readability. We should handle these situations like this:

``` python
    success_rate = num_contigs_passed_quality_filtering * 100 / total_num_conitgs
    run.info_single(f"Your success rate is {success_rate}%")
```

### Nested / difficult-to-{read|test} function calls

Function calls are OK in f-Strings, but again, we shouldn't overdo it. Nested function calls may be difficult to read:

``` python
    run.info_single(f"Your success rate is {terminal.human_radable(utils.get_success_rate(good_contigs, num_contigs))}.")
```

In these cases this would be much better, 

``` python
    human_readable_success_rate = terminal.human_radable(utils.get_success_rate(good_contigs, num_contigs))
    run.info_single(f"Your success rate is {human_readable_success_rate}.")
```

### Try/Except blocks

Embedding function calls into f-Strings will make it more difficult to try/expect blocks for robust code without much redundancy. For instance, this is much better:

``` python
    try:
        success_rate = utils.get_success_rate(good_contigs, num_contigs)
    except Exception, e:
        raise ConfigError(f"You done bad with that last call: {e}")

    run.info_single(f"Your success rate is {success_rate}.")
```

than this:

``` python
    try:
        run.info_single(f"Your success rate is {utils.get_success_rate(good_contigs, num_contigs)}.")
    except Exception, e:
        raise ConfigError(f"You done bad with that last call: {e}")
```

---

Thanks for your time! :)

**Comment by ekiefl** [comment]
The future is now

**Comment by mooreryan** [comment]
Should single or double quoted format strings be preferred? E.g.,

```python
s = 'pie'

# This...
f'apple {s}'

# Or this...
f"apple {s}"
```

**Comment by meren** [comment]
We generally prefer double quotes for convenience (other wise you have to escape every time you type anvi'o).
