### ISSUE TITLE
[BUG] Too much output in the South Loop

### ISSUE THREAD

**Issue by mooreryan** [merenlab/anvio#1471]
## Short description of the problem

There is too much logging in the south loop.

## anvi'o version

On master branch commit: 5b9facaa

```
~/projects/anvio/bin/anvi-self-test --version
Anvi'o version ...............................: esther (v6.2-master)
Profile DB version ...........................: 34
Contigs DB version ...........................: 18
Pan DB version ...............................: 14
Genome data storage version ..................: 7
Auxiliary data storage version ...............: 2
Structure DB version .........................: 2
Kegg Modules DB version ......................: 2
```

## System info

Debian linux....tracking anvio master branch.

## Detailed description of the issue

A recent commit (not sure which) has changed the logging behaviour in the South Loop.  It no longer has the nice increasing progress bar, rather three lines are printed for each contig like this:

![too-much-logging-in-the-south-loop](https://user-images.githubusercontent.com/3172014/87974646-5f3e9c80-ca98-11ea-982a-6d3ae40ffb88.png)

The problem lines are these:

https://github.com/merenlab/anvio/blob/5b9facaa07131b2d59c076be2e06ad3a28bef931/anvio/dbops.py#L3929

https://github.com/merenlab/anvio/blob/5b9facaa07131b2d59c076be2e06ad3a28bef931/anvio/dbops.py#L3939

https://github.com/merenlab/anvio/blob/5b9facaa07131b2d59c076be2e06ad3a28bef931/anvio/dbops.py#L3946

If this behaviour change was intentional, please ignore this issue!!

## Files to reproduce

I exported the infant gut tutorial contigs for this.  Then ran anvi-gen-contigs:

```
anvi-gen-contigs-database -f contigs.fa -o contigs.db -T 2
```

**Comment by meren** [comment]
It was not intentional :) this is a legitimate bug. thank you!

**Comment by meren** [comment]
Just to note, it is working well here:

![image](https://user-images.githubusercontent.com/197307/87977404-4b913700-ca94-11ea-998a-9bca5820a007.png)

I think this is due to the terminal window size. We actually cut the text and put a set of ` (...)` characters when things are not going to fit to the resolution of the terminal you're using. But I think @ekiefl's latest editions to that shows the ETA is violating that.

**Comment by ekiefl** [comment]
Meren did you try making your terminal window smaller to replicate the problem?

**Comment by meren** [comment]
Indeed :)

![image](https://user-images.githubusercontent.com/197307/87978559-35847600-ca96-11ea-9c1f-be634b9583d3.png)

**Comment by meren** [comment]
OK. I went back to `v5.5`, it is still there even without ETA :/ I don't think this has started with ETA, but it seems ETA did not make things better either. There is only one byte extra on `v5.5`:

![image](https://user-images.githubusercontent.com/197307/87978764-914eff00-ca96-11ea-9e22-91041cb07cd5.png)

This is on `master`, the entire ETA is Cartman saying screw you guys I'm going home:

![image](https://user-images.githubusercontent.com/197307/87978892-d07d5000-ca96-11ea-90f6-077be4a3dce3.png)

**Comment by meren** [comment]
We must find out what the hell is up with the extra character.

**Comment by ekiefl** [comment]
I will spend 1 hour on this today
