### ISSUE TITLE
[BUG] run_all_tests.sh fails with sqlite3.OperationalError: near "s_column": syntax error

### ISSUE THREAD

**Issue by ekiefl** [merenlab/anvio#1476]
## Short description of the problem

On master, this happens when I run all tests:

```
:: Show available misc data keys ...


DATA KEYS FOR "ITEMS" in 1 DATA GROUP(S)
===============================================

* DATA GROUP "default" WITH 2 KEYS
    - type (str, describes 35 items)
Traceback (most recent call last):
  File "/Users/evan/Software/anvio/bin/anvi-show-misc-data", line 67, in <module>
    main(args)
  File "/Users/evan/Software/anvio/bin/anvi-show-misc-data", line 49, in main
    table_for_additional_data.list_data_keys()
  File "/Users/evan/Software/anvio/anvio/tables/miscdata.py", line 329, in list_data_keys
    rows = database.get_some_rows_from_table_as_dict(self.table_name, 'data_key="%s"' % data_key)
  File "/Users/evan/Software/anvio/anvio/db.py", line 775, in get_some_rows_from_table_as_dict
    rows = self.get_some_rows_from_table(table_name, where_clause)
  File "/Users/evan/Software/anvio/anvio/db.py", line 386, in get_some_rows_from_table
    response = self._exec('''SELECT %s FROM %s WHERE %s''' % (self.PROPER_SELECT_STATEMENT(table_name), table_name, where_clause))
  File "/Users/evan/Software/anvio/anvio/db.py", line 268, in _exec
    ret_val = self.cursor.execute(sql_query)
sqlite3.OperationalError: near "s_column": syntax error
```

Here is my sql version (maybe this is the problem)

```
$ python
Python 3.6.7 | packaged by conda-forge | (default, Feb 28 2019, 02:16:08)
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import sqlite3
>>> sqlite3.version
'2.6.0'
```

I notice there is no `sqlite3` in the `requirements.txt` so not sure what everyone is running.

**Comment by meren** [comment]
This is due to old sqlite :)

There will be one in the conda recipe with a minimum of version `3.31.1`.

**Comment by meren** [comment]
Akshully, this closes this issue: 1fe69de7f610cf854b99f20b3887f7a57183425c.

Thanks for reporting, so Google can bring those in need of help to this solution.

**Comment by ekiefl** [comment]
Discussion from https://groups.google.com/g/anvio/c/BzcH1zT31Hw/m/jLThGYXfAQAJ moved to this issue.

It turns out this error is not due to **old** sqlite3 versions, but also **newer** sqlite3 versions. 3.31 must be an anomaly.

**Comment by meren** [comment]
This is very disturbing :( I will look into this with a newer sqlite3.

**Comment by meren** [comment]
I figured it out :/ It is not about the SQLite version directly. It is about one of the column variable names we had been using. I updated it in one of the test files and run all tests is running properly.
