### ISSUE TITLE
[BUG] run_metabolism_tests.sh fails on master

### ISSUE THREAD

**Issue by ekiefl** [merenlab/anvio#1477]
## Short description of the problem

Running `run_metabolism_tests.sh` yields this error:

```
:: Estimating metabolism on a single contigs database ...

Modules database .............................: An existing database, /Users/evan/Software/anvio/anvio/data/misc/KEGG/MODULES.db, has been loaded.
Kegg Modules .................................: 410 found

Config Error: The contigs DB that you are working with has been annotated with a different
              version of the MODULES.db than you are working with now. Perhaps you updated
              your KEGG setup after running `anvi-run-kegg-kofams` on this contigs DB? Or
              maybe you have multiple KEGG data directories set up on your computer, and the
              one you are using now is different from the one that you used for `anvi-run-
              kegg-kofams`? Well. The solution to the first problem is to re-run `anvi-run-
              kegg-kofams` on the contigs DB (B_thetaiotamicron_VPI-5482.db) using the updated
              MODULES.db (located in the KEGG data directory
              /Users/evan/Software/anvio/anvio/data/misc/KEGG). The solution to the second
              problem is to specify the appropriate KEGG data directory using the --kegg-data-
              dir flag. If neither of those things make this work, then you should contact the
              developers to see if they can help you figure this out. For those who need this
              information, the Modules DB used to annotate this contigs database previously
              had the following hash: ba0d0dda2796. And the hash of the current Modules DB is:
              fa8d979ce0c0
```

## anvi'o version

master

## System info

custom

**Comment by ivagljiva** [comment]
@ekiefl This is actually not a surprising error. :/ This is expected to happen whenever you try to run metabolism estimation using a MODULES.db with different content than the one used to annotate KOfams (to avoid potential version discrepancy issues from throwing off the estimation). Normally, this is fine, but in the context of self-test we cannot have this happening to people, as it is very likely that people will have different versions of MODULES.db set up on their computers. 

My first inclination for a solution is to have the self test first run `anvi-run-kegg-kofams` with the user's MODULES.db before doing the estimation tests, but a concern with that is that it would take too long. Any thoughts, @meren or @ekiefl ?

**Comment by meren** [comment]
Can you reproduce this error on `master`, @ivagljiva?

**Comment by ivagljiva** [comment]
Yes, I get the same error on `master`

**Comment by ivagljiva** [comment]
And I have also just checked how long it takes to run `anvi-run-kegg-kofams` on one of the test databases.

Annotating just `anvio/anvio/tests/sandbox/data/genomes/bacteria/B_thetaiotamicron_VPI-5482.db` with 4 threads takes over 7 minutes on my laptop. That is too long for testing in my opinion.
`✓ anvi-run-kegg-kofams took 0:07:21.688839`

This would be one situation in which that `--ignore-modules-db-hash` flag (that I implemented and immediately got rid of) would be useful. 

A possible alternative is to 'trick' `anvi-estimate-metabolism` by changing the hash in the test databases to match the hash of their system's MODULES.db at the start of the test script.

**Comment by meren** [comment]
> This would be one situation in which that --ignore-modules-db-hash flag (that I implemented and immediately got rid of) would be useful.

Hahah :) I'm so proud that you immediately got rid of it :)))

> A possible alternative is to 'trick' anvi-estimate-metabolism by changing the hash in the test databases to match the hash of their system's MODULES.db at the start of the test script.

Yes, I think that is the way to go :) Two SQLite calls to learn from one db and to update the other db :)

**Comment by ivagljiva** [comment]
Sorry for the delay, I have fixed this with [this commit](https://github.com/merenlab/anvio/commit/8b82c1db034afdb954b15c62cf7b057cfd3ebc40)

@ekiefl, can you please confirm that you no longer get this error when running `anvi-self-test --suite metabolism`? :)

**Comment by ekiefl** [comment]
> Sorry for the delay, I have fixed this with [this commit](https://github.com/merenlab/anvio/commit/8b82c1db034afdb954b15c62cf7b057cfd3ebc40)

No problem at all!

> @ekiefl, can you please confirm that you no longer get this error when running `anvi-self-test --suite metabolism`? :)

It works. Thank you for dealing with this :) I will close
