### ISSUE TITLE
[BUG] Problem with R1 and R2 outputs from anvi-get-short-reads-from-bam

### ISSUE THREAD

**Issue by FlorianTrigodet** [merenlab/anvio#1478]
## Short description of the problem
When using `anvi-get-short-reads-from-bam`, you can choose between two type of outputs: (1) a single fasta; (2) 3 fasta files for R1, R2 and unpaired reads. The problem with (2) is that one of the paired sequence should be the reverse complement. 

## anvi'o version

```
Anvi'o version ...............................: esther (v6.2-master)
Profile DB version ...........................: 34
Contigs DB version ...........................: 18
Pan DB version ...............................: 14
Genome data storage version ..................: 7
Auxiliary data storage version ...............: 2
Structure DB version .........................: 2
Kegg Modules DB version ......................: 2
```

## Detailed description of the issue

I have used `anvi-get-short-reads-from-bam` with the `-Q` argument to get a separate R1 and R2 fasta file (and unpaired in a third fasta).
At first, I was puzzled by identical sequences found in both R1 and R2 fasta file. I manually checked with the initial short reads used for the mapping and I found out that one read was always good, while the other (could be either R1 or R2) was the reverse complement of the original short reads. 

Let me give you a graphic abstract of what's happening:
```
Initial paired-end short reads:
  R1
------->
========================================   
                                <-------
                                    R2

With anvi-get-short-reads-from-bam:
  R1                               R2
------->                        ------->                
========================================    OR    ========================================
                                                  <-------                        <-------
                                                     R1                               R2
```

My issue with identical sequence both in R1 and R2 only concerned shorter sequence, with no insert. And therefore the reverse complement is the paired read sequence:
```
Original paired-end short reads:
  R1
------->
========
<-------
  R2

With anvi-get-short-reads-from-bam:
  R1         
------->
  R2         
------->                 
========
```

Since I want to assemble these sequences, I need the original paired-end orientation for insert size estimation.

**Comment by meren** [comment]
Can you please test the solution, @FlorianTrigodet? Thank you!

**Comment by FlorianTrigodet** [comment]
I see you did the reversed complement of R2, and that partially solve the problem, but not completely. 

With `anvi-get-short-reads-from-bam`, we either get:
```
  R1                               R2
------->                        ------->                
========================================

```
Or:
```
========================================
<-------                        <-------
   R1                               R2
```

Reverse complement of R2 only solve the first case. In the second situation, it make the two reads facing opposite directions, like that:
```
                                  R2
                                ------->
========================================
<-------
   R1 
```

Let me know if this make sense (otherwise, I will make more keyboard drawings!)

I am going to look in the code to see what information we can get from the bam that could be useful to solve this bug.

**Comment by FlorianTrigodet** [comment]
Ok, I think I found what could be done but don't feel really qualify to make the change.
If R1 is reverse direction (`is_reverse` seems to be available), then rev_comp R1 and don't touch R2
Else, rev_comp R2.

**Comment by meren** [comment]
Try it! It is one more if/else block for rev/comp :)

**Comment by FlorianTrigodet** [comment]
The bug has been fixed by the last commit!

**Comment by meren** [comment]
Thanks, @FlorianTrigodet :)
