### ISSUE TITLE
[BUG] anvi-refine is loading only for a subset of collection

### ISSUE THREAD

**Issue by jzrapp** [merenlab/anvio#1487]
## Short description of the problem

Hi, I'm trying to refine a collection of approximately 60 MAGs, but for some reason the anvi-refine command does not open the interactive interface for a subset of those 60 bins

## anvi'o version

Anvi'o version ...............................: esther (v6.2)
Profile DB version ...........................: 31
Contigs DB version ...........................: 14
Pan DB version ...............................: 13
Genome data storage version ..................: 6
Auxiliary data storage version ...............: 2
Structure DB version .........................: 1

I installed it with Blake Sanders solution: 
    conda env create -f anvio-environment.yml
    conda activate anvio-6.2

## System info

MacOS Mojave 10.14.6

## Detailed description of the issue
I'm using
anvi-refine -c contigs.db -p SB-MERGED/PROFILE.db -C osc_collection -b *BIN_NAME* 
to start the interactive interface and arrive at the refinement mask. This works for approximately 50 of the bins, but for 10 bins my browser just halts in loading state indefinitely. It's unclear to me if this is an issue with the performance of my notebook or an issue with the input data. To exclude the first option, I rerun the same thing on our big compute cluster and here it was the same, ~50 bins were drawn in the interactive interface and 10 bins just loaded forever. Is there any way for me to see what might be the problem here?

## Files to reproduce
I'm sharing my contigs database & profile database: https://drive.google.com/drive/folders/1qfLI6jgYk-qtQfVjxk3LLCBXZFk78tQQ?usp=sharing

anvi-import-collection osc_collection.txt --bins-info osc_collection_info.txt -p SB-MERGED/PROFILE.db -c contigs.db -C osc_collection --contigs-mode

Contig/split name conversion .................: 15460 contig names converted into 16762 split names.
Item names in input ..........................: 16,762
Num bins in input ............................: 63
Items in profile database ....................: 238,562
Item names shared between input and db .......: 16,762

anvi-summarize -p SB-MERGED/PROFILE.db -c contigs.db -C osc_collection --cog-data-dir /scratch2/db/dset/COG_anvio -o SUMMARY_osc_collection
anvi-refine -c contigs.db -p SB-MERGED/PROFILE.db -C osc_collection -b bin_XX

Bins that I cannot load: 
bin_101
bin_11
bin_17
bin_62
bin_67
bin_70
bin_73
bin_74
bin_92
bin_97

Do you see where I might have created an error? Have you experienced this before?
Thanks!
Josephine

**Comment by jzrapp** [comment]
It appears that all bins can load and be visualized after I removed the default state from my database!

**Comment by meren** [comment]
Hey @jzrapp, I've been meaning to get to this, but the backlog of things to finish prevented me to respond earlier. I apologize for that.

I am glad it is resolved, and thank you very much for reporting that back and closing your own issue :) But I have to admit that it makes zero sense to me how a default state could have caused such an issue. Do you have any insights how it may have happened by any chance?


Thanks,

**Comment by jzrapp** [comment]
Ho @meren,

anvio had never failed me, so typically the issues I run into are caused by myself. That being said, I don't really understand what happened either, but I think I had overwritten the default state previously so that some additional misc data layers would automatically show up for each bin. However, there was no consistent difference between the bins that loaded and those that didn't, so I'm in the dark on why the change to the default would cause such an issue for only a subset.

**Comment by meren** [comment]
Thanks for the insights, Josephine.

I will try to figure out whether inconsistencies between what is in misc data and what is set in state files may lead to a snafu.

_(The difficult part for anvi'o is that the state file is not processed until the interactive interface is initiated, so our regular sanity checks throughout the codebase do not benchmark them against the data procured before the interactive interface is initiated)_.
