### ISSUE TITLE
[FEATURE] Markdown output for `anvi-display-contigs-stats`

### ISSUE THREAD

**Issue by FlorianTrigodet** [merenlab/anvio#1498]
## The need

`anvi-display-contigs-stats` provides a table in a .txt output that I have to convert to markdown every time I want to report contigs.db summaries. We could use a markdown ouptut.

## The solution

Add a flag like `--as-markdown` for an optional markdown output format.

## Beneficiaries

Would be useful to report and share the output of `anvi-display-contigs-stats`, especially in GitHub issues.

**Comment by meren** [comment]
DONE.

**Comment by ekiefl** [comment]
Please no one ever `anvi-gen-variability-profile --quince-mode --as-markdown`

**Comment by meren** [comment]
It is a hidden flag and will not appear in help menus :p
