### ISSUE TITLE
[BUG] anvi-display-contigs-stats import error

### ISSUE THREAD

**Issue by sadelbe** [merenlab/anvio#1499]
## Short description of the problem

When running anvi-display-contigs-stats on my contigs db I get an error.

## anvi'o version

Anvi'o version ...............................: esther (v6.2)
Profile DB version ...........................: 31
Contigs DB version ...........................: 14
Pan DB version ...............................: 13
Genome data storage version ..................: 6
Auxiliary data storage version ...............: 2
Structure DB version .........................: 1

## System info

Linux - installed using conda following Meren lab instructions 

## Detailed description of the issue
When I run anvi-display-contigs-stats on my contigs db i get the following error. I am running this on my University computing cluster. 

Process Process-1:
Traceback (most recent call last):
  File "/home/sadelbe/anaconda3/envs/anvio-6.2/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/sadelbe/anaconda3/envs/anvio-6.2/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/sadelbe/anaconda3/envs/anvio-6.2/bin/bottle.py", line 761, in run
    run(self, **kwargs)
  File "/home/sadelbe/anaconda3/envs/anvio-6.2/bin/bottle.py", line 3137, in run
    server.run(app)
  File "/home/sadelbe/anaconda3/envs/anvio-6.2/bin/bottle.py", line 2795, in run
    from cherrypy import wsgiserver
ImportError: cannot import name 'wsgiserver'

* The server is now listening the port number '8080'. When you are finished, press
CTRL+C to terminate the server. If you are using OSX and if the server
terminates prematurely before you can see anything in your browser, try to run
the same command by putting 'sudo ' at the beginning of it (you will be likely
prompted to enter your password as this command will require super user rights
to run)

**Comment by meren** [comment]
Your `cherrypy` version must be `8.0.0`. Please take a look at the version you have by running this:

```
python -c "import cherrypy; print(cherrypy.__version__)"
```

We are leaving cherrypy behind in `v7`.


Best wishes,

**Comment by sadelbe** [comment]
18.6.0 is what I get when I run the above command. I am still getting the same error.
