### ISSUE TITLE
metadata file missing in summary

### ISSUE THREAD

**Issue by tdelmont** [merenlab/anvio#150]
For Meren,
in summary, their is no file to export for the first table (bin name, taxa, GC content, length, comtanination, etc).
It would be useful to estimate average completion, average length and so on...
see attached excel where I combined them for SAND by doing copy-paste....
![screen shot 2015-06-11 at 9 06 53 am](https://cloud.githubusercontent.com/assets/8332889/8107703/50ecff08-1019-11e5-956e-875044a8451d.png)

**Comment by meren** [comment]
fixed.
