### ISSUE TITLE
[FEATURE] Include the SCG taxonomy in the collection summary

### ISSUE THREAD

**Issue by FlorianTrigodet** [merenlab/anvio#1502]
## The need

In the collection summary output, especially the html, there is a taxonomy column per bin (usually centrifuge output, if I am not mistaking). We can use the SCG taxonomy instead. We can actually have the full SCG taxonomy output in the collection summary.

## The solution

Include the output of `anvi-estimate-scg-taxonomy` in the `anvi-summarize` output.
We could have a short taxonomy like the one displayed in the interactive interface in the bins_summary.txt and index.html:
![Screen Shot 2020-09-11 at 1 12 41 PM](https://user-images.githubusercontent.com/10922896/92958877-9db95d80-f430-11ea-9fa1-9e38f80a4f84.png)
And the more complete output of `anvi-estimate-scg-taxonomy` in the `bin_by_bin`directory:
```
bin_name        total_scgs      supporting_scgs t_domain        t_phylum        t_class t_order t_family        t_genus t_species
Bin_11  23      14      Bacteria        Actinobacteriota        Actinomycetia   Actinomycetales Micrococcaceae  Rothia  Rothia mucilaginosa
```

## Beneficiaries

Anyone who wants the ultimate summary of a collection!

**Comment by meren** [comment]
This is done, @FlorianTrigodet. Please let me know how it looks when you have a chance to test it :)

**Comment by FlorianTrigodet** [comment]
It is beautiful!
