### ISSUE TITLE
anvi-refine "Search functions" gives red box with number in it, but no functions

### ISSUE THREAD

**Issue by watsonar** [merenlab/anvio#1515]
## Short description of the problem

Upon clicking the "Search functions" box after inputting a search query in the anvi-refine interactive interface, I don't get any results but get a red box saying "467". The number seems to vary depending on what I search, "ribo" gave me the number 41.

## anvi'o version

```
Anvi'o version ...............................: esther (v6.2-master)
Profile DB version ...........................: 35
Contigs DB version ...........................: 19
Pan DB version ...............................: 14
Genome data storage version ..................: 7
Auxiliary data storage version ...............: 2
Structure DB version .........................: 2
Kegg Modules DB version ......................: 2
tRNA-seq DB version ..........................: 1
```

## System info

I'm using the Meren lab's UChicago midway partition.

## Detailed description of the issue

When I try to search for my function, I get a red box saying "467", and no functions listed in search results, instead of my functions containing the word "phage" that I know are contained in these contigs. :'(

![image](https://user-images.githubusercontent.com/31998264/95270569-635d9900-0801-11eb-9907-5c2e0be7a9b6.png)

## Files to reproduce

The files and command to reproduce this issue will be in a comment on this post in the github channel of the Meren lab Slack.

Thank you! :)

**Comment by meren** [comment]
This should be now working :)
