### ISSUE TITLE
anvi-get-sequences-for-gene-calls as DNA sequences for genome_storage.db ?

### ISSUE THREAD

**Issue by jzrapp** [merenlab/anvio#1516]
## Short description of the problem

anvi-get-sequences-for-gene-calls behaves different than expected and doesn't export DNA sequences for gene calls from genome_storage.db

## anvi'o version

Anvi'o version ...............................: esther (v6.2)
Profile DB version ...........................: 31
Contigs DB version ...........................: 14
Pan DB version ...............................: 13
Genome data storage version ..................: 6
Auxiliary data storage version ...............: 2
Structure DB version .........................: 1

I installed it with Blake Sanders solution:
conda env create -f anvio-environment.yml
conda activate anvio-6.2

## System info

MacOS Mojave 10.14.6

## Detailed description of the issue

Hi,

I tried to retrieve gene calls and DNA sequences for every MAG in a collection as a fasta file. To do so, I created a genomes.db and tried to:

(anvio-6.2) $ anvi-get-sequences-for-gene-calls --report-extended-deflines -g SB-GENOMES.db -G SB_MAG1 -o GENE_CALLS_test1.fna
Genomes storage ..............................: Initialized (storage hash: hash18fa3b50)                                                
Num genomes in storage .......................: 66
Num genomes will be used .....................: 66
Exclude partial gene calls ...................: False

AA sequences FASTA ...........................: GENE_CALLS_test1.fna                                                                          

Num AA sequences reported ....................: 158,406
Num excluded gene calls ......................: 0

Instead of only reporting sequences for just SB_MAG1, I end up with a file that contains all gene calls of all 66 MAGs. Also, they come as AA, although I didn't specify aa sequences as export format.

Trying these commands, they all result in the same output file.                         

(anvio-6.2) $ anvi-get-sequences-for-gene-calls -g SB-GENOMES.db -G SB_MAG1 -o GENE_CALLS_test2.fna
Genomes storage ..............................: Initialized (storage hash: hash18fa3b50)                                                
Num genomes in storage .......................: 66
Num genomes will be used .....................: 66
Exclude partial gene calls ...................: False

AA sequences FASTA ...........................: GENE_CALLS_test2.fna                                                                     

Num AA sequences reported ....................: 158,406
Num excluded gene calls ......................: 0

(anvio-6.2) $ anvi-get-sequences-for-gene-calls --report-extended-deflines -g SB-GENOMES.db -o GENE_CALLS_test3.fna
Genomes storage ..............................: Initialized (storage hash: hash18fa3b50)                                                
Num genomes in storage .......................: 66
Num genomes will be used .....................: 66
Exclude partial gene calls ...................: False

AA sequences FASTA ...........................: GENE_CALLS_test3.fna                                                                     

Num AA sequences reported ....................: 158,406
Num excluded gene calls ......................: 0

I can manually create the fasta that I want from my bin_by_bin summary files, but I was wondering if there is a way to directly export the CDS DNA fasta per bin from anvio?

Thank you for your help!
Josephine

**Comment by meren** [comment]
Dear @jzrapp,

This is a bug we need to fix:

> Instead of only reporting sequences for just SB_MAG1, I end up with a file that contains all gene calls of all 66 MAGs

But unfortunately this part is going to take much longer to address due to a design flaw in genome storage (i.e., the genome storage does not know about DNA sequences for space considerations, which is a major shortcoming that we intend to fix in the future):

> Also, they come as AA, although I didn't specify aa sequences as export format.

We will try to make sure the first bug is addressed in `v7`. Thank you for your time to report it, and apologies for the inconvenience!

### Getting DNA sequences per bin

If you want to get gene DNA sequences per bin described in a collection, here is a workaround that will prevent any manual work on your part:

* Use `anvi-split` ([help](http://merenlab.org/software/anvio/help/programs/anvi-split/)) to split your bins in your collection (using the merged profile and contigs database) into stand-alone anvi'o databases.
* Use `anvi-get-sequences-for-gene-calls` on each resulting bin-specific contigs database :)

**Comment by jzrapp** [comment]
Thank you! Also thank you for the work-around!
