### ISSUE TITLE
[FEATURE] anvi-script-visualize-split-coverages to visualise coverage for genes across samples

### ISSUE THREAD

**Issue by dbenitom** [merenlab/anvio#1518]
## The need

When using `anvi-script-visualize-split-coverages` I realised I'd like to visualise differential coverage for individual genes or operons across samples. This is especially useful for metatranscriptomics samples.

## The solution

To include the ORFs arrows (optially with the gene call ID) as an additional element in the output graphs of `anvi-script-visualize-split-coverages`. 

## Beneficiaries

E.g. anyone who would like to visualise differential gene expression in metatranscriptomes or differential coverage due to strain variation across samples.

Please tell me if this feature is interesting and possible to implement. Thank you for your work!
David

**Comment by meren** [comment]
(this is now being discussed at #1517)
