### ISSUE TITLE
Can I save the result of ```Displaying the pan genome```?

### ISSUE THREAD

**Issue by xuechunxu** [merenlab/anvio#1519]
Hey,

When I used remote CMD tool like ```xshell``` to use Anvi'o ```anvi-display-pan -p PROJECT-PAN.db -g PROJECT-PAN-GENOMES.db``` (http://merenlab.org/2016/11/08/pangenomics-v2/) on remote server. It invoked ```xmanger``` or ```xming``` to display interactive interface. It is very slow and almost impossible to operate. 

Can I save the result of ```Displaying the pan genome```? After finish, I can download the result to my personal computer from remote server, and use browser to operate them.

**Comment by meren** [comment]
Hey @xuechunxu,

Please take a look at this post:

http://merenlab.org/2018/03/07/working-with-remote-interative/

I hope this helps.


Best,

**Comment by xuechunxu** [comment]
Looks so hard for me. It will be more better if ```Anvio``` can produce interactive file like ```Qiime2```.
Thank you very much.

**Comment by meren** [comment]
If you download those files (PAN.db and STORAGE.db) to your computer and run `anvi-pan-genome` locally to visualize the pangenome interactively.
