### ISSUE TITLE
[BUG] anvi-setup-ncbi-cogs fails

### ISSUE THREAD

**Issue by ay-amityadav** [merenlab/anvio#1525]
## Short description of the problem

Setting ncbi-cogs using `anvi-setup-ncbi-cogs` fails.

## anvi'o version

```
Anvi'o version ...............................: esther (v6.2)
Profile DB version ...........................: 31
Contigs DB version ...........................: 14
Pan DB version ...............................: 13
Genome data storage version ..................: 6
Auxiliary data storage version ...............: 2
Structure DB version .........................: 1

```

## System info

OS: `Ubuntu 16.04.5`
Anvio installation method : Installed anvio using conda in a separate environment only for anvio

## Detailed description of the issue

The command `anvi-setup-ncbi-cogs` gave the below error message,  I was expecting a successful execution of the command.

```
COG data directory ...........................: /home/amit/miniconda3/envs/anvio-6.2/lib/python3.6/site-packages/anvio/data/misc/COG
COG data source ..............................: The anvi'o default.
COG data dir .................................: /home/amit/miniconda3/envs/anvio-6.2/lib/python3.6/site-packages/anvio/data/misc/COG

WARNING
===============================================
This program will first check whether you have all the raw files, and then will
attempt to regenerate everything that is necessary from them.

Press ENTER to continue, or press CTRL + C to cancel...

Downloaded succesfully .......................: /home/amit/miniconda3/envs/anvio-6.2/lib/python3.6/site-packages/anvio/data/misc/COG/RAW_DATA_FROM_NCBI/cog2003-2014.csv
Downloaded succesfully .......................: /home/amit/miniconda3/envs/anvio-6.2/lib/python3.6/site-packages/anvio/data/misc/COG/RAW_DATA_FROM_NCBI/cognames2003-2014.tab
Downloaded succesfully .......................: /home/amit/miniconda3/envs/anvio-6.2/lib/python3.6/site-packages/anvio/data/misc/COG/RAW_DATA_FROM_NCBI/fun2003-2014.tab
Downloaded succesfully .......................: /home/amit/miniconda3/envs/anvio-6.2/lib/python3.6/site-packages/anvio/data/misc/COG/RAW_DATA_FROM_NCBI/prot2003-2014.fa.gz
[12 Oct 20 09:08:18 Formatting raw files] Decompressing protein sequences                                                                                             Traceback (most recent call last):
  File "/home/amit/miniconda3/envs/anvio-6.2/bin/anvi-setup-ncbi-cogs", line 45, in <module>
    setup.create()
  File "/home/amit/miniconda3/envs/anvio-6.2/lib/python3.6/site-packages/anvio/cogs.py", line 469, in create
    self.setup_raw_data()
  File "/home/amit/miniconda3/envs/anvio-6.2/lib/python3.6/site-packages/anvio/cogs.py", line 631, in setup_raw_data
    self.files[file_name]['func'](file_path, J(self.COG_data_dir, self.files[file_name]['formatted_file_name']))
  File "/home/amit/miniconda3/envs/anvio-6.2/lib/python3.6/site-packages/anvio/cogs.py", line 560, in format_protein_db
    f_out.write(f_in.read())
  File "/home/amit/miniconda3/envs/anvio-6.2/lib/python3.6/gzip.py", line 276, in read
    return self._buffer.read(size)
  File "/home/amit/miniconda3/envs/anvio-6.2/lib/python3.6/gzip.py", line 482, in read
    raise EOFError("Compressed file ended before the "
EOFError: Compressed file ended before the end-of-stream marker was reached

```

**Comment by meren** [comment]
Hi @ay-amityadav, it is likely that the file was corrupted / downloaded incomplete :/ Can you please rerun the command with the flag `--reset` and see if that addresses the issue?

Thank you,

**Comment by ay-amityadav** [comment]
Thank you very much, it worked.

**Comment by PatoUru** [comment]
**Hi Meren!
I think I have the same error with the anvi-setup-ncbi-cogs command (ANVIO V7):**

Config Error: Something went wrong while decompressing the downloaded file :/ It is likely    
              that the download failed and only part of the file was downloaded. If you would 
              like to try again, please run the setup command with the flag `--reset`. Here is
              what the downstream library said: 'Error -3 while decompressing data: invalid   
              code lengths set'. 

**I re-ran the command (four times :)) anvi-setup-ncbi-cogs with flag --reset, but it didn't work.
Previously in anvio 6.2 i use this command without a problem, any suggestions?
Thank you very much!
Pat**

**Comment by meren** [comment]
Sorry to hear, @PatoUru. What is your operating system? How did you install anvi'o?

**Comment by PatoUru** [comment]
The operating system is Ubuntu 20.04 and I followed this link https://merenlab.org/2016/06/26/installation-v2/
(2) Setup an anvi’o environment
    **--> Slower but reliable option**
(3) Install anvi’o
(4) Check your installation

Maybe I could install it again and see what happens?

**Comment by meren** [comment]
It is very annoying because I can't see any reason why this might be happening :(

I haven't heard this problem from anyone else although it is tested on many systems by now. I am sorry I am not very useful here.
