### ISSUE TITLE
Usage for Non-Microbial Omics Data?

### ISSUE THREAD

**Issue by YogiOnBioinformatics** [merenlab/anvio#1528]
I ran into this recently and thought this was wonderful! 
However, I was a bit confused about whether this tool is only tailored for Microbial omics work?

I would hope/imagine this platform is there for use for multi-omics from any context. 
I personally work with human iPSC multi-omics data and wanted to know if this would be fine to use.

**Comment by meren** [comment]
Although there is nothing published at the moment, we have used it to study alpha-satellites of the human chromosome :) In theory it is perfectly fine to use it apart from the fact that the default gene caller anvi'o uses, Prodigal, is only able to identify bacterial and archaeal genes effectively. Making things worse, while anvi'o allows [the user to import their own gene calls](http://merenlab.org/software/anvio/help/artifacts/external-gene-calls/), the design does not allow introns/exons (which will change soon 🤞).

But please keep us posted, through this issue or through Slack, and we would be very happy to see how it works for you and perhaps give you suggestions while finding ways to improve anvi'o to be more generic for 'omics.

**Comment by YogiOnBioinformatics** [comment]
Awesome, thanks so much!
