### ISSUE TITLE
anvi-display-pan does not work 

### ISSUE THREAD

**Issue by PatoUru** [merenlab/anvio#1529]
Hi all!
Today I installed ANVIO! I tried to make a pangenome from four MAGs. But unfortunately the last step did not work! 
(This works very well  anvi-self-test --suite pangenomics)
Any suggestion?
Thank you in advance!! 
![image](https://user-images.githubusercontent.com/47186701/96311146-366a6c80-0fdf-11eb-85ff-05428e7dfb9c.png)

**Comment by meren** [comment]
Hi @PatoUru,

Did you try clicking the blinking Draw button?

![image](https://user-images.githubusercontent.com/197307/96311804-edf78280-0fcf-11eb-8302-6de073318712.png)

**Comment by PatoUru** [comment]
Sorry :D Thank you!!
