### ISSUE TITLE
anvi-display-pan cannot work when using ubuntu on windows

### ISSUE THREAD

**Issue by xuechunxu** [merenlab/anvio#1531]
Hey,

When I use Ubuntu on windows to anvi-display-pan the result of Pangenome analysis. But it has error:
![image](https://user-images.githubusercontent.com/23622076/96394887-c2ee7800-11f5-11eb-9875-98fd804fb15b.png)

and the google chrome got:
![image](https://user-images.githubusercontent.com/23622076/96394938-db5e9280-11f5-11eb-8d34-3a1322d5bff1.png)

Thank you

**Comment by meren** [comment]
This is due to an installation error. Please make sure your cherrypy version is `8.0.0`.

```
$ python -c "import cherrypy; print(cherrypy.__version__)"
8.0.0
```

**Comment by xuechunxu** [comment]
Hey，
I have changed cherrypy version to ```8.0.0```. It seems worked. But another error occurred:
![image](https://user-images.githubusercontent.com/23622076/96411710-8170c380-121b-11eb-9c64-d60d8defdccd.png)

Anvio invoked the google chrome in my windows system. The linux I used was ```Ubuntu on windows```. 

Thank you very much

**Comment by meren** [comment]
How exactly did you install anvi'o>

**Comment by xuechunxu** [comment]
I installed according to http://merenlab.org/2016/06/26/installation-v2/
![image](https://user-images.githubusercontent.com/23622076/96460173-86526900-1255-11eb-8f75-754eb08159ca.png)

**Comment by meren** [comment]
This error doesn't seem to have anything to do with anvi'o.

![image](https://user-images.githubusercontent.com/197307/96460539-ebbc4080-11e8-11eb-8a9c-ca6c0b59569e.png)

But you can try to run the same `anvi-display-pan` command with an additional parameter: `--ip-address localhost` to see if it is going to change anything.

**Comment by xuechunxu** [comment]
Thank you very much. It works very well
