### ISSUE TITLE
[BUG] can't install v6.2 'Please add an explicit pip dependency.' error

### ISSUE THREAD

**Issue by drelo** [merenlab/anvio#1532]
## Short description of the problem

I can't install anvi'o following the installation instructions in a Fedora 32 machine
`conda env create -f anvio-environment-6.2.yml
`
```
conda --version                                                                                                                                                              
conda 4.9.0
```
## anvi'o version

trying to install v6.2...

## System info

NAME=Generic
VERSION="32 (Generic)"
ID=generic
ID_LIKE=fedora
VERSION_ID=32
PRETTY_NAME="Generic 32 (Generic)"

## Detailed description of the issue

I couldn't install anvio, I put pip=20.2.4 in the yml file as a dependency but that failed too.

## Files to reproduce

I used the yml file from the website. 

**Thanks for your help!**

**Comment by meren** [comment]
The YAML file solution works very well on Mac systems (which has a huge issue with conda dependency resolver) but often fails on Linux systems (for which conda dependency resolver works very well anyway).

Can you please instead try the instructions listed under "A more conventional way to install stable anvi'o through conda"?


Best,

**Comment by drelo** [comment]
Thanks for your reply, I didn't even noticed that section, it was hidden in my browser, thanks!
It installed flawlessly and very quick, thanks! I already run the test and everything seems fine. 
Best
