### ISSUE TITLE
pip-installed dependencies 

### ISSUE THREAD

**Issue by Lcornet** [merenlab/anvio#1539]
## Short description of the problem

I would like to use the master version of Anvio but failed to install it via Conda.

## anvi'o version

master

## System info

Ubuntu 18.04

## Detailed description of the issue

conda env create -f anvio-environment-master.yml
Warning: you have pip-installed dependencies in your environment file, but you do not list pip itself as one of your conda dependencies.  Conda may not use the correct pip to install your packages, and they may end up in the wrong place.  Please add an explicit pip dependency.  I'm adding one for you, but still nagging you.
Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound:
  - yaml==0.2.2=h0b31af3_1
  - perl-clone==0.42=pl526h01d97ff_0
  - r-ellipsis==0.3.0=r35h159158b_0
  - lz4-c==1.8.3=h6de7cb9_1001
  - xorg-renderproto==0.11.1=h1de35cc_1002

...

## Files to reproduce

I follow wget http://merenlab.org/files/anvio-conda-environments/anvio-environment-master.yml

**Comment by Lcornet** [comment]
Following "http://merenlab.org/2015/08/22/docker-image-for-anvio/ " for install the master in a docker. 

$ git clone https://github.com/merenlab/anvio.git
$ cd anvio/
$ sudo docker build -t meren/anvio:master .

I have this error: 

conda.exceptions.ResolvePackageNotFound:
  - bioconductor
  - anvio-minimal==6.2_master

**Comment by meren** [comment]
Hi @Lcornet, I'm sorry for all the trouble you've been dealing with and thanks for your patience so far.

If you are using Linux, you should not follow the YAML recipe which causes issues with pip. I just updated the installation manual to make sure it is clear by adding a new section:

![image](https://user-images.githubusercontent.com/197307/97305588-4aa63900-182b-11eb-8d42-6077aa1fb79a.png)

Please follow that and let us know if it solved the installation through master.

**Comment by Lcornet** [comment]
Thanks a lot for the quick help.

I had to manually redo some pip (5 or 6) but anyway it works well now.

Thanks
