### ISSUE TITLE
[FEATURE] Improve anvi-script-get-short-reads-matching-something

### ISSUE THREAD

**Issue by FlorianTrigodet** [merenlab/anvio#1542]
## The need

`anvi-script-get-short-reads-matching-something` could use a samples.txt file to report the shorts reads matching a sequence from multiple samples (with one output fasta per sample).

A second improvement: provide a list of sequence to match. The idea is to go through all sample for every sequence to match. In the end, the number of output fasta file should be: num_of_sequence_to_match*num_of_sample.

Bonus point: make it multi-thread. The command would be more practical with a `samples.txt` and `sequences_to_match.txt` files, but I don't know if it would be quicker. And it would improve my life if it could run on multiple threads. 

## The solution

Use a `samples.txt` file as input to go through multiple samples in one command.
Use a `sequences_to_match.txt` file containing multiple sequences of interest. 

## Beneficiaries

This is maybe a niche demand, but a welcome improvement :)

**Comment by meren** [comment]
@FlorianTrigodet, I implemented this and merged it to the main repository.

The same program is now called `anvi-script-get-primer-matches`.

Please test it and let me know how it feels.

**Comment by FlorianTrigodet** [comment]
Thanks a lot, I'll try it right now :)

**Comment by meren** [comment]
@FlorianTrigodet, the program is documented here:

https://merenlab.org/software/anvio/help/main/programs/anvi-script-get-primer-matches/

And the artifact `samples-txt` here:

https://merenlab.org/software/anvio/help/main/artifacts/samples-txt/

If you see any ways to improve them, please feel free to edit either.

**Comment by FlorianTrigodet** [comment]
Seems to work but does not use the `--output-dir` argument. No errors, it just go with the default `./MATCHING_SEQUENCES` directory.
