### ISSUE TITLE
[FEATURE] Sorted HMM classes in the anvi-display-contig-stats output

### ISSUE THREAD

**Issue by meren** [merenlab/anvio#1546]
## The need

Having this list to be sorted alphabetically:

![image](https://user-images.githubusercontent.com/197307/98052066-d8b98b00-1dfa-11eb-9254-14da60fe9fb8.png)

## The solution

Sorting it perhaps?

## Beneficiaries

Anyone who has to look at these things a lot.

**Comment by FlorianTrigodet** [comment]
Fixed:
<img width="335" alt="Screen Shot 2020-11-03 at 8 59 04 PM" src="https://user-images.githubusercontent.com/10922896/98064381-cb5ec980-1e17-11eb-8303-b24bcab0aa51.png">

**Comment by meren** [comment]
PHOTOSHOP.
