### ISSUE TITLE
[FEATURE] Update anvi-interactive help to include tips for server / IP / port configuration

### ISSUE THREAD

**Issue by RicardoGCCR** [merenlab/anvio#1548]
Hi, 
I am trying to run anvi-display-pan on my laptop, but after the message saying:

* The server is now listening the port number '8080'. When you are finished, press
CTRL+C to terminate the server. If you are using OSX and if the server
terminates prematurely before you can see anything in your browser, try to run
the same command by putting 'sudo ' at the beginning of it (you will be likely
prompted to enter your password as this command will require super user rights
to run)

**tcgetpgrp failed: Not a tty**

And chrome could not load the page

Replace this text with a single-sentence description of the problem.

## anvi'o version : 

Anvi'o version ...............................: esther (v6.2)
Profile DB version ...........................: 31
Contigs DB version ...........................: 14
Pan DB version ...............................: 13
Genome data storage version ..................: 6
Auxiliary data storage version ...............: 2
Structure DB version .........................: 1

## System info

Ubuntu (WSL2 - Windows 10)

## Detailed description of the issue
I tried the same command with my university server and works fine. 

Any help?

Thanks
Ricardo

**Comment by RicardoGCCR** [comment]
Hi, 
I managed to run anvi-display-pan on Windows Terminal (with ubuntu), following the approach suggested in the issue #993 :
https://github.com/merenlab/anvio/issues/993

I copy the solution from issue #993:

############################
 Can you try adding flags below when running anvi-display-pan

--server-only --ip-address 127.0.0.1
Then after seeing message

* The server is now listening the port number "8080". When you are finished, press
CTRL+C to terminate the server.

######################

It worked perfectly. 

Best,
Ricardo

**Comment by meren** [comment]
Thank you very much for updating us with your solution, @RicardoGCCR. 

I am not going to close this issue so we can remember to include some tips for similar situations here:

http://merenlab.org/software/anvio/help/programs/anvi-interactive/

The source file of which is here: 

https://github.com/merenlab/anvio/blob/master/anvio/docs/programs/anvi-interactive.md

**Comment by RicardoGCCR** [comment]
Cheers!
Thank you for your service.
Ricardo

**Comment by meren** [comment]
5dfa83932c797e8ba57cbba620f26883ae47628e closes this :)
