### ISSUE TITLE
[BUG/FEATURE] A thread to improve anvi'o inspection page

### ISSUE THREAD

**Issue by meren** [merenlab/anvio#1550]
I am using the active branch of anvi'o to test @isaacfink21's recent changes to the anvi'o inspection page for contigs. Following is a bunch of bugs and/or feature requests for usability. Thank you for your efforts, Isaac. This is going very well.

Here are some suggestions on these for starters,

- [x] **Settings panel accessibility**
- [x] **Tabs in the settings panel**
- [x] **The default coloring of genes**
- [x] **Agglomerating all settings in the settings panel**
- [x] **anvi-inspect snafu**

which are detailed in the sections below (and following issues).

# Settings panel accessibility

When I press ‘S’, the settings panel does not open/close:

![image](https://user-images.githubusercontent.com/197307/98386253-8bfdcc00-2015-11eb-9138-34bc8ce90979.png)

# Tabs in the settings panel

I think it will much easier for the user if these were not individual tabs, but were different sections of a single tab:

![image](https://user-images.githubusercontent.com/197307/98386324-a6d04080-2015-11eb-8db4-68bf9dbf7df0.png)

Similar to how we do this in the "Additional Settings" section of the main settings tab in the main display. Sections and options in a single display.

# The default coloring of genes

I think this should be the default coloring:

![image](https://user-images.githubusercontent.com/197307/98386495-db43fc80-2015-11eb-9678-bb70ed7405a7.png)

This wold preserve the default behavior and wouldn't surprise users. Another issue here is that when I change the coloring scheme of genes, this information is not being carried over to the next split when I click next. These selections should be stored in the global `state` so users don't have to click those buttons again and again as they browse their splits :)

# Agglomerating all settings in the settings panel

These should go into the settings window as well, so all settings are in one place :)

![image](https://user-images.githubusercontent.com/197307/98386661-13e3d600-2016-11eb-887a-9887914facdf.png)

**Comment by meren** [comment]
# anvi-inspect snafu

When the interface is initiated through `anvi-inspect`, we get an error:

```
Uncaught TypeError: Cannot read property 'attr' of undefined
    at charts.js?rand=dad29b1edb475bf1d998e0b1046bb73c:59
    at dispatch (jquery.js:4670)
    at r.handle (jquery.js:4338)
```

**Comment by isaacfink21** [comment]
Thanks for all this! I just added two commits (4bafe29 and 0af69e3) that address these issues.

> Another issue here is that when I change the coloring scheme of genes, this information is not being carried over to the next split when I click next. These selections should be stored in the global state so users don't have to click those buttons again and again as they browse their splits :)

As for this issue, I initially added the 'Reset function colors' button to reset any unintended color changes back to the current state - the user has to manually save the state to save gene colors. Now that I’m reviewing it, though, I see that it adds an unnecessary step - I think it would make more sense for this button to reset genes to the default color set.

**Comment by meren** [comment]
> Thanks for all this! I just added two commits (b9c63d2 and 0af69e3) that address these issues.

Thank you very much! I will continue testing.

> the user has to manually save the state to save gene colors

Yes, I think the user should manually save the state to store gene colors permanently across anvi-interactive sessions. But if they make a change, it should be kept across split pages within a session even if they don't store the state :) So we basically can add every change to the existing global state object.

**Comment by meren** [comment]
Hey @isaacfink21, I've made some cosmetic changes on the panel. Please pull from main and take a look. 

One remaining issue at the moment is that when I click on the green button here,

![image](https://user-images.githubusercontent.com/197307/98478172-64953380-21bc-11eb-96c9-e7a2f68f2394.png)

it immediately goes to black:

![image](https://user-images.githubusercontent.com/197307/98478331-71198c00-21bc-11eb-9441-c15344dc30fe.png)

**Comment by meren** [comment]
- [ ] Settings panel should come hidden (otherwise it becomes annoying very quickly to having to hide it every time :))

**Comment by meren** [comment]
- [ ] I think we should turn that button into a checkbox for brevity and consistency:

![image](https://user-images.githubusercontent.com/197307/98483737-6e289680-21d0-11eb-91af-421a6d2222db.png)

**Comment by meren** [comment]
I think it is time to retire this issue :)
