### ISSUE TITLE
Batch process in anvio

### ISSUE THREAD

**Issue by razz1618** [merenlab/anvio#1552]
Hi, i have recently assembled and binned (using squeezemeta pipeline) 10 different metagenomic samples separately. I want to add it to ANVIO's and visualize, curate, and further process the bins. Is it possible to batch create the contig.db and profile.db from these 10 contig.fa and their respective BAM files.  My idea is to further merge this data so that finally I can get a single chart with all 10 samples, their bins, taxonomy and functions.

**Comment by meren** [comment]
It is quite doable as many groups do this including ourselves. You can either **create your own batch script** in BASH that uses `anvi-gen-contigs-database` to profile your FASTA file(s), `anvi-profile` to profile your BAM files, and `anvi-import-collection` to import your bins into the profile database, OR you can use [anvi'o snakemake workflows](http://merenlab.org/2018/07/09/anvio-snakemake-workflows/), in which case [this section](http://merenlab.org/2018/07/09/anvio-snakemake-workflows/#can-i-use-bam-files-as-input-for-the-metagenomics-workflow) would be most relevant.

Best,
