### ISSUE TITLE
Completing the documentation

### ISSUE THREAD

**Issue by Jessica-Pan** [merenlab/anvio#1553]
Hello everyone! Here is a full list of things that still need to be documented in anvi’o as of 11/10/2020. 

Feel free to take over any one of these tasks or send me things to add to the list if I missed something or an existing description is unclear in any way. Thank you in advance!

**Section 1**: Programs and artifacts that haven’t been described, but are displayed on the help page on the website. (aka pages that display the sad "No one has described the usage of this program :/" or the "No one has described this artifact yet :/" text)

 - [x] anvi-db-info
 - [x] anvi-gen-fixation-index-matrix
    - [x] fixation-index-matrix (artifact)
 - [x] anvi-oligotype-linkmers
    - [x] oligotypes (artifact)
 - [x] anvi-run-interacdome
    - [x] anvi-setup-interacdome
    - [x] interacdome-data (artifact)
    - [x] binding-frequencies (artifiact)
 - [x] anvi-trnaseq 
    - [x] trnaseq-db (artifact)
 - [x] anvi-estimate-trna-taxonomy
    - [x] trna-taxonomy (artifact)
    - [x] anvi-run-trna-taxonomy
    - [x] trna-taxonomy-db (artifact)
    - [x] anvi-setup-trna-taxonomy 
 - [x] anvi-script-augustus-output-to-external-gene-calls
 - [x] anvi-script-calculate-pn-ps-ratio
    - [x] pn-ps-data (artifact)
 - [x] anvi-script-filter-fasta-by-blast
 - [x] anvi-script-gen-distribution-of-genes-in-a-bin 
 - [x] anvi-script-gen-pseudo-paired-reads-from-fastq
 - [x] anvi-script-get-hmm-hits-per-gene-call
 - [x] anvi-script-process-genbank-metadata
 - [x] anvi-script-snvs-to-interactive

**Section 2**: Programs that haven't been described or given provides/requires statements (these are lower priority, and some may be replaced or defunct)

- [x] anvi-help
- [x] anvi-script-run-functional-enrichment-stats 
- [x] anvi-migrate
- [x] anvi-script-visualize-split-coverages
- [x] anvi-self-test
- [x] anvi-gen-network
- [x] anvi-script-transpose-matrix
- [x] anvi-export-table
- [x] anvi-experimental-organization 
     - [x] clustering-configuration
- [x] anvi-script-tabulate
- [x] anvi-push
- [x] anvi-script-gen-scg-domain-classifier
- [x] anvi-script-predict-CPR-genomes
- [x] anvi-run-workflow
    - [x] samples-txt
    - [x] fasta-txt 
    - [x] workflow-config
    - [x] contigs-workflow
    - [x] metagenomics-workflow
    - [x] phylogenomics-workflow
    - [x] pangenomics-workflow
    - [x] transeq-workflow
- [x] anvi-gen-variability-network
- [x] anvi-agglomerate 

**Section 3**: Programs that are described but could greatly benefit from an exaple use case or more details 

- [x] anvi-get-short-reads-from-bam (specifically definitions for R1 and R2) 

**Section 4**: Programs that are unlikely working and/or ready for primetime

- [x] anvi-gen-variability-matrix
- [x] anvi-estimate-genome-taxonomy (defunct)
- [x] anvi-script-checkm-tree-to-interactive (not clear if it is still functional)
- [x] anvi-upgrade (not clear if it is still functional)
- [x] anvi-mcg-classifier (not clear if it is still functional)
- [x] anvi-script-run-eggnog-mapper (not clear if it is still functional)
- [x] anvi-script-gen_stats_for_single_copy_genes.sh (shouldn't be used by anyone)
- [x] anvi-script-gen-CPR-classifier (meh)

**Comment by ivagljiva** [comment]
I promise to take care of `anvi-db-info` and `anvi-script-process-genbank-metadata` this week :)

**Comment by meren** [comment]
I think we can retire this issue :) Thank you very much, @Jessica-Pan! I think the most important ones are now taken care of.
