### ISSUE TITLE
.h5 should revised to .db

### ISSUE THREAD

**Issue by xuechunxu** [merenlab/anvio#1557]
Hey,

In manual (http://merenlab.org/data/prochlorococcus-metapangenome/), The genomes storage file should end with '-GENOMES.db', not 'GENOMES.h5'. Maybe because you used h5 in old version.
![image](https://user-images.githubusercontent.com/23622076/99276273-75ead980-2867-11eb-933c-45f046dfaa75.png)

Best,
Chunxu

**Comment by ekiefl** [comment]
Thanks for the report.

Like our documentation, perhaps our tutorials should be part of the codebase too, and could therefore be versioned to avoid issues like this. It is a lot of work to update tutorials, but I think I speak for everyone that the largest deterrent is **not** that a lot has to be changed, but rather that the codebase is a moving target, and that your changes will not stand the test of time. By versioning, every change will be stuck in time, and permanently relevant for a given version of anvi'o.

**Comment by meren** [comment]
Yes :/ I agree that the disconnected repositories for code and documentation is not really helping.

**Comment by meren** [comment]
This is now fixed.
