### ISSUE TITLE
[BUG] Inspect page - Get Sequence for a Range or Selection

### ISSUE THREAD

**Issue by FlorianTrigodet** [merenlab/anvio#1559]
## Short description of the problem

When you want to get the sequence for a given selection, there is a sneaky `\n` in the actual sequence window.

## anvi'o version

Up-to-date master version.

## System info

MacOS 10.14.06 

## Detailed description of the issue

![ezgif com-gif-maker](https://user-images.githubusercontent.com/10922896/99318684-cb09f980-282d-11eb-916b-6fa06a0ff9fd.gif)

## Files to reproduce

I guess any "inspect page" should reproduce the error.

**Comment by isaacfink21** [comment]
Should be fixed now 👍
