### ISSUE TITLE
Doubt with Prodigal ORFs detection

### ISSUE THREAD

**Issue by jsevereyn** [merenlab/anvio#1563]
Hello Anvi'o team, thank you for your help 

I Have an issue but I'm not sure what to ask. So, let me tell you the whole short version.

I'm following the pan-genomics tutorial for a set of 11 external genomes of Acidithiobacillus ferrooxidans. In the generation of the contigs.db, for one of the genomes (X) Prodigal detected 6175 ORFs, way above those detected in the rest of the strains (3300 average).

I found this odd, as there are the same species and effectively when I later extracted the singletons using anvi-get-sequences-for-gene-clusters, I get 3300 total singletons of which 2594 belongs to the X genome, odd as well, maybe...

So, for my own peace of mind I annotated all the 11 genomes (.fasta files) with prokka (which I believe it also use Prodigal) and for the same X genome it only detected 3802 ORFs, much more coherent with the rest of the genomes and quite fewer comparing with the 6175 ORFs detected during the genome_X_contigs.db.

I guess what I'm wondering is what to believe, has something like this happened to someone else?

PD: as requested by Meren, here I'm sending the Contigs.db and the genome .fasta file, to take a look at it by the development branch to know if there is something interesting or if there is a bug in the codebase.

[Archivo comprimido.zip](https://github.com/merenlab/anvio/files/5555794/Archivo.comprimido.zip)

**Comment by meren** [comment]
Hey @jsevereyn, 

I figured that the reason for that is the tremendous number of short contigs in your FASTA file.

Essentially, 90% of the contigs in this FASTA file is less than 1,000 nucleotides long, and a crazy amount of them is contamination from another organism.

```
anvi-script-reformat-fasta A_ferrooxidans_MC2-2.fasta --min-len 1000 -o A_ferrooxidans_MC2-2-better.fasta
Input ........................................: A_ferrooxidans_MC2-2.fasta
Output .......................................: A_ferrooxidans_MC2-2-better.fasta
Minimum length ...............................: 1,000
Max % gaps allowed ...........................: 100.00%
Total num contigs ............................: 3,019
Total num nucleotides ........................: 3,778,454
Contigs removed ..............................: 2690 (89.10% of all)
Nucleotides removed ..........................: 934898 (24.74% of all)
Nucleotides modified .........................: 0 (0.00% of all)
Deflines simplified ..........................: False
```

Not an anvi'o bug :)

Best,
