### ISSUE TITLE
[FEATURE] New COG database version 2020

### ISSUE THREAD

**Issue by Sirbius** [merenlab/anvio#1567]
## The need
Hi there,
A new version of the COG database has been released in September 2020 and since there are good improvement, as announced [here](https://www.ncbi.nlm.nih.gov/research/cog), I was wondering if we could import it on anvi'o.

## The solution
Ideally, just few changes in the anvi-setup-ncbi-cogs script where it points at the [ftp page](https://www.ncbi.nlm.nih.gov/research/cog-project/) should do the job (?). 

## Beneficiaries
Everyone who is working with COG annotation and is tired to read so many undefined proteins.

Not sure if it's the right place too, but besides the COG function, the COG category in the enrichment file would also be great for downstream analysis and fancy plots.

Thank you guys! You work is amazing!! 

Silvia

**Comment by xvazquezc** [comment]
I'd suggest to keep some backwards compatibility if somebody needs to use the older (current) version. I think there is something alike in the scg data used from the GTDB

**Comment by meren** [comment]
Thanks for the report, @Sirbius. I will look into this (although a very preliminary investigation showed that they changed everything, so it will take some effort to get it into anvi'o).

> I'd suggest to keep some backwards compatibility if somebody needs to use the older (current) version

I agree, that would be ideal. But I am not sure what would be the best way to do it. Thinking out loud here, the best way I can think of would be the following:

* Write a migration script to rename all occurrences of `COG_CATEGORY` and `COG_FUNCTION` in existing contigs databases to `COG14_CATEGORY` and `COG14_FUNCTION`.
* Add a --cog-version flag to `anvi-setup-ncbi-cogs` and `anvi-run-ncbi-cogs` (the default would be 2020, and would annotate contigs databases with `COG20_CATEGORY` and `COG20_FUNCTION`, but the user can change it to 2014 to setup databases and run them).


Best,

**Comment by meren** [comment]
Regarding this part of your comment @Sirbius, 

> Not sure if it's the right place too, but besides the COG function, the COG category in the enrichment file would also be great for downstream analysis and fancy plots.

@ivagljiva is working on generalizing @adw96's method to compute enrichment statistic, which will accept any functional source to calculate enrichment scores. Since we store `COG_FUNCTION` and `COG_CATEGORY` as distinct functional sources per gene, in theory you will be able to do enrichment analyses on `COG_CATEGORY` seamlessly :)

**Comment by ivagljiva** [comment]
>  in theory you will be able to do enrichment analyses on COG_CATEGORY seamlessly :)

In fact, you should already be able to do this for pangenome functional enrichment with `anvi-get-enriched-functions-per-pan-group --annotation-source COG_CATEGORY`.

The program I am working on that generalizes this script, `anvi-compute-enrichment-stats`, will eventually allow you to also do functional enrichment for bins in a collection. :)

**Comment by Sirbius** [comment]
Yes guys,
I already did the enrichment with the COG function.
I was just saying that in its output file could be useful another column
with the COG categories (A, B, C...) as present for example in the output
file of anvio-summarize.

The program I am working on that generalizes this script,
> anvi-compute-enrichment-stats, will eventually allow you to also do
> functional enrichment for bins in a collection. :)
>

That will be awesome!!
Thanks!!

**Comment by meren** [comment]
> I already did the enrichment with the COG function.
> I was just saying that in its output file could be useful another column
> with the COG categories (A, B, C...) as present for example in the output
> file of anvio-summarize.

Ah, I see. It is not technically quite feasible since our design treats COG functions and COG categories as distinct sources for functional annotation :/

**Comment by Sirbius** [comment]
Then,
No problem, I would just retrieve them from the other file when needed!
Cheers,

Silvia :)

Il mer 25 nov 2020, 20:12 A. Murat Eren <notifications@github.com> ha
scritto:

**Comment by meren** [comment]
@xvazquezc, I implemented this (see the PR #1570) and it is available in the branch `update_cogs` in case you would like to test it before we merge it.

**Comment by Sirbius** [comment]
Hi @Meren,

Could you push these new improvements on the docker file? Thanks!!

**Comment by meren** [comment]
I don't think I will be able to that any time soon, @Sirbius. If you are unable to follow the active repository through GitHub, it will have to wait until the official release of `v7`.

**Comment by xvazquezc** [comment]
> @xvazquezc, I implemented this (see the PR #1570) and it is available in the branch `update_cogs` in case you would like to test it before we merge it.

Do you still need testing on this?

**Comment by meren** [comment]
Sure, if you have time and energy, @xvazquezc :) That would be great to have one more person other than myself and @ivagljiva to test it and tell us if it feels alright.

**Comment by xvazquezc** [comment]
OK, I've tested the migration of the COG annotations from an old profile and it converts the COG annotations. I've set up the new COG20 and made the calls too. No issues with any of this.

I've been able to install the old COGs at the same time, however, before that, I tried to run the COG14 annotation and...
```
$ anvi-run-ncbi-cogs -c GCA_000247605.db -T 6 --cog-version COG14
COG version ..................................: COG14
COG data source ..............................: The anvi'o default.
COG base directory ...........................: /home/xabi/Desktop/repos/anvio/anvio/data/misc/COG


Config Error: You requested to run the NCBI COGs using the version 'COG14', but you don't have
              the data to be able to run that version of COGs setup on this system yet. Here  
              is the only version available for COGs on this system: COG20. You can either    
              specify which version you wish to use through the parameter `--cog-version`, or 
              you can run the following command to setup the data files for the version you   
              wish to use: `anvi-setup-ncbi-cogs --version COG14`, and re-run the same command
              that brought you here.
```

Weird thing is that if you run `anvi-setup-ncbi-cogs --version COG14` (as suggested, please fix) or try to run `anvi-setup-ncbi-cogs` with anything provided through the `--version` option, I get this:
```
$ anvi-setup-ncbi-cogs -T 6 --version COG14
Anvi'o version ...............................: esther (v6.2-master)
Profile DB version ...........................: 35
Contigs DB version ...........................: 20
Pan DB version ...............................: 14
Genome data storage version ..................: 7
Auxiliary data storage version ...............: 2
Structure DB version .........................: 2
Kegg Modules DB version ......................: 2
tRNA-seq DB version ..........................: 1
```
It took me a while to figure out that `--version` is actually a universal flag for `anvi-*` programs not an option requiring input, and that I should use `--cog-version` instead.

Otherwise, all good!

**Comment by meren** [comment]
Great catch, @xvazquezc! Thank you very much for looking into this :) It is always great to have an external pair of eyes. 

I will fix this and merge it to the main repository.

**Comment by meren** [comment]
This is now in anvi'o main branch via #1570.

Thank you all!
