### ISSUE TITLE
Config error: Bad news of the day: the database at (...).db was generated with  an anvi'o version that is 'newer' (...)

### ISSUE THREAD

**Issue by RicardoGCCR** [merenlab/anvio#1568]
Hi, 
I was trying to run the anvi-display-pan in my laptop with the files produced on the university cluster. In the past, I run it without any issue with the command: 
$ anvi-display-pan -p Clado_2_new_run-PAN.db -g Clado_2_new_run-PAN.db --server-only --ip-address 127.0.0.1

But now I am getting the following error:

Config Error: Bad news of the day: the database at Clado_2_new_run-PAN.db was generated with
              an anvi'o version that is 'newer' than the one you are actively using right now.
              We know, you hate to hear this, but you need to upgrade your anvi'o :(

The only difference between previous runs is that this time the anvi-pan was run with ncbi instead of DIAMOND.

As you can see below, both anvio versions are the same.

Could you please assist me with this issue?

## anvi'o version

**Laptop:**
Anvi'o version ...............................: esther (v6.2)
Profile DB version ...........................: 31
Contigs DB version ...........................: 14
Pan DB version ...............................: 13
Genome data storage version ..................: 6
Auxiliary data storage version ...............: 2
Structure DB version .........................: 1

**University cluster:**
Anvi'o version ...............................: esther (v6.2)
Profile DB version ...........................: 31
Contigs DB version ...........................: 14
Pan DB version ...............................: 13
Genome data storage version ..................: 6
Auxiliary data storage version ...............: 2
Structure DB version .........................: 1

```
anvi-self-test --version
```

## System info

WSL/Ubuntu 20 installed a Windows 10

**Comment by meren** [comment]
Hi @RicardoGCCR, there is no other technically possible explanation for the error you are getting: the database was generated in a newer version of anvi'o. NCBI BLAST vs DIAMOND can not cause this.

Just for fun, can you also please send the output of this command:

```
anvi-db-info Clado_2_new_run-PAN.db
```

**Comment by RicardoGCCR** [comment]
Hi @meren, 
Thank you for your fast reply. 

This is the output from my laptop: 

DB Info (no touch)
===============================================
Database Path ................................: Clado_2_new_run-PAN.db
Description ..................................: _No description is provided_
Type .........................................: pan
Version ......................................: 13


DB Info (no touch also)
===============================================
internal_genome_names ........................:
external_genome_names ........................: grupo1_ST41_01,grupo1_ST41_02,grupo1_ST41_03,grupo1_ST41_04,grupo1_ST41_05,grupo1_ST41_06,grupo1_ST41_07,grupo1_ST41_08,grupo1_ST41_09,grupo1_ST41_10,grupo1_ST41_11,grupo1_ST41_12,grupo1_ST41_13,grupo1_ST41_14,grupo1_ST41_15,grupo1_ST41_16,grupo1_ST41_17,grupo1_ST41_18,grupo1_ST41_19,grupo1_ST41_20,grupo1_ST41_21,grupo1_ST41_22,grupo1_ST41_23,grupo1_ST41_24,grupo1_ST41_25,grupo1_ST41_26,grupo1_ST41_27,grupo1_ST41_28,grupo1_ST41_29,grupo2_ST67_01,grupo2_ST67_02,grupo2_ST67_03,grupo2_ST67_04,grupo2_ST67_05,grupo2_ST67_06,grupo2_ST67_07,grupo2_ST67_08,grupo2_ST67_09,grupo2_ST67_10,grupo2_ST67_11,grupo2_ST67_12,grupo2_ST67_13,grupo2_ST67_14,grupo2_ST67_15,grupo2_ST67_16,grupo2_ST67_17,grupo2_ST67_18,grupo2_ST67_19,grupo2_ST67_20,grupo2_ST67_21,grupo2_ST67_22,grupo2_ST67_23,grupo2_ST67_24,grupo2_ST67_25,grupo2_ST67_26,grupo2_ST67_27,grupo2_ST67_28,grupo2_ST67_29,grupo2_ST67_30,grupo3_subclade_01,grupo3_subclade_02,grupo3_subclade_03,grupo3_subclade_04,grupo3_subclade_05,grupo3_subclade_06,grupo3_subclade_07,grupo3_subclade_08,grupo3_subclade_09,grupo3_subclade_10,grupo3_subclade_11,grupo3_subclade_12,grupo3_subclade_13,grupo3_subclade_14,grupo3_subclade_15,grupo3_subclade_16,grupo3_subclade_17,grupo3_subclade_18,grupo3_subclade_19,grupo3_subclade_20,grupo3_subclade_21,grupo3_subclade_22,grupo3_subclade_23,grupo3_subclade_24,grupo3_subclade_25,grupo3_subclade_26,grupo3_subclade_27,grupo3_subclade_28,grupo3_subclade_29,grupo3_subclade_30,grupo3_subclade_31,grupo3_subclade_32,ref_01,ref_02,ref_03,ref_04,ref_05,ref_06,ref_07,ref_08,ref_09,ref_10,ref_11,ref_12,ref_13,ref_14,ref_15,ref_16,ref_17,ref_18,ref_19,ref_20,ref_21,ref_22,ref_23,ref_24,ref_25,ref_26,ref_27,ref_28,ref_29
num_genomes ..................................: 120
min_percent_identity .........................: 0.0
gene_cluster_min_occurrence ..................: 1
mcl_inflation ................................: 10.0
default_view .................................: gene_cluster_presence_absence
use_ncbi_blast ...............................: 1
diamond_sensitive ............................: 1
minbit .......................................: 0.5
exclude_partial_gene_calls ...................: 0
gene_alignments_computed .....................: 1
genomes_storage_hash .........................: hashda61442e
project_name .................................: Clado_2_new_run
creation_date ................................: 1606172253.23703
num_gene_clusters ............................: 6715
num_genes_in_gene_clusters ...................: 460392
default_item_order ...........................: presence-absence:euclidean:ward
available_item_orders ........................: frequency:euclidean:ward,presence-absence:euclidean:ward,Forced synteny <> grupo1_ST41_01:NA:NA,Forced synteny <> grupo1_ST41_02:NA:NA,Forced synteny <> grupo1_ST41_03:NA:NA,Forced synteny <> grupo1_ST41_04:NA:NA,Forced synteny <> grupo1_ST41_05:NA:NA,Forced synteny <> grupo1_ST41_06:NA:NA,Forced synteny <> grupo1_ST41_07:NA:NA,Forced synteny <> grupo1_ST41_08:NA:NA,Forced synteny <> grupo1_ST41_09:NA:NA,Forced synteny <> grupo1_ST41_10:NA:NA,Forced synteny <> grupo1_ST41_11:NA:NA,Forced synteny <> grupo1_ST41_12:NA:NA,Forced synteny <> grupo1_ST41_13:NA:NA,Forced synteny <> grupo1_ST41_14:NA:NA,Forced synteny <> grupo1_ST41_15:NA:NA,Forced synteny <> grupo1_ST41_16:NA:NA,Forced synteny <> grupo1_ST41_17:NA:NA,Forced synteny <> grupo1_ST41_18:NA:NA,Forced synteny <> grupo1_ST41_19:NA:NA,Forced synteny <> grupo1_ST41_20:NA:NA,Forced synteny <> grupo1_ST41_21:NA:NA,Forced synteny <> grupo1_ST41_22:NA:NA,Forced synteny <> grupo1_ST41_23:NA:NA,Forced synteny <> grupo1_ST41_24:NA:NA,Forced synteny <> grupo1_ST41_25:NA:NA,Forced synteny <> grupo1_ST41_26:NA:NA,Forced synteny <> grupo1_ST41_27:NA:NA,Forced synteny <> grupo1_ST41_28:NA:NA,Forced synteny <> grupo1_ST41_29:NA:NA,Forced synteny <> grupo2_ST67_01:NA:NA,Forced synteny <> grupo2_ST67_02:NA:NA,Forced synteny <> grupo2_ST67_03:NA:NA,Forced synteny <> grupo2_ST67_04:NA:NA,Forced synteny <> grupo2_ST67_05:NA:NA,Forced synteny <> grupo2_ST67_06:NA:NA,Forced synteny <> grupo2_ST67_07:NA:NA,Forced synteny <> grupo2_ST67_08:NA:NA,Forced synteny <> grupo2_ST67_09:NA:NA,Forced synteny <> grupo2_ST67_10:NA:NA,Forced synteny <> grupo2_ST67_11:NA:NA,Forced synteny <> grupo2_ST67_12:NA:NA,Forced synteny <> grupo2_ST67_13:NA:NA,Forced synteny <> grupo2_ST67_14:NA:NA,Forced synteny <> grupo2_ST67_15:NA:NA,Forced synteny <> grupo2_ST67_16:NA:NA,Forced synteny <> grupo2_ST67_17:NA:NA,Forced synteny <> grupo2_ST67_18:NA:NA,Forced synteny <> grupo2_ST67_19:NA:NA,Forced synteny <> grupo2_ST67_20:NA:NA,Forced synteny <> grupo2_ST67_21:NA:NA,Forced synteny <> grupo2_ST67_22:NA:NA,Forced synteny <> grupo2_ST67_23:NA:NA,Forced synteny <> grupo2_ST67_24:NA:NA,Forced synteny <> grupo2_ST67_25:NA:NA,Forced synteny <> grupo2_ST67_26:NA:NA,Forced synteny <> grupo2_ST67_27:NA:NA,Forced synteny <> grupo2_ST67_28:NA:NA,Forced synteny <> grupo2_ST67_29:NA:NA,Forced synteny <> grupo2_ST67_30:NA:NA,Forced synteny <> grupo3_subclade_01:NA:NA,Forced synteny <> grupo3_subclade_02:NA:NA,Forced synteny <> grupo3_subclade_03:NA:NA,Forced synteny <> grupo3_subclade_04:NA:NA,Forced synteny <> grupo3_subclade_05:NA:NA,Forced synteny <> grupo3_subclade_06:NA:NA,Forced synteny <> grupo3_subclade_07:NA:NA,Forced synteny <> grupo3_subclade_08:NA:NA,Forced synteny <> grupo3_subclade_09:NA:NA,Forced synteny <> grupo3_subclade_10:NA:NA,Forced synteny <> grupo3_subclade_11:NA:NA,Forced synteny <> grupo3_subclade_12:NA:NA,Forced synteny <> grupo3_subclade_13:NA:NA,Forced synteny <> grupo3_subclade_14:NA:NA,Forced synteny <> grupo3_subclade_15:NA:NA,Forced synteny <> grupo3_subclade_16:NA:NA,Forced synteny <> grupo3_subclade_17:NA:NA,Forced synteny <> grupo3_subclade_18:NA:NA,Forced synteny <> grupo3_subclade_19:NA:NA,Forced synteny <> grupo3_subclade_20:NA:NA,Forced synteny <> grupo3_subclade_21:NA:NA,Forced synteny <> grupo3_subclade_22:NA:NA,Forced synteny <> grupo3_subclade_23:NA:NA,Forced synteny <> grupo3_subclade_24:NA:NA,Forced synteny <> grupo3_subclade_25:NA:NA,Forced synteny <> grupo3_subclade_26:NA:NA,Forced synteny <> grupo3_subclade_27:NA:NA,Forced synteny <> grupo3_subclade_28:NA:NA,Forced synteny <> grupo3_subclade_29:NA:NA,Forced synteny <> grupo3_subclade_30:NA:NA,Forced synteny <> grupo3_subclade_31:NA:NA,Forced synteny <> grupo3_subclade_32:NA:NA,Forced synteny <> ref_01:NA:NA,Forced synteny <> ref_02:NA:NA,Forced synteny <> ref_03:NA:NA,Forced synteny <> ref_04:NA:NA,Forced synteny <> ref_05:NA:NA,Forced synteny <> ref_06:NA:NA,Forced synteny <> ref_07:NA:NA,Forced synteny <> ref_08:NA:NA,Forced synteny <> ref_09:NA:NA,Forced synteny <> ref_10:NA:NA,Forced synteny <> ref_11:NA:NA,Forced synteny <> ref_12:NA:NA,Forced synteny <> ref_13:NA:NA,Forced synteny <> ref_14:NA:NA,Forced synteny <> ref_15:NA:NA,Forced synteny <> ref_16:NA:NA,Forced synteny <> ref_17:NA:NA,Forced synteny <> ref_18:NA:NA,Forced synteny <> ref_19:NA:NA,Forced synteny <> ref_20:NA:NA,Forced synteny <> ref_21:NA:NA,Forced synteny <> ref_22:NA:NA,Forced synteny <> ref_23:NA:NA,Forced synteny <> ref_24:NA:NA,Forced synteny <> ref_25:NA:NA,Forced synteny <> ref_26:NA:NA,Forced synteny <> ref_27:NA:NA,Forced synteny <> ref_28:NA:NA,Forced synteny <> ref_29:NA:NA
items_ordered ................................: 1

* Please remember that it is never a good idea to change these values. But in some
cases it may be absolutely necessary to update something here, and a programmer
may ask you to run this program and do it. But even then, you should be very
skeptical. For instance, if the programmer asks you to change the values for
'num_contigs', or 'kmer_size', it would mean that they likely hate you and want
you to fail. So please be extremely careful changing any of these values.

Any clue?

**Comment by meren** [comment]
Very weird since versions match.

One way to address this is to go to the anvi'o environment where you get the "db was generated with an anvi'o version that is 'newer' than the one you are actively using right now" error, and generate a small pangenome to see what does the anvi-db-info for the resulting pan db says.

**Comment by RicardoGCCR** [comment]
How about the output of the previous db that I run in the past, which still works fine with the anvi-pan-display?
See :

anvi-db-info Clado_2-PAN.db

DB Info (no touch)
===============================================
Database Path ................................: Clado_2-PAN.db
Description ..................................: _No description is provided_
Type .........................................: pan
Version ......................................: 13


DB Info (no touch also)
===============================================
internal_genome_names ........................:
external_genome_names ........................: grupo1_ST41_01,grupo1_ST41_02,grupo1_ST41_03,grupo1_ST41_04,grupo1_ST41_05,grupo1_ST41_06,grupo1_ST41_07,grupo1_ST41_08,grupo1_ST41_09,grupo1_ST41_10,grupo1_ST41_11,grupo1_ST41_12,grupo1_ST41_13,grupo1_ST41_14,grupo1_ST41_15,grupo1_ST41_16,grupo1_ST41_17,grupo1_ST41_18,grupo1_ST41_19,grupo1_ST41_20,grupo1_ST41_21,grupo1_ST41_22,grupo1_ST41_23,grupo1_ST41_24,grupo1_ST41_25,grupo1_ST41_26,grupo1_ST41_27,grupo1_ST41_28,grupo1_ST41_29,grupo2_ST67_01,grupo2_ST67_02,grupo2_ST67_03,grupo2_ST67_04,grupo2_ST67_05,grupo2_ST67_06,grupo2_ST67_07,grupo2_ST67_08,grupo2_ST67_09,grupo2_ST67_10,grupo2_ST67_11,grupo2_ST67_12,grupo2_ST67_13,grupo2_ST67_14,grupo2_ST67_15,grupo2_ST67_16,grupo2_ST67_17,grupo2_ST67_18,grupo2_ST67_19,grupo2_ST67_20,grupo2_ST67_21,grupo2_ST67_22,grupo2_ST67_23,grupo2_ST67_24,grupo2_ST67_25,grupo2_ST67_26,grupo2_ST67_27,grupo2_ST67_28,grupo2_ST67_29,grupo2_ST67_30,grupo3_subclade_01,grupo3_subclade_02,grupo3_subclade_03,grupo3_subclade_04,grupo3_subclade_05,grupo3_subclade_06,grupo3_subclade_07,grupo3_subclade_08,grupo3_subclade_09,grupo3_subclade_10,grupo3_subclade_11,grupo3_subclade_12,grupo3_subclade_13,grupo3_subclade_14,grupo3_subclade_15,grupo3_subclade_16,grupo3_subclade_17,grupo3_subclade_18,grupo3_subclade_19,grupo3_subclade_20,grupo3_subclade_21,grupo3_subclade_22,grupo3_subclade_23,grupo3_subclade_24,grupo3_subclade_25,grupo3_subclade_26,grupo3_subclade_27,grupo3_subclade_28,grupo3_subclade_29,grupo3_subclade_30,grupo3_subclade_31,grupo3_subclade_32,ref_01,ref_02,ref_03,ref_04,ref_05,ref_06,ref_07,ref_08,ref_09,ref_10,ref_11,ref_12,ref_13,ref_14,ref_15,ref_16,ref_17,ref_18,ref_19,ref_20,ref_21,ref_22,ref_23,ref_24,ref_25,ref_26,ref_27,ref_28,ref_29
num_genomes ..................................: 120
min_percent_identity .........................: 0.0
gene_cluster_min_occurrence ..................: 1
mcl_inflation ................................: 10.0
default_view .................................: gene_cluster_presence_absence
use_ncbi_blast ...............................: 0
diamond_sensitive ............................: 1
minbit .......................................: 0.5
exclude_partial_gene_calls ...................: 0
gene_alignments_computed .....................: 1
genomes_storage_hash .........................: hashda61442e
project_name .................................: Clado_2
creation_date ................................: 1599496196.35898
num_gene_clusters ............................: 6748
num_genes_in_gene_clusters ...................: 459669
default_item_order ...........................: presence-absence:euclidean:ward
available_item_orders ........................: frequency:euclidean:ward,presence-absence:euclidean:ward,Forced synteny <> grupo1_ST41_01:NA:NA,Forced synteny <> grupo1_ST41_02:NA:NA,Forced synteny <> grupo1_ST41_03:NA:NA,Forced synteny <> grupo1_ST41_04:NA:NA,Forced synteny <> grupo1_ST41_05:NA:NA,Forced synteny <> grupo1_ST41_06:NA:NA,Forced synteny <> grupo1_ST41_07:NA:NA,Forced synteny <> grupo1_ST41_08:NA:NA,Forced synteny <> grupo1_ST41_09:NA:NA,Forced synteny <> grupo1_ST41_10:NA:NA,Forced synteny <> grupo1_ST41_11:NA:NA,Forced synteny <> grupo1_ST41_12:NA:NA,Forced synteny <> grupo1_ST41_13:NA:NA,Forced synteny <> grupo1_ST41_14:NA:NA,Forced synteny <> grupo1_ST41_15:NA:NA,Forced synteny <> grupo1_ST41_16:NA:NA,Forced synteny <> grupo1_ST41_17:NA:NA,Forced synteny <> grupo1_ST41_18:NA:NA,Forced synteny <> grupo1_ST41_19:NA:NA,Forced synteny <> grupo1_ST41_20:NA:NA,Forced synteny <> grupo1_ST41_21:NA:NA,Forced synteny <> grupo1_ST41_22:NA:NA,Forced synteny <> grupo1_ST41_23:NA:NA,Forced synteny <> grupo1_ST41_24:NA:NA,Forced synteny <> grupo1_ST41_25:NA:NA,Forced synteny <> grupo1_ST41_26:NA:NA,Forced synteny <> grupo1_ST41_27:NA:NA,Forced synteny <> grupo1_ST41_28:NA:NA,Forced synteny <> grupo1_ST41_29:NA:NA,Forced synteny <> grupo2_ST67_01:NA:NA,Forced synteny <> grupo2_ST67_02:NA:NA,Forced synteny <> grupo2_ST67_03:NA:NA,Forced synteny <> grupo2_ST67_04:NA:NA,Forced synteny <> grupo2_ST67_05:NA:NA,Forced synteny <> grupo2_ST67_06:NA:NA,Forced synteny <> grupo2_ST67_07:NA:NA,Forced synteny <> grupo2_ST67_08:NA:NA,Forced synteny <> grupo2_ST67_09:NA:NA,Forced synteny <> grupo2_ST67_10:NA:NA,Forced synteny <> grupo2_ST67_11:NA:NA,Forced synteny <> grupo2_ST67_12:NA:NA,Forced synteny <> grupo2_ST67_13:NA:NA,Forced synteny <> grupo2_ST67_14:NA:NA,Forced synteny <> grupo2_ST67_15:NA:NA,Forced synteny <> grupo2_ST67_16:NA:NA,Forced synteny <> grupo2_ST67_17:NA:NA,Forced synteny <> grupo2_ST67_18:NA:NA,Forced synteny <> grupo2_ST67_19:NA:NA,Forced synteny <> grupo2_ST67_20:NA:NA,Forced synteny <> grupo2_ST67_21:NA:NA,Forced synteny <> grupo2_ST67_22:NA:NA,Forced synteny <> grupo2_ST67_23:NA:NA,Forced synteny <> grupo2_ST67_24:NA:NA,Forced synteny <> grupo2_ST67_25:NA:NA,Forced synteny <> grupo2_ST67_26:NA:NA,Forced synteny <> grupo2_ST67_27:NA:NA,Forced synteny <> grupo2_ST67_28:NA:NA,Forced synteny <> grupo2_ST67_29:NA:NA,Forced synteny <> grupo2_ST67_30:NA:NA,Forced synteny <> grupo3_subclade_01:NA:NA,Forced synteny <> grupo3_subclade_02:NA:NA,Forced synteny <> grupo3_subclade_03:NA:NA,Forced synteny <> grupo3_subclade_04:NA:NA,Forced synteny <> grupo3_subclade_05:NA:NA,Forced synteny <> grupo3_subclade_06:NA:NA,Forced synteny <> grupo3_subclade_07:NA:NA,Forced synteny <> grupo3_subclade_08:NA:NA,Forced synteny <> grupo3_subclade_09:NA:NA,Forced synteny <> grupo3_subclade_10:NA:NA,Forced synteny <> grupo3_subclade_11:NA:NA,Forced synteny <> grupo3_subclade_12:NA:NA,Forced synteny <> grupo3_subclade_13:NA:NA,Forced synteny <> grupo3_subclade_14:NA:NA,Forced synteny <> grupo3_subclade_15:NA:NA,Forced synteny <> grupo3_subclade_16:NA:NA,Forced synteny <> grupo3_subclade_17:NA:NA,Forced synteny <> grupo3_subclade_18:NA:NA,Forced synteny <> grupo3_subclade_19:NA:NA,Forced synteny <> grupo3_subclade_20:NA:NA,Forced synteny <> grupo3_subclade_21:NA:NA,Forced synteny <> grupo3_subclade_22:NA:NA,Forced synteny <> grupo3_subclade_23:NA:NA,Forced synteny <> grupo3_subclade_24:NA:NA,Forced synteny <> grupo3_subclade_25:NA:NA,Forced synteny <> grupo3_subclade_26:NA:NA,Forced synteny <> grupo3_subclade_27:NA:NA,Forced synteny <> grupo3_subclade_28:NA:NA,Forced synteny <> grupo3_subclade_29:NA:NA,Forced synteny <> grupo3_subclade_30:NA:NA,Forced synteny <> grupo3_subclade_31:NA:NA,Forced synteny <> grupo3_subclade_32:NA:NA,Forced synteny <> ref_01:NA:NA,Forced synteny <> ref_02:NA:NA,Forced synteny <> ref_03:NA:NA,Forced synteny <> ref_04:NA:NA,Forced synteny <> ref_05:NA:NA,Forced synteny <> ref_06:NA:NA,Forced synteny <> ref_07:NA:NA,Forced synteny <> ref_08:NA:NA,Forced synteny <> ref_09:NA:NA,Forced synteny <> ref_10:NA:NA,Forced synteny <> ref_11:NA:NA,Forced synteny <> ref_12:NA:NA,Forced synteny <> ref_13:NA:NA,Forced synteny <> ref_14:NA:NA,Forced synteny <> ref_15:NA:NA,Forced synteny <> ref_16:NA:NA,Forced synteny <> ref_17:NA:NA,Forced synteny <> ref_18:NA:NA,Forced synteny <> ref_19:NA:NA,Forced synteny <> ref_20:NA:NA,Forced synteny <> ref_21:NA:NA,Forced synteny <> ref_22:NA:NA,Forced synteny <> ref_23:NA:NA,Forced synteny <> ref_24:NA:NA,Forced synteny <> ref_25:NA:NA,Forced synteny <> ref_26:NA:NA,Forced synteny <> ref_27:NA:NA,Forced synteny <> ref_28:NA:NA,Forced synteny <> ref_29:NA:NAitems_ordered ................................: 1

* Please remember that it is never a good idea to change these values. But in some
cases it may be absolutely necessary to update something here, and a programmer
may ask you to run this program and do it. But even then, you should be very
skeptical. For instance, if the programmer asks you to change the values for
'num_contigs', or 'kmer_size', it would mean that they likely hate you and want
you to fail. So please be extremely careful changing any of these values.

**Comment by meren** [comment]
Ah, I just realized something. You are running this command:

```
anvi-display-pan -p Clado_2_new_run-PAN.db -g Clado_2_new_run-PAN.db
```

To which you give your PAN database twice. The second one should be the genomes storage.

**Comment by meren** [comment]
Anvi'o should give you a different type of error when you make this mistake, rather than saying your genomes storage has the wrong version. I will fix it in the codebase.

**Comment by RicardoGCCR** [comment]
Oh!!! Please forgive me! I can't believe it! (it was an error of copy-paste and due to a very similar names between the db and the pan output).
Thank you for noticing...
It is running fine now, of course...

Ricardo

Regards,
Ricardo

**Comment by meren** [comment]
Thank you for your patience with anvi'o, @RicardoGCCR! :)
