### ISSUE TITLE
Config Error: You must specify a collection id :/

### ISSUE THREAD

**Issue by li0604** [merenlab/anvio#1569]
Dear professors,

I have install anvio followed the Web guidance and checked. It works. However, when I run anvi-summarize, it shows error as follwing:
Config Error: You must specify a collection id :/

The script:
anvi-summarize -o KS/ \
               -p KS/KS_Pan-PAN.db \
	       -g 2KS-GENOMES.db

Would you mind give me some suggestion on this error?
Thanks a lot.

**Comment by meren** [comment]
Hi @li0604,

Please run this first:

```
anvi-script-add-default-collection -p KS/KS_Pan-PAN.db
```

And then this:

```
anvi-summarize -o KS/ -p KS/KS_Pan-PAN.db -g 2KS-GENOMES.db --collection DEFAULT
```
