### ISSUE TITLE
[BUG] Anvi'o v6.2 installation issue

### ISSUE THREAD

**Issue by ISonets** [merenlab/anvio#1574]
# Anvi'o v6.2 install problems
## Short description of the problem

Greetings!
I have anvi'o install issue. I'm currently trying to install anvi'o 6.2 on my Linux server using conda. All were done according to tutorial. But it turns out a major problem for me.
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json) : done
Solving environment : ... and it lasts for 4 hours!
What should I do? Where is the problem?
I have no other data to reproduce bug. Already tried killing process and removing environment and creating a new environment. Also tried wiping Anaconda out and install it clear new version, but nothing works for me. Pls respond ASAP.

## anvi'o version
I trying to install anvio v.6.2

## System info
System is Linux 18.04 LTS

**Comment by meren** [comment]
Four hours is not unheard of with conda :/ We know people who waited much longer than that. Sorry you are dealing with that. But it will eventually resolve.


Best,
