### ISSUE TITLE
Search for a codename for anvi'o v7

### ISSUE THREAD

**Issue by meren** [merenlab/anvio#1575]
As we are preparing for `v7`, it is time to set a codename. As you know, the last three major anvi'o releases had codenames commemorating scientists of the past, whose contributions have been overlooked by their peers.

Please send your ideas, vote for ones that are already sent, and help us finalize one of the most challenging parts of making an anvi'o release :) Here is a reminder of the codenames of past releases:

![image](https://user-images.githubusercontent.com/197307/100896932-c592ed00-3484-11eb-8cab-0f1bb2becbb6.png)

Thank you very much for your help!

**Comment by rbartelme** [comment]
Ada or Lovelace, after Ada Lovelace

**Comment by aassie** [comment]
Lynn Margulis, godmother of Symbiosis =)

**Comment by meren** [comment]
@ShaiberAlon writes on Slack:

> I bumped into this article:
> 
> https://circulatingnow.nlm.nih.gov/2018/09/06/finding-hope-a-womans-place-is-in-the-lab/
> 
> And learned about **Hope Hopps**. And I hereby nominate her name.
> 
> I thought it would be symbolic since we all are holding much hope for the new COVID19 vaccines (see what I did there?), and it would be appropriate to honor someone that probably got less credit than she deserved for an old vaccine.

**Comment by susheelbhanu** [comment]
Maybe this is not a great suggestion given the current circumstances but, `June Almeida`, for first identifying coronaviruses.

**Comment by meren** [comment]
Emil Ruff on Twitter:

> **Ada Lovelace** (1815-1852). She is considered the first computer programmer, and a greatly underestimated scientist and visionary. https://en.wikipedia.org/wiki/Ada_Lovelace

**Comment by cibberson** [comment]
Barbara McClintock for her discovery of “jumping genes” (transposons)

**Comment by sam217pa** [comment]
Hi, maybe **Erwin Chargaff** could be a great choice? He was scooped out of the Nobel prize for the DNA 3D structure but widely acknowledged as being the one that came out with base-pairing rules.

**Comment by mschecht** [comment]
I nominate Ruth Ella Moore, a professor of bacteriology who was the first African-American woman to receive a PhD in a natural science. 

https://en.wikipedia.org/wiki/Ruth_Ella_Moore

**Comment by shreyaramachandran** [comment]
I remember the awe I felt leanring that Maud Menten of Michaelis-Menten kinetics was a woman, and wish more people knew!

**Comment by sam217pa** [comment]
There is also **Fanny Hesse**, which first used the agar-agar for cultivating bacteria, but wasn't acknowledged by Koch for doing so.
"Hesse worked in an unpaid capacity to assist her husband through preparing bacterial growth media, cleaning equipment and producing illustrations for publications." https://en.wikipedia.org/wiki/Fanny_Hesse

**Comment by luuuuuuuke** [comment]
Matilda Gage: "Gage was the daughter of an exceptionally forward-thinking father, an abolitionist and doctor who raised his daughter to practice medicine. No medical school in her area would accept a woman, so instead, while the mother of five children, she channeled her intellect into abolitionist activism (her home was a stop on the Underground Railroad), as well as the burgeoning suffragist movement. She spoke at the third National Woman’s Rights Convention in Syracuse, in 1852, and was a founding member of (and frequent officeholder in) the National Woman Suffrage Association."

From this incredible article in Smithsonian: https://www.smithsonianmag.com/science-nature/unheralded-women-scientists-finally-getting-their-due-180973082/?page=1

**Comment by MADscientist314** [comment]
#### I nominate English chemist and X-ray crystallographer `Rosalind Franklin` 
![image of Rosalind Franklin](https://upload.wikimedia.org/wikipedia/en/e/e9/Rosalind_Franklin_%281920-1958%29.jpg)
https://en.wikipedia.org/wiki/Rosalind_Franklin

**Comment by meren** [comment]
Zena Cardman on Twitter:

> **Marie Tharp**, for the data collection and analysis behind this mind-blowing map of the sea floor: a breakthrough ushering our modern understanding of plate tectonics.

![image](https://user-images.githubusercontent.com/197307/100921831-b327ac00-34a2-11eb-8611-a261bd32c1e8.png)

**Comment by JennJess** [comment]
Henrietta for Henrietta Lacks, someone whose cells most scientists have handled or learnt of. Though not a scientist her contribution can't be overlooked.

**Comment by ellasiera** [comment]
Katherine Johnson, NASA mathematician, passed away last February and could always use more commemoration.
https://en.wikipedia.org/wiki/Katherine_Johnson

**Comment by ankit4035** [comment]
I would like to suggest name of "Fanny Hesse". She was the one who suggested use of agar instead of gelatin as a medium for bacterial culturing and still not credited for her work.

**Comment by cdiener** [comment]
Emmy, for (Amalie) Emmy Noether
https://en.m.wikipedia.org/wiki/Emmy_Noether

**Comment by Lopesas** [comment]
Briliant and elegant way to support WiS. Thanks for being an ally! Here my suggestion...Eunice Newton Foote, thanks to her experiments we today talk about the effects of greenhouse gases: https://en.m.wikipedia.org/wiki/Eunice_Newton_Foote or

**Comment by tpriest0** [comment]
Marjory Stephenson - a pioneer in advancing our understanding on bacterial metabolisms and also the first person to extract a bacterial enzyme from a cell.

OR..alternative solution which is applicable for the current situation we are faced by:

June Almeida - the first person to visualise and identify the family of coronaviruses. She also improved and developed various microscopy techniques for visualising viral structures.

p.s looking forward to v7 being released

**Comment by meren** [comment]
@MGKmicro on Twitter:

> **Angelina Fanny Hesse** - (wife of Hans Petri , who had more cloud with Robert Koch and got his name attached to Fanny’s invention, without which there would not be microbiology as we know it)

**Comment by meren** [comment]
@MichaelTangher1 on Twitter:

> I can add **Laura Bassi** (the first woman to have doctorate in science) or **Henrietta Lacks** (ok, not a scientist but I guess her contribution to science is quite huge).

**Comment by meren** [comment]
Thank you all very much for your suggestions. Given its release cycle, I think it is safe to assume that the treasure of codenames suggested under this issue will certainly outlive anvi'o :) I _hope_ the choice for `v7` will please most of you.

I am looking forward to use more of the suggestions going forward.

I wish you all a happy 2021, and thank you again.
