### ISSUE TITLE
[FEATURE] Post processing after assigning bins/MAGs

### ISSUE THREAD

**Issue by razz1618** [merenlab/anvio#1581]
Hi,

I am not sure whether these features are already incorporated into ANVIO but I could not find it on ANVIO web (maybe I missed it).

So,  I have a contig.db - contigs with size 1000bp, annotated, and already clustered and refined into bins. How can I view features (functional /taxonomic annotations) of only the bins and not all contigs (If possible can subtract the contigs not clustered into the bin)?  Currently, the search option allows searching for a particular function in all visualized contigs.

**Comment by meren** [comment]
Hi @razz1618,

There are multiple ways to do that. You can use `anvi-summarize` to get summary outputs for a given collection, or you can use `anvi-split` to get individual profile and contigs databases for each bin in a collection.

**Comment by razz1618** [comment]
I have already used anvi-summerize which gave me HTML output. will anvi-split for each bin (contig and profile db) will give me functional annotation in anvio-interactive? I tried anvio with all bins in collection mode and later found that the functional annotation search option is not working in collection mode.  My initial question may not be clear. What I mean is to do this in anvio-interactive plot,  labeling/showing functional and taxonomical annotation of the bins and not whole assembled contig. I am not sure whether it can be done or is not yet implemented?

**Comment by meren** [comment]
I see. There is no option in anvi'o to show functional annotations in the interface per bin or per contig. But you could add additional layers into any anvi'o display to show presence or absence of certain functions or pathways you're interested in per bin in collection mode.

If you were to send a sketch of what you have in mind in terms of visualization of your bins, perhaps I could make better suggestions :)

**Comment by razz1618** [comment]
I see. Great, I will try adding layer and see if I can get the desired outcome. Anyways, it is not a big deal, the same can be done manually. For reference, I have attached a picture of my clustered bins. Though I could not modify it properly, but you can get an idea about the visualization and probably if possible can provide some suggestions (If cannot also, I can understand as it is outside the scope of technical issues related to ANVIO).

![Picture1](https://user-images.githubusercontent.com/59241611/101637577-e8666800-3a67-11eb-9c14-bc2ed70a0b9b.jpg)

I have labeled the bin with random taxonomy for reference. If something like that can be done in collection mode (showing just the bins/MAGs). Or instead of the domain layer if can add a taxonomy layer?

Similarly, if i can search a particular gene of interest and if present can highlight/mark the bin with a color showing the presence of the gene of interest in representative bins/MAGs.

**Comment by meren** [comment]
If this is anvi'o `main` branch, you could use [anvi-estimate-scg-taxonomy](https://merenlab.org/software/anvio/help/main/programs/anvi-estimate-scg-taxonomy/) to get a taxonomy matrix for your bins, and then add it to your `anvi-interactive` call in collection mode using the parameter `--additional-layers`. Then, you would see additional layers from phylum to species for each genome bin (which can be turned into text or colors to display).

If this is anvi'o `v6.2`, you can do the same by creating an EXCEL spreadsheet for genome taxonomy, and add it to the display using the parameter `--additional-layers`.

I think it is a good idea to do add taxonomy layers automatically in collection mode. I will add an issue so we remember it.

Thank you!

**Comment by razz1618** [comment]
Thanks. i will try that.

**Comment by razz1618** [comment]
Hi,
I included taxonomy via additional layers and now I am looking at the functional annotation of the bins. I used COGG, Eggnogg, and KEGG for functional annotation. 

When I look at the gene-call.txt of a **single bin**, there is one column named EGGNOG_BEST_TAX which is pointing to different taxa for each gene-call and these taxa are not related to the representing bin. Is it a matter of concern or its just an assumed taxa by eggnog as I have used all the 'called genes' from the assembled contig in eggnog annotation?

Eg. this is a bin related to synechococcus,
gene_callers_id | contig | start | stop | direction | KeggGhostKoala | KeggGhostKoala (ACCESSION) | **EGGNOG_BEST_TAX** EGGNOG_BEST_TAX (ACCESSION)

16334 | G01_000000003977 | 350 | 1550 | f | dxr;   1-deoxy-D-xylulose-5-phosphate reductoisomerase [EC:1.1.1.267] | K00099 | **Planctomycetes** | 1142394.PSMK_24580

16361 | G01_000000003977 | 33665 | 34433 | f | gloB,   gloC, HAGH; hydroxyacylglutathione hydrolase [EC:3.1.2.6] | K01069 | **Paenibacillaceae** | 1121346.KB899826_gene394

**Comment by meren** [comment]
Hey @razz1618,

EGGNOG_BEST_TAX tells you which sequences from which taxa were used to make that functional prediction for your genes. It does not necessarily reflect the actual taxonomy of a given genome.

**Comment by razz1618** [comment]
I see. thanks. that makes sense.
