### ISSUE TITLE
[BUG] Cannot set --cluster-contigs to false for anvi-profile in metagenomics workflow

### ISSUE THREAD

**Issue by ivagljiva** [merenlab/anvio#1588]
## Short description of the problem

I am trying to produce single profiles without clustering. I have set the `--cluster-contigs` flag to `false` in my config file for the metagenomics workflow, but this flag is still being added to the `anvi-profile` rule. 

## anvi'o version

```
Anvi'o version ...............................: esther (v6.2-master)
Profile DB version ...........................: 35
Contigs DB version ...........................: 20
Pan DB version ...............................: 14
Genome data storage version ..................: 7
Auxiliary data storage version ...............: 2
Structure DB version .........................: 2
Kegg Modules DB version ......................: 2
tRNA-seq DB version ..........................: 1
```

## System info

Midway

## Detailed description of the issue

See screenshots below:
![image](https://user-images.githubusercontent.com/10360586/101698506-2f8c3300-3a3f-11eb-9e36-58668e35d074.png)
![image](https://user-images.githubusercontent.com/10360586/101698557-4cc10180-3a3f-11eb-8889-5d613f44ef17.png)

I believe the issue is in the `get_cluster_contigs_param` function in the `anvio/anvio/workflows/metagenomics/Snakefile` file. The conditional statement will be false if you set `--cluster-contigs` to `false`, so the else clause always runs, and that clause uses the `--cluster-contigs` flag if you are working with single profiles (I am).

**Comment by ekiefl** [comment]
So here's the function:

```python
def get_cluster_contigs_param(wildcards):
    """ helper function to sort out whether to cluster contigs for a single profile database"""
    if M.get_param_value_from_config(['anvi_profile', '--cluster-contigs']):
        run.warning('You chose to set the value for --cluster-contigs as %s. You can do that if you '
                    'choose to, but just so you know, if you don\'t provide a value then '
                    'the workflow would automatically cluster contigs for profile databases '
                    'that are not merged (i.e. profiles that belong to groups of size 1).' \
                    % M.get_param_value_from_config(['anvi_profile', '--cluster-contigs']))
        cluster_contigs = M.get_rule_param('anvi_profile', '--cluster-contigs')
    else:
        # if profiling to individual assembly then clustering contigs
        # see --cluster-contigs in the help manu of anvi-profile
        cluster_contigs = '--cluster-contigs' if M.group_sizes[wildcards.group] == 1 else ''
    return cluster_contigs
```

This seems like a design flaw. First of all, the warning is with regard to the `else` clause, so should be _in_ the `else` clause, not the `if` clause. Second, is this really a behavior we want? Forcing `--cluster-contigs` for single profiles seems the opposite of the advice provided in `anvi-profile`: 

```
  --cluster-contigs     Single profiles are rarely used for genome binning or
                        visualization, and since clustering step increases the
                        profiling runtime for no good reason, the default
                        behavior is to not cluster contigs for individual
                        runs. However, if you are planning to do binning on
                        one sample, you must use this flag to tell anvi'o to
                        run cluster configurations for single runs on your
                        sample. (default: False)
```

This is not my area of expertise so maybe I am missing something.

**Comment by meren** [comment]
So what are we doing about this? :)

**Comment by ivagljiva** [comment]
I think we should fix it so that the users can actually set a 'false' value for `--cluster-contigs` if they want to, but if no value is set the defaults should be 'true' for merged profiles and 'false' for single profiles. If you think that makes sense, I will take a stab at it tomorrow...er, today. much later today. :)
