### ISSUE TITLE
Config error using anvi-gen-contigs-database with external-gene-calls

### ISSUE THREAD

**Issue by aline385** [merenlab/anvio#1591]
## Short description of the problem

A config error is raise when I try to run anvi-gen-contigs-database with external-gene-calls : "There are more fields in the file 'gene_calls.txt' than the expected fields"

## anvi'o version

Anvi'o version ...............................: esther (v6.2)
Profile DB version ...........................: 31
Contigs DB version ...........................: 14
Pan DB version ...............................: 13
Genome data storage version ..................: 6
Auxiliary data storage version ...............: 2
Structure DB version .........................: 1

## System info

Ubuntu 16.04, anvio installe via anaconda3

## Detailed description of the issue

I ran the anvi-gen-contigs-database without problems without the --external-gene-calls function. Here is what I get  when trying to run it with a gene_call file produced with gff_parser.py : 

$ anvi-gen-contigs-database -f d427_assembly_option17_ten_times_polished_bigger_2000.fasta -o contigs_d427_annotated.db -n 'd427_contigs_pacbio' --external-gene-calls gene_calls.txt
Input FASTA file .............................: d427_assembly_option17_ten_times_polished_bigger_2000.fasta
Name .........................................: d427_contigs_pacbio
Description ..................................: No description is given
                                                                                                          [10 Dec 20 21:30:14 Checking deflines and contig lengths] tick tock ...                                                                                                                                             Split Length .................................: 20,000
K-mer size ...................................: 4
Skip gene calling? ...........................: False
External gene calls provided? ................: gene_calls.txt
Ignoring internal stop codons? ...............: False
Splitting pays attention to gene calls? ......: True

Config Error: There are more fields in the file 'gene_calls.txt' than the expected fields :/
              Anvi'o is telling you about this because get_TAB_delimited_file_as_dictionary 
              function is called with `only_expected_fields` flag turned on. 

I don't understand how to fix this because the file seem to have the requested format.

## Files to reproduce

https://www.dropbox.com/s/8590bwpfec9be80/config_error.tar.gz?dl=0

**Comment by aline385** [comment]
The files are not uploading on dropbox, so here they are :
[config_error.tar.gz](https://github.com/merenlab/anvio/files/5675564/config_error.tar.gz)

box, so here they are :

**Comment by ivagljiva** [comment]
Hi @aline385,

I think this is happening because your gene calls file has a `call_type` column. The fields that anvio-6.2 expects are `['gene_callers_id', 'contig', 'start' , 'stop'  , 'direction', 'partial', 'source', 'version']`, and `call_type` is not one of those. 

`call_type` was added later to the expected fields list, so perhaps you generated that external gene calls file using the development version of anvi'o? (If not, then this would be a bug in version 6.2)

**Comment by meren** [comment]
This is because our documentation follows the `main` repository when most people are still using `v6.2`. For instance this external gene calls artifact: https://merenlab.org/software/anvio/help/main/artifacts/external-gene-calls/

This will no longer be a problem with anvi'o `v7`, but meanwhile apologies for the inconvenience, @aline385 :( You simply need to remove the `call_type` column for now.

**Comment by ivagljiva** [comment]
Also, I just realized that `gff_parser.py` is not tracked in the anvi'o repository. It is [here](https://github.com/karkman/gff_parser) instead :) So the current version of that program is probably not the one that is compatible with anvio-v6.2 (@meren, please correct me if I am wrong)

**Comment by meren** [comment]
Funny enough, this problem was brought up very recently here as well: https://github.com/karkman/gff_parser/issues/7

In an ideal world, gff_parser can produce a suitable external gene calls file for `--anvio-v6-or-earlier` :)

**Comment by aline385** [comment]
Thank you very much ! It works now that I removed the call_type column :)
