### ISSUE TITLE
[BUG] iu-filter-quality-minoche is crashing

### ISSUE THREAD

**Issue by maziz2** [merenlab/anvio#1602]
Hi

I am running this tutorial on my metagenomics data
https://merenlab.org/tutorials/assembly-based-metagenomics/

I am at the step where I run iu-filter-quality-minoche for quality filtering

Here is the command I run
for ini in 01_QC/*.ini; do sbatch  -J SSI_metagen -t 14-00:00:00 -p defq --wrap="iu-filter-quality-minoche $ini"; done

Here is the error I get ( i get it for all 42 samples but im pasting just one)

(anvio-6.2) [mlaziz@log001 SSI_Metagenomics_CST]$ cat slurm-875104.out 
Traceback (most recent call last):
  File "/groups/liu_price_lab/shared/envs/anvio-6.2/bin/iu-filter-quality-minoche", line 314, in <module>
    sys.exit(main(config, args))
  File "/groups/liu_price_lab/shared/envs/anvio-6.2/bin/iu-filter-quality-minoche", line 163, in main
    while pair_1.next(raw = ignore_deflines) and pair_2.next(raw = ignore_deflines):
  File "/groups/liu_price_lab/shared/envs/anvio-6.2/lib/python3.6/site-packages/IlluminaUtils/lib/fastqlib.py", line 252, in next
    self.entry = FastQEntry([self.file_pointer.readline().strip() for _ in range(0, 4)], trim_from, trim_to, raw, CASAVA_version = self.CASAVA_version, pos = self.pos)
  File "/groups/liu_price_lab/shared/envs/anvio-6.2/lib/python3.6/site-packages/IlluminaUtils/lib/fastqlib.py", line 117, in __init__
    self.pair_no    = header_fields[6].split()[1]
IndexError: list index out of range

here is the 01_QC folder
(anvio-6.2) [mlaziz@log001 SSI_Metagenomics_CST]$ ls -lrt 01_QC/
total 172
-rw-rw---- 1 mlaziz liu_price_lab  404 Dec 18 00:19 14046334_GWU_DNA_1.ini
-rw-rw---- 1 mlaziz liu_price_lab  404 Dec 18 00:19 14027334_GWU_DNA_1.ini
-rw-rw---- 1 mlaziz liu_price_lab  404 Dec 18 00:19 14027321_GWU_DNA_1.ini
-rw-rw---- 1 mlaziz liu_price_lab  404 Dec 18 00:19 14027325_GWU_DNA_1.ini
-rw-rw---- 1 mlaziz liu_price_lab  404 Dec 18 00:19 14047047_GWU_DNA_1.ini
-rw-rw---- 1 mlaziz liu_price_lab  404 Dec 18 00:19 14046035_GWU_DNA_1.ini
-rw-rw---- 1 mlaziz liu_price_lab  404 Dec 18 00:19 14042952_GWU_DNA_1.ini
-rw-rw---- 1 mlaziz liu_price_lab  404 Dec 18 00:19 14042951_GWU_DNA_1.ini
-rw-rw---- 1 mlaziz liu_price_lab  404 Dec 18 00:19 14027328_GWU_DNA_1.ini
-rw-rw---- 1 mlaziz liu_price_lab  406 Dec 18 00:19 14043682_GWU_DNA_1.ini
-rw-rw---- 1 mlaziz liu_price_lab  406 Dec 18 00:19 14047048_GWU_DNA_1.ini
-rw-rw---- 1 mlaziz liu_price_lab  406 Dec 18 00:19 14047045_GWU_DNA_1.ini
-rw-rw---- 1 mlaziz liu_price_lab  406 Dec 18 00:19 14046337_GWU_DNA_1.ini
-rw-rw---- 1 mlaziz liu_price_lab  406 Dec 18 00:19 14046039_GWU_DNA_1.ini
-rw-rw---- 1 mlaziz liu_price_lab  406 Dec 18 00:19 14046037_GWU_DNA_1.ini
-rw-rw---- 1 mlaziz liu_price_lab  406 Dec 18 00:19 14046034_GWU_DNA_1.ini
-rw-rw---- 1 mlaziz liu_price_lab  406 Dec 18 00:19 14046033_GWU_DNA_1.ini
-rw-rw---- 1 mlaziz liu_price_lab  406 Dec 18 00:19 14043884_GWU_DNA_1.ini
-rw-rw---- 1 mlaziz liu_price_lab  406 Dec 18 00:19 14043683_GWU_DNA_1.ini
-rw-rw---- 1 mlaziz liu_price_lab  406 Dec 18 00:19 14043681_GWU_DNA_1.ini
-rw-rw---- 1 mlaziz liu_price_lab  406 Dec 18 00:19 14043679_GWU_DNA_1.ini
-rw-rw---- 1 mlaziz liu_price_lab  406 Dec 18 00:19 14042950_GWU_DNA_1.ini
-rw-rw---- 1 mlaziz liu_price_lab  406 Dec 18 00:19 14027759_GWU_DNA_1.ini
-rw-rw---- 1 mlaziz liu_price_lab  406 Dec 18 00:19 14027337_GWU_DNA_1.ini
-rw-rw---- 1 mlaziz liu_price_lab  406 Dec 18 00:19 14027336_GWU_DNA_1.ini
-rw-rw---- 1 mlaziz liu_price_lab  406 Dec 18 00:19 14027333_GWU_DNA_1.ini
-rw-rw---- 1 mlaziz liu_price_lab  406 Dec 18 00:19 14027332_GWU_DNA_1.ini
-rw-rw---- 1 mlaziz liu_price_lab  406 Dec 18 00:19 14027319_GWU_DNA_1.ini
-rw-rw---- 1 mlaziz liu_price_lab  406 Dec 18 00:19 14027317_GWU_DNA_1.ini
-rw-rw---- 1 mlaziz liu_price_lab  406 Dec 18 00:19 14027316_GWU_DNA_1.ini
-rw-rw---- 1 mlaziz liu_price_lab  406 Dec 18 00:19 14027315_GWU_DNA_1.ini
-rw-rw---- 1 mlaziz liu_price_lab  406 Dec 18 00:19 14027314_GWU_DNA_1.ini
-rw-rw---- 1 mlaziz liu_price_lab  404 Dec 18 00:19 14024546_GWU_DNA_1.ini
-rw-rw---- 1 mlaziz liu_price_lab  404 Dec 18 00:19 14023631_GWU_DNA_1.ini
-rw-rw---- 1 mlaziz liu_price_lab  404 Dec 18 00:19 14022454_GWU_DNA_1.ini
-rw-rw---- 1 mlaziz liu_price_lab  404 Dec 18 00:19 14021158_GWU_DNA_1.ini
-rw-rw---- 1 mlaziz liu_price_lab  404 Dec 18 00:19 14019362_GWU_DNA_1.ini
-rw-rw---- 1 mlaziz liu_price_lab  404 Dec 18 00:19 14019067_GWU_DNA_1.ini
-rw-rw---- 1 mlaziz liu_price_lab  406 Dec 18 00:19 14017556_GWU_DNA_1.ini
-rw-rw---- 1 mlaziz liu_price_lab  404 Dec 18 00:19 14017360_GWU_DNA_1.ini
-rw-rw---- 1 mlaziz liu_price_lab  404 Dec 18 00:19 14012634_GWU_DNA_1.ini
-rw-rw---- 1 mlaziz liu_price_lab  404 Dec 18 00:19 14006542_GWU_DNA_1.ini

and here is my read folder
(anvio-6.2) [mlaziz@log001 SSI_Metagenomics_CST]$ ls -lhrt Kneaddata_clean_reads/140*
-rw-r----- 1 mlaziz liu_price_lab 124M Oct 26 15:09 Kneaddata_clean_reads/14006542_GWU_DNA_1_S5_R1_001_kneaddata_paired_2.fastq
-rw-r----- 1 mlaziz liu_price_lab 958M Oct 26 15:09 Kneaddata_clean_reads/14043681_GWU_DNA_1_S28_R1_001_kneaddata_paired_2.fastq
-rw-r----- 1 mlaziz liu_price_lab 1.1G Oct 26 15:09 Kneaddata_clean_reads/14027314_GWU_DNA_1_S13_R1_001_kneaddata_paired_2.fastq
-rw-r----- 1 mlaziz liu_price_lab 344M Oct 26 15:09 Kneaddata_clean_reads/14047045_GWU_DNA_1_S29_R1_001_kneaddata_paired_1.fastq
-rw-r----- 1 mlaziz liu_price_lab 240M Oct 26 15:10 Kneaddata_clean_reads/14021158_GWU_DNA_1_S8_R1_001_kneaddata_paired_1.fastq
-rw-r----- 1 mlaziz liu_price_lab 377M Oct 26 15:10 Kneaddata_clean_reads/14027328_GWU_DNA_1_S7_R1_001_kneaddata_paired_2.fastq
-rw-r----- 1 mlaziz liu_price_lab 1.1G Oct 26 15:10 Kneaddata_clean_reads/14027321_GWU_DNA_1_S2_R1_001_kneaddata_paired_1.fastq
-rw-r----- 1 mlaziz liu_price_lab 826M Oct 26 15:10 Kneaddata_clean_reads/14046337_GWU_DNA_1_S19_R1_001_kneaddata_paired_2.fastq
-rw-r----- 1 mlaziz liu_price_lab 451M Oct 26 15:10 Kneaddata_clean_reads/14042952_GWU_DNA_1_S9_R1_001_kneaddata_paired_1.fastq
-rw-r----- 1 mlaziz liu_price_lab 1.5G Oct 26 15:11 Kneaddata_clean_reads/14027315_GWU_DNA_1_S14_R1_001_kneaddata_paired_2.fastq
-rw-r----- 1 mlaziz liu_price_lab 379M Oct 26 15:11 Kneaddata_clean_reads/14027328_GWU_DNA_1_S7_R1_001_kneaddata_paired_1.fastq
-rw-r----- 1 mlaziz liu_price_lab 1.6G Oct 26 15:11 Kneaddata_clean_reads/14047047_GWU_DNA_1_S6_R1_001_kneaddata_paired_1.fastq
-rw-r----- 1 mlaziz liu_price_lab 216M Oct 26 15:11 Kneaddata_clean_reads/14012634_GWU_DNA_1_S9_R1_001_kneaddata_paired_2.fastq
-rw-r----- 1 mlaziz liu_price_lab 184M Oct 26 15:11 Kneaddata_clean_reads/14046037_GWU_DNA_1_S23_R1_001_kneaddata_paired_2.fastq
-rw-r----- 1 mlaziz liu_price_lab 186M Oct 26 15:11 Kneaddata_clean_reads/14046037_GWU_DNA_1_S23_R1_001_kneaddata_paired_1.fastq
-rw-r----- 1 mlaziz liu_price_lab 435M Oct 26 15:12 Kneaddata_clean_reads/14047048_GWU_DNA_1_S27_R1_001_kneaddata_paired_1.fastq
-rw-r----- 1 mlaziz liu_price_lab 864M Oct 26 15:12 Kneaddata_clean_reads/14042951_GWU_DNA_1_S5_R1_001_kneaddata_paired_2.fastq
-rw-r----- 1 mlaziz liu_price_lab 841M Oct 26 15:12 Kneaddata_clean_reads/14027317_GWU_DNA_1_S17_R1_001_kneaddata_paired_1.fastq
-rw-r----- 1 mlaziz liu_price_lab 125M Oct 26 15:12 Kneaddata_clean_reads/14006542_GWU_DNA_1_S5_R1_001_kneaddata_paired_1.fastq
-rw-r----- 1 mlaziz liu_price_lab 396M Oct 26 15:12 Kneaddata_clean_reads/14046033_GWU_DNA_1_S11_R1_001_kneaddata_paired_1.fastq
-rw-r----- 1 mlaziz liu_price_lab 759M Oct 26 15:13 Kneaddata_clean_reads/14027316_GWU_DNA_1_S30_R1_001_kneaddata_paired_2.fastq
-rw-r----- 1 mlaziz liu_price_lab 872M Oct 26 15:13 Kneaddata_clean_reads/14027325_GWU_DNA_1_S4_R1_001_kneaddata_paired_2.fastq
-rw-r----- 1 mlaziz liu_price_lab 450M Oct 26 15:13 Kneaddata_clean_reads/14042952_GWU_DNA_1_S9_R1_001_kneaddata_paired_2.fastq
-rw-r----- 1 mlaziz liu_price_lab 1.8G Oct 26 15:13 Kneaddata_clean_reads/14027336_GWU_DNA_1_S15_R1_001_kneaddata_paired_2.fastq
-rw-r----- 1 mlaziz liu_price_lab 104M Oct 26 15:13 Kneaddata_clean_reads/14027759_GWU_DNA_1_S20_R1_001_kneaddata_paired_1.fastq
-rw-r----- 1 mlaziz liu_price_lab 276M Oct 26 15:14 Kneaddata_clean_reads/14043884_GWU_DNA_1_S24_R1_001_kneaddata_paired_2.fastq
-rw-r----- 1 mlaziz liu_price_lab 172M Oct 26 15:14 Kneaddata_clean_reads/14017360_GWU_DNA_1_S3_R1_001_kneaddata_paired_2.fastq
-rw-r----- 1 mlaziz liu_price_lab 299M Oct 26 15:14 Kneaddata_clean_reads/14017556_GWU_DNA_1_S10_R1_001_kneaddata_paired_2.fastq
-rw-r----- 1 mlaziz liu_price_lab 961M Oct 26 15:14 Kneaddata_clean_reads/14043681_GWU_DNA_1_S28_R1_001_kneaddata_paired_1.fastq
-rw-r----- 1 mlaziz liu_price_lab 375M Oct 26 15:14 Kneaddata_clean_reads/14027332_GWU_DNA_1_S16_R1_001_kneaddata_paired_1.fastq
-rw-r----- 1 mlaziz liu_price_lab 922M Oct 26 15:14 Kneaddata_clean_reads/14042950_GWU_DNA_1_S18_R1_001_kneaddata_paired_1.fastq
-rw-r----- 1 mlaziz liu_price_lab 431M Oct 26 15:14 Kneaddata_clean_reads/14047048_GWU_DNA_1_S27_R1_001_kneaddata_paired_2.fastq
-rw-r----- 1 mlaziz liu_price_lab 442M Oct 26 15:15 Kneaddata_clean_reads/14027337_GWU_DNA_1_S12_R1_001_kneaddata_paired_1.fastq
-rw-r----- 1 mlaziz liu_price_lab 103M Oct 26 15:15 Kneaddata_clean_reads/14027759_GWU_DNA_1_S20_R1_001_kneaddata_paired_2.fastq
-rw-r----- 1 mlaziz liu_price_lab 222M Oct 26 15:15 Kneaddata_clean_reads/14024546_GWU_DNA_1_S6_R1_001_kneaddata_paired_1.fastq
-rw-r----- 1 mlaziz liu_price_lab 1.6G Oct 26 15:15 Kneaddata_clean_reads/14047047_GWU_DNA_1_S6_R1_001_kneaddata_paired_2.fastq
-rw-r----- 1 mlaziz liu_price_lab 368M Oct 26 15:15 Kneaddata_clean_reads/14046039_GWU_DNA_1_S21_R1_001_kneaddata_paired_1.fastq
-rw-r----- 1 mlaziz liu_price_lab 349M Oct 26 15:15 Kneaddata_clean_reads/14043679_GWU_DNA_1_S25_R1_001_kneaddata_paired_1.fastq
-rw-r----- 1 mlaziz liu_price_lab 477M Oct 26 15:16 Kneaddata_clean_reads/14046035_GWU_DNA_1_S8_R1_001_kneaddata_paired_1.fastq
-rw-r----- 1 mlaziz liu_price_lab 860M Oct 26 15:16 Kneaddata_clean_reads/14027319_GWU_DNA_1_S31_R1_001_kneaddata_paired_1.fastq
-rw-r----- 1 mlaziz liu_price_lab 366M Oct 26 15:16 Kneaddata_clean_reads/14027332_GWU_DNA_1_S16_R1_001_kneaddata_paired_2.fastq
-rw-r----- 1 mlaziz liu_price_lab 439M Oct 26 15:16 Kneaddata_clean_reads/14027337_GWU_DNA_1_S12_R1_001_kneaddata_paired_2.fastq
-rw-r----- 1 mlaziz liu_price_lab 258M Oct 26 15:16 Kneaddata_clean_reads/14019362_GWU_DNA_1_S7_R1_001_kneaddata_paired_2.fastq
-rw-r----- 1 mlaziz liu_price_lab 1.1G Oct 26 15:16 Kneaddata_clean_reads/14027314_GWU_DNA_1_S13_R1_001_kneaddata_paired_1.fastq
-rw-r----- 1 mlaziz liu_price_lab 601M Oct 26 15:16 Kneaddata_clean_reads/14046034_GWU_DNA_1_S22_R1_001_kneaddata_paired_1.fastq
-rw-r----- 1 mlaziz liu_price_lab 218M Oct 26 15:17 Kneaddata_clean_reads/14012634_GWU_DNA_1_S9_R1_001_kneaddata_paired_1.fastq
-rw-r----- 1 mlaziz liu_price_lab 307M Oct 26 15:17 Kneaddata_clean_reads/14023631_GWU_DNA_1_S1_R1_001_kneaddata_paired_1.fastq
-rw-r----- 1 mlaziz liu_price_lab 434M Oct 26 15:17 Kneaddata_clean_reads/14043682_GWU_DNA_1_S10_R1_001_kneaddata_paired_2.fastq
-rw-r----- 1 mlaziz liu_price_lab 125M Oct 26 15:17 Kneaddata_clean_reads/14019067_GWU_DNA_1_S2_R1_001_kneaddata_paired_1.fastq
-rw-r----- 1 mlaziz liu_price_lab 213M Oct 26 15:17 Kneaddata_clean_reads/14022454_GWU_DNA_1_S4_R1_001_kneaddata_paired_2.fastq
-rw-r----- 1 mlaziz liu_price_lab 1.8G Oct 26 15:17 Kneaddata_clean_reads/14027336_GWU_DNA_1_S15_R1_001_kneaddata_paired_1.fastq
-rw-r----- 1 mlaziz liu_price_lab 174M Oct 26 15:17 Kneaddata_clean_reads/14017360_GWU_DNA_1_S3_R1_001_kneaddata_paired_1.fastq
-rw-r----- 1 mlaziz liu_price_lab 926M Oct 26 15:18 Kneaddata_clean_reads/14027333_GWU_DNA_1_S32_R1_001_kneaddata_paired_1.fastq
-rw-r----- 1 mlaziz liu_price_lab 629M Oct 26 15:18 Kneaddata_clean_reads/14046334_GWU_DNA_1_S1_R1_001_kneaddata_paired_1.fastq
-rw-r----- 1 mlaziz liu_price_lab 218M Oct 26 15:18 Kneaddata_clean_reads/14022454_GWU_DNA_1_S4_R1_001_kneaddata_paired_1.fastq
-rw-r----- 1 mlaziz liu_price_lab 1.5G Oct 26 15:18 Kneaddata_clean_reads/14027315_GWU_DNA_1_S14_R1_001_kneaddata_paired_1.fastq
-rw-r----- 1 mlaziz liu_price_lab 908M Oct 26 15:19 Kneaddata_clean_reads/14042950_GWU_DNA_1_S18_R1_001_kneaddata_paired_2.fastq
-rw-r----- 1 mlaziz liu_price_lab 474M Oct 26 15:19 Kneaddata_clean_reads/14046035_GWU_DNA_1_S8_R1_001_kneaddata_paired_2.fastq
-rw-r----- 1 mlaziz liu_price_lab 278M Oct 26 15:19 Kneaddata_clean_reads/14043884_GWU_DNA_1_S24_R1_001_kneaddata_paired_1.fastq
-rw-r----- 1 mlaziz liu_price_lab 1.1G Oct 26 15:19 Kneaddata_clean_reads/14027321_GWU_DNA_1_S2_R1_001_kneaddata_paired_2.fastq
-rw-r----- 1 mlaziz liu_price_lab 303M Oct 26 15:19 Kneaddata_clean_reads/14017556_GWU_DNA_1_S10_R1_001_kneaddata_paired_1.fastq
-rw-r----- 1 mlaziz liu_price_lab 338M Oct 26 15:19 Kneaddata_clean_reads/14047045_GWU_DNA_1_S29_R1_001_kneaddata_paired_2.fastq
-rw-r----- 1 mlaziz liu_price_lab 437M Oct 26 15:19 Kneaddata_clean_reads/14043682_GWU_DNA_1_S10_R1_001_kneaddata_paired_1.fastq
-rw-r----- 1 mlaziz liu_price_lab 348M Oct 26 15:19 Kneaddata_clean_reads/14043679_GWU_DNA_1_S25_R1_001_kneaddata_paired_2.fastq
-rw-r----- 1 mlaziz liu_price_lab 599M Oct 26 15:20 Kneaddata_clean_reads/14046034_GWU_DNA_1_S22_R1_001_kneaddata_paired_2.fastq
-rw-r----- 1 mlaziz liu_price_lab 767M Oct 26 15:20 Kneaddata_clean_reads/14027316_GWU_DNA_1_S30_R1_001_kneaddata_paired_1.fastq
-rw-r----- 1 mlaziz liu_price_lab 868M Oct 26 15:20 Kneaddata_clean_reads/14042951_GWU_DNA_1_S5_R1_001_kneaddata_paired_1.fastq
-rw-r----- 1 mlaziz liu_price_lab 124M Oct 26 15:20 Kneaddata_clean_reads/14019067_GWU_DNA_1_S2_R1_001_kneaddata_paired_2.fastq
-rw-r----- 1 mlaziz liu_price_lab 879M Oct 26 15:20 Kneaddata_clean_reads/14027325_GWU_DNA_1_S4_R1_001_kneaddata_paired_1.fastq
-rw-r----- 1 mlaziz liu_price_lab 379M Oct 26 15:20 Kneaddata_clean_reads/14043683_GWU_DNA_1_S26_R1_001_kneaddata_paired_2.fastq
-rw-r----- 1 mlaziz liu_price_lab 380M Oct 26 15:20 Kneaddata_clean_reads/14043683_GWU_DNA_1_S26_R1_001_kneaddata_paired_1.fastq
-rw-r----- 1 mlaziz liu_price_lab 304M Oct 26 15:21 Kneaddata_clean_reads/14023631_GWU_DNA_1_S1_R1_001_kneaddata_paired_2.fastq
-rw-r----- 1 mlaziz liu_price_lab 974M Oct 26 15:21 Kneaddata_clean_reads/14027334_GWU_DNA_1_S3_R1_001_kneaddata_paired_1.fastq
-rw-r----- 1 mlaziz liu_price_lab 965M Oct 26 15:21 Kneaddata_clean_reads/14027334_GWU_DNA_1_S3_R1_001_kneaddata_paired_2.fastq
-rw-r----- 1 mlaziz liu_price_lab 392M Oct 26 15:21 Kneaddata_clean_reads/14046033_GWU_DNA_1_S11_R1_001_kneaddata_paired_2.fastq
-rw-r----- 1 mlaziz liu_price_lab 834M Oct 26 15:22 Kneaddata_clean_reads/14027317_GWU_DNA_1_S17_R1_001_kneaddata_paired_2.fastq
-rw-r----- 1 mlaziz liu_price_lab 260M Oct 26 15:22 Kneaddata_clean_reads/14019362_GWU_DNA_1_S7_R1_001_kneaddata_paired_1.fastq
-rw-r----- 1 mlaziz liu_price_lab 853M Oct 26 15:22 Kneaddata_clean_reads/14027319_GWU_DNA_1_S31_R1_001_kneaddata_paired_2.fastq
-rw-r----- 1 mlaziz liu_price_lab 913M Oct 26 15:22 Kneaddata_clean_reads/14027333_GWU_DNA_1_S32_R1_001_kneaddata_paired_2.fastq
-rw-r----- 1 mlaziz liu_price_lab 623M Oct 26 15:22 Kneaddata_clean_reads/14046334_GWU_DNA_1_S1_R1_001_kneaddata_paired_2.fastq
-rw-r----- 1 mlaziz liu_price_lab 236M Oct 26 15:22 Kneaddata_clean_reads/14021158_GWU_DNA_1_S8_R1_001_kneaddata_paired_2.fastq
-rw-r----- 1 mlaziz liu_price_lab 365M Oct 26 15:22 Kneaddata_clean_reads/14046039_GWU_DNA_1_S21_R1_001_kneaddata_paired_2.fastq
-rw-r----- 1 mlaziz liu_price_lab 220M Oct 26 15:23 Kneaddata_clean_reads/14024546_GWU_DNA_1_S6_R1_001_kneaddata_paired_2.fastq
-rw-r----- 1 mlaziz liu_price_lab 838M Oct 26 15:23 Kneaddata_clean_reads/14046337_GWU_DNA_1_S19_R1_001_kneaddata_paired_1.fastq

**Comment by meren** [comment]
Hi, please add this to your command: --ignore-deflines
