### ISSUE TITLE
Performance issue with anvi-display-pan

### ISSUE THREAD

**Issue by razz1618** [merenlab/anvio#1604]
Hi, 
Recently I finished pangenomics analysis on my 124 MAGs. When I start the interactive mode the process gets killed at initialize gene clusters (on my 8 core i7-16GBram PC). If I use  **--skip-init-functions**, the command starts the browser but later on just hangs on clicking the "draw" tab. This is sure because of the large number of gene clusters in my data.
I tried to fire up the command on the server (with 104 cores/512 GB RAM) with port forwarding. when I click draw , it just keep showing the drawing icon and does not process further. 

**Terminal output**

anvi-display-pan -g /home/mcs/gene/shail/metagenomics/CLEANED_FILES/sunbeam_decontaminated/leptolyngbya_cleaned/sunbeam_output/qc/decontam/binning_all_togather/pangenomics/03_PAN/pangenomics-GENOMES.db \
>                  -p /home/mcs/gene/shail/metagenomics/CLEANED_FILES/sunbeam_decontaminated/leptolyngbya_cleaned/sunbeam_output/qc/decontam/binning_all_togather/pangenomics/03_PAN/pangenomics-PAN.db
Interactive mode .............................: pan
Genomes storage .............................................: Initialized (storage hash: hash6ec4e458)
Num genomes in storage ......................................: 124
Num genomes will be used ....................................: 124
Pan DB ......................................................: Initialized: /home/mcs/gene/shail/metagenomics/CLEANED_FILES/sunbeam_decontaminated/leptolyngbya_cleaned/sunbeam_output/qc/decontam/binning_all_togather/pangenomics/03_PAN/pangenomics-PAN.db (v. 13)
Gene cluster homogeneity estimates ..........................: Functional: [YES]; Geometric: [YES]; Combined: [YES]

* Gene clusters are initialized for all 241142 gene clusters in the database.

WARNING
==============================================================
This pangenome (which you gracefully named as 'pangenomics') does not seem to
have any hierarchical clustering of gene clusters it contains. Maybe you skipped
the clustering step, maybe anvi'o skipped it on your behalf because you had too
many gene clusters or something. Anvi'o will do its best to recover from this
situation. But you will very likely not be able to see a hierarchical dendrogram
in the resulting display even if everything goes alright.. In some cases using a
parameter like `--min-occurrence 2`, which would reduce the number of gene
clusters by removing singletons that appear in only one genome can help solve
this issue and make your pangenome great again.

* The server is now listening the port number '8080'. When you are finished, press
CTRL+C to terminate the server. If you are using OSX and if the server
terminates prematurely before you can see anything in your browser, try to run
the same command by putting 'sudo ' at the beginning of it (you will be likely
prompted to enter your password as this command will require super user rights
to run).

Is there any solution that I can visualize the interactactive mode

**Comment by meren** [comment]
Hi @razz1618,

You have `241,142` gene clusters. The anvi'o pangenomics workflow is not suitable to study such large pangenomes.

If you are getting more than 200K gene clusters with only 124 MAGs, you are very likely doing a mistake. Pangenomics is most powerful when relatively closely related genomes are compared. But it seems you are comparing a large collection of genomes that belong to vastly different clades of life.

I hope these help.


Best wishes,
