### ISSUE TITLE
Functions table: raw values

### ISSUE THREAD

**Issue by rikander** [merenlab/anvio#162]
It would be great if the functions table that is outputted in the bin by bin directories could have the raw read hits, rather than the normalized values, so that we can normalize across the bin. Then it would also be great to have the following values so that we can normalize ourselves:
1) total number of reads mapped by each sample/metagenome
2) total number of reads mapped to each bin by each sample/metagenome

Thank you!

**Comment by meren** [comment]
this was fixed at some point.
