### ISSUE TITLE
[BUG] docs suggestion for install of h5py

### ISSUE THREAD

**Issue by dspeth** [merenlab/anvio#1622]
## Short description of the problem

h5py not included in install instructions for v7

## anvi'o version

Replace this text with the output of this command:

Anvi'o .......................................: hope (v7)

Profile database .............................: 35
Contigs database .............................: 20
Pan database .................................: 14
Genome data storage ..........................: 7
Auxiliary data storage .......................: 2
Structure database ...........................: 2
Metabolic modules database ...................: 2
tRNA-seq database ............................: 1

## System info

Linux, RedHat 8.3.
Installed v7 following updated install instructions (not the yml file)

## Detailed description of the issue

since the move from anvi-migrate-db to anvi-migrate (I guess in v6.2?) anvi-migrate requires the additional install of h5py. providing this message when run for the first time:

Config Error: There is an issue but it is easy to resolve and everything is fine! To continue,
              please first install the Python module `h5py` by running `pip install           
              h5py==2.8.0` in your anvi'o environment. The reason why the standard anvi'o     
              package does not include this module is both complicated and really unimportant.
              Re-running the migration after `h5py` is installed will make things go smootly. 

The error message is clear, and the issue is easily solved. I was just wondering whether this error message is still up to date, as 'h5py v2.8.0' is available on conda-forge. So I was wondering if adding this line: `conda install -y -c conda-forge h5py=2.8.0` to the install instructions might be useful.

**Comment by meren** [comment]
Thank you, @dspeth! Good point. I updated the installation doc via https://github.com/merenlab/web/commit/64ad6ac50cff51d080a1fb1f357f3089f26ec872.
