### ISSUE TITLE
[BUG] anvi-setup-pdb-database fails because of "Config Error: Cannot call `DB.remove_some_rows_from_table` in read-only instance"

### ISSUE THREAD

**Issue by dspeth** [merenlab/anvio#1623]
## Short description of the problem

write read-only file by anvi-setup-pdb-database, subsequent "broken pipe" error

## anvi'o version

Anvi'o .......................................: hope (v7)

Profile database .............................: 35
Contigs database .............................: 20
Pan database .................................: 14
Genome data storage ..........................: 7
Auxiliary data storage .......................: 2
Structure database ...........................: 2
Metabolic modules database ...................: 2
tRNA-seq database ............................: 1

## System info

Linux, RedHat 8.3.
Installed v7 following updated install instructions (not the yml file)

## Detailed description of the issue
anvi-setup-pdb-database fails, presumably because the temp file written for one of the downloaded pdb entries is read only? Not urgent, just setting up the various anvio integrated resources to make my future me (potentially) happier.
Screen shots attached.

![image](https://user-images.githubusercontent.com/5320639/103574320-8c370e00-4e84-11eb-9c26-e654dba48535.png)

![image](https://user-images.githubusercontent.com/5320639/103574356-9c4eed80-4e84-11eb-954e-a19178bc8bef.png)

**Comment by meren** [comment]
Thank you, @dspeth!

**Comment by ekiefl** [comment]
Hey @dspeth thank you for the report. This has been fixed with this commit: 65ec4a380132f601697a2309af6ffe034bb17726

The problem was that the database you were creating was itself in a read-only mode.

**Comment by srisvs33** [comment]
Hi @ekiefl I am too facing the same issue, with my installation. i see this issue has been fixed now, is it available for those who installed anvio-v7 through conda stable release. 

if not, could you please help me how to fix this. 

sorry, it is too primitive question. I am new to anvio, working my way around to the top.

many thanks

Venkat

**Comment by ekiefl** [comment]
Hi @srisvs33,

Unfortunately, this was fixed _after_ v7, so it is currently only available in the development branch of anvi'o.

If you feel so inclined, you can use the development branch to access these changes. Instructions are [here](https://merenlab.org/2016/06/26/installation-v2/#5-follow-the-active-development-youre-a-wizard-arry)

Alternatively, I do have a quick fix that you could consider that involves editing the anvi'o code directly. Be very careful when doing this!

Start by locating where your anvi'o installation is located:

```bash
▶▶ which anvi-setup-pdb-database
/Users/evan/Software/anvio/bin/anvi-setup-pdb-database
```

For me, we can see the program is `/Users/evan/Software/anvio/bin/anvi-setup-pdb-database` and that means the anvi'o directory is `/Users/evan/Software/anvio`. The file you are interested in is `/Users/evan/Software/anvio/anvio/structureops.py`.

Open that up in a text editor and change line 

The file of interest is

`/Users/evan/Software/anvio/anvio/structureops.py`

Go ahead and change line 1416 from

```python
        pdb_db = self.load_db()
```

to 

```python
        pdb_db = self.load_db(write=True)
```

Then change lines 1497-1498 from 

```python
    def load_db(self):
        return db.DB(self.db_path, '0.1', new_database=False, read_only=True)
```

to

```python
    def load_db(self, write=False):
        return db.DB(self.db_path, '0.1', new_database=False, read_only=(not write))
```

This will solve the problem.

By the way, the database you want to setup is >20GB, so make sure you have space for it.

Good luck!
