### ISSUE TITLE
[BUG] anvi-setup-trna-taxonomy fails at AAA database

### ISSUE THREAD

**Issue by dspeth** [merenlab/anvio#1624]
## Short description of the problem

anvi-setup-trna-taxonomy fails at AAA database

## anvi'o version

Anvi'o .......................................: hope (v7)

Profile database .............................: 35
Contigs database .............................: 20
Pan database .................................: 14
Genome data storage ..........................: 7
Auxiliary data storage .......................: 2
Structure database ...........................: 2
Metabolic modules database ...................: 2
tRNA-seq database ............................: 1

## System info

Linux, RedHat 8.3.
Installed v7 following updated install instructions (not the yml file)

## Detailed description of the issue

I've run anvi-setup-scg-taxonomy prior to running anvi-setup-trna-taxonomy
No idea what could be the cause here

![image](https://user-images.githubusercontent.com/5320639/103577254-4c265a00-4e89-11eb-9c41-4fca4e3d472a.png)

**Comment by meren** [comment]
Thank you very much, @dspeth!

This is weird as I tested this on Linux! Can you please run the same command with a `--debug` flag?

**Comment by dspeth** [comment]
Here you go @meren 

![image](https://user-images.githubusercontent.com/5320639/103579404-1be0ba80-4e8d-11eb-9144-1cf0ef8065bd.png)

Can't immediately see anything wrong with the temp files:
![image](https://user-images.githubusercontent.com/5320639/103579597-67936400-4e8d-11eb-84ca-7d3f1c759730.png)

**Comment by meren** [comment]
Crap. I think it will not be a problem if you update your BLAST to `2.10.1`. You can see your version if you type `blastn -version`.

If you don't want to update, you can solve this by first running this to learn the file path,

```
python -c "import anvio.taxonomyops.trna; print(anvio.taxonomyops.trna.__file__)"
```

then opening that file and replacing this line:

```
nucl_database_extensions = ['.ndb', '.nhr', '.nin', '.not', '.nsq', '.ntf', '.nto']
```

with this one:

```
nucl_database_extensions = ['.ndb', '.nhr', '.nin']
```

Please let me know how it goes and thank you again!

**Comment by meren** [comment]
I'm planning to update the BLAST installation line from 

```
conda install -y -c bioconda blast
```
to

```
conda install -y -c bioconda blast=2.10.1
```

I will test how this goes and write back.

**Comment by dspeth** [comment]
update was not a problem, as nothing was downgraded or changed (solving took a few mins though). 
just for info: It did pull in entrez-direct, expat and a whole host of perl packages

anvi-setup-trna-taxonomy worked fine after updating

**Comment by meren** [comment]
On my system it caused the following error:

```
UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

Package libcxx conflicts for:
python=3.6 -> libcxx[version='>=10.0.0|>=4.0.1']
blast=2.10.1 -> pcre[version='>=8.44,<9.0a0'] -> libcxx[version='>=10.0.0']
blast=2.10.1 -> libcxx[version='>=9.0.1']
```

I have no clue how to address this.

**Comment by dspeth** [comment]
conda operates in ways I don't fully understand. This command works for me in a fresh env, but there are a number of differences in the solution (R 4.0.3 vs R 3.6.1 for example). No idea how possible solutions are chosen when versions are not specified.

conda install -y -c bioconda "sqlite >=3.31.1" prodigal mcl muscle hmmer diamond "blast=2.10.1" megahit spades bowtie2 bwa samtools centrifuge trimal iqtree trnascan-se r-base r-stringi r-tidyverse r-magrittr r-optparse bioconductor-qvalue fasttree

**Comment by meren** [comment]
I am closing this with #1626. Not only this PR solves it in the main branch, but also in `v7` package associated with the release as an asset retrospectively.

**Comment by meren** [comment]
Thank you again for your help, @dspeth.
