### ISSUE TITLE
Installation of pysam breaks during v7 installation

### ISSUE THREAD

**Issue by mschecht** [merenlab/anvio#1636]
## Short description of the problem

Hi everyone, I had an installation issue for v7 that I solved and wanted to document it here just in case it comes up for someone else. During the installation tutorial, I had an error at the step `pip install anvio-7.tar.gz` in the [installation tutorial](https://merenlab.org/2016/06/26/installation-v2/#3-install-anvio).

## System info
macOS Big Sur

$ system_profiler SPSoftwareDataType
Software:

    System Software Overview:

      System Version: macOS 11.1 (20C69)
      Kernel Version: Darwin 20.2.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal

## Detailed description of the issue

Basically, `pysam` was breaking during the `pip install anvio-7.tar.gz` step in the installation tutorial. I believe it was because the conda env variable $CC was assigned to an older c-compiler called `x86_64-apple-darwin13.4.0-clang`.

## Solved it

To fix this I did the following:
```
# Trashed and re-installed x-code
sudo rm -rf /Library/Developer/CommandLineTools
xcode-select --install

# confirmed newest c-compiler
$ clang --version
clang version 10.0.0
Target: x86_64-apple-darwin20.2.0
Thread model: posix
InstalledDir: /Users/mschechter/miniconda3/envs/anvio-7/bin

# forced conda to use newest c-compiler
export CC=clang
```
After that,  `pip install anvio-7.tar.gz`  ran just fine :)

**Comment by HMorrison** [comment]
This works if you remember to use a fresh terminal window--which I did not, initially.
