### ISSUE TITLE
[BUG] pandas version issue for anvi-estimate-metabolism --matrix-format

### ISSUE THREAD

**Issue by ivagljiva** [merenlab/anvio#1637]
## Short description of the problem

As reported on the anvi'o Slack, users with newer versions of `pandas` may get the following error when running `anvi-estimate-metabolism --matrix-format`:

```
[...]
  File "/home/jcastros/miniconda3/envs/anvio-7/lib/python3.6/site-packages/anvio/kegg.py", line 3250, in store_metabolism_superdict_multi_matrix_format
    matrix = sps.coo_matrix((df[header], (df.index.labels[1], df.index.labels[0]))).todense().tolist()
AttributeError: 'MultiIndex' object has no attribute 'labels'
``` 

The reason this happens is that newer versions of `pandas` do not have `labels` attribute in the `MultiIndex` class.

## anvi'o version

```
Anvi'o .......................................: hope (v7)

Profile database .............................: 35
Contigs database .............................: 20
Pan database .................................: 14
Genome data storage ..........................: 7
Auxiliary data storage .......................: 2
Structure database ...........................: 2
Metabolic modules database ...................: 2
tRNA-seq database ............................: 1
```

The version of `pandas` that I know works (on my system) is 0.25.1
I am not sure in which version the `labels` attribute disappears, but we know it does not work for 1.0.5

## The fix

Need to add an explicit version requirement for `pandas` in the installation setup for anvi'o `v7`

**Comment by meren** [comment]
> Need to add an explicit version requirement for pandas in the installation setup for anvi'o v7

We already have it though :)

https://github.com/merenlab/anvio/blob/master/requirements.txt

**Comment by ivagljiva** [comment]
😲 I wonder why that error came up then. 

Well, at least it is now documented here so if anyone else has a similar issue, the fix is listed. I will close this now :)

**Comment by ekiefl** [comment]
If/when we migrate to pandas >1, we are likely to run into many such errors.

Related issue: https://github.com/merenlab/anvio/issues/1474
