### ISSUE TITLE
A proposal to use `prodigal` in anvi'o with the `-m` flag by default

### ISSUE THREAD

**Issue by meren** [merenlab/anvio#1641]
# Background

Anvi'o uses prodigal as the default gene caller. While we are aware of the many limitations of using a single gene caller especially for metagenomic assemblies that may include contigs that are coming from different lineages of life with different genetic code, this is the best we can do for now.

As of today, and in `v7`, `prodigal` is run by anvi'o with the default parameters of,

* `-i` (input file),
* `-o` (output file), and
* `-a` (report amino acid sequences for ORFs), 

and the following mutually exclusive parameters: 

* `-g` (if the user provided a specific translation table) or
* `-p meta` (to run the gene caller in metagenome mode).

Here is that section of the code from the [relevant file](https://github.com/merenlab/anvio/blob/ce4e821d1f3cf5832aa7df857cc67fb3dbae38b3/anvio/threadingops.py#L427) for those who would like to see it the way it is implemented:

``` python
            command = ['prodigal',
                       '-i', self.input_file_splits[i],
                       '-o', self.output_file_split_paths['gff_path'][i],
                       '-a', self.output_file_split_paths['peptide_path'][i]]

            # Use either custom translation table or 'meta' mode.
            if self.translation_table:
                # Translation tables and meta mode cannot be used together.
                command.extend(['-g', self.translation_table])
                if self.logger:
                    self.logger.run.warning(
                        "Prodigal translation table is set to '%s' (whatever you did has worked so far, but "
                        "keep an eye for errors from prodigal in case it doesn't like your translation table "
                        "parameter). This means we will not use prodigal in the metagenomics mode, due to this"
                        "issue: https://github.com/hyattpd/Prodigal/issues/19. If that issue is closed, and "
                        "you are reading this message, then please contact an anvi'o developer."
                        % str(self.translation_table))
            else:
                # Use 'meta' mode if no translation tables are given.
                command.extend(['-p', 'meta'])
```

# Proposal

The idea proposed by @dspeth in #1638 is to **add `-m` to the mix of default `prodigal` flags,** which instructs the program to treat runs of `N` as masked sequence and so it doesn't build genes across them.

This is due to an observation Daan has made in #1638, where `prodigal` identified a gene with in [a GTDB genome](https://gtdb.ecogenomic.org/genomes?gid=GCA_003029985.1) that contained over 100,000 residues of `X`, which is a place holder in amino acid sequences for `NNN`. This gene was infinitely long because 136 contigs were joined by `N`s into a single scaffold to produce this genome.

Daan confirmed that the addition of `-m` into the default `prodigal` flags solves the identification of extremely long genes due to scaffolding with `N`s. Both Daan and I believe that it is a good idea to update the way anvi'o runs `prodigal`, but since this is such a fundamental change, we thought it would be a good idea to ask members of the community in case there are those with alternative suggestions.

# Request for input

If you run into this proposal and read through it, please thumbs up the post if you support it, or please consider sharing your concerns or suggestions to help us solve this matter in a better way.

Thank you for your time and input in advance.

**Comment by ekiefl** [comment]
@FlorianTrigodet, you have done a lot of tests on the quality of prodigal's gene calling. Are any of those findings relevant to this discussion?

I was curious how often do we see an `N` in genes. As a completely non-exhaustive exercise, I calculated the number of genes in some 20 contigs databases I had on hand and found the following:

```
{'HIMB114': 0, 'htcc9565': 6, 'HIMB122': 0, 'HIMB140': 0, 'htcc1040': 4, 'htcc1013': 13, 'HIMB058': 3, 'imcc9063': 0, 'htcc1062': 0, 'htcc7214': 1, 'htcc8051': 1, 'HIMB4': 0, 'HIMB5': 0, 'htcc1016': 2, 'htcc9022': 6, 'HIMB083': 1, 'htcc1002': 0, 'HIMB59': 0, 'htcc7217': 0, 'htcc1321': 0, 'htcc7211': 0}
```

Basically, a minimal number of amino acid sequences contained `X`, which occurs whenever the nt sequence contains `N`.

**Comment by meren** [comment]
@ekiefl, @FlorianTrigodet, @dspeth, I am also curious what does 'runs of `N`' exactly mean in prodigal lingo. I don't think prodigal will ignores when it is in `-m` mode _any_ gene call with one or two ambiguous bases (since it says "runs of `N` rather than any occurrence, but perhaps I'm reading too much into it). But if that is the case, it may be important for us to know the number of `N`s that will render an ORF to be excluded. If no one knows this, we perhaps can figure it out either from the prodigal code or empirically by running it on different scenarios.

**Comment by FlorianTrigodet** [comment]
I have tested the "metagenomics" vs "single" mode of Prodigal on MAGs. Right now anvi'o uses the meta mode on the contigs (which make sense), but we could consider re-running prodigal in single-genome mode once we have a collection of MAG (on average it generates more and smaller genes-call). But I haven't looked into `N` in genes.

I agree that we should have the `-m` argument by default in anvi'o. I'd prefer to have partial genes call rather than genes that overlap a region of `N` due to assembly scaffolding.

**Comment by meren** [comment]
Well, looking through the prodigal code was not so much fun, so I wrote this Python program that generates versions of the same template sequence with different number of `N`s:

``` python
# the gene caller id '1' from the IGD contigs database:
template = "TTGAAAATATTGTTATATTTTGAAGGTGAGAAAATCTTAGCTAAATCAGGTATTGGTCGAGCATTAGATCACCAGAAACGAGCGCTCTCTGAAGTTGGAATAGAATATACATTAGATGCTGATTGCAGTGACTATGATATATTGCATATTAATACATACGGCGTAAATAGCCATCGTATGGTCAGAAAAGCACGCAAACTAGGAAAAAAAGTTATTTATCATGCCCATTCGACAGAAGAAGACTTTCGTAATTCCTTTATTGGGTCTAATCAACTAGCACCATTAGTAAAAAAATATCTTATCAGTTTGTATTCTAAAGCGGATCATTTAATTACACCAACACCGTATTCTAAAACATTGCTAGAAGGATATGGCATTAAAGTGCCTATTTCGGCGATCTCAAATGGTATTGATTTATCACGCTTTTATCCTTCAGAAGAAAAGGAACAAAAATTCCGAGAATATTTTAAAATAGATGAAGAGAAAAAAGTAATTATTTGTGTGGGATTATTTTTTGAACGCAAAGGAATCACTGATTTTATTGAAGTTGCACGACAATTACCAGAGTATCAATTTATTTGGTTTGGTGATACACCAATGTATTCTATCCCAAAAAATATCCGACAATTAGTTAAAGAAGATCATCCAGAAAATGTTATTTTCCCAGGTTATATTAAAGGAGATGTCATCGAAGGGGCCTATGCGGCAGCGAATCTCTTCTTTTTCCCTTCGCGTGAAGAAACGGAAGGAATTGTTGTCTTAGAAGCATTAGCTAGTCAGCAACAAGTTTTAGTGCGTGATATTCCAGTTTATCAAGGCTGGCTAGTAGCTAATGAAAATTGTTATATGGGTCATTCTATTGAAGAATTTAAAAAATATATTGAAGGCTTATTAGAAGGGAAAATACCTAGCACTAGAGAAGCAGGCTATCAAGTAGCAGAGCAAAGAAGTATCAAGCAAATTGGTTACGAGTTAAAAGAAGTCTACGAAACAGTCTTATCTTAA"
nucleotide_position_to_insert_Ns = 20
max_num_Ns = 100
output_file = 'genes.fa'

with open(output_file, 'w') as output:
    for num_ns in range(0, max_num_Ns):
        gene_sequence = template[:nucleotide_position_to_insert_Ns] + 'N' * num_ns + template[nucleotide_position_to_insert_Ns:]
        output.write(f'>gene_seq_with_{num_ns}_Ns\n')
        output.write(f'{gene_sequence}\n')
```

Running it gave me the `genes.fa` that contained 500 sequences that has 0 to 499 `N`s. I run it like this:

```
prodigal -i genes.fa -o genes.txt -a gene-AAs.txt -p meta -m
```

And I got all the sequences properly identified:

```
grep CDS genes.txt | wc -l
500
```

When I run it this way, without `-m`, however,

```
prodigal -i genes.fa -o genes.txt -a gene-AAs.txt -p meta
```

There were way too many spurious gene calls:

```
grep CDS genes.txt | wc -l
559
```

This was due to arbitrary splitting of genes like this without `-m`:

```
QRSIKQIGYELKEVYETVLS*
>gene_seq_with_499_Ns_1 # 3 # 539 # 1 # ID=500_1;partial=10;start_type=Edge;rbs_motif=None;rbs_spacer=None;gc_cont=0.946
ENIVIFXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXKVRKS*
>gene_seq_with_499_Ns_2 # 677 # 1504 # 1 # ID=500_2;partial=00;start_type=ATG;rbs_motif=TAA;rbs_spacer=11bp;gc_cont=0.342
MVRKARKLGKKVIYHAHSTEEDFRNSFIGSNQLAPLVKKYLISLYSKADHLITPTPYSKT
LLEGYGIKVPISAISNGIDLSRFYPSEEKEQKFREYFKIDEEKKVIICVGLFFERKGITD
FIEVARQLPEYQFIWFGDTPMYSIPKNIRQLVKEDHPENVIFPGYIKGDVIEGAYAAANL
FFFPSREETEGIVVLEALASQQQVLVRDIPVYQGWLVANENCYMGHSIEEFKKYIEGLLE
GKIPSTREAGYQVAEQRSIKQIGYELKEVYETVLS*
```

Where the same gene `gene_seq_with_499_Ns` looked like this with `-m`:

```
>gene_seq_with_499_Ns_1 # 677 # 1504 # 1 # ID=500_1;partial=00;start_type=ATG;rbs_motif=TAA;rbs_spacer=11bp;gc_cont=0.342
MVRKARKLGKKVIYHAHSTEEDFRNSFIGSNQLAPLVKKYLISLYSKADHLITPTPYSKT
LLEGYGIKVPISAISNGIDLSRFYPSEEKEQKFREYFKIDEEKKVIICVGLFFERKGITD
FIEVARQLPEYQFIWFGDTPMYSIPKNIRQLVKEDHPENVIFPGYIKGDVIEGAYAAANL
FFFPSREETEGIVVLEALASQQQVLVRDIPVYQGWLVANENCYMGHSIEEFKKYIEGLLE
GKIPSTREAGYQVAEQRSIKQIGYELKEVYETVLS*
```

Of course, a better test would have been to see what happens when `N`s overwrite the stop and start codons in a contig with multiple genes in it, perhaps I will do that too if I can find a minute, but essentially this shows that prodigal will not discard genes just because they have internal `N`s with `-m`, which is good news.

**Comment by dspeth** [comment]
@meren, I did see some proteins with X residues in the GTDB genome that started this discussion, even when running with `-m` suggesting it doesn't consider 3 Ns a "run of Ns". In your test, what's the largest number of Xs added to the protein aa sequence when running prodigal with `-m`?

**Comment by meren** [comment]
> In your test, what's the largest number of Xs added to the protein aa sequence when running prodigal with -m?

17, in this one with 48 `N`s:

```
>gene_seq_with_48_Ns_1 # 1 # 1053 # 1 # ID=49_1;partial=10;start_type=Edge;rbs_motif=None;rbs_spacer=None;gc_cont=0.372
LKILLYXXXXXXXXXXXXXXXXXEGEKILAKSGIGRALDHQKRALSEVGIEYTLDADCSD
YDILHINTYGVNSHRMVRKARKLGKKVIYHAHSTEEDFRNSFIGSNQLAPLVKKYLISLY
SKADHLITPTPYSKTLLEGYGIKVPISAISNGIDLSRFYPSEEKEQKFREYFKIDEEKKV
IICVGLFFERKGITDFIEVARQLPEYQFIWFGDTPMYSIPKNIRQLVKEDHPENVIFPGY
IKGDVIEGAYAAANLFFFPSREETEGIVVLEALASQQQVLVRDIPVYQGWLVANENCYMG
HSIEEFKKYIEGLLEGKIPSTREAGYQVAEQRSIKQIGYELKEVYETVLS*
```

After 48, there is not a single `X` for downstream sequences, and all of them are identical to this, where the beginning of the sequence is truncated and aligns to the original sequence the way shown in my previous message:

```
>gene_seq_with_49_Ns_1 # 227 # 1054 # 1 # ID=50_1;partial=00;start_type=ATG;rbs_motif=TAA;rbs_spacer=11bp;gc_cont=0.342
MVRKARKLGKKVIYHAHSTEEDFRNSFIGSNQLAPLVKKYLISLYSKADHLITPTPYSKT
LLEGYGIKVPISAISNGIDLSRFYPSEEKEQKFREYFKIDEEKKVIICVGLFFERKGITD
FIEVARQLPEYQFIWFGDTPMYSIPKNIRQLVKEDHPENVIFPGYIKGDVIEGAYAAANL
FFFPSREETEGIVVLEALASQQQVLVRDIPVYQGWLVANENCYMGHSIEEFKKYIEGLLE
GKIPSTREAGYQVAEQRSIKQIGYELKEVYETVLS*
```

**Comment by dspeth** [comment]
that checks out. I don't know any flavour of C, but did some trawling through the prodigal codebase:

the variable `MASK_SIZE` defined here seems to be the key:
https://github.com/hyattpd/Prodigal/blob/GoogleImport/sequence.h

and lines 73 and 184 of this file is where the magic happens:
https://github.com/hyattpd/Prodigal/blob/GoogleImport/sequence.c

**Comment by meren** [comment]
That is correct, @dspeth. `-m` turns on `do_mask`, so the code enters that section.

**Comment by meren** [comment]
(I have to admit that in these kinds of threads I always expect @xvazquezc to come and tell us something we didn't think of 😂 (so I am patiently waiting)).

**Comment by xvazquezc** [comment]
haha thanks @meren
Unfortunately, the only thing I can say is that `-m` appears to be a deprecated option _similar_ to `-e 1` (_Genes cannot run into gaps._). See https://github.com/hyattpd/prodigal/wiki/cheat-sheet
No idea if the output and/or behaviour is exactly the same though.

Certainly, allowing 50 Ns seems absurd unless the genome is derived from a reference-based assembly (gapped length in the conflictive genome is ~1.7Mbp!!). It is also true that many folks back in the day used to scaffold genomes with trails of N without having actual evidence for it so it may also be an issue for old assemblies

**Comment by dspeth** [comment]
@xvazquezc I browsed that documentation as well, in search for the meaning of `-m` hoping I wouldn't have to trawl the code :P The doc page is older than the latest release of prodigal (08/2014 vs 02/2016) and the `-m` flag comes  from the sparse help of release 2.6.3. 

My takeaway was that `-m` got de-deprecated

With `-m` 50 N nucleotides are still allowed 
without any number goes

**Comment by xvazquezc** [comment]
You are totally right. I wouldn't be surprised that the docs were based on the v3 which was planned for years but that will never be released.

My guess is that this situation will mainly happen with external genomes. Another way to deal with it to avoid having to modify Prodigal specifically could be to make anvi'o split the contigs with trails of Ns during the importing, and/or, maybe even better, as an automated QC check/alert during the reformat fasta (so metaG assemblies would also be checked). Just an idea..

**Comment by meren** [comment]
Thanks for all the input! :)

> Another way to deal with it to avoid having to modify Prodigal specifically could be to make anvi'o split the contigs with trails of Ns during the importing

This scares me since it may create some downstream headaches. When we split contigs into smaller ones based on trail of Ns, we will have to give new and unique names to each piece, which will not match to the input sequence deflines :/

> an automated QC check/alert during the reformat fasta

I think this is something we need certainly and I will try to implement this in `anvi-script-reformat-fasta`.

Meanwhile, AFAICS, there is no significant concern against `-m`. So I will add that, too.

**Comment by meren** [comment]
This is now in the main branch. Thank you all very much!
