### ISSUE TITLE
Error: mdb_env_open: Cannot allocate memory

### ISSUE THREAD

**Issue by VMJarocki** [merenlab/anvio#1646]
## Short description of the problem

Recieve "Error: mdb_env_open: Cannot allocate memory" when attempting to run anvi-setup-ncbi-cogs

## anvi'o version

Replace this text with the output of this command:

v7

## System info

Linux, conda

## Detailed description of the issue

$ anvi-setup-ncbi-cogs

WARNING
===============================================
This program will first check whether you have all the raw files, and then will
attempt to regenerate everything that is necessary from them.

Press ENTER to continue, or press CTRL + C to cancel...

Diamond log ..................................: /home/Data/miniconda3/envs/anvio-7/lib/python3.6/site-packages/anvio/data/misc/COG/COG20/DB_DIAMOND/log.txt
Diamond search db ............................: /home/Data/miniconda3/envs/anvio-7/lib/python3.6/site-packages/anvio/data/misc/COG/COG20/DB_DIAMOND/COG.dmnd
BLAST log ....................................: /home/Data/miniconda3/envs/anvio-7/lib/python3.6/site packages/anvio/data/misc/COG/COG20/DB_BLAST/log.txt
                                                                                                                                            

Config Error: Pfft. Something probably went wrong with 'makeblastdb' process since one of the
              expected output files are missing. Please check the log file here:             
              '/home/Data/miniconda3/envs/anvio-7/lib/python3.6/site-               
              packages/anvio/data/misc/COG/COG20/DB_BLAST/log.txt' 

log.txt:

# DATE: 21 Jan 21 08:33:01
# CMD LINE: makeblastdb -in /tmp/tmpug7gjlhq -dbtype prot -out /home/Data/miniconda3/envs/anvio-7/lib/python3.6/site-packages/anvio/data/misc/COG/COG20/DB_BLAST/COG/COG.fa

Building a new DB, current time: 01/21/2021 08:33:02
New DB name:   /home/Data/miniconda3/envs/anvio-7/lib/python3.6/site-packages/anvio/data/misc/COG/COG20/DB_BLAST/COG/COG.fa
New DB title:  /tmp/tmpug7gjlhq
Sequence type: Protein
Keep MBits: T
Maximum file size: 1000000000B

No volumes were created.

Error: mdb_env_open: Cannot allocate memory

**Comment by meren** [comment]
Try running this before running the `anvi-setup-ncbi-cogs`:

```
export BLASTDB_LMDB_MAP_SIZE=1000000
```

**Comment by VMJarocki** [comment]
Thanks, worked a treat 👍
