### ISSUE TITLE
[FEATURE] Grids AND Shades

### ISSUE THREAD

**Issue by meren** [merenlab/anvio#1650]
The current default behavior in the interactive interface is to either mark selections with a colored area, or grids. The latter is turned on via the "Show grids" checkbox and automatically turns off the colored area:

![image](https://user-images.githubusercontent.com/197307/105727462-b9f5fc80-5ef0-11eb-9c40-77f1e9671511.png)

It would be much better to have "Show shades" as an additional option, so grids and shades are not mutually exclusive, and the user can turn both of them on.

This will make the lives of those who try to make pretty figures much easier :)

But it is essential to make sure the implementation works with existing states.

**Comment by matthewlawrenceklein** [comment]
addressed in PR #1657
