### ISSUE TITLE
Why can't anvi'o be nice: A feature request

### ISSUE THREAD

**Issue by meren** [merenlab/anvio#1653]
## The need

SO I AM FINALLY TOO TIRED OF TYPING `-p PROFILE.db -c CONTIGS.db` EVERY TIME I WANT ANVI'O TO DO SOMETHING STUPID. JUST FIGURE IT OUT. MAKE IT HAPPEN. LET ME GET AWAY BY TYPING `anvi-interactive` OR `anvi-display-pan`. WHAT IS THE BIG DEAL EH? WHY CAN'T YOU BE NICE YOU STUPID CALCULATOR :(

## The solution

Well. Our beloved anvi'o knows all of its databases, their types, and the network of association between them thanks to cryptographic hashes. It certainly has the technical capacity to make it happen if it wanted to (at least whenever it can unambiguously resolve database associations).

## Beneficiaries

ME.

And/or anyone who uses anvi'o for anything and/or older than 40 and/or have hands.

**Comment by ivagljiva** [comment]
😂 

seriously, though, this will be next-level stuff. pretty soon anvi'o will be reading everyone's minds and taking over the world
