### ISSUE TITLE
anvi-estimate-metabolism failing with AttributeError even when using pandas 0.25

### ISSUE THREAD

**Issue by tpriest0** [merenlab/anvio#1656]
First of all thank you for another awesome Anvi'o release! 

Unfortunately I have come across a problem with 'anvi-estimate-metabolism' when using multiple bins in a collection via the '-i' option.

The script failed with an 'AttributeError: 'MultiIndex' object has no attribute 'labels'. 

I noticed that there was a bug already identified but apparently only for later pandas releases. I am experiencing this problem with the recommended pandas 0.25.1 installation. Importantly, I have already tried this script with a single bin in a contigs database and experienced no problems. Therefore, it is only when using multiple bins in a collection.

A bit more information:
I have a contigs and profile database with a single collection containing 12 bins. I created the internal genomes file as recommended and ran the anvi-estimate-metabolism script with the following command:

anvi-estimate-metabolism -i genomes.txt --matrix-format --include-metadata

Any suggestions on how I can get around this problem?

Thank you for your time!

**Comment by ivagljiva** [comment]
Hey @tpriest0, I am sorry that this continues to be an issue for you. The script is working on my end with multiple bins in a collection (I tested the same command you used, but with my own collection of 6 bins), so I am not sure why it is not working in your case. 

I know you are on pandas 0.25.1, but just in case this is a weird environment conflict could you please try to set this version explicitly by running the following?
`pip install pandas==0.25.1`

Please let me know if it still doesn't work afterwards.

**Comment by tpriest0** [comment]
That seems to have solved the problem thank you! When I ran this command, it stated it was uninstalling pandas 1.1.1 that was already installed, despite the listed version of pandas being 0.25.1

Thanks for your help!

**Comment by ivagljiva** [comment]
Yay :)
