### ISSUE TITLE
[FEATURE] Phylogenomics tutorial is outdated

### ISSUE THREAD

**Issue by phiweger** [merenlab/anvio#1665]
## The need

The [phylogenomics tutorial](https://merenlab.org/2017/06/07/phylogenomics/) uses the now deprecated Campbell et al. collection.

## The solution

Integrate the latest collections:

> Starting with this version, we no longer use Campbell et al. and Rinke et al. single-copy core gene (SCGs) HMM sets to estimate completion of bacterial and archaeal genomes. Instead, we are using a modified version of the bacterial single-copy core gene collections Mike Lee recently described, and a set of BUSCO HMMs Tom Delmont curated. Now anvi'o can estimate the completion of bacterial, archaeal, and protist genomes (#1150).

## Beneficiaries

Me, bc/ I am a noob and don't quite know what to replace the `Campbell_et_al` with :)

```bash
anvi-get-sequences-for-hmm-hits \
	--external-genomes external-genomes.txt \
	--hmm-source Campbell_et_al \
	--list-available-gene-names
```

Thanks a lot!

**Comment by meren** [comment]
This is now done as I updated multiple things in the document via https://github.com/merenlab/web/commit/e88714259ff65c510073aba97ef2d2029da7f4e2 :) Thank you, @phiweger!

**Comment by phiweger** [comment]
awesome speed thx @meren !
