### ISSUE TITLE
[BUG] can't find anvi-script-FASTA-to-contigs-db

### ISSUE THREAD

**Issue by GodloveD** [merenlab/anvio#1668]
## Short description of the problem

The documentation [here](https://merenlab.org/2017/06/07/phylogenomics/) suggests there should be a wrapper script called `anvi-script-FASTA-to-contigs-db`.  I've searched this repo and the conda environment and cannot find either the script or the string within any files.   

## anvi'o version

```
Anvi'o .......................................: hope (v7)

Profile database .............................: 35
Contigs database .............................: 20
Pan database .................................: 14
Genome data storage ..........................: 7
Auxiliary data storage .......................: 2
Structure database ...........................: 2
Metabolic modules database ...................: 2
tRNA-seq database ............................: 1
```

**Comment by meren** [comment]
Thank you very much for pointing this out, @GodloveD!

We got rid of that script recently and clearly forgot to update the documentation :) I have now fixed it.

(I realized there are other parts that also need to be updated there, so I will take care of them, too).


Best,

**Comment by GodloveD** [comment]
Thank you for verifying that this script no longer exists.  😸
