### ISSUE TITLE
Failed installation of version 7 on Ubuntu 20.04

### ISSUE THREAD

**Issue by pavlo888** [merenlab/anvio#1669]
## Short description of the problem

I cannot successfully install anvio-7 in a Ubuntu 20.04 environment. I have tried installing it using the yml file and creating a conda environment. However, when I try to check the version of the installation I get an error. 

## anvi'o version

```
anvi-self-test --version
anvi-self-test: command not found

```
Any idea what could be wrong?

**Comment by ivagljiva** [comment]
@pavlo888, I'm sorry for the very long delay. This issue clearly fell through the cracks. From the `command not found`, it looks like anvi'o is not in your path, which can happen if you don't activate the conda environment before trying to run anvi'o commands.
