### ISSUE TITLE
[BUG] "anvi-dereplicate-genomes" defaulting to the "centrality" --representative-method instead of the Qscore method

### ISSUE THREAD

**Issue by brookeweigel** [merenlab/anvio#1674]
## Short description of the problem

I'm having an issue with "anvi-dereplicate-genomes" defaulting to the "centrality" --representative-method instead of the Qscore method when using pyANI, even through the bins associated with my internal genomes file clearly have good completion and redundancy scores associated with them. 

## anvi'o version 7
```
anvi-self-test --version
```

Anvi'o .......................................: hope (v7)

Profile database .............................: 35
Contigs database .............................: 20
Pan database .................................: 14
Genome data storage ..........................: 7
Auxiliary data storage .......................: 2
Structure database ...........................: 2
Metabolic modules database ...................: 2
tRNA-seq database ............................: 1

## System info

Running anvio on the UChicago midway2 RCC cluster, using anvio v.7

## Here is the code that I ran:
anvi-dereplicate-genomes -i MAGs_final_internal_genomes.txt -o 14_Dereplicated_MAGs/ANI_99 --program pyANI --similarity-threshold 0.99 --representative-method Qscore -T 4 --log-file 14_Dereplicated_MAGs/ANI_99/anvi_derep.log

WARNING
===============================================
At least one of your genomes does not have completion and/or redundancy scores,
which makes it impossible to use Qscore to pick best representatives from each
cluster. One of these genomes is g4_MAG_00004. Anvi'o switched you to the
'centrality' method for picking representatives.

## After I removed this genome (g4_MAG_00004) which was the last genome in my internal genomes.txt file (attached), the error was reproducible for the last genome in the internal genomes file, after removing  g2_MAG_00004, which was now g4_MAG_00003. I’m not sure what is wrong here, but it seems like a bug or something is still wrong with my internal genomes .txt file. Thanks!

WARNING
===============================================
At least one of your genomes does not have completion and/or redundancy scores,
which makes it impossible to use Qscore to pick best representatives from each
cluster. One of these genomes is g4_MAG_00003. Anvi'o switched you to the
'centrality' method for picking representatives.

## Files to reproduce
[MAGs_final_internal_genomes.txt](https://github.com/merenlab/anvio/files/5979127/MAGs_final_internal_genomes.txt)

## I think my contigs.db + profile.db will be too large to upload because it contains my entire dataset, but I'm happy to share via email (brookeweigel@uchicago.edu) or scp file transfer. Thank you!

**Comment by meren** [comment]
It has been a long time, but I finally was able to reproduce this, and was able to solve the problem.

I'm very sorry this fell through the cracks, and took this long (I know you moved on from this and managed to address your problem, but still :)).


Best wishes,
