### ISSUE TITLE
[FEATURE] add flag to `anvi-run-hmms` to export raw output of `hmmscan`

### ISSUE THREAD

**Issue by mschecht** [merenlab/anvio#1675]
## The need

`anvi-run-hmms` only provides the best hit based on e-value. It would be great if the user could have access to the raw `hmmscan` output files to look at other sequences that aligned to the hmm models provided by anvio.

## The solution

I think a solution to this problem would be to add a parameter to `anvi-run-hmms` which allows the user to provide a path to a directory to put the raw `hmmscan`/`hmmsearch` files for their own perusal. 

## Beneficiaries

This would benefit any anvio user who wants to take a deeper dive into the results of the `hmmscan` driver in the anvio code base without using the `--debug` flag.

**Comment by ivagljiva** [comment]
Alright @mschecht, I've done some work on this and would like you to check it out to make sure it fills your needs :)

Please checkout the branch `fr_1675` to test it out. 
You can run 
```
anvi-run-hmms -c CONTIGS.db --hmmer-output-dir hmmer_output_test -I Bacteria_71
``` 
to get a directory that contains the `hmmscan` output (only the regular table file). If you also want the domain table file in that directory, you can run 
```
anvi-run-hmms -c CONTIGS.db --hmmer-output-dir hmmer_output_test -I Bacteria_71 --get-domtable-output
``` 
Please note that in the latter case, the domain table output will not be used to annotate the contigs database (it is still only the regular table file that is used for that).

I would appreciate hearing your feedback on whether this is what you need for PR #1678, and whether you find any bugs while testing. Thanks!

**Comment by mschecht** [comment]
@ivagljiva I can't thank you enough for implementing this! 

> I would appreciate hearing your feedback on whether this is what you need for PR #1678, and whether you find any bugs while testing.

`fr_1675` works out of the box with #1678!

Here I start in your branch to get domtblout with `anvi-run-hmms` then move to my branch and seamlessly use `anvi-script-filter-hmm-hits-table`:
```
# start in Iva's branch where she added in the correct way to get domtblout (god bless Iva!)
# git checkout fr_1675
$ anvi-run-hmms -c CONTIGS.db --hmmer-output-dir hmmer_output_test_dom_hmmsearch -I Bacteria_71 --get-domtable-output --just-do-it --hmmer-program hmmsearch

WARNING
===============================================
Previous entries for "Bacteria_71" is being removed from "hmm_hits_info,
hmm_hits, hmm_hits_in_splits, genes_in_contigs, gene_functions"

Contigs DB ...................................: MIT9201.db
HMM sources ..................................: Bacteria_71
Alphabet/context target found ................: AA:GENE

HMM Profiling for Bacteria_71
===============================================
Reference ....................................: Lee modified, https://doi.org/10.1093/bioinformatics/btz188
Kind .........................................: singlecopy
Alphabet .....................................: AA
Context ......................................: GENE
Domain .......................................: bacteria
HMM model path ...............................: /var/folders/l4/c5v07vmj4jj9phh9lqm_hbz00000gq/T/tmp800utphc/Bacteria_71.hmm
Number of genes in HMM model .................: 71
Noise cutoff term(s) .........................: --cut_ga
Number of CPUs will be used for search .......: 1
HMMer program used for search ................: hmmsearch
Temporary work dir ...........................: /var/folders/l4/c5v07vmj4jj9phh9lqm_hbz00000gq/T/tmpf0xqtijh
Log file for thread 0 ........................: /var/folders/l4/c5v07vmj4jj9phh9lqm_hbz00000gq/T/tmpf0xqtijh/AA_gene_sequences.fa.0_log
Number of raw hits in table file .............: 70
Number of raw hits in domtable file ..........: 71
Number of weak hits removed by HMMER parser ..: 0
Number of hits in annotation dict  ...........: 70

# Move to other branch and test 
# git checkout anvi-script-filter-hmm-hits-table
$ anvi-script-filter-hmm-hits-table -c CONTIGS.db --domtblout hmmer_output_test_dom_hmmsearch/hmm.domtable --hmm-source Bacteria_71 --target-coverage 0.9

HMM profiles .................................: 9 sources have been loaded: Bacteria_71 (71 genes, domain: bacteria), Archaea_76 (76 genes, domain: archaea), Ribosomal_RNA_23S (2 genes, domain: None), Ribosomal_RNA_28S (1 genes, domain: None), Ribosomal_RNA_5S (5 genes, domain: None), Ribosomal_RNA_16S (3 genes, domain: None), Ribosomal_RNA_12S (1 genes, domain:
                                                None), Protista_83 (83 genes, domain: eukarya), Ribosomal_RNA_18S (1 genes, domain: None)
Database Path ................................: MIT9201.db
Domtblout Path ...............................: hmmer_output_test_dom_hmmsearch/hmm.domtable
Num hits before filtering ....................: 71
Num hits after filtering .....................: 17
Num filtered .................................: 54

WARNING
===============================================
Previous entries for "Bacteria_71" is being removed from "hmm_hits_info,
hmm_hits, hmm_hits_in_splits, genes_in_contigs, gene_functions"


WARNING
===============================================
This is the base parser class--a part of the code you should never hear from.
PLEASE READ THIS CAREFULLY. While anvi'o was trying to parse some files
assocaited with the annotation source `HMMScan`, it found that 16 of the lines
in this file were not able to made sense of. This part of the code does not know
anything more than that. It doesn't even know what file it is. But in general
this error occurs when the mapping function does not find what its looking for
in a line. For instance, a value that was supposed to be an integer ends up
being actually a piece of text or something. Well. Here are the line numbers if
you care and can make sense of this information: 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
1, 1, 1, 1, 1, 1

Number of weak hits removed by HMMER parser ..: 0
Number of hits in annotation dict  ...........: 17
```


What is the best way to move forward? Merge `fr_1675` with `main` then I'll merge `main` with #1678?

**Comment by ivagljiva** [comment]
yay :)

> What is the best way to move forward? 

Hmm. I still need @ekiefl to take a look at this and make sure it doesn't break his interacdome code. Maybe you could merge `fr_1675` with your own branch and then all changes can be merged together to `main` later once everything has been tested properly?

Also, @mschecht do you know if there are any sanity checks I am missing here? I was trying to remember if using `--domtblout` would cause `hmmscan` to fail in some situations (I did not test it), since I believe you told me something about how it only works for a certain `CONTEXT`? If you think of something, please let me know so I can add the proper exception :)

**Comment by ekiefl** [comment]
I won't be able to look at this until Tuesday, sorry.

**Comment by ivagljiva** [comment]
No worries at all @ekiefl (enjoy your break :). I tested it with the code you sent me (`anvi-run-interacdome -c CONTIGS.db -T 6`), and it ran fine without errors! It also looks like the output was unchanged, so I am not worried about this anymore :)
