### ISSUE TITLE
Anvi'o Self-test: connection failed

### ISSUE THREAD

**Issue by jscheffing** [merenlab/anvio#1679]
## Short description of the problem

Hello everyone!

I tried to setup anvi'o according to this tutorial (https://merenlab.org/2018/03/07/working-with-remote-interative/),  but when I do a self-test, I cannot open the interactive interface nor does it open automatically. This is what i get:

## anvi'o version 7

channel 1015: open failed: connect failed: Device or resource busy
OPEN_ON_LOCAL[http://0.0.0.0:8091]

* The server is up and running 🎉

WARNING
===============================================
If you are using OSX and if the server terminates prematurely before you can see
anything in your browser, try running the same command by putting 'sudo ' at the
beginning of it (you will be prompted to enter your password if sudo requires
super user credentials on your system). If your browser does not show up, try
manually entering the URL shown below into the address bar of your favorite
browser. *cough* CHROME *cough*.

Server address ...............................: http://0.0.0.0:8091

* When you are ready, press CTRL+C once to terminate the server and go back to the
command line.

## System info

I downloaded and installed anvi'o v7 as described on this website: https://merenlab.org/2016/06/26/installation-v2/#running-the-mini-test

Maybe someone of you has a solution to this problem?

Best wishes,
Jutta

**Comment by meren** [comment]
Hi @jscheffing, 

Unfortunately this is not an easy issue to help remotely. Please take a look at the comments underneath the blog post and see if there is anything that may help you.

Essentially anvi'o is working, but your local or remote setup for connections is not.

In the worst case scenario you will need to download your db files from your server to run `anvi-interactive` locally.

Best wishes,
