### ISSUE TITLE
[BUG] Metabolism Display shows empty

### ISSUE THREAD

**Issue by GeoMicroSoares** [merenlab/anvio#1680]
## Short description of the problem

Running `anvi-display-metabolism` I get a server address that uses RAM and CPU associated to the python process but won't show anything.

## anvi'o version

Replace this text with the output of this command:

```
$ anvi-self-test --version
Anvi'o .......................................: hope (v7)

Profile database .............................: 35
Contigs database .............................: 20
Pan database .................................: 14
Genome data storage ..........................: 7
Auxiliary data storage .......................: 2
Structure database ...........................: 2
Metabolic modules database ...................: 2
tRNA-seq database ............................: 1
```

## System info

Running macOS Big Sur 11.2 and installed `anvi'o` [via conda](https://merenlab.org/2016/06/26/installation-v2/).

## Detailed description of the issue

Running `sudo anvi-display-metabolism -c contigs.db -p SAMPLES-MERGED/PROFILE.db -C CONCOCT -B metabolism_bins.txt`, it runs well (see below) and I can track the python process in my RAM and CPU usage. However, opening up the corresponding address leads me to an empty browser page. I've tried this with and without `sudo` and even using a specific IP address and port (`--server-only --ip-address 127.0.0.1 -P 8080`).
```
$ sudo anvi-display-metabolism -c contigs.db -p SAMPLES-MERGED/PROFILE.db -C CONCOCT -B metabolism_bins.txt --server-only --ip-address 127.0.0.1 -P 8080
Password:
Modules database .............................: An existing database,
                                                /Users/andre/miniconda3/envs/anvio-7/lib/python3.6/site-packages/anvio/data/misc/KEGG/MODULES.db,
                                                has been loaded.
Kegg Modules .................................: 443 found

CITATION
===============================================
Anvi'o will reconstruct metabolism for modules in the KEGG MODULE database, as
described in Muto et al (doi:10.1021/ci3005379). When you publish your findings,
please do not forget to properly credit this work.


Server address ...............................: http://127.0.0.1:8080

* When you are ready, press CTRL+C once to terminate the server and go back to the
command line.

^C
* The server is being terminated...
```

Anything I might be doing wrong here/not remembering? Something that has changed with BigSur too? Any help will be appreciated!

Thanks,
Andre

**Comment by meren** [comment]
Hey @GeoMicroSoares, can you please run the server with `--debug` flag and see if you catch something in your terminal?

**Comment by meren** [comment]
You can also take a look at the JavaScript console on your browser to see if the interactive interface is complaining about something.

**Comment by GeoMicroSoares** [comment]
Thanks for the quick reply @meren - a couple interesting things I think!

So from the JavaScript console what I get is
```
Failed to load resource: the server responded with a status of 404 (Not Found)
:8080/data/get_metabolism:1 Failed to load resource: the server responded with a status of 500 (Internal Server Error)
metabolism.html?rand=290d2814:117 Uncaught TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at metabolism.html?rand=290d2814:117
    at Object.<anonymous> (d3.v4.js?rand=b326d1e3ee18d94cea78481359229bbe:11497)
    at Dispatch.call (d3.v4.js?rand=b326d1e3ee18d94cea78481359229bbe:792)
    at XMLHttpRequest.respond (d3.v4.js?rand=b326d1e3ee18d94cea78481359229bbe:11397)
```

And from the first few lines of the output of the command running `--debug`, I see the following:
```
127.0.0.1 - - [18/Feb/2021:23:49:49 +0200] "GET / HTTP/1.1" 303 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.3 Safari/605.1.15"
127.0.0.1 - - [18/Feb/2021:23:49:49 +0200] "GET /app/metabolism.html?rand=02912ad8 HTTP/1.1" 200 5177 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.3 Safari/605.1.15"
127.0.0.1 - - [18/Feb/2021:23:49:49 +0200] "GET /app/js/utils.js HTTP/1.1" 200 25348 "http://0.0.0.0:8080/app/metabolism.html?rand=f3333991" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.3 Safari/605.1.15"
127.0.0.1 - - [18/Feb/2021:23:49:49 +0200] "GET /app/lib/d3.js/d3.min.js HTTP/1.1" 200 151145 "http://0.0.0.0:8080/app/metabolism.html?rand=f3333991" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.3 Safari/605.1.15"
127.0.0.1 - - [18/Feb/2021:23:49:49 +0200] "GET /favicon.ico HTTP/1.1" 404 740 "http://0.0.0.0:8080/app/metabolism.html?rand=f3333991" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.3 Safari/605.1.15"
127.0.0.1 - - [18/Feb/2021:23:49:49 +0200] "GET /app/lib/jquery/dist/jquery.min.js?rand=7713f77702d16a33dffebeb6351f1580 HTTP/1.1" 200 95992 "http://0.0.0.0:8080/app/metabolism.html?rand=02912ad8" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.3 Safari/605.1.15"
127.0.0.1 - - [18/Feb/2021:23:49:49 +0200] "GET /app/lib/d3.js/d3.min.js HTTP/1.1" 200 151145 "http://0.0.0.0:8080/app/metabolism.html?rand=02912ad8" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.3 Safari/605.1.15"
127.0.0.1 - - [18/Feb/2021:23:49:49 +0200] "GET /app/js/utils.js HTTP/1.1" 200 25348 "http://0.0.0.0:8080/app/metabolism.html?rand=02912ad8" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.3 Safari/605.1.15"
127.0.0.1 - - [18/Feb/2021:23:49:49 +0200] "GET /app/lib/bootstrap/dist/js/bootstrap.min.js?rand=c1b1ff2548ca038077b363bbd52b72dd HTTP/1.1" 200 36816 "http://0.0.0.0:8080/app/metabolism.html?rand=02912ad8" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.3 Safari/605.1.15"
127.0.0.1 - - [18/Feb/2021:23:49:49 +0200] "GET /app/lib/bootstrap/dist/css/bootstrap.min.css?rand=c811b3dcbe56ec026d25ba08763774ac HTTP/1.1" 200 122540 "http://0.0.0.0:8080/app/metabolism.html?rand=02912ad8" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.3 Safari/605.1.15"
127.0.0.1 - - [18/Feb/2021:23:49:50 +0200] "GET /favicon.ico HTTP/1.1" 404 740 "http://0.0.0.0:8080/app/metabolism.html?rand=02912ad8" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.3 Safari/605.1.15"
```

Does that give you any idea of what's happening?

**Comment by meren** [comment]
@ivagljiva, did we not retire `anvi-display-metabolism`? Is it why this is happening?

**Comment by ivagljiva** [comment]
@GeoMicroSoares, sorry this is happening :( I didn't spend too much time working on this program so it is far from polished, sadly.

@meren If I recall correctly, we decided to just leave this program alone in case someone wanted to use it. I don't think I took anything related to it out of the codebase. It is theoretically possible that some of the later modifications I made to `kegg.py` affected the metabolism data passed to `anvi-display-metabolism`, but it doesn't look like that is what is happening here since the metabolism estimation part seems to run smoothly. 

I will look into this further and see if I can figure out what is going on :)

**Comment by ivagljiva** [comment]
Hmm. I tested this on my computer and it is working fine. 😕 I am on OS Catalina so it may very well be an issue with Big Sur. 

For records' sake, this is what I tried:
```
anvi-display-metabolism -c INFANT-GUT-TUTORIAL/CONTIGS.db -p INFANT-GUT-TUTORIAL/PROFILE.db -C TEST_6_BINS -B test_bin_ids.txt
```
And this is a screenshot of what the display looked like:
![image](https://user-images.githubusercontent.com/10360586/108444764-d996f100-7220-11eb-9379-82df1dbbd012.png)

I'll see if I can reproduce the error on another computer that is running Big Sur.

**Comment by GeoMicroSoares** [comment]
Thanks for this @ivagljiva, trying to replicate that in my system and will get back to you.

**Comment by GeoMicroSoares** [comment]
Yeah, just ran this with the INFANT-GUT-TUTORIAL dataset and got a similar warning (below), **but** was able to visualise my results on the browser (Chrome). Not sure what's happening here then as I ran this and my dataset with the same KEGG version using `anvi-run-kegg-kofams`.

```
Failed to load resource: the server responded with a status of 404 (Not Found)
```

**Comment by ivagljiva** [comment]
Sorry for the delay, @GeoMicroSoares. I set up anvi'o `v7` on an old laptop running Big Sur so I could see if I get the same error as you on that OS, but sadly it is a very lame laptop and running `anvi-run-kegg-kofams` is taking literally forever.

> got a similar warning (below), but was able to visualise my results on the browser

This is weird on multiple levels 😕: 
1) why do you get an error but are still able to see the interactive heatmap? 
and 2) why should this work on one dataset but not another?

Still waiting for my laptop to do its thing so I can test 1), but in the meantime maybe you can try something to test 2). I wonder, if you run `anvi-estimate-metabolism` on your dataset, do you get any errors? Maybe something is breaking at that stage and `anvi-display-metabolism` is just not smart enough to tell us about it.

**Comment by GeoMicroSoares** [comment]
Yep, keep wondering about why this is happening. No errors from what I remember running `anvi-estimate-metabolism` or `anvi-run-kegg-kofams`... Also tried reducing the number of bins I was visualizing with `anvi-display-metabolism` and even tried waiting for longer times (15min) for 9, 3 and 1 bins and same old empty browser...

**Comment by ivagljiva** [comment]
@GeoMicroSoares It is good to know that `anvi-estimate-metabolism` and `anvi-run-kegg-kofams` are running fine on your dataset, that means that it is an issue specific to `anvi-display-metabolism`, at least.

I finally got the chance to test this (again using the infant gut dataset) on Big Sur and I had no issues... I didn't get the 404 warning message that you did when you ran it on the infant gut dataset, plus the heatmap showed up as expected (I'm also on Chrome so it's probably not a browser problem). So I am not sure I'm going to be able to fix whatever is causing you to have the 404 warning on infant gut, but at least it is working for you despite that warning. 

But perhaps there is still hope for getting it working on your dataset. One major difference I noticed during my test was that I only had a single `GET` line in my `--debug` output:
```
127.0.0.1 - - [22/Feb/2021:16:46:43 -0500] "GET /data/get_metabolism HTTP/1.1" 200 568955 "http://0.0.0.0:8080/app/metabolism.html?rand=3159410c" "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_1_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36"
```
And it's for `/data/get_metabolism`, which is where you got that `Failed to load resource` error for your own dataset. I am guessing there may be something, like a data type, unique to your dataset which is causing the failure. Therefore, if you feel comfortable, you could send me your dataset and I could try it out on my system to see if I can pinpoint what that is. :) 

In the meantime, since `anvi-estimate-metabolism` is working, you could always try generating a heatmap in `anvi-interactive`, using the strategy outlined in the Infant Gut Tutorial [here](https://merenlab.org/tutorials/infant-gut/#estimating-metabolism-in-the-enterococcus-genomes). It will be a much better-looking and more customizable heat map than `anvi-display-metabolism` could give you, anyway :)
