### ISSUE TITLE
Add functional annotations to .gffs exported with anvi-get-sequences-for-gene-calls

### ISSUE THREAD

**Issue by IsabelFE** [merenlab/anvio#1685]
## The need

When using `anvi-get-sequences-for-gene-calls  --export-gff3` the output .gff files contain gene calls information (start and end positions for each gene) but they lack the functional annotation.

This is, the output looks like this:
```
c_000000000001	.	CDS	3654	4955	.	-	.	ID=ATCC_51524___1
c_000000000001	.	CDS	5083	6612	.	-	.	ID=ATCC_51524___2
c_000000000001	.	CDS	6612	7370	.	-	.	ID=ATCC_51524___3
c_000000000001	.	CDS	7460	8644	.	-	.	ID=ATCC_51524___4
c_000000000001	.	CDS	8772	9767	.	-	.	ID=ATCC_51524___5
```

Instead of this:
```
c_000000000001	.	CDS	3654	4955	.	-	.	ID=ATCC_51524___1;eC_number=4.2.1.11;Name=eno;db_xref=COG:COG0148;gene=eno;inference=ab initio prediction:Prodigal:002006,similar to AA sequence:UniProtKB:O69174;locus_tag=FLLBPJGF_00001;product=Enolase
c_000000000001	.	CDS	5083	6612	.	-	.	ID=ATCC_51524___2;eC_number=5.4.2.12;Name=gpmI;gene=gpmI;inference=ab initio prediction:Prodigal:002006,similar to AA sequence:UniProtKB:Q9X519;locus_tag=FLLBPJGF_00002;product=2%2C3-bisphosphoglycerate-independent phosphoglycerate mutase
c_000000000001	.	CDS	6612	7370	.	-	.	ID=ATCC_51524___3;eC_number=5.3.1.1;Name=tpiA_1;db_xref=COG:COG0149;gene=tpiA_1;inference=ab initio prediction:Prodigal:002006,similar to AA sequence:UniProtKB:Q04JH4;locus_tag=FLLBPJGF_00003;product=Triosephosphate isomerase
c_000000000001	.	CDS	7460	8644	.	-	.	ID=ATCC_51524___4;eC_number=2.7.2.3;Name=pgk;gene=pgk;inference=ab initio prediction:Prodigal:002006,similar to AA sequence:UniProtKB:Q6GIL7;locus_tag=FLLBPJGF_00004;product=Phosphoglycerate kinase
c_000000000001	.	CDS	8772	9767	.	-	.	ID=ATCC_51524___5;eC_number=1.2.1.12;Name=gap;gene=gap;inference=ab initio prediction:Prodigal:002006,similar to AA sequence:UniProtKB:Q59309;locus_tag=FLLBPJGF_00005;product=Glyceraldehyde-3-phosphate dehydrogenase
```
## The solution

Add another flag to `anvi-get-sequences-for-gene-calls  --export-gff3` that lets you add some/all of the functional annotations (COG, KEEG, Prokka...) present on your contigs-db to the .gff output.

## Beneficiaries

As indicated in https://github.com/labgem/PPanGGOLiN/issues/56 this allows for more informative outputs when importing Anvi'o clustering into PPanGGOLiN.

Thanks!!

**Comment by meren** [comment]
Hi @IsabelFE,

Thanks for this feature request. I finally was able to take a look at this. Unfortunately dealing with GFF format makes one doubt themselves with similar questions that may come to one's mind when they're standing in front of Stonehenge: what was wrong with our ancestors, and why am I here looking at this ancient and absolutely useless monument of self-torture?

So, trying to add gene functions to the GFF output didn't go as productive or as fun as it could've been, BUT I did something via 2f15f4f5016a0963c634b9d032a3b489c5b4e5e7 and I'm hoping that you could test it and let me know what you think.

Please `git pull` from the active branch to have the latest changes.


Thank you for your patience,

**Comment by IsabelFE** [comment]
Hello @meren,

Sorry about the trip to decipher the ancient runes of our ancestors... 😬

I exported the gffs and they look good:

```
c_000000000001	.	CDS	3654	4955	.	-	.	ID=ATCC_51524___1;Name=COG0148;db_xref=COG20:COG0148;product=Enolase (Eno) (PDB:1E9I)
c_000000000001	.	CDS	5083	6612	.	-	.	ID=ATCC_51524___2;Name=COG0696;db_xref=COG20:COG0696;product=Phosphoglycerate mutase (BPG-independent), AlkP superfamily (GpmI) (PDB:1EJJ)
c_000000000001	.	CDS	6612	7370	.	-	.	ID=ATCC_51524___3;Name=COG0149;db_xref=COG20:COG0149;product=Triosephosphate isomerase (TpiA) (PDB:1HG3)
c_000000000001	.	CDS	7460	8644	.	-	.	ID=ATCC_51524___4;Name=COG0126;db_xref=COG20:COG0126;product=3-phosphoglycerate kinase (Pgk) (PDB:13PK)
c_000000000001	.	CDS	8772	9767	.	-	.	ID=ATCC_51524___5;Name=COG0057;db_xref=COG20:COG0057;product=Glyceraldehyde-3-phosphate dehydrogenase/erythrose-4-phosphate dehydrogenase (GapA) (PDB:3ZDF)
c
```

I also took them to the PPanGGOLiN pipeline and everything worked fine. The annotation info was properly incorporated into the gephi output. You can see in the screenshot how now the COG names and the products have been updated properly:

![Screen Shot 2021-03-04 at 09 51 24](https://user-images.githubusercontent.com/7309296/109989340-67211900-7cd6-11eb-9cc8-325dc8b68892.png)

This allows now to explore the PPanGGOLiN graph with more useful annotations and easily go back and forward with Anvi'o based on the GCs IDs. I really hope that someone else finds this useful too 

Thanks for your help! 🙏🏻

**Comment by meren** [comment]
Hey @IsabelFE, that's great news. Thanks for reporting back!

I meant to ask you, actually, would you be interested in writing a blog post so people can see the utility of your workflow and they can also apply to their data? It would be an amazing resource both for the users of anvi'o and PPanGGOLiN :)

I am sure you have a million things to do, but if you were to be interested in doing it, there are some examples here, and I promise to help you with formatting and editorial needs:

https://merenlab.org/people/#forever

It would simply be a step-by-step tutorial preferably using a set of genomes you are interested in or publicly available (it would also help us to reproduce what you've done and perhaps find ways to improve anvi'o to do better with some steps of your analysis).


Best,

**Comment by IsabelFE** [comment]
Sure! Happy to write a blog post tutorial about the Anvi'o-PPanGGOLiN pipeline.

I still need to play a little bit more with the genomes and import the partitions from PPanGGOLiN back into Anvi'o. We will be submitting soon a paper with some new _Dolosigranulum pigrum_ genomes (in the next 1-2 months) and it will include this analysis. Since the genomes are still not publicly available, what do you think if I put together the blog post to be published as we submit the paper? We will be uploading a biorxiv as we submit the paper, so the genomes will be available at that time. I am working on methods and final figures for this publication, so drafting the blog post as I do that should be easy.

Best,

Isabel

**Comment by meren** [comment]
Thank you very much for your willingness to help the community follow your footsteps, @IsabelFE. That sounds like a great plan :) Please feel free to reach out to me if there is anything I can help.
