### ISSUE TITLE
IndexError: list index out of range while running anvi-setup-ncbi-cogs.

### ISSUE THREAD

**Issue by dineshkumarsrk** [merenlab/anvio#1686]
I have installed anvi'o in my miniconda3 (Ubuntu 18.04 LTS) laptop computer. I had successfully executed `anvi-self-test` and obtained proper output. I intended to do pan-genome (Included whole and draft genome) analysis for which I suppose to make `contig.db` and `annotate` the same. The `anvi-setup-ncbi-cogs` always end up with an error as follows,
```
(anvio-7) dinesh@dinesh7k:~$ anvi-setup-ncbi-cogs
COG version ..................................: COG20
COG data source ..............................: The anvi'o default.
COG base directory ...........................: /home/dinesh/miniconda3/envs/anvio-7/lib/python3.6/site-packages/anvio/data/misc/COG

WARNING
===============================================
This program will first check whether you have all the raw files, and then will
attempt to regenerate everything that is necessary from them.

Press ENTER to continue, or press CTRL + C to cancel...

Downloaded successfully ......................: /home/dinesh/miniconda3/envs/anvio-7/lib/python3.6/site-packages/anvio/data/misc/COG/COG20/RAW_DATA_FROM_NCBI/cog-20.cog.csv
Downloaded successfully ......................: /home/dinesh/miniconda3/envs/anvio-7/lib/python3.6/site-packages/anvio/data/misc/COG/COG20/RAW_DATA_FROM_NCBI/cog-20.def.tab
Downloaded successfully ......................: /home/dinesh/miniconda3/envs/anvio-7/lib/python3.6/site-packages/anvio/data/misc/COG/COG20/RAW_DATA_FROM_NCBI/fun-20.tab
Downloaded successfully ......................: /home/dinesh/miniconda3/envs/anvio-7/lib/python3.6/site-packages/anvio/data/misc/COG/COG20/RAW_DATA_FROM_NCBI/cog-20.fa.gz
Traceback (most recent call last):
  File "/home/dinesh/miniconda3/envs/anvio-7/bin/anvi-setup-ncbi-cogs", line 47, in <module>
    setup.create()
  File "/home/dinesh/miniconda3/envs/anvio-7/lib/python3.6/site-packages/anvio/cogs.py", line 617, in create
    self.setup_raw_data()
  File "/home/dinesh/miniconda3/envs/anvio-7/lib/python3.6/site-packages/anvio/cogs.py", line 831, in setup_raw_data
    self.files[file_name]['func'](file_path, J(self.COG_data_dir, self.files[file_name]['formatted_file_name']))
  File "/home/dinesh/miniconda3/envs/anvio-7/lib/python3.6/site-packages/anvio/cogs.py", line 659, in format_p_id_to_cog_id_cPickle
    p_id = fields[2].replace('.', '_')
IndexError: list index out of range
```
I referred issue section #1183 and followed all the instruction mentioned there (including `--reset` and `--just-do-it`) but still getting the same error as mentioned above. 
For your kind reference, my conda environment is shown below,
```
(anvio-7) dinesh@dinesh7k:~$ conda env list
# conda environments:
#
base                     /home/dinesh/miniconda3
anvio-7               *  /home/dinesh/miniconda3/envs/anvio-7
```
Please help me to fix this issue.

**Comment by avlisaidualc** [comment]
Hello! I am having the exact same issue with anvio-7 in anvi-setup-ncbi-cogs command. Even after I tried to solve it with the same instructions --reset and --just-do-it, the same error is still occurring:



(anvio-7) claudiasilva@x86_64-apple-darwin13 1_megahit % anvi-self-test --version
Anvi'o .......................................: hope (v7)

Profile database .............................: 35
Contigs database .............................: 20
Pan database .................................: 14
Genome data storage ..........................: 7
Auxiliary data storage .......................: 2
Structure database ...........................: 2
Metabolic modules database ...................: 2
tRNA-seq database ............................: 1

(anvio-7) claudiasilva@x86_64-apple-darwin13 1_megahit % anvi-setup-ncbi-cogs
COG version ..................................: COG20
COG data source ..............................: The anvi'o default.
COG base directory ...........................: /Users/claudiasilva/opt/anaconda3/envs/anvio-7/lib/python3.6/site-packages/anvio/data/misc/COG

WARNING
===============================================
This program will first check whether you have all the raw files, and then will
attempt to regenerate everything that is necessary from them.

Press ENTER to continue, or press CTRL + C to cancel...

                                                                                                                             
Config Error: Something went wrong while decompressing the downloaded file :/ It is likely    
              that the download failed and only part of the file was downloaded. If you would 
              like to try again, please run the setup command with the flag `--reset`. Here is
              what the downstream library said: 'Error -3 while decompressing data: invalid   
              literal/length code'.                                                           


Is anybody else having the same problem? Can you help me/us? Thanks

**Comment by dineshkumarsrk** [comment]
@avlisaidualc , 26 days have passed since I posted this issue. However, till now there is no suggestion or help received from the anvio's creator group. Despite being a cache tool, I could not use it for my study due to this issue. Looking forward for the help from the creator end.

**Comment by meren** [comment]
Dear @dineshkumarsrk, @avlisaidualc,

Unfortunately we are unable to reproduce this error on our end, so we don't know what to suggest or how to help.

Many people use this program without any problem, so probably it is related to your end.


Best wishes,

**Comment by ivagljiva** [comment]
I just wanted to mention that this issue has been brought up before (see [this comment](https://github.com/merenlab/anvio/issues/1647#issuecomment-765910171) in issue #1647) so you can read through that issue for a larger discussion. :)

In fact, another user suggested a fix that worked for them [here](https://github.com/merenlab/anvio/issues/1647#issuecomment-794010298), maybe that would work for you two.

**Comment by chasemc** [comment]
Same problem. Reran 3 times. Worked on third try

**Comment by meren** [comment]
Absolutely infuriating. The worst part is I haven't run into this issue even once in my many tries to reproduce it. 

Did you also get the following error, @chasemc?

```
p_id = fields[2].replace('.', '_')
```

Thanks,

**Comment by dineshkumarsrk** [comment]
@meren , Could you please run it on ubuntu 16.04 LTS or 18.04 LTS version, so that you can reproduce our issue.
@chasemc , I tried more than 30 times but end up with the same error, now I am using `roary pipeline` for my analysis despite intended to use `anvi`.

**Comment by chasemc** [comment]
@meren  Not sure, and computer's full speed ahead on later analyses. I can try again later (not sure where anvio stores logs?)

I'm assuming it is something with the download? In another pipeline I'd consistently get like 5 /1000 downloads from the NCBI that wouldn't pass md5sum

  
@dineshkumarsrk did you try using the `--reset` flag

**Comment by meren** [comment]
>  I tried more than 30 times but end up with the same error, now I am using roary pipeline for my analysis despite intended to use anvi.

NCBI COGs are not necessary for pangenomics in anvi'o so there was nothing stopping you to be able to do everything, but Roary is as good, so you are in good hands.

> Not sure, and computer's full speed ahead on later analyses

No worries, then, @chasemc, it is not that critical. Probably the solution is to have our own anvi'o mirrors of the COG data :/

**Comment by meren** [comment]
Anyone who is willing to help with this error can switch to the active branch (explained [here](https://merenlab.org/2016/06/26/installation-v2/#5-follow-the-active-development-youre-a-wizard-arry)), run the following command,

```
anvi-setup-ncbi-cogs --reset
```

And follow the instructions in the error message to send necessary files to us.

**Comment by razz1618** [comment]
This error is solely due network issue and not related to Anvios.  Anyone facing the same issue, 

1. Delete the CONDA/envs/anvio/data/misc/COG/ directory.
 2. Download the COG files with some alternate download manager and push those files in  
CONDA/envs/anvio/data/misc/COG/COG20/RAW_DATA_FROM_NCBI/

Be sure to check the file size and files by opening with a compatible file reader (even sometimes successfully downloaded files are corrupted), or if cannot download the files change the internet provider (which I had to do by downloading through my cell phone internet provider) 

3. Rerun,
anvi-setup-ncbi-cogs.
