### ISSUE TITLE
third party tools documentation vs conda recipe

### ISSUE THREAD

**Issue by EricDeveaud** [merenlab/anvio#1693]
I'm packaging anvi'o V7  from https://github.com/merenlab/anvio/archive/v7.tar.gz for our cluster

I have some question//remarks.

1) third party tools installation instruction list some tools (yes I've read that the list may be not complete) while conda "Slower but reliable option" installation isntruction lists some tools 
there is some missing tools in third party tools documentation

here's a comparaisoon of both 
```
  Thirdparty    |  conda      | version                    | used in
 documentatioin |  recipe     |  info                      |
----------------+-------------+----------------------------+---------------------------------------
  samtools      | samtools    | >=1.3.1                    |
  Prodigal      | prodigal    | >=2.6.2                    |
  HMMER         | hmmer       | 3.2.1                      |
  SQLite        | sqlite      | >=3.31.1                   |
  FastTree      | fasttree    | 2.1.10                     |
  Centrifuge    | centrifuge  | v1.0.1-beta-27-g30e3f06ec3 |
  MCL           | mcl         | 14-137                     |
  egnogg-mapper |             | 0.12.6                     | anvio/drivers/emapper.py
                |             |                            | sandbox/anvi-script-run-eggnog-mapper
  muscle        | muscle      | 3.8.31                     |
  FAMSA         |             | 1.2.1                      | anvio/drivers/famsa.py
  DSSP          |             |                            | anvio/structureops.py
  MODELLER      |             |                            |
                | diamond     |                            |
                | blast       |                            |
                | megahit     |                            |
                | spades      |                            |
                | bowtie2     |                            |
                | bwa         |                            |
                | trimal      |                            |
                | iqtree      |                            |
                | trnascan-se |                            |
                | r-base (R)  |                            |
```

##-------------------------------------------------------------------##

2)  bioconda-recipe https://github.com/bioconda/bioconda-recipes/blob/master/recipes/anvio/meta.yaml document `fastani` as requirement. 
is `FastANI` required ??, I would bet for no as  `drivers.fastani` is not imported by any file

##-------------------------------------------------------------------##

3) some dirvers uses programs that are not documented

`anvio/drivers/binsanity.py` -> `BinSanity (https://github.com/edgraham/BinSanity)

`anvio/drivers/dastool.py` -> `DAS_Tool` (https://github.com/cmks/DAS_Tool)

`anvio/drivers/concoct.py` -> `concoct` 

`anvio/drivers/maxbin2.py` -> `run_MaxBin.pl` (https://sourceforge.net/projects/maxbin)

`anvio/drivers/metabat2.py` -> metabat2 (https://bitbucket.org/berkeleylab/metabat)

`anvio/drivers/sourmash.py` -> sourmash (https://github.com/dib-lab/sourmash)

but as for fastany they are not imported anywhere, Am I right ?

##-------------------------------------------------------------------##

4) regarding recommended //mandatory version of tools it will be nice to have the ones taht does not have version info listed here to be documented.

##-------------------------------------------------------------------##

5) seems there is 2 R libraries missing in the conda recipe. 
`anvi-script-gen_stats_for_single_copy_genes.R` requires following r libs that are not documented in recipe

```
gtools
gridExtra
```
##-------------------------------------------------------------------##

FYI:  I installed anvi'o with the following external tools
```
R/3.6.2 
prodigal/2.6.3 
mcl/14-137 
muscle/3.8.31 
hmmer/3.2.1 
diamond/2.0.4 
blast+/2.10.0 
megahit/1.2.9 
SPAdes/3.15.0 
bowtie2/2.3.5.1 
bwa/0.7.17 
samtools/1.10 
centrifuge/1.0.4-beta 
trimal/1.4.1 
IQ-TREE/2.0.6 
tRNAscan-SE/2.0.7 
FastTree/2.1.11 
SQLite 
FAMSA/1.6.2 
eggnog-mapper/1.0.3 
dssp/2.2.1 
SQLite/3.31.0 
```
and `anvi-self-test` pass successfully

best regards 

Eric

**Comment by EricDeveaud** [comment]
about point 3



seems at least `concot` `metabat2`, `maxbin`, `dastool` and `binsanity` are still needed based on `anvi-cluster-contigs -h`

```
[gensoft@c1d61c16d94c anvio-7]$ anvi-cluster-contigs -h 
usage: anvi-cluster-contigs [-h] -p PROFILE_DB -c CONTIGS_DB -C COLLECTION_NAME
                            --driver DRIVER [-T NUM_THREADS] [--log-file FILE_PATH]
                            [--just-do-it]

A program to cluster items in a merged anvi'o profile using automatic binning
algorithms

optional arguments:
  -h, --help            show this help message and exit
  -p PROFILE_DB, --profile-db PROFILE_DB
                        Anvi'o profile database
  -c CONTIGS_DB, --contigs-db CONTIGS_DB
                        Anvi'o contigs database generated by 'anvi-gen-contigs-
                        database'
  -C COLLECTION_NAME, --collection-name COLLECTION_NAME
                        Collection name.
  --driver DRIVER       Automatic binning drivers. Available options 'concoct,
                        metabat2, maxbin2, dastool, binsanity'.
  -T NUM_THREADS, --num-threads NUM_THREADS
                        Maximum number of threads to use for multithreading whenever
                        possible. Very conservatively, the default is 1. It is a good
                        idea to not exceed the number of CPUs / cores on your system.
                        Plus, please be careful with this option if you are running
                        your commands on a SGE --if you are clusterizing your runs, and
                        asking for multiple threads to use, you may deplete your
                        resources very fast.
  --log-file FILE_PATH  File path to store debug/output messages.
  --just-do-it          Don't bother me with questions or warnings, just do it.

CONCOCT [NOT FOUND]

METABAT2 [NOT FOUND]

MAXBIN2 [NOT FOUND]

DASTOOL [NOT FOUND]

BINSANITY [NOT FOUND]
```

Eric

**Comment by EricDeveaud** [comment]
Hello, 

so to be sure I understand correctly. One can say:
mandatory third party programs are:
```
dssp 
modeller
samtools
prodigal
hmmer 
fasttree
centrifuge
mcl
muscle
diamond
blast
megahit
spades
bowtie2
bwa
trimal
iqtree
trnascan-se
R
```

optional // recommended
```
fastani
eggnog-mapper
concot
metabat2
maxbin
dastool
binsanity
famsa
sourmash 
```

Am I right ? 

regards

Eric

**Comment by meren** [comment]
I'd say for anvi'o to operate in its most basic functionality (ability to create a contigs database, do profiling, run HMMs, run single-copy core gene taxonomy, compute pangenomes, and perform phylogenomics), the following are needed and everything else will be dependent on a particular analysis:

```
samtools
prodigal
hmmer 
fasttree
mcl
muscle
diamond
trnascan-se
R
```

For instance I didn't include here `Bowtie2` or `BWA`, or any of the assemblers. Because it is on the user to decide how should they assemble their contigs if assembly is needed, or how to recruit reads from their long or short reads. Anvi'o will work with whatever BAM files the user has produced.


Best,

**Comment by EricDeveaud** [comment]
thanks for that  information. you may have guessed that I'm not a biological scientist ;-)

I just want to be sure to include all required tools necessary to provide a working installation of anvi'o to our users. 
and provide them with the auxiliary tools that they may requires 
we uses the module environement on our cluster so I want to be sure that when they 'module load nvio' they will alos module load the core requirement for third party tools
I will let them 'module load' individual tools based on their needs.

thanks gain.

Eric

**Comment by meren** [comment]
In that case I would probably consider associating all modules for third-party apps anvi'o uses with the anvi'o module for convenience. But of course you know your system and users best.

Best wishes,
