### ISSUE TITLE
anvi-self-test --no-interactive :: does execute anvi-interactive

### ISSUE THREAD

**Issue by EricDeveaud** [merenlab/anvio#1698]
Hello.

when run with `--no-interactive` option `anvi-self-test` run some interactive commands, at least anvi-interactive is run.

should'nt be ignored ? 

regards

Eric

**Comment by meren** [comment]
It should execute `anvi-interactive`, but do not pop-up any interactive interface.

Basically `anvi-self-test` performs a 'dry run' for `anvi-interactive` when `--no-interactive` flag is set (which should also apply to any program that provides [`interactive`](https://merenlab.org/software/anvio/help/main/artifacts/interactive/)).

If anvi'o is not trying to show you an interactive interface by opening a browser, `--no-interactive` did its job :)

**Comment by EricDeveaud** [comment]
ok
