### ISSUE TITLE
Anvio doesnt display pangenomic tree

### ISSUE THREAD

**Issue by braddmg** [merenlab/anvio#1700]
Hi, Im trying to display my pangenomic analysis, and all it is right but I don't know what I don't have a gene tree like the tutorial. I attach a picture, someone know how to add the cladogram?
![anvio problem](https://user-images.githubusercontent.com/56454173/111827881-0dad1280-88b0-11eb-8da8-85d87cdc4adf.png)

**Comment by ivagljiva** [comment]
Hi @braddmg, the inner dendrogram is supposed to be generated automatically without you having to do anything. However, I can see from your screenshot that you have 21,846 "splits" (in this context, those are gene clusters), and this may have been too large a number for anvi'o to attempt clustering. Did you see any warnings about this on your terminal screen when you ran `anvi-display-pan`? 

Anyhow, if this is indeed the issue, one way to reduce the number of gene clusters in your pangenome is to play around with the `--minbit`, `--mcl-inflation`, and `--min-occurrence` parameters as described in the [tutorial](https://merenlab.org/2016/11/08/pangenomics-v2/#running-a-pangenome-analysis). You could try that.

**Comment by braddmg** [comment]
Thank you very much, that was the problem!
