### ISSUE TITLE
[BUG] anvi-estimate-metabolism error out after ~ 2 days

### ISSUE THREAD

**Issue by GeoMicroSoares** [merenlab/anvio#1703]
## Short description of the problem

Just got a weird error running `anvi-estimate-metabolism` after 2 days and I think after going through all the bins I requested. Seems to do with `coo_matrix()`.

## anvi'o version

Replace this text with the output of this command:

```
$ anvi-self-test --version
Anvi'o .......................................: hope (v7)

Profile database .............................: 35
Contigs database .............................: 20
Pan database .................................: 14
Genome data storage ..........................: 7
Auxiliary data storage .......................: 2
Structure database ...........................: 2
Metabolic modules database ...................: 2
tRNA-seq database ............................: 1
```

## System info

$ sw_vers
ProductName:	macOS
ProductVersion:	11.2.3
BuildVersion:	20D91

`anvi'o` installed via conda.

## Detailed description of the issue

Running `anvi-estimate-metabolism -i metabolism_bins_ext.txt -O test_metabolisms_matrix --matrix-format` and it errored out as follows after ca. 2 days of processing. Looks like a `pandas` dataframe wasn't built properly?

Let me know what else I can provide and thanks in advance!

```
✖ anvi-estimate-metabolism encountered an error after 2 days, 15:50:40.783353
Traceback (most recent call last):
  File "/Users/andre/miniconda3/envs/anvio-7/bin/anvi-estimate-metabolism", line 96, in <module>
    main(args)
  File "/Users/andre/miniconda3/envs/anvio-7/lib/python3.6/site-packages/anvio/terminal.py", line 843, in wrapper
    program_method(*args, **kwargs)
  File "/Users/andre/miniconda3/envs/anvio-7/bin/anvi-estimate-metabolism", line 39, in main
    m.estimate_metabolism()
  File "/Users/andre/miniconda3/envs/anvio-7/lib/python3.6/site-packages/anvio/kegg.py", line 3335, in estimate_metabolism
    self.store_metabolism_superdict_multi_matrix_format(kegg_metabolism_superdict_multi, ko_hits_superdict_multi)
  File "/Users/andre/miniconda3/envs/anvio-7/lib/python3.6/site-packages/anvio/kegg.py", line 3250, in store_metabolism_superdict_multi_matrix_format
    matrix = sps.coo_matrix((df[header], (df.index.labels[1], df.index.labels[0]))).todense().tolist()
AttributeError: 'MultiIndex' object has no attribute 'labels'
```

**Comment by ivagljiva** [comment]
Hi @GeoMicroSoares, 

Other people have encountered this issue before - see [here](https://anvio.slack.com/archives/C8SFMGYF3/p1610380278448900) on the anvi'o Slack. It seems to be related to having a newer version of pandas.

Try going back to an older version of pandas to fix it: `pip install pandas==0.25.1`

**Comment by ivagljiva** [comment]
Another alternative is to try the development version of anvi'o, since that one has been updated and now uses a different strategy for generating matrix format output.

**Comment by GeoMicroSoares** [comment]
Thanks for this @ivagljiva  - will give it a try with the older version of pandas and get back to you soon!

**Comment by ivagljiva** [comment]
hey @GeoMicroSoares , I was just wondering if you are still having this issue? :)

**Comment by GeoMicroSoares** [comment]
Wow. Sorry for not reporting back on this - rolling back pandas did it for me! Thanks again for this!

**Comment by ivagljiva** [comment]
Yay!! Glad to hear it :)
