### ISSUE TITLE
[BUG] Error adding MAGs scg-taxonomy using anvi-interactive --additional-layers 

### ISSUE THREAD

**Issue by fconstancias** [merenlab/anvio#1705]
Dear Anvi'o developers and users,

## Short description of the problem
I am trying to add taxonomic information as an external layer of the anvi-interactive visualisation.

## anvi'o version

```
Anvi'o .......................................: hope (v7)

Profile database .............................: 35
Contigs database .............................: 20
Pan database .................................: 14
Genome data storage ..........................: 7
Auxiliary data storage .......................: 2
Structure database ...........................: 2
Metabolic modules database ...................: 2
tRNA-seq database ............................: 1
```

## System info

I am using macOS Mojave 10.14.6 and installed anvio starting with an updated conda and following these [steps](https://merenlab.org/2016/06/26/installation-v2/). All tests were successful.

## Detailed description of the issue

I would like to add MAGs taxonomy or other information as an external layer of the anvi-interactive visualisation. As a start, I have generated SCG taxonomy using:

```
(anvio-7)$ anvi-estimate-scg-taxonomy -c ${CONT_DB} \
                           -p ${PROF_DB} \
                           -C MAGs_60_10 \
                           --compute-scg-coverages --output-file test.txt

less -S test.txt

bin_name        total_scgs      supporting_scgs t_domain        t_phylum        t_class t_order t_family
EZ_INH_MAG_00001        2       2       Bacteria        Proteobacteria  Gammaproteobacteria     Steroidobacter
EZ_INH_MAG_00002        19      16      Bacteria        Bacteroidota    Bacteroidia     Chitinophagales Chitin
EZ_INH_MAG_00003        11      3       Bacteria        Bacteroidota    Bacteroidia     Chitinophagales Chitin
EZ_INH_MAG_00004        13      13      Bacteria        Bacteroidota    Bacteroidia     Chitinophagales Chitin
EZ_INH_MAG_00005        9       3       Bacteria        Bacteroidota    Bacteroidia     Chitinophagales Chitin
EZ_INH_MAG_00006        21      21      Bacteria        Bacteroidota    Bacteroidia     Chitinophagales Sapros
```

I used then anvi-interactive to add this information using the `-A` argument

```
(anvio-7)$ anvi-interactive -p ${PROF_DB} \
                  -c ${CONT_DB} \
                  -C MAGs_60_10 \
                 --tree phylogenomic-tree.txt \
                  -A test.txt
```

Which lead to the follwoing error:

```
[29 Mar 21 16:33:37 Processing additional data to order items (to skip: --skip-auto-ordering)] for "taxa" ...Traceback (most recent call last):
  File "/Users/fconstan/miniconda3/envs/anvio-7/bin/anvi-interactive", line 122, in <module>
    d = interactive.Interactive(args)
  File "/Users/fconstan/miniconda3/envs/anvio-7/lib/python3.6/site-packages/anvio/interactive.py", line 283, in __init__
    self.gen_orders_for_items_based_on_additional_layers_data()
  File "/Users/fconstan/miniconda3/envs/anvio-7/lib/python3.6/site-packages/anvio/interactive.py", line 382, in gen_orders_for_items_based_on_additional_layers_data
    layer_type = utils.get_predicted_type_of_items_in_a_dict(self.items_additional_data_dict, layer)
  File "/Users/fconstan/miniconda3/envs/anvio-7/lib/python3.6/site-packages/anvio/utils.py", line 221, in get_predicted_type_of_items_in_a_dict
    items = [x[key] for x in d.values()]
  File "/Users/fconstan/miniconda3/envs/anvio-7/lib/python3.6/site-packages/anvio/utils.py", line 221, in <listcomp>
    items = [x[key] for x in d.values()]
KeyError: 'taxa'
```

adding ```--skip-auto-ordering``` did not help.

Not sure if it could be related but I had the same error related to my CONTIG.db and used the script to solve the issue [here] (https://github.com/merenlab/anvio/issues/1596)

I am able to run `anvi-interactive` without the `-A` argument.

```
(anvio-7)$ anvi-interactive -p ${PROF_DB} \
                  -c ${CONT_DB} \
                  -C MAGs_60_10 \
                 --tree phylogenomic-tree.txt 
```

## Files to reproduce

You can access the contig database [here](https://www.dropbox.com/s/osore09v0455dy9/Refined1-MAGs_contigs2021.db?dl=0)

As always, thanks for this amazing work.

Best,

Flo

**Comment by meren** [comment]
Hey @fconstancias, can you please send me privately Dropbox links for ALL the files involved in this analysis? Namely, `${PROF_DB}`, `${CONT_DB}`, `test.txt`, and `phylogenomic-tree.txt`?

**Comment by fconstancias** [comment]
thanks a lot @meren. 
Since omitting the phylogenomic-tree.txt led to the same error, I sent you a link to access the profile.db contig.db and the test.txt including the taxonomic file.

**Comment by meren** [comment]
Hey @fconstancias, 

Thanks for reporting this and making the files available to reproduce the problem. This was an interesting bug that must only happen very rarely to have survived this long in the codebase :)

I can see that you are not tracking the development branch, which means the solution to this bug that is in the code via 157cd9ef2988813671bded0f9caaaf12e274fd36 will not be available to you. Here is a little workaround if you would like to continue using the stable `v7`:

``` bash
# create a copy of the profile database
cp PROFILE.db PROFILE-FOR-COLLECTION-MODE.db

# remove the items additional data (since it will not be accessible to collection mode anyway)
anvi-delete-misc-data -t items -p PROFILE-FOR-COLLECTION-MODE.db --just-do-it

# run the same command with the new db
anvi-interactive -p PROFILE-FOR-COLLECTION-MODE.db -c Refined1-MAGs_contigs2021.db -A test.txt -C MAGs_60_10
```

This should solve your problem.

Thanks for the report!

Best,

---

PS: This is irrelevant, but I also realized that everything looked terrible when the anvi'o interactive interface showed up:

![image](https://user-images.githubusercontent.com/197307/112910709-99494f00-90b9-11eb-9cc3-ad65884e83da.png)

These values are shown as string because anvi'o failed to parse them as numeric data points. The reason to that is because your `test.txt` contains a lot of the string `None` in otherwise numeric columns. When I replaced `None` with empty cells (`:%s/None//g`), things looked better for the prettification step :)
