### ISSUE TITLE
Missing submodules in cloned repository prevents interactive interface to initiate

### ISSUE THREAD

**Issue by microDM** [merenlab/anvio#1717]
## Short description of the problem

anvio's interactive stuck at still loading

## anvi'o version

Anvi'o .......................................: hope (v7-dev)

Profile database .............................: 35
Contigs database .............................: 20
Pan database .................................: 14
Genome data storage ..........................: 7
Auxiliary data storage .......................: 2
Structure database ...........................: 2
Metabolic modules database ...................: 2
tRNA-seq database ............................: 1

```
anvi-self-test --version
```

## System info

I am using Pop OS 21.10. I have install anvio using conda

## Detailed description of the issue

I have used following command after following anvio protocol of pangenome

`anvi-display-pan -p Burkh_Pan-PAN.db -g Burk-GENOMES.db`

 ## The output is

`Interactive mode .............................: pan                                                                                                    
Functions found .............................................: COG20_FUNCTION, COG20_CATEGORY, COG20_PATHWAY                                           
Genomes storage .............................................: Initialized (storage hash: hash1a269245)                                                
Num genomes in storage ......................................: 143
Num genomes will be used ....................................: 143
Pan DB ......................................................: Initialized: Burkh_Pan-PAN.db (v. 14)
Gene cluster homogeneity estimates ..........................: Functional: [YES]; Geometric: [YES]; Combined: [YES]
                                                                                                                                                       
* Gene clusters are initialized for all 28145 gene clusters in the database.                                                                                                                                        
WARNING
==============================================================
This pangenome (which you gracefully named as 'Burkh_Pan') does not seem to have
any hierarchical clustering of gene clusters it contains. Maybe you skipped the
clustering step, maybe anvi'o skipped it on your behalf because you had too many
gene clusters or something. Anvi'o will do its best to recover from this
situation. But you will very likely not be able to see a hierarchical dendrogram
in the resulting display even if everything goes alright.. In some cases using a
parameter like `--min-occurrence 2`, which would reduce the number of gene
clusters by removing singletons that appear in only one genome can help solve
this issue and make your pangenome great again.                                                                                                                            
The server is up and running 🎉
WARNING
===============================================
If you are using OSX and if the server terminates prematurely before you can see
anything in your browser, try running the same command by putting 'sudo ' at the
beginning of it (you will be prompted to enter your password if sudo requires
super user credentials on your system). If your browser does not show up, try
manually entering the URL shown below into the address bar of your favorite
browser. *cough* CHROME *cough*.
Server address ...............................: http://0.0.0.0:8080
When you are ready, press CTRL+C once to terminate the server and go back to the
command line.`

## But there is not display in the browser. Its still loading

**Comment by matthewlawrenceklein** [comment]
Hi @microDM - Can you pop open your Chrome Developer Tools and check to see if any messaging is logged in the console?

**Comment by microDM** [comment]
Please see the log

`index.html:14 GET http://0.0.0.0:8080/app/lib/toastr/build/toastr.min.css?rand=3db0e264d7a4912025b573414a081585 net::ERR_ABORTED 404 (Not Found)
index.html:17 GET http://0.0.0.0:8080/app/lib/jquery/dist/jquery.min.js?rand=d96951f6bc5398c7073133eba60a1061 net::ERR_ABORTED 404 (Not Found)
index.html:18 GET http://0.0.0.0:8080/app/lib/jquery-ui/themes/base/all.css?rand=893f57eb7c78f874092c62b104e90956 net::ERR_ABORTED 404 (Not Found)
index.html:19 GET http://0.0.0.0:8080/app/lib/bootstrap/dist/css/bootstrap.min.css?rand=fb819d1b298fd5dd8d0a0c449770917b net::ERR_ABORTED 404 (Not Found)
index.html:20 GET http://0.0.0.0:8080/app/lib/bootstrap/dist/js/bootstrap.min.js?rand=81b995ecf67b5573285765f80e7ba654 net::ERR_ABORTED 404 (Not Found)
index.html:24 GET http://0.0.0.0:8080/app/lib/jquery-ui/ui/core.js?rand=af21d2b778490c30e49134b96f30b894 net::ERR_ABORTED 404 (Not Found)
index.html:25 GET http://0.0.0.0:8080/app/lib/jquery-ui/ui/widget.js?rand=c3d3c4bc1445e5f06f75f6891283db10 net::ERR_ABORTED 404 (Not Found)
index.html:26 GET http://0.0.0.0:8080/app/lib/jquery-ui/ui/mouse.js?rand=b823a16ac9789ef84fce5202eff4f644 net::ERR_ABORTED 404 (Not Found)
index.html:27 GET http://0.0.0.0:8080/app/lib/jquery-ui/ui/sortable.js?rand=dc3c3d5d0f03a9c01e4ddfece4cd9ccd net::ERR_ABORTED 404 (Not Found)
index.html:28 GET http://0.0.0.0:8080/app/lib/jquery-ui/ui/draggable.js?rand=9b40a131734686112d927f7491668dc1 net::ERR_ABORTED 404 (Not Found)
index.html:29 GET http://0.0.0.0:8080/app/lib/jquery-ui/ui/accordion.js?rand=9d4167c2769b49f659ceaf385b16c195 net::ERR_ABORTED 404 (Not Found)
index.html:30 GET http://0.0.0.0:8080/app/lib/jquery-ui/ui/resizable.js?rand=18cb767ac5f8a9175e69a51ad646dbf9 net::ERR_ABORTED 404 (Not Found)
index.html:31 GET http://0.0.0.0:8080/app/lib/jquery-ui/ui/button.js?rand=482d675a95439be4c10d1ed44bdb4895 net::ERR_ABORTED 404 (Not Found)
index.html:32 GET http://0.0.0.0:8080/app/lib/jquery-ui/ui/position.js?rand=886baa54d069ce97bcf09f8d71cc723b net::ERR_ABORTED 404 (Not Found)
index.html:34 GET http://0.0.0.0:8080/app/lib/randomColor/randomColor.js?rand=02c5bcccb6c09875a185ac32b3b019e4 net::ERR_ABORTED 404 (Not Found)
index.html:36 GET http://0.0.0.0:8080/app/lib/bootstrap-waitingfor/build/bootstrap-waitingfor.js?rand=cea0a3edcf81350b9a045222583050ab net::ERR_ABORTED 404 (Not Found)
index.html:37 GET http://0.0.0.0:8080/app/lib/toastr/build/toastr.min.js?rand=6d305d4ed4a8f4cc252f06b3d9d1f26b net::ERR_ABORTED 404 (Not Found)
index.html:38 GET http://0.0.0.0:8080/app/lib/JavaScript-MD5/js/md5.js?rand=dce96035bf828c4a3fb7b060339326dd net::ERR_ABORTED 404 (Not Found)
index.html:64 GET http://0.0.0.0:8080/app/lib/bootstrap-sortable/Scripts/bootstrap-sortable.js?rand=d5cd31491dc1b61c48d7597f4320aebe net::ERR_ABORTED 404 (Not Found)
index.html:65 GET http://0.0.0.0:8080/app/lib/bootstrap-sortable/Contents/bootstrap-sortable.css?rand=e3b9cb0d92af9241cd771e2a0df554c4 net::ERR_ABORTED 404 (Not Found)
index.html:68 GET http://0.0.0.0:8080/app/lib/marked/lib/marked.js?rand=76401133e60015fd0fbf71585bd70e8b net::ERR_ABORTED 404 (Not Found)
index.html:69 GET http://0.0.0.0:8080/app/lib/bootstrap-markdown/css/bootstrap-markdown.min.css?rand=8f623e71e245cd80d78cbd8b0d7c5c19 net::ERR_ABORTED 404 (Not Found)
index.html:70 GET http://0.0.0.0:8080/app/lib/bootstrap-markdown/js/bootstrap-markdown.js?rand=12eab1eaace6e5841f1dd075e5df4c6b net::ERR_ABORTED 404 (Not Found)
jquery-svgpan.js?rand=cba294eaf5741b5a40c768633b151ccd:118 Uncaught ReferenceError: jQuery is not defined
    at jquery-svgpan.js?rand=cba294eaf5741b5a40c768633b151ccd:118
    at jquery-svgpan.js?rand=cba294eaf5741b5a40c768633b151ccd:120
(anonymous) @ jquery-svgpan.js?rand=cba294eaf5741b5a40c768633b151ccd:118
(anonymous) @ jquery-svgpan.js?rand=cba294eaf5741b5a40c768633b151ccd:120
index.html:24 GET http://0.0.0.0:8080/app/lib/jquery-ui/ui/core.js?rand=af21d2b778490c30e49134b96f30b894 net::ERR_ABORTED 404 (Not Found)
index.html:25 GET http://0.0.0.0:8080/app/lib/jquery-ui/ui/widget.js?rand=c3d3c4bc1445e5f06f75f6891283db10 net::ERR_ABORTED 404 (Not Found)
index.html:26 GET http://0.0.0.0:8080/app/lib/jquery-ui/ui/mouse.js?rand=b823a16ac9789ef84fce5202eff4f644 net::ERR_ABORTED 404 (Not Found)
index.html:27 GET http://0.0.0.0:8080/app/lib/jquery-ui/ui/sortable.js?rand=dc3c3d5d0f03a9c01e4ddfece4cd9ccd net::ERR_ABORTED 404 (Not Found)
index.html:28 GET http://0.0.0.0:8080/app/lib/jquery-ui/ui/draggable.js?rand=9b40a131734686112d927f7491668dc1 net::ERR_ABORTED 404 (Not Found)
index.html:29 GET http://0.0.0.0:8080/app/lib/jquery-ui/ui/accordion.js?rand=9d4167c2769b49f659ceaf385b16c195 net::ERR_ABORTED 404 (Not Found)
index.html:30 GET http://0.0.0.0:8080/app/lib/jquery-ui/ui/resizable.js?rand=18cb767ac5f8a9175e69a51ad646dbf9 net::ERR_ABORTED 404 (Not Found)
index.html:31 GET http://0.0.0.0:8080/app/lib/jquery-ui/ui/button.js?rand=482d675a95439be4c10d1ed44bdb4895 net::ERR_ABORTED 404 (Not Found)
index.html:32 GET http://0.0.0.0:8080/app/lib/jquery-ui/ui/position.js?rand=886baa54d069ce97bcf09f8d71cc723b net::ERR_ABORTED 404 (Not Found)
colpick.js?rand=a0e68becc33e03306acdbafd2ca3b3fc:527 Uncaught ReferenceError: jQuery is not defined
    at colpick.js?rand=a0e68becc33e03306acdbafd2ca3b3fc:527
(anonymous) @ colpick.js?rand=a0e68becc33e03306acdbafd2ca3b3fc:527
index.html:34 GET http://0.0.0.0:8080/app/lib/randomColor/randomColor.js?rand=02c5bcccb6c09875a185ac32b3b019e4 net::ERR_ABORTED 404 (Not Found)
index.html:36 GET http://0.0.0.0:8080/app/lib/bootstrap-waitingfor/build/bootstrap-waitingfor.js?rand=cea0a3edcf81350b9a045222583050ab net::ERR_ABORTED 404 (Not Found)
index.html:37 GET http://0.0.0.0:8080/app/lib/toastr/build/toastr.min.js?rand=6d305d4ed4a8f4cc252f06b3d9d1f26b net::ERR_ABORTED 404 (Not Found)
index.html:38 GET http://0.0.0.0:8080/app/lib/JavaScript-MD5/js/md5.js?rand=dce96035bf828c4a3fb7b060339326dd net::ERR_ABORTED 404 (Not Found)
main.js?rand=3e9e4b77d017feb3f343bfbab693afaa:88 Uncaught ReferenceError: $ is not defined
    at main.js?rand=3e9e4b77d017feb3f343bfbab693afaa:88
(anonymous) @ main.js?rand=3e9e4b77d017feb3f343bfbab693afaa:88
mouse-events.js?rand=38d211a452b5db387ee8a3e5f40d429b:20 Uncaught ReferenceError: $ is not defined
    at mouse-events.js?rand=38d211a452b5db387ee8a3e5f40d429b:20
(anonymous) @ mouse-events.js?rand=38d211a452b5db387ee8a3e5f40d429b:20
multiple.js?rand=3e23e19295a61b88299843a1b2cbde85:3 Uncaught ReferenceError: $ is not defined
    at multiple.js?rand=3e23e19295a61b88299843a1b2cbde85:3
(anonymous) @ multiple.js?rand=3e23e19295a61b88299843a1b2cbde85:3
sample.js?rand=efdcf77e0e3779d24eda183d22bcdf61:32 Uncaught ReferenceError: $ is not defined
    at sample.js?rand=efdcf77e0e3779d24eda183d22bcdf61:32
(anonymous) @ sample.js?rand=efdcf77e0e3779d24eda183d22bcdf61:32
news.js?rand=5cec78f6fa0982a7541047ebc698c504:1 Uncaught ReferenceError: $ is not defined
    at news.js?rand=5cec78f6fa0982a7541047ebc698c504:1
(anonymous) @ news.js?rand=5cec78f6fa0982a7541047ebc698c504:1
inspectionutils.js?rand=318a6961039e8fee3bb31c1dfcc19d4e:54 Uncaught ReferenceError: $ is not defined
    at inspectionutils.js?rand=318a6961039e8fee3bb31c1dfcc19d4e:54
(anonymous) @ inspectionutils.js?rand=318a6961039e8fee3bb31c1dfcc19d4e:54
index.html:64 GET http://0.0.0.0:8080/app/lib/bootstrap-sortable/Scripts/bootstrap-sortable.js?rand=d5cd31491dc1b61c48d7597f4320aebe net::ERR_ABORTED 404 (Not Found)
index.html:65 GET http://0.0.0.0:8080/app/lib/bootstrap-sortable/Contents/bootstrap-sortable.css?rand=e3b9cb0d92af9241cd771e2a0df554c4 net::ERR_ABORTED 404 (Not Found)
index.html:68 GET http://0.0.0.0:8080/app/lib/marked/lib/marked.js?rand=76401133e60015fd0fbf71585bd70e8b net::ERR_ABORTED 404 (Not Found)
index.html:69 GET http://0.0.0.0:8080/app/lib/bootstrap-markdown/css/bootstrap-markdown.min.css?rand=8f623e71e245cd80d78cbd8b0d7c5c19 net::ERR_ABORTED 404 (Not Found)
index.html:70 GET http://0.0.0.0:8080/app/lib/bootstrap-markdown/js/bootstrap-markdown.js?rand=12eab1eaace6e5841f1dd075e5df4c6b net::ERR_ABORTED 404 (Not Found)
index.html?rand=1e21c1d2:799 Uncaught ReferenceError: $ is not defined
    at index.html?rand=1e21c1d2:799
(anonymous) @ index.html?rand=1e21c1d2:799
index.html?rand=1e21c1d2:1220 Uncaught ReferenceError: $ is not defined
    at index.html?rand=1e21c1d2:1220
(anonymous) @ index.html?rand=1e21c1d2:1220`

**Comment by meren** [comment]
Hey @microDM, I see you track the development branch. The error indicates that you forgot to initiate submodules :)

Go to your anvi'o source code directory and run this command to solve this:

```
git submodule update --init
```


Best,

**Comment by microDM** [comment]
@meren thanks for being so quick. In meantime, I tried the solution given by @ozcan [https://github.com/merenlab/anvio/issues/1003#issuecomment-428651831](https://github.com/merenlab/anvio/issues/1003#issuecomment-428651831). Manually adding those lib files solved my issue.

I will try your solution on another system I am using and will update you.

**Comment by meren** [comment]
That solution is not for people who are tracking the codebase and I would suggest you not to do that to avoid future snafus. But you are the boss :)


Best,
