### ISSUE TITLE
[BUG] anvi-interactive unable to load states

### ISSUE THREAD

**Issue by FlorianTrigodet** [merenlab/anvio#1720]
## Short description of the problem

Both `anvi-interactive` and `anvi-display-pan` fail to load saved states. 

## anvi'o version

Gituhub's main version.

## System info

MacOS

## Detailed description of the issue

I made some changes in the interactive interface and save multiples states. After closing and restarting the server, anvi'o fails to load any states and restores a default state. Here is the message that appears on the top right corner of the interface:
<img width="380" alt="Screen Shot 2021-04-18 at 9 27 54 PM" src="https://user-images.githubusercontent.com/10922896/115173468-fb7beb00-a08c-11eb-86b9-4ca2a808d7e8.png">

## Files to reproduce

I was able to reproduce the error with the Infant Gut dataset, for both `anvi-interactive` and `anvi-display-pan`.

**Comment by matthewlawrenceklein** [comment]
hey @FlorianTrigodet, thanks for catching this! Just so I'm understanding, when you hit `load state` on the bottom left of the interactive interface, do you no longer see your saved states? 

Using the infant gut dataset I'm able to instantiate the interface with a default state, save my changes as a new state, kill the server, and then load up my saved state in a new interactive environment. 

While taking a look at this, I'm seeing that the way anvio currently processes `layers` state data causes the toastr warnings to fire when they shouldn't and for user's `layers` data to be superceded. I'll patch this issue asap while I work out the kinks  : )

**Comment by FlorianTrigodet** [comment]
> when you hit load state on the bottom left of the interactive interface, do you no longer see your saved states?

No, I see all saved states. But when I actually load one, nothing is changed (layers colors, size, etc) and I see the message on the top right corner (screenshot in previous comment). I've tried it both from my local machine and remotely from the server to check if it was coming from my laptop.

**Comment by matthewlawrenceklein** [comment]
Gotcha, thanks! I believe I've tracked down the main offenders and I put up a PR #1721 to remedy the issues you're seeing. 

Also, any saved state data that you've established **has not** been overwritten, even though you're not seeing your state data reflected in the interface. With the PR in place, your states should be back to working correctly , Apologies for any late-Sunday headaches : )

**Comment by meren** [comment]
Hey @FlorianTrigodet, can you please test using an up-to-date active branch and report back?

**Comment by FlorianTrigodet** [comment]
It works 🎉

**Comment by matthewlawrenceklein** [comment]
addressed in PR #1728
