### ISSUE TITLE
[BUG] Diamond Searchresults not Reused when Changing Pan Genome Parameters

### ISSUE THREAD

**Issue by tillepprecht** [merenlab/anvio#1734]
## Short description of the problem

When using diamond to create a pan genome in anvio and changing the `--mcl-inflation` parameter only the diamond database (.dmnd file) gets reused, not the search results. When using blast, the search results are reused.

## anvi'o version

```
Anvi'o .......................................: hope (v7)

Profile database .............................: 35
Contigs database .............................: 20
Pan database .................................: 14
Genome data storage ..........................: 7
Auxiliary data storage .......................: 2
Structure database ...........................: 2
Metabolic modules database ...................: 2
tRNA-seq database ............................: 1
```

## System info

Happens on both Desktop and Server

Desktop:
Ryzen 5 5600x (6c12t@3.7gHz)
32 GB RAM
Windows 10 with anvio running in a wsl 1 ubuntu 20.04

Server:
64c128t@2.1 gHz
1 TB RAM
Linux

## Detailed description of the issue

After running `anvi-pan-genome -g PROCHLORO-GENOMES.db -n "Diamond_Bug_Test_ncbi" --output-dir PROCHLORO --mcl-inflation 10 --use-ncbi-blast` once and wanting to change the mcl-inflation, `anvi-pan-genome -g PROCHLORO-GENOMES.db -n "Diamond_Bug_Test_ncbi_2" --output-dir PROCHLORO --mcl-inflation 5 --use-ncbi-blast` reuses the blast database and the blast search results. Or as anvio puts it: 
```
WARNING
===============================================
Notice: A BLAST database is found in the output directory, and will be used!


WARNING
===============================================
Notice: A BLAST search result is found in the output directory: skipping BLASTP!
```

However, when using diamond, `anvi-pan-genome -g PROCHLORO-GENOMES.db -n "Diamond_Bug_Test_dmnd" --output-dir PROCHLORO --mcl-inflation 10` and wanting to change the mcl-inflation, `anvi-pan-genome -g PROCHLORO-GENOMES.db -n "Diamond_Bug_Test_dmnd_2" --output-dir PROCHLORO --mcl-inflation 5`, anvio ignores the search results, only reusing the database:

```
WARNING
===============================================
Notice: A diamond database is found in the output directory, and will be used!

DIAMOND is set to be .........................: Fast
[07 May 21 17:35:50 DIAMOND] running blastp
```

Using the `--overwrite-output-destinations / -W` flag doesn't reuse anything, as expected. 

## Files to reproduce

I took a subset from the pangenome tutorial and already ran the first run of both ncbi blast and diamond.
[diamond_bug.zip](https://github.com/merenlab/anvio/files/6442837/diamond_bug.zip)

For reproduction steps see above.

**Comment by meren** [comment]
This is now fixed. Thank you very much for the report, @tillepprecht!
