### ISSUE TITLE
[BUG] gff outputs not formatted as v6

### ISSUE THREAD

**Issue by lyy005** [merenlab/anvio#1744]
## Short description of the problem

Hi there, 
I was using anvi-get-sequences-for-gene-calls to export the annotation gff files. And the output of the gff file is not formatted the same as version 6. I was wondering if there's anyway I could outputt the gff format as before? 

Thank you! 

Yiyuan

```
anvi-get-sequences-for-gene-calls -c contig.db --export-gff3 -o contig.gff3
```

## anvi'o version

anvi'o v7

This is the output from anvio-7

```
##gff-version 3
c_000000000001	.	CDS	1	213	.	+	.	ID=0
c_000000000001	.	CDS	1	1395	.	-	.	ID=1
c_000000000001	.	CDS	1	171	.	-	.	ID=2
c_000000000001	.	CDS	1	870	.	+	.	ID=3
c_000000000001	.	CDS	1	498	.	+	.	ID=4
c_000000000001	.	CDS	1	1434	.	+	.	ID=5

```

This is the output from anvio-6.2, where I used the same command as in anvio-6.2

```
##gff-version 3
c_000000000001	.	CDS	314	526	.	+	.	ID=0
c_000000000001	.	CDS	642	2036	.	-	.	ID=1
c_000000000001	.	CDS	2065	2235	.	-	.	ID=2
c_000000000001	.	CDS	2945	3814	.	+	.	ID=3
c_000000000001	.	CDS	3759	4256	.	+	.	ID=4
c_000000000001	.	CDS	4897	6330	.	+	.	ID=5

```
## System info

I'm using anvio on Ubuntu 18.04.5 LTS, installed with miniconda

**Comment by meren** [comment]
Hi @lyy005, 

I think we addressed this issue in the active branch :( Apologies for the error in `v7`. Would you be willing to switch to the active branch and try it? There is a section in our installation tutorial and it is quite easy.


Best,

**Comment by lyy005** [comment]
Hi meren,
Thank you for your help. It works great after I updated to the active branch. 

Yiyuan

**Comment by meren** [comment]
Thank you for testing, @lyy005!
