### ISSUE TITLE
anvi-script-process-genbank output

### ISSUE THREAD

**Issue by SolayMane** [merenlab/anvio#1749]
## Short description of the problem

I run anvi-script-process-genbank  on gbk file of fungal genome and the  Num gene records found is different to  Num genes reported.

## anvi'o version

Anvi'o .......................................: hope (v7)

here is the script lanched 
anvi-script-process-genbank -i assembly.gbk -O essai

Num GenBank entries processed ................: 51
Num gene records found .......................: 20,416
Num genes reported ...........................: 6,325
Num genes with functions .....................: 97

FASTA file path ..............................: essai-contigs.fa
External gene calls file .....................: essai-external-gene-calls.txt
TAB-delimited functions ......................: essai-external-functions.txt

How can I get the external gene calls file including all the recodrs found?

**Comment by meren** [comment]
Hey @SolayMane, apologies for the late response to this. Following the report at #1768 I was able to propose substantial changes to the program, which now clarifies why some genes were omitted from results.

If you are following the active branch, you can pull the latest changes from GitHub.
