### ISSUE TITLE
Update parser for output from EggNOG-mapper v2.1.4

### ISSUE THREAD

**Issue by cpeeters** [merenlab/anvio#1757]
## The need

The online eggNOG-mapper tool changed to version 2.1.4 (was 2.0.1 until few days ago) and Anvio does not support this version when trying to import these functions as described here: https://merenlab.org/2016/06/18/importing-functions/#eggnog-database--emapper (highest supported version is 2.0.1).

## The solution

Would be possible to enable the import of eggNOG-mapper v2.1.4 output?

I realize it is a hassle that the output format of eggNOG-mapper keeps on changing, but as discussed in this post (https://github.com/eggnogdb..., it should remain the same on the mid term from now.

## Beneficiaries

Everyone working with eggNOG-mapper and doing microbiol genomics.

## Attached files

Please find in attachment an example of a contigs database for isolate DNF00083, as well as the output from eggNOG-mapper 2.1.4 as generated by the online tool (http://eggnog-mapper.embl.de/). A 'g' was added for to each line with gene annotation info so it should be ready for import.

[eggnog-mapper-2.1.4.zip](https://github.com/merenlab/anvio/files/6686523/eggnog-mapper-2.1.4.zip)

**Comment by meren** [comment]
Thank you very much for the test files, @cpeeters! The commit d8e4af47deb67cf8adb3df53b0f113c64cf4015e addresses this in the development branch.

This is what I get when I run it on the contigs database you've sent:

``` 
>>> anvi-script-run-eggnog-mapper -c DNF00083.db \
                                  --annotation DNF00083.emapper.annotations.fixed \
                                  --use-version 2.1.4

COG version ..................................: COG20
COG data source ..............................: The anvi'o default.
COG base directory ...........................: /Users/meren/github/anvio/anvio/data/misc/COG

Gene functions ...............................: 11,278 function calls from 12 sources (EGGNOG_GENE_FUNCTION_NAME, EGGNOG_BRITE, EGGNOG_GO_TERMS, EGGNOG_KEGG_TC, EGGNOG_KEGG_PATHWAYS, EGGNOG_KEGG_MODULE,
                                                EGGNOG_BEST_TAX, EGGNOG_BiGG_REACTIONS, EGGNOG_EC_NUMBER, EGGNOG_CAZy, EGGNOG_KEGG_KO, EGGNOG_BACT) for 1,822 unique gene calls have been added to the contigs
                                                database.
```


Best wishes,

**Comment by cpeeters** [comment]
Thank you very much, worked like a charm!

Charlotte

**Comment by meren** [comment]
Brilliant. Thank you for reporting back!

**Comment by cdv22222** [comment]
Hi Meren, how did you use that update? I replace emapper.py in my directory? if so I did it but I get the following error 

```
> anvi-script-run-eggnog-mapper -c contigs.db --annotation MM_uf7ygt2_.emapper.annotations.txt --use-version 2.1.4
Traceback (most recent call last):
  File "/home/z/anaconda3/envs/anvio-7/bin/anvi-script-run-eggnog-mapper", line 11, in <module>
    from anvio.drivers.emapper import EggNOGMapper
  File "/home/z/anaconda3/envs/anvio-7/lib/python3.6/site-packages/anvio/drivers/emapper.py", line 83
    '2.0.5': self.__parser_4,
    ^
IndentationError: unexpected indent
```
bref, i'm so stupid (-_-;) jajajajaj

**Comment by meren** [comment]
I just responded to your other issue!

> Any advice please with language for dummies, because I am moron (⊙.⊙)

I laughed out-loud reading this :) Thanks for your patience!

**Comment by Schaubi14** [comment]
Hi Meren,

Thanks a lot for updating the egg-NOG script. 

I was wondering if it would be possible to extend it to also work aside from contigs databases also with genomes-storage databases? 

cheers, 

Clemens
