### ISSUE TITLE
Error EggNOG-mapper v2.1.4 

### ISSUE THREAD

**Issue by cdv22** [merenlab/anvio#1758]
Hi Meren, following the information in this post (https://github.com/merenlab/anvio/issues/1757), I have this problem when I ran it 

```
anvi-script-run-eggnog-mapper -c contigs.db --annotation 1.tsv --use-version 2.1.4
COG version ..................................: COG20
COG d
[emapper.zip](https://github.com/merenlab/anvio/files/6720901/emapper.zip)
ata source ..............................: The anvi'o default.
COG base directory ...........................: /home/z/anaconda3/envs/anvio-7/lib/python3.6/site-packages/anvio/data/misc/COG
```

`Config Error: Gene caller ids found in this annotation file does not start with the expected 
              prefix. This is a historical glitch that is not quite easy to address          
              programmatically, so anvi'o asks you to add the expected prefix as the first   
              character of every gene call in your annotations file. This is the prefix what 
              you need to add manually to the very beginning of every line (anvi'o developers
              are very sorry for this step): `'g'.``

But when i tryed to add `'g'.` to every gene call, the result is as follows: 
```
`Config Error: At least one gene caller id in this annotation file (gc_000000000001_1) does not
              look like how anvi'o likes its gene calls. Hint: what should remain after       
              removing gene caller id prefix (g) should be an integer value.`

```
these are the original data files I am using (it's a sample, the others are the same), if you could guide me in my mistake, I would be happy 
[emapper.zip](https://github.com/merenlab/anvio/files/6720905/emapper.zip)

Any advice please with language for dummies, because I am moron (⊙.⊙)

Thanks anyway 

_Originally posted by @cdv22222 in https://github.com/merenlab/anvio/issues/1757#issuecomment-868091016_

**Comment by meren** [comment]
Hey @cdv22, I'm sorry that you're dealing with this. The output file you have from emapper has lines that go like this:

```
c_000000000001_1 (...)
c_000000000001_2 (...)
c_000000000001_2 (...)
```

This is quite unexpected, but I may have a better idea how this happened if you send me the command by which you have generated **the FASTA input file with gene sequences** you must have submitted to emapper. Essentially, I'm asking how did you get the gene sequences from the `contigs.db` at the first place?


Best,

**Comment by cdv22** [comment]
Hi Meren, thank you for taking the time to reply to me 
I will tell you the step by step that I did
1- downloaded the genomes from ncbi
2- I renamed the contigs:
`anvi-script-reformat-fasta mygenome.contigs.fasta -o contigs.fasta -l 1000 -simplify-names`
3- this file was the input for eggnog (it accepts contigs as imput, plus it uses prodigal as predictor). This same file I converted to db using 
`anvi-gen-contigs-database -f contigs.fasta -o contigs.db`
4- and here I tried to do the data integration using 
`anvi-script-run-eggnog-mapper -c contigs.db --annotation empapper_annotation.tsv --use-version 2.1.4`

looking at the penultimate thing you tell me, c_000000000001, comes from anvi-script-reformat-fasta and _1 comes from prodigal(provided by EggNOG), the problem if I rename the contig name just using the name given by prodigal 1,2,3.... I would lose the contig location of each protein and I think it would not be convenient like that.
as well, I attach the original fasta sequences 
[mygenome.contigs.zip](https://github.com/merenlab/anvio/files/6722231/mygenome.contigs.zip)

**Comment by meren** [comment]
> I renamed the contigs [...] this file was the input for eggnog.

Here is the problem. [The tutorial says](https://merenlab.org/2016/06/18/importing-functions/#eggnog-database--emapper) you should export your genes and that file should be the input for eggnog:


```
anvi-get-sequences-for-gene-calls -c CONTIGS.db \
                                  --get-aa-sequences \
                                  -o amino-acid-sequences.fa
```

If you upload the `amino-acid-sequences.fa` and import the results, you will be fine :)

**Comment by cdv22** [comment]
thanks i'll try

**Comment by cdv22** [comment]
Hi again, I tried again after your recommendation, now I get this: 
`COG version ..................................: COG20
COG data source ..............................: The anvi'o default.
COG base directory ...........................: /home/z/anaconda3/envs/anvio-7/lib/python3.6/site-packages/anvio/data/misc/COG
                                                                                

Config Error: Annotations dictionary is empty :/ There is nothing to add to the database.
`

**Comment by meren** [comment]
I presume this is fixed, @cdv22.
