### ISSUE TITLE
[FEATURE] Backend check for treefile compatibility

### ISSUE THREAD

**Issue by matthewlawrenceklein** [merenlab/anvio#1760]
## The need

A basic sanity check for user-supplied tree files, so that anvio can alert the user in cases where the treefile is incompatible with the corresponding db items

## The solution

A check that compares the # of leaves in a treefile to the # of corresponding items in a profile.db . If the tree is deemed a mismatch, the backend can display a warning in the terminal, or pass forward an error message to be displayed by the frontend, via a toastr message or elsewhere

## Beneficiaries

users that want to know when their thing is broken (or the wrong thing entirely) so they can troubleshoot their thing (or get the right thing) : )

**Comment by meren** [comment]
This is now done. Thank you!
