### ISSUE TITLE
Provide functional distribution tables in the format of genomes versus functions

### ISSUE THREAD

**Issue by tdelmont** [merenlab/anvio#1762]
## The need

If not already possible (if so sorry in advance), would the devs consider providing a way to create a matrix table for functions across genomes (providing a specific functional source), from a Genome storage file?

Similarly, with the very exciting **anvi-compute-functional-enrichment**, would it be also possible to create a matrix table of genome versus functions WITH as additional columns the statistic results of the program?

This would be a very useful data structure for biologists with limited computing skills to immediately get a format ready to be explored in term of functions to visualize/analyze and functions significantly different between groups.

## The solution

flag to create this format as outcome, either from a **anvi-summarize** or **anvi-compute-functional-enrichment**, and new anvi-script maybe?

Or maybe a default output in the summary folder?

## Beneficiaries

Biologists working on genomes / MAGs, etc and that do not know awk, the snake et al.  :)
(for example we have used excel pivot table in the past and it creates some issues, while not being compatible with large volumes of data). 

(if Meren reads this, well yes, I assume it all haha).

Many thanks for considering this.

Best

Tom

**Comment by meren** [comment]
Did you investigate the new anvi'o program [anvi-display-functions](https://merenlab.org/software/anvio/help/main/programs/anvi-display-functions/)?

**Comment by tdelmont** [comment]
@meren thanks my interns work on anvi'o v7:

anvi-self-test --version
Anvi'o .......................................: hope (v7)
Profile database .............................: 35
Contigs database .............................: 20
Pan database .................................: 14
Genome data storage ..........................: 7
Auxiliary data storage .......................: 2
Structure database ...........................: 2
Metabolic modules database ...................: 2
tRNA-seq database ............................: 1```

**We do not see this program**, however it is clear it likely does fulfill what we were looking for,
so I close this for now at least, and will explore it with master asap

Many thanks

Tom
