### ISSUE TITLE
[BUG] anvi-script-process-genbank miss CDS in external-gene-calls

### ISSUE THREAD

**Issue by kafker** [merenlab/anvio#1768]
## Short description of the problem

anvi-script-process-genbank miss coding sequences in external-gene-calls

## anvi'o version

```
anvi-self-test --version
Anvi'o .......................................: hope (v7-dev)

Profile database .............................: 37
Contigs database .............................: 20
Pan database .................................: 15
Genome data storage ..........................: 7
Auxiliary data storage .......................: 2
Structure database ...........................: 2
Metabolic modules database ...................: 2
tRNA-seq database ............................: 2
```

## System info

Ubuntu 18.04.5 LTS

## Detailed description of the issue

It seems that not every CDS in the gbff file is included in the external-gene-calls file. For instance, the protein WP_010815658.1
should be Ef_ATCC_19433_aa.fasta but is missing. 

Does anyone know what the problem could be?

```
anvi-script-process-genbank -i Enterococcus_faecalis_ATCC_19433.gbff --output-file-prefix Ef_ATCC_19433
anvi-gen-contigs-database -f Ef_ATCC_19433-contigs.fa -o Ef_ATCC_19433-contigs.db --external-gene-calls Ef_ATCC_19433-external-gene-calls.txt --ignore-internal-stop-codons --skip-predict-frame
anvi-get-sequences-for-gene-calls -c Ef_ATCC_19433-contigs.db --get-aa-sequences -o Ef_ATCC_19433_aa.fasta
diamond makedb --in Ef_ATCC_19433_aa.fasta -d DB
diamond blastp -d DB -q test.fa --outfmt 6 -o test.out
#Reported 0 pairwise alignments, 0 HSPs.
#0 queries aligned.
```

## Files to reproduce

Attached the GenBank file (gbff) downloaded from RefSeq and the aa fasta file of WP_010815658.1 (test.fa)
[test_input_file.zip](https://github.com/merenlab/anvio/files/6803351/test_input_file.zip)

**Comment by meren** [comment]
Thank you very much for the files! I'm looking into this :)

**Comment by meren** [comment]
(I found out why they're being excluded, I'm trying to find a smart way to keep them in when possible, and report those that are excluded anyway)

**Comment by meren** [comment]
Hey @kafker,

I realized that `anvi-script-process-genbank` was excluding partial gene calls or those that span across multiple contigs. The latter is dangerous and I'm not sure how to solve it, but the former has a place in `external-gene-calls` description of anvi'o. With #1769 I hope I addressed many things that may help you.

Thanks to this report, I also looked into some other additional features. One of them was to make use of use of the amino acid sequences if/when they are present in GFF files. Which means you can now generate your contigs database without the `--ignore-internal-stop-codons` and `--skip-predict-frame` flags. But please pay attention to the warnings and output messages, which intend to clarify if things are being excluded and why. 

Thank you very much for your report and please let me know if there are things that need to be improved in `anvi-script-process-genbank`.


Best wishes,

**Comment by kafker** [comment]
> Hey @kafker,
> 
> I realized that `anvi-script-process-genbank` was excluding partial gene calls or those that span across multiple contigs. The latter is dangerous and I'm not sure how to solve it, but the former has a place in `external-gene-calls` description of anvi'o. With #1769 I hope I addressed many things that may help you.
> 
> Thanks to this report, I also looked into some other additional features. One of them was to make use of use of the amino acid sequences if/when they are present in GFF files. Which means you can now generate your contigs database without the `--ignore-internal-stop-codons` and `--skip-predict-frame` flags. But please pay attention to the warnings and output messages, which intend to clarify if things are being excluded and why.
> 
> Thank you very much for your report and please let me know if there are things that need to be improved in `anvi-script-process-genbank`.
> 
> Best wishes,

Thank you Meren!
