### ISSUE TITLE
[FEATURE] Discarding unwanted sequences from contigs.db

### ISSUE THREAD

**Issue by razz1618** [merenlab/anvio#1773]
Hi,

I am not sure if this feature is already implemented. Is there a way, by which one can discard all sequences of no interest. For say, I have  a large size contigs DB, of which I am just interested in the hits assigned for a set of bins. Can Anvio discard/remove all sequences not related to the bin set?

This will highly improve the performance of all downstream analyses.

**Comment by meren** [comment]
Hey @razz1618, that is the purpose of [`anvi-split`](https://merenlab.org/software/anvio/help/main/programs/anvi-split/). When you run anvi-split on any given collection, it will create a smaller contigs database (and profile database, if applicable) that only include the sequences of interest.

**Comment by razz1618** [comment]
Thanks
