### ISSUE TITLE
Calculate Percent reads taken by all bins in the metagenome

### ISSUE THREAD

**Issue by razz1618** [merenlab/anvio#1775]
Hi,
Can anvio show the percent reads taken by all bins in the raw reads or the in assembled contig (the initial contig from which the bins were assembled)?

I did read this page https://merenlab.org/2017/05/08/anvio-views/ but could not get understand some concepts.

**Comment by meren** [comment]
The program anvi-summarize reports those numbers, @razz1618

**Comment by razz1618** [comment]
@meren Hi,
Yes, that's true. I got the summary, which is absolutely brilliant for downstream analysis. 
Somehow, I missed checking the splits not binned column.

Another query- Apart from relative abundance which other data transformation files can be used for comparing bins/genes across all the samples?


Thanks.
