### ISSUE TITLE
[Bug] Update Default Snakemake workflow anvi-scan-trnas

### ISSUE THREAD

**Issue by rbartelme** [merenlab/anvio#1780]
## Short description of the problem

Inclusion of `anvi-scan-trnas` in the default snakemake workflow JSON file causes downstream hmm annotation error.

## anvi'o version

Replace this text with the output of this command:

```
docker run --rm -it rbartelme/anvio-pangenomics:latest anvi-self-test --version
Anvi'o .......................................: hope (v7)

Profile database .............................: 35
Contigs database .............................: 20
Pan database .................................: 14
Genome data storage ..........................: 7
Auxiliary data storage .......................: 2
Structure database ...........................: 2
Metabolic modules database ...................: 2
tRNA-seq database ............................: 1
```

## System info
Singularity container running anvi'o v7 on cluster 

## Detail of problem
After testing `trna` annotation could be included in the default workflow JSON's via `anvi-run-hmms` with the `--also-scan-trnas` flag. The new default json could remove `anvi_run_trna_scan` from the snakemake rules. This was tested with the pangenomics workflow, but will also probably affect the downstream analyses in the metagenomic workflow as well.

**Comment by meren** [comment]
Thanks for reporting this, @rbartelme. This is very important.

I agree. **We should not run `anvi-trna-scan` in our metagenomic workflow by default, and instead use `--also-scan-trnas` flag for that step to avoid race conditions.** @mschecht? Would you like to take a stab at it later?

**Comment by mschecht** [comment]
@meren I will take care of this on Thursday. 

I took a quick look and both `anvi-trna-scan` and the parameter `--also-scan-trnas` are inherited from the contigs workflow. Making the default for `anvi-trna-scan` "off" will impact all other workflows. I'll look into this.
