### ISSUE TITLE
[BUG] Issue with bowtie2 after fresh install of dev branch

### ISSUE THREAD

**Issue by ekiefl** [merenlab/anvio#1789]
## Short description of the problem

I was getting the following error when running `bash anvio/tests/run_variability_mock.sh new`:

```
:: Generating a Bowtie2 ref ...

dyld: Library not loaded: @rpath/libtbb.dylib
  Referenced from: /Users/evan/anaconda3/envs/anvio-dev/bin/bowtie2-build-s
  Reason: image not found
```

so I decided to install a fresh conda environment of the development branch via the [merenlab](https://merenlab.org/2016/06/26/installation-v2/#5-follow-the-active-development-youre-a-wizard-arry) instructions. But the problem persists.

In fact, the error can be reproduced simply by typing `bowtie2`:

```
▶▶ bowtie2
dyld: Library not loaded: @rpath/libtbb.dylib
  Referenced from: /Users/evan/anaconda3/envs/anvio-dev/bin/bowtie2-align-s
  Reason: image not found
```

From the conda installation I can see I have version `2.3.5.1`, but it is clearly not compiled right. Here is the conda installation stdout:

```
conda install -y -c bioconda bowtie2
Collecting package metadata (current_repodata.json): done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.10.1
  latest version: 4.10.3

Please update conda by running

    $ conda update -n base -c defaults conda



## Package Plan ##

  environment location: /Users/evan/anaconda3/envs/anvio-dev

  added / updated specs:
    - bowtie2


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    tbb-2021.3.0               |       hf7b0b51_0         155 KB
    ------------------------------------------------------------
                                           Total:         155 KB

The following NEW packages will be INSTALLED:

  bowtie2            bioconda/osx-64::bowtie2-2.3.5.1-py36h2dec4b4_0
  tbb                pkgs/main/osx-64::tbb-2021.3.0-hf7b0b51_0



Downloading and Extracting Packages
tbb-2021.3.0         | 155 KB    | ############################################################################################################################################################################################################################################################################################################################### | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
```

**Comment by meren** [comment]
There is certainly something wrong with the new `tbb` package. You should be able to solve this by uninstalling both packages:

```
conda uninstall bowtie2 tbb
```

And installing them this way:

```
conda install -c bioconda bowtie2=2.3.4.1 tbb=2019.8
```

**Comment by ekiefl** [comment]
This fixed it (I just updated website), thanks.  But alas, there is another problem found downstream, this time with samtools :\

```
▶▶ samtools
dyld: Library not loaded: @rpath/libcrypto.1.0.0.dylib
  Referenced from: /Users/evan/anaconda3/envs/anvio-dev/bin/samtools
  Reason: image not found
Abort trap: 6
```

**Comment by meren** [comment]
> This fixed it (I just updated website)

You only updated the standard installation, and not the part for those who wish to track the codebase. I think we should have it in both places.

> samtools
> dyld: Library not loaded: @rpath/libcrypto.1.0.0.dylib
>  Referenced from: /Users/evan/anaconda3/envs/anvio-dev/bin/samtools
>  Reason: image not found
> Abort trap: 6

This is very annoying. I have no idea why conda installs crappy versions. This should fix it:

```
conda uninstall samtools
conda install -c bioconda samtools=1.9
```

**Comment by ekiefl** [comment]
> This should fix it:

It does. Thank you!

> You only updated the standard installation, and not the part for those who wish to track the codebase. I think we should have it in both places.

Fixed, and updated samtools as well.

> This is very annoying. I have no idea why conda installs crappy versions.

It may have misinterpreted our priorities. Maybe it is trying to minimize the number of required downgrades. So it's going "_Well, 3 downgrades required for samtools=1.9, but 0 for samtools=1.7. Since the user did not specify, samtools 1.7 seems better._" Of course, most users rightfully assume that unspecified means they will get the latest.

**Comment by meren** [comment]
Thank you, @ekiefl!

> It may have misinterpreted our priorities

This looks like the case. The problem is, when we are too aggressive with 'versioning' every tool we are using, then we miss the opportunity to benefit from updates to those tools. It is a difficult situation :/
