### ISSUE TITLE
[BUG] anvi-get-sequences-for-gene-calls in gff3 mode  crashes when run before COG db is set up

### ISSUE THREAD

**Issue by dspeth** [merenlab/anvio#1791]
## Short description of the problem

anvi-get-sequences-for-gene-calls in gff3 mode crashes when run before COG db is set up

## anvi'o version

master branch, installed using instructions on install page

## System info

Unix, Debian 9

## Detailed description of the issue

I recently gave in and installed the master branch, but forgot I had not set up any of the databases for this anvio install. When I tried running `anvi-get-sequences-for-gene-calls` to get gff output it threw a non-helpful error and did not run. 

After setting up the COG database, I could no longer reproduce the error, and I forgot to take a screenshot immediately.
So, after setting up the COG database, `anvi-get-sequences-for-gene-calls` runs fine on contigs dbs without COG annotation, but it crashes before COG db is set up.

**Comment by meren** [comment]
Hey @dspeth,

Thanks for the report, but I haven't been able to reproduce the problem on my up-to-date main branch. Regardless of whether COGs were setup, when I run `anvi-get-sequences-for-gene-calls` on a contigs database that DOES have `COG20_FUNCTION` as a gene function source, I get this message:

```
(...)

FUNCTIONS FOUND 🎊
===============================================
Anvi'o found gene function annotations by `COG20_FUNCTION` in your contigs
database and will include that information in the output GFF file (anvi'o also
admits that it is looking for `COG20_FUNCTION` instead of an annotation source
of your choice due to the laziness of its developers. If you would like to be
able to choose a different annotation source, please let the developers know and
they will parameterize this option).

(...)
```

And my output file does contain the following additional labels for a given gene:

```
;Name=COG2084;db_xref=COG20:COG2084;product=3-hydroxyisobutyrate dehydrogenase or related beta-hydroxyacid dehydrogenase (MmsB) (PDB:1I36)
```

If I run it on a contigs database that does **not** have `COG20_FUNCTION`, regardless of whether COGs were setup or not, I get this message:

```
(...)

WARNING
===============================================
Just so you know: anvi'o wanted to include functions for your genes into the GFF
file but your contigs database does not seem to include annotations from
`COG20_FUNCTION`. You can ignore this message if you don't care. But if you
would like your GFF file to include functions for your genes, you can run `anvi-
run-ncbi-cogs` on your contigs db and re-run this command to have an output file
with functions :)

(...)
```

And everything goes alright without functions.

If you send me your contigs database privately, I can test it further :)

**Comment by meren** [comment]
_(all my uses of the program did include the flag `--export-gff3`)_

**Comment by dspeth** [comment]
hmm, weird. Let me try to reproduce the problem on my end so that I can send you a screenshot along with the contigs db. Can one easily "un-setup" the COG dbs, or would a fresh install be best?

**Comment by meren** [comment]
It is easy to 'un-setup' the databases for COGs. I will send an exact command in a second. Don't start a fresh install :)

**Comment by meren** [comment]
This will give you where your database directory for COGs is:

``` bash
python -c "import os; import anvio; print(os.path.join(os.path.dirname(anvio.__file__), 'data/misc/COG'))"
```

Which means you could do that to temporarily 'unsetup' it:

``` bash
my_COGs_dir=`python -c "import os; import anvio; print(os.path.join(os.path.dirname(anvio.__file__), 'data/misc/COG'))"`
mv $my_COGs_dir /tmp/XXX
```

And once you're done, you can put it back where it was to undo your unsetup:

``` bash
mv /tmp/XXX $my_COGs_dir
```

**Comment by dspeth** [comment]
that did the trick:
 
<img width="1631" alt="Screenshot 2021-09-06 at 20 16 44" src="https://user-images.githubusercontent.com/5320639/132251877-2a8f9d29-e894-4bfd-ae2e-68cc2326eab6.png">

**Comment by dspeth** [comment]
zipped contigs db, because github did not want a .db file:
[GEMOTU_00001.zip](https://github.com/merenlab/anvio/files/7117436/GEMOTU_00001.zip)

**Comment by meren** [comment]
Aha! ​Now I get it. When there are NO function annotation sources it explodes :) I will take a quick look now. Thank you very much for your patience

**Comment by dspeth** [comment]
so, the problem is not the absence of the COG db. After restoring that I still got the same issue: 
<img width="1644" alt="Screenshot 2021-09-06 at 20 24 09" src="https://user-images.githubusercontent.com/5320639/132252416-a3bd6f74-f9eb-499b-a69c-f491050bfa17.png">

but then it is fixed when I run COGs
<img width="1644" alt="Screenshot 2021-09-06 at 20 24 30" src="https://user-images.githubusercontent.com/5320639/132252424-b6c1b8d2-5e22-4626-82a1-41e9b90c099b.png">

**Comment by dspeth** [comment]
not an actual issue that interferes with my work, the error was clear enough to make me realise what my mistake was and fix it. Just looking out for the anvi'o codebase :D

**Comment by meren** [comment]
I think it should be now resolved. Thank you very much, Daan!

**Comment by dspeth** [comment]
yep, works on my end now
