### ISSUE TITLE
[BUG] Config Error: get_synonymous_and_non_synonymous_potential

### ISSUE THREAD

**Issue by TianyiChang** [merenlab/anvio#1792]
## Short description of the problem![image](https://user-images.githubusercontent.com/32375577/132428483-b04ec109-e494-4b36-a8ff-b73ff236e076.png)
Config Error: get_synonymous_and_non_synonymous_potential :: sequence does not end with a stop
              codon and is therefore probably not what you want. If you want to continue      
              anyways, use the just_do_it flag

## anvi'o version

Anvi'o .......................................: hope (v7)

Profile database .............................: 35
Contigs database .............................: 20
Pan database .................................: 14
Genome data storage ..........................: 7
Auxiliary data storage .......................: 2
Structure database ...........................: 2
Metabolic modules database ...................: 2
tRNA-seq database ............................: 1

## System info

operating system: Linux; anvi'o installed via conda.

## Detailed description of the issue
I encountered this error when I tried to calculate the pN/pS with 'anvi-script-calculate-pn-ps-ratio'. I didn't get any trouble generating the files (contig-db, profiled-db, SAAVs.txt, and SCVs.txt) required for this command.

Below are all the commands I used:
#generate contigs-db (work fine)
anvi-gen-contigs-database -f combined.fa -o combined.db -T 40

#generate profile-db (work fine)
anvi-profile -i combined_indexed.bam \
                             -c combined.db \
                             -o combined_profile-db -T 40 --profile-SCVs

#define Collection and Bin (work fine)
anvi-script-add-default-collection -p combined_profile-db/PROFILE.db \
                                   -C combined_COLLECTION \
                                   -b combined_BIN

#generate SAAVs.txt (work fine)
anvi-gen-variability-profile -p combined_profile-db/PROFILE.db \
                             -c combined.db \
                             -o SAAVs.txt \
                             -C combined_COLLECTION \
                             -b combined_BIN \
                             --engine AA

#generate SCVs.txt (work fine)
anvi-gen-variability-profile -p combined_profile-db/PROFILE.db \
                             -c combined.db \
                             -o SCVs.txt \
                             -C combined_COLLECTION \
                             -b combined_BIN \
                             --engine CDN

#calculate pN/pS (error occured)
anvi-script-calculate-pn-ps-ratio \
                             -a SAAVs.txt \
                             -b SCVs.txt \
                             -c combined.db \
                             -o pn-ps

**Comment by meren** [comment]
Hi @TianyiChang,

Did you include the `--just-do-it` to your `anvi-script-calculate-pn-ps-ratio` command as the error suggests?


Best,

**Comment by TianyiChang** [comment]
Dear  Murat
  
​
  
​Thanks a lot for your quick reply! I don't think that there is an option '--just-do-it' for the command 'anvi-script-calculate-pn-ps-ratio' (maybe I missed something?). Also, I hope to find out the reason that caused the issue to know that the analysis is done correctly.
  
​
  
​Thank you again   😊
  
​
  
​Best,
  
​Tianyi
  
​

**Comment by meren** [comment]
Hey @ekiefl, should we add `--just-do-it` to `anvi-get-pn-ps-ratio`? If not, how do you think we should solve this?

**Comment by ekiefl** [comment]
Hi @TianyiChang and @meren.

It's  great you're making use of pN/pS @TianyiChang. However, I would highly recommend you switch to our main development branch, as it has undergone drastic improvement. For one, this bug is fixed. But more importantly, the entire calculation has been changed for the better. Here is the pull request that details the two methods, and why the new one is better: https://github.com/merenlab/anvio/pull/1663

Closing this issue, but please feel free to keep the conversation moving in this thread.

**Comment by TianyiChang** [comment]
> Hi @TianyiChang and @meren.
> 
> It's great you're making use of pN/pS @TianyiChang. However, I would highly recommend you switch to our main development branch, as it has undergone drastic improvement. For one, this bug is fixed. But more importantly, the entire calculation has been changed for the better. Here is the pull request that details the two methods, and why the new one is better: #1663
> 
> Closing this issue, but please feel free to keep the conversation moving in this thread.

Hi @ekiefl 

Thank you for showing me all the details and your awesome script.

I replaced the old script with the sandbox/anvi-script-calculate-pn-ps-ratio (5e6abc5 ) and made it executable (chmod +x), but now I got this new error: "Terminal Error: Progress.new() can't be called before ending the previous one (Existing: '08 Sep
                21 15:03:06 Calculating pN and pS', Competing: 'Calculating pN and pS')." I was wondering if you know how should I solve this problem?

Thank you!

**Comment by meren** [comment]
Hey @TianyiChang,

Copying the script and changing its executable bit is not the right way to do it.

You should simply follow these instructions to create a new environment that track the development branch:

https://merenlab.org/2016/06/26/installation-v2/#5-follow-the-active-development-youre-a-wizard-arry


Best,

**Comment by TianyiChang** [comment]
Get it! Thank you so much for the help😊
  
​
