### ISSUE TITLE
Annotations dictionary is empty (anvi-script-run-eggnog-mapper)

### ISSUE THREAD

**Issue by cdv22** [merenlab/anvio#1795]
## Short description of the problem

Hi, when I try to run the following command I get this error 

## anvi'o version = 7

`anvi-script-run-eggnog-mapper -c contig.db --annotation MM_x3cya7db.emapper.annotations.tsv --use-version 2.1.4`

```
`COG version ..................................: COG20
COG data source ..............................: The anvi'o default.
COG base directory ...........................: /anaconda3/envs/anvio-7/lib/python3.6/site-packages/anvio/data/misc/COG
                                                                                

Config Error: Annotations dictionary is empty :/ There is nothing to add to the database.
`
```
Does anyone know why this is?

**Comment by meren** [comment]
Hi @cdv22, I'd suggest you to try the development branch of anvi'o. If the error persists, please re-open this issue, and send me privately your contigs database and the annotations.tsv file so I can test it.
