### ISSUE TITLE
anvi-script-FASTA-to-contigs-db: command not found

### ISSUE THREAD

**Issue by huizhen-yan** [merenlab/anvio#1801]
Hi, 
After I successfully installed anvi'o program and checked with "anvi-self-test --suite mini", I successfully opened the browser “SAMPLES MERGED” page.
But when I run the command "anvi-script-FASTA-to-contigs-db -h", I got the error: anvi-script-FASTA-to-contigs-db: command not found. Can you help me?
By the way, the command "anvi-get-sequences-for-hmm-hits -h" run properly and I got the help page.
So I wonder if there is a problem with this command "anvi-script-FASTA-to-contigs-db"??

**Comment by ivagljiva** [comment]
Hi @huizhen-yan , that script is deprecated - it no longer exists. You will have to convert your fasta files to contigs dbs manually (which is not that hard, you will need to run `anvi-gen-contigs-database` instead).

We should update our tutorials to reflect this, so if you could send us the links where you found this script, we would really appreciate it!

**Comment by huizhen-yan** [comment]
Thank you very much.  @ivagljiva , I will try the way you mentioned to convert. 
The links of this script is: https://merenlab.org/2017/07/09/recovering-rRNAs/

**Comment by meren** [comment]
Thanks for the report. The blog post is now up-to-date.
