### ISSUE TITLE
error: "There are no HMM sources among your external genomes that occur in every genome. " while using phylogenomics module

### ISSUE THREAD

**Issue by huizhen-yan** [merenlab/anvio#1811]
##I want to extract the ribosomal protein sequence from metagenome-assembled genomes and reconstruct phylogenetic tree. 
But I got an error:
 "There are no HMM sources among your external genomes that occur in every genome. " while using phylogenomics module

I obtained 7 metagenome-assembled genomes, then I did
anvi-gen-contigs-database -f $i.fa -o $i.db -T 4
anvi-run-hmms -c $i.db
so I got 7 genomes' contigs database.
Similarly, I converted the genome downloaded from NCBI into contigs-db. 
Then fill in the external-genomes.txt file. 
I run the script "anvi-get-sequences-for-hmm-hits --external-genomes external-genomes.txt --hmm-source Archaea_76 --list-available-gene-names",  I got the following error:

(anvio7) yhz@eihi:/mnt/f/contigs-db$ **anvi-get-sequences-for-hmm-hits --external-genomes external-genomes.txt --h
mm-source Archaea_76 --list-available-gene-names
[26 Sep 21 10:43:37 Sanity checks] ...
Config Error: There are no HMM sources among your external genomes that occur in every genome**
              :/

##The selected bins/genomes are all archaea, and I think there must be some shared sequences among them, which contradicts the reported error. I don't know why. Can you help me?

**Comment by meren** [comment]
This error indicates that one or more of your contigs databases are missing HMMs. It may be the case because you forgot to run anvi-run-hmms or the run for anvi-run-hmms failed to successfully complete for one of your contacts databases. I suggest you rerun  anvi-run-hmms on each of your countries databases.

**Comment by huizhen-yan** [comment]
Thanks for your reminding. I checked and found that anvi-run-hmms did not run successfully.
