### ISSUE TITLE
[BUG] Handling categorical data layer render slowdown

### ISSUE THREAD

**Issue by matthewlawrenceklein** [merenlab/anvio#1816]
## issue 

At present, the interactive interface will automatically switch from drawing categorical layer data as colors to drawing text. Currently this decision is based on the number of _unique_ items per layer, with the cutoff being `20`. This makes sense, as rendering 100 different colors for a layer doesn't provide a ton of visual clarity. 

This process does not take into account the total number of items per layer, so a layer with 21 unique items and 1500 total items will require the rendering of 1500 text objects. This is a bottleneck. 

## solution
Setting a threshold for total items per layer allows us to incorporate an additional performance-minded setting
- if _unique_ items per layer < 20, display type defaults to `color`
- if _unique_ items per layer > 20 && total items per layer < 1000 (or any arbitrary cutoff), switch type from `color` to `text`
- if _unique_ items per layer > 20 && total items per layer > 1000, set the layer height to `0` and warn the user that the layer has been minimized for the sake of performance. The user can then opt to display the layer however they see fit.

**Comment by meren** [comment]
Instead of a `height`, we use maximum font size variable to determine if we want to show things bigger.

Increasing `height` beyond the boundaries of maximum font size given the number of elements, would result in overlapping characters as fonts would continue of increase as a function of `height` :)

**Comment by matthewlawrenceklein** [comment]
@meren - I'm going to close this for now unless you'd like to revisit this from a different angle

**Comment by meren** [comment]
I think the current solution is good for a while. Thank you!
