### ISSUE TITLE
show grid for contigs 

### ISSUE THREAD

**Issue by tdelmont** [merenlab/anvio#182]
Hi,
The "show grid for bins" is very good.
yet, in one of the main approaches of anvio, we determine and refine bins first, then re-do the analysis at the bin level. At this point, a bin is a contig, and we can have a lot of them.

It would be very useful to have the option to show all contigs (and hence bins) as a grid by clicking in a bottom.

Hope it is clear and easy to do.
Tom

**Comment by meren** [comment]
There is a more proper solution to this than adding a new feature: bin each contig separately (which doesn't have to be through the interface --it can be done by importing a pre-arranged collection).

**Comment by tdelmont** [comment]
Actually, the best would be to have to option of selecting each contig as a bin, so we can not only show the grid for them but also summarize them... Best would be to name them from the largest bin to the smallest bin!
So at the end of the analysis, we have a bin number that actually makes sense, instead of being random.

**Comment by meren** [comment]
We already have this option, and it is called `anvi-import-collection`.

**Comment by tdelmont** [comment]
ok... but it is a bit complex for something I feel will become a classic anvio analysis.
I need to create a table with all splits linked to a bin name... 
Could it be possible to run a single command line when we want to create a collection at the contig level and anvio takes care of finding all contigs and name bins the same the contig is called?

**Comment by meren** [comment]
Yes, there can be a script to do that. I will look into that when I have a chance.

**Comment by meren** [comment]
fixed.
