### ISSUE TITLE
[FEATURE] Allow users to choose the annotation source when creating GFF3 files

### ISSUE THREAD

**Issue by philipwoods** [merenlab/anvio#1827]
## The need

Prior to v7.1, the function `anvi-get-sequences-for-gene-calls` did not include functional annotation information in exported GFF3 files. In v7.1, this was changed, but the annotation source included was hard coded to COG20_FUNCTION. The changed function also asked users to alert the developers if it would be useful to be able to choose the desired annotation source. This is following through on that request, as the option to have different functional annotations in the GFF3 files would be useful to me.

## The solution

The solution I imagine would be to have a `--annotation-source` option analogous to the option in many other Anvi'o functions. Because such an option exists in many other functions and there is already a method to add a COG functions to the GFF3 files, I imagine this wouldn't be too complicated to put together.

## Beneficiaries

In my particular case, I find the GFF3 files can be useful to add gene and annotation information when browsing through contigs or MAGs in genome visualization software. In those cases, it can be nice to have multiple annotation sources available because different annotation sources may miss or catch different genes, and some annotations provide different kinds of information from COGs (e.g. Pfam can provide information on multiple domains within a given predicted protein). In the past I did this with a separate script, but it would be much more convenient if Anvi'o could do it internally.

This could also be a step towards exporting annotated genomes as mentioned in issue #1764. At the least, it would simplify the task for users wanting to take that step on their own.

**Comment by meren** [comment]
This is now done. Thank you very much for taking the time to report it, @philipwoods.
