### ISSUE TITLE
relative abundance calculations

### ISSUE THREAD

**Issue by jvineis** [merenlab/anvio#183]
The summary produces two "relative_abundance.txt" tables.  It would be great if the relative_abundance from the bins_across_samples calculated the relative abundance of a bin within each sample, instead of across all samples.  For example, in the "bins_percent_recruitment" , the calculation is made in this way with a "**splits_not_binned**".  I find this to me much more useful. 

For example, I have a bin "Group_1".  In the "bin_by_bin" directory, the value of this bin in a sample is reported as 0.99, indicating that this bin is 99% relative abundance of this sample, but this is not correct.

**Comment by meren** [comment]
This is important. I will work on this soon. Sorry for the delay.

**Comment by jvineis** [comment]
You,
Ok.  I'm settling for mean coverage for now.
Thanks,

-Me


----- Original Message -----
