### ISSUE TITLE
[BUG] no additional data for 'items' in this database 

### ISSUE THREAD

**Issue by SCarrSuperstar** [merenlab/anvio#1830]
I've updated to Anvi'o 7.1 and thought I successfully made my profiles. I did get a warning stating that "there were 201,121 reads present in the BAM file that did not end up being used by the profiler," but I expected this because I accidentally made my bam files PE.fasta files that later underwent 1 extra qc step before the co-assembly was made. So I was ok with this error. BUT my anvi-merge step gives me this: 

Config Error: There is something wrong with your input databases. The group name 'default'   
              should be common to all of them, but it doesn't seem to be the case :/ How did 
              you end up with an anvi'o single profile database that doesn't have the        
              'default' group in its additional layer data table? It is very likely that your
              profiling step failed for some reason for one or more of your databases :( 

and when I run anvi-show-misc-data I get this: 

```
* There are no additional data for 'items' in this database :/

                                                                                                                                    
DATA KEYS FOR "LAYERS" in 1 DATA GROUP(S)
===============================================

* DATA GROUP "default" WITH 4 KEYS
    - num_INDELs_reported (int, describes 1 layers)
    - num_SNVs_reported (int, describes 1 layers)
    - total_reads_kept (int, describes 1 layers)
    - total_reads_mapped (int, describes 1 layers)

                                                                                                                                    
* There are no additional data for 'layer_orders' in this database :/
```

I was talking with @ekiefl before about the the profile step. I'm happy to drop more files into our shared drop box. I'm also considering it maybe time to start over and make new bam files. 

Thanks for the help!

**Comment by SCarrSuperstar** [comment]
You're right! I feel rather silly because I got a far down the rabbit hole after reading errors from others and didn't just check the RUNLOG.txt files. I found the file that didn't finish, ran the merge, and was able to view the merge file with anvi-interactive!

**Comment by ekiefl** [comment]
Amazing! Glad you got everything working.
