### ISSUE TITLE
Interface layer display on Chrome

### ISSUE THREAD

**Issue by Diamonds95** [merenlab/anvio#1831]
Hello! I found that when I displayed the pan-genome on Chrome, only part of the layer panels appeared, like the picture. 
So I cannot select multiple items. Is there any resolvents？ Thanks for your reply!
![1635773915(1)](https://user-images.githubusercontent.com/41280750/139681565-594992fe-697d-41a0-898f-c288018fd24c.png)

**Comment by matthewlawrenceklein** [comment]
@Diamonds95 with your mouse focused in the settings panel, you can press `shift` and use your scroll wheel to navigate horizontally to hidden fields. That should enable you to access each element :)

**Comment by Diamonds95** [comment]
It works! Thanks a lot!

**Comment by matthewlawrenceklein** [comment]
Sure thing! If you haven't already done so, I absolutely recommend joining the [anvi'o slack channel](https://join.slack.com/t/anvio/shared_invite/zt-ov46uj90-9p2woLJFcVCfv7cdhANXSA) It's a great resource to ask/answer questions from the anvi'o community :)
