### ISSUE TITLE
[BUG] RNA features labeled as CDS in GFF output of anvi-get-sequences-for-gene-calls

### ISSUE THREAD

**Issue by dspeth** [merenlab/anvio#1832]
## Short description of the problem

When running `anvi-get-sequences-for-gene-calls` with the `--export-gff3` flag on a contigs db, the RNA features in the contigs db (produced by `anvi-run-hmms` with the `--also-scan-trnas` flag) are labeled "CDS" in the 3rd column (feature type) of the gff output. This seems incorrect, but also not an urgent problem. 

## anvi'o version

development branch

## System info

Unix, Debian 9, installed dev version following the install instructions on the website

**Comment by dspeth** [comment]
Hey @meren, thanks for the quick fix! Seems generally fine to me, but is the choice to label "Ribosomal RNAs" as "mRNA" deliberate or a typo?

**Comment by meren** [comment]
> choice to label "Ribosomal RNAs" as "mRNA" deliberate or a typo?

Oh, that is a reminder for me to not code when I'm jetlagged :) I'll fix it.
