### ISSUE TITLE
[BUG] can't remove samtools

### ISSUE THREAD

**Issue by marwa38** [merenlab/anvio#1833]
Hello 

samtools couldn't be updated from 1.7 to 1.9
as I can't remove it in the first place 
I have left that overnight and still "Solving environment"
Do I really need to update samtools?

Also could you please give me some insights into why python 3.6 is the one we have to use
I am not sure if that is true that is the main source of the problem, 

## anvi'o version anvio-7.1

![image](https://user-images.githubusercontent.com/68851733/140299409-c7c011e0-b548-4cf2-8326-ddb3f2128fe8.png)

## System info
![image](https://user-images.githubusercontent.com/68851733/140300067-3a869e80-d17a-47ae-96ad-688038f9a6f1.png)

I am installing anvio as steps clarified in https://merenlab.org/2016/06/26/installation-v2/

Expecting installation to work fine 

Many thanks

**Comment by meren** [comment]
Sorry, @marwa38, this is not something we can help with. You do need to have samtools 1.9.

I just updated the installation instructions to include an earlier command to ensure proper installation of samtools. Please remove your anvi'o v7.1 environment, and try to install it again following the instructions.

Best,
