### ISSUE TITLE
anvi-pan-genome stuck in "Aligning amino acid sequences for genes in gene clusters"

### ISSUE THREAD

**Issue by fancyge** [merenlab/anvio#1834]
Dear developer,

I'm running command "anvi-pan-genome" and got stuck below. It output some warnings but still running until the last line with "ETA: 44s" that hold there for over 1day without progress. In my Activity Monitor, I can still see that tool "muscle" is running. Can you tell me if this is common? Is this the most time consuming part?

The other question is "re-run your last command with a `--debug` flag" in the warning message. What is "the last command" here? I was reluctant to do a re-run, as I'm not sure if the analysis will continue from the last checkpoint if I re-run? The analysis was running for over a week (I should put it on HPC but not available at the moment) and output over 1T files. So I really don't want to lose the progress. Can you please advise? Many thanks.

Below is my command and screen output: 

(anvio-7) fancy@AC02FV31AMD6P ANVIO % anvi-pan-genome -g ./pan-genome/3788-GENOMES.db --project-name "3788_Pan" --output-dir 3788_Pan  --num-threads 6

WARNING
===============================================
If you publish results from this workflow, please do not forget to cite DIAMOND
(doi:10.1038/nmeth.3176), unless you use it with --use-ncbi-blast flag, and MCL
(http://micans.org/mcl/ and doi:10.1007/978-1-61779-361-5_15)

Genomes storage ..............................: Initialized (storage hash: hashc395913b)                           
Num genomes in storage .......................: 3,788
Num genomes will be used .....................: 3,788
Pan database .................................: A new database,                                                    
                                                ./ANVIO/3788_Pan/3788_Pan-PAN.db,
                                                has been created.
Exclude partial gene calls ...................: False

AA sequences FASTA ...........................: ./ANVIO/3788_Pan/combined-aas.fa

Num AA sequences reported ....................: 6,375,599
Num excluded gene calls ......................: 0
Unique AA sequences FASTA ....................: ./ANVIO/3788_Pan/combined-aas.fa.unique
Diamond search db ............................: ./ANVIO/3788_Pan/combined-aas.fa.unique.dmnd
DIAMOND is set to be .........................: Fast
Diamond blastp results .......................: ./ANVIO/3788_Pan/diamond-search-results.daa
[03 Nov 21 06:15:37 DIAMOND] Un-uniqueing the tabular output ...                                                                                                                                                    Diamond un-uniquedtabular output file ........: ./ANVIO/3788_Pan/diamond-search-results.txt
                                                                                                          
WARNING
===============================================
DIAMOND did not retun search results for 112 of 6371778 the amino acid sequences
in your input FASTA file. Anvi'o will do some heuristic magic to complete the
missing data in the search output to recover from this. But since you are a
scientist, here are the amino acid sequence IDs for which DIAMOND failed to
report self search results: b89d090c5939_1191, b74f4ca1f512_476,
746ffaf61a55_981, 9a70d5050f86_85, 0cad4c900e48_703, c480317b7062_1996,
263680199f70_1062, f692842edbca_579, 253644ba3651_862, 72949a63ec73_2647,
a02e938161b5_220, bf60466f93b9_927, e759120e2db4_1313, 5806a76e30dc_67,
74859a6b8179_1379, b9b66ffabb4d_1710, 2bdd72e0d65e_766, 40401c9b7665_1540,
abfbdfe92eee_215, a079249198d9_718, 0cad4c900e48_992, 706865277d4c_1237,
c924803b6c49_393, e08646e0c51a_960, f42588004104_1117, af6b976fb597_62,
9e2a8d811322_629, 4189c0700ea9_1262, f706cf428433_362, 421329951455_1145,
114e6ae2d139_329, 421329951455_1131, dfa1e37242b7_262, 6bfc98195c35_1062,
9f21c4b1a0d1_1331, 9da10cf9282c_2327, 3239a180dd9a_702, 746ffaf61a55_115,
a9db9de189a9_504, b37e19a3c5d7_710, 97a94942c5c3_1614, 9d50c2f44b44_1305,
6b7d6f93d199_689, f753472ca22b_831, 0b0cb6056f6a_1562, 2f8fecc67a55_624,
def7e4bcc553_927, eee4aa1932fe_581, 722df1c3af80_868, bf60466f93b9_200,
746ffaf61a55_942, 746ffaf61a55_261, f5a57491a6a8_382, 74d48703285b_1577,
8e2cf3f0e344_567, 2195f86a941e_1369, 3ac98ecf0ed4_9, def7e4bcc553_1221,
37e3aa53efae_11, 8a3571a86455_350, e74252bee0e9_1529, e7600581136f_241,
d4b8dbc35596_699, 0cad4c900e48_718, 7078d44bfe57_994, a4b5041dc509_1908,
e8bdae6eb3bd_790, 50d5980df4a3_1071, 1683706fdb5d_410, d0b3fa03d08c_1545,
033da9b819a3_496, af41f5f06f20_998, 2f8fecc67a55_448, 411c7fec264b_207,
2adf0b40b3c4_1059, 2adf0b40b3c4_754, e8bdae6eb3bd_1185, c9db09ae7bf3_107,
876cbf2509fe_891, 2ca6ba0487d8_1854, 19b81417603c_541, 06c431af8127_567,
158a3f71af56_980, 08b0a9149e12_628, 38a64abeffa7_314, c924803b6c49_130,
7a2f82213a5c_125, b094d0893466_63, 8aa4f66b8fee_119, 746ffaf61a55_220,
51496ffde7b9_4629, ac3052f7db5b_898, d780b08f165e_432, 41cf5a90cac4_1703,
2ece6ed9b67f_1011, 72a8647efcb0_1415, abfb3319361b_762, d0b3fa03d08c_1115,
c81672a1075f_420, 7034257bf8d3_1319, 5e9a662f37a6_330, a6ab6c3b5be9_2599,
51496ffde7b9_435, afba6a7d469b_1151, 2d5a66b4c766_1922, a13aa449eaec_1254,
cf3ecd44068e_489, bf6ff98c5fe4_29, 0fbe77464c1b_1011, dad5ed50c1bf_655,
8a37ae2ba2c7_842, 23cc9b7e3512_1264.

Min percent identity .........................: 0.0
Minbit .......................................: 0.5
Filtered search results ......................: 1,421,779,648 edges stored                                
MCL input ....................................: ./ANVIO/3788_Pan/mcl-input.txt
MCL inflation ................................: 2.0
[04 Nov 21 15:07:01 MCL] clustering (using 6 thread(s)) ...                                                                                                                                                                     MCL output ...................................: ./ANVIO/3788_Pan/mcl-clusters.txt
Number of gene clusters ......................: 269,026
                                                                                                                
CITATION
===============================================
Anvi'o will use 'muscle' by Edgar, doi:10.1093/nar/gkh340
(http://www.drive5.com/muscle) to align your sequences. If you publish your
findings, please do not forget to properly credit their work.

[05 Nov 21 02:18:32 Aligning amino acid sequences for genes in gene clusters] Processed 66 o (...)  ETA: 1110w1d

WARNING
===============================================
VERY BAD NEWS. The alignment of sequences with 'Muscle' in the gene cluster
'GC_00000072' failed for some reason. Since the real answer to 'why' is too deep
in the matrix, there is no reliable solution for anvi'o to find it for you, BUT
THIS WILL AFFECT YOUR SCIENCE GOING FORWARD, SO YOU SHOULD CONSIDER ADDRESSING
THIS ISSUE FIRST. If you re-run your last command with a `--debug` flag, anvi'o
will generate more information for you about the contenets of this gene cluster
(but if you are seeing millions of these warnings, it may not be a good idea
since with the `--debug` flag anvi'o will generate a FASTA file in a temporary
directory with the contents of the gene cluster, and will not attempt to delete
them later).

[05 Nov 21 02:18:32 Aligning amino acid sequences for genes in gene clusters] Processed 416 o (...)  ETA: 231w5d

WARNING
===============================================
VERY BAD NEWS. The alignment of sequences with 'Muscle' in the gene cluster
'GC_00000420' failed for some reason. Since the real answer to 'why' is too deep
in the matrix, there is no reliable solution for anvi'o to find it for you, BUT
THIS WILL AFFECT YOUR SCIENCE GOING FORWARD, SO YOU SHOULD CONSIDER ADDRESSING
THIS ISSUE FIRST. If you re-run your last command with a `--debug` flag, anvi'o
will generate more information for you about the contenets of this gene cluster
(but if you are seeing millions of these warnings, it may not be a good idea
since with the `--debug` flag anvi'o will generate a FASTA file in a temporary
directory with the contents of the gene cluster, and will not attempt to delete
them later).

[05 Nov 21 02:18:32 Aligning amino acid sequences for genes in gene clusters] Processed 664 o (...)  ETA: 147w3d

WARNING
===============================================
VERY BAD NEWS. The alignment of sequences with 'Muscle' in the gene cluster
'GC_00000663' failed for some reason. Since the real answer to 'why' is too deep
in the matrix, there is no reliable solution for anvi'o to find it for you, BUT
THIS WILL AFFECT YOUR SCIENCE GOING FORWARD, SO YOU SHOULD CONSIDER ADDRESSING
THIS ISSUE FIRST. If you re-run your last command with a `--debug` flag, anvi'o
will generate more information for you about the contenets of this gene cluster
(but if you are seeing millions of these warnings, it may not be a good idea
since with the `--debug` flag anvi'o will generate a FASTA file in a temporary
directory with the contents of the gene cluster, and will not attempt to delete
them later).

[05 Nov 21 02:18:32 Aligning amino acid sequences for genes in gene clusters] Processed 1023 o (...) ETA: 96w5d 

WARNING
===============================================
VERY BAD NEWS. The alignment of sequences with 'Muscle' in the gene cluster
'GC_00001023' failed for some reason. Since the real answer to 'why' is too deep
in the matrix, there is no reliable solution for anvi'o to find it for you, BUT
THIS WILL AFFECT YOUR SCIENCE GOING FORWARD, SO YOU SHOULD CONSIDER ADDRESSING
THIS ISSUE FIRST. If you re-run your last command with a `--debug` flag, anvi'o
will generate more information for you about the contenets of this gene cluster
(but if you are seeing millions of these warnings, it may not be a good idea
since with the `--debug` flag anvi'o will generate a FASTA file in a temporary
directory with the contents of the gene cluster, and will not attempt to delete
them later).

[05 Nov 21 02:18:32 Aligning amino acid sequences for genes in gene clusters] Processed 17223 o (...) ETA: 5w3d 

WARNING
===============================================
VERY BAD NEWS. The alignment of sequences with 'Muscle' in the gene cluster
'GC_00017094' failed for some reason. Since the real answer to 'why' is too deep
in the matrix, there is no reliable solution for anvi'o to find it for you, BUT
THIS WILL AFFECT YOUR SCIENCE GOING FORWARD, SO YOU SHOULD CONSIDER ADDRESSING
THIS ISSUE FIRST. If you re-run your last command with a `--debug` flag, anvi'o
will generate more information for you about the contenets of this gene cluster
(but if you are seeing millions of these warnings, it may not be a good idea
since with the `--debug` flag anvi'o will generate a FASTA file in a temporary
directory with the contents of the gene cluster, and will not attempt to delete
them later).

[05 Nov 21 02:18:32 Aligning amino acid sequences for genes in gene clusters] Processed 176131 o (...) ETA: 44s

**Comment by meren** [comment]
Hi @fancyge,

It is kind of astonishing to me that this workflow came even this far with over 3,500 genomes, and over 6 million amino acid sequences to process over 1 billion edges and 250,000 gene clusters 😂

Anvi'o is not quite suitable for that kind of analysis.

I changed the code so it will not allow the users to analyze more than 100 genomes without admitting that they know it is not a good idea. Here is the error message anvi'o will produce going forward:

```
Config Error: Sorry for making you wait this long to tell you this, but you have a total of 3,788
              genomes to process, and anvi'o may not be the best platform to do that. The
              anvi'o pangenomics workflow is designed for interactive and in-depth
              investigations of microbial pangenomes. While one can certainly perform an in-
              depth investigation of their 3,788 genomes by turning them into a pangenome, they
              will unlikely manage to do it with anvi'o with more than about 100 genomes. We
              can't stop you if you insist running a pangenomic analyses on your genomes
              ANYWAY. For instance, you can easily force anvi'o to start the analysis using
              the flag `--I-know-this-is-not-a-good-idea`. But by using that flag, you will be
              forfeiting your privilege to complain to anvi'o developers if something goes
              wrong with your analyses :)
```

Best,
