### ISSUE TITLE
Running out of /tmp memory running anvio-compute-genome-similarity with pyANI on HPC

### ISSUE THREAD

**Issue by rgtaketani** [merenlab/anvio#1844]
## Short description of the problem

I am running a anvio in our HPC. Most of the pipieline ran well but I am running out of /tmp memory in the node when running anvio-compute-genome-similarity with pyANI. I already set the TMPDIR to another folder but it is still using the nodes tmp. Is there a work around it?

## anvi'o version

```
Anvi'o version ...............................: esther (v6.1)
Profile DB version ...........................: 31
Contigs DB version ...........................: 14
Pan DB version ...............................: 13
Genome data storage version ..................: 6
Auxiliary data storage version ...............: 2
Structure DB version .........................: 1
```

## System info

We are using the version available in EasyBuild for our HPC. I ran it with 8 cores (tried with 24 also), 200Gb of RAM and a /tmp of 10Gb.

## Detailed description of the issue

```
CITATION
===============================================
Anvi'o will use 'PyANI' by Pritchard et al. (DOI: 10.1039/C5AY02550H) to compute
ANI. If you publish your findings, please do not forget to properly credit their
work.

[PyANI] Num threads to use ...................: 8
[PyANI] Alignment method .....................: ANIb
[PyANI] Log file path ........................: /tmp/tmpzqwz5pjo


WARNING
===============================================
You are comparing 114 genomes. That's no small task. For context, 10
Prochlorococcus genomes using 4 threads took 2m20s on a 2016 Macbook Pro. And 50
genomes took 49m53s. Consider instead using sourmash (--program sourmash). On
the same Macbook with 1 thread using sourmash, these times were 12s and 42s,
respectively.


                                                                                                                        
[48;5;6m[38;5;0m
[22 Nov 21 10:13:57 PyANI] Running ...                                                                                 [0m
                                                                                                                        
✖ anvi-compute-genome-similarity encountered an error after 1 day, 4:03:19.230321

```

From the PyANI log:

```
# DATE: 22 Nov 21 10:13:57
# CMD LINE: average_nucleotide_identity.py --outdir output --indir /tmp/tmpsoq1acnd --method ANIb --workers 8
```

It ends with:

```
OSError: [Errno 28] No space left on device
```

**Comment by meren** [comment]
> I already set the TMPDIR to another folder but it is still using the nodes tmp. Is there a work around it?

Hey, @rgtaketani, can you please find out if there is a parameter for PyANI to explicitly set a temporary directory?

**Comment by rgtaketani** [comment]
Hi @meren 

From the log I see that average_nucleotide_identity.py is setting  --indir /tmp/tmpsoq1acnd. This folder is the one filling up the nodes memory. The pyANI documentation doesn't have a tmp dir setting in its documentation. 

# CMD LINE: average_nucleotide_identity.py --outdir output --indir /tmp/tmpsoq1acnd --method ANIb --workers 8

**Comment by meren** [comment]
If wonder if this is happening because the `TMPDIR` environmental variable you've set is not reaching to the HPC node as an environment variable.

Can you please submit a job that that sets the `TMPDIR`, but then instead of running anything else, runs only this command:

```
echo $TMPDIR
```

**Comment by rgtaketani** [comment]
Hi @meren 
When I put 'echo $TMPDIR' in my sbatch script, I get '/tmp'. When I add 'export TMPDIR=/home/data/myfolder/tmp' and then 'echo $TMPDIR', I get
'/home/data/myfolder/tmp'.
So, the 'export' is getting there.

**Comment by meren** [comment]
Hey @rgtaketani, I checked the code, everything seems good and things should work as expected.

It looks to me that when you set a `TMPDIR` explicitly, anvi'o will pass that as the `--indir` parameter to PyANI for it to use that particular path to store temporary files. Which means, if you want PyANI to NOT use the default temporary directory of a given node when run on an HPC, you should set your TMPDIR to somewhere that is shared across all nodes and has enough space (like your home directory).

But you're saying this doesn't work even though `TMPDIR` is doing its job. Am I correctly interpreting the situation here?

**Comment by rgtaketani** [comment]
Dear @meren ,

> But you're saying this doesn't work even though TMPDIR is doing its job. Am I correctly interpreting the situation here?
Yes, even when I set `TMPDIR` pyANI still runs in the nodes `/tmp`.

**Comment by meren** [comment]
I found out the problem, @rgtaketani.

This is happening, because the path you set using the environmental variable `TMPDIR` does not exist.

Here is an example, where I set the `TMPDIR` as a directory that doesn't exist:

``` bash
$ export TMPDIR="/TEST-TMP/"
$ ls $TMPDIR
ls: cannot access '/TEST-TMP/': No such file or directory

$ anvi-compute-genome-similarity -e external-genomes.txt --program pyANI -o OUTPUT

CITATION
===============================================
Anvi'o will use 'PyANI' by Pritchard et al. (DOI: 10.1039/C5AY02550H) to compute
ANI. If you publish your findings, please do not forget to properly credit their
work.

[PyANI] Num threads to use ...................: 1
[PyANI] Alignment method .....................: ANIb
[PyANI] Log file path ........................: /tmp/tmps5vv8yhi

(...)
```

In this case Python sets the temp dir to `/tmp/tmps5vv8yhi` becasue `/TEST-TMP/` does not exist.

In contrast, this is what happens if I create it first:

``` bash
$ mkdir $TMPDIR
```

And then run `anvi-compute-genome-similarity`:

``` bash
$ anvi-compute-genome-similarity -e external-genomes.txt --program pyANI -o OUTPUT

CITATION
===============================================
Anvi'o will use 'PyANI' by Pritchard et al. (DOI: 10.1039/C5AY02550H) to compute
ANI. If you publish your findings, please do not forget to properly credit their
work.

[PyANI] Num threads to use ...................: 1
[PyANI] Alignment method .....................: ANIb
[PyANI] Log file path ........................: /TEST-TMP/tmpeo1_qc25
```

So you just need to create the directory you're using with `TMPDIR`.

**Comment by rgtaketani** [comment]
@meren thank you for your help. Sorry for the rookie mistake.
