### ISSUE TITLE
anvi-display-functions doesn't recognize --gene-caller flag

### ISSUE THREAD

**Issue by VManning** [merenlab/anvio#1847]
## Short description of the problem

anvi-display-functions doesn't recognize --gene-caller flag

## anvi'o version

hope (v7.1)
```

## System info

MacOs Big Sur on a Mac Pro with 3.2 GHz 16-Core Intel Xeon W Processor, 96 GB 2933 MHz DDR4 Memory. Anvi'o was installed with miniconda

## Detailed description of the issue

I intended to use anvi-display-functions to display COG annotations for diverse genomes of a low complexity metagenome to get an idea of enriched functions in the different genomes. These genomes had been annotated with RastTk in another platform. The external-gene-calls file contains Kbase-Rasttk in the source column.

Ran this command:
anvi-display-functions -e external_genomes.txt -g pan1-5-GENOMES.db --annotation-source COG20_FUNCTION -p COG20-PROFILE.db --min-occurrence 2

Config Error: None of your genomes seem to have a gene call, which is a typical error you get
       if you are working with contigs databases with external gene calls. You can   
       solve it by looking at the output of the program `anvi-db-info` for a given   
       contigs database in your collection, and use one of the gene caller sources   
       listed in the output using the `--gene-caller` parameter. 

Reran with --gene-caller flag
anvi-display-functions -e external_genomes.txt -g pan1-5-GENOMES.db --annotation-source COG20_FUNCTION -p COG20-PROFILE.db --gene-caller Kbase-Rasttk --min-occurrence 2  

And got this:
anvi-display-functions: error: unrecognized arguments: --gene-caller Kbase-Rasttk 

                                               
There appears to be a bug.

**Comment by meren** [comment]
This should be now done. Thank you very much for the report, @VManning!

**Comment by VManning** [comment]
Hi @meren,

Thank you for working on this. Unfortunately I tried again and got the same error:

(anvio-7.1) manniv@x86_64-apple-darwin13 PAN12 % anvi-display-functions -e external_genomes.txt -g pan12-GENOMES.db --annotation-source COG20_FUNCTION --gene-caller Prodigal -p COG20-PROFILE.db --min-occurrence 2   

usage: anvi-display-functions [-h] [-i FILE_PATH] [-e FILE_PATH]                                                                       
                              [-g GENOMES_STORAGE] [-G TEXT_FILE]
                              [--print-genome-names-and-quit]
                              --annotation-source SOURCE NAME
                              [--aggregate-based-on-accession]
                              [--aggregate-using-all-hits]
                              [--min-occurrence NUM GENOMES] -p PROFILE_DB
                              [--title NAME] [--state-autoload NAME]
                              [--collection-autoload NAME]
                              [--export-svg FILE_PATH] [--dry-run]
                              [--skip-news] [-I IP_ADDR] [-P INT]
                              [--browser-path PATH] [--read-only]
                              [--server-only] [--password-protected]
                              [--user-server-shutdown] [--version] [--debug]
                              [--force] [--fix-sad-tables] [--quiet]
                              [--no-progress] [--as-markdown]
                              [--tmp-dir TMP_DIR] [--display-db-calls]
                              [--force-use-my-tree]
anvi-display-functions: error: unrecognized arguments: --gene-caller Prodigal

Shucks!

**Comment by ivagljiva** [comment]
Hi @VManning, the bug fix that Meren did was pushed into our development branch, so you will not see it reflected in v7.1 :)

You should install the dev branch by following [the instructions here](https://merenlab.org/2016/06/26/installation-v2/#5-follow-the-active-development-youre-a-wizard-arry) and then try again with that version of anvi'o!

**Comment by VManning** [comment]
Oh, That makes a lot of sense.

Sounds scary, but I’ll try it (I am not a wizard!)

v

From: Iva Veseli ***@***.***>
Date: Wednesday, December 15, 2021 at 9:49 AM
To: merenlab/anvio ***@***.***>
Cc: Manning, Viola ***@***.***>, Mention ***@***.***>
Subject: Re: [merenlab/anvio] anvi-display-functions doesn't recognize --gene-caller flag (Issue #1847)

Hi @VManning<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FVManning&data=04%7C01%7C%7C7c324e0b541642e9e8a608d9bff33143%7Ced5b36e701ee4ebc867ee03cfa0d4697%7C0%7C0%7C637751873489301268%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=mfIv1iBoeZLzU0cXOsr%2FAPUbViZMyi%2BYrpcC9G14ogk%3D&reserved=0>, the bug fix that Meren did was pushed into our development branch, so you will not see it reflected in v7.1 :)

You should install the dev branch by following the instructions here<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fmerenlab.org%2F2016%2F06%2F26%2Finstallation-v2%2F%235-follow-the-active-development-youre-a-wizard-arry&data=04%7C01%7C%7C7c324e0b541642e9e8a608d9bff33143%7Ced5b36e701ee4ebc867ee03cfa0d4697%7C0%7C0%7C637751873489301268%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=YXzl1q8g5nfeQJVGmFjnnmM14%2By9MIfGoN%2Ff078lr2o%3D&reserved=0> and then try again with that version of anvi'o!

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmerenlab%2Fanvio%2Fissues%2F1847%23issuecomment-995023615&data=04%7C01%7C%7C7c324e0b541642e9e8a608d9bff33143%7Ced5b36e701ee4ebc867ee03cfa0d4697%7C0%7C0%7C637751873489311226%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=D04K6WMcF%2Bhl25bZfOfrzlVHqWjp5cma31wwJnrzfcQ%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAQVB4V6EXUB3WJL6EC5VTT3URDIJFANCNFSM5JAMHQIA&data=04%7C01%7C%7C7c324e0b541642e9e8a608d9bff33143%7Ced5b36e701ee4ebc867ee03cfa0d4697%7C0%7C0%7C637751873489311226%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Hiw%2Bop9SY5EvilVFygztAM3%2B%2BKj8MuOU%2BW0pxL4Y4tE%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C7c324e0b541642e9e8a608d9bff33143%7Ced5b36e701ee4ebc867ee03cfa0d4697%7C0%7C0%7C637751873489321180%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=txY6eQsZ4hJxikmWu86XuUA24hUX1bLzujpZEZhw4BY%3D&reserved=0> or Android<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7C7c324e0b541642e9e8a608d9bff33143%7Ced5b36e701ee4ebc867ee03cfa0d4697%7C0%7C0%7C637751873489321180%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=DNRVcdCK2aabyVokNiE0Iy048zDyY%2FXZALbwQ8toslw%3D&reserved=0>.




This electronic message contains information generated by the USDA solely for the intended recipients. Any unauthorized interception of this message or the use or disclosure of the information it contains may violate the law and subject the violator to civil or criminal penalties. If you believe you have received this message in error, please notify the sender and delete the email immediately.

**Comment by ivagljiva** [comment]
Anyone can be a wizard! 😉 

Feel free to let us know if you run into issues!
