### ISSUE TITLE
[FEATURE] Anvi'o pangenomics self test is BORING!

### ISSUE THREAD

**Issue by matthewlawrenceklein** [merenlab/anvio#1848]
## The need

The slumbering behemoth known as `Genome View` currently lies dormant, its genome clustering abilities waiting silently in the wings. Meanwhile, rumblings from the current Anvio user base speak towards a common need - our pangenomics test files are _boring_, and we need to spice them up!

## The solution

More exciting test files for Anvio's pangenomics self test

## Beneficiaries

self-testers at large, but especially users of the yet-to-be-finalized `genome-view` self test and tutorial, who will be able to utilize `Genome View`'s clustering features in a test environment :)

**Comment by meren** [comment]
There is no call we do not answer. There is no faith that we betray.

If the pangenomics self test is boring, we make it unboring (it is now brewing in #1849).

Atreides. Atreides. Atreides. Atreides. Atreides. Atreides.

**Comment by matthewlawrenceklein** [comment]
> There is no call we do not answer. There is no faith that we betray.
> 
> If the pangenomics self test is boring, we make it unboring (it is now brewing in #1849).
> 
> Atreides. Atreides. Atreides. Atreides. Atreides. Atreides.

The self tests must flow!

**Comment by meren** [comment]
This is no longer the case.

Here's the screenshot of the pangenome new test yields:

<img width="1372" alt="image" src="https://user-images.githubusercontent.com/197307/162973150-ab12f2d0-3469-4b85-b95b-3c3d2b86d16e.png">
