### ISSUE TITLE
Combining metagenome & metatranscriptome

### ISSUE THREAD

**Issue by Tsingsjeen** [merenlab/anvio#1866]
When I am going to combine the metagenomes and metatranscriptomes, I met this problem:

```
anvi-experimental-organization my_cluster_config.ini -i merged/ -c contigs.db -p merged/PROFILE.db --skip-store-in-db -o new_newick_tree.txt

**Config Error: store array: header length (3) differs from data (4)...**
```

Do you know what is wrong with that?

Here is my "my_cluster_config.ini":

```
[general]

[TNF !CONTIGS.db::kmer_contigs]

[Coverage PROFILE.db::mean_coverage_contigs]
columns_to_use = sort_NS_PCE,sort_S_PCE

[Coverage_N PROFILE.db::mean_coverage_contigs]
columns_to_use = sort_NS_PCE,sort_S_PCE
normalize = False
log = True

[GC_content !CONTIGS.db::splits_basic_info]
columns_to_use = gc_content_parent,gc_content_parent,gc_content_parent
normalize = False
```

This was also pended at anvi'o webpage: http://disq.us/p/2lix1p0

**Comment by meren** [comment]
Thank you very much for this report, @Tsingsjeen! I solved the problem by updating the tutorial with https://github.com/merenlab/web/commit/d1455bdc4bb6eb69aa23f4800601c2ed95a956ac. It turns out the config template did not reflect most recent changes in the codebase.

Can you please try again using the new instructions in [the tutorial](https://merenlab.org/2015/06/10/combining-omics-data/)?

Thanks again.

**Comment by Tsingsjeen** [comment]
Hi Meren,


Thanks!


I tried to rerun the code again, there is still the same problem as below.


########################################################################################################################################
(anvio-7.1) ***@***.***:/work/chen03/marine_AB/chen_run/meta_DR/anvio$ anvi-experimental-organization my_cluster_config.ini -i merged/ -c contigs.db -p merged/PROFILE.db --skip-store-in-db -o new_newick_tree.txt




Config Error: store array: header length (3) differs from data (4)...


#########################################################################################################################################


I have no idea what is going on. thanks for you kind help, ;-)!




Best,


Chen



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "merenlab/anvio"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月25日(星期六) 晚上7:32
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [merenlab/anvio] Combining metagenome &amp; metatranscriptome (Issue #1866)





 
Thank you very much for this report, @Tsingsjeen! I solved the problem by updating the tutorial with ***@***.*** It turns out the config template did not reflect most recent changes in the codebase.
 
Can you please try again using the new instructions in the tutorial?
 
Thanks again.

**Comment by meren** [comment]
Can you post your `my_cluster_config.ini` again?

**Comment by Tsingsjeen** [comment]
Thanks!


##############################################################################
[general]


[TNF !CONTIGS.db::kmer_contigs]


[Coverage PROFILE.db::mean_coverage_contigs]
columns_to_use = sort_NS_PCE,sort_S_PCE


[Coverage_N PROFILE.db::mean_coverage_contigs]
columns_to_use = sort_NS_PCE,sort_S_PCE
normalize = False
log = True


[GC_content !CONTIGS.db::splits_basic_info]
columns_to_use = gc_content_parent,gc_content_parent,gc_content_parent
normalize = False
###############################################################################


Best,


Chen





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "merenlab/anvio"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月26日(星期天) 凌晨4:52
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [merenlab/anvio] Combining metagenome &amp; metatranscriptome (Issue #1866)





 
Can you post your my_cluster_config.ini again?

**Comment by meren** [comment]
Yeah, this is the old stuff, @Tsingsjeen. I mentioned that you should follow the up-to-date tutorial:

> Can you please try again using the new instructions in [the tutorial](https://merenlab.org/2015/06/10/combining-omics-data/)?

This issue is resolved.

**Comment by Tsingsjeen** [comment]
Hi Meren,


That is amazing, now it worked, ;-)!


Merry Christmas!




Best,


Chen




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "merenlab/anvio"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月26日(星期天) 凌晨4:58
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [merenlab/anvio] Combining metagenome &amp; metatranscriptome (Issue #1866)





 
Yeah, this is the old stuff, @Tsingsjeen. I mentioned that you should follow the up-to-date tutorial:
  
Can you please try again using the new instructions in the tutorial?
  
This issue is resolved.
