### ISSUE TITLE
[BUG] conda install r-tidyverse fail

### ISSUE THREAD

**Issue by TonyMane** [merenlab/anvio#1868]
## Short description of the problem

Issue trying to download and install r-tidyverse for further use of anvio-master brach.

## anvi'o version
Master branch installation.
```
anvi-self-test --version
```
NA
## System info
```
Distributor ID:	Centos
Description:	Centos release 6.7 (Final)
Release:	6.7
Codename:	Final
```

## Detailed description of the issue

Below is the command i am submitting through our workload manager.
Out of desperation, i tried the 'conda install' command after loading a python3 environment and reconfiguring channels, independently, just to see if that would work.
```
#!/bin/bash
##first MaxBin run; MaxBin of random one fastq file
#SBATCH --job-name    condaTidyV        # job name
#SBATCH --output      condaTidyV-%j.out # standard output file (%j = jobid)
#SBATCH --error       condaTidyV-%j.err # standard error file
#SBATCH --partition   defq      # queue partition to run the job in
#SBATCH --nodes       1            # number of nodes to allocate
#SBATCH --ntasks-per-node 1        # number of descrete tasks - keep at one except for MPI 
#SBATCH --cpus-per-task=1          # number of CPU cores to allocate
#SBATCH --mem         20000         # 2000 MB of Memory allocated; set --mem with care
#SBATCH --time        24:00:00     # Maximum job run time
##SBATCH --mail-user   $email      # user to send emails to
##SBATCH --mail-type   ALL         # Email on: BEGIN, END, FAIL & REQUEUE
## Run 'man sbatch' for more information on the options above.

#module load python3

#conda config --add channels conda-forge

#conda config --set channel_priority strict

conda install -y -c bioconda r-tidyverse
```

## Files to reproduce

[condaTidyV-2175229.tar.gz](https://github.com/merenlab/anvio/files/7798158/condaTidyV-2175229.tar.gz)ave files that you can share with us to reproduce the issue (i.e., a contigs database, a profile database, a BAM file, etc), they may help us dramatically. Please put them in a single directory, compress the directory, upload it to Dropbox (or any other comparable service), and share with us a direct download link along with instructions on how to reproduce the error.

The error files is quite long, and i'm not sure how to interpret it (condaTidyV-2175229.tar.gz).
Any assistance would be welcome.

Thank you!

**Comment by xvazquezc** [comment]
You are in a environment with Python 3.9. The instructions for installing anvi'o specify 3.6 for a reason.

**Comment by meren** [comment]
Thanks, @xvazquezc! This clearly fell through the cracks, but I hope you solved the problem, @TonyMane.
