### ISSUE TITLE
[BUG] Problems reproducing visualization created with anvi-display-functions

### ISSUE THREAD

**Issue by dpbisme** [merenlab/anvio#1870]
## Short description of the problem

Visualization created by `anvi-display-functions` loses all layer info when attempting to reproduce viz with `anvi-interactive --manual`

## anvi'o version

Anvi'o .......................................: hope (v7.1)

Profile database .............................: 38
Contigs database .............................: 20
Pan database .................................: 15
Genome data storage ..........................: 7
Auxiliary data storage .......................: 2
Structure database ...........................: 2
Metabolic modules database ...................: 2
tRNA-seq database ............................: 2

## System info

Running MacOS 'Monterey' v12.1.  Anvi'o was installed via miniconda

## Detailed description of the issue

When I run the `anvi-display-functions` program, I get a viz that makes sense and I have no problem customizing the display (see attached).  However, if I save the viz state and relaunch by passing the profile.db produced by `anvi-display-functions` to `anvi-interactive --manual`, I lose all my layers (see other attached image).  All other interactive aspects of anvi'o are working fine (e.g. creating, saving, reloading a pangenome).  

<img width="664" alt="anvi-display-functions" src="https://user-images.githubusercontent.com/3161263/148242392-0a027218-63d7-4dac-83d1-6733d94b8fe6.png">
<img width="691" alt="anvi-interactive" src="https://user-images.githubusercontent.com/3161263/148242393-ccc90675-c00e-4967-aee2-465838b3efc9.png">

**Comment by meren** [comment]
Thank you very much for the report, @dpbisme. 

I could reproduce this bug by running the following commands:

``` bash
# once the browser pops up make some changes
# and update the default state
anvi-self-test --suite display-functions -o DF

# kill the server, and re-run anvi-interactive 
anvi-interactive -p DF/functions_display/COG20_FUNCTION.db --manual
```

**Comment by FatherofEverest** [comment]
I have encountered the same problem unfortunately and hate to be a nag, but would love to see this addressed. I find the figures that can be produce to be pretty great.

**Comment by meren** [comment]
It is already addressed. Unfortunately it is in the active development branch, and not yet in a stable release.

Many apologies for the inconvenience.

**Comment by meren** [comment]
Following the active development branch is easy and is explained in the installation instructions :)
