### ISSUE TITLE
[E::bwa_idx_load_from_disk] fail to locate the index files [main_samview] fail to read the header from "-".

### ISSUE THREAD

**Issue by ArtuManga19** [merenlab/anvio#1882]
Hi! I'm new in this world and i need help to understand how to overcome the problem that i have. I used bwa mem for the alignment of a sample with hg38 reference genome and got this error, can't really understand why. The code that i'm running is this one:

`bwa mem /home/arturo/Documenti/hg38.fa /home/arturo/Documenti/PATIENT/PATIENT_TRIMMED/PATIENT-BM_S7_L001_R1_001_trimmed.fastq.gz /home/arturo/Documenti/PATIENT/PATIENT_TRIMMED/PATIENT-BM_S7_L001_R2_001_trimmed.fastq.gz | samtools view -bS - > /home/arturo/Documenti/PATIENT/PATIENT_BAM/PATIENT_BM_unsorted.bam` 
the output is: 

`[E::bwa_idx_load_from_disk] fail to locate the index files [main_samview] fail to read the header from "-".`

What could be wrong here??
I have also another question: the hg38 reference genome should be unzipped once downloaded or not?

**Comment by matthewlawrenceklein** [comment]
Hi @ArtuManga19, I'm not a samtools expert but I'll give it a swing!

this snippet `| samtools view -bS - >`, coupled with the error message `fail to read the header from "-"` leads me to believe that samtools expects a target filename in the above command, and is instead seeing `-`. 

Here's an example from the samtools-view [manpage](http://www.htslib.org/doc/1.11/samtools-view.html) that shows the correct command formatting. 
`samtools view -bS aln.sam > aln.bam` 

Hope that helps!

**Comment by ArtuManga19** [comment]
I've read the page you suggested (thanks) and technically might be right. The only issue is that i'm in the process of creating SAM files because i still have to align the samples to the reference genome so the example that you've suggested might fit the process of SAM conversion into BAM file once i have it. 

Plus the first error that it says is `[E::bwa_idx_load_from_disk] fail to locate the index files` but the indexing step should be done after the creation of the BAM file, am i wrong? 

I tried to modify anyway the `| samtools view -bS - >` with different variant but is still giving me the same error. The absurd part is that colleagues of mine are running the same code and it works for them.

**Comment by meren** [comment]
Hi @ArtuManga19, sorry you're dealing with this. This looks to me like an issue that perhaps is more suitable to address by the developers of BWA or samtools. You can also come to the anvi'o Slack channel to see if there are people with more experience with this issue who can help :)

Best wishes,
