### ISSUE TITLE
[BUG] anvi-export-gene-calls behaviour

### ISSUE THREAD

**Issue by xvazquezc** [merenlab/anvio#1884]
Hi folks,
I'm not completely sure if this falls under bugs or feature requests but here it is...

First, if you run `anvi-export-gene-calls --help` all flags/options appear under "Optional arguments", which doesn't seem right to me. At very least you need a contigs database...

Second, [in the documentation](https://anvio.org/help/main/programs/anvi-export-gene-calls/), it's stated that we should run `anvi-export-gene-calls -c contigs-db --list-gene-callers` first and then request the gene caller of our choice. However, if you omit the `--gene-caller` option, the program will start normally, i.e., loading the db in memory before exiting because you haven't specify the gene caller. This might not be too bad for small databases but for large ones it can take a good amount of time until it fails (happened to me yesterday).

I think there could be a couple of possible alternatives to this:
- make the `--gene-caller` argument compulsory, i.e., error and exit right away if missing, or
- If `-gene-caller` is missing, automatically check for gene calls before anything else (as per `--list-gene-callers`) and either export all gene calls, or exit with error.

Cheers,
Xabi

PS: running anvi'o devel branch on Linux

**Comment by meren** [comment]
Good points, @xvazquezc, which are now addressed :)
