### ISSUE TITLE
[FEATURE REQUEST] A streamlined interactive interface without all the ~ stuff ~

### ISSUE THREAD

**Issue by matthewlawrenceklein** [merenlab/anvio#1894]
## The need

Sometimes, our data is __big__. And __mean__. And doesn't want to play nice with our beloved interactive interface. That's a pain. Ideally, anvi'o should warn the user when it introspects incoming data and expects the possibility of a slow, bogged-down session. Better yet, we should  allow the user to pass a flag from the terminal to let the interactive interface know that we just want a visualization. Hold the tables, legends, and pickles please!

## The solution

Workin on it ;) . Step one is to root out our bottlenecks, step two would be to see if we can address them, step three would be to see if we can remove them entirely in the case of a `just-the-vis-please` session. @meren had mentioed the user of a profiler to get a better sense of how things are flowing through the interface (credits to @ekiefl for the inspo), so I'll start with javascript's built in [console.profile](https://docs.w3cub.com/dom/console/profile) and go from there !

## Beneficiaries

Folks with big giant datasets that don't require a mandatory 30 minute break in between renders + loads :)

**Comment by matthewlawrenceklein** [comment]
woah, ok! So I'm working on [this](https://github.com/merenlab/anvio/tree/giant_tree_testing) branch, and I believe I can point to our processes for generating legends and populating color dicts as the main culprits RE performance. Removing those processes from the interface improved the initial load performance of our giant test tree from ~ 75 minutes to ~ 20 seconds! Wowzers! Gonna keep digging there

**Comment by meren** [comment]
😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱 😱

**Comment by matthewlawrenceklein** [comment]
alright folks! so given that our largest performance bottleneck appears to be item-level legends color dicts, we're going to set a cutoff for how we display legends in the user interface. That will look something like

- if a layer has < 20 categorical data layers associated with it, we proceed as normal
- if a layer has > 20 categorical data layers associated with it
    - we alert the user (via toastr or within the legends tab) that their layers containing many CDLs will be rendered differently within the legends tab
    - we render out a text input field within the legends layer dropdown so users can query against the specific CDL they want to manipulate
    - users can make/submit color/other(?) changes at the per-item level
    - we do not need to render out items for a billion CDLs

@meren et al, please feel free to add/correct anything I may have missed. Exciting stuff! :)

**Comment by meren** [comment]
Yes! :)

**Comment by matthewlawrenceklein** [comment]
@meren the proposed solution for this legends tab refactor for each legend (ie class, domain, family) consists of:

- a text input box for the user to input their item of interest
- a color picker to select their desired color
- a submit button that
    - queries for the item provided
        - upon no matches, returns an error message
        - upon a match, updates the item's color value and returns  a success message

The above process captures the legend to be queried, as well as the query string and colorpicker value. 

As far as I can tell, this query/update should occur in the `categorical_data_colors` global object. The issue is that this object has generic numeric keys, and so I don't appear to be able to query against specific legends. Instead, I'd need to query against the entire `categorical_data_colors` object - not exactly performant. 

Are there implications to refactoring the `categorical_data_colors` object keys to match their respective legends? That way we'd be able to query `categorical_data_colors[legend][item_name]` directly.

**Comment by matthewlawrenceklein** [comment]
@meren I think this is ready for testing :D

**Comment by meren** [comment]
I tried it with infant gut, I got this error:

![image](https://user-images.githubusercontent.com/197307/158641919-b4676844-b440-48b4-b64c-598385ac137d.png)

Then tried it with 

```
anvi-self-test --suite interactive-interface
```

Got the same error. Can you please double-check?

**Comment by meren** [comment]
Oi. I followed this link, and ended up at the wrong place:

![image](https://user-images.githubusercontent.com/197307/158650044-8f7bf92e-722e-40d8-9b07-9813c1e9a6e2.png)

For future references, it is best to start a PR from the branch to be tested so we can discuss under the PR :) I'm testing it now!

**Comment by meren** [comment]
I'm testing it with Infant gut dataset, the marking shows where my mouse is, which clearly is `db_bin_1` in GROOPM:

![image](https://user-images.githubusercontent.com/197307/158650998-5744adfa-c2e0-48da-8479-55a269535552.png)

I'm not sure how did you test this feature and whether I'm doing something wrong, but querying that text gives me this error:

![image](https://user-images.githubusercontent.com/197307/158651086-5b1c21f6-4d9a-499b-bd32-502f9813558b.png)


This ALSO makes me realize a much needed feature. When your mouse-pointer is on a particular cell, there could be another item in the right-click menu that says "edit legend color" if applicable, which would jump to the relevant categorical value color editing section in the Legends tab with the right query already run. Does it make sense?

**Comment by matthewlawrenceklein** [comment]
>  but querying that text gives me this error:

I'll look into this, thanks!

>This ALSO makes me realize a much needed feature.

Making sure I understand this correctly:
- A user can right-click on a cell to access the mouse-context-menu, where they should find an 'edit legend color` option to click
- upon click, we
    - expand the settings pane
    - make the legends tab the active tab
    - open the accordion-menu for the appropriate legend
    - if the legend in question has > 20 layers, we see the query menu
        - we autofill the input field with the relevant cell name 
    - if the legend in question has < 20 layers, we do nothing since each layer should be directly manipulable from the legend menu

does that sound correct?

**Comment by meren** [comment]
> does that sound correct?

100% :)

**Comment by matthewlawrenceklein** [comment]
RE our discussion today:

- Language
    - the new legends tab implementation takes a __category__ as input, and has an __update color__  button
- Bug
    - a subset of layers incorporated via flat text files are giving us issues. I'll explore this using the IGD
- Quality of life  additions
    - the above mentioned right click context-menu functionality
    - new legends tab implementation should include a color picker + button to set __all__ categories in a layer to a color
    - new legends tab implementation should include a button to randomize __all__ category colors in a layer
    - the above buttons should trigger an update to the effected categories without requiring an additional re-draw a la how we set bin colors

**Comment by meren** [comment]
This is done (not in a way that we envisioned, but in a way that made @matthewlawrenceklein discovered and solved the legends bottleneck :)).
