### ISSUE TITLE
Issues with pysam installation using pip: Levenshtein wheel error

### ISSUE THREAD

**Issue by HMorrison** [merenlab/anvio#1896]
## Short description of the problem

pip install anvio-7.1.tar.gz fails even after resinstalling x-code (https://github.com/merenlab/anvio/issues/1636)

## anvi'o version
(anvio-7.1) morrison2: anvi-self-test --version
Traceback (most recent call last):
  File "/usr/local/bin/anvi-self-test", line 12, in <module>
    import anvio
ModuleNotFoundError: No module named 'anvio'

```
anvi-self-test --version
```

## System info

Please tell us which operating system you are using, and how did you install anvi'o.
macOS Monterey v. 12.1
installing using https://anvio.org/install/#3-install-anvio conda procedure

## Detailed description of the issue

Error messages (full version attached):

```
[anvio7.1_pip_install_errors.txt](https://github.com/merenlab/anvio/files/8201186/anvio7.1_pip_install_errors.txt)

    Running setup.py install for python-Levenshtein ... error
    ERROR: Command errored out with exit status 1:
    /Users/morrison/miniconda3/envs/anvio-7.1/include/python3.6m/Python.h:25:10: fatal error: 'stdio.h' file not found
    1 error generated.
    error: command 'clang' failed with exit status 1
ERROR: Command errored out with exit status 1: /Users/morrison/miniconda3/envs/anvio-7.1/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/kw/_gn7bf0s0s14m3c_m369b5gm0000gn/T/pip-install-_co3sk49/python-levenshtein_9906ce56e2294ebf95e983ccacd706af/setup.py'"'"'; __file__='"'"'/private/var/folders/kw/_gn7bf0s0s14m3c_m369b5gm0000gn/T/pip-install-_co3sk49/python-levenshtein_9906ce56e2294ebf95e983ccacd706af/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/kw/_gn7bf0s0s14m3c_m369b5gm0000gn/T/pip-record-jhvmvax4/install-record.txt --single-version-externally-managed --compile --install-headers /Users/morrison/miniconda3/envs/anvio-7.1/include/python3.6m/python-Levenshtein Check the logs for full command output.
```

**Comment by meren** [comment]
Hey Hilary, did you re-create your conda environment after `xcode-select --install` in a fresh terminal?

**Comment by HMorrison** [comment]
I believe that I had *not*. 

I tried again--fresh window today. NB: prompt initially says "(base) morrison2:", where it used to just say "morrison2:". I forgot the second two steps of the fix, re. clang. 

This time: 
Successfully built anvio python-Levenshtein
Installing collected packages: python-Levenshtein, psutil, patsy, nbformat, llvmlite, joblib, gitpython, docutils, datrie, configargparse, biopython, asgiref, appdirs, tabulate, statsmodels, snakemake, scikit-learn, pysam, pyani, paste, numba, mistune, illumina-utils, ete3, django, colored, bottle, anvio
Successfully installed anvio-7.1 appdirs-1.4.4 asgiref-3.4.1 biopython-1.79 bottle-0.12.19 colored-1.4.3 configargparse-1.5.3 datrie-0.8.2 django-3.2.12 docutils-0.18.1 ete3-3.1.2 gitpython-3.1.18 illumina-utils-2.12 joblib-1.1.0 llvmlite-0.36.0 mistune-2.0.2 nbformat-5.1.3 numba-0.53.1 paste-3.5.0 patsy-0.5.2 psutil-5.9.0 pyani-0.2.11 pysam-0.18.0 python-Levenshtein-0.12.2 scikit-learn-0.24.2 snakemake-5.10.0 statsmodels-0.12.2 tabulate-0.8.9
