### ISSUE TITLE
[BUG] $ anvi-self-test --suite pangenomics failure

### ISSUE THREAD

**Issue by HMorrison** [merenlab/anvio#1897]
## Short description of the problem

anvi-self-test --suite pangenomics failed at [Computing gene cluster homogeneity indices] step

Does it need files downloaded/created before doing the test? The self test command is suggested right after the introduction. 

## anvi'o version
7.1
Replace this text with the output of this command:

```
(anvio-7.1) morrison2: anvi-self-test --version
Anvi'o .......................................: hope (v7.1)

Profile database .............................: 38
Contigs database .............................: 20
Pan database .................................: 15
Genome data storage ..........................: 7
Auxiliary data storage .......................: 2
Structure database ...........................: 2
Metabolic modules database ...................: 2
tRNA-seq database ............................: 2
```

## System info

MacOS Monterey v. 12.1; anvi'o 7.1 installed using pip install anvio-7.1.tar.gz (install tutorial)

## Detailed description of the issue

WARNING
==============================================================
Homogeneity indices computation for gene cluster GC_00000001 failed. This can
happen due to one of three reasons: (1) this gene cluster is named incorrectly,
does not exist in the database, or is formatted into the input dictionary
incorrectly, (2) there is an alignment mistake in the gene cluster, and not all
genes are aligned to be the same lenght; or (3) the homogeneity calculator was
initialized incorrectly. As you can see, this is a rare circumstance, and anvi'o
will set this gene cluster's homogeneity indices to `-1` so things can move on,
but we highly recommend you to take a look at your data to make sure you are
satisfied with your analysis.

Process Process-2:
Traceback (most recent call last):
  File "/Users/morrison/miniconda3/envs/anvio-7.1/lib/python3.6/site-packages/anvio/dbops.py", line 1627, in homogeneity_worker
    funct_index, geo_index, combined_index = homogeneity_calculator.get_homogeneity_dicts(gene_cluster)
  File "/Users/morrison/miniconda3/envs/anvio-7.1/lib/python3.6/site-packages/anvio/homogeneityindex.py", line 174, in get_homogeneity_dicts
    fun = self.compute_functional_index(cluster_sequences)
  File "/Users/morrison/miniconda3/envs/anvio-7.1/lib/python3.6/site-packages/anvio/homogeneityindex.py", line 50, in compute_functional_index
    residues.append(gene_cluster_sequences[gene_sequence][residue_number])
IndexError: string index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/morrison/miniconda3/envs/anvio-7.1/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/Users/morrison/miniconda3/envs/anvio-7.1/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/morrison/miniconda3/envs/anvio-7.1/lib/python3.6/site-packages/anvio/dbops.py", line 1638, in homogeneity_worker
    combined_index[gene_cluster_name] = -1
UnboundLocalError: local variable 'combined_index' referenced before assignment

**Comment by meren** [comment]
We just fixed this bug with 1bf60bdbd71fdcb6eb81d8c19a0df33c2a6894fe a few days ago, @HMorrison :/

Would you consider tracking the active development branch? This way we can ensure everything is tested for our upcoming minor release too :)

**Comment by HMorrison** [comment]
I could do so, but there were several more lines of instructions :). 
Okay, okay.

**Comment by meren** [comment]
The anvi'o community thanks you for your courage :))

**Comment by HMorrison** [comment]
Disregard email. Had a very old anvi'o release with path pointing to it.

**Comment by meren** [comment]
this should solve it:

```
cd /Users/morrison/github/anvio/
pip install -r requirements.txt
```
