### ISSUE TITLE
[BUG] Error code 500 - Internal server error when trying to save refined bins

### ISSUE THREAD

**Issue by bistace** [merenlab/anvio#1903]
Hello,

I am using the latest available docker image of Anvi'o on Ubuntu18.04 (I also tested on CentOS7 and WSL) and I am trying to manually curate my bins through `anvi-refine`. However, once I click on the `Store refined bins in the database` button, nothing happens and I can see in Chrome's console the following message:
```
Failed to load resource: the server responded with a status of 500 (Internal Server Error)
```
Here is also a screenshot of the error message in the console 

![image](https://user-images.githubusercontent.com/7983565/159015978-b6816fca-512f-48d0-bd50-3e97a317f7b6.png)

Here is the command I ran in order to launch `anvi-refine`:
```
sudo docker run -p 8080:8080 meren/anvio anvi-refine -p $(pwd)/METABAT__233_refined/PROFILE.db -c $(pwd)/METABAT__233_refined/CONTIGS.db --server-only
```

You can download the files I used by clicking [here](https://filesender.renater.fr/?s=download&token=c335689c-015f-45a2-aa92-200eff9dd6f4).

Thanks in advance for your help and your dedication in developing Anvi'o!

**Comment by meren** [comment]
Hi @bistace, sorry for the frustration. Can you please start `anvi-refine` with the flag `--debug`?

When you do that, you should be able to see the actual error that results in this outcome in your terminal window.

**Comment by bistace** [comment]
No problem, I understand that developing an application as large as Anvi'o is not an easy task. Here is the relevant part of the log:
```
Traceback (most recent call last):                                                                                          
  File "/opt/conda/envs/anvioenv/bin/bottle.py", line 868, in _handle
    return route.call(**args)
  File "/opt/conda/envs/anvioenv/bin/bottle.py", line 1748, in wrapper
    rv = callback(*a, **ka)
  File "/opt/conda/envs/anvioenv/lib/python3.6/site-packages/anvio/bottleroutes.py", line 1212, in store_refined_bins       
    self.interactive.store_refined_bins(data, bins_info_dict)
  File "/opt/conda/envs/anvioenv/lib/python3.6/site-packages/anvio/interactive.py", line 1501, in store_refined_bins        
    run.info('collection from db', collection_dict)
  File "/opt/conda/envs/anvioenv/lib/python3.6/site-packages/anvio/terminal.py", line 393, in info
    wrapped_value_lines = textwrap.wrap(value, width=wrap_width, break_long_words=False, break_on_hyphens=False)
  File "/opt/conda/envs/anvioenv/lib/python3.6/textwrap.py", line 379, in wrap
    return w.wrap(text)
  File "/opt/conda/envs/anvioenv/lib/python3.6/textwrap.py", line 351, in wrap
    chunks = self._split_chunks(text)
  File "/opt/conda/envs/anvioenv/lib/python3.6/textwrap.py", line 337, in _split_chunks
    text = self._munge_whitespace(text)
  File "/opt/conda/envs/anvioenv/lib/python3.6/textwrap.py", line 154, in _munge_whitespace
    text = text.expandtabs(self.tabsize)
AttributeError: 'dict' object has no attribute 'expandtabs'
127.0.0.1 - - [18/Mar/2022:17:04:19 +0200] "POST /data/store_refined_bins HTTP/1.1" 500 764 "http://localhost:8080/app/index.html?rand=3815a2d7" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36"
```

**Comment by meren** [comment]
Ah, we fixed this problem but we have not released a new Docker image :/ If you don't have an option to switch to the conda installation solution, you should be able to remove the line number 1501 manually form this file (the one starts with `run.info`):

```
/opt/conda/envs/anvioenv/lib/python3.6/site-packages/anvio/interactive.py
```

And it should all work.

Apologies again.

**Comment by bistace** [comment]
It worked! Thanks a lot for your help!
