### ISSUE TITLE
Option to keep only best hit when multiple HMMs have a match to the same gene ID

### ISSUE THREAD

**Issue by tdelmont** [merenlab/anvio#1905]
## The need

Avoid redundancy of hits for the same gene Id when running HMMs, and keep only the best hit. 

## The solution

A flag allowing removal of redundancy and if possible keeping the best hit, when running HMMs. 

This way, when running "anvi-script-gen-hmm-hits-matrix-across-genomes" for instance, the total number of hits corresponds to the total number of genes with a HMM hit. Currently, the number of hits can be higher than the number of genes, as far as I could see when testing a set of >8,000 HMMs for giant viruses...

## Beneficiaries

People working with HMMs on their metagenomes and genomes. 

It is also something that could be key down the line to estimate genomes present in assemblies. As far as I know, estiumation of genomes from Archaea Bacteria and Eukarya is not removing less relevant hits when multiple domains target the same function. Looking into a more comprehensive approach with viruses for example, it would be key to keep the bets hit prior to estimate what is in the assembly. This could be applied to gene markers of interest for example. Many thanks for considering this.

**Comment by meren** [comment]
Hey @tdelmont, I think I can do this, but I will need a minimal test case here to implement and test the new flag

If possible, can you please put together the following:

* A user-defined HMMs directory with only two models (that match the same gene)
* A contigs-db that contains the sequence of that gene so that when `anvi-run-hmms` is run on that contigs-db, the same gene has two hits.

Thank you!

**Comment by tdelmont** [comment]
@meren I realized that  anvi-get-sequences-for-hmm-hits has the optional flag "--return-best-hit" already with this text:

  --return-best-hit     A bin (or genome) may contain more than one hit for a
                        gene name in a given HMM source. For instance, there
                        may be multiple RecA hits in a genome bin from
                        Campbell et al.. Using this flag, will go through all
                        of the gene names that appear multiple times, and
                        remove all but the one with the lowest e-value. Good
                        for whenever you really need to get only a single copy
                        of single-copy core genes from a genome bin. (default
                        False)

I tested it on a genome with many hits using VOG HMMs and indeed the flags provides a smaller output. I will close this and we might think of this issue as both noise (my fault) and the easiest one to solve...

Best

Tom

**Comment by meren** [comment]
That flag removes hits if the same model hits multiple genes.

I thought you were asking for the removal of hits when different models hit the same gene.

Did I misunderstand?
