### ISSUE TITLE
[BUG] Tidyverse line in install doesn't work on MacOS, needs to use r not bioconductor channel

### ISSUE THREAD

**Issue by zscooper** [merenlab/anvio#1918]
## Short description of the problem

In the install documentation (https://anvio.org/install/), the list of dependencies to install in the anvio conda environment includes the line:
`conda install -y -c bioconda r-tidyverse`

This leads to a "Solving environment" loop that won't resolve. 

Instead, using the line:

`conda install -c r r-tidyverse` 

works just fine. 

## anvi'o version

Anvi'o .......................................: hope (v7.1)

Profile database .............................: 38
Contigs database .............................: 20
Pan database .................................: 15
Genome data storage ..........................: 7
Auxiliary data storage .......................: 2
Structure database ...........................: 2
Metabolic modules database ...................: 2
tRNA-seq database ............................: 2

## System info

MacOS Catalina (10.15.7)
conda 4.12.0
Anvi'o environment installed as specified. 

## Detailed description of the issue

Following the install tutorial (Anvi'o 7.1), everything goes smoothly until it's time to install the `r-tidyverse` dependency. I've run across the command `conda install -y -c bioconda r-tidyverse` not working before, and I found that `conda install -c r r-tidyverse`  gets the job done. Following this, everything else installs correctly, and `anvi-self-test --suite mini` works perfectly.

The error in the documentation may lead to frustration for other users that is not easily resolved without digging around. 

I'm simply requesting an update to the install instructions.

**Comment by meren** [comment]
Thank you for this report, and apologies for the inconvenience, @zscooper. I'm glad you were able to solve it!

We are in the process of switching to Python 3.7, and we're revising the installation instructions according to that switch.

We will keep in mind the tidyverse problem.

Best wishes,

**Comment by kylakell** [comment]
I am still having trouble with `conda install -c r r-tidyverse` with python 3.6. Any further suggestions? I'm trying to install it on an hpc
