### ISSUE TITLE
anvi-gen-contigs-database: force-overwrite

### ISSUE THREAD

**Issue by nick-youngblut** [merenlab/anvio#1921]
## The need

If the user cannot force-overwrite output, then the user must delete any existing output, which requires more code and a potential to delete the wrong file(s), versus just using `--force-overwrite`. Specifically:

```
Config Error: Anvi'o will not overwrite an existing contigs database. Please choose a
              different name or remove the existing database ('/path/to/contigs.db') first.
```

## The solution

Include `--force-overwrite` for `anvi-gen-contigs-database` (and similar commands) 

## Beneficiaries

Everyone who doesn't want to write their code as:

```
rm -f $CONTIG_DB_FILE && anvi-gen-contigs-database -f $INPUT_FASTA -o $CONTIG_DB_FILE 
```

..but rather:

```
anvi-gen-contigs-database --force-overwrite -f $INPUT_FASTA -o $CONTIG_DB_FILE 
```

## Notes

I'm using anvio v7.1

**Comment by meren** [comment]
Now in main.
