### ISSUE TITLE
anvi-get-sequences-for-gene-clusters: one file per gene cluster

### ISSUE THREAD

**Issue by nick-youngblut** [merenlab/anvio#1928]
## The need

It appears that `anvi-get-sequences-for-gene-clusters` will only output one fasta of all selected gene clusters. For many downstream workflows, one file per gene cluster is needed. 

## The solution

It would be helpful to `anvi-get-sequences-for-gene-clusters` could directly write each file (e.g., files named with the gene cluster ID) versus having to write a fasta parser. 

## Beneficiaries

All users that would like to process each gene cluster fasta separately for downstream analyses.

**Comment by nick-youngblut** [comment]
It would also be helpful to get nucleotide alignments for each gene cluster, given that it appears that `anvi-get-dna-sequences-for-gene-calls` and `anvi-export-pc-alignments --report-DNA-sequences` no longer exist in anvio 7.1

**Comment by meren** [comment]
Very good suggestion. This has been annoying me for a while, too. It is now implemented in #1929, and merged to the development branch.

Do you have the ability to test this? If you do, please let me know if something goes wrong.

Thank you!

**Comment by meren** [comment]
(I also committed updated program usage instructions which should appear here in a few minutes: https://anvio.org/help/main/programs/anvi-get-sequences-for-gene-clusters/)
