### ISSUE TITLE
[FEATURE REQUEST] Link contig names to split names

### ISSUE THREAD

**Issue by genomewalker** [merenlab/anvio#1930]
Hi anvi'o developers

## The need

Sometimes, one would like to import contig-wise information using `anvi-import-misc-data`. At the moment, to achieve this, we need to fiddle around to match contig names and split names. 

## The solution

Have a flag like `--contigs-mode` in `anvi-import-misc-data` that digests TAB-delimited files where the identifier is the contig name.

## Beneficiaries

Anyone that would like to import information associated with a contig into anvi'o

Many thanks
Antonio

**Comment by meren** [comment]
I implemented something, but have not rigorously tested yet :)

**Comment by genomewalker** [comment]
Thanks @meren I will test it next week and come back to you.

Many thanks

**Comment by meren** [comment]
I had to merge this for something else. It is now in the main branch. Let me know if something goes wrong :)
