### ISSUE TITLE
[BUG] anvi-interactive command failed after anvi-split

### ISSUE THREAD

**Issue by FlorianTrigodet** [merenlab/anvio#1936]
## Short description of the problem

I have used `anvi-split` and wanted to refine some bins but the interactive command did not work (failed in terminal, no browser output). `anvi-interactive` also failed with the same error on the split databases.

## anvi'o version

Development version.

## System info

Linux. 

## Detailed description of the issue

Here is the error I got with `anvi-interactive` and `anvi-refine`:
```
Traceback (most recent call last):
  File "/project2/meren/GITHUB/anvio/bin/anvi-interactive", line 122, in <module>
    d = interactive.Interactive(args)
  File "/project2/meren/GITHUB/anvio/anvio/interactive.py", line 202, in __init__
    self.completeness = Completeness(self.contigs_db_path)
  File "/project2/meren/GITHUB/anvio/anvio/completeness.py", line 158, in __init__
    hmm_hit = self.hmm_hits_table[entry['hmm_hit_entry_id']]
KeyError: 207
```

**Comment by meren** [comment]
Can you please re-run `anvi-run-hmms` on the source contigs-db and then re-split your collection? This is an impossible error to have :(

**Comment by meren** [comment]
If it persists, please re-open the issue :)
