### ISSUE TITLE
anvi-setup-pfams does not handle already downloaded local file

### ISSUE THREAD

**Issue by EricDeveaud** [merenlab/anvio#1941]
## Short description of the problem
despite the `anvi-setup-pfams` help says 
```This program by default attempts to use previously downloaded files in your Pfam data directory if there are any.```
`anvi-setup-pfams` does not handle this possibility does not handle already downloaded files

## anvi'o version
```
maestro-builder:PlasX/PlasX-0.1 > anvi-self-test --version
Anvi'o .......................................: hope (v7)

Profile database .............................: 35
Contigs database .............................: 20
Pan database .................................: 14
Genome data storage ..........................: 7
Auxiliary data storage .......................: 2
Structure database ...........................: 2
Metabolic modules database ...................: 2
tRNA-seq database ............................: 1
```

## System info
```
maestro-builder:PlasX/0.1 > cat /etc/os-release 
NAME="CentOS Linux"
VERSION="8"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="CentOS Linux 8"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:8"
HOME_URL="https://centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"
CENTOS_MANTISBT_PROJECT="CentOS-8"
CENTOS_MANTISBT_PROJECT_VERSION="8"
```

anvio installed in a virtualenv

## Detailed description of the issue

expected is that `anvi-setup-pfams` takes in account previously downloaded pfam files and not tries to downlaod it again.
this is not possible on our cluster setup where compute nnodes does nnot have access to internet.
I would expect to be abble to downlaod the required pfam files and let `anvi-setup-pfams` process it.

## Files to reproduce

lets say I want to use pfam v32.

```
mkdir ~/Pfam_v32 && cd ~/Pfam_v32/
wget http://ftp.ebi.ac.uk/pub/databases/Pfam/releases/Pfam32.0/Pfam-A.hmm.gz
wget http://ftp.ebi.ac.uk/pub/databases/Pfam/releases/Pfam32.0/Pfam.version.gz
wget http://ftp.ebi.ac.uk/pub/databases/Pfam/releases/Pfam32.0/Pfam-A.clans.tsv.gz
wget http://ftp.ebi.ac.uk/pub/databases/Pfam/releases/Pfam32.0/md5_checksums
anvi-setup-pfams --pfam-data-dir ~/Pfam_v32/ --pfam-version 32.0
```
 
regards

Eric

**Comment by ivagljiva** [comment]
It's been over a year and nobody else has come here to say they are still having this issue, so I am closing it :)
