### ISSUE TITLE
[BUG] `anvi-profile` does not compute codon variable positions when the ORF length matches the contig length

### ISSUE THREAD

**Issue by mschecht** [merenlab/anvio#1943]
## Short description of the problem

`anvi-profile` with the flag `--profile-SCVs` does not compute codon variable positions when the ORF length matches the contig length. This is important for the EcoPhylo workflow where individual genes are profiled for SNVs and any other small contig profiling scenario.

## anvi'o version

```
$ anvi-self-test --version

Anvi'o .......................................: hope (v7.1-dev)

Profile database .............................: 38
Contigs database .............................: 20
Pan database .................................: 15
Genome data storage ..........................: 7
Auxiliary data storage .......................: 2
Structure database ...........................: 2
Metabolic modules database ...................: 4
tRNA-seq database ............................: 2
```

## System info

macOS Big Sur

## Files to reproduce

Here are the files to reproduce the problem:

[SCV_test.tar.gz](https://github.com/merenlab/anvio/files/8903176/SCV_test.tar.gz)

```bash
tar -zxvf SCV_test.tar.gz && cd SCV_test

$ tree -L 2
.
├── 00_SAMPLES
│   ├── AUS0002_R1.fastq
│   ├── AUS0002_R2.fastq
│   ├── AUS0004_R1.fastq
│   └── AUS0004_R2.fastq
├── ORF_length
│   ├── 00_LOGS
│   ├── 01_QC
│   ├── 02_FASTA
│   ├── 03_CONTIGS
│   ├── 04_MAPPING
│   ├── 05_ANVIO_PROFILE
│   ├── 06_MERGED
│   ├── Ribosomal_L16-external_gene_calls_subset.tsv
│   ├── Ribosomal_L16-references_for_mapping_NT.fa
│   ├── fasta.txt
│   ├── metagenomics_config.json
│   └── samples.txt
├── ORF_length_longer
│   ├── 00_LOGS
│   ├── 01_QC
│   ├── 02_FASTA
│   ├── 03_CONTIGS
│   ├── 04_MAPPING
│   ├── 05_ANVIO_PROFILE
│   ├── 06_MERGED
│   ├── Ribosomal_L16-references_for_mapping_NT_longer.fa
│   ├── fasta.txt
│   ├── metagenomics_config.json
│   └── samples.txt
└── fasta.txt
```

To create this data, I ran the metagenomics workflow with `anvi-profile --profile-SCVs` in two different scenarios: (1) ORF length = contig length and (2) contig length > ORF length. Big thanks to @FlorianTrigodet for helping me design the reproducible example. 

**ORF length = contig length**

`ORF_length/` contains `Ribosomal_L16-references_for_mapping_NT.fa` where the contig length is equal to the ORF length. To ensure this, I have provided `Ribosomal_L16-external_gene_calls_subset.tsv` with associated amino acid sequences. After running the metagenomics workflow in reference mode this is what I see in the `profile.db`. Please note the sample `AUS0004` did not map reads to the references and thus there is no merged `profile.db`.

```bash
open ORF_length/05_ANVIO_PROFILE/Ribosomal_L16/AUS0002/PROFILE.db
```
Here you see that no codon variability is recorded.

![image](https://user-images.githubusercontent.com/8404575/173670133-fc2b892b-01ff-455d-8b99-4ca8d0098e9e.png)

All SNV positions are recorded as non-coding regions
![image](https://user-images.githubusercontent.com/8404575/173624168-6b1626df-6184-4a0a-bd11-e58f0fd81a25.png)

**contig length > ORF length**

In this scenario I extended all the sequences in `Ribosomal_L16-references_for_mapping_NT.fa` by running:

```bash
sed 's/$/TTTTT/' Ribosomal_L16-references_for_mapping_NT.fa > Ribosomal_L16-references_for_mapping_NT_longer.fa
```

Additionally, I did not provide an `external-gene-calls.txt` and let prodigal do the gene calling. For the record, I ran the previous scenario without an `external-gene-calls.txt` and got the same results of no codon variability. 

```bash
open ORF_length_longer/05_ANVIO_PROFILE/Ribosomal_L16/AUS0002/PROFILE.db
```

SNVs are now in coding regions and we get codon variability back :)

![image](https://user-images.githubusercontent.com/8404575/173670577-d4490cd4-ce47-4dda-b303-70fdc9ef6a3e.png)

![image](https://user-images.githubusercontent.com/8404575/173624284-46b1f29b-e439-46f6-ba59-abb5c99cc333.png)

Thank you very much in advance for anyone who can help me fix this :)

**Comment by meren** [comment]
Hey Matt, this was quite a challenging one. But I managed to find the root issue here. Unfortunately you will need to re-generate your contigs-db files to test it.

Thank you for the test case (for fail and success).
