### ISSUE TITLE
[BUG] upload layer_orders in newick type, when draw figure, report Error: Layer additional order has leaf named 'undefined' but it is not a valid layer name.

### ISSUE THREAD

**Issue by wuyudelan** [merenlab/anvio#1944]
## Short description of the problem

Upload the layer_order in newick type using anvi-import-misc-data,
when changed the layer order in the web interface
report error: Error: Layer additional order 'genome_tree' has leaf named 'undefined' but it is not a valid layer name. Falling back to custom order. Maybe that layer is hidden??

I have checked the tree, all leafs have genome names.

## anvi'o version

```
anvi-self-test --version
Anvi'o .......................................: hope (v7.1)
```

## System info

Please tell us which operating system you are using, and how did you install anvi'o.
Linux version 3.10.0-1160.31.1.el7.x86_64
install by conda

## Files to reproduce

[files.zip](https://github.com/merenlab/anvio/files/8917746/files.zip)

## Commands

anvi-import-misc-data genome_tree_table.tsv \
                      -p profile.db \
                      -t layer_orders
                      
                      
anvi-interactive -d orthofinder_PHO_N0_01_need.tsv \
                 -t orthofinder_PHO_N0_01_need_tree.tre \
                 -p profile.db \
                 --title "orthofinder_PHO_N0_01_need" \
                 --manual

**Comment by meren** [comment]
Hi @wuyudelan,

I run this,

```
anvi-import-misc-data genome_tree_table.tsv -p profile.db -t layer_orders --just-do-it
```

And then this,

```
anvi-interactive -d orthofinder_PHO_N0_01_need.tsv -t orthofinder_PHO_N0_01_need_tree.tre -p profile.db --title "orthofinder_PHO_N0_01_need" --manual
```

And got the same error:

![image](https://user-images.githubusercontent.com/197307/174087504-6e912b07-bec3-4b4b-8bb2-8b564512f498.png)

Then looked at the 'leaf' names in your tree and realized that the leafs describe items, and not layers :)
