### ISSUE TITLE
[BUG] Discrepancy between redundancy estimates

### ISSUE THREAD

**Issue by FlorianTrigodet** [merenlab/anvio#1945]
## Short description of the problem

There is a difference in the redundancy estimate between the command `anvi-estimate-genome-completeness` and the report output of `anvi-rename-bins` for an Eukaryote bin. 

## anvi'o version

Development version.

## Detailed description of the issue

I have a collection of bin which contains a large eukaryote. Here is the output of `anvi-estimate-genome-completeness`:
```
Bins in collection "default"
===============================================
╒════════════╤══════════╤══════════════╤════════════════╤════════════════╤══════════════╤════════════════╕
│ bin name   │ domain   │   confidence │   % completion │   % redundancy │   num_splits │   total length │
╞════════════╪══════════╪══════════════╪════════════════╪════════════════╪══════════════╪════════════════╡
│ Bin_1      │ BACTERIA │          0.9 │          98.59 │           8.45 │          530 │        1612349 │
├────────────┼──────────┼──────────────┼────────────────┼────────────────┼──────────────┼────────────────┤
│ Bin_2      │ EUKARYA  │          0.6 │          61.45 │           7.23 │         8411 │       26924911 │
├────────────┼──────────┼──────────────┼────────────────┼────────────────┼──────────────┼────────────────┤
│ Bin_3      │ BLANK    │            1 │              0 │              0 │           62 │         103694 │
├────────────┼──────────┼──────────────┼────────────────┼────────────────┼──────────────┼────────────────┤
│ Bin_4      │ BLANK    │            1 │              0 │              0 │          156 │         378418 │
├────────────┼──────────┼──────────────┼────────────────┼────────────────┼──────────────┼────────────────┤
│ Bin_5      │ BLANK    │            1 │              0 │              0 │           77 │         128382 │
╘════════════╧══════════╧══════════════╧════════════════╧════════════════╧══════════════╧════════════════╛
```

I then used the command `anvi-rename-bins` with the option to specifically rename "bin" into "MAG" based on completeness and redundancy threshold (in this case min 50% complete and max 10% redundancy). Surprisingly, the Eukaryote bin was not renamed as a MAG, and here is the report made by `anvi-rename-bins`:

|**old_bin_name**|**new_bin_name**|**completion**|**redundancy**|**size_in_Mbp**|
|:--|:--|:--|:--|:--|
|Bin_1|p800_00M_PP_MUC_MAG_00001|98.59|8.45|1.61|
|Bin_2|p800_00M_PP_MUC_Bin_00002|63.16|34.21|26.92|
|Bin_4|p800_00M_PP_MUC_Bin_00003|1.41|0.00|0.38|
|Bin_3|p800_00M_PP_MUC_Bin_00004|0.00|0.00|0.10|
|Bin_5|p800_00M_PP_MUC_Bin_00005|0.00|0.00|0.13|

You can see that the completeness and redundancy don't match the numbers above. Could it be that `anvi-rename-bins` uses a different set of SCG to estimate completeness? 

## Files to reproduce

The eukaryote genome is pretty big, but if needed I can find a way to send it.

**Comment by meren** [comment]
Can you run `anvi-estimate-genome-completeness` with `--debug`? I'm curious if what we see in `anvi-summarize` is actually the C/R values for `Bin_2` with archaeal SCGs.

**Comment by meren** [comment]
That is the first thing to check, I think :)

**Comment by meren** [comment]
This is now solved. Thank you!
