### ISSUE TITLE
[FEATURE REQUEST] Filter bin collection by completeness/redundancy

### ISSUE THREAD

**Issue by FlorianTrigodet** [merenlab/anvio#1946]
## The need

I would like a command to create a new collection from an existing one and only keep bins fitting completeness/redundancy threshold (and also length, why not).

There is a command, `anvi-rename-bins`, which allows to rename all the bins from a collection with the option to rename as MAG the bins passing a completeness/redundancy threshold. But it keeps all the other low quality bins. Maybe we can add a flag in that command to just keep the "MAG" in the new collection?

## The solution

Add a flag in `anvi-rename-bins` to discard bins not passing completeness/redundancy threshold.

## Beneficiaries

Anyone doing metagenomic binning, especially prior to dereplication and/or to only share and visualize medium/high quality MAGs.

**Comment by meren** [comment]
This is now done :)
