### ISSUE TITLE
[DISCUSSION] Creating contig database with NCBI genome and genome with custom annoation

### ISSUE THREAD

**Issue by arunvv90** [merenlab/anvio#1969]
Hi,
I have a reference genome and I downloaded it from NCBI. I have twenty genomes I have assembled and annotated with vapid. I got the following files
Reference genome - .gbff file
Another strain of the virus - .gb file
Novel genomes - .gbf file from vapid annotator(twenty genomes)
I do not want to use prodigal for annotation and would like to keep my custom annotation created with vapid.
I want to create a contig database and later use it for pangenome. I tried different ways. In the post written by Mike Lee, the prodigal was used for annotation for new genomes and merged. I already have annotated file. Could you please tell me what is the best approach?

**Comment by meren** [comment]
Hi @arunvv90, I think this could be a great discussion on anvi'o slack, where you can also find Mike Lee. Based on his input, we can update the post written by Mike so it has more coverage.
