### ISSUE TITLE
[BUG] anvi-report-inversions error when contig has coverage of 0 in sample

### ISSUE THREAD

**Issue by watsonar** [merenlab/anvio#1970]
## Short description of the problem

Hello! I am running anvi-report-inversions using a contigs db consisting of multiple genomes. I am getting a type error (TypeError: 'NoneType' object is not iterable) that I think is happening because one of my contigs has zero coverage in one of my samples.

## anvi'o version

```
Anvi'o .......................................: hope (v7.1-dev)

Profile database .............................: 38
Contigs database .............................: 20
Pan database .................................: 16
Genome data storage ..........................: 7
Auxiliary data storage .......................: 2
Structure database ...........................: 2
Metabolic modules database ...................: 4
tRNA-seq database ............................: 2
```

## System info

I using an AWS EC2 instance running Ubuntu 22.04 LTS, with 32 CPUS and 128 GB of memory. I installed anvio-dev following these instructions: https://anvio.org/install/#5-follow-the-active-development-youre-a-wizard-arry

## Detailed description of the issue

I am running the following command:
```
anvi-report-inversions -P bams_and_profiles.txt.short \
                       -T 32 \
                       --force-overwrite \
                       --debug
```
And receiving this output:
```
[General] Input BAMs and profiles file ......................: bams_and_profiles.txt.short
[General] Number of samples to process ......................: 1
[General] R1/R2 for raw reads present? ......................: False
[General] Be talkative (--verbose)? .........................: False

[Defining stretches] Min FF/RR coverage to qualify ..........: 10
[Defining stretches] Min length .............................: 50
[Defining stretches] Min dist between independent stretches .: 2,000
[Defining stretches] Num nts to pad a stretch ...............: 100

[Finding palindromes] Algorithm .............................: [will be dynamically determined based on sequence length]
[Finding palindromes] Min palindrome length .................: 10
[Finding palindromes] Max num mismatches ....................: 0
[Finding palindromes] Min mismatch distance to first base ...: 1
[Finding palindromes] Min distance betwen each sequence .....: 50

[Confirming inversions] Check all palindromes in a stretch? .: False
[Confirming inversions] Process only inverted reads? ........: False

[Genomic context] Recover and report genomic context? .......: True
[Genomic context] Gene caller to use ........................: prodigal
[Genomic context] Number of genes to consider ...............: 3

[Inversion activity] Compute inversion activity? ............: False
[Inversion activity] Not computing because ..................: `bams-and-profiles-txt` does not contain raw reads for r1/r2

[21 Aug 22 20:56:39 Processing 'FF05465528'] Computing coverage stretches
✖ anvi-report-inversions encountered an error after 0:00:03.530991
Traceback (most recent call last):
  File "/home/ubuntu/github/anvio/bin/anvi-report-inversions", line 147, in <module>
    main(args)
  File "/home/ubuntu/github/anvio/anvio/terminal.py", line 879, in wrapper
    program_method(*args, **kwargs)
  File "/home/ubuntu/github/anvio/bin/anvi-report-inversions", line 26, in main
    I.process()
  File "/home/ubuntu/github/anvio/anvio/inversions.py", line 1223, in process
    self.process_db(entry_name, profile_db_path, bam_file_path)
  File "/home/ubuntu/github/anvio/anvio/inversions.py", line 272, in process_db
    for e in coverage_stretches_in_contigs[contig_name]]
TypeError: 'NoneType' object is not iterable
```

I added some print statements to `anvio/anvio/inversions.py` to troubleshoot, and it looks like the first contig is working fine, but the second contig is causing the error. I added the line `print(max(contig_coverage))` to line 235 and `print(regions_of_contig_covered_enough.any())` to line 239, and got outputs of 0.0 and False, respectively.

Thank you so much, wonderful anvi'o developers ❤️

**Comment by meren** [comment]
Hey @watsonar, thank you very much for catching this and for your report! We don't have a test dataset to catch this, but I hope you can test this change after a git pull and see if it is working for you now? :)

**Comment by watsonar** [comment]
Thank you so much @meren! Your fix worked but then I ran into another error with a contig that did have some coverage but no regions of high enough coverage to pass the filter. I proposed an additional change (https://github.com/merenlab/anvio/pull/1971) that removed that error for me! :)

**Comment by meren** [comment]
I should have seen that coming. Sorry. But a great fix came from you, so not too sorry!

Thank you again, Andrea.

**Comment by watsonar** [comment]
I ran into another similar error when running more samples, this time where a contig had a region of sufficient coverage, but was not long enough to be considered. I implemented a quick fix that worked for me which I hope is okay!

**Comment by meren** [comment]
This looks like an appropriate change as well, Andrea. You are on a roll! :)
