### ISSUE TITLE
[BUG] anvi-get-split-coverages doesn't export gene caller ID = 0

### ISSUE THREAD

**Issue by efogarty11** [merenlab/anvio#1979]
## Short description of the problem

anvi-get-split-coverages gives error when gene caller id 0 is given.

## anvi'o version

main on midway :) 

## Detailed description of the issue

When I run the commend:
```bash
anvi-get-split-coverages -p PROFILE.db -c contigs.db --gene-caller-id 0 -o COVs.txt
```

I get this error:
```
Config Error: You must either declare a split or contig name, a bin name in a collection, or a
              gene caller id for this to work.
```

## Files to reproduce
I'll post the files on the Meren lab slack- for some reason I can't upload them here :)

**Comment by ivagljiva** [comment]
Should be fixed as of [4e86c1d2](https://github.com/merenlab/anvio/commit/4e86c1d2d89989a78f529916fb114a996e25fc30)!
