### ISSUE TITLE
Error during anvio installation 

### ISSUE THREAD

**Issue by ewelinarubin** [merenlab/anvio#1980]
I am following all the instructions listed here  
https://anvio.org/install/

Everything goes well except for one error 

ERROR: Failed building wheel for python-Levenshtein

Any ideas on how to fix this?

**Comment by ivagljiva** [comment]
Hi @ewelinarubin, 

In order for us to help you effectively, we need to know the context of the error (ie, which specific command was running when you got the error message). It would help if you could paste here a bit more of the installation output from just before this `ERROR` line as that often has clues about what went wrong. You should also tell us your operating system and what version of anvi'o you are trying to install.

People have had issues with the Levenshtein package in the past; I also suggest that you try some of the solutions recorded in these prior issues, namely #1896 and  #1643.

**Comment by ewelinarubin** [comment]
Hi Iva -- thanks so much for responding. I am trying out from scratch again with the installation.
Today I am getting  new error at this step: 

conda activate anvio-7.1

xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun

Any help is more than welcome

**Comment by ivagljiva** [comment]
Aha :) You need to install the developer tools first. That should solve all of your problems, I think. 

You should open a new terminal, run `xcode-select --install`, then start the installation from scratch (deleting your old conda environment and making a new one). 

If that doesn't work, let us know.

**Comment by ewelinarubin** [comment]
I tried that but the computer gets stuck on "Finding Software" panel. 
I see that I can download the package from
https://developer.apple.com/download/all/ 

but I do not know what exactly I need for example is it 
Xcode 14 beta 6
or
Command Line Tools for Xcode 14 Release Candidate

or which package

**Comment by meren** [comment]
This looks like an issue you need to resolve with your system administrator or IT support, @ewelinarubin :(

**Comment by ewelinarubin** [comment]
Ok -- I see. I do not have an IT support but thanks for closing this :)
