### ISSUE TITLE
Co-assembling metagenomic sets

### ISSUE THREAD

**Issue by pedres** [merenlab/anvio#1981]
## Short description of the problem

I am sorry to bother you with this problem but I cannot co-assemble my samples. I am following the TARA tutorial with my samples, but megahit always gives the "number of paired-end files not match" error. 
My set files is 
CT21
CT63
EW21
EW63

and my samples are

CT21_A-QUALITY_PASSED_R1.fastq	CT21_A-QUALITY_PASSED_R2.fastq
CT21_B-QUALITY_PASSED_R1.fastq	CT21_B-QUALITY_PASSED_R2.fastq
CT21_C-QUALITY_PASSED_R1.fastq	CT21_C-QUALITY_PASSED_R2.fastq
CT63_A-QUALITY_PASSED_R1.fastq	CT63_A-QUALITY_PASSED_R2.fastq
CT63_B-QUALITY_PASSED_R1.fastq	CT63_B-QUALITY_PASSED_R2.fastq
CT63_C-QUALITY_PASSED_R1.fastq	CT63_C-QUALITY_PASSED_R2.fastq
EW21_A-QUALITY_PASSED_R1.fastq	EW21_A-QUALITY_PASSED_R2.fastq
EW21_B-QUALITY_PASSED_R1.fastq	EW21_B-QUALITY_PASSED_R2.fastq
EW21_C-QUALITY_PASSED_R1.fastq	EW21_C-QUALITY_PASSED_R2.fastq
EW63_A-QUALITY_PASSED_R1.fastq	EW63_A-QUALITY_PASSED_R2.fastq
EW63_B-QUALITY_PASSED_R1.fastq	EW63_B-QUALITY_PASSED_R2.fastq
EW63_C-QUALITY_PASSED_R1.fastq	EW63_C-QUALITY_PASSED_R2.fastq

It works perfectly, when my set file is
CT21_A
CT21_B
CT21_C
CT63_A
CT63_B
CT63_C
EW21_A
EW21_B
EW21_C
EW63_A
EW63_B
EW63_C

## anvi'o version
anvio 7.1

```
anvi-self-test --version
```

## System info

Working on CESGA a supercomputer from Spain. I installed anvio in a conda environment

**Comment by ivagljiva** [comment]
Hello @pedres,  I am sorry that this question has gone unanswered for over a year. However, it is not clear to me whether this is something we can help you with. First, it seems to be a `megahit` error and not an anvi'o error. Second, we don't have a TARA tutorial as far as I am aware, so I'm not sure what the instructions that you are trying to follow.

I hope that you have already figured out how to fix this. 

I am going to close this issue now, but if you think that we can still help you, please feel free to reopen it and provide some more specifics like 1) the link of the tutorial you are working with, 2) the anvi'o command that fails, and 3) hopefully a few files for a minimal test case.

**Comment by pedres** [comment]
Hi Ivan,

Finally I was able to fix the problem using several commands instead of a for loop that appears in the Tara tutorial

Cheers,

Manuel
________________________________
De: Iva Veseli ***@***.***>
Enviado: lunes, 25 de septiembre de 2023 15:52
Para: merenlab/anvio ***@***.***>
Cc: Manuel Aira Vieira ***@***.***>; Mention ***@***.***>
Asunto: Re: [merenlab/anvio] Co-assembling metagenomic sets (Issue #1981)


Hello @pedres<https://urldefense.com/v3/__https://github.com/pedres__;!!D9dNQwwGXtA!Qtw5SifmhnIb8sry1fCfE7T_KR6jWQIJAunjNxyxYCDOJdH0kJIFfe7gETRurwkAlOMD7LT4YQg1B3N_A_gAqA$>, I am sorry that this question has gone unanswered for over a year. However, it is not clear to me whether this is something we can help you with. First, it seems to be a megahit error and not an anvi'o error. Second, we don't have a TARA tutorial as far as I am aware, so I'm not sure what the instructions that you are trying to follow.

I hope that you have already figured out how to fix this.

I am going to close this issue now, but if you think that we can still help you, please feel free to reopen it and provide some more specifics like 1) the link of the tutorial you are working with, 2) the anvi'o command that fails, and 3) hopefully a few files for a minimal test case.
