### ISSUE TITLE
Import items-info for collections 

### ISSUE THREAD

**Issue by sklasek** [merenlab/anvio#1983]
## The need

I have a collection of binned MAGs that I can view using anvi-interactive, and I would like to import misc-data that corresponds to each of the MAGs. (As far as I understand, it is currently only possible to import misc-data layers into a collection view, and import misc-data items to a splits- or contigs view). There's a --contigs-mode, but I suppose what I need is a --collection-mode.

## No solution, but here's a reproducible example:

I made a brief items.txt table (attached here) and attempted to import it to the collection of MAGs from the Infant Gut Dataset. Trying anvi-import-misc-data failed predictably:

`anvi-import-misc-data madeup.mags.items.info.txt -p 06_MERGED/ig/PROFILE.db --target-data-table items
`

> Config Error: Well. None of the 13 item names in your additional data are matching to those  
>               that are in the profile you are working with :/ Since there is no reason to add
>               additional data for items that do not exist in your database, anvi'o will stop 
>               you right there. Please fix your data and come again. In case you want to see a
>               random item that is only in your data, here is one: 'IGD_MAG_00007'. Item names
>               in your db generally looks like this: 'Day17a_QCcontig90_split_00009'. If you  
>               are working with contigs names instead of split names, perhaps you need the    
>               `--contigs-mode` flag? 

Using contigs-mode and pointing it to the contigs db gives a python traceback:

`anvi-import-misc-data madeup.mags.items.info.txt -p 06_MERGED/ig/PROFILE.db -c 03_CONTIGS/ig-contigs.db --target-data-table items --contigs-mode`

> * madeup.mags.items.info.txt successfully loaded

> Traceback (most recent call last):
>   File "/users/sklasek/github/anvio/bin/anvi-import-misc-data", line 84, in <module>
>     main(args)
>   File "/users/sklasek/github/anvio/anvio/terminal.py", line 879, in wrapper
>     program_method(*args, **kwargs)
>   File "/users/sklasek/github/anvio/bin/anvi-import-misc-data", line 46, in main
>     MiscDataTableFactory(args).populate_from_file(args.data_file)
>   File "/users/sklasek/github/anvio/anvio/tables/miscdata.py", line 164, in populate_from_file
>     AdditionalDataBaseClass.add(self, data_dict, data_keys, skip_check_names)
>   File "/users/sklasek/github/anvio/anvio/tables/miscdata.py", line 807, in add
>     data_dict = self.update_input_data_dict_with_split_names(data_dict)
>   File "/users/sklasek/github/anvio/anvio/tables/miscdata.py", line 769, in update_input_data_dict_with_split_names
>     for split_name in contig_name_to_split_names_dict[contig_name]:
> KeyError: 'IGD_MAG_00001'
> 

Currently running this on the development branch. Importing misc data as items works just fine.

## Beneficiaries

Those doing genome-resolved metagenomics who want to import more data to their MAGs collections (for making figures, or for comparative purposes)

[madeup.mags.items.info.txt](https://github.com/merenlab/anvio/files/9576487/madeup.mags.items.info.txt)

**Comment by meren** [comment]
Hey @sklasek, instead of importing this file to the profile database you can pass it to the interactive interface with the `-A` parameter in collection mode.

Can you please try it and let us know if it works?

We should, however, fix the cryptic error message and catch it earlier :) Thank you!
