### ISSUE TITLE
[FEATURE REQUEST] anvi-estimate-metabolism gene list and order

### ISSUE THREAD

**Issue by zscooper** [merenlab/anvio#1995]
## The need

The `anvi-estimate-metabolism` program currently returns completion values for KEGG modules. I'm hoping it would be possible to add output options to return a list of KOs that are present in the query genome. If possible, it would also be nice to incorporate information about the position in the KEGG defined metabolism where the pathway is disrupted. This would be useful for understanding whether components of a pathway might be used for alternate reactions or whether a key enzyme is missing that completely disrupts a pathway. This would primarily be important for complete genomes incorporated into anvio, but perhaps less important for MAGs where completion varies.

## The solution

Adding an output option with a list of KOs annotated for each pathway would be a simple beginning step. Getting into the ordering is a bit more difficult, but perhaps could be solved with a secondary list of KOs expected but not present. This would leave the user to decipher the pathway order. 

## Beneficiaries

Users with complete genomes and interest in metabolism should broadly be interested in this as an additional way to interpret the KEGG data.

**Comment by ivagljiva** [comment]
(just a note to myself) This is for pathwise completeness. Something similar to the deprecated 'paths_in_modules' output mode could be a solution :)

**Comment by ivagljiva** [comment]
Hey @zscooper, I'm looking into this now. I have a plan for what to add and wanted your opinion on it to see if it's what you are looking for :)

My idea is to add an additional column to the ['module paths' mode output file](https://anvio.org/help/main/artifacts/kegg-metabolism/#module-paths-mode), ie, the output you get when you run `anvi-estimate-metabolism --output-modes module_paths`. The column would be called something like 'annotated_enzymes_in_path' and show a comma-delimited list of the enzymes, in order of the path through the module (which is already described in the 'path' column). Anytime an enzyme is missing from the annotations, we could refer to it as missing.

For example, here is what I imagine it could look like (I lifted the example table from the documentation page linked above, scroll all the way to the right to see the last column I added):

module | genome_name | db_name | pathwise_module_completeness | pathwise_module_is_complete | path_id | path | path_completeness | annotated_enzymes_in_path
-- | -- | -- | -- | -- | -- | -- | -- | --
M00001 | Enterococcus_faecalis_6240 | E_faecalis_6240 | 1.0 | True | 0 | K00844,K01810,K00850,K01623,K01803,K00134,K00927,K01834,K01689,K00873 | 0.8 | K00844,[MISSING K01810],K00850,K01623,[MISSING K01803],K00134,K00927,K01834,K01689,K00873
M00001 | Enterococcus_faecalis_6240 | E_faecalis_6240 | 1.0 | True | 1 | K12407,K01810,K00850,K01623,K01803,K00134,K00927,K01834,K01689,K00873 | 0.8 | K12407,[MISSING K01810],K00850,K01623,[MISSING K01803],K00134,K00927,K01834,K01689,K00873
M00001 | Enterococcus_faecalis_6240 | E_faecalis_6240 | 1.0 | True | 2 | K00845,K01810,K00850,K01623,K01803,K00134,K00927,K01834,K01689,K00873 | 0.8 | K00845,[MISSING K01810],K00850,K01623,[MISSING K01803],K00134,K00927,K01834,K01689,K00873
(…) | (…) | (…) | (…) | (…) | (…) | (…) | (…) | (…)

What do you think? Does this fit what you are looking for?

**Comment by zscooper** [comment]
Hi @ivagljiva, that's exactly what I'm looking for. Solves both presence/absence and some info on the order of the path. Looks great to me!

**Comment by ivagljiva** [comment]
Excellent, thanks for the feedback! This is now implemented in anvio-dev as of [this commit](https://github.com/merenlab/anvio/compare/6e8c22b2eb4a...7bd02577617b). :)
