### ISSUE TITLE
[BUG] Cannot summarize from the interactive interface

### ISSUE THREAD

**Issue by FlorianTrigodet** [merenlab/anvio#1996]
## Short description of the problem

Error when trying to summarize a pangenome from the interactive interface (using Chrome). 
I've seen the error on @arbarno's laptop, during a workshop. 

## anvi'o version

Anvi'o 7.1

## System info

MacOS Monterey

## Detailed description of the issue

The issue only happened when using the interactive interface, not when using `anvi-summarize`.
I couldn't reproduce the error on my laptop, even when using the same databases.
No idea what's causing the issue, but I felt like reporting it anyway. 

<img width="308" alt="Screen Shot 2022-10-24 at 17 43 38" src="https://user-images.githubusercontent.com/10922896/197706618-1b0fc264-30a0-4fcc-8005-a8c3dd25de11.png">

**Comment by meren** [comment]
Good idea to report this. Can you reproduce it when you run the following, and then summarize from the interface?

```
anvi-self-test --suite pangenomics
```

**Comment by FlorianTrigodet** [comment]
The issue was the same with `anvi-self-test --suite pangenomics`.
We solve it by using iterm2 instead of the default terminal. The problem was related to emojis that couldn't be rendered properly.

**Comment by meren** [comment]
lol

that's embarrassing that anvi'o doesn't know how to handle poopy terminals :(

I assume you're certain that this is an issue with anvio-dev (unlike the report which is coming from "anvi'o 7.1"), can you please confirm?

**Comment by FlorianTrigodet** [comment]
After checking, the terminal was not setting "locale environment variables on startup". 
AND it seems it was fixed in the dev version because I cannot reproduce it with anvio-dev. 
I guess this issue is only relevant to users of 7.1 at the moment and will be solved in the next stable release.

**Comment by meren** [comment]
Crisis averted (I think I fixed it in the development branch (we REALLY REALLY need to make a stable release)).

**Comment by arbarno** [comment]
Thank you Florian and Meren for your help!
