### ISSUE TITLE
anvi-gen-contigs-database is generating a mis-translation

### ISSUE THREAD

**Issue by wichne** [merenlab/anvio#2002]
I am running anvi-gen-contigs-database using a --external-gene-calls generated from a gff file. The relevant line in the gff file is 
`Ga0538187_01    img_core_v400   CDS     739241  740536  .       +       0       ID=2963638220;locus_tag=Ga0538187_01_739241_740536;product=hypothetical protein`
which generated this line in the genes.txt file:
`2963638220      Ga0538187_01    739240  740536  f       0       1       img_core_v400   400`

Executing the program:
`anvi-gen-contigs-database -f 2963637191.fna -o 2963637191.db --external-gene-calls 2963637191.genes.txt`
throws the following error:

> ✖ anvi-gen-contigs-database encountered an error after 0:00:04.125540
> 
> Traceback (most recent call last):
>   File "/home/nels329/anaconda3/envs/anvio-7/lib/python3.6/site-packages/anvio/dbops.py", line 4285, in create
>     skip_predict_frame=skip_predict_frame,
>   File "/home/nels329/anaconda3/envs/anvio-7/lib/python3.6/site-packages/anvio/tables/genecalls.py", line 225, in use_external_gene_calls_to_populate_genes_in_contigs_table
>     skip_predict_frame=skip_predict_frame,
>   File "/home/nels329/anaconda3/envs/anvio-7/lib/python3.6/site-packages/anvio/tables/genecalls.py", line 425, in get_amino_acid_sequences_for_genes_in_gene_calls_dict
>     "sense as a gene call: '%s'." % (str(gene_callers_id), sequence, amino_acid_sequence))
> anvio.errors.ConfigError: 
> 
> Config Error: Oops. Anvi'o run into an amino acid sequence (that corresponds to the gene      
>               callers id '2963638220') which had an internal stop codon :/ This is sometimes  
>               due to errors in the external gene calls file, but more often it is due to the  
>               non-standard genetic code. You still can continue by asking anvi'o to ignore    
>               internal stop codons via the flag \`--ignore-internal-stop-codons\`. It will      
>               probably look very ugly on your screen, but here is the DNA sequence for that   
>               gene in case you don't trust anvi'o (which only would be fair since anvi'o does 
>               not trust you either): 'ATGGTCGAGAACAGGCCCGAACACGAACAGGCTGCGGAACCGGCCGAGCATCACCA
>               GCCGACCGGCGAGGAGACCAGCACCGCGGCCACTGGTGCCGAGGCAGAAGCTGCAGCGGAGATAGCGCCCGAGGCCGAAC
>               CGGCGCAGGGACCGGAGCAGGCCTTCGACATCGCCGCCGATCAGCGCGAGCAGGCCGAGCAGGCTGCCGGCCTGCCGGAA
>               CCGGAATTCGCCACCACCACAGCTGCAGCCGATGCGTCGGCGACCGCGCAAAAGCTCTGCAGCGCCGCGGAACAGCATTG
>               CGTCGCTGATCCTGCCACCGGTGCTGACGATCGCGATCGCGACCGGCCTCGTGGTCGGCGCCGCCAAGATGGGCCTGCTG
>               CCGCAATTTCTGTCGTCGACCAGCGTCACGGCCCCGCAGGCAGATCCTGCAGCGTTCGATGCGCTGAACGCCCGGATCGC
>               CAAGCTCGAAGCCGCTCCCACCGCTGGCGGCGCAACGGCCGTGCCGAGCGACAGCGCGGCGCTGGAAGCACTCGCGATCC
>               GGATCACAAATCTCGAAGCGCGGCCAAAGGCGGCGTCCGATGGGGCTGCCGCTGCCGATCCGGCCGCTACCGGCCGGATC
>               GATGCGCTGGAGAAGTCGGTGGCATCGCTGCGGGACGACCTGACAGCGCTGCGCAGCCAGACCGATCAGCTCGCGGCGAC
>               CGTGAAGGACTTGAAGGCTGCGCCGGGCGCCAGCGCCGACGAGGCCAAGCCGAGTGCGGAGGCAGCCGGCGCCGAGAAGG
>               CGGCCGCGCTGGAGCAGACCACCGCCGCGTTAGCCGCGATCGATCGGCGGCTCGGCGTGCTGGAAGCCGCCACCAAGGCC
>               GAGGCGGAGAAACCGGCGCCGAAATCCGCCCCCGCCGAGGACGGTGCGCTGCGCCGCGCGGTCGCCGCCACCTTGCTCGA
>               CCTCGCCGTCACGCAAGGCCAACCGTTCCAGCCCTTGCTGAAGGCCGCGGCGCCACTCGCGCCCGATGCTGGGTCGCTGA
>               AGCCGCTCGACCGCTTCGCCGCGACCGGCGTTCCGAGTGCCCGTGCGCTCGGCCAGGAGCTGATCGACCAACTGCCGAAC
>               CTGCTGCCCGACAAAACCCATTCGAATGCCAATTTCATCGACCGATTTCAGGCCAATGCCGAGCGGCTGGTGAAGATTCA
>               GCGCTCGGATGCGGTCGAGGGCATCGATCGCACCGCGATCGTCGGCCGGCTGACCGCGGCCGCCAAGCAGGGCGACATCG
>               CCGCCGCGCTGAAGGAGCTGAAAGCGCTTGCGCCGGGTGA'. And here is the amino acid sequence  
>               of the same gene call if you would like to BLAST it around and see whether it   
>               actually makes sense as a gene call: 'WSRTGPNTNRLRNRPSITSRPARRPAPRPLVPRQKLQRR*RP
>               RPNRRRDRSRPSTSPPISASRPSRLPACRNRNSPPPQLQPMRRRPRKSSAAPRNSIASLILPPVLTIAIATGLVVGAAKM
>               GLLPQFLSSTSVTAPQADPAAFDALNARIAKLEAAPTAGGATAVPSDSAALEALAIRITNLEARPKAASDGAAAADPAAT
>               GRIDALEKSVASLRDDLTALRSQTDQLAATVKDLKAAPGASADEAKPSAEAAGAEKAAALEQTTAALAAIDRRLGVLEAA
>               TKAEAEKPAPKSAPAEDGALRRAVAATLLDLAVTQGQPFQPLLKAAAPLAPDAGSLKPLDRFAATGVPSARALGQELIDQ
>               LPNLLPDKTHSNANFIDRFQANAERLVKIQRSDAVEGIDRTAIVGRLTAAAKQGDIAAALKELKALAPG'.
> 

The first part of the message suggests anvi-gen-contigs-database is attempting to predict the correct reading frame rather than defaulting to +0. Is that true? If so, in this case it appears to be choosing the wrong frame because the nucleotide sequence presented  translates to:
`>Ga0538187_01_739241_740536_tx1 Ga0538187_01_739241_740536
MVENRPEHEQAAEPAEHHQPTGEETSTAATGAEAEAAAEIAPEAEPAQGPEQAFDIAADQ
REQAEQAAGLPEPEFATTTAAADASATAQKLCSAAEQHCVADPATGADDRDRDRPRGRRR
QDGPAAAISVVDQRHGPAGRSCSVRCAERPDRQARSRSHRWRRNGRAERQRGAGSTRDPD
HKSRSAAKGGVRWGCRCRSGRYRPDRCAGEVGGIAAGRPDSAAQPDRSARGDREGLEGCA
GRQRRRGQAECGGSRRREGGRAGADHRRVSRDRSAARRAGSRHQGRGGETGAEIRPRRGR
CAAPRGRRHLARPRRHARPTVPALAEGRGATRARCWVAEAARPLRRDRRSECPCARPGAD
RPTAEPAARQNPFECQFHRPISGQCRAAGEDSALGCGRGHRSHRDRRPADRGRQAGRHRR
RAEGAESACAG*`
and the +1 translation is the protein sequence presented in the error.

What triggers this behavior?

**Comment by meren** [comment]
@wichne, please try again using anvio-dev. I think we resolved this issue.

**Comment by wichne** [comment]
Thanks Meren. I also found the --skip-predict-frame option (note to self - RTFM).

**Comment by meren** [comment]
Ah, perfect! Thanks for reporting back. We all can benefit from RingTFM :)
