### ISSUE TITLE
[BUG] anvi-setup-scgs-taxonomy writes SCGs database always to default location

### ISSUE THREAD

**Issue by karkman** [merenlab/anvio#2010]
## Short description of the problem

`anvi-setups-scgs-taxonomy` writes to default locations even with flag `--scgs-taxonomy-data-dir`.

## anvi'o version

```
Anvi'o .......................................: hope (v7.1)

Profile database .............................: 38
Contigs database .............................: 20
Pan database .................................: 15
Genome data storage ..........................: 7
Auxiliary data storage .......................: 2
Structure database ...........................: 2
Metabolic modules database ...................: 2
tRNA-seq database ............................: 2
```

## System info

Red Hat Enterprise Linux 8, anvio installed with conda + pip

## Detailed description of the issue

The command doesn't write the database to the specified location, but always to the default location. This is especially problematic with containers on HPC, that are read-only. So it is impossible to create the SCGs database.

**Comment by meren** [comment]
Hey @karkman, this issue should now be resolved for anvio-dev. Can you please git pull and test, and let us know if it is indeed the case?

Thank you for your patience.

**Comment by karkman** [comment]
Hi @meren, 

Huge thanks for fixing this!

I don't have  anvio-dev at the moment installed, but I have asked in discord, whether the user reporting this issue also in anvio-dev could test this. 
I probably should switch  to anvio-dev, so when I do, I will test this as well.

**Comment by dgslos** [comment]
When will this be released in the stable version?

**Comment by ivagljiva** [comment]
@dgslos, we don't have a specific timeline yet for v8 but we are working on getting it ready. The best I can tell you is 'soon' (if I had to guess, sometime in the next 2-3 months, but no guarantees) :)
