### ISSUE TITLE
[BUG] anvi-summarize shows HMMs warnings after anvi-import-collection with --contigs-mode

### ISSUE THREAD

**Issue by dot4822** [merenlab/anvio#2013]
## Short description of the problem

`anvi-summarize` shows HMMs warnings after `anvi-import-collection` with `--contigs-mode`

## anvi'o version

```
Anvi'o .......................................: hope (v7.1)

Profile database .............................: 38
Contigs database .............................: 20
Pan database .................................: 15
Genome data storage ..........................: 7
Auxiliary data storage .......................: 2
Structure database ...........................: 2
Metabolic modules database ...................: 2
tRNA-seq database ............................: 2
```

## System info

CentOS 7 with Anvi'o-7.1 installed via CONDA following the instructions on the Anvi'o website

## Detailed description of the issue

I am running `anvi-summarize` for a collection of bins clustered using external binning tools, and I have got `A WARNING RELATED TO HMMs` for several bins.

After looking into the detail of this warning, I am a bit of confused as I imported the collection using `anvi-import-collection` with `--contigs-mode`. Therefore, I don't think any splits would be excluded from the bins.

I have also checked the number of contigs in the summarised fasta file. It is exactly the same as the one in the external bin result table I used, but I am not sure whether there are any splits missing there (But I can re-run the DAS Tool and compare the outputs).

**Comment by meren** [comment]
Hi @dot4822,

The warnings were due to a bug which we fixed after `v7.1`. If all you have is the warnings, you don't need to worry about them.


Best wishes,
