### ISSUE TITLE
'anvi-setup-ncbi-cogs --reset' ends in makeblastdb error 

### ISSUE THREAD

**Issue by jahid10** [merenlab/anvio#2022]
## Short description of the problem

Something probably went wrong with 'makeblastdb' process since one of the
              expected output files are missing. Please check the log file here: 'blast-     
              log.txt'. 

anvio -7.1

```
anvi-self-test --version

Anvi'o .......................................: hope (v7.1)

Profile database .............................: 38
Contigs database .............................: 20
Pan database .................................: 15
Genome data storage ..........................: 7
Auxiliary data storage .......................: 2
Structure database ...........................: 2
Metabolic modules database ...................: 2
tRNA-seq database ............................: 2
```

## System info

Ubuntu 20.04.4

## Detailed description of the issue
Hi, I'm new on anvio. I tried to setup ncbi cog database multiple times. However, I seem to run one issue to the another multiple times. I tried to manually download the files from NCBI but that didn't work too. I tried to switch to a different ISP and run the command again with --reset flag too. Eventually, i hit this error multiple times. I checked the log file under the directory DB_BLAST but it doesn't have anything. Can anyone help me please?

I tired 'anvi-setup-ncbi-cogs' with  --debug and got this.

File "/home/bioinfo/mambaforge/envs/anvio-7.1/bin/anvi-setup-ncbi-cogs", line 46, in <module>
    setup.create()
  File "/home/bioinfo/mambaforge/envs/anvio-7.1/lib/python3.6/site-packages/anvio/cogs.py", line 615, in create
    self.setup_raw_data()
  File "/home/bioinfo/mambaforge/envs/anvio-7.1/lib/python3.6/site-packages/anvio/cogs.py", line 844, in setup_raw_data
    self.files[file_name]['func'](file_path, J(self.COG_data_dir, self.files[file_name]['formatted_file_name']))
  File "/home/bioinfo/mambaforge/envs/anvio-7.1/lib/python3.6/site-packages/anvio/cogs.py", line 812, in format_protein_db
    blast.makedb(os.path.join(output_db_path, 'COG.fa'))
  File "/home/bioinfo/mambaforge/envs/anvio-7.1/lib/python3.6/site-packages/anvio/drivers/blast.py", line 121, in makedb
    self.check_output(expected_output, 'makeblastdb')
  File "/home/bioinfo/mambaforge/envs/anvio-7.1/lib/python3.6/site-packages/anvio/drivers/blast.py", line 96, in check_output
    "Please check the log file here: '%s'" % (process, self.log_file_path))

**Comment by meren** [comment]
Hey @jahid10, unfortunately this is an issue related to 'download speeds'. Based on tens of similar reports we concluded that when the download takes too long the NCBI kills the connection for reasons that are not clear to us, which results in a crappy archive file. The solution is to try it over and over again :/ Sorry for not being able to help more here.

**Comment by jahid10** [comment]
[blast-log.txt](https://github.com/merenlab/anvio/files/10206136/blast-log.txt)
Hi, I have uploaded the log file from the makeblastdb. Can you please check and make sure that there is no other problem going on here.
Thank you

**Comment by meren** [comment]
Ah, thanks for sending this, @jahid10. This is not the issue I was thinking of, but related to your system.

If you Google the error message you should be able to find some answers (such as [this one](https://askubuntu.com/questions/339364/libssl-so-10-cannot-open-shared-object-file-no-such-file-or-directory)). If you are working on a server system, please ask your sys admin about this.

**Comment by jahid10** [comment]
Thanks for the solve. Finally, it worked and i successfully set up cog.

**Comment by meren** [comment]
🎉
