### ISSUE TITLE
anvi-self-test --suite pangenomics ends with missing R package tidyverse and qvalue.

### ISSUE THREAD

**Issue by jahid10** [merenlab/anvio#2024]
## Short description of the problem

Hi, I'm new in anvio. I have used the command "anvi-self-test --suite pangenomics" to check whether it's properly set. However I got this following error  "The following R packages are required in order to run this, but seem to be      
              missing or broken: 'tidyverse, qvalue'. If you have installed anvi'o through    
              conda, BEFORE ANYTHING ELSE we would suggest you to run the command Rscript -e  
              "update.packages(repos='https://cran.rstudio.com')" in your terminal....."

## anvi'o version

Anvi'o .......................................: hope (v7.1)

Profile database .............................: 38
Contigs database .............................: 20
Pan database .................................: 15
Genome data storage ..........................: 7
Auxiliary data storage .......................: 2
Structure database ...........................: 2
Metabolic modules database ...................: 2
tRNA-seq database ............................: 2

## System info
Ubuntu 20.04.4

## Detailed description of the issue
I have tried the solve mentioned in the config error but nothing seems to be wroking. If I run on my terminal it works fine and library(tidyverse) works fine too. However, in anvio environment : typing   $ Rscript -e "library(tidyverse)" produce the following error:

/home/bioinfo/mambaforge/envs/anvio-7.1/lib/R/bin/exec/R: /home/bioinfo/mambaforge/envs/anvio-7.1/lib/R/bin/exec/../../lib/../../libtinfo.so.6: no version information available (required by /lib/x86_64-linux-gnu/libreadline.so.6)
Error in library(tidyverse) : there is no package called ‘tidyverse’
Execution halted

**Comment by Gao-Lei-Xinjiang** [comment]
Config Error: The following R packages are required in order to run this, but seem to be
              missing or broken: 'tidyverse, stringi, magrittr, qvalue, optparse'. If you have
              installed anvi'o through conda, BEFORE ANYTHING ELSE we would suggest you to run
              the command Rscript -e "update.packages(repos='https://cran.rstudio.com')" in
              your terminal. This will try to update all R libraries on your conda environment
              and will likely solve this problem. If it doesn't work, then you will need to
              try a bit harder, so here are some pointers: if you are using conda, in an ideal
              world youshould be able to install these packages by running the following
              commands: "conda install -c r r-tidyverse", "conda install -c r r-stringi",
              "conda install -c bioconda r-magrittr", "conda install -c bioconda bioconductor-
              qvalue", "conda install -c conda-forge r-optparse". But if this option doesn't
              seem to be working for you, then you can also try to install the problem
              libraries directly through R, for instance by typing in your terminal, Rscript
              -e 'install.packages("tidyverse", repos="https://cran.rstudio.com")' and see if
              it will address the installation issue. UNFORTUNATELY, in some cases you may
              continue to see this error despite the fact that you have these packages
              installed :/ It would most likely mean that some other issues interfere with
              their proper usage during run-time. If you have these packages installed but you
              continue seeing this error, please run in your terminal Rscript -e
              "library(tidyverse)" to see what is wrong with tidyverse on your system. Running
              this on your terminal will test whether the package is properly loading or not
              and the resulting error messages will likely be much more helpful solving the
              issue. Apologies for the frustration. R frustrates everyone.




Config Error: According to the exit code ('255'), anvi'o suspects that something may have gone
              wrong while running your tests :/ We hope that the reason is clear to you from
              the lines above. But if you don't see anything obvious, and especially if the
              test ended up running until the end with reasonable looking final results, you
              shouldn't worry too much about this error. Life is short and we all can worry
              just a bit less.

Hello, when I run anvi-self-test --suite pangenomics, I got the above error. How can I fix it? anvio-7.1

**Comment by ivagljiva** [comment]
Hello, the Config Error message tells you what to do :)

Iva

-------------------------------------------------
Iva Veseli (she/her)
Graduate Student, Meren Lab
Biophysical Sciences Program
University of Chicago
