### ISSUE TITLE
TypeError: join() argument must be str or bytes, not 'int64'

### ISSUE THREAD

**Issue by LuisGuz** [merenlab/anvio#2025]
Dear Anvio developers.
I'm having trouble running the metagenomics workflow.
I'd appreciate any help.
Best regards.

After installation, I try to run the different workflows, and the following error appears:

$ anvi-run-workflow -w metagenomics                   -c default-metagenomics-config.json                   --save-workflow-graph

WARNING
===============================================
If you publish results from this workflow, please do not forget to cite
snakemake (doi:10.1093/bioinformatics/bts480)

WARNING
===============================================
We are initiating parameters for the metagenomics workflow

Traceback (most recent call last):
  File "/home/lg/miniconda3/envs/anviob/bin/anvi-run-workflow", line 77, in <module>
    main(args)
  File "/home/lg/envs/anviob/bin/anvi-run-workflow", line 50, in main
    M.init()
  File "/home/lg/miniconda3/envs/anviob/lib/python3.6/site-packages/anvio/workflows/metagenomics/__init__.py", line 211, in init
    self.profile_databases[group] = os.path.join(self.dirs_dict["MERGE_DIR"], group, "PROFILE.db") if self.group_sizes[group] > 1 else \
  File "/home/lg/miniconda3/envs/anviob/lib/python3.6/posixpath.py", line 94, in join
    genericpath._check_arg_types('join', a, *p)
  File "/home/lg/miniconda3/envs/anviob/lib/python3.6/genericpath.py", line 149, in _check_arg_types
    (funcname, s.__class__.__name__)) from None
TypeError: join() argument must be str or bytes, not 'int64'

$ anvi-self-test --version

Anvi'o .......................................: hope (v7.1)

Profile database .............................: 38
Contigs database .............................: 20
Pan database .................................: 15
Genome data storage ..........................: 7
Auxiliary data storage .......................: 2
Structure database ...........................: 2
Metabolic modules database ...................: 2
tRNA-seq database ............................: 2

## System info

I installed anvio in a new conda environment in Ubuntu 22.04.1 LTS, as specified in the instructions in https://anvio.org/install/.

**Comment by meren** [comment]
Sorry we couldn't get to this as fast, @LuisGuz. I hope the problem truly resolved itself? :)

**Comment by LuisGuz** [comment]
Thank you Dr. Eren.

Yes, apparently the problem was caused because of a mistake in the samples.txt format.
The problem was solved after replacing digits for a letter and digit in my "group" column.

Best regards.

**Comment by meren** [comment]
I see! Thank you for reporting back!

Best wishes,
Meren
