### ISSUE TITLE
[DISCUSSION] Update Bioconda recipe?

### ISSUE THREAD

**Issue by vinisalazar** [merenlab/anvio#2026]
Hi,

I was trying to install Anvi'o from the [conda recipe](https://github.com/bioconda/bioconda-recipes/blob/master/recipes/anvio/meta.yaml) but it seems a bit outdated, and furthermore I found a few problems, such as missing dependencies, etc.

My end goal is to easily install Anvi'o with a single command like `conda create -n anvio anvio`, instead of having to install dependencies manually in the conda environment.

I wanted to know if you would welcome a PR to the Bioconda recipes repository updating/improving the Anvi'o recipe? I thought it would be useful to open this issue for discussion.

Thank you in advance,
Vini

**Comment by vinisalazar** [comment]
Please see the referenced PR for context.

Thanks!
V

**Comment by meren** [comment]
Hey @vinisalazar,

Thanks for taking a look at this. While we did maintain a conda package for anvi'o for a while, we dropped it with v7. From having to wait long times to have conda recipes merged to the main repository, to significant wait times for end users as conda struggled to resolve dependencies during the installation step, there were multiple reasons that made us realize having full control over the installation procedure through a resource that anvi'o developers control on the web was the best solution for the vast majority of our users.

Maintaining anvi'o would have been impossible without conda. But in a weird way, having a conda package for anvi'o has not been the best way to make it accessible. You are more than welcome to maintain an up-to-date package for anvi'o on bioconda, but the instructions on our web page will likely have to stick with the current option.

My 2 cents :)

Best wishes,
Meren

**Comment by vinisalazar** [comment]
Thanks, that makes sense. I'll try improving the current recipe and would be happy to maintain it as an unofficial installation method.

**Comment by meren** [comment]
Thanks for your understanding, @vinisalazar. I will update the installation instructions and mention this effort in case there are likeminded people who would like to find you :)

PS: we have v8 coming out soon, and I hope you will soon hear about it through Discord or other means.

**Comment by vinisalazar** [comment]
Hi @meren, just an update on this: I got an improved recipe to work, but the large number of dependencies crashes the Bioconda CI machines so it's hard to pass their checks. So it's hard to find a workaround at the moment.

Thanks

**Comment by meren** [comment]
Thank you very much for reporting back, @vinisalazar. This is one of the issues we run into which led to the current solution :(
