### ISSUE TITLE
Interactive interface, TypeError: Cannot read properties of null (reading 'IsLeaf')

### ISSUE THREAD

**Issue by susheelbhanu** [merenlab/anvio#2027]
Hey all, 

I've seen other issues where some had similar challenges, but they were supposed to be fixed in v7.1. When trying to load existing bins, I'm getting this error still. Any thoughts on how to fix it?

The data is unfortunately quite large (~358 MB) for me to share but can do if necessary. 

Thank you,
Susheel 

*Anvi'o version: `7.1`*
```
TypeError: Cannot read properties of null (reading 'IsLeaf')
    at Bins.ExportCollection (http://0.0.0.0:20202/app/js/bin.js?rand=8f84e68305a8926c2db1870621ab7703:728:22)
    at Bins.MigrateCollection (http://0.0.0.0:20202/app/js/bin.js?rand=8f84e68305a8926c2db1870621ab7703:657:27)
    at Drawer.draw (http://0.0.0.0:20202/app/js/drawer.js?rand=27080d9960c59e50841c0f48f668ee0c:113:10)
    at m.fn.init.onShow (http://0.0.0.0:20202/app/js/main.js?rand=dc8ae97e936c551db841d2e84fc248c8:1616:28)
    at HTMLDivElement.<anonymous> (http://0.0.0.0:20202/app/lib/bootstrap-waitingfor/build/bootstrap-waitingfor.js?rand=eefe14fc39f3f156066a0e78a1a59711:134:22)
    at HTMLDivElement.dispatch (http://0.0.0.0:20202/app/lib/jquery/dist/jquery.min.js?rand=abf4eb6114fbea148f506142c7ca0052:4:8549)
    at r.handle (http://0.0.0.0:20202/app/lib/jquery/dist/jquery.min.js?rand=abf4eb6114fbea148f506142c7ca0052:4:5252)
    at Object.trigger (http://0.0.0.0:20202/app/lib/jquery/dist/jquery.min.js?rand=abf4eb6114fbea148f506142c7ca0052:4:7650)
    at HTMLDivElement.<anonymous> (http://0.0.0.0:20202/app/lib/jquery/dist/jquery.min.js?rand=abf4eb6114fbea148f506142c7ca0052:4:15517)
    at Function.each (http://0.0.0.0:20202/app/lib/jquery/dist/jquery.min.js?rand=abf4eb6114fbea148f506142c7ca0052:2:2975)```

**Comment by meren** [comment]
Hey @susheelbhanu, sorry to ask this, but do you have a means to try this on the main branch? The installation instructions for anvio-dev is [here](https://anvio.org/install/).

**Comment by susheelbhanu** [comment]
Absolutely can do. Won't get to it tonight, but first thing tomorrow. Thank you for the quick response!

**Comment by susheelbhanu** [comment]
Just putting this here, but the numbers in the output of the `anvi-self-test -v` that I am getting, compared to that on the installation instructions page is slightly different. I realise it's not an issue, but thought you should know.
```
Anvi'o .......................................: hope (v7.1-dev)

Profile database .............................: 38
Contigs database .............................: 20
Pan database .................................: 16
Genome data storage ..........................: 7
Auxiliary data storage .......................: 2
Structure database ...........................: 2
Metabolic modules database ...................: 4
tRNA-seq database ............................: 2
```

Another thing is that installing `fastani` is giving me the following error:
```
mamba install -y -c bioconda fastani
# Encountered problems while solving:
#  - package r-base-4.2.2-h6e3643f_2 requires icu >=70.1,<71.0a0, but none of the providers can be installed
```

Haven't yet figured out a way around it (yet).

**Comment by meren** [comment]
Yes, you did it! Don't worry about the fastani. Di you get the same error from `anvi-interactive` with this version?

**Comment by susheelbhanu** [comment]
Haven't had a chance to run it yet, cos life happened. Should be able to report back tomorrow morning though. Thanks for being patient with me🙏.

**Comment by meren** [comment]
👍

**Comment by susheelbhanu** [comment]
@meren I can now confirm that updating to the dev branch renders and loads the existing states. 

There still, however, seems to be an issue with `loading the bin collection`. As you can see from the figure, the phylogenetic tree is highlighted with the respective bins that I previously created, but for some reason the outer annotations and the highlights themselves are not loading. This is not a major issue for me, and I can simply mark the bins again, but I'm wondering if there's another bug. And you can see in the second screenshot, the earlier marked bins, i.e. `Singletons` and `Standard` essentially are reported as empty.

<img width="646" alt="Screenshot 2023-01-10 at 22 23 40" src="https://user-images.githubusercontent.com/9979661/211666610-4cdfbcf4-cbbd-4ae2-9762-7abc07d1b153.png">

<img width="378" alt="Screenshot 2023-01-10 at 22 27 22" src="https://user-images.githubusercontent.com/9979661/211666627-a610f349-2994-40ee-8131-fc75737ddb71.png">

**Comment by susheelbhanu** [comment]
On a distantly related note, I have a question about the interpretation of this figure. Each of these are genomes from the same species of Alistipes, collected across two dietary conditions. The MAGs were 95-100% complete, with many of them having the requisite ribosomal genes etc. 

In light of this, would the green and blue gene clusters at 7 o'clock and 9 o'clock respectively, be indicative of strain-level variation?

**Comment by meren** [comment]
> This is not a major issue for me, and I can simply mark the bins again, but I'm wondering if there's another bug. And you can see in the second screenshot, the earlier marked bins, i.e. `Singletons` and `Standard` essentially are reported as empty.

Hey @susheelbhanu, I'm glad you solved your main issue. The only explanation of the empty bins is that they were somehow stored without any items in them :/ since everything else is working with the imported bin, I'm having hard time imagining how else they could be empty. In any case, I suggest you to select them again and move on with your research :)

> In light of this, would the green and blue gene clusters at 7 o'clock and 9 o'clock respectively, be indicative of strain-level variation?

If all these genomes belong to the same 'species', I would confidently say that in theory, every variation you see here represents a strain level variation.

But I'm very confused how the middle blue genomes here can be missing SO MANY core gene clusters, especially if every genome here is high-quality and relatively well complete as far as SCGs go:

![image](https://user-images.githubusercontent.com/197307/211897233-62195106-d7a1-4e15-a787-895d2ed8c837.png)

Looking at more carefully I can see that their completion estimates as well as their total sizes are quite low compared to others in the pangenome. Perhaps it is a good idea to take them off and re-compute the pangenome. My 2 cents (by the way, for these kinds of discussions the anvi'o Discord may be a better revenue).

I'll close the issue since anvio-dev solved the original snafu. Thanks!


Best wishes,

**Comment by susheelbhanu** [comment]
Thanks very much for the insights @meren. I'll recheck the bins and try recomputing without the shady bins.

Best regards!!
