### ISSUE TITLE
[FEATURE REQUEST] Add read filter flags to `anvi-profile` in the config-file of the `metagenomics` workflow 

### ISSUE THREAD

**Issue by cifuj** [merenlab/anvio#2032]
Hi Anvi'o team,
 
## The need

I would like to be able to filter the reads that are included in the `anvi-profile` step of the `metagenomics` workflow. 
Currently, I can't add new flags to default config files. 

## The solution 

Add the flags `--min-percent-identity` and `--fetch-filter`  to the config file of the `metagenomics` workflow

## Beneficiaries

People working with the variability-profile. For instance to generate a variability-profile of reads mapping with > read-identity and mapped as paired-end.

**Comment by meren** [comment]
This is now implemented via https://github.com/merenlab/anvio/commit/5dac3538cdd2cc965827c80ef9774c533a45ec52, @cifuj. These parameters will be included in the default config.json files generated by `anvi-run-workflow` for `metagenomics` and will executed if they are changed by the user.

Thanks for the report!
