### ISSUE TITLE
[FEATURE REQUEST] Button for 'generate static summary with gene coverages'

### ISSUE THREAD

**Issue by ivagljiva** [merenlab/anvio#2034]
## The need

At the moment, `anvi-interactive` users can generate a summary of a collection from the interface by clicking on the button to generate a static summary. However, because `anvi-summarize` by default does not initialize gene coverage information (a potentially computationally-expensive step), the resulting summary has the gene coverage and detection files greyed out (photo provided by Zac Cooper):
![image](https://user-images.githubusercontent.com/10360586/215166269-fb87a1bb-4b70-4adc-91cb-a159feb21558.png)

We need an additional button that runs the summary function with the `--init-gene-coverages` argument so that these files can be generated from the interface. 

## The solution

Currently, the arguments for `anvi-summarize` as called from the interactive interface are defined in lines 1046-1050 of `bottleroutes.py`, in the `gen_summary()` function. However, simply adding the `--init-gene-coverages` flag there would result in gene coverage being initialized by default, which is potentially a bad idea given that it could take a lot of processing power for large collections.

We may need to add an additional function, similar to `gen_summary()` but with the gene coverages parameter added, and then call this function from the new button in the interface.

## Beneficiaries

Anyone who prefers to access summary data from the interface rather than from the command line. Tagging original requester @zscooper :)

**Comment by meren** [comment]
I think the best way to do it would be to make it such that the 'summarize' button in the interface brings up a modal window with some checkboxes for key parameters (for now it could be simply "[ ] init gene coverages") to pass them to the bottle callback function. I'm going to assign this to Mete, so perhaps he can take a look and discuss it with me if he has questions.

**Comment by FlorianTrigodet** [comment]
Great job guys! Unfortunately, as a professional software tester (lol) I have found two small issues:
- The gene coverage is always computed when I generate the summary from the interactive interface, with the box checked or not.
- Also, I can see the box when I want to summarize a pangenomic collection, but there should be no box, it is not useful for pangenomics.

**Comment by meren** [comment]
Thanks for testing, @FlorianTrigodet. I'll reopen the issue :/
