### ISSUE TITLE
anvi-get-split-coverages TypeError: a bytes-like object is required, not 'int'

### ISSUE THREAD

**Issue by wn835166087** [merenlab/anvio#2035]
## Short description of the problem

When I run anvi-get-split-coverages by bins, I got the error in the title

## anvi'o version

Anvio 7.1, installed via conda
Anvi'o .......................................: hope (v7.1)

Profile database .............................: 38
Contigs database .............................: 20
Pan database .................................: 15
Genome data storage ..........................: 7
Auxiliary data storage .......................: 2
Structure database ...........................: 2
Metabolic modules database ...................: 2
tRNA-seq database ............................: 2

```
anvi-self-test --version
```

## System info

macOS Monterey Version 12.0.1, installed via conda 23.1.10

## Detailed description of the issue

I run the command
```
anvi-get-split-coverages -p SAMPLES-MERGED/PROFILE.db -c all_flye_assembly.db \
                         -o microcystis_coverage.txt \
                         -b microcystis_merged \
                         -C concoct_collection
```

and I got error:
```
traceback (most recent call last):
  File "/Users/a123/opt/miniconda3/envs/anvio-7.1/bin/anvi-get-split-coverages", line 238, in <module>
    main(args)
  File "/Users/a123/opt/miniconda3/envs/anvio-7.1/bin/anvi-get-split-coverages", line 187, in main
    split_coverage_values = auxiliarydataops.AuxiliaryDataForSplitCoverages(profile_db.auxiliary_data_path, profile_db.p_meta['contigs_db_hash'], db_variant=profile_db_variant).get(split_name)
  File "/Users/a123/opt/miniconda3/envs/anvio-7.1/lib/python3.6/site-packages/anvio/auxiliarydataops.py", line 127, in get
    split_coverage[sample_name] = utils.convert_binary_blob_to_numpy_array(coverage_blob, dtype=self.coverage_dtype)
  File "/Users/a123/opt/miniconda3/envs/anvio-7.1/lib/python3.6/site-packages/anvio/utils.py", line 769, in convert_binary_blob_to_numpy_array
    return np.frombuffer(gzip.decompress(blob), dtype=dtype)
  File "/Users/a123/opt/miniconda3/envs/anvio-7.1/lib/python3.6/gzip.py", line 531, in decompress
    with GzipFile(fileobj=io.BytesIO(data)) as f:
TypeError: a bytes-like object is required, not 'int'
```

**Comment by meren** [comment]
Hi @wn835166087, 

I don't seem to be able to reproduce this error. Would you mind trying anvio-dev and see if the problem persists?


Best wishes,

**Comment by ivagljiva** [comment]
As this issue has not been updated in the past few months, I would assume that switching to `anvio-dev` did the trick. Feel free to update us if that is not the case @wn835166087. 

Closing this for now :)
