### ISSUE TITLE
[BUG] Tidyverse Environment won't solve

### ISSUE THREAD

**Issue by SevanEsaian** [merenlab/anvio#2051]
Hello, I am trying to install anvi'o on my university's cluster. I am following the anvi'o installation guide and have encountered a problem with tidyverse. The problem is that the environment won't solve when I use the command: 
```
conda install -y -c bioconda r-tidyverse
```
I looked at a different [GitHub post and also tried their suggestion](https://github.com/merenlab/anvio/issues/1918)
```
conda install -c r r-tidyverse
```
I still have the same problem which is that the environment won't solve. 
I would greatly appreciate any suggestions for installing tidyverse correctly. I have had no installation problems for any of the other packages before reaching tidyverse in the tutorial. 

Thank you for your help.

**Comment by kylakell** [comment]
I am still having trouble with `conda install -c r r-tidyverse` with python 3.6 and with the Rscript above. Any further suggestions? I'm trying to install it on an hpc

**Comment by metehaansever** [comment]
> I am still having trouble with `conda install -c r r-tidyverse` with python 3.6 and with the Rscript above. Any further suggestions? I'm trying to install it on an hpc

Instead of using python 3.6, you can use 3.7 with anvio-dev.

**Comment by ivagljiva** [comment]
This issue has been quiet for a few months, so I will close it. @kylakell or @SevanEsaian , if either of you are still having issues, please feel free to reopen this issue and give us an update :)
