### ISSUE TITLE
anvi-self-test error: C extension: /lib64/libm.so.6: version `#GLIBC_2.29' not found

### ISSUE THREAD

**Issue by valc30** [merenlab/anvio#2055]
## Short description of the problem

Hi everyone, I'm a  newbie , so sorry in advance if I bring an obvious question!
After intalling Anvio following https://anvio.org/install/#3-install-anvio , anvi-self-test returns (amongst other things) ImportError: /lib64/libm.so.6: version `GLIBC_2.29' not found 

## System info
I'm on Windows, using MobaXterm connected to a server with a UNIX environment
 Installed Anvio following https://anvio.org/install/#3-install-anvio

## Detailed description of the issue
![image](https://user-images.githubusercontent.com/127342855/224189215-a87c7ef1-cb69-4c5a-8e4e-89da76772d49.png)

ldd (Gentoo 2.30-r8 p10) 2.30
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

![image](https://user-images.githubusercontent.com/127342855/224190348-e2ac11c3-9640-42cb-bdae-a91248b33a98.png)

**Comment by meren** [comment]
hi @valc30, looking from here, the installation doesn't look quite right, but I'm not sure what led to your python in the conda environment to import functionality from somewhere else. I'd suggest you to get in touch with the sys admin of the server you are connecting to :(
