### ISSUE TITLE
Config Error: There are multiple gene calls in 'file

### ISSUE THREAD

**Issue by neelam19051** [merenlab/anvio#2057]
Hi, I am following the manual of pan genomics to analyze enrichment and I am getting this error please have a look once.

anvi-get-sequences-for-gene-clusters -p ~/Neelam/44_fna/out_pae/p_aeru_43-PAN.db -g paer_final-GENOMES.db    -C default -b  Bin_1  --concatenate-gene-clusters -o bin1_core.fa
Mode .........................................: Working with gene clusters in collection default and bin Bin_1.                                                                                              
Functions found .............................................: COG20_FUNCTION, COG20_CATEGORY, Pfam, KOfam, KEGG_Module, KEGG_Class, COG20_PATHWAY                                                           
Genomes storage .............................................: Initialized (storage hash: hash8fee006f)                                                                                                      
Num genomes in storage ......................................: 43
Num genomes will be used ....................................: 43
Pan DB ......................................................: Initialized: /home/bvs/Neelam/44_fna/out_pae/p_aeru_43-PAN.db (v. 15)
Gene cluster homogeneity estimates ..........................: Functional: [YES]; Geometric: [YES]; Combined: [YES]

* A short announcement for the curious: anvi'o found 9914 gene clusters in the
database, attempted to initialize a gene clusters dictionary for 587 of them as
requested by the user or the programmer, and managed to get back a gene clusters
dictionary with 587 items. We just hope all these make sense to you.

GENE CLUSTER FILTERS
==============================================================
Based on --min-num-genomes-gene-cluster-occurs 0, --max-num-genomes-gene-
cluster-occurs 43, --min-num-genes-from-each-genome 0, --max-num-genes-from-
each-genome 43, --min-functional-homogeneity-index -1.000, --max-functional-
homogeneity-index 1.000, --min-geometric-homogeneity-index -1.000, --max-
geometric-homogeneity-index 1.000, --min-combined-homogeneity-index -1.000,
--max-combined-homogeneity-index 1.000 (some of these may be default values, no
need to panic).

All gene clusters (587) .....................................: GC_00004959, GC_00004750, GC_00004705, (... 584 more (`--debug` will show all))
Gene clusters that passed the filter (587) ..................: GC_00004959, GC_00004750, GC_00004705, (... 584 more (`--debug` will show all))
Genes clusters that failed the filter (0) ...................: None.

INFO
===============================================
Your filters resulted in 587 gene clusters that contain a total of 25241 genes.
for downstream analyses. Just so you know.

Config Error: There are multiple gene calls in 'GC_00005132' and sample
              'P_aeruginosa_SRRSH1101', which is not appropriate for phylogenomic analyses.
              Please use advanced filters (see help if you are not sure what this means) to
              remove gene clusters from your analysis if they contain multiple gene calls from
              any of the genomes in your pan (not to tell you what to do, but '--max-num-
              genes-from-each-genome 1' would make sure gene clusters that contain multiple
              genes from a given genome would be removed from your final list).

thank you!

**Comment by meren** [comment]
Hey @neelam19051, the error message is very clear: there are multiple genes in the gene cluster `GC_00005132` from the genome `P_aeruginosa_SRRSH1101`, which means you don't have clean list of single-copy core gene families for a phylogenomic analysis.

You need to make sure the list of gene clusters you use for the phylogenomics comply with the `--max-num-
genes-from-each-genome 1` requirement.
