### ISSUE TITLE
[FEATURE REQUEST] Add another option for anvi-script-add-default-collection

### ISSUE THREAD

**Issue by FlorianTrigodet** [merenlab/anvio#2068]
## The need

When we use long-read assemblies, we can be tempted to consider each contig as a MAG/genome, especially if you filter for a high min contig size. To get quick info on these putative genomes, I usually create a fake collection where each contig has its own bin. It is not very hard to do, but I realize that we already have a script command which does something very similar: anvi-script-add-default-collection.

This command create a default collection of one bin for all contigs (when your contigs correspond to one genome and you know it). 

I suggest we add a parameter in this command to create a default collection with as many bins as contigs. 

## The solution

An option like `--collection-type` with either "everything" (could be default) and "each". Or something like that. 

## Beneficiaries

Mostly people working with long-read assemblies. So more and more people.

**Comment by meren** [comment]
This is now done :)
