### ISSUE TITLE
external gene calls with Augustus output

### ISSUE THREAD

**Issue by ereyred** [merenlab/anvio#2069]
## Short description of the problem

Cannot input Augustus gene calls into anvio

## Detailed description of the issue

I want to use anvio with my de novo eukaryotic genome assembly to remove contaminants (https://merenlab.org/2015/06/25/screening-cultivars/).

I have done gene prediction with a variety of programs (braker which does augustus and genemark, transdecoder) and combined these all with EvidenceModeler (EVM). Since my species is eukaryotic I don't want anvio to do gene calls with prodigal, so I wanted to add external-gene-calls to the db generation step. But this is proving difficult. The outputs of EVM and all the previous steps are gff or gtf, but not the exact format required as input for anvio external-gene-calls. I tried doing anvi-script-augustus-output-to-external-gene-calls with my augustus output but this output is in gtf format (and I can't run augustus on its own with the -gff3 output tag because my species is not trained for). I've tried converting the augustus.hints.gtf file to gff/gff3 with several programs (from biocode, GAAS, EVM) but it is not giving me a format that anvi-script-augustus-output-to-external-gene-calls can use (results in Num genes parsed = 0).

Is there any way to edit the augustus output format to input into anvio?
Or a way to input any of the other gene prediction calls, preferably from EVM?

## Files to reproduce

The formats look as follows:

Augustus.gtf
scaffold_1      AUGUSTUS        gene    2       677     0.83    -       .       g1
scaffold_1      AUGUSTUS        transcript      2       677     0.83    -       .       g1.t1
scaffold_1      AUGUSTUS        CDS     2       272     0.84    -       0       transcript_id "g1.t1"; gene_id "g1";
scaffold_1      AUGUSTUS        exon    2       272     .       -       .       transcript_id "g1.t1"; gene_id "g1";
scaffold_1      AUGUSTUS        intron  273     536     1       -       .       transcript_id "g1.t1"; gene_id "g1";

Genemark.gtf
scaffold_1      GeneMark.hmm3   CDS     21      185     .       -       0       gene_id "1_g"; transcript_id "1_t"; cds_type "Internal"; count "2_2";
scaffold_1      GeneMark.hmm3   gene    21      677     .       -       .       gene_id "1_g"; transcript_id "1_t";
scaffold_1      GeneMark.hmm3   mRNA    21      677     .       -       .       gene_id "1_g"; transcript_id "1_t";
scaffold_1      GeneMark.hmm3   intron  186     536     .       -       0       gene_id "1_g"; transcript_id "1_t";
scaffold_1      GeneMark.hmm3   CDS     537     677     .       -       0       gene_id "1_g"; transcript_id "1_t"; cds_type "Initial"; count "1_2";
scaffold_1      GeneMark.hmm3   start_codon     675     677     .       -       0       gene_id "1_g"; transcript_id "1_t";
scaffold_1      GeneMark.hmm3   stop_codon      1309    1311    .       -       0       gene_id "2_g"; transcript_id "2_t";

braker.gtf
scaffold_1      AUGUSTUS        gene    2       677     .       -       .       g1
scaffold_1      AUGUSTUS        transcript      2       677     0.83    -       .       g1.t1
scaffold_1      AUGUSTUS        CDS     2       272     0.84    -       0       transcript_id "g1.t1"; gene_id "g1";
scaffold_1      AUGUSTUS        exon    2       272     .       -       .       transcript_id "g1.t1"; gene_id "g1";
scaffold_1      AUGUSTUS        intron  273     536     1       -       .       transcript_id "g1.t1"; gene_id "g1";

EVM
scaffold_30     EVM     gene    17      1282    .       +       .       ID=evm.TU.scaffold_30.1;Name=EVM%20prediction%20scaffold_30.1
scaffold_30     EVM     mRNA    17      1282    .       +       .       ID=evm.model.scaffold_30.1;Parent=evm.TU.scaffold_30.1;Name=EVM%20prediction%20scaffold_30.1
scaffold_30     EVM     exon    17      144     .       +       .       ID=evm.model.scaffold_30.1.exon1;Parent=evm.model.scaffold_30.1
scaffold_30     EVM     CDS     17      144     .       +       0       ID=cds.evm.model.scaffold_30.1;Parent=evm.model.scaffold_30.1
scaffold_30     EVM     exon    280     1282    .       +       .       ID=evm.model.scaffold_30.1.exon2;Parent=evm.model.scaffold_30.1
scaffold_30     EVM     CDS     280     1282    .       +       1       ID=cds.evm.model.scaffold_30.1;Parent=evm.model.scaffold_30.1

Thank you!!

**Comment by meren** [comment]
Hi @ereyred, apologies for the very late response. An example AUGUSTUS output anvi'o is able to work with is shown here:

https://anvio.org/help/main/artifacts/augustus-gene-calls/

I just tested, and everything seems to be working with output files formatted as such.

Here are some questions if you're still interested in pursuing this issue: Which version of AUGUSTUS are you using? If it is not 3.3.3, would you please send me the actual output file from the program? The information you shared above is not quite useful to identify the problem :/


Best wishes,
