### ISSUE TITLE
[BUG] Product attribute in GFF output can include reserved characters

### ISSUE THREAD

**Issue by philipwoods** [merenlab/anvio#2070]
## Short description of the problem

When using `anvi-get-sequences-for-gene-calls` with the `--export-gff3` flag, attributes in column 9 are sometimes formatted incorrectly.

## anvi'o version

```
Anvi'o .......................................: hope (v7.1)

Profile database .............................: 38
Contigs database .............................: 20
Pan database .................................: 15
Genome data storage ..........................: 7
Auxiliary data storage .......................: 2
Structure database ...........................: 2
Metabolic modules database ...................: 2
tRNA-seq database ............................: 2
```

## System info

OS is Red Hat Enterprise Linux release 8.3 (Ootpa).
Anvi'o is installed as a conda environment.

## Detailed description of the issue

When generating GFF files, Anvi'o currently places any gene annotations in the 'product' attribute in column 9 of the file. Depending on the annotation source, this information may contain large amounts of text, sometimes including non-alphanumeric characters. Some of these characters are reserved in the GFF3 file format, but are not escaped properly in the output from Anvi'o. This can lead to these files being incorrectly parsed by other software.

In the GFF3 file specification (found [here](https://github.com/The-Sequence-Ontology/Specifications/blob/master/gff3.md)), they state that the semicolon, comma, equals sign, and ampersand are reserved in column 9. Many gene annotation sources often contain commas in their annotation data. Also, when referencing PubMed, COG annotations use semicolons to delimit lists with multiple PubMed IDs. The Anvi'o tRNAs annotation source also often uses semicolons (or did the last time I checked).

When creating GFF3 files, Anvi'o should check the data that will be added to attributes in column 9 of the output for these reserved characters and escape them as described in the file specification.

## Files to reproduce

Here is a small contigs database where the COG20_FUNCTION annotations sometimes contain commas and/or semicolons: [Rnf_example.zip](https://www.dropbox.com/s/ur5j25do6kupu6j/Rnf_example.zip?dl=0)

To reproduce, run `anvi-get-sequences-for-gene-calls --export-gff3 -c Rnf_example.db -o Rnf_example.gff` in Anvi'o 7.1 or
`anvi-get-sequences-for-gene-calls --export-gff3 -c Rnf_example.db -o Rnf_example.gff --annotation-source COG20_FUNCTION` in the dev version.

Note the raw commas in the product attribute for many of the genes, and the raw semicolon in the product attribute for gene 8.

**Comment by meren** [comment]
Thank you very much for reporting this, @philipwoods, and apologies for the delay responding to your message.

If I understand correctly, replacing semicolon, comma, equals sign, and ampersand symbol with a space would address this issue.

With 9a76617d7e8d8e45efa1179465ba6f20f3b122a2 this issue should be resolved in anvio-dev. Please let me know if it is not the case and thank you for your patience.
