### ISSUE TITLE
update db version

### ISSUE THREAD

**Issue by JoseLopezArcondo** [merenlab/anvio#2074]
## I have an older version of the database which does not work in latest 7.1 version. I don't know how to update it. I tried with "anvi-migrate --migrate-dbs-safely ca_contigs.db" , it gives me

Database Path ................................: ca_contigs.db
Detected Type ................................: contigs
Current Version ..............................: 20
Target Version ...............................: 20
Migration mode ...............................: Safe

SQLite Version ...............................: 3.41.2

when I run "anvi-interactive -v":

Anvi'o .......................................: hope (v7.1)

Profile database .............................: 38
Contigs database .............................: 20
Pan database .................................: 15
Genome data storage ..........................: 7
Auxiliary data storage .......................: 2
Structure database ...........................: 2
Metabolic modules database ...................: 2
tRNA-seq database ............................: 2
 

but when I run "anvi-interactive -p SAMPLES-MERGED/PROFILE.db -c ca_contigs.db", it tells me

Config Error: The database at 'SAMPLES-MERGED/PROFILE.db' is outdated (this database is v35   
              and your anvi'o installation wants to work with v38). You can migrate your      
              database without losing any data using the program `anvi-migrate` with either of
              the flags `--migrate-dbs-safely` or `--migrate-dbs-quickly`.                    

how can I correctly update this, I cannot find a simple way... Where do I get the -t parameter I need from?

Thanks a lot

**Comment by meren** [comment]
You need to migrate your profile-db as well, @JoseLopezArcondo :) According to your command, you seem to have migrated only your contigs-db.

**Comment by meren** [comment]
```
anvi-migrate SAMPLES-MERGED/PROFILE.db --migrate-dbs-safely
```
