### ISSUE TITLE
[BUG] anvi-setup-ncbi-cogs error

### ISSUE THREAD

**Issue by Miseonn** [merenlab/anvio#2086]
## Short description of the problem

When I try to run anvi-setup-ncbi-cogs, the config error comes up as below.

Config Error: Something went wrong with your download attempt. Here is the problem for the url
              ftp://ftp.ncbi.nih.gov/pub/COG/COG2020/data/cog-20.cog.csv: '<urlopen error ftp 
              error: ConnectionResetError(104, 'Connection reset by peer')>'       

## anvi'o version

Anvi'o .......................................: hope (v7.1)

Profile database .............................: 38
Contigs database .............................: 20
Pan database .................................: 15
Genome data storage ..........................: 7
Auxiliary data storage .......................: 2
Structure database ...........................: 2
Metabolic modules database ...................: 2
tRNA-seq database ............................: 2

## System info

operating system: Ubuntu 20.04.6 LTS
how did you install anvi'o:  I followed the intall step in the web page.

**Comment by ivagljiva** [comment]
This issue is a duplicate of https://github.com/merenlab/anvio/issues/1738, which is now solved in the development branch. 

The only solution for anyone on v7.1 is to re-run `anvi-setup-ncbi-cogs` until it works.

**Comment by shanexuuu** [comment]
https://github.com/merenlab/anvio/issues/1738
