### ISSUE TITLE
[FEATURE REQUEST] Add "function" column to anvi-compute-functional-enrichment-across-genomes output

### ISSUE THREAD

**Issue by kellikmullane** [merenlab/anvio#2092]
## The need

I'm not sure if this used to be a function and it got lost/dropped at some point (or hopefully it's not just an issue with my machine/install), but I've been using `anvi-compute-functional-enrichment-across-genomes` a ton, and have found it tedious and time-consuming (especially with the number of genomes/groups I'm working with) to analyze the output in a meaningful way. While the `functional-enrichment.txt` output provides an accession value, it does not list the actual function associated with the accession. 

<img width="589" alt="Screenshot 2023-07-20 at 2 57 34 PM" src="https://github.com/merenlab/anvio/assets/71904553/75af0100-1dda-4ef4-9cb4-3839dea4c272">

What I've been having to do is either look up the accession online, or cross-reference it with the functional occurrence table (provided by the additional parameter `--functional-occurrence-table-output`). While this is fine, it would save SO much time if this "function" was just included in the `functional-enrichment.txt` output. 

I saw on the Microbial Pangenomics Tutorial that the output shown under the "Quantifying functional enrichment in a pangenome" section does list the function in the output, but this example uses `anvi-compute-functional-enrichment-in-pan`. 

## The solution

Add a "function" column in the `functional-enrichment.txt` output of `anvi-compute-functional-enrichment-across-genomes`.

## Beneficiaries

I think this would be of great benefit to anyone who uses the command `anvi-compute-functional-enrichment-across-genomes`.

**Comment by meren** [comment]
Hey @kellikmullane, thank you very much for reporting this. I'm not sure what happened, but we indeed lost that column at some point :) I just fixed the problem in the codebase. Please `git pull` your anvio-dev and try again. You should find the functional annotation column in your updated output file.


Best wishes,

**Comment by kellikmullane** [comment]
Ohh wow - thanks for getting to this so quickly! You have no idea how much time this will save me - thank you!!
