### ISSUE TITLE
anvi-rename-bins_ Config Error

### ISSUE THREAD

**Issue by nahbergo** [merenlab/anvio#2093]
Hi, 

 I am having error with the anvi-rename-bins.
I don't know why. 

Here is the command I used:
anvi-rename-bins -p SAMPLES-MERGED/PROFILE.db -c 03_CONTIGS/contigs.db --collection-to-read CONCOCT --collection-to-write selectedMAGs --call-MAGs --prefix M250 --min-completion-for-MAG 40 --max-redundancy-for-MAG 15 --report-file REPORT_rename_mags

And here is the error report:

Config Error: TablesForCollections::append: 143 split names or contig IDs appear more than
              once in your input for this collection. This part of the code is unable to  
              predict how you may have ended up here, but check your input file maybe? :/ 

Could you please, help me?

**Comment by meren** [comment]
Hey @nahbergo, I just tested your command and it seems to be working fine in `anvio-dev`. Sorry, I'm not sure how you ended up here.

But I realize there is a problem with filtering based on completion and I'll look into that.

**Comment by meren** [comment]
If you hadn't removed the the issue template and leave all the questions it requested you to respond unanswered, I may have had some suggestions.

**Comment by nahbergo** [comment]
Sorry I do not understand. What questions were not answered? Yes, I accept suggestions.

**Comment by nahbergo** [comment]
> If you hadn't removed the the issue template and leave all the questions it requested you to respond unanswered, I may have had some suggestions.


 Sorry I do not understand. What questions were not answered? Yes, I accept suggestions.
