### ISSUE TITLE
[BUG] anvi-display-pan， when I run the following command, the local interactive interface cannot pop up.....

### ISSUE THREAD

**Issue by Menggong-li** [merenlab/anvio#2107]
## Local interactive interface cannot pop up

Replace this text with a single-sentence description of the problem.

## anvi'o version 7.1

anvi-display-pan -p 03_PAN/MYPAN-PAN.db -g 03_PAN/MYPAN-GENOMES.db --title "Sedimenticola pangenome" -I xx.xxx.xx.xx -P 8080

**Comment by meren** [comment]
This doesn't sound like a bug. Please try our Discord server for usage related questions :)
