### ISSUE TITLE
anvi-init-bam bug in anvio-dev branch 

### ISSUE THREAD

**Issue by jwilliams648** [merenlab/anvio#2114]
## Short description of the problem

There is a typo in line 446 of anvio/terminal.py (if warp_width < 40 ... should read wrap_width)

## anvi'o version

Anvio-dev (as of 4 pm PST Sep 6, 2023) 

```
anvi-self-test --version
```

## System info

anvio-dev install instructions (wizar-arry) 

## Detailed description
line 446, in info if warp_width < 40:
NameError: name 'warp_width' is not defined
variable name should be 'wrap_width'

**Comment by jjcolgan** [comment]
I am getting this error on anvi-run-workflow and anvi-run-hmms as well.

**Comment by meren** [comment]
There was indeed a typo, @jwilliams648. I'm sorry. That's what happens when someone who shall not be named here commits a [quick fix](https://github.com/merenlab/anvio/commit/9cf3e912691c6bb2ad2bbeb52d8cb2f3169adeb3) for something close to midnight :/ It is now resolved.
