### ISSUE TITLE
COG functions share the same enrichment score

### ISSUE THREAD

**Issue by Ahmed-Shibl** [merenlab/anvio#2119]
Hello anvio peeps! I apologize in advance if my question/this discussion has been addressed or answered before.

I ran the gene enrichment analysis using my generated MAGs and reference genomes that belong to the Proteobacteria taxa. The output file showed several COG functions associated with the group of interest (in my case it was 'Healthy-Weight') and many of them had the exact same enrichment score of 11.913.

My question is general; what does it mean when the majority of the COG functions are assigned the same enrichment score and q values? I would appreciate if you point me towards where I could find the answer myself and I'd be happy to come back with more in-depth questions. 

Thanks in advance!

**Comment by meren** [comment]
You will get the exact same enrichment score and q values for a set of functions that occur at the same frequency across all genomes in one group versus the other. If you were to find a colleague in your institution who specialise in statistics, they would be a great help to shed some light on such tests.


Best wishes,
Meren
