### ISSUE TITLE
[FEATURE REQUEST] Documentation for metabolic reaction network toolkit

### ISSUE THREAD

**Issue by meren** [merenlab/anvio#2124]
## The need

For the new toys in our codebase made available through the heroic efforts of @semiller10 via #2123, we need,

- More comprehensive documentation for the new programs and artifacts
- Component tests with a minimal test scenario to keep them in our minds

## The solution

Addressing the following concerns would be the best solution.

### Docs

Here are some of the artifacts and programs that need love:

- [x] `anvi-setup-modelseed-database` (`anvio/docs/programs/anvi-setup-modelseed-database.md`, currently empty)
- [x] `anvi-reaction-network` (`anvio/docs/programs/anvi-reaction-network.md`, currently empty)
- [x] `anvi-get-metabolic-model-file ` (`anvio/docs/programs/anvi-get-metabolic-model-file.md`, currently empty)
- [x] `reaction-network` (`anvio/docs/artifacts/reaction-network.md`, has minimal info)
- [x] `reaction-network-json` (`anvio/docs/artifacts/reaction-network-json.md`, has minimal info -- could use a brief example and more information regarding which flux balance analysis tools / standards it is compatible with)

### Component tests

- [x] A minimal test case is missing for the new programs and their use cases -- `anvio/tests/run_component_tests_for_metabolism.sh` may be a good place to implement them.

## Beneficiaries

Anvi'o users who are interested in understanding how to use these tools effectively :)

**Comment by semiller10** [comment]
Some of the documentation was stored in files without the requisite `.md` extension, but I fleshed it out a lot more with the help of your handy checklist.

I added reaction network tests to the metabolism self-test suite.

**Comment by meren** [comment]
You are the absolute best, Sam. Thank you very much.
