### ISSUE TITLE
Failed to setup CAZymes with `anvi-setup-cazymes`

### ISSUE THREAD

**Issue by IsabelFE** [merenlab/anvio#2139]
## Short description of the problem

Anvi'o failed to setup CAZymes at the stage of downloading the data (V11' does not exist on the server)

## anvi'o version

```
Anvi'o .......................................: marie (v8)
Python .......................................: 3.10.12

Profile database .............................: 38
Contigs database .............................: 21
Pan database .................................: 16
Genome data storage ..........................: 7
Auxiliary data storage .......................: 2
Structure database ...........................: 2
Metabolic modules database ...................: 4
tRNA-seq database ............................: 2
```

## System info

Mac Sonoma 14.0 (Chip M1). Anvio installed followed the instructions 

## Detailed description of the issue

I am getting this error when running `anvi-setup-cazymes `

Config Error: Anvi'o failed to setup your CAZymes at the stage of downloading the data :/ It  
              is very likely that the version 'V11' does not exist on the server, or the      
              locations of the files have changed. If you are certain that your internet      
              connection works well otherwise, please let the anvi'o developers know about    
              this issue, and they will find a solution. Here is the error message that came  
              from the depths of the code for your reference: 'Something went wrong with your 
              download attempt. Here is the problem for the url                               
              https://bcb.unl.edu/dbCAN2/download/Databases/V11/dbCAN-HMMdb-V11.txt: '<urlopen
              error [Errno 60] Operation timed out>''.

**Comment by meren** [comment]
Hey @IsabelFE, I don't seem to get a response from the server at https://bcb.unl.edu/dbCAN2/download/Databases/.

So I think a time-out error is perfectly appropriate and there is nothing we can do other than wait and hope that the dbCAN servers will come back to life.

**Comment by meren** [comment]
:)

![image](https://github.com/merenlab/anvio/assets/197307/6f7b9d6d-55a9-4dcc-b299-6ac541caf584)

**Comment by IsabelFE** [comment]
Sorry about that, I did not realize it was an issue with the server.
It works now!

The CAZyme database V11 is successfully setup on your computer for anvi'o to use
  🎉 Now you can use the program `anvi-run-cazyme` on any contigs-db file to
  annotate genes in them with CAZymes.
