### ISSUE TITLE
Process stops midway and does not create the PROFILES.db on Anvio

### ISSUE THREAD

**Issue by Azimdine** [merenlab/anvio#2140]
## Short description of the problem
Dear all,
After running a metagenomics analysis in a SqueezeMeta tool and get output datas,
i run output on anvio for downstream analysis and visualistaion.
After 21:07:16 hours of run, it stops sometime and is unable to create the PROFILE.db and throws an error.

Any help, suggestions, solutions?

## anvi'o version

anvio version 8

```
anvi-self-test --version
```

## System info

LINUX on a server
installation was made following this tutorial:
https://anvio.org/install/linux/stable/

## Detailed description of the issue

Keep the header of this section, but replace this text with a clear description of what you expected to happen and what happened instead. Try to include screenshots, complete error text from your terminal, and exact commands you've run to get those errors. If you don't think you need additional description of the problem and your short description is sufficient, feel free to remove this section along with its header.
[Capture d’écran 2023-10-05 à 13.53.21.zip](https://github.com/merenlab/anvio/files/12819866/Capture.d.ecran.2023-10-05.a.13.53.21.zip)
[anvi-load-sqm.logfile.zip](https://github.com/merenlab/anvio/files/12819881/anvi-load-sqm.logfile.zip)
[Uploading batch.err.zip…]()
[batch.out.zip](https://github.com/merenlab/anvio/files/12819904/batch.out.zip)
[anvio.sh.zip](https://github.com/merenlab/anvio/files/12819911/anvio.sh.zip)

cordially
Azim

**Comment by meren** [comment]
Hi @Azimdine,

There is not information in any of these log files to determine what the error might be related to, but I don't think this is an anvi'o issue. I'd get in touch with the developers of SqueezeMeta and ask for their help on "how to figure out what is the actual error message for a given step that fails". We may be able to help more if we knew the Traceback (detailed error output) from anvi'o.


Best wishes,

**Comment by Azimdine** [comment]
Dears,
Thank you for reply.
I had also opened an issue on SqueezeMeta for this error but not yet goes response. I have seen also someone else open the same issue before but did not yet have the response of the question.
Anyway, when I had install anvio, in the checking installation step, I have not get an error but I did not get the interactive interface on my browser. I get just: test is done and datas are gone.
Also, I did not go in the 6.1 step for installation of the setup key resources. So I don’t know if this can cause the error.

In other hands, yesterday, I have uninstalled anvio and reinstall it with all step. I lunched the SqueeZemeta output in anvio. I’am waiting to see if everything will go well this time.Cross fingers.
For information, this the tutorial of lunching SqueezeMeta data on anvio
https://github.com/jtamames/SqueezeMeta/wiki/Loading-SQM-results-into-anvi'o

cordially
Azim

De : "A. Murat Eren (Meren)" ***@***.***>
Répondre à : merenlab/anvio ***@***.***>
Date : vendredi 6 octobre 2023 à 09:35
À : merenlab/anvio ***@***.***>
Cc : Azimdine HABIB ***@***.***>, Mention ***@***.***>
Objet : Re: [merenlab/anvio] Process stops midway and does not create the PROFILES.db on Anvio (Issue #2140)


Hi @Azimdine<https://urldefense.com/v3/__https:/github.com/Azimdine__;!!JFdNOqOXpB6UZW0!rHPcR5aNveImWEYtdS-4EFRpB3NjELvfl-bSJ-grnqw35YYS5R-666oWMR1-vMwQQhta3jRCzbIuPZBk3sG1wYa11iICQt4$>,

There is not information in any of these log files to determine what the error might be related to, but I don't think this is an anvi'o issue. I'd get in touch with the developers of SqueezeMeta and ask for their help on "how to figure out what is the actual error message for a given step that fails". We may be able to help more if we knew the Traceback (detailed error output) from anvi'o.

Best wishes,
