### ISSUE TITLE
anvio 7.1: anvi-setup-ncbi-cogs --reset

### ISSUE THREAD

**Issue by 17863952296** [merenlab/anvio#2145]
when I anvi-setup-ncbi-cogs --reset， I encountered the error :It is likely that the download failed and only part of the file was downloaded. If you would like to try again, please run the setup command with the flag `--reset`. Here is what the downstream library said: 'Error -3 while decompressing data: invalid  stored block lengths'.
when I try "anvi-setup-ncbi-cogs --reset" again, it happened again. so How shoud I cope with it ?

**Comment by meren** [comment]
By installing the latest version :)
