### ISSUE TITLE
Screen for contigs to process based on coverage in the dataset

### ISSUE THREAD

**Issue by tdelmont** [merenlab/anvio#215]
Hi, if I am not wrong, we can only discriminate contigs to process (profiling and merging steps) based on length.
I think it is relevant for some large assemblies to screen for length and coverage.
Could this be possible, maybe at the merging step (coverage value based on the accumulation of coverages in all samples would be best),

Tom

**Comment by meren** [comment]
We probably will get back to this when we need the necessity at some point :(
