### ISSUE TITLE
[BUG] Search with operators in the interactive interface

### ISSUE THREAD

**Issue by FlorianTrigodet** [merenlab/anvio#2153]
## Short description of the problem

In the interactive interface, we can search for items matching an operator formula. And it does not work with large numbers somewhat.

## anvi'o version

anvi'o v8

## Detailed description of the issue

With this table:
[toto.txt](https://github.com/merenlab/anvio/files/13071267/toto.txt)

```
anvi-interactive --manual -d toto.txt -p PROFILE.db
```
The search works when I search for values > 70,000:
<img width="1224" alt="Screenshot 2023-10-23 at 15 45 22" src="https://github.com/merenlab/anvio/assets/10922896/37900cb0-fdde-42c7-82be-c4210e2ae3e3">

But it fails when I search for values > 2,000,000, it reports too many things including values not matching my condition?:
<img width="1224" alt="Screenshot 2023-10-23 at 15 45 36" src="https://github.com/merenlab/anvio/assets/10922896/dc93d39a-a6ca-4f1a-ba69-fee45fd1b845">

No idea what is happing here 🤷

**Comment by meren** [comment]
lol. weird indeed.

@metehaansever, can you please take a look at this?

**Comment by Ge0rges** [comment]
@FlorianTrigodet @metehaansever I was looking into this but couldn't reproduce it, has it been fixed and/or can you reproduce it?

**Comment by Ge0rges** [comment]
I will say that generally though something like this would be cleaner/safer than eval():

```
function evaluateCondition(cellValue, searchValue, operator, operatorText) {
    switch (operator) {
        case '0': // "=="
            return cellValue.toString() === searchValue;
        case '1': // "!="
            return cellValue.toString() !== searchValue;
        case '2': // ">"
            return parseFloat(cellValue) > parseFloat(searchValue);
        case '3': // "<"
            return parseFloat(cellValue) < parseFloat(searchValue);
        case '4': // ">="
            return parseFloat(cellValue) >= parseFloat(searchValue);
        case '5': // "<="
            return parseFloat(cellValue) <= parseFloat(searchValue);
        case '6': // "contains"
            return cellValue.toString().toLowerCase().includes(searchValue.toLowerCase());
        default:
            return; // or throw an error
    }
}
```

**Comment by metehaansever** [comment]
I realized that using the `Eval` function posed significant problems, so I replaced it with `Function()`. However, this didn't resolve the issue. I believe we should reconsider the entire structure from the ground up.
