### ISSUE TITLE
Performing `anvi-self-test` but the interactive operator did not load in Chrome

### ISSUE THREAD

**Issue by LRH1995** [merenlab/anvio#2163]
## Short description of the problem
I performed the `anvi-self-test` but the interactive operator did not load in Chrome.

## anvi'o version

Anvi'o .......................................: marie (v8)

```
anvi-self-test --version
```
Anvi'o .......................................: marie (v8)
Python .......................................: 3.10.13

## System info

Ubuntu 22.04.2 LTS (the subsystem of Windows 11)
I installed anvio-8 using conda and mamba.

## Detailed description of the issue
when I performed the `anvi-self-test`, the interactive operator did not load in the Chrome browser. I copied the IP " http://0.0.0.0:8080" to the browser but did not open it. I searched the historical solution [https://github.com/merenlab/anvio/issues/582](url), but it still did not work for me. Then I pressed “ctrl+c”, and an error happened as follows. I hope to make the interactive nomally. How can I deal with it?
`Config Error: According to the exit code ('-2'), anvi'o suspects that something may have gone
              wrong while running your tests :/ We hope that the reason is clear to you from
              the lines above. But if you don't see anything obvious, especially if the
              test ended up running until the end with reasonable looking final results, you
              shouldn't worry too much about this error. Life is short and we all can worry
              just a bit less.`

**Comment by metehaansever** [comment]
Hello @LRH1995, 

This is expected behavior. If you follow Windows installation, you will see command below:
`anvi-interactive -c CONTIGS.db -p MERGED/PROFILE.db -I localhost`
You can run with -I localhost parameter.
