### ISSUE TITLE
anvi-setup-scg-taxonomy and anvi-setup-ncbi-cogs error

### ISSUE THREAD

**Issue by magueos** [merenlab/anvio#2172]
## Short description of the problem

I am trying to run the command line "anvi-setup-scg-taxonomy" and "anvi-setup-ncbi-cogs"  is sending me the same error everytime

## anvi'o version

Anvi'o version is 7

## System info

It was installed in the institute cluster by the admin and by using the container singularity

## Detailed description of the issue

I am in an anvio container (singularity v 3.7.0) and I am trying to setup the databases, I tried by writting only the commands and also by seting up the path for each database: 
anvi-setup-scg-taxonomy
anvi-setup-ncbi-cogs

I am having the following errors everytime: 
for anvi-setup-scg-taxonomy: 
                                   Config Error: Something went wrong and DIAMOND did not create the database file it was supposed to for 
                                    Ribosomal_S2 :(

for anvi-setup-ncbi-cogs:

COG version ..................................: COG20
COG data source ..............................: The anvi'o default.
COG base directory ...........................: /opt/conda/envs/anvioenv/lib/python3.6/site-packages/anvio/data/misc/COG

Config Error: So the COG data directory is not there, and anvi'o wants to create one. But it
              didn't go that well. It could be due to permissions (which may require you to
              run this with sudo or may need to ask your sys admin to do it for you since this
              is a one time operation), or it could be due to something totally irrelevant.
              Here is the error message: [Errno 30] Read-only file system:
              '/opt/conda/envs/anvioenv/lib/python3.6/site-packages/anvio/data/misc/COG'.

## Files / commands to reproduce the issue

A diamond-log-file.txt appeared in my directory: 

# DATE: 10 Nov 23 13:34:04
# CMD LINE: diamond makedb --in /tmp/tmp_k1kxyd0/Ribosomal_S2 -d /opt/conda/envs/anvioenv/lib/python3.6/site-packages/anvio/data/misc/SCG_TAXONOMY/GTDB/SCG_SEARCH_DATABASES/Ribosomal_S2.dmnd -p 1
diamond v2.0.6.144 (C) Max Planck Society for the Advancement of Science
Documentation, support and updates available at http://www.diamondsearch.org

#CPU threads: 1
Scoring parameters: (Matrix=BLOSUM62 Lambda=0.267 K=0.041 Penalties=11/1)
Database input file: /tmp/tmp_k1kxyd0/Ribosomal_S2
Opening the database file... Read-only file system
 [0s]
Error: Error opening file /opt/conda/envs/anvioenv/lib/python3.6/site-packages/anvio/data/misc/SCG_TAXONOMY/GTDB/SCG_SEARCH_DATABASES/Ribosomal_S2.dmnd
[10 Nov 23 13:34:04] diamond makedb cmd ...........................: diamond makedb --in /tmp/tmp_k1kxyd0/Ribosomal_S2 -d
                                                /opt/conda/envs/anvioenv/lib/python3.6/site-packages/anvio/data/misc/SCG_TAXONOMY/GTDB/SCG_SEARCH_DATABASES/Ribosomal_S2.dmnd
                                                -p 1
[10 Nov 23 13:34:04] Diamond search db ............................: /opt/conda/envs/anvioenv/lib/python3.6/site-packages/anvio/data/misc/SCG_TAXONOMY/GTDB/SCG_SEARCH_DATABASES/Ribosomal_S2.dmnd.dmnd

**Comment by ivagljiva** [comment]
Hi @magueos , please update to anvi'o version 8 by following [these instructions](https://anvio.org/install/) and then try this command again. If the error persists, please let us know, and if that fixes the problem, then please close this issue. Thank you!

**Comment by magueos** [comment]
it worked, thank you very much !!
