### ISSUE TITLE
Remove jquery-ui dependency

### ISSUE THREAD

**Issue by ozcan** [merenlab/anvio#219]
Jquery-UI is a very big library and we are using only one function from it. Removing this dependency will improve cloning speed.

References to JqueryUI in codebase

```
anvio/data/interactive/js/main.js

// make layers and samples table sortable
$("#tbody_layers").sortable({helper: fixHelperModified, handle: '.drag-icon', items: "> tr:not(:first)"}).disableSelection(); 
$("#tbody_samples").sortable({helper: fixHelperModified, handle: '.drag-icon', items: "> tr"}).disableSelection(); 
```

**Comment by meren** [comment]
Thanks for looking into this, Ozcan. I think removing jquery-ui will save a couple of hundreds megs of download, too.
