### ISSUE TITLE
anvi-self-test script

### ISSUE THREAD

**Issue by ozcan** [merenlab/anvio#220]
I think we need script like this, because some installation methods do not include mini_test. This script can download source code from Github/PyPI since it knows the version number, and extract it to /tmp and run the mini_test. In the future releases we don't have to worry about including appropriate test folder.

**Comment by meren** [comment]
I've been thinking about how this could be done. I am not sure what would be the most elegant solution to this. I think making people download the entire codebase is not a very good idea :/

**Comment by meren** [comment]
this was fixed at some point.
