### ISSUE TITLE
anvio-8:mamba installation doesn’t work in the anaconda environment

### ISSUE THREAD

**Issue by haihao999** [merenlab/anvio#2203]
Hi,
I don’t know why there is no problem in the miniconda environment, but such an error occurs in the anaconda environment

mamba install -y  python=3.10 \
>         sqlite prodigal idba mcl muscle=3.8.1551 famsa hmmer diamond \
>         blast megahit spades bowtie2 bwa graphviz "samtools>=1.9" \
>         trimal iqtree trnascan-se fasttree vmatch r-base r-tidyverse \
>         r-optparse r-stringi r-magrittr bioconductor-qvalue meme ghostscript

Looking for: ['python=3.10', 'sqlite', 'prodigal', 'idba', 'mcl', 'muscle=3.8.1551', 'famsa', 'hmmer', 'diamond', 'blast', 'megahit', 'spades', 'bowtie2', 'bwa', 'graphviz', "samtools[version='>=1.9']", 'trimal', 'iqtree', 'trnascan-se', 'fasttree', 'vmatch', 'r-base', 'r-tidyverse', 'r-optparse', 'r-stringi', 'r-magrittr', 'bioconductor-qvalue', 'meme', 'ghostscript']

bioconda/linux-64 (check zst)                       Checked  0.5s
bioconda/noarch (check zst)                         Checked  0.2s
pkgs/main/linux-64 (check zst)                      Checked  0.6s
pkgs/main/noarch (check zst)                        Checked  0.1s
pkgs/free/linux-64 (check zst)                      Checked  0.3s
pkgs/free/noarch (check zst)                        Checked  0.3s
pkgs/r/linux-64 (check zst)                         Checked  0.1s
pkgs/r/noarch (check zst)                           Checked  0.1s
au-eoed/linux-64 (check zst)                        Checked  0.4s
au-eoed/noarch (check zst)                          Checked  0.4s
r/linux-64 (check zst)                              Checked  0.6s
r/noarch (check zst)                                Checked  0.4s
ursky/linux-64 (check zst)                          Checked  0.4s
ursky/noarch (check zst)                            Checked  0.4s
/linux-64/repodata.json.zst": Malformed input to a URL function

**Comment by meren** [comment]
Hi @haihao999,

We haven't tested anvi'o installation in Anaconda environment and we don't have the throughput to investigate installation issues that arise during attempts that don't follow online installation instructions word-by-word.

Best wishes,
