### ISSUE TITLE
[BUG] anvi-pan-genome DIAMOND expected output files are missing

### ISSUE THREAD

**Issue by carloshenriquezc** [merenlab/anvio#2227]
## Short description of the problem

I setup my databases after installing DIAMOND via conda. However I still receive this message using the COG or KEGG databases.
The log file: 
# DATE: 20 Feb 24 18:29:18
# CMD LINE: diamond view -a /media/carlos/20D87261D872355E/Work/CEAZA/FIGEMA/ROXANA/Vibrio/fasta_gnomes/SELECTED-GENOMES/diamond-search-results.daa -o /media/carlos/20D87261D872355E/Work/CEAZA/FIGEMA/ROXANA/Vibrio/fasta_gnomes/SELECTED-GENOMES/diamond-search-results.txt -p 16 --outfmt 6
diamond v0.9.21.122 | by Benjamin Buchfink <buchfink@gmail.com>
Licensed under the GNU AGPL <https://www.gnu.org/licenses/agpl.txt>
Check http://github.com/bbuchfink/diamond for updates.

#CPU threads: 16
Loading subject IDs... No such file or directory
 [9.8e-05s]
Error: Error opening file /media/carlos/20D87261D872355E/Work/CEAZA/FIGEMA/ROXANA/Vibrio/fasta_gnomes/SELECTED-GENOMES/diamond-search-results.daa

## anvi'o version

Anvi'o .......................................: marie (v8)
Python .......................................: 3.10.4
```

## System info
Linux Mint

## Detailed description of the issue

 Something probably went wrong with Diamond's 'view' since one of the expected output files are missing. Please check the log file here: '/media/SELECTED-GENOMES/log.txt'. IT IS VERY LIKELY to get these kinds of errors if the version of DIAMOND installed on your system differs from the one you had used to first setup your databases. Some errors may disappear if you were to setup your search databases from scratch.

## Files / commands to reproduce the issue

anvi-pan-genome -g VIBRIO-GENOMES.db --project-name SELECTED-GENOMES --output-dir SELECTED-GENOMES --mcl-inflation 8 --exclude-partial-gene-calls --enforce-hierarchical-clustering --num-threads 16 --additional-params-for-seq-search “--sensitive”

**Comment by pcampiteli** [comment]
Hey, I'm current trying to solve  this exact same error in my pangenome analysis. This topic is closed without any explanation, did you solve this @carloshenriquezc ? Can you explain how?
