### ISSUE TITLE
[Bug] external-genomes.txt missing genomes

### ISSUE THREAD

**Issue by Alesita0381** [merenlab/anvio#2239]
Hi!

Im working with Anvio and im trying to run this command to generate an input file containing paths to all of the databases (17 files).

anvi-script-gen-genomes-file --input-dir ./ \
                 -o external-genomes.txt

Then, when i try to check it with     cat external-genomes.txt  the content only has one path. What am i doing wrong?

**Comment by ivagljiva** [comment]
Hi @Alesita0381 , what do you see when you run `ls *.db` in the same directory? 

The only possibilities I can imagine is that your databases in a different folder. If they are in subdirectories of your working directory, you will need to use the `--include-subdirs` flag for anvi'o to find them.

**Comment by Alesita0381** [comment]
Hello, when I run the command everything indicates to be fine, but when I
check the content it only appends the address of a single file instead of
the 17 that are located in the same place, only file number 17 appears, but
in the instructions it says that they have to come out the one of each file
in the form of a list,  I don't know if this changes because of my anvio's
version which is 8 and the one in the instructions is 7

**Comment by meren** [comment]
Can you run this command two of the anvi'o databases you have in that directory and send it back please:

```
anvi-db-info 01.db

anvi-db-info 02.db
```

**Comment by Alesita0381** [comment]
This is the result:

DB Info (no touch)
===============================================
Database Path ................................: maxbin_1.db
description ..................................: [Not found, but it's OK]
db_type ......................................: contigs (variant: unknown)
version ......................................: 21


DB Info (no touch also)
===============================================
project_name .................................: Pseudomonas
contigs_db_hash ..............................: hash59407a87
split_length .................................: 20000
kmer_size ....................................: 4
num_contigs ..................................: 246
total_length .................................: 4917381
num_splits ...................................: 321
gene_level_taxonomy_source ...................: None
gene_function_sources ........................: None
genes_are_called .............................: 1
external_gene_calls ..........................: 0
external_gene_amino_acid_seqs ................: 0
skip_predict_frame ...........................: 0
splits_consider_gene_calls ...................: 1
trna_taxonomy_was_run ........................: 0
trna_taxonomy_database_version ...............: None
creation_date ................................: 1710360177.51146
scg_taxonomy_was_run .........................: 1
scg_taxonomy_database_version ................: v214.1

* Please remember that it is never a good idea to change these values. But in some
  cases it may be absolutely necessary to update something here, and a
  programmer may ask you to run this program and do it. But even then, you
  should be extremely careful.


AVAILABLE GENE CALLERS
===============================================
* 'prodigal' (4,640 gene calls)


AVAILABLE FUNCTIONAL ANNOTATION SOURCES
===============================================
* No functional annotations found in this contigs database :/


AVAILABLE HMM SOURCES
===============================================
* 'Archaea_76' (76 models with 60 hits)
* 'Bacteria_71' (71 models with 114 hits)
* 'Protista_83' (83 models with 4 hits)
* 'Ribosomal_RNA_12S' (1 model with 0 hits)
* 'Ribosomal_RNA_16S' (3 models with 0 hits)
* 'Ribosomal_RNA_18S' (1 model with 0 hits)
* 'Ribosomal_RNA_23S' (2 models with 0 hits)
* 'Ribosomal_RNA_28S' (1 model with 0 hits)
* 'Ribosomal_RNA_5S' (5 models with 0 hits)

(anvio-8) alejandra-aguilar@:MaxbinDB$ 
(anvio-8) alejandra-aguilar@:MaxbinDB$ anvi-db-info maxbin2.db 

DB Info (no touch)
===============================================
Database Path ................................: maxbin2.db
description ..................................: [Not found, but it's OK]
db_type ......................................: contigs (variant: unknown)
version ......................................: 21


DB Info (no touch also)
===============================================
project_name .................................: Pseudomonas
contigs_db_hash ..............................: hash151f66c3
split_length .................................: 20000
kmer_size ....................................: 4
num_contigs ..................................: 184
total_length .................................: 757460
num_splits ...................................: 187
gene_level_taxonomy_source ...................: None
gene_function_sources ........................: None
genes_are_called .............................: 1
external_gene_calls ..........................: 0
external_gene_amino_acid_seqs ................: 0
skip_predict_frame ...........................: 0
splits_consider_gene_calls ...................: 1
trna_taxonomy_was_run ........................: 0
trna_taxonomy_database_version ...............: None
creation_date ................................: 1710360932.87123
scg_taxonomy_was_run .........................: 1
scg_taxonomy_database_version ................: v214.1

* Please remember that it is never a good idea to change these values. But in some
  cases it may be absolutely necessary to update something here, and a
  programmer may ask you to run this program and do it. But even then, you
  should be extremely careful.


AVAILABLE GENE CALLERS
===============================================
* 'prodigal' (926 gene calls)


AVAILABLE FUNCTIONAL ANNOTATION SOURCES
===============================================
* No functional annotations found in this contigs database :/


AVAILABLE HMM SOURCES
===============================================
* 'Archaea_76' (76 models with 13 hits)
* 'Bacteria_71' (71 models with 29 hits)
* 'Protista_83' (83 models with 0 hits)
* 'Ribosomal_RNA_12S' (1 model with 0 hits)
* 'Ribosomal_RNA_16S' (3 models with 0 hits)
* 'Ribosomal_RNA_18S' (1 model with 0 hits)
* 'Ribosomal_RNA_23S' (2 models with 0 hits)
* 'Ribosomal_RNA_28S' (1 model with 0 hits)
* 'Ribosomal_RNA_5S' (5 models with 0 hits)

**Comment by meren** [comment]
This is why it is happening, @Alesita0381:

```
project_name .................................: Pseudomonas
(...)
project_name .................................: Pseudomonas
```

The project name for every single contigs-db is the same (when they should be unique).

**Comment by meren** [comment]
Once solution for this could be to add a check to `anvi-script-gen-genomes-file`. I.e.,

``` python
if len(set(genome_names)) != len(genome_names):
    raise ConfigError("Oi. Not every contigs-db this program considers seems to have "
                      "a unique name. Such a redundancy will make sad.")
```

**Comment by Alesita0381** [comment]
Thanks, I assigned a unique project name to each file and the path of all the files now appears in external-genomes.txt !!! Thank you :)

**Comment by meren** [comment]
I'm glad it is resolved, @Alesita0381, and thanks for catching this. We will do something to ensure there is an informative error report generated by the tool in the future.
