### ISSUE TITLE
[BUG] Parent layer bug

### ISSUE THREAD

**Issue by FlorianTrigodet** [merenlab/anvio#2245]
## Short description of the problem

In the interactive interface, there is a "parent" layer that indicate when splits are coming from the same contig. It is not working properly in the interface at the moment.

## anvi'o version

Dev version

## Detailed description of the issue

Using the infant gut dataset:

<img width="1718" alt="Screenshot 2024-03-25 at 11 51 36" src="https://github.com/merenlab/anvio/assets/10922896/b722c42c-e8ce-4cf8-8224-8f6511973d06">

All parent's gray boxes don't align at the right position. It looks like all the withe space (when no parent) are place first (anti-clockwise) and then all the parent gray boxes.

Here is another example on a different dataset:

<img width="851" alt="Screenshot 2024-03-25 at 11 57 04" src="https://github.com/merenlab/anvio/assets/10922896/20508df9-3eab-408c-8376-f6fc63dfdf4c">

## Files / commands to reproduce the issue

The first screenshot is coming from the infant gut tutorial with `anvi-interactive`.

**Comment by metehaansever** [comment]
I solved it! @FlorianTrigodet I'll merge with `ui-bug-fix` branch. Thanks for catching Florian!
