### ISSUE TITLE
[BUG] anvi-interactive is not working in my computer 

### ISSUE THREAD

**Issue by soojunglee98** [merenlab/anvio#2251]
## Short description of the problem

The anvi-interactive is not working in my computer. 

## anvi'o version

```
anvi-self-test --version
```

Anvi'o .......................................: marie (v8)
Python .......................................: 3.10.14

Profile database .............................: 38
Contigs database .............................: 21
Pan database .................................: 16
Genome data storage ..........................: 7
Auxiliary data storage .......................: 2
Structure database ...........................: 2
Metabolic modules database ...................: 4
tRNA-seq database ............................: 2

## Detailed description of the issue

ANVI'O FILLED IN THE 2 ARGS BELOW AUTOMATICALLY
===============================================
profile_db ...................................: ./Downloads/PROFILE.db
contigs_db ...................................: ./Downloads/contigs.db

Contigs DB ...................................: Initialized: ./Downloads/contigs.db (v. 21)                     
Interactive mode .............................: full                                                            
Profile Super ................................: Initialized with all 1052137 splits: ./Downloads/PROFILE.db (v. 
                                                38)
                                                                                                                
WARNING
===============================================
Auxiliary data is not available; which means you will not be able to perform
certain operations (i.e., the inspect menu in the interactive interface will not
work, etc).

WARNING
===============================================
This merged profile database does not seem to have any hierarchical clustering
of splits :/ It may be the case becasue it may have been generated by anvi-merge
with the `--skip-hierarchical-clustering` flag, or hierarchical clustering step
may have been skipped by anvi-merge because you had too many splits to get the
clustering in a reasonable amount of time. Basically you will not see a
clustering dendrogram in the center of your display. Please read the help menu
for anvi-merge, and/or refer to the tutorial:
http://merenlab.org/2015/05/01/anvio-tutorial/#clustering-during-merging

Config Error: Apologies :( The code managed to came all the way down here without any item  
              orders set for your project, which makes it impossible for anvi'o intearctive 
              interface to display anything :/ Please check warning messages you may have on
              your screen.

**Comment by metehaansever** [comment]
Hello @soojunglee98 What is your system information? Do you run Anvio under WSL?

**Comment by meren** [comment]
@soojunglee98, there is nothing wrong here: there are 1,052,137 splits in your profile database, and no hierarchical clustering of them to offer an interactive interface. I am not sure what is your end goal, but this is not a technical bug.

If you have usage questions or need for input for best practices please consider sending them to the anvi'o discord :)
