### ISSUE TITLE
Config Error: There is nothing at               '/mnt/d/bioinformatics/phlogytree/M_ZM43__SPLIT/ZM43_CLEAN/CONTIGS.db' :/

### ISSUE THREAD

**Issue by GZL217** [merenlab/anvio#2254]
Dear developer, hello
I had this problem when using it

(base) zan@DESKTOP-F0361EU:/mnt/d/bioinformatics/phlogytree$ anvi-estimate-genome-completeness -e external-genomes-final.txt
[16 Apr 24 09:32:51 Setting up genome hash dicts] working on M_ZM43 (external)   ETA: None

Config Error: There is nothing at
              '/mnt/d/bioinformatics/phlogytree/M_ZM43__SPLIT/ZM43_CLEAN/CONTIGS.db' :/

**Comment by ivagljiva** [comment]
Duplicate issue, closing.
