### ISSUE TITLE
Pangenome analysis when dispaly result, can't see the Phylogenetic tree 

### ISSUE THREAD

**Issue by GZL217** [merenlab/anvio#2275]
there is the code that uesd

ls *fasta

ls *fasta | awk 'BEGIN{FS="_"}{print $1}' > genomes.txt
cat genomes.txt

for g in `cat genomes.txt`
do
    echo
    echo "Working on $g ..."
    echo
    anvi-script-reformat-fasta ${g}_scaffolds.fasta \
                               --min-len 2500 \
                               --simplify-names \
                               -o ${g}_scaffolds_2.5K.fasta
done

for g in `cat genomes.txt`
do
    echo
    echo "Working on $g ..."
    echo
    anvi-gen-contigs-database -f ${g}_scaffolds_2.5K.fasta \
                              -o M_${g}.db \
                              --num-threads 4 \
                              -n M_${g}      
done

for g in *.db
do
    anvi-run-hmms -c $g --num-threads 8
    anvi-run-ncbi-cogs -c $g --num-threads 8
    anvi-scan-trnas -c $g --num-threads 8
    anvi-run-scg-taxonomy -c $g --num-threads 8
done

anvi-display-contigs-stats *db -I localhost

anvi-script-gen-genomes-file --input-dir . \
                             -o external-genomes.txt

anvi-estimate-genome-completeness -e external-genomes.txt

anvi-profile -c M_marinusZ4.db \
             --sample-name M_marinusZ4 \ 
             --output-dir M_marinusZ4 \
             --blank

anvi-interactive -c M_marinusZ4.db \
                 -p M_marinusZ4/PROFILE.db -I localhost

anvi-split -p M_marinusZ4/PROFILE.db \
           -c M_marinusZ4.db \
           -C default \
           -o M_marinusZ4_SPLIT

sed 's/M_marinusZ4.db/M_marinusZ4_SPLIT\/M_marinusZ4_CLEAN\/CONTIGS.db/g' external-genomes.txt > external-genomes-final.txt

anvi-estimate-genome-completeness -e external-genomes.txt
anvi-estimate-genome-completeness -e external-genomes-final.txt 

anvi-gen-genomes-storage -e external-genomes-final.txt \
-o M_-GENOMES.db

anvi-pan-genome -g M_-GENOMES.db \  
                --project-name M_ \ 
                --num-threads 16

anvi-display-pan -p M_/M_-PAN.db \ 
                 -g M_-GENOMES.db -I localhost

![Uploading QQ截图20240531220617.png…]()

**Comment by meren** [comment]
Is this prematurely sent? :) I don't see a question here. Neither I see the screenshot.

**Comment by GZL217** [comment]
![Uploading QQ截图20240531220617.png…]()

**Comment by GZL217** [comment]
how about now? I already uplode the picture

**Comment by GZL217** [comment]
![Uploading QQ截图20240531220617.png…]()

**Comment by meren** [comment]
It didn't work again.

**Comment by metehaansever** [comment]
I can't see either. Can you wait until you see the preview after uploading the image?

**Comment by GZL217** [comment]
![Uploading 1.png…]()

**Comment by GZL217** [comment]
no

**Comment by metehaansever** [comment]
Maybe you can share in our discord channel: https://discord.com/invite/C6He6mSNY4

**Comment by GZL217** [comment]
![Uploading 1.png…]()

**Comment by GZL217** [comment]
thanks I am try

**Comment by GZL217** [comment]
finally！！

**Comment by GZL217** [comment]
![screenshot-1717165714718](https://github.com/merenlab/anvio/assets/167152039/2866928a-45b0-4b60-bb17-aeb253e83a65)

**Comment by meren** [comment]
Ah. If there are more than 25,000 gene clusters, a dendrogram is not computed automatically (which is not a phylogenetic tree, but a clustering dendrogram). 

That said, if you look at the help menu of the `anvi-pan-genome`, you will see that there is a parameter to 'enforce' it. If you re-run it with that flag, it should work.

**Comment by meren** [comment]
I understand that. Please read my message again, @GZL217.
