### ISSUE TITLE
Config Error: PyANI returned with non-zero exit code, there may be some errors. please check the log file for details.  

### ISSUE THREAD

**Issue by Naim4382** [merenlab/anvio#2277]
I am facing this error. Please give me a solution. It shows:

✖ anvi-compute-genome-similarity encountered an error after 0:00:04.793558

Config Error: PyANI returned with non-zero exit code, there may be some errors. please check
              the log file for details.                                                     

Config Error: According to the exit code ('255'), anvi'o suspects that something may have gone
              wrong while running your tests :/ We hope that the reason is clear to you from  
              the lines above. But if you don't see anything obvious, and especially if the   
              test ended up running until the end with reasonable looking final results, you  
              shouldn't worry too much about this error. Life is short and we all can worry   
              just a bit less.

**Comment by ivagljiva** [comment]
Downgrade your matplotlib package to fix this issue: `pip install matplotlib==3.5.1`
