### ISSUE TITLE
Anvio installation

### ISSUE THREAD

**Issue by UniAlberta** [merenlab/anvio#2285]
## anvi'o 8

Keep the header of this section, but replace this text with the output of this command in your terminal:

```
anvi-self-test --version
```

## System info
Windows 10, using Powershell 
https://anvio.org/install/linux/stable/

## Detailed description of the issue

I`m getting an error for anvio installation, in step 4, I run pip install anvio-8.tar.gz and it says Failed to build anvio ERROR: Could not build wheels for anvio, which is required to install pyproject.toml-based projects. The troubleshooting page says to run sudo apt update which I can`t on GPSCC server. Anyoine had the same issue?

**Comment by meren** [comment]
Please use WSL to install anvi'o rather than PowerShell as instructed in the installation manual.
