### ISSUE TITLE
[BUG] Can't visualise the pangenome with average nucleotide identity

### ISSUE THREAD

**Issue by CarolineSchouNielsen** [merenlab/anvio#2293]
## Short description of the problem

Can't visualise the pangenome with average nucleotide identity, even when ANI is imported. 

## anvi'o version

Keep the header of this section, but replace this text with the output of this command in your terminal:

```
anvi-self-test --version
```
Anvi'o .......................................: marie (v8)
Python .......................................: 3.10.14

Profile database .............................: 38
Contigs database .............................: 21
Pan database .................................: 16
Genome data storage ..........................: 7
Auxiliary data storage .......................: 2
Structure database ...........................: 2
Metabolic modules database ...................: 4
tRNA-seq database ............................: 2

## System info

I installed Anvi'o with the following commands (probably a lot more information than needed, but I am unsure of what to write as I did not make these installation instructions myself):

<img width="656" alt="Screenshot 2024-07-03 at 16 50 30" src="https://github.com/merenlab/anvio/assets/167312789/9cf34cc5-6f88-40a2-82ee-c14f389fd5af">

## Detailed description of the issue

Keep the header of this section, but replace this text with a clear description of what you expected to happen and what happened instead. Try to include screenshots, complete error text from your terminal, and exact commands you've run to get those errors. If you don't think you need additional description of the problem and your short description is sufficient, feel free to remove this section along with its header.

I am doing the [A primer on Anvi'o tutorial](https://merenlab.org/tutorials/infant-gut/#adding-average-nucleotide-identity), but I can't seem to get the average nucleotide identity to appear in the interface. 

I have imported the ANI percent identity file using the following command (I added the --just-do-it flag because I had already tried to import the ANI file, and I wanted to try again): 

`anvi-import-misc-data additional-files/pangenomics/ANI_percentage_identity.txt \
                      -p PAN/Enterococcus-PAN.db \
                      --target-data-table layers \
                      --target-data-group ANI_percentage_identity --just-do-it`

Which gives this output: 
![Screenshot 2024-07-03 at 16 56 26](https://github.com/merenlab/anvio/assets/167312789/f13f7631-f774-4d85-939a-32abb4116425)

However, when I try to visualise the pangenome again with the ANI results, it does not appear in the pangenome. I use this command: 

`anvi-display-pan -g Enterococcus-GENOMES.db \
                 -p PAN/Enterococcus-PAN.db \
                 --title "Enterococccus Pan"`

I get this output in the command line: 

![Screenshot 2024-07-03 at 16 58 40](https://github.com/merenlab/anvio/assets/167312789/b21428c0-74d1-45b6-aee6-a70e1ed46e5d)

But this output in the Anvi'o interface (which is the same as was generated without the ANI percent identity file): 

<img width="1165" alt="Screenshot 2024-07-03 at 16 59 52" src="https://github.com/merenlab/anvio/assets/167312789/8f8d6381-e3ab-430c-8d09-139828a015e5">

Can you help me figure out what the issue is? 

Many thanks!

**Comment by meren** [comment]
Hi @CarolineSchouNielsen, you need to go to the `layers` tab shown in the interface, and turn on the ANI layers you will see there.
