### ISSUE TITLE
[BUG] ERROR in running anvi-script-gen_stats_for_single_copy_genes.R

### ISSUE THREAD

**Issue by AlenaYoung** [merenlab/anvio#2316]
## Short description of the problem

ERROR in running anvi-script-gen_stats_for_single_copy_genes.R

## anvi'o version

Anvi'o .......................................: marie (v8)
Python .......................................: 3.10.14

Profile database .............................: 38
Contigs database .............................: 21
Pan database .................................: 16
Genome data storage ..........................: 7
Auxiliary data storage .......................: 2
Structure database ...........................: 2
Metabolic modules database ...................: 4
tRNA-seq database ............................: 2

## System info

The operating system is Linux. Anvi'o was installed in a conda environment.

## Detailed description of the issue

When running `anvi-script-gen_stats_for_single_copy_genes.R` I get the following error:

```Bash
Warning message:
package ‘gtools’ was built under R version 4.3.3 
Warning message:
package ‘gridExtra’ was built under R version 4.3.3 
Warning message:
package ‘ggplot2’ was built under R version 4.3.3 
Warning message:
package ‘optparse’ was built under R version 4.3.3 
null device 
          1
```
The specific step is:
`anvi-run-hmms -c ../contigs_FH62.db -T 120`
`anvi-script-gen_stats_for_single_copy_genes.py contigs_FH62.db`
`conda install -c conda-forge r-gtools`
`conda install -c conda-forge r-gridExtra`
`anvi-script-gen_stats_for_single_copy_genes.R contigs_FH62.db.hits contigs_FH62.db.genes`

**Comment by meren** [comment]
Hey @AlenaYoung,

The information this script used to provide is now provided by the program `anvi-display-contigs-stats`.

I will remove this unused script from the codebase :)
