### ISSUE TITLE
[FEATURE REQUEST] Using external gene clusters for anvi-pan-genome

### ISSUE THREAD

**Issue by FlorianTrigodet** [merenlab/anvio#2317]
## The need

Let the user use their own gene clusters for anvi-pan-genome.

## The solution

A flag for anvi-pan-genome to tell the program to not run diamond/MCL, but use a user-defined list of gene cluster.
The final pangenome would have the exact same features with AA alignment, functions, homogeneity layers, etc. 

## Beneficiaries

I would really like that feature, but I'm sure other people would too :D

**Comment by meren** [comment]
FINE.
