### ISSUE TITLE
[FEATURE REQUEST] Case-sensitive search in `anvi-export-locus`

### ISSUE THREAD

**Issue by philipwoods** [merenlab/anvio#2319]
## The need

I find the `anvi-export-locus` command to be extremely useful, especially for generating synteny figures. However, I would like to have the option to force `anvi-export-locus` to search functions in a case-sensitive manner or to specify which annotation source(s) to search in. For example, I have annotated several genomes with a custom HMM for a gene called **pylT**. These genomes also have a gene with "...pro**pylt**ransferase..." in their KEGG BRITE annotation. Unfortunately, when I use the search term "pylT", I also get loci containing the unrelated propyltranferase gene despite the different capitalization.

## The solution

I understand the utility of the current search using a fuzzier search and am not suggesting you replace the current search with a strict one. However, it might be useful to add a `--case-sensitive` option to enable case sensitivity when searching. I'm not sure how one would implement my alternative suggestion that the user could specify which annotation source(s) to search against since there is already an option ``--annotation-sources` which does something else. For this reason I lean towards the case-sensitive search solution, but you're free to make your own decisions :).

## Beneficiaries

As people annotate their genomes with many different annotation databases, the chances that there will be overlaps between the text fields in these annotation sources increases. This is especially true of annotation databases like KOfams or eggNOG which add many annotation sources to contigs databases when run. The beneficiaries of this feature will be people who like having many diverse annotation sources in their contigs databases but who would like to search functions while limiting the chances of unintentional overlap between the sources in their annotations.

**Comment by meren** [comment]
I can see that there are some issues there and we need some improvements in the search function.

I'll implement this soon and will keep you posted, @philipwoods. Thank you for the feature request.

**Comment by meren** [comment]
@mschecht I just realized you self assigned this! Please don't worry about it. I know you have more important things to do nowadays. I'll take care of it :)

**Comment by mschecht** [comment]
lol I was just drafting a reponse - thanks for looking into it @meren! 

`anvi-self-test --suite export-locus` should give you what you need to look into this feature request.

Two notes I want to add: 

1. I think `--case-sensitive` is a great idea
2. We could add the option for users to search by accession numbers which should be very specific. 

@philipwoods I'm glad the tool is helping you with your research!

**Comment by meren** [comment]
Hey @philipwoods,

The changes you requested are now in `anvio-dev` (via #2321).

This update also solves this issue:

> As people annotate their genomes with many different annotation databases, the chances that there will be overlaps between the text fields in these annotation sources increases.

Now `--annotation-sources` parameter works expectedly, and limits the search to specific sources of annotation.

I hope you can test these changes and let us know whether they work for you or not, and re-open the issue if necessary :)

**Comment by philipwoods** [comment]
This worked exactly as I hoped, thank you so much!

**Comment by meren** [comment]
🎉
