### ISSUE TITLE
[BUG] The CONTIGS.db file is 0kb and slurm job is still running

### ISSUE THREAD

**Issue by itpcas-zcb** [merenlab/anvio#2324]
## Short description of the problem
I use anvi-gen-contigs-database -f "${contigs_fa}" -o "${contigsdb}" -n "VAMB_binning_${dup}" -T "${anvio_threads}" >> The "${log}" 2>&1 code runs, but after 2 days in slurm, CONTIGS.db is still 0 bytes and the cpu usage is 0
Keep the header of this section, but replace the content with a *single-sentence description* of the problem.

## anvi'o version

Keep the header of this section, but replace this text with the output of this command in your terminal:

```
anvi-self-test --version
Anvi'o .......................................: marie (v8)
Python .......................................: 3.10.14

Profile database .............................: 38
Contigs database .............................: 21
Pan database .................................: 16
Genome data storage ..........................: 7
Auxiliary data storage .......................: 2
Structure database ...........................: 2
Metabolic modules database ...................: 4
tRNA-seq database ............................: 2
```

## System info

linux follow https://anvio.org/install/linux/stable/

## Detailed description of the issue

Now my log file content only the following content: Input FASTA file... : /home/usr/zhangcb/Daihu/zcb/cleaned.fq/sdust/filtered2/rename_fq_gz/assembly-combine/refined/vamb_concatenate/vamb-anvio /dup/contigs.fa
Name ......................................... : VAMB_binning_dup
Description .................................. : No description is given

My fa file size is 956mb, I tried it with a very small fa file and a similar situation occurred

**Comment by meren** [comment]
If that's all the information you see in your log file, it makes no sense to me, @itpcas-zcb, and I can't see how it could be related to anvi'o :(

I think the issue is likely related to how you construct your slurm job or the slurm configuration somehow. I wonder if it could be related to the value of `${anvio_threads}`.

You can test if things are working outside of slurm using an interactive session or by downloading the files on your computer.

**Comment by meren** [comment]
If you find more, please reopen the issue.
