### ISSUE TITLE
"Curated bin" property in collections

### ISSUE THREAD

**Issue by tdelmont** [merenlab/anvio#233]
Hi,
I realize that when we want to refine all automatically created bins, and when you have a lot of bins, it becomes tricky to track yet to be refined bins. 
Would be awesome to know the refining history of bins in summary, as a small logo "refined" or as a new column, maybe just after bin name, or at the very end. If we could order bins based on refined/not refined it might save a lot of the users' time!

Tom

**Comment by meren** [comment]
This could be done. Good idea (especially for 3:15pm, kudos!).

**Comment by meren** [comment]
this was fixed at some point.
