### ISSUE TITLE
isuue with anvio output files

### ISSUE THREAD

**Issue by UniAlberta** [merenlab/anvio#2338]
Hi there, I`m using anvio 8, bowtie2 version 2.5.2 and samtools 1.18. The workflow runs well but it doesn`t create all output files. I see that I have 00_LOGS, 02_FASTA, 03_CONTIGS. 04_MAPPING folder is created but doesn`t have bam files, .bam and .bam.bai files. Also  05_ANVIO_PROFILE (anvio profile database) is not created. Can you please help me find out where the problem is? I don`t have coassembly anaylysis.

**Comment by meren** [comment]
The files in 00_LOGS directory will include information about the problem, @UniAlberta.

You can go into that directory, type `ls -t`, and start looking at their contents one by one until you see the error that led to the premature ending of the workflow.

**Comment by UniAlberta** [comment]
I looked at 00_LOGS with ls -t and there was no error. I just
have -bowtie.log of my samples.

**Comment by meren** [comment]
Can you please compress your `00_LOGS` directory and send it here?

```
tar -zcf 00_LOGS.tar.gz 00_LOGS/
```

**Comment by meren** [comment]
I'm looking at the first one, and it says the following:

```
cat S00JY_0809-S00JY_0809-bowtie.log
(ERR): Cannot find the large index 04_MAPPING/S00JY_0809/S00JY_0809-contigs.1.bt2l
Exiting now ...
```

Clearly the bowtie-build step didn't run for some reason. Assuming you sent all the log files, it is likely that it never run since there is no log for the bowtie-build step. Without having access to the workflow directory, it is difficult to speculate.

But this is not a bug.

**Comment by UniAlberta** [comment]
I sent the complete 00_LOGS folder. What information do you need to be able to help?

**Comment by UniAlberta** [comment]
Can I share my config file with you?

**Comment by meren** [comment]
You can, but the config file will not help because there is nothing you can do in the config file for snakemake to skip bowtie-build but continue with bowtie :(

**Comment by UniAlberta** [comment]
Here is my config file
[config-metaspades.json](https://github.com/user-attachments/files/16963411/config-metaspades.json)
