### ISSUE TITLE
Adding binning step to workflow

### ISSUE THREAD

**Issue by UniAlberta** [merenlab/anvio#2340]
Hi, I know that if I don`t have co-assembly, the anvio will not do binning as a step in the workflow and I need to do it after I get my contigs. I wanted to ask if there is any way that I can add binning to the workflow?

**Comment by meren** [comment]
@UniAlberta, GitHub Issues is to document and report technical issues that most likely require changes in the codebase, and track the progress of such problems. Questions related how to use anvi'o should go to anvi'o Discord, where a community of anvi'o users help one another with usage related questions.

Best wishes,
