### ISSUE TITLE
[BUG] Insert a short but descriptive title (leave the '[BUG]' part)

### ISSUE THREAD

**Issue by PeymanDerik** [merenlab/anvio#2345]
Hi,

I am getting this error when I run "anvi-setup-ncbi-cogs":

Config Error: Command failed to run. What command, you say? This: 'makeblastdb -in
              /gpfs/fs3c/aafc/aafc_shp/pdv000/Anvio/tmpskp4t2xv -dbtype prot -out 
              /home/pdv000/miniconda3/envs/anvio-8/lib/python3.10/site-           
              packages/anvio/data/misc/COG/COG20/DB_BLAST/COG/COG.fa' 

I would appreciate any help to solve this.

Thanks!

**Comment by meren** [comment]
If you wish to report a bug, please use the template, @PeymanDerik.
