### ISSUE TITLE
[BUG] Error in anvi-setup-ncbi-cogs: makeblastdb

### ISSUE THREAD

**Issue by PeymanDerik** [merenlab/anvio#2346]
## Short description of the problem

I am getting error when I run "anvi-setup-ncbi-cogs"

## anvi'o version

Anvi'o .......................................: marie (v8)
Python .......................................: 3.10.15

Profile database .............................: 38
Contigs database .............................: 21
Pan database .................................: 16
Genome data storage ..........................: 7
Auxiliary data storage .......................: 2
Structure database ...........................: 2
Metabolic modules database ...................: 4
tRNA-seq database ............................: 2

## System info

Installing anvi'o on Linux 64-bit

## Detailed description of the issue

Config Error: Command failed to run. What command, you say? This: 'makeblastdb -in
/gpfs/fs3c/aafc/aafc_shp/pdv000/Anvio/tmpskp4t2xv -dbtype prot -out
/home/pdv000/miniconda3/envs/anvio-8/lib/python3.10/site-
packages/anvio/data/misc/COG/COG20/DB_BLAST/COG/COG.fa'

**Comment by meren** [comment]
I run this program in anvio-dev just this morning, and had no issues. What happens when you manually run the following command on the same terminal, @PeymanDerik?

```
makeblastdb -in
/gpfs/fs3c/aafc/aafc_shp/pdv000/Anvio/tmpskp4t2xv -dbtype prot -out
/home/pdv000/miniconda3/envs/anvio-8/lib/python3.10/site-
packages/anvio/data/misc/COG/COG20/DB_BLAST/COG/COG.fa
```

Perhaps you are running into some memory issues.

Can you also double-check if there are any sequences in the following file:

```
/home/pdv000/miniconda3/envs/anvio-8/lib/python3.10/site-
packages/anvio/data/misc/COG/COG20/DB_BLAST/COG/COG.fa
```

**Comment by PeymanDerik** [comment]
Thank you so much for your response. Here is the output:

(anvio-8) pdv000@inter-c-aafc-ubuntu2004:~/aafc_shp/pdv000/Anvio$ makeblastdb -in
USAGE
  makeblastdb [-h] [-help] [-in input_file] [-input_type type]
    -dbtype molecule_type [-title database_title] [-parse_seqids]
    [-hash_index] [-mask_data mask_data_files] [-mask_id mask_algo_ids]
    [-mask_desc mask_algo_descriptions] [-gi_mask]
    [-gi_mask_name gi_based_mask_names] [-out database_name]
    [-blastdb_version version] [-max_file_sz number_of_bytes]
    [-metadata_output_prefix ] [-logfile File_Name] [-taxid TaxID]
    [-taxid_map TaxIDMapFile] [-oid_masks oid_masks] [-version]

DESCRIPTION
   Application to create BLAST databases, version 2.16.0+

Use '-help' to print detailed descriptions of command line arguments
========================================================================

Error: Argument "-in". Value is missing
Error:  (CArgException::eNoArg) Argument "-in". Value is missing
(anvio-8) pdv000@inter-c-aafc-ubuntu2004:~/aafc_shp/pdv000/Anvio$               /gpfs/fs3c/aafc/aafc_shp/pdv000/Anvio/tmpiah7qnrg -dbtype prot -out 
-bash: /gpfs/fs3c/aafc/aafc_shp/pdv000/Anvio/tmpiah7qnrg: Permission denied
(anvio-8) pdv000@inter-c-aafc-ubuntu2004:~/aafc_shp/pdv000/Anvio$               /home/pdv000/miniconda3/envs/anvio-8/lib/python3.10/site-           
-bash: /home/pdv000/miniconda3/envs/anvio-8/lib/python3.10/site-: No such file or directory
(anvio-8) pdv000@inter-c-aafc-ubuntu2004:~/aafc_shp/pdv000/Anvio$               packages/anvio/data/misc/COG/COG20/DB_BLAST/COG/COG.fa



And here is the contents of my DB_BLAST/COG:

(anvio-8) pdv000@inter-c-aafc-ubuntu2004:~/miniconda3/envs/anvio-8/lib/python3.10/site-packages/anvio/data/misc/COG/COG20/DB_BLAST/COG$ ls
COG.fa.pdb  COG.fa.phr	COG.fa.pin  COG.fa.pot	COG.fa.psq  COG.fa.ptf	COG.fa.ptf-lock  COG.fa.pto

**Comment by meren** [comment]
Sorry, your attempt failed due to new lines :( Can you please try copy-pasting this one instead:

```
makeblastdb -in /gpfs/fs3c/aafc/aafc_shp/pdv000/Anvio/tmpskp4t2xv -dbtype prot -out /home/pdv000/miniconda3/envs/anvio-8/lib/python3.10/site-packages/anvio/data/misc/COG/COG20/DB_BLAST/COG/COG.fa
```

**Comment by PeymanDerik** [comment]
Thanks. Here is the output:


Building a new DB, current time: 09/22/2024 19:45:32
New DB name:   /home/pdv000/miniconda3/envs/anvio-8/lib/python3.10/site-packages/anvio/data/misc/COG/COG20/DB_BLAST/COG/COG.fa
New DB title:  /gpfs/fs3c/aafc/aafc_shp/pdv000/Anvio/tmpskp4t2xv
Sequence type: Protein
Deleted existing Protein BLAST database named /home/pdv000/miniconda3/envs/anvio-8/lib/python3.10/site-packages/anvio/data/misc/COG/COG20/DB_BLAST/COG/COG.fa
Keep MBits: T
Maximum file size: 3000000000B
Adding sequences from FASTA; added 3213025 sequences in 52.8353 seconds.


Segmentation fault (core dumped)

**Comment by meren** [comment]
Most likely, you are running out of memory:

```
Segmentation fault (core dumped)
```

There is nothing anvi'o can do about this unfortunately :(
