### ISSUE TITLE
[BUG] Error in rule megahit

### ISSUE THREAD

**Issue by PeymanDerik** [merenlab/anvio#2352]
## Short description of the problem

CalledProcessError in file /Snakefile, line 632.

## anvi'o version

Anvi'o .......................................: marie (v8)
Python .......................................: 3.10.15

Profile database .............................: 38
Contigs database .............................: 21
Pan database .................................: 16
Genome data storage ..........................: 7
Auxiliary data storage .......................: 2
Structure database ...........................: 2
Metabolic modules database ...................: 4
tRNA-seq database ............................: 2

## System info

I use Linux 64-bit
Installed Anvio using: "pip install anvio-8.tar.gz"

## Detailed description of the issue

I get this error when running command "anvi-run-workflow -w metagenomics  -c config-megahit.json --additional-params --cores 24 --keep-going --rerun-incomplete":

Error in rule megahit:
    jobid: 0
    input: 01_QC_megahit/S00JY_0368-QUALITY_PASSED_R1.fastq.gz, 01_QC_megahit/S00JY_0506-QUALITY_PASSED_R1.fastq.gz, 01_QC_megahit/S00JY_0368-QUALITY_PASSED_R2.fastq.gz, 01_QC_megahit/S00JY_0506-QUALITY_PASSED_R2.fastq.gz
    output: 02_FASTA_megahit/Kinsella Tame 2A/final.contigs.fa
    log: 00_LOGS_megahit/Kinsella Tame 2A-megahit.log (check log file(s) for error details)

RuleException:
CalledProcessError in file /gpfs/fs3c/aafc/aafc_shp/pdv000/Anvio/anvio-8/lib/python3.10/site-packages/anvio/workflows/metagenomics/Snakefile, line 632:
Command 'set -euo pipefail;  megahit -1 01_QC_megahit/S00JY_0368-QUALITY_PASSED_R1.fastq.gz,01_QC_megahit/S00JY_0506-QUALITY_PASSED_R1.fastq.gz -2 01_QC_megahit/S00JY_0368-QUALITY_PASSED_R2.fastq.gz,01_QC_megahit/S00JY_0506-QUALITY_PASSED_R2.fastq.gz -o 02_FASTA_megahit/Kinsella Tame 2A_TEMP -t 24 --min-contig-len 1000                --memory 1000000.0        >> 00_LOGS_megahit/Kinsella Tame 2A-megahit.log 2>&1' returned non-zero exit status 127.
  File "/gpfs/fs3c/aafc/aafc_shp/pdv000/Anvio/anvio-8/lib/python3.10/site-packages/anvio/workflows/metagenomics/Snakefile", line 632, in __rule_megahit
  File "/gpfs/fs3c/aafc/aafc_shp/pdv000/Anvio/anvio-8/lib/python3.10/concurrent/futures/thread.py", line 58, in run
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Exiting because a job execution failed. Look above for error message

**Comment by ivagljiva** [comment]
Hi @PeymanDerik,

> Installed Anvio using: "pip install anvio-8.tar.gz"

If the `pip install` is the only command you used to install anvi'o, then that is probably the issue. You need to follow all the instructions at https://anvio.org/install/linux/stable/ to make sure you have all the required dependencies.

I suspect that is the case since your paths don't appear to make use of a conda environment :)
Please re-install following the appropriate instructions.

**Comment by PeymanDerik** [comment]
Thanks. I followed all the instructions and then ran "conda pulp=2.7" (because I was getting an error for this). I removed my Anvio and re-install it but I still get the same error!

**Comment by PeymanDerik** [comment]
I don't see megahit in my /bin and here is the output of megahit log:  /usr/bin/bash: megahit: command not found. I would appreciate your guidance on this. Thanks!

**Comment by meren** [comment]
This means not everything worked during your installation, and anvi'o is not installed properly.

Please try again, @PeymanDerik. Or go through the installation instructions with a local bioinformatician to figure out what goes wrong.

**Comment by PeymanDerik** [comment]
I re-installed it three times and never got any error on that but the issue persists. Will try again. Thanks!

**Comment by meren** [comment]
Try again with someone beside you :) Something is going wrong somewhere and you are not realizing it, and repeating the same steps will unlikely help.

**Comment by PeymanDerik** [comment]
Downloading and Extracting Packages:
                                                                                                                                                     
Preparing transaction: done                                                                                                                          
Verifying transaction: done
Executing transaction: / vmatch selection functions are installed in /gpfs/fs3c/aafc/aafc_shp/pdv000/Anvio/anvio-8/lib.
You can use them without specifying their full path.
Symbol map files are installed in /gpfs/fs3c/aafc/aafc_shp/pdv000/Anvio/anvio-8/share/vmatch-2.3.0-5/TRANS/.
Activation and deactivation scripts will set MKVTREESMAPDIR accordingly
so you can use symbol map files without specifying their full path.
Those scripts are in /gpfs/fs3c/aafc/aafc_shp/pdv000/Anvio/anvio-8/etc/conda/activate.d/vmatch-2.3.0-5.sh and /gpfs/fs3c/aafc/aafc_shp/pdv000/Anvio/anvio-8/etc/conda/deactivate.d/vmatch-2.3.0-5.sh respectively.

| 
\ 
done


I will, thanks again!

**Comment by PeymanDerik** [comment]
It seems you have designed Anvio just for yourself. Nobody understands it!! I give up.

**Comment by meren** [comment]
I'm sorry for not being able to help you more, @PeymanDerik. There are much easier tools out there that will likely be more than enough for your questions. I hope you will find a way to analyze your data and find in them the answers you are looking for :)


Best wishes,
Meren
