### ISSUE TITLE
[BUG]  manual curation import binning to profile.db not working

### ISSUE THREAD

**Issue by emily-ap** [merenlab/anvio#2370]
## Short description of the problem

We are trying to follow this protocol: https://github.com/koszullab/metaTOR/blob/master/docs/example/manual_curation_of_metator_MAGs.md, and the "Import binning" step is not working due to the PROFILE.db missing a table. 

## anvi'o version

Anvi’o .......................................: marie (v8)
Python .......................................: 3.10.15

```
anvi-self-test --version
```

## System info

**Current OS**
Description:	Ubuntu 22.04.5 LTS
Release:	22.04
Codename:	jammy

**Used conda to install anvi'o** 
```
conda create -y --name anvio-8 python=3.10
```
## Detailed description of the issue

Using the following tutorial: https://github.com/koszullab/metaTOR/blob/master/docs/example/manual_curation_of_metator_MAGs.md we are trying to manually curate a single bin. When running the "import binning" step, we receive the output attached (see photo and text below): 

Config Error: The database at profile/PROFILE.db does not seem to have a table named
       `mean_coverage_Q2Q3_splits` :/ Here is a list of table names this database
       knows: self, item_additional_data, item_orders, layer_additional_data,
       layer_orders, variable_nucleotides, variable_codons, indels, views,
       collections_info, collections_bins_info, collections_of_contigs,
       collections_of_splits, states

![Screenshot 2024-11-07 at 3 21 37 PM](https://github.com/user-attachments/assets/76ea09c2-fd4a-48a7-bf1b-554441ac0d28)

## Files / commands to reproduce the issue

command to reproduce: 
```
anvi-import-collection -c ME2015-04-11_3300034167_anvio.db -p profile/PROFILE.db -C ME201504 --contigs-mode ME2015-04-11_3300034167_binning.tsv
```
Files are very large but can be uploaded if necessary!

**Comment by meren** [comment]
That profile-db seems to be broken :/

Can you please send the following output as well:

```
anvi-db-info profile/PROFILE.db
```

**Comment by emily-ap** [comment]
Please see screenshot of output! 
![Screenshot 2024-11-08 at 12 24 24 PM](https://github.com/user-attachments/assets/1d45ad81-d4a4-49b7-9b8c-8516beccfc58)

**Comment by meren** [comment]
and can you please also send the output for `anvi-self-test -v`?

**Comment by meren** [comment]
I will also need this output please:

```
anvi-export-table profile/PROFILE.db --list
```

For instance when I run this on a proper database, this is the output I get:

```
self
item_additional_data
item_orders
layer_additional_data
layer_orders
variable_nucleotides
variable_codons
indels
views
collections_info
collections_bins_info
collections_of_contigs
collections_of_splits
states
protein_abundances
metabolite_abundances
std_coverage_splits
std_coverage_contigs
mean_coverage_splits
mean_coverage_contigs
mean_coverage_Q2Q3_splits
mean_coverage_Q2Q3_contigs
detection_splits
detection_contigs
abundance_splits
abundance_contigs
variability_splits
variability_contigs
```

If you have a list that differs from this, it is a certainty that the run that generated your profile-db failed at some point, and what you have a the moment is a broken, unfinished output :/

**Comment by emily-ap** [comment]
See photo: 
![Screenshot 2024-11-08 at 12 44 40 PM](https://github.com/user-attachments/assets/5d34877e-8daf-40a8-9bea-1321219a1236)

Yes it looks like ours failed. We can try redoing our earlier steps. Would it matter that we're performing this on a single bin at and therefore are skipping the merging step outlined in the protocol from metaTOR documentation? 

protocol referenced: https://github.com/koszullab/metaTOR/blob/master/docs/example/manual_curation_of_metator_MAGs.md

**Comment by meren** [comment]
That part doesn't matter :)
