### ISSUE TITLE
tRNAscan-SE version tested

### ISSUE THREAD

**Issue by shuqili** [merenlab/anvio#2381]
Hi Anvio developers,

Thank you so much for your hard work! Im just sharing the warning msg below as indicated from the program.

WARNING
===============================================
The version of tRNAscan-SE installed on your system ('2.0.12') is not one of
those that we tested its anvi'o driver with. Anvi'o will continue to try to run
everything as if this didn't happen. If you see this warning but everything
works fine, let us know so we can include this version number into the list of
'tested' version numbers. If you see an unexpected error, please consider
installing one of these versions of tRNAScan-SE (and again please let us know
anyway so we can address it for later): '2.0.5, 2.0.7, 2.0.9'

**Comment by meren** [comment]
Thank you very much for sending this, @shuqili! The anvi'o main branch includes `2.0.12` as one of the tested versions, and it will be in our next stable release!

Best wishes,
Meren
