### ISSUE TITLE
 The script of anvi-export-gene-clusters is missing

### ISSUE THREAD

**Issue by drhchen** [merenlab/anvio#2383]
In the anvio-8, I tried to use anvi-export-gene-clusters, but it is missing. 
https://anvio.org/help/main/programs/anvi-export-gene-clusters/
<img width="1048" alt="image" src="https://github.com/user-attachments/assets/26d1246b-bdf3-47d2-b33d-33f994a2925b" />

**Comment by ivagljiva** [comment]
Hi @drhchen, This is a new program. You need to install the development version of anvi'o in order to use it: https://anvio.org/install/#development-version
