### ISSUE TITLE
anvi'server does not send large files for download

### ISSUE THREAD

**Issue by meren** [merenlab/anvio#347]
For projects with large view data files, the download links for the whole project and view data (`downloadProjectZIP()` and `saveAs(pdata.files.data, 'data.txt')`) are not working.

I tested with a smaller dataset, and they worked :)

**Comment by gkmngrgn** [comment]
@meren can you share with me a sample data for repeating the same problem in my local server?

**Comment by meren** [comment]
Sure! I will send you a private e-mail!

**Comment by paczian** [comment]
Could you shoot me that data too? The client might get overwhelmed. Solid solution would be to store the full data as zip on the server (which would imply updating the zip file every time new data is uploaded) and sending that zip.

I was assuming all small files, if they get larger, there should be distinct server requests to get each file.

Cheers
Tobi

**Comment by meren** [comment]
I was also questioning the ways we transfer data in a similar manner. See #348.

**Comment by meren** [comment]
this is too old.
