### ISSUE TITLE
anvi-script to randomly select a defined number of raw from large files

### ISSUE THREAD

**Issue by tdelmont** [merenlab/anvio#369]
Hi,

Given the fact that anvi'o cannot always visualize entire tables due to browser limitations in the interface, it would be useful to allow users to select randomly a defined number of rows (on top of the first row that generally provides metadata information).

An anvi-script command would be very useful to microbial ecologists with limited bioinformatics skills :)

Tom

**Comment by meren** [comment]
Maybe we can write something like `anvi-script-subsample-matrix`.
