### ISSUE TITLE
Samples tree not available if added later

### ISSUE THREAD

**Issue by ShaiberAlon** [merenlab/anvio#378]
I created a project, and originally I  didn't put a samples order file, but only added it later (through the option on the home screen). But the samples order tree is not available.

**Comment by meren** [comment]
That part of the server needs a bit attention. I am tentatively assigning to @ozcanesen, in case he finds some extra time in his hands and wants to get used to the server code a bit.

**Comment by meren** [comment]
the new server will not suffer from this.
