### ISSUE TITLE
Ability to pull protein clusters out of pangenome output based upon their distribution among bins/genomes

### ISSUE THREAD

**Issue by AstrobioMike** [merenlab/anvio#396]
Just a reminder this has been requested by some.

For instance, if I wanted the protein clusters that were present ONLY in two of my bins, and absent from all others. It'd be good to be able to export them by specifying which bins you want the exclusively present protein clusters, without having to manually select them in interactive.

A current bash workaround can be done as such. Say I want the protein clusters found in only two bins (which in this case just so happen to be columns 8 and 19 of my view_data.txt file):
### This pulls out all the protein cluster IDs that are in both of those bins only, and absent from all others:

$ awk '{ total_others=$2+$3+$4+$5+$6+$7+$9+$10+$11+$12+$13+$14+$15+$16+$17+$18; if ($8 >=1 && $19 >=1 && total_others==0) print $1 }' view_data.txt | sed '1d' > PC_IDs_exclusively_shared.txt
### Then this will pull the full info for those protein cluster IDs from the protein_cluster.txt file:

$ while read p; do grep "$p" ../protein-clusters.txt; done < PC_IDs_exclusively_shared.txt > PCs_exclusively_shared.txt
### And then this will turn that into a fasta:

$ awk '{print ">"$3"_"$4"\n"$5}' PCs_exclusively_shared.txt > PCs_exclusively_shared.faa

cheers!

**Comment by meren** [comment]
Thanks again for this, Mike. We now have a very comprehensive summary output for pangenomic analyses which makes these somewhat easier (I hope).
