### ISSUE TITLE
Layer selection in interactive interface

### ISSUE THREAD

**Issue by ShaiberAlon** [merenlab/anvio#403]
The layer selection feature is great (thank you Ozcan!). Right now when you go over a branch of the layers with the mouse then that branch becomes red. I think it would be great if the layers themselves would also change color.

**Comment by meren** [comment]
I assume this can be quite challenging to achieve. Can you comment and/or close the issue, @ozcan? :)

**Comment by ozcan** [comment]
This is not impossible to achieve but needs a lot of work and will make code more complicated
