### ISSUE TITLE
Anvi-interactive through SSH tunnel

### ISSUE THREAD

**Issue by weirdlobster** [merenlab/anvio#413]
I'm trying to run Anvi-interactive through a SSH tunnel according to directions on Merenlab.org, but I'm having an interface issue when I start Google Chrome. It looks like two CSS sheets are overlapping (this could be an incorrect term). I don't have the ability to change parameters for the graph, only select objects that are normally tabulated at the top. Is the sizing for these not set to static, and allowed to take up a large section of the screen? I've attached a picture. You can see a bullet list of 'layers' 'sample' 'bins' 'mouse' which should not be present.

Thank you!
![screen shot 2016-11-07 at 3 30 47 pm](https://cloud.githubusercontent.com/assets/17112621/20080755/3b88e546-a500-11e6-9987-7b403603821e.png)

**Comment by meren** [comment]
Hi weirdlobster,

We see this when people install anvi'o from the GitHub repository, like it is explained here:

http://merenlab.org/2016/06/26/installation-v2/#installing-or-updating-from-the-current-codebase-semi-pro

But without initializing submodules before the installation.

How did you install anvi'o on your server?


Best,

**Comment by weirdlobster** [comment]
I use a large server on my campus, and all module installations (including ANVI'O) are installed by the server team. Here is a screenshot of what they have installed. Should I email them that page and tell them a feature is not working because "submodules need to be initialized before installation"?

Thank you for the quick reply! I'm looking forward to seeing my data through ANVI'O.
![screen shot 2016-11-07 at 3 48 58 pm](https://cloud.githubusercontent.com/assets/17112621/20081043/f47a5ffc-a501-11e6-85b1-ea5aaf94b303.png)

**Comment by meren** [comment]
Yes, I think it would be wise to consult with them. You can direct them to this issue so they have the link to the installation instructions, and they know how to reach me if I can be of any help to them.

Thanks,
