### ISSUE TITLE
command not found for COG annotation

### ISSUE THREAD

**Issue by rbeinart** [merenlab/anvio#414]
Hi there,
I am running v.2.0.2 and I tried the new COG annotation commands for the first time. Both the setup and run commands result in a "command not found". Other Anvio commands work fine.

Thanks!
-Roxanne-

**Comment by meren** [comment]
Hi Roxanne,

Sorry for the confusion. The COG workflow is going to be available with the next release. I now put the proper warning at the top of the post: http://merenlab.org/2016/10/25/cog-annotation/

The document for COGs is available, along with the one for our new pangenomic workflow, so early adopters and testers can start playing with them before the official release.

If you would like to try you can install anvi'o from the `master` repository (which will have the version `v2.0.3`, but when this repo becomes an official release, we will change the version number to `v2.1.0`).


Best,
