### ISSUE TITLE
default state is an issue when modifying the SAMPLE.db in pangenomics workflow

### ISSUE THREAD

**Issue by tdelmont** [merenlab/anvio#417]
Hi,

as the default state automatically loads after invoking anvi-display-pan, it creates an issue if one wants to use an alternative SAMPLES.db (e.g., if extra information is needed).

Best

tom

**Comment by meren** [comment]
@ozcan, If you add a new layer to the samples.db, the previous state brakes.

**Comment by meren** [comment]
Tom, did you have a chance to test this? If you did, close the issue.

**Comment by tdelmont** [comment]
it works!
