### ISSUE TITLE
Add number of PCs per genome in the samples.db for pangenomes

### ISSUE THREAD

**Issue by ShaiberAlon** [merenlab/anvio#419]
I suggest to add a layer of additional information to the samples.db for pangenome: for each genome it would show the number of PCs that are represented in that genome.

Another cool option: a layer showing the number of singleton PCs present in each genome.

**Comment by meren** [comment]
Both are very good ideas (and I am surprised the first one is not there (is it really not there? THANKS, MEREN)).

I will look into this :)

**Comment by meren** [comment]
Took only 14 months. Better late than..

**Comment by ShaiberAlon** [comment]
hehe right! I totally forgot I opened this issue.
