### ISSUE TITLE
pangenome interactive - switch the numbers for Gene Calls and PCs

### ISSUE THREAD

**Issue by ShaiberAlon** [merenlab/anvio#420]
The number under Gene Calls and under PCs are supposed to be switched.
If I understand Gene Calls >= PCs (since multiple Gene Calls could be in one PC)

![image](https://cloud.githubusercontent.com/assets/17661044/20608503/3be24c1c-b248-11e6-9ef0-c9a936b0ca54.png)

**Comment by meren** [comment]
Correct.

We don't need `Splits` and `Len` in this context :) `PCs` and `Genes` is great, but then the content of `PCs` should be what is shown underneath the `Genes` and vice-versa.

I will tentatively assign this to @ozcan, but then I can take care of it if he doesn't show up soon ;)

**Comment by ShaiberAlon** [comment]
Awesome!! :-)
Thank you!
