### ISSUE TITLE
It is time to say goodbye to the "contig" requirement in anvi'o, no?

### ISSUE THREAD

**Issue by tdelmont** [merenlab/anvio#425]
Hi,

long ago, anvi'o aim was only to making sense of contigs from metagenomic-assembly outputs. 
Now anvi'o is a platform that can visualize all sorts of data.
As a result, some traits of the past remain in the codebase that are not that relevant today.

"contig" requirement is emblematic of changes in anvi'o. Or like my mentor likes to say, "contig" is so 2016.

So, Meren, would you be willing to allow other nomenclature for the top left cell of matrix tables anvi'o uses as an input file???

Let's bring anvi'o into the wonders of 2017!!!

Thanks!

Tom

**Comment by meren** [comment]
I SHALL THINK ABOUT THIS.

... but I kinda like the idea of making you suffer too.

![image](https://cloud.githubusercontent.com/assets/197307/20867284/0e7bc012-ba06-11e6-9138-46c4660a0d7c.png)

This will be a hard one.
