### ISSUE TITLE
anvi-script-gen_stats_for_single_copy_genes.R Error

### ISSUE THREAD

**Issue by michoug** [merenlab/anvio#426]
Hi,

There is a duplicate line in the anvi-script-gen_stats_for_single_copy_genes.R
the line 104 and 106 contains the same command : line = element_blank()
that create this error :

Error in theme(line = element_blank(), text = element_blank(), line = element_blank(),  :
  formal argument "line" matched by multiple actual arguments
Execution halted

Best
Greg

**Comment by meren** [comment]
Although, the current implementation of this script will definitely not work with the next release :/

You can download the latest version of this file and use it, but we need to re-implement it for the current master repo, because our SCG infrastructure has changed quite a bit.

Best,
