### ISSUE TITLE
Pan-Genome with known genome

### ISSUE THREAD

**Issue by michoug** [merenlab/anvio#432]
Hi,
I've been playing with the pan-genome pipeline (2.0.3 version) with external genomes, and I would suggest to add an option to be able to work with "known" proteins, instead of having prodigal found new ones. Another option could be to be able to use a gff file to load the annotations and use them during the analyses.
Best

Greg

**Comment by meren** [comment]
Hi Greg,

Thank you very much for the report. I think what you suggest here is a legitimate need. There is a workaround to achieve this even with the current implementation.

The current implementation of the program `anvi-pan-genome` does not know whether ORFs reported in the contigs database for a given internal or external genome has known functions, and uses all ORFs. Although, you have full control over ORFs stored in a given contigs database. You can use the parameter `--external-gene-calls` to generate a contigs db for your external genome only with gene calls that have known functions. The format of this file is in the user tutorial, but I also implemented a new program, `anvi-export-gene-calls` while responding to this issue (`git pull` if you are following `master`), so one can export all the gene calls from a contigs database in a proper format, remove things from it, and use the same file with the `--external-gene-calls` flag. The workaround is ugly, but making `anvi-pan-genome` annotation-aware will be uglier.

I've heard about providing option to use GFF/GBK files with `anvi-gen-contigs-database` too many times to ignore it :) So I will open another issue for that and hopefully get it done at some point.


Best,
