### ISSUE TITLE
anvi-script-predict-CPR-genomes output to file not working

### ISSUE THREAD

**Issue by xvazquezc** [merenlab/anvio#445]
Hi Meren,
I ran `anvi-script-predict-CPR-genomes` with the `-o` option but while the STDOUT looks fine the generated file only included this:

> NOT CPR (Conf: 95%, Size: 3,386,494, C/R: 79%/4%)

Which is the result of the last bin evaluated.

This is the command I used:

> anvi-script-predict-CPR-genomes cpr-bscg.classifier -c contigs.db -p SAMPLES-CLUSTERED-MERGED/PROFILE.db -C CONCOCT_clustered_good -o CPR_bins.txt

Cheers,
Xabi

**Comment by meren** [comment]
It is now fixed via 5e8ed269fc72423b9eacccb3541f8732297e9c08 in a branch which will be merged to the `master` branch very soon :)

Thank you very much for the report.
