### ISSUE TITLE
colors vs. bars in additional layers (interactive interface)

### ISSUE THREAD

**Issue by ShaiberAlon** [merenlab/anvio#446]
When supplying additional layers file (using `anvi-interactive -A additional_layers.txt`), in order to choose whether to show the information as bars or color-coded, then for each layer (each column in the file `additional_layers.txt`), the first line of the data is checked (to see if numeric or character), but what should be done is that if there is a non-numeric value in the column then color-coding should be used, and only if **all** the values are numeric, then bars should be used.

**Comment by meren** [comment]
It is a very expensive check :/

**Comment by ozcan** [comment]
actually I though like that but when I implemented ordering each taxa/category according to number of items they have I had to loop through each column and I have seen that the cost is nothing comparing to actual rendering

**Comment by meren** [comment]
but you didn't try to cast them through int/str checks, right? :)

**Comment by meren** [comment]
still! if you think it is not a big deal, I think we can add it. your call :)
