### ISSUE TITLE
Anvi-interactive won't run with cherrpy>=9.0

### ISSUE THREAD

**Issue by jmeppley** [merenlab/anvio#447]
My latest installs have been failing because pip is now up to cherrypy 10.0. The issue comes up when I launch anvi-interactive:

<code><blockquote>
Traceback (most recent call last):
  File "/Users/jmeppley/anaconda3/envs/anvio/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/Users/jmeppley/anaconda3/envs/anvio/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/jmeppley/anaconda3/envs/anvio/lib/python2.7/site-packages/bottle.py", line 3117, in run
    server.run(app)
  File "/Users/jmeppley/anaconda3/envs/anvio/lib/python2.7/site-packages/bottle.py", line 2777, in run
    from cherrypy import wsgiserver
ImportError: cannot import name wsgiserver
</blockquote></code>

It seems that, as of cherrypy 9.0, the wsgiserver module in cherrpy has been relocated. Technically, this is probably a bug with the dependency definitions in bottle, but it might be worthwhile for anvio users to limit cherrypy to versions <9.

I see this problem both with the pip installed anvio (2.1.0) and the python3 version of anvio (the new-profiling branch). I don't have a working install from the master branch to test with, sorry.

**Comment by meren** [comment]
Hi John,

I realized that a very short while ago and fixed the requirements.txt in the `master` (https://github.com/merenlab/anvio/commit/d23bb1f584e6fc49787a074baa4bebd3e99244f7) :/

We clearly need to stick with explicit version numbers in the requirements just to make sure things will not fail in the long run. My mistake.

I know you don't need any help to resolve it, but I updated the installation manual, and I've been referencing people who complain about this error to this e-mail:

https://groups.google.com/forum/#!msg/anvio/56KI_ulAJr8/3xLpRk0qBAAJ

When py3 repo is merged to master the fix will be in affect. Sorry for the inconvenience, and thank you for the report.
