### ISSUE TITLE
Export splits before BAM profiling step

### ISSUE THREAD

**Issue by dot4822** [merenlab/anvio#452]
Hi Meren,

I went through your tutorial and found that the 'anvi-export-splits-and-coverages' can only be used on merged database. Since the BAM profiling step takes long time, and my target is only to get splits cut up by ANVIO, I would like to know whether it is possible that you can add a new script to export fasta file of splits before BAM profiling step.

Regards,
Dot

**Comment by meren** [comment]
a new program, `anvi-export-splits` is in order.

**Comment by meren** [comment]
(this is now resolved in the development branch and will be in the next release)

**Comment by meren** [comment]
Simply you will use this command to export splits instead of contigs from a single contigs database:

```
anvi-export-contigs -c contigs.db -o output.fa --splits-mode
```

:)
