### ISSUE TITLE
The displayed completion values are problematic when summarizing CONCOCT clusters

### ISSUE THREAD

**Issue by tdelmont** [merenlab/anvio#454]
Hi, 

I realized that with the new recipe of anvi'o regarding Bacteria/Archaea completion values selected for each bin, highly redundant bacterial bins will be displayed as arhaeal, simply because the redundancy is much lower for archaeal, even though completion is obviously pointing at Bacteria:

here is an example:

<img width="1095" alt="screen shot 2017-02-04 at 4 14 26 pm" src="https://cloud.githubusercontent.com/assets/8332889/22621960/62faf494-eaf5-11e6-93bb-cff89c88e01b.png">

and a click on the first bin:

<img width="1149" alt="screen shot 2017-02-04 at 4 14 39 pm" src="https://cloud.githubusercontent.com/assets/8332889/22621963/6a53aa38-eaf5-11e6-8b53-f90cb8f1dd60.png">

I think we should change the recipe, so that it takes primarily into account completion.

**Comment by meren** [comment]
This needs o be tested with this dataset. It is in the `new-version` branch, though.

**Comment by tdelmont** [comment]
we tested it and it worked perfectly!
