### ISSUE TITLE
anvi-profile running out of memory, need bin visualization

### ISSUE THREAD

**Issue by UCSBMicrobiologyCore** [merenlab/anvio#459]
Firstly, I apologize if this is a simplistic issue that can be resolved looking through the manual--I tried, but I wasn't sure exactly which unctions could help me do wheat I need

I am currently trying to use anvio to visualize metabat-derived bins, and to do that, I planned on following the metagenomics walkthrough by first making a profile using my total assembled contigs <2500 nt and bam file and use anvi-import to import bins of these contigs into the aforementioned created profile. 

The problem is, my local computer seems to run out of memory during the anvi-profile step (computer gets very slow, eventually outputs "killed" into the terminal). 

What are my options here? Do I take each bin, run it through bowtie to get a bam file for each one and individually look at each bin as its on profile? Is there another way to import a bunch of bins with coverage information into one anvio profile without me having to look at each bin individually like that? Am I grossly misrepresenting how this program works?

thanks again

Jon

**Comment by meren** [comment]
Hi Jon,

Your approach makes sense. You should merge your individual anvi'o profiles with `--skip-hierarchical-clustering`, and then use `anvi-import-collection` to import your metabat binning results for that data.

Here is some examples to that kind of workflow:

http://merenlab.org/tutorials/infant-gut/

We are aware of the memory issue with `anvi-profile` and will release a new version very soon. But regardless, you should never profile things on your local computer.


Best,

**Comment by UCSBMicrobiologyCore** [comment]
thank you!

the guy who runs our cluster was out for the week :[.

**Comment by vaxherra** [comment]
Hi,
what then are typical memory requirements for anvi-profile? I have a contig.db of around 3.6GB and .bam files in the range of 8GB-1GB. When I compute things on my local SGE cluster with 50GB of RAM, the jobs gets killed.

**Comment by meren** [comment]
Unfortunately I don't have a simple answer for you, @vaxherra :/ If you want, you can make available one of the largest BAMs to me, and I would profile on my server and tell you the maximum memory usage.

**Comment by vaxherra** [comment]
Thanks
Meren, here is a Dropbox folder with contigs.db contigs.h5, and my biggest .bam file with accompanying .bai file:

https://www.dropbox.com/sh/fmrk3qfqx6q6yqs/AAABmy-Nss_vRLQ3RLHPyC_La?dl=0

I've tested some smaller .bam files (1GB) with (obviously) the same contigs.db, but even 120GB of RAM caused SGE cluster to kill it. Right now I've asked for maximum resources per highest-node we have here (370GB) and we'll see. If it gets killed, what are my options here?

Also, I don't know how this happened, now I see I've been using anvio 2.1.0 (although I've installed it through conda 
`conda create -n anvio240 -c bioconda -c conda-forge python=3.5.4 gsl anvio`
anvi-profile--version reported 2.1.0. 
I had basically done most of analyses up to profiling with anvi-profile. Are they major differences between 2.1.0 and 2.4.0 that might affect this basic workflow? (contig.db creation, mapping and profiling?). 

Best,
Robert. 

You can also contact me privately on robert.kwapich@gmail.com.

**Comment by ozcan** [comment]
Hi Robert,

Yes there are many differences and improvements on newer versions. Actually we addressed memory issues in version 2.2.2. I think upgrading to 2.4.0 will solve your problem, [this blog post](http://merenlab.org/2017/03/07/the-new-anvio-profiler/) can help you how to tweak anvi-profile to increase speed or reduce memory usage according to your needs.

All the best,
Ozcan

**Comment by vaxherra** [comment]
@ozcan Thank you so much. I hope it will get better at anvi-profile. But again, should I recompute everything from the start on a standard metagenomic workflow? That is after I start my workflow from contigs produced by (for example) megahit?  Or, you think it would be ok to switch to 2.4.0 at anvi-profile step?

**Comment by ozcan** [comment]
Hi Robert,

You can switch to recent versions without losing any of your steps, assembly or mapping results already compatible. But for example if you created anvi'o contigs.db from your assembly output this will not be compatible automatically, you need to manually upgrade those databases using upgrade scripts we provide in anvi'o. They usually have `anvi-script-upgrade-` prefix, you can see full list of upgrade scripts [here](https://github.com/merenlab/anvio/tree/master/sandbox).

All the best,
Ozcan

**Comment by vaxherra** [comment]
Thanks, it turns out that from 2.1.0 to 2.4.0 (except for profiles db) only PAN DB has changed. So, fortunately for me, not even conversion is needed. 
Thanks for all the rapid help.
