### ISSUE TITLE
no need to require tree for manual mode

### ISSUE THREAD

**Issue by ShaiberAlon** [merenlab/anvio#460]
in interactive.py line 246, there is an error:
        if not self.tree:
            raise ConfigError("When you are running the interactive interface in manual mode, you must declare at least the tree file. Please see the documentation for help.")

now that there is alphabetical order, we should make alphabetical order the default order if no tree was supplied

**Comment by meren** [comment]
Very good point. We should do it before the release, I guess. I will look into this to better understand how this would be possible.
