### ISSUE TITLE
CONTIGS.h5 vs AUXILIARY-DATA.h5

### ISSUE THREAD

**Issue by luuuuuuuke** [merenlab/anvio#467]
It appears that anvi-get-dna-sequences-for-gene-calls is looking for auxiliary data entitled "CONTIGS.h5" instead of the automatically named "AUXILIARY-DATA.h5". If I change the .h5 filename from "AUXILIARY-DATA" to "CONTIGS" the command passes without issue. 

When I use anvi-refine, it works fine: first it looks for CONTIGS.h5 and adds a warning that it cannot be found, but then also looks for AUXILIARY-DATA.h5 and finds it. See screenshots below. Thanks!

<img width="994" alt="screen shot 2017-03-01 at 3 35 13 pm" src="https://cloud.githubusercontent.com/assets/26125116/23482480/dc2075d0-fe94-11e6-9328-1e3b09562484.png">
<img width="837" alt="screen shot 2017-03-01 at 3 38 55 pm" src="https://cloud.githubusercontent.com/assets/26125116/23482622/5e350964-fe95-11e6-8b46-40a5d250e2e1.png">

**Comment by meren** [comment]
It is just a warning, Luke, and it is OK to continue with that warning :)

That part of the code is _really_ looking for the CONTIGS.h5 file. Renaming "AUXILIARY-DATA" to "CONTIGS" makes it think it is there, so it goes like "whatever, it is here", but if it were to be needed for something, things would have been collapsed like the USSR.
