### ISSUE TITLE
ProfileSuperClass should know to work with a bin

### ISSUE THREAD

**Issue by ShaiberAlon** [merenlab/anvio#469]
It should be possible to init an instance of ProfileSuperClass for a give bin.
And then self.split_names will only take the splits that are included in the specified bin

**Comment by meren** [comment]
I don't remember whether we fixed this or not, but I feel like there is code now to be able to do this. Is that correct, @ShaiberAlon?

**Comment by ShaiberAlon** [comment]
I'll have to look into it.

**Comment by meren** [comment]
Any news on this? :)

**Comment by ShaiberAlon** [comment]
Since this is precisely where my classifier broke, then I will know for sure soon, when I implement the wrapper class for the mcg-classifier (as we recently discussed)

**Comment by ShaiberAlon** [comment]
I'm pretty sure that this is done :-) but in any case MCGC is happy with ProfileSuperClass (for now)
