### ISSUE TITLE
pip installing older versions of anvio?

### ISSUE THREAD

**Issue by UCSBMicrobiologyCore** [merenlab/anvio#477]
Hi all;

I installed the spring version of anvio using pip as instructed on the installation guide. However, as my version of ubuntu requires python 2, I cannot run anvio without a virtualenv. Currently I'm in a rush to get something on a poster, but after trying and failing multiple times with setting this up using online guides (still getting the "we no longer support python2" message, even though python --version spits out 3), I need a quick fix. Is there any way to pip install the xmas version of anvio? I tried running the script as I had installed it before, but it runs into an error reinstalling Rstudio as it exists already (?) and I don't want to mess with that any further (I also tried installing it on another computer in this manner and it gives me the spring).

sorry for the trouble and thank you

Jon

**Comment by meren** [comment]
Hi Jon,

Do all the steps described [here](http://merenlab.org/2016/06/26/installation-v2/#installing-the-latest-stable-release-safe-mode), but modify this part (and all the other version numbers):

```
pip install numpy
pip install scipy
pip install cython
pip install anvio==2.1.0
```

**Comment by UCSBMicrobiologyCore** [comment]
works great! much appreciated.
