### ISSUE TITLE
Contrasts between binning results

### ISSUE THREAD

**Issue by rprops** [merenlab/anvio#480]
Hi,

I was wondering whether it would be possible to include a contrast option to visualize contigs that are differently classified between two bin collections.

To provide some context:
I am currently trying to bin genomes from a low complexity environment. Using different binning methods: e.g. CONCOCT & vizbin I get three genomes at 100 % completeness and around 1% redundancy. However, the actual bin size can differ as much as 500 kb between those bins without affecting completeness and redundancy estimates. As such, depending on the choice of binning method these genome bins can contain up to 500 genes more or less.

To help aid me in refining these bins in anvi'o, it would be helpful to visualize the contigs that are differently clustered between two collections (i.e. binning methods).

Thanks

Ruben

**Comment by meren** [comment]
There are multiple ways of doing this, Ruben. For instance, here I had compared multiple binning results using a single dataset (which is similar to your case):

http://merenlab.org/tutorials/infant-gut/

Another way to see how those bins differ from each other could be taking each pair (or all bins), and doing a pangenomic analyses with anvi'o. Here is some info on how to do that:

http://merenlab.org/2016/11/08/pangenomics-v2/

Or you can simply use the interactive interface to do ad hoc visualizations of bins.

If any of these sound more or less appealing, we can talk more about that if you want.

I will holler at @tdelmont, in case he finds this particularly interesting. Maybe you guys can arrange a short Skype meeting to discuss potential ways of doing this a bit deeper if both of you have time and interest :)

**Comment by rprops** [comment]
Hi Meren,

Thanks for the info - this seemed to do the trick for what I needed to do! 

Greatly appreciate the detailed and quick response!

Ruben
