### ISSUE TITLE
anvi-summarize is very slow

### ISSUE THREAD

**Issue by tdelmont** [merenlab/anvio#481]
Hi,

There is a new strategy for anvi-summarize, but it seems to be problematic, at least for "large metagenomic projects".

here is a screenshot of the first and very slow step:
<img width="1187" alt="screen shot 2017-03-20 at 9 07 34 am" src="https://cloud.githubusercontent.com/assets/8332889/24110519/a9d743e8-0d61-11e7-92a3-4c3cc1c40b83.png">

It is not easy to estimate but anvi'o processed 1000 splits (out of 151,009) in about 15 minutes. So about 40 hours just for this step...

Not sure how to fix this, but this issue is for Meren to be aware of the situation.

Tom

**Comment by meren** [comment]
I already made some improvements for that step while flying to Canada, but it will take some time to incorporate them to the repo.

**Comment by brymerr921** [comment]
I can second this. I have 42 samples (~170,000 splits) which I am thrilled that I can now run through anvi-profile, but anvi-summarize does take two days to complete. I'm running version 2.2.2.

**Comment by meren** [comment]
Yes, I didn't appreciate the fact that reading from HDF could take this much in very large datasets.

I will add a flag to `anvi-summarize` :/

**Comment by meren** [comment]
I solved this. The git push does not work, but I will complete this as soon as I am in Chicago :/ Sorry about the delay.

**Comment by meren** [comment]
This solved in the master with b608834e7c7de30fedc6c9f39bd081003be0e2d6 and following commits. Now there is a new flag, `--init-gene-coverages`, for them to get initialized.
