### ISSUE TITLE
summarize with multiple custom HMMs

### ISSUE THREAD

**Issue by jvineis** [merenlab/anvio#484]
The following problem occurs in v2.1.0 and v2.2.2
When I add more than one custom HMM to the contigs.db, the summarize is unable to complete and throws the following error.

![screen shot 2017-03-23 at 8 38 06 am](https://cloud.githubusercontent.com/assets/1020413/24248123/80d24e76-0fa4-11e7-92df-a29011d47249.png)

Summarize will complete normally if only one custom HMM is loaded.  I tried loading three different HMMs sequentially and regardless of the order added, more than one HMM resulted in an error.  I have attached three custom HMM directories
[HMM_FOR_ANVIO.tar.gz](https://github.com/merenlab/anvio/files/864704/HMM_FOR_ANVIO.tar.gz)

**Comment by meren** [comment]
This problem is now fixed in the master repo, Joe. Thank you very much for reporting it, and sorry for the inconvenience. If you want, you can follow these instructions to crate virtualenv that works with the master repo:

http://merenlab.org/2016/06/26/installation-v2/#installation-for-developers-youre-a-wizard-arry

**Comment by jvineis** [comment]
Hey Meren,
Thanks for your attention to this issue.  Running anvio from the master did not work (see attached), but I commented out line 435 of summarizer.py (see attached) and works.  Most likely due to the fact that I did not load any functions to my contigs.db? 
~J

----- Original Message -----

**Comment by meren** [comment]
Hey Joe,

No attachment :( Responding to GitHub issues from e-mail usually doesn't work the way you intend :/

Thank you!

**Comment by meren** [comment]
Fixed :/ Sorry!
