### ISSUE TITLE
Bin legend in svg file from anvi-display-pan

### ISSUE THREAD

**Issue by dcourtine** [merenlab/anvio#495]
Hi all,

I found a little "bug" in the SVG file.
In Inkscape, the bin legend looks like this,
![bin_inkscape](https://cloud.githubusercontent.com/assets/14869177/25040976/03c5e9e0-210d-11e7-8c2f-34d7fa35fff9.png)
while within the interactive mode (anvi-display-pan), I have this:
![bin_anvi-display-pan](https://cloud.githubusercontent.com/assets/14869177/25041030/55fdd9ac-210d-11e7-90fe-fd351e80c401.png)

Best, 
Damien

**Comment by meren** [comment]
Even flying over the Atlantic did not stop Damien from finding bugs in anvi'o.

**Comment by ozcan** [comment]
Thank you again @dcourtine, I found some dead code while fixing this bug.
