### ISSUE TITLE
improving the workflow for single genomes

### ISSUE THREAD

**Issue by tdelmont** [merenlab/anvio#496]
Hi,

I feel that anvi'o can fill a niche for the analysis of single genomes.
However, my understanding is that we do not have an optimal workflow for this.

In particular, after creating the contigs.db, and running the hmms, we should offer a direct way to summarize the results in a nice way.

I was thinking something like "anvi-summarize -c E_coli_K12_CONTIGS.db --genome-mode --genome-name E_coli_K12 -o SUMMARY_ E_coli_K12"

This way, no need to import a collection connecting the contigs, and no need for a PROFILES.db (blanc or not). 

In the summary, people will get the GC-content, length, N50, completion and redundancy, plus the gene sequences, and if functions were imported, the function of genes.

Of course, we would also encourage people to map reads used to generate the genome, in order to get gene coverages, etc using profiles. This it should be an option.

What do you think?

Tom

**Comment by meren** [comment]
There will always be a need for profile databases, and we will not hide that with flags. Creating a blank profile database for single genomes is a must. That being said, we can add a script into the sandbox directory to import all contigs as a collection into a profile database to make things much more simpler :)
