### ISSUE TITLE
--skip-concoct-binning

### ISSUE THREAD

**Issue by tdelmont** [merenlab/anvio#497]
Hi,

now that we have a dedicated program to control the number of clusters CONCOCT creates,
I suggest we make CONCOCT clustering optional, and not a default parameter, during merging.

It is a bit confusing when writing material on the workflow. "We skipped CONCOCT, and then immediately created CONCOCT clusters....."

Alternatively, if CONCOCT is a default, it would be good to have the option to define the number of clusters to be created (which if I recall is not easy to implement?)

Tom

**Comment by meren** [comment]
It doesn't have to be confusing. CONCOCT shall stay as the default binning algorithm to generate a collection unless the user elects to skip it. We can't change default parameters every time we run into an issue writing a sentence specific to one study.
