### ISSUE TITLE
Noise cutoffs for HMM search should be optional

### ISSUE THREAD

**Issue by meren** [merenlab/anvio#498]
Currently we expect the `GA` noise thresholds to be present in HMM files, but they are not always present in built HMM profiles:

https://groups.google.com/d/msg/anvio/2f75Tyj-k8A/ZlWjTBTtBAAJ

We should make it possible to remove noise based on user-defined e_values, and the current driver for `hmmscan`, and the program `anvi-run-hmms` should change.

Here is the [current header](https://github.com/merenlab/anvio/blob/94807263f85c5d53de0a0459e3031a203d56a034/anvio/drivers/hmmer.py#L47) as a reminder:

``` python
run_hmmscan(self, source, target, kind, domain, genes_in_model, hmm, ref, cut_off_flag="--cut_ga"):
     ...
```

**Comment by meren** [comment]
More pressure:

https://groups.google.com/d/msg/anvio/0gVMSEAwuE0/KBAb3iO4AQAJ

**Comment by meren** [comment]
One of the files required files for external anvi'o HMM profiles to be used with `anvi-run-hmms` `-H` flag is `noise_cutoff_terms.txt` (following the PR #725).

The contents of this file will tell anvi'o which parameters should be passed to `hmmscan` so it can remove noisy hits from HMM results. The current anvi'o defaults is `--cut_ga`, since our default collections are curated from PFAM HMMs, and they contain intrinsically computed noise cutoffs.

If you are using your own HMMs, you can chose an e-value, or anything else permitted by hmmscan. You can learn what you can use based on the help menu (the following output may not be concurrent):

``` bash
meren ~ $ hmmscan -h
# hmmscan :: search sequence(s) against a profile database
# HMMER 3.1b2 (February 2015); http://hmmer.org/

(...)

Options controlling reporting thresholds:
  -E <x>     : report models <= this E-value threshold in output  [10.0]  (x>0)
  -T <x>     : report models >= this score threshold in output
  --domE <x> : report domains <= this E-value threshold in output  [10.0]  (x>0)
  --domT <x> : report domains >= this score cutoff in output

Options controlling inclusion (significance) thresholds:
  --incE <x>    : consider models <= this E-value threshold as significant
  --incT <x>    : consider models >= this score threshold as significant
  --incdomE <x> : consider domains <= this E-value threshold as significant
  --incdomT <x> : consider domains >= this score threshold as significant

Options for model-specific thresholding:
  --cut_ga : use profile's GA gathering cutoffs to set all thresholding
  --cut_nc : use profile's NC noise cutoffs to set all thresholding
  --cut_tc : use profile's TC trusted cutoffs to set all thresholding

(...)
```

For instance, if you were to put the following value in your `noise_cutoff_terms.txt` file so any hits below this e-value would be ommitted from your results:

```
-E 1e-12
```

When you are building and testing your own HMM collection for anvi'o, please keep an eye on the output messages, check your raw number of hits, and if things don't look alright use the `--debug` flag to keep temporary files so you can go through them to figure out what might have gone wrong. If you are confused, or something is not working, consider reaching out to us anyway you can (by leaving a comment down below, or finding us on Slack for a more synchronous conversation).

Please do not hack this approach by passing other parameters to the program through this file other than the noise cut-off parameters so to not compete with parameters anvi'o passes during runtime (unless you particularly feel adventurous).

**Comment by dadahan** [comment]
Hi A. Murat, 

I find that when I include one noise cutoff term to ``anvi-run-hmms`` the script runs fine, but when I include >1, as I have previously and succesfully using ``hmmscan`` locally, the script cannot run. 

Here are example ``noise_cutoff_terms.txt`` files with the tmp log file below:
1
```
-T 1000
```
>1
```
-T 1000 -E 5e-30
```

As you can see in the logfile, this is strange. I thought this might be a character erorr and so I tried using a \n character between flags but that didn't work. 

In some cases I use both E-value and bitscore (S) as cutoffs so being able to use both flags would be helpful.

Any ideas?
 
Thanks!
Dylan

```
# DATE: 29 May 18 15:42:24
# CMD LINE: hmmscan -o /tmp/tmpbvkmjmqj/hmm.output -T 1000 -E 5e-30 --cpu 1 --tblout /tmp/tmpbvkmjmqj/hmm.hits.shitty /tmp/tmpbvkmjmqj/hmm.txt /tmp/tmp8pxnlx6d/aa_gene_sequences.fa
Failed to parse command line: Option -E is incompatible with option(s) -E,-T,--cut_ga,--cut_nc,
Usage: hmmscan [-options] <hmmdb> <seqfile>

where most common options are:
  -h : show brief help on version and usage

To see more help on available options, do hmmscan -h
```

**Comment by meren** [comment]
This was a bug on our part and is fixed in the master repository.

**Comment by dadahan** [comment]
Thanks ~ my mistake, just saw you noted to run the script with the master repo. Thanks!
