### ISSUE TITLE
--skip-single-nucleotide-variants option for anvi-split?

### ISSUE THREAD

**Issue by tdelmont** [merenlab/anvio#500]
Hi,

as always, a new program opens the door to new challenges.
I have been exploring the anvi-split option on a rather large data (>800 MAGs)
and the process is very slow, due to this step:

`Table 'variable_nucleotide_positions' .. reading data`

So, should be consider an option to `--skip-single-nucleotide-variants` ?

Tom

**Comment by meren** [comment]
this will create lots of design headache. plus, @ozcan just fixed the HDF5 mess, so this process will likely take much less time.
