### ISSUE TITLE
ANI estimates for pangenomes?

### ISSUE THREAD

**Issue by AstrobioMike** [merenlab/anvio#505]
Hey all,

I typically take the genomes i'm poking in anvio and run them through pyani to get ANI to make pretty anvio figs like this: 
![image](https://cloud.githubusercontent.com/assets/13923308/25497458/44b203f2-2b4a-11e7-97ae-32216962769c.png)

I figure since this is already a python module: https://github.com/widdowquinn/pyani

Maybe it wouldn't be hard to incorporate and worthwhile for others?
-mike

**Comment by meren** [comment]
@ozcan, let's talk about this when we have a chance. since we now have the misc layer data tables, we should be able to add this functionality for the pangenomic workflow rather easily.

**Comment by ozcan** [comment]
This look really pretty, I have couple questions, do we run this using just core or the whole genome?

**Comment by meren** [comment]
We are not yet at this visual cutery, but anvi'o can do ANI now through pyANI (and it can even add the results into a pan genome database as additional data for layers). Thank you very much for suggesting this, Mike.
