### ISSUE TITLE
anvi-interactive --manual-mode

### ISSUE THREAD

**Issue by ekiefl** [merenlab/anvio#509]
In manual mode, you are forced to provide a non-existent PROFILE.db. Fine. But you are unable to generate it in a directory other than the working directory.

`anvi-interactive --manual-mode -p PROFILE.db -t TREE.txt`

creates a PROFILE.db file in the working directory.

`anvi-interactive --manual-mode -p /path/to/PROFILE.db -t TREE.txt`

generates the error

`File/Path Error: You do not have permission to generate the output file
                 '/path/to/PROFILE.db`,

even if `/path/to/` already exists as a directory.

**Comment by ozcan** [comment]
Hey @ekiefl, can you send the output of `ls -l /path/to/`

**Comment by ekiefl** [comment]
`$ ls -l SNV/SOIgt50_MCIES15_DFC0p01_QM/`
-rw-r--r--  1 Ev  staff   1688791 May  1 16:58 CLUSTERMATRIX.txt
-rw-r--r--  1 Ev  staff  51666706 May  1 16:47 SNV_table.txt
-rw-r--r--  1 Ev  staff   4063028 May  1 16:52 SNV_table_fq.txt
-rw-r--r--  1 Ev  staff      2002 May  1 17:01 TREE_braycurtis.txt
-rw-r--r--  1 Ev  staff      1868 May  1 17:02 TREE_canberra.txt
-rw-r--r--  1 Ev  staff      2114 May  1 17:01 TREE_euclidean.txt
-rw-r--r--  1 Ev  staff    830437 May  1 16:55 cluster_itep.txt

**Comment by ozcan** [comment]
Sorry, my mistake I have edited the comment after sending, I need output of `-la` instead of just `-l`

**Comment by ekiefl** [comment]
`$ ls -l SNV/SOIgt50_MCIES15_DFC0p01_QM/`
total 113800
drwxr-xr-x  9 Ev  staff       306 May  1 17:02 .
drwxr-xr-x  5 Ev  staff       170 May  1 16:45 ..
-rw-r--r--  1 Ev  staff   1688791 May  1 16:58 CLUSTERMATRIX.txt
-rw-r--r--  1 Ev  staff  51666706 May  1 16:47 SNV_table.txt
-rw-r--r--  1 Ev  staff   4063028 May  1 16:52 SNV_table_fq.txt
-rw-r--r--  1 Ev  staff      2002 May  1 17:01 TREE_braycurtis.txt
-rw-r--r--  1 Ev  staff      1868 May  1 17:02 TREE_canberra.txt
-rw-r--r--  1 Ev  staff      2114 May  1 17:01 TREE_euclidean.txt
-rw-r--r--  1 Ev  staff    830437 May  1 16:55 cluster_itep.txt

**Comment by ozcan** [comment]
What is your user name on this machine? It looks like only `Ev` has write permission

**Comment by meren** [comment]
I can't reproduce this. It truly seems to be a permission issue :(
