### ISSUE TITLE
N50 is not displayed in the summary

### ISSUE THREAD

**Issue by tdelmont** [merenlab/anvio#511]
Hi,

at anvi'o v2.3.1 N50 displays "none" in all my summaries:

<img width="1143" alt="screen shot 2017-05-04 at 9 17 49 am" src="https://cloud.githubusercontent.com/assets/8332889/25707962/b2cb3a4c-30aa-11e7-837f-784eceb8ef0f.png">

Tom

**Comment by meren** [comment]
I'm sure you broke it, Tom. I'll look into it!

**Comment by meren** [comment]
Can you confirm whether it is resolved?

Thanks.
