### ISSUE TITLE
binning files not produced?

### ISSUE THREAD

**Issue by eliztr** [merenlab/anvio#513]
Hi, 

I am trying to compare IDBA-UD assembled data binned by anvio and a couple other programs. My goal was to use anvio to bin only one sample. Following the tutorial, I think the code to do this is:

```
docker run --rm -v /media/executor/etrhert/idba_FS921:/idba_FS921 -it meren/anvio:2.3.0
anvi-script-reformat-fasta contig-100.fa -o contig-100f.fa --min-len 2500 --simplify-names --report name_conversions.txt
anvi-gen-contigs-database -f contig-100f.fa -o contig-100f.db
anvi-run-hmms -c contig-100f.db
anvi-get-dna-sequences-for-gene-calls -c contig-100f.db -o gene-calls.fa
centrifuge -f -x $CENTRIFUGE_BASE/p+h+v/p+h+v gene-calls.fa -S centrifuge_hits.tsv
anvi-import-taxonomy -c contig-100f.db -i centrifuge_report.tsv centrifuge_hits.tsv -p centrifuge
bowtie2-build contig-100f.fa mapping_anvio/contig-100f
bowtie2 --threads 32 -x ./mapping_anvio/contig-100f -1 ~/idba_FS921/Backarc_metagenomes-QUALITY_PASSED_R1.fastq -2 ~/idba_FS921/Backarc_metagenomes-QUALITY_PASSED_R2.fastq -S ./mapping_anvio/FS921_contig-100f.sam
for i in *.sam; do samtools view -SbF 4 $i | samtools sort -@ 12 - ${i%.sam} && samtools index ${i%sam}bam & done
anvi-profile -i ./mapping_anvio/FS921_contig-100f.bam -c contig-100f.db --output-dir FS921_cc --sample-name FS921 --cluster-contigs
```

However, this results in only these files:
`AUXILIARY-DATA.h5  PROFILE.db  RUNLOG.txt`

And returns errors when I try to move on to the interactive step:
```
anvi-interactive -p FS921_cc/PROFILE.db -c contig-100f.db -C CONCOCT
```
Am I missing additional flags to prepare an analysis of just one sample? Any guidance would be greatly appreciated - Thank you!

**Comment by tdelmont** [comment]
Hi,

If I understand the situation correctly, the CONCOCT collection is only
generated in the merging step, which in the case of a single profile is
skipped.

Can you try "anvi-interactive -p FS921_cc/PROFILE.db -c contig-100f.db" for
manual binning without CONCOCT?

Tom

**Comment by eliztr** [comment]
That returns this:

[13 May 17 02:13:55 Initializing splits taxonomy] ...
   Traceback (most recent call last):
  File "/usr/local/bin/anvi-interactive", line 111, in <module>
    d = interactive.InputHandler(args)
  File "/usr/local/lib/python3.5/dist-packages/anvio/interactive.py", line
104, in __init__
    self.init_splits_taxonomy(self.taxonomic_level)
  File "/usr/local/lib/python3.5/dist-packages/anvio/dbops.py", line 206,
in init_splits_taxonomy
    splits_taxonomy_table =
contigs_db.db.get_table_as_dict(t.splits_taxonomy_table_name)
AttributeError: 'NoneType' object has no attribute 'get_table_as_dict'

**Comment by meren** [comment]
Hi elitzr,

The only explanation I can think of regarding the following error is a corrupted contigs database :/

```
contigs_db.db.get_table_as_dict(t.splits_taxonomy_table_name)
AttributeError: 'NoneType' object has no attribute 'get_table_as_dict'
```

Can you run this:

```
sqlite3 contig-100f.db 'select * from self;'
```

Best,

**Comment by meren** [comment]
BTW, you are using 2.3.0. This bug may have been fixed since then.

**Comment by eliztr** [comment]
Hi,

This is the result:

version|8
db_type|contigs
contigs_db_hash|bf30e584
split_length|20000
kmer_size|4
num_contigs|11611
total_length|53228049
num_splits|11675
gene_function_sources|
genes_are_called|1
splits_consider_gene_calls|1
creation_date|1494472134.72897
taxonomy_source|centrifuge

**Comment by meren** [comment]
Can you please confirm this error does not go away with the latest version?

**Comment by federicofassetta** [comment]
Hi, I am having the same problem, did anyone solve it by chance? Thanks a lot
