### ISSUE TITLE
anvi-gen-contigs-database speed?

### ISSUE THREAD

**Issue by adityabandla** [merenlab/anvio#517]
Hi 

Is there anyway to speedup the generation of the contigs database for large assemblies? For a moderately sized dataset, containing approx. 3 million contigs (>2.5kbp), it currently takes about 2d

Regards
Aditya

**Comment by meren** [comment]
Yes, we could better parallelize the process. But 2 days is not a bad time for something you will do only once throughout to entire workflow, so it is not a very high priority for us given the resources we have.

**Comment by adityabandla** [comment]
Agreed! I am regenerating my contigs database, to troubleshoot issues with the potential C/R estimates bug and hence the question :)
