### ISSUE TITLE
The summary of anvi-split bins have silly percent recruitment stats

### ISSUE THREAD

**Issue by tdelmont** [merenlab/anvio#524]
Hi,

anvi-split does not keep the collection(s) information, needed to run anvi-summarize.
We currently need to use anvi-interactive, select all splits, and save as a bin prior to summarize.

Thinking about it, now that anvi-split is there, it would be nice to have a flag during anvi-summarize so that all the contigs are used for summary, instead of selecting a collection Id and bin Id (irrelevant when working with self contained files representing a single bin).

Tom

**Comment by tdelmont** [comment]
In the same topic, I realized that with anvi-split, this is what we get when summarizing:

<img width="1178" alt="screen shot 2017-05-28 at 3 08 38 pm" src="https://cloud.githubusercontent.com/assets/8332889/26531833/a74e8226-43b7-11e7-8755-f1b18a25fdc7.png">

Would it make sense to keep values from the whole collection?

**Comment by meren** [comment]
The current title is not correct. anvi-split does keep a default collection (`DEFAULT`) with a single bin that describes all splits (`ALL_SPLITS`):

```
(anvio-master) meren CONCOCT_BINS_SPLIT/Bin_1 $ anvi-show-collections-and-bins -p PROFILE.db

Collection: "DEFAULT"
===============================================
Collection ID ................................: DEFAULT
Number of bins ...............................: 1
Number of splits described ...................: 18
Bin names ....................................: ALL_SPLITS
```
