### ISSUE TITLE
Searching for function in anvi'o Interactive

### ISSUE THREAD

**Issue by jjscarpa** [merenlab/anvio#526]
Feature suggestion:

Is it useful to be able to search for functions within the anvi'o interactive? Perhaps simplest to just start with COG annotations or separate each annotation source into a separate choice from the dropdown menu.  It is easy enough to search with `anvi-search-functions-in-splits` and then import the data. But as a quick search for some specific function this may be useful?

Jarrod

**Comment by ozcan** [comment]
Hi @jjscarpa,
Thank you for the suggestion, this feature will be included in next release.
