### ISSUE TITLE
Pangenomic summary does not provide row protein sequences anymore

### ISSUE THREAD

**Issue by tdelmont** [merenlab/anvio#532]
Hi, here is the way proteins sequences are reported:

<img width="984" alt="screen shot 2017-06-01 at 7 28 32 pm" src="https://cloud.githubusercontent.com/assets/8332889/26706162/c8076b76-4700-11e7-9f45-7d4c0788fd0a.png">

It seems to keep the alignment data, which is not very optimal if one just wants to get the sequence for blast, or any other downstream analysis.

Is it a bug, or done on purpose?

Tom

**Comment by meren** [comment]
It is on purpose :)
