### ISSUE TITLE
py2 / py3 problems with installation.

### ISSUE THREAD

**Issue by ctb** [merenlab/anvio#533]
anvi-self-test disagrees with setup.py:

```
% anvi-self-test
Your active Python major version ('2') is not compatible with what anvi'o expects :/ We recently switched to Python 3.
```

but

```
% grep -i python setup.py
       'Programming Language :: Python :: 2.7',
```

Also, the [install script for Ubuntu](https://gist.githubusercontent.com/meren/f1e674f774a30a209d82/raw/6675af97e89cbc67d91843e3264705e5d8332b8f/anvi-ubuntu-setup.sh) linked to from the Installation Menu/Ubuntu Recipe installs everything into Python 2 AFAICT.

**Comment by ctb** [comment]
Oh, and I get this:

```
% pip install anvio
Collecting anvio
  Using cached anvio-2.3.2.tar.gz
No files/directories in /tmp/pip-build-edqwt237/anvio/pip-egg-info (from PKG-INFO)
```

which seems likely to be a py2/py3 problem as well - I'm running pip from python version 3.5 here.

**Comment by meren** [comment]
This is why I don't like maintaining installation scripts in ad hoc places --we forget to keep them up-to-date :/ Sorry about that, the Ubuntu script clearly needs attention. As well as the `setup.py`, for which I will send a commit soon. But that description shouldn't result in the error you're getting.

The Python issue with pip is weird. Have you tried from within a virtualenv ([copy-pasta](http://merenlab.org/2016/06/26/installation-v2/#installing-the-latest-stable-release-safe-mode) for the lazy is here) just to make sure? Another option could be to try this instead to see what is really failing, I feel like it is a dependency issue .. like samtools version or something:

``` bash
pip install --verbose anvio
```

Thanks,

**Comment by ctb** [comment]
I'll write up my install, but it seems clear that it's a problem with
setup.py or the directory layout that pip expects, not something else.

I was able to install with python setup.py without a problem (well, with
problems, but they were different ones and I fixed them :).

More soon!

**Comment by meren** [comment]
by the way, @ozcan reminds me that we have an up-to-date Docker file here if you would like to copy-paste from there:

https://gist.github.com/meren/65b1f1bfea1b53e87e10f025d1e4c29a
