### ISSUE TITLE
custom angle and missing layer labels

### ISSUE THREAD

**Issue by xvazquezc** [merenlab/anvio#536]
Hi @meren,
I was preparing a figure with `anvi-interactive` and I realised that if I set a different angle the names of the layers disappear, not only from the display but they don't show when saving the svg file either.
I searched in Google Groups and Github but I couldn't find anything about it.
Is this expected?
Cheers,
Xabi

**Comment by meren** [comment]
what do you think, @ozcan? should we keep the layer labels for all angles?

**Comment by ozcan** [comment]
Hi Xabi,
Thank you for reminding. We should definitely implement this feature. I will try to include this feature in next version.
Thank you,
Ozcan

**Comment by ozcan** [comment]
This is fixed on `master`, Will be included in next release.
