### ISSUE TITLE
side panels hiding

### ISSUE THREAD

**Issue by xvazquezc** [merenlab/anvio#537]
Hi @meren,
would it be possible to set the side panels in `anvi-interactive` so they don't hide each time you redraw the graph?
Not sure if in a local installation is the same but, when accessing remotely to the server I need to click the 'Draw' button for almost any modification and it becomes quite annoying to have the left panel closing each time.
Not sure how difficult could be to implement a 'remember state' feature or a clickable option for this, but it would be nice if you could give it a thought.
Thanks again,
Xabi

**Comment by meren** [comment]
@ozcan already fixed this with the behavior you describe, Xabi. next version will have that :)

**Comment by meren** [comment]
(or you can update from the master, and you'd be golden).

**Comment by xvazquezc** [comment]
Cool! Thanks!
