### ISSUE TITLE
Space in sample metadata column names causes silent error

### ISSUE THREAD

**Issue by jmeppley** [merenlab/anvio#540]
Adding a samples database to a previously working metagenome visualization caused it to hang on the display step with no error message. The browser displays a progress bar with the Anvi'o logo and the word "Drawing..." and sits there forever. The console shows no error, but does sometimes print this message: " * Clustering of 'tnf-cov:euclidean:ward' has been requested". 

The same anvi-interactive command without the samples database (-s) displays just fine.

This is the change to the sample metadata file that fixes it for me:

```
 $ diff metadata_3.txt metadata_4.txt
1c1
< samples       C_Flux _g_m2_d
---
> samples       C_Flux_g_m2_d
```

I just removed a space from the column name. The fields are tab separated and the column name shows up correctly (with the space) in the web browser under sample sorting options.

This appeared using version 2.1.0.  I have not had a chance to reproduce with the latest code.

**Comment by meren** [comment]
Yep, I can reproduce this with current master, too :)

**Comment by meren** [comment]
more info:

space does not break things when it is in layer names:

``` bash
cd tests
sed -i '' 's/c1/c1 test/g' sandbox/files_for_manual_interactive/view_data.txt
sed -i '' 's/c1/c1 test/g' sandbox/files_for_manual_interactive/samples-information.txt
sed -i '' 's/c1/c1 test/g' sandbox/files_for_manual_interactive/samples-order.txt
./run_manual_interactive.sh
```

but adding a space for samples info attributes does break things:

``` bash
git checkout sandbox/
sed -i '' 's/numerical_01/numerical_01 test/g' sandbox/files_for_manual_interactive/samples-information.txt
./run_manual_interactive.sh
```

SAD.

**Comment by meren** [comment]
After the latest commit, this is what happens:

```
git checkout sandbox/
sed -i '' 's/numerical_01/numerical_01 test/g' sandbox/files_for_manual_interactive/samples-information.txt
./run_manual_interactive.sh

(...)

:: Generating a samples database ... ...

Samples Info Error: Well, anvi'o does not like some of the column names in your samples information
                    file. The best practice is to limit the characters that make up the column name
                    to ASCII letters, digits, and the underscore character ('_'). No spaces, or
                    funky characters unless they are necessary for various data types. Here are the
                    perpetrators: 'numerical_ 01'.
```

Thank you, John.
