### ISSUE TITLE
concatenated sequence retrieval needs trimming option 

### ISSUE THREAD

**Issue by meren** [merenlab/anvio#543]
to trim positions that are remarkably enriched with gaps and regions that are not conserved.

this says why: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2712344/

**Comment by xvazquezc** [comment]
I use BMGE (java-based) in case you want an alternative.

**Comment by meren** [comment]
I used trimal, and it is excellent. I think this would be better to outsource.
