### ISSUE TITLE
Import GO annotations from Interproscan

### ISSUE THREAD

**Issue by xvazquezc** [merenlab/anvio#545]
Hi @meren,
I have been fiddling around and I got to make a simple Shell script to get the IPRS output with `-goterms` into the anvio database. So I thought somebody would find it useful.

Note that the IPRS output was generated from this command:
``
interproscan.sh -i input.fa -b output -goterms -dp -pa -appl Pfam
``
although it should work perfectly with output from the command without specifying `-appl` too.

[iprs2anvi_go.sh](https://github.com/xvazquezc/stuff/blob/master/iprs2anvi_go.sh)

And as extra an alternate version that also parses the pathways, although I'm not a huge fan of the way IPRS annotates them..
[iprsalt2anvio.sh](https://github.com/xvazquezc/stuff/blob/master/iprsalt2anvio.sh)

Cheers,
Xabi

**Comment by meren** [comment]
Hi Xabi,

Thank you very much for sharing! 

Although I'm sure Google will cache this and it will appear in online searches, I think the discussion group would have been a very good revenue to make sure it reaches to the most people who may be looking for something like this :)


Best,
