### ISSUE TITLE
Missing hmm databases

### ISSUE THREAD

**Issue by kengcher** [merenlab/anvio#546]
Hi 

I just installed the latest version of anvio to try out the single copy gene analyses and there's only two hmms: Campbell and Rinke. Alneberg and Creevey ones are not in the repo, is there a way i can get them as well.

Thank you.

**Comment by meren** [comment]
Hi,

We scaled down to those two have the appropriate noise filtering scores. They are here in the codebase:

https://github.com/merenlab/anvio/tree/master/anvio/data/hmm

It seems the last version we had them was `v2.0.2`:

https://github.com/merenlab/anvio/tree/v2.0.2/anvio/data/hmm

You can download these directories and use them with `-H` parameter in `anvi-run-hmms` after a bit of fixing (they need to look like the new ones in the latest repo, which includes an extra file).
