### ISSUE TITLE
Structure of summarizer.Bin

### ISSUE THREAD

**Issue by ShaiberAlon** [merenlab/anvio#547]
I have a silly question for you @meren : in `summarizer.Bin`, why do you store `split_coverage_values_per_nt_dict` in `self.summary.split_coverage_values_per_nt_dict`, but store `gene_coverages` in `self.gene_coverages` (and not in `self.summary.gene_coverages`?

This is not very critical, but the reason I'm asking is because if they were both under the same thing (either `self` or `self.summary`) then it would be more similar to `ProfileSuperclass` (in which they are both under `self`).

This way any function could get one of these (`ProfileSuperclass` or `summarizer.Bin.summary`) without knowing which it is and access all these dictionaries (`gene_coverages`, `gene_detections`, `split_coverage_values_per_nt_dict`)

**Comment by ShaiberAlon** [comment]
Another thing on the same topic: in `summarizer.Bin` it is called `gene_coverages` / `gene_detection` and in `ProfileSuperclass` it is called `gene_coverages_dict` / `gene_detection_dict`. Also here consistency would be useful.

In fact, I see that both `gene_coverages` and `gene_coverages_dict` exist under `summarizer.Bin`, and I'm not sure what the difference is.

**Comment by ShaiberAlon** [comment]
Ok, so now I understand that this was my mistake: `self.summary.split_coverage_values_per_nt_dict`, `self.summary.gene_coverages`, `self.summary.gene_detection` refer to the data from the profile database (i.e. of ALL splits and not just those that are in the bin), and `bin.*` refers to bin-specific data.

I still think it is a good idea to change `self.gene_coverages`, `self.gene_detection` to `self.gene_coverages_dict`, `self.gene_detection_dict` respectively in `summarizer.Bin`.

**Comment by meren** [comment]
I don't know if this is still relevant. We changed the design slightly, and we no longer have `gene_coverages`, or `gene_detection` dicts in ProfileSuper and instead we have a `gene_level_coverage_stats_dict` that describes `mean_coverage`, `detection`, `non_outlier_mean_coverage`, and `non_outlier_coverage_std` per `gene_caller_id` and `sample_name`.

**Comment by ShaiberAlon** [comment]
I'll keep this in mind as I go, but I definitely agree it is safe to close this issue.
