### ISSUE TITLE
anvi-export-pc-alignment does not concatenate some single calls

### ISSUE THREAD

**Issue by rbartelme** [merenlab/anvio#548]
Running the 2.3.2-master, I had anvio skip PC's in a bin that actually had single gene calls resulting in an empty fasta file.

**Comment by meren** [comment]
Hi Ryan,

I just checked this, and everything seems to be working expectedly :)

Although, I made a commit to the repository to make sure if there are no PCs left, the FASTA file is not going to be generated at all.
