### ISSUE TITLE
Export of gff and/or gbk files from Anvio 

### ISSUE THREAD

**Issue by rbeinart** [merenlab/anvio#551]
Hello,

It would be great to have the option to export the Prodigal annotations done through Anvio as gff and/or gbk files. Even better if the annotations that are done in Anvio or imported into Anvio could be exported as part of this file.

Thank you!
-Roxanne-

**Comment by meren** [comment]
`anvio.dbops.ContigsSuperclass` has a member function `gen_FASTA_file_of_sequences_for_gene_caller_ids` that is primarily used by the program `anvi-get-dna-sequences-for-gene-calls` to export gene calls in FASTA format.

I guess a reasonable strategy would be to add another function in `anvio.dbops.ContigsSuperclass` like `gen_GFF3_file_of_sequences_for_gene_caller_ids`, and add a flag to the `anvi-get-dna-sequences-for-gene-calls` (something like `--export-gff3`) to take care of this.

We may also need to consider coming up with a better design. Because the way `anvi-get-dna-sequences-for-gene-calls` works is much different than the way `anvi-get-aa-sequences-for-gene-calls` works. But this could be a discussion for later :)


2 cents.

**Comment by gkmngrgn** [comment]
@meren Aah, sorry for removing whitespaces. It's my editor's bullshit. Can you do a review for my method? I didn't test this code yet, but I think to progress like this. Thanks.

**Comment by meren** [comment]
Hi @gkmngrgn I just realized something :/ Now I can do this, and get a proper GFF file:

    anvi-get-dna-sequences-for-gene-calls -c CONTIGS.db -o sequences.gff --export-gff

While looking at the output and reading more about GFF, I am realizing that the right place to add this flag is `anvi-export-gene-calls` :( It is OK for `anvi-get-dna-sequences-for-gene-calls` to report only FASTA files for gene sequences (as the name suggests). But currently `anvi-export-gene-calls` only exports a TAB-delimited file only anvi'o recognizes for gene calls, and adding the `--export-gff` flag for that program makes much more sense.

This one,

```
anvi-export-gene-calls -c CONTIGS.db -o gene_calls.txt
```

Produces this one:

```
head gene_calls.txt
gene_callers_id	contig	start	stop	direction	partial	source	version
0	204_10M_MERGED.PERFECT.gz.keep_contig_878	0	933	f	1	prodigal	v2.6.2
1	204_10M_MERGED.PERFECT.gz.keep_contig_878	1113	1677	f	0	prodigal	v2.6.2
2	204_10M_MERGED.PERFECT.gz.keep_contig_878	1698	2142	f	0	prodigal	v2.6.2
3	204_10M_MERGED.PERFECT.gz.keep_contig_878	2229	3447	f	0	prodigal	v2.6.2
4	204_10M_MERGED.PERFECT.gz.keep_contig_878	3439	6820	f	0	prodigal	v2.6.2
5	204_10M_MERGED.PERFECT.gz.keep_contig_878	6819	7761	f	0	prodigal	v2.6.2
6	204_10M_MERGED.PERFECT.gz.keep_contig_878	7821	8409	f	0	prodigal	v2.6.2
7	204_10M_MERGED.PERFECT.gz.keep_contig_878	8496	10350	r	0	prodigal	v2.6.2
8	204_10M_MERGED.PERFECT.gz.keep_contig_878	10570	10855	f	0	prodigal	v2.6.2
```

And this one,

```
anvi-get-dna-sequences-for-gene-calls -c CONTIGS.db -o sequences.gff --export-gff3
```

Produces this one:

```
$ head sequences.gff
##gff-version 3
0	IGS	204_10M_MERGED.PERFECT.gz.keep_contig_878	1	933	.	.	.	ID=0
1	IGS	204_10M_MERGED.PERFECT.gz.keep_contig_878	1	564	.	.	.	ID=1
2	IGS	204_10M_MERGED.PERFECT.gz.keep_contig_878	1	444	.	.	.	ID=2
3	IGS	204_10M_MERGED.PERFECT.gz.keep_contig_878	1	1218	.	.	.	ID=3
4	IGS	204_10M_MERGED.PERFECT.gz.keep_contig_878	1	3381	.	.	.	ID=4
5	IGS	204_10M_MERGED.PERFECT.gz.keep_contig_878	1	942	.	.	.	ID=5
6	IGS	204_10M_MERGED.PERFECT.gz.keep_contig_878	1	588	.	.	.	ID=6
7	IGS	204_10M_MERGED.PERFECT.gz.keep_contig_878	1	1854	.	.	.	ID=7
8	IGS	204_10M_MERGED.PERFECT.gz.keep_contig_878	1	285	.	.	.	ID=8
```

It would have been much more intuitive and meaningful if we got this output when we run this one:

```
anvi-export-gene-calls -c CONTIGS.db -o gene_calls.gff  --export-gff3
```

Addressing this will require (1) a new function in `utils` module such as `store_genes_in_contigs_dict_as_GFF`, (2) moving over the flag `--export-gff3` from `anvi-get-dna-sequences-for-gene-calls` to `anvi-export-gene-calls`, (3) removing the GFF function in `dbops`, and (4) updating the tests. I was going to do this myself, but I thought you would like to be on top of this :/ I apologize for this, and I hope most of your code can be used in that function.

Let me know if you would like me to do this instead.


Best,

**Comment by gkmngrgn** [comment]
@meren okay, better. I'll do the changes for your review. Thanks!

**Comment by harish0201** [comment]
@meren 

I have a doubt regarding the output GFF. 

Why does every gene-call start from position 1? I'm asking this because when I exported out using anvi-export-gene-calls, I get different coordinates which shows prediction from prodigal as compared to export by "anvi-get-sequences-for-gene-calls" options.

I believe it would be much better that "anvi-get-sequences-for-gene-calls"  can directly output a formatted gff having the gene co-ordinates rather than the sequence lengths.

> Hi @gkmngrgn I just realized something :/ Now I can do this, and get a proper GFF file:
> 
> ```
> anvi-get-dna-sequences-for-gene-calls -c CONTIGS.db -o sequences.gff --export-gff
> ```
> 
> While looking at the output and reading more about GFF, I am realizing that the right place to add this flag is `anvi-export-gene-calls` :( It is OK for `anvi-get-dna-sequences-for-gene-calls` to report only FASTA files for gene sequences (as the name suggests). But currently `anvi-export-gene-calls` only exports a TAB-delimited file only anvi'o recognizes for gene calls, and adding the `--export-gff` flag for that program makes much more sense.
> 
> This one,
> 
> ```
> anvi-export-gene-calls -c CONTIGS.db -o gene_calls.txt
> ```
> 
> Produces this one:
> 
> ```
> head gene_calls.txt
> gene_callers_id	contig	start	stop	direction	partial	source	version
> 0	204_10M_MERGED.PERFECT.gz.keep_contig_878	0	933	f	1	prodigal	v2.6.2
> 1	204_10M_MERGED.PERFECT.gz.keep_contig_878	1113	1677	f	0	prodigal	v2.6.2
> 2	204_10M_MERGED.PERFECT.gz.keep_contig_878	1698	2142	f	0	prodigal	v2.6.2
> 3	204_10M_MERGED.PERFECT.gz.keep_contig_878	2229	3447	f	0	prodigal	v2.6.2
> 4	204_10M_MERGED.PERFECT.gz.keep_contig_878	3439	6820	f	0	prodigal	v2.6.2
> 5	204_10M_MERGED.PERFECT.gz.keep_contig_878	6819	7761	f	0	prodigal	v2.6.2
> 6	204_10M_MERGED.PERFECT.gz.keep_contig_878	7821	8409	f	0	prodigal	v2.6.2
> 7	204_10M_MERGED.PERFECT.gz.keep_contig_878	8496	10350	r	0	prodigal	v2.6.2
> 8	204_10M_MERGED.PERFECT.gz.keep_contig_878	10570	10855	f	0	prodigal	v2.6.2
> ```
> 
> And this one,
> 
> ```
> anvi-get-dna-sequences-for-gene-calls -c CONTIGS.db -o sequences.gff --export-gff3
> ```
> 
> Produces this one:
> 
> ```
> $ head sequences.gff
> ##gff-version 3
> 0	IGS	204_10M_MERGED.PERFECT.gz.keep_contig_878	1	933	.	.	.	ID=0
> 1	IGS	204_10M_MERGED.PERFECT.gz.keep_contig_878	1	564	.	.	.	ID=1
> 2	IGS	204_10M_MERGED.PERFECT.gz.keep_contig_878	1	444	.	.	.	ID=2
> 3	IGS	204_10M_MERGED.PERFECT.gz.keep_contig_878	1	1218	.	.	.	ID=3
> 4	IGS	204_10M_MERGED.PERFECT.gz.keep_contig_878	1	3381	.	.	.	ID=4
> 5	IGS	204_10M_MERGED.PERFECT.gz.keep_contig_878	1	942	.	.	.	ID=5
> 6	IGS	204_10M_MERGED.PERFECT.gz.keep_contig_878	1	588	.	.	.	ID=6
> 7	IGS	204_10M_MERGED.PERFECT.gz.keep_contig_878	1	1854	.	.	.	ID=7
> 8	IGS	204_10M_MERGED.PERFECT.gz.keep_contig_878	1	285	.	.	.	ID=8
> ```
> 
> It would have been much more intuitive and meaningful if we got this output when we run this one:
> 
> ```
> anvi-export-gene-calls -c CONTIGS.db -o gene_calls.gff  --export-gff3
> ```
> 
> Addressing this will require (1) a new function in `utils` module such as `store_genes_in_contigs_dict_as_GFF`, (2) moving over the flag `--export-gff3` from `anvi-get-dna-sequences-for-gene-calls` to `anvi-export-gene-calls`, (3) removing the GFF function in `dbops`, and (4) updating the tests. I was going to do this myself, but I thought you would like to be on top of this :/ I apologize for this, and I hope most of your code can be used in that function.
> 
> Let me know if you would like me to do this instead.
> 
> Best,

**Comment by meren** [comment]
Yes, that doesn't look alright. @brymerr921, do you have any input by any chance?

Best,

**Comment by harish0201** [comment]
Not @brymerr921 but here are my outputs:

1. Running ````anvi-get-dna-sequences-for-gene-calls -c CONTIGS.db -o sequences.gff --export-gff3````

[head.gff.txt](https://github.com/merenlab/anvio/files/2487345/head.gff.txt)

````
##gff-version 3
0	IGS	c_000000000001	1	309	.	.	.	ID=0
1	IGS	c_000000000002	1	312	.	.	.	ID=1
2	IGS	c_000000000003	1	405	.	.	.	ID=2
3	IGS	c_000000000004	1	177	.	.	.	ID=3
4	IGS	c_000000000005	1	312	.	.	.	ID=4
5	IGS	c_000000000006	1	264	.	.	.	ID=5
6	IGS	c_000000000006	1	63	.	.	.	ID=6
7	IGS	c_000000000007	1	348	.	.	.	ID=7
8	IGS	c_000000000008	1	165	.	.	.	ID=8
````

2. Running ```anvi-export-gene-calls -c contigs.db -o calls.txt```

[head.calls.txt](https://github.com/merenlab/anvio/files/2487366/head.calls.txt)

```
gene_callers_id	contig	start	stop	direction	partial	source	version
0	c_000000000001	0	309	f	1	prodigal	v2.6.3
1	c_000000000002	5	317	r	1	prodigal	v2.6.3
2	c_000000000003	2	407	r	1	prodigal	v2.6.3
3	c_000000000004	0	177	r	1	prodigal	v2.6.3
4	c_000000000005	0	312	r	1	prodigal	v2.6.3
5	c_000000000006	2	266	f	1	prodigal	v2.6.3
6	c_000000000006	265	328	f	1	prodigal	v2.6.3
7	c_000000000007	0	348	f	1	prodigal	v2.6.3
8	c_000000000008	2	167	f	1	prodigal	v2.6.3
```

which I later parsed to get a gff.

Also one more question from case 2, do I label these as genes?

I wonder if there is an issue with obtaining the gene-calls from the 1st method? I'm trying out prokka as well to see how close the 2nd approach is matching (though I do know that prokka runs prodigal as well)

**Comment by meren** [comment]
I am asking @brymerr921's input because he contributed code to the GFF export script.

**Comment by harish0201** [comment]
Ahh, my bad!
