### ISSUE TITLE
anvi-get-sequences-for-hmm-hits asks for -o when -l or -L

### ISSUE THREAD

**Issue by xvazquezc** [merenlab/anvio#555]
Hi @meren,
I realised that the output flag `-o` is required even when `-l` or `-L` are used.
Even if a file is provided to `-o` in those cases, no file is produced, only `STDOUT`.
Not sure if you are aware of this behaviour, but just in case.
Cheers,
Xabi

**Comment by meren** [comment]
Hi Xabi,

I fixed that behavior in master a couple of weeks ago, and it will be in the next stable release :)

Thank you!
