### ISSUE TITLE
"ModuleNotFoundError: No module named 'six'" after homebrew installation on OSX

### ISSUE THREAD

**Issue by damurdock** [merenlab/anvio#561]
Installation on OSX El Capitan (10.11.6) via Homebrew completes without error, however attempting to run `anvi-self-test` or any other anvi'o command fails with `ModuleNotFoundError: No module named 'six'`. It appears that anvi'o is installing in its own virtualenv, as installing six via the system python3 doesn't affect anything. 

I was able to get anvi'o running in two different ways. The first was by modifying the anvio.rb recipe to include the `resource "six"` directive from [this recipe](https://github.com/Homebrew/homebrew-core/blob/master/Formula/mesos.rb) (chosen randomly from google) and reinstalling after a `brew cleanup -s`. That threw a 404 error when downloading the bottle and forced a recompile, but the resulting anvi'o installation appears to work fine. Alternatively, I was able to install anvi'o via the normal recipe, then manually run `/usr/local/Cellar/anvio/2.3.2_1/libexec/bin/pip install six` to install six within anvio's venv. This also appears to run correctly.

**Comment by meren** [comment]
Thank you very much for the detailed report, Duncan!

I think we fixed this problem, but I will wait @ozcan to say the final word :)
