### ISSUE TITLE
The CONCOCT module could not be imported

### ISSUE THREAD

**Issue by shekas3** [merenlab/anvio#567]
Hi,
I installed anvio-2.4.0 under a virtualenv on my UBUNTU 16.10. Everything works fine except CONCOCT. I installed gsl already and it's on my $PATH.  Does anyone know how can I fix this? Should I install CONCOCT on my machine?

 Here are the warnings :
WARNING
===============================================
The CONCOCT module could not be imported :( Anvi'o will still be able to perform
the merging, however, the unsupervised binning results will not be available to
you in the resulting merged profile database. This is what the module was upset
about: '''libgsl.so.23: cannot open shared object file: No such file or
directory''', in case you would like to fix this problem.

and this one :
Config Error: CONCOCT is not a valid collection ID. See a list of available ones with '--list-
              collections' flag 

Thanks,
Sharok

**Comment by Stefano04** [comment]
Hey @shekas3 , did you manage to find a solution to your problem? I have got the very same error. 

Thanks in advance, 

Stefano
