### ISSUE TITLE
Location of ncbi cogs dir from environment variable

### ISSUE THREAD

**Issue by mbl-jbpc-richardfox** [merenlab/anvio#570]
It seems that if you put the NCBI cogs directory anyhere but where Anvio thinks it should be, you must always remember to add arguments telling anvio where it is. Instead of requiring this extra step on each invocation of the relevant program(s), I think it would increase usability if it were able to be determined by the value of an environment variable. That way a sysadmin could set it, for example, and then it will work for everybody every time and users need not know anything about where the COG files are unless they want to customize their process for some reason.

**Comment by meren** [comment]
This is a very good suggestion, Rich. Thank you very much!

**Comment by meren** [comment]
Done :) 

This is how it goes now; default:

```
$ anvi-run-ncbi-cogs -c CONTIGS.db
COG data directory ...........................: /Users/meren/github/anvio/anvio/data/misc/COG
COG data source ..............................: The anvi'o default. 
```

command line param:

```
$ anvi-run-ncbi-cogs -c CONTIGS.db --cog-data-dir '/tmp/blah'
COG data directory ...........................: /tmp/blah
COG data source ..............................: The command line parameter.
```

environmental variable:

```
$ ANVIO_COG_DATA_DIR="/tmp/COGs" anvi-run-ncbi-cogs -c CONTIGS.db
COG data directory ...........................: /tmp/COGs
COG data source ..............................: The environmental variable.
```

I hope this looks OK.
