### ISSUE TITLE
Error installing Anvi'o: pip install numpy fails inside virtual environment

### ISSUE THREAD

**Issue by tberben** [merenlab/anvio#571]
I am trying to install Anvi'o on the linux server at my institute using the instructions in the [Anvi'o manual](http://merenlab.org/2016/06/26/installation-v2/#installation-with-varying-levels-of-pain). I cloned the git codebase and, using Python 3.4, created the virtual environment using `python -m venv ~/virtualenv/anvio` followed by `source ~/virtualenv/anvio/bin/activate`. So far so good, but when I change directory to ~/virtualenv/anvio and run `pip install -r requirements.txt` I get a string of exceptions while it's installing NumPy that I have trouble interpreting and solving. The pip.log file is attached.

I have tried deleting the directory completely and starting anew, but the problem persists.

[pip.txt](https://github.com/merenlab/anvio/files/1217440/pip.txt)

**Comment by meren** [comment]
Hi @tberben,

To me this seems like a Python related issue. Please upgrade your Python to 3.6.* and try again.


Best,
