### ISSUE TITLE
clustering configurations for a single profile

### ISSUE THREAD

**Issue by ShaiberAlon** [merenlab/anvio#572]
When using anvi-interactive with a single profile, why are only two views available?
Why not add a clustering according to coverage only?

Another thing is that I worry that the clustering of a single profile in it's current configuration gives too much of the "power" to coverage. At least my experience so far as shown that the view using `tnf-ab-cov` seems to be following the coverage of the contigs "too strongly" (this is of course my observation, and maybe a more serious inspection is needed, but if we would have a `coverage` clustering configuration then we could compare it to the existing ones and it could help).

Take this example:
I choose this bin when viewing the `tnf-ab-cov`
![image](https://user-images.githubusercontent.com/17661044/29220494-d2affc98-7e80-11e7-895c-53a5362f455d.png)

And then I switch to `Sequence composition`:
![image](https://user-images.githubusercontent.com/17661044/29220536-f77f7936-7e80-11e7-863b-f745b7b405f2.png)

The contigs of the bin seem to be all over the place. I don't think I would expect this.

**Comment by meren** [comment]
You can copy one of those configurations and edit it. `anvi-experimental-organization` will add new clustering results into the DB with your edited versions. I agree that the second view is concerning, and you can see that that is going to be the outcome from the first one having GC-content all over the place. Maybe we should replace tnf-ab-cov with tnf-ab or tnf-cov only.
