### ISSUE TITLE
Stuck on Drawing!

### ISSUE THREAD

**Issue by susheelbhanu** [merenlab/anvio#576]
Hey Ozcan, 

This is probably trivial, but anytime I change the colors in the intensity section, and hit 'Draw' the interactive site is stuck on 'Drawing' (screenshot attached). 
![screen shot 2017-08-17 at 11 17 27 am](https://user-images.githubusercontent.com/9979661/29422486-fd93f7e0-833d-11e7-89de-ac7a90db3c96.png)

I'm running the following (files attached): anvi-interactive -t Zymo_tree.txt -d Zymo_Anvio.txt -p profile.db --title 'ZymoBiomics vs Aaron' --manual

[Zymo_Anvio.txt](https://github.com/merenlab/anvio/files/1231931/Zymo_Anvio.txt)
[Zymo_tree.txt](https://github.com/merenlab/anvio/files/1231932/Zymo_tree.txt)

Is it something to with my cache on the browser? Or is something wrong with the actual script?

Thank you for your help!

-Susheel Busi

**Comment by ozcan** [comment]
Hi Susheel,

Is there anything on Javascript console `View > Developer > Javascript Console` ?

Thank you very much.

**Comment by susheelbhanu** [comment]
This is what I found, Ozcan. 

bin.js?rand=05ae5fbf0bb5d3620ad276c11cb561a7:279 Uncaught TypeError: Cannot read property 'ancestor' of undefined
    at rebuildIntersections (bin.js?rand=05ae5fbf0bb5d3620ad276c11cb561a7:279)
    at Object.success (main.js?rand=f1c3ccb78e33d419e99a4779cedf94ea:2174)
    at j (jquery.js:3148)
    at Object.fireWith [as resolveWith] (jquery.js:3260)
    at x (jquery.js:9314)
    at XMLHttpRequest.b (jquery.js:9718)

I closed the browser, cleared cache, and reopened it by running the same analysis. The problem seems to have gone away. Must have been something on my end, since I was trying a few different datasets. 

Sorry for the trouble and thanks again!!

**Comment by meren** [comment]
If find this very interesting :)

**Comment by ozcan** [comment]
Hi Susheel,
It looks like this problem is not related with intensity but related with selections (bins). I think we recently fixed that bug [here](https://github.com/merenlab/anvio/commit/36f8304410fa3fce368de1b6d09b329bb0cb4737). 

If you want you can download this bins.js file from master repository and replace your local installation or you can install master version

All the best,
Ozcan

**Comment by susheelbhanu** [comment]
Brilliant, thank you very much! I am not yet adept at dealing with the master version, so for now will only download the bins.js file. 

Btw, you have a typo (see attached; word-> "plase"). Don't think anybody will care, but it was driving me nuts :)

![image](https://user-images.githubusercontent.com/9979661/29428874-5ad1dee8-8354-11e7-9cf4-309c4a04ef63.png)

Thanks again for looking into the issue and responding so quickly!

**Comment by ozcan** [comment]
Hello again Susheel,
I realized that you also need to replace drawer.js, sorry for the inconvenience.

**Comment by susheelbhanu** [comment]
No worries mate. Thank you very much!!
