### ISSUE TITLE
bug anvi-summarize

### ISSUE THREAD

**Issue by wegnerce** [merenlab/anvio#578]
Dear anvio team,
I noticed a bug after calling anvi-summarize. In the resulting static .html, under "Summary" there are links given to the summary as tab-delimited file and and the number of reads mapped. The link to the tab-delimited summary file is referring to the static .html but not to the tab-delimited file.

Thanks for all your efforts

Carl-Eric

**Comment by meren** [comment]
Yes, that was definitely a bug, and it is now fixed! Thank you very much :)
