### ISSUE TITLE
AttributeError when creating blank profile

### ISSUE THREAD

**Issue by GeoMicroSoares** [merenlab/anvio#580]
Hello there,

Running anvi'o 2.4.0 (conda create -n anvio240 -c bioconda -c conda-forge python=3.5.4 gs) on an Ubuntu 14.04 here. Is this a matter of updating a python library?

Following http://merenlab.org/2016/06/06/working-with-contigs-only/ I can't seem to create an empty profile database running ```anvi-profile -c Desktop/ynys_blank.db -o ynys_blank -S ynys_blank --blank-profile```

Complete error output:
```[01 Sep 17 09:42:32 Loading contig sequences] Reading contig sequences                                                                                       Traceback (most recent call last):
  File "/home/andre/miniconda3/envs/anvio240/bin/anvi-profile", line 71, in <module>
    profiler = anvio.profiler.BAMProfiler(args)
  File "/home/andre/miniconda3/envs/anvio240/lib/python3.5/site-packages/anvio/profiler.py", line 94, in __init__
    self.init_contig_sequences()
  File "/home/andre/miniconda3/envs/anvio240/lib/python3.5/site-packages/anvio/dbops.py", line 238, in init_contig_sequences
    self.contig_sequences = contigs_db.db.get_table_as_dict(t.contig_sequences_table_name, string_the_key=True)
AttributeError: 'NoneType' object has no attribute 'get_table_as_dict'

**Comment by meren** [comment]
Hi,

Can you please share your contigs.db so we can try to reproduce?

**Comment by GeoMicroSoares** [comment]
I'm so sorry. Total rookie mistake. Thought the idea was to create the profile database from a non-existing  contigs.db. Ran with my contigs.db and worked perfectly. Thanks @meren !
