### ISSUE TITLE
anvi-interactive - Connection refused error in W10 Linux Subsystem

### ISSUE THREAD

**Issue by GeoMicroSoares** [merenlab/anvio#582]
Hello there,

Running anvi'o 2.4.0 in a Ubuntu 14.04 Windows 10 Linux Subsystem, I can't seem to be able to view anvi-interactive outputs in a browser.

At first, it would only open lynx in the terminal but got it opening Chrome following instructions in https://stackoverflow.com/questions/41404536/why-is-bash-wsl-acting-like-a-webbrowser.

Now, I'm just getting a 'Connection to 0.0.0.0 failed.' error as seen below:
![image](https://user-images.githubusercontent.com/14272488/29978605-c97f05b4-8f39-11e7-8085-0cf3b67909c4.png)

anvi-self-test --suite mini runs normally with the exception that the when the browser opens the same error as above comes up.

Any thoughts?

Thanks in advance.

**Comment by ozcan** [comment]
Hi André,

Can you try `127.0.0.1:8080` instead `0.0.0.0:8080`?

**Comment by meren** [comment]
And the server is running and listening the port 8080, right?

**Comment by GeoMicroSoares** [comment]
127.0.0.1:8080 works like a charm! Thanks so much!!
