### ISSUE TITLE
issue on running cogs in anvio

### ISSUE THREAD

**Issue by hites77** [merenlab/anvio#586]
when i run the command:  anvi-run-ncbi-cogs -c seq1.db

Following error occur:
Config Error: At least one essential formatted file that is necesary for COG operations is not
              where it should be ('/home/resistance/virtual-                                  
              envs/anvio-2.4.0/lib/python3.5/site-                                            
              packages/anvio/data/misc/COG/MISSING_COG_IDs.cPickle'). You should run COG      
              setup, with the flag `--reset` if necessary, to make sure things are in order.

I have also cog setup with reset flag too but the error continue to occur. When installing cog setup only csv file get downloaded and no other file get downloaded.
Please help what to do.

**Comment by meren** [comment]
I can't reproduce this error. When I run it, it downloads everything.

**Comment by hites77** [comment]
so any possible reason for not getting full cog installation

**Comment by meren** [comment]
It may be helpful if you send the full output.

**Comment by hites77** [comment]
(anvio-2.4.0) resistance@resistance-VirtualBox ~/Desktop $ anvi-run-ncbi-cogs -c seq1.db


Config Error: At least one essential formatted file that is necesary for COG operations is not
              where it should be ('/home/resistance/virtual-                                  
              envs/anvio-2.4.0/lib/python3.5/site-                                            
              packages/anvio/data/misc/COG/MISSING_COG_IDs.cPickle'). You should run COG      
              setup, with the flag `--reset` if necessary, to make sure things are in order.

**Comment by meren** [comment]
Well, you already sent this. I meant the output from `anvi-setup-ncbi-cogs --reset`.

**Comment by hites77** [comment]
(anvio-2.4.0) resistance@resistance-VirtualBox ~/MEGAsync $ anvi-setup-ncbi-cogs --reset
COG data dir .................................: /home/resistance/virtual-envs/anvio-2.4.0/lib/python3.5/site-packages/anvio/data/misc/COG

WARNING
===============================================
This program will remove everything in the COG data directory, then download and
reformat everything from scratch.

Press ENTER to continue, or press CTRL + C to cancel...

Traceback (most recent call last):
  File "/home/resistance/virtual-envs/anvio-2.4.0/bin/anvi-setup-ncbi-cogs", line 45, in <module>
    setup.create()
  File "/home/resistance/virtual-envs/anvio-2.4.0/lib/python3.5/site-packages/anvio/cogs.py", line 395, in create
    self.get_raw_data()
  File "/home/resistance/virtual-envs/anvio-2.4.0/lib/python3.5/site-packages/anvio/cogs.py", line 549, in get_raw_data
    utils.download_file(self.files[file_name]['url'], file_path, progress=progress, run=run)
  File "/home/resistance/virtual-envs/anvio-2.4.0/lib/python3.5/site-packages/anvio/utils.py", line 1697, in download_file
    file_size = int(response.headers['Content-Length'])
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

**Comment by meren** [comment]
Are you sure you have internet access in this VirtualBox?

**Comment by hites77** [comment]
yes

**Comment by meren** [comment]
Then I have no suggestion. VirtualBox solutions come with their own luggage of technical issues, and it is hard easy to recapitulate and/or investigate them. Sorry :(

**Comment by hites77** [comment]
can in run anvio without creating virtual environment in linux

**Comment by meren** [comment]
I don't know, you tell me :)

I suggest you to try Docker instead: http://merenlab.org/2015/08/22/docker-image-for-anvio/
