### ISSUE TITLE
Add flag for exporting HMM sequences only present in all external genomes

### ISSUE THREAD

**Issue by rbartelme** [merenlab/anvio#588]
Please add a flag to anvi-get-sequences-for-hmm-hits to specify exporting only those sequences present in all external genomes supplied in external-genomes.txt

This would significantly help with concatenation of nucleotide or amino acid sequences from this command.

**Comment by meren** [comment]
I think this #590 solves this now, Ryan. Can you please take a look?

**Comment by rbartelme** [comment]
Left my comment on #590

**Comment by meren** [comment]
This is what we have currently:

> If you ​set `--max-number-of-genes-missing` to `0`, for your 30 genomes, only the GENOMES that have every gene in your list will remain in the analysis.

But this is what you want:

> if you set `--another-flag` to `0` for your 30 genomes, only the GENES in your list that appear in every genome you are working with will remain in the analysis.

Is this correct?

**Comment by rbartelme** [comment]
I was thinking that the --another-flag would be set to 30...as in filter out the genes from the hmm that do not appear 30 times.

campbell_hmm_gene	number_of_genomes_containing_gene_in_db
Arg_tRNA_synt_N	30
B5	22
CTP_synth_N	30
CoaE	27

The hypothetical flag would filter out genes B5, and CoaE because they do not appear in all the genomes in the db.

**Comment by meren** [comment]
> I was thinking that the --another-flag would be set to 30...as in filter out the genes from the hmm that do not appear 30 times.

But there is a difference between a gene appearing 30 times, and a gene appearing in 30 genomes. If you set the number based on the appearance of the gene, you may end up with a gene that appears in a single genome 30 times, which is not very useful for anything phylogenomics.

**Comment by rbartelme** [comment]
Ahh I see, yes, a gene appearing in 30 genomes is what I was trying to articulate

**Comment by meren** [comment]
I see. I will work on this.

**Comment by rbartelme** [comment]
Thank you!

**Comment by meren** [comment]
Hey Ryan,

Now `anvi-get-sequences-for-hmm-hits` has a new flag, `--min-num-bins-gene-occurs`.

I would be very happy if you can update your repo from `master`, read the new help menu, and test the new flag. I would like to know whether it works properly, and whether it solves your issue.

Best,

**Comment by rbartelme** [comment]
This works beautifully. 61 genes in my dataset "gon' buhbye".

**Comment by meren** [comment]
Excellent! Did you have a chance to double-check whether it is working as expected? I tested it, but it is always better to have someone else vet the code. You are the very first person who ever uses it for production, so please be cautious and let me know if there are some glitches. I am closing this issue for now.

Thanks,
