### ISSUE TITLE
Line graphs

### ISSUE THREAD

**Issue by meren** [merenlab/anvio#592]
I think line graphs could be much more visually pleasing and helpful if the shade was only under the curve:

![image](https://user-images.githubusercontent.com/197307/30657590-b7d9c0c4-9dfd-11e7-8848-c358fc16c3a0.png)

2 cents :)

**Comment by meren** [comment]
There is no rush or anything. I just didn't want us to forget. It may f'up the performance when there are crazy number of items, too. I haven't really thought about that aspect either.

**Comment by ozcan** [comment]
So now we can change background colors using second color box like we do in intensity mode, also background also cover the area below the line.
![screen shot 2017-09-20 at 2 41 47 pm](https://user-images.githubusercontent.com/940884/30664034-049cccd0-9e12-11e7-9e26-85f0605a7ecc.png)
![screen shot 2017-09-20 at 2 41 52 pm](https://user-images.githubusercontent.com/940884/30664038-0649806e-9e12-11e7-941c-386c39ecb8ec.png)
