### ISSUE TITLE
Going from anvi'o to DESMAN

### ISSUE THREAD

**Issue by meren** [merenlab/anvio#593]
Going from anvi'o to DESMAN (https://github.com/chrisquince/DESMAN) to deconvolute MAGs with enough variation should be seamless. This may require changes in the DESMAN codebase as well for maximum elegance.

@ozcan, please consider getting some familiarity with DESMAN, so we can sit together and design this the right way :)

**Comment by vaxherra** [comment]
Hi, 
Do you have a workflow that takes MAGs produced in Tara Oceans plankton microbiome survey, that uses DESMAN to come up with the final results?

**Comment by ozcan** [comment]
I have tried DESMAN today and the main problem I noticed is DESMAN uses `Python 2` so It seems we can not have a seamless workflow since it is not possible to install both of them in same virtualenv. We still can generate output files DESMAN requires as an input.

**Comment by chrisquince** [comment]
I would be willing to rewrite into python 3 if it will make integration easier?

**Comment by ozcan** [comment]
@chrisquince, That would be very good, also I would like to help with that. Initially we switched to Python 3 because snakemake does not supports Python 2 but In DESMAN you have snakemake, how does it work at the moment? Do you guys use virtualenv or just install everything to system-wide?

**Comment by chrisquince** [comment]
Yes it is rather clunky we create two conda environments for Python 2 and 3 and we switch between them within the snakemake. OK lets do it! I actually do not think it will be that hard and I can rationalise some of the code as I go.

**Comment by vnsriniv** [comment]
Hi all,

I was wondering if there was any update on this? I am starting to work with DESMAN and would love to know if there is an easier way to export anvio binning results to DESMAN. 

Thanks! 
Varun
