### ISSUE TITLE
Metagenomics: update needed for the "generate a static summary page" option

### ISSUE THREAD

**Issue by tdelmont** [merenlab/anvio#599]
Hi all,

I just realized that when generating the summary from the interface (metagenomic mode), gene coverage and detection is not processed. We use the flag "--init-gene-coverages" for the manual command "anvi-summarize".

So, could it be possible to allow 2 summary options in the interface: "rapid" and "full (includes gene coverage and detection)"?

Because if not, then the people that use the interface for summary will never know this very cool option (contribution of Alon) is possible.

Tom

**Comment by meren** [comment]
We already have a quick option, and people who are interested in gene coverages will realize it's missing from the output when they browse the static summary page, and re-summarize their collection even if they were too lazy to read the help menu prior to summary.
