### ISSUE TITLE
Anvio on AWS EC2 not able to use interactive mode

### ISSUE THREAD

**Issue by halexand** [merenlab/anvio#600]
Hello, 

I am using Anvio 2.4.0 to run the following command on an amazon EC2 instance: 

`anvi-interactive -p MERGED-SAMPLES/PROFILE.db -c anvio-contigs.db
`
It runs and throws the following errors: 
`Alert!: Unable to connect to remote host.
** Bad HTML!! Use -trace to diagnose. **
`
And then takes me to an interactive page that looks like the following. 

<img width="602" alt="screenshot 2017-09-29 00 05 01" src="https://user-images.githubusercontent.com/7264618/31004601-e62078a8-a4a9-11e7-9a74-b922649c3a65.png">

If I quit out of the page, I can access the interactive page through the provided port 8080. However, I can't interact with the page-- it gets stuck 'Drawing...'. 

Any thoughts? 

Thank you!

**Comment by ozcan** [comment]
Hello @halexand,
Do you see anything if you open `View > Developer > JavaScript Console` on Chrome?

**Comment by halexand** [comment]
Hi @ozcan, 

I see the following: 
<img width="552" alt="screenshot 2017-09-29 07 48 47" src="https://user-images.githubusercontent.com/7264618/31021438-af8a4616-a4ea-11e7-83c3-4c01919dda9e.png">

As an aside, I created a new conda environment with v. 2.3.2. There I get the same printed error message but the interactive interface doesn't freeze while drawing and I can interact with it.

**Comment by halexand** [comment]
Sorry-- hit the wrong button! Still open.

**Comment by ozcan** [comment]
Hi @halexand,
I suspect this problem happens because your layer names is longer than the plot, we recently fixed this bug on development version and we will release it soon. As a workaround you can try to increase the `Radius` value in `Show additional settings` section

**Comment by halexand** [comment]
Ah, interesting! Thank you. I suppose that as it works with 2.3.2 I will just wait until the next version is released. Good to know the workaround though!

**Comment by ozcan** [comment]
We just released new version, this should have fixed now.
