### ISSUE TITLE
anvi-display-contig-stats needs improvements

### ISSUE THREAD

**Issue by ozcan** [merenlab/anvio#613]
- It should be able to print table to file
- There should be an option to disable human readable base numbers (mbp, kbp)
- Numbers in the table should be colored according to a color scale (ex: green for low, red for high)

**Comment by jvineis** [comment]
Also, the "N" stats have no annotation of Kbp, Mbp etc.

**Comment by jvineis** [comment]
For phylogenetic analysis reasons, it would be great if the user could see which of the single copy hmm hits are common among all MAGs/SAGs/REFs/Othergenomethings.

**Comment by ozcan** [comment]
Some of the things mentioned here addressed in this commit:  https://github.com/merenlab/anvio/commit/8cc7f882d57129a585591dfe1b980d0a07a5f702
