### ISSUE TITLE
Nucmer-based removal of redundant MAGs

### ISSUE THREAD

**Issue by wegnerce** [merenlab/anvio#614]
Dear anvio team,

This post is not directly about anvio, and I'm not sure it's worth mentioning.

I'm currently playing around with the nucmer-based workflow to identify and remove redundant MAGs that you introduced in the bioinformatics workflow to recover and characterize MAGs from the TARA Oceans metagenomic co-assemblies (http://merenlab.org/data/2017_Delmont_et_al_HBDs/#identification-and-removal-of-redundant-mags).

The 01-gen-nucmer-jobs.py script was throwing an error: 
```bash
Traceback (most recent call last):
  File "01-gen-nucmer-jobs.py", line 32, in <module>
    while fasta.next():
AttributeError: 'SequenceSource' object has no attribute 'next'
```
I had a look at the script and the respective line needs a tiny fix (fasta.next() --> next(fasta)).

```python
#!/usr/bin/env python

# you run this first:
#
#    python 01-gen-nucmer-jobs.py affiliations.txt MAGs_input_dir 
#

import os
import sys
import anvio.fastalib as u
import anvio.utils as utils

affiliations_input = utils.get_TAB_delimited_file_as_dictionary(sys.argv[1], no_header=True, column_names=['item', 'affiliation'])
affiliations_dict = {}

for mag in affiliations_input:
    affiliation =  affiliations_input[mag]['affiliation']
    if not affiliation in affiliations_dict:
        affiliations_dict[affiliation] = [mag]
    else:
        affiliations_dict[affiliation].append(mag)

for affiliation in affiliations_dict:
    db_path = '%s.fa' % affiliation
    output = open(db_path, 'w')
    for mag in affiliations_dict[affiliation]:
        path = '%s/%s.fa' % (sys.argv[2], mag)

        fasta = u.SequenceSource(path)

        seq = ''
        #while fasta.next():
        while next(fasta): #Python3 iterator syntax
            seq += fasta.seq

        output.write('>%s\n' % mag)
        output.write('%s\n' % seq)

        print('nucmer --minmatch 500 --prefix %s %s %s' % (os.path.join('hits', mag), path, db_path))
    output.close()
```
The nucmer-based strategy to identify and remove redundancy is a cool idea, did you ever compare this with the respective functionality implemented in checkm?

Have a nice weekend

Carl-Eric

**Comment by meren** [comment]
Hi Carl-Eric,

Thanks for the report. Unfortunately the script at that address, which is a reproducible workflow document for a specific version of anvi'o, will continue working without that fix. Which creates an interesting versioning issue for that document. We need to think about a more general solution...

> did you ever compare this with the respective functionality implemented in checkm?

I didn't know CheckM could collapse redundancy! We should definitely look into this :)


Thank you,

**Comment by brymerr921** [comment]
Another great tool to collapse redundant mags is [dRep](http://www.nature.com/ismej/journal/vaop/ncurrent/full/ismej2017126a.html). I've been very impressed with it.

**Comment by nailabc** [comment]
Hi, I'm also trying to reproduce the same workflow for my own data and I'm facing a problem that I couldn't solve yet while trying to run the python script (02-estimate-similarity.py) that uses the delta nucmer outputs.
The file REDUNDANT-MAGs-ANI.txt has zeros and nan at the last two columns:
```
query_genome_name	query_genome_length	target_genome_name	target_genome_length	matching_nucleotides	average_identity
pond_C8_MAG_00018	4632588	pond_D8_MAG_00002	3491239	0	nan
pond_C4_MAG_00057	2352710	pond_D4_MAG_00082	2294988	0	nan
pond_C8_MAG_00040	2353520	pond_E1_MAG_00069	3572234	0	nan
```

And I get an error which seems to be something related to numpy and an empty list (probably the m[] from line 58 of the python code):
```
/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/scipy-stack/2019a/lib/python3.5/site-packages/numpy/core/fromnumeric.py:3118:RuntimeWarning: Mean of empty slice.
  out=out, **kwargs
/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/scipy-stack/2019a/lib/python3.5/site-packages/numpy/core/_methods.py:85: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount) 
```

I see that the code tries to run the show-coords program and, as a test, I ran a nucmer command with he flag --coords and I got the correct output, I suppose, confirming to me that apparently it's not a problem with my files neither mummer, but with python, I just don't know how to fix it.

I was wondering if you faced the same problem while trying to follow the workflow or if anyone else could help me on that.

Just in case, this is the .coords file I got:
```
/home/naila/Documents/pond_C4_MAG_00016.fa /home/naila/Documents/Actinobacteria.fa
NUCMER

    [S1]     [E1]  |     [S2]     [E2]  |  [LEN 1]  [LEN 2]  |  [% IDY]  | [TAGS]
=====================================================================================
       1     6752  |        1     6752  |     6752     6752  |   100.00  | pond_C4_MAG_00016_000000000001	pond_C4_MAG_00016
       1   289391  |     6753   296143  |   289391   289391  |   100.00  | pond_C4_MAG_00016_000000000002	pond_C4_MAG_00016
       1  1095030  |   296144  1391173  |  1095030  1095030  |   100.00  | pond_C4_MAG_00016_000000000003	pond_C4_MAG_00016
  376983   378264  |   689519   690800  |     1282     1282  |    99.84  | pond_C4_MAG_00016_000000000003	pond_E1_MAG_00068
       1     3164  |  1391174  1394337  |     3164     3164  |   100.00  | pond_C4_MAG_00016_000000000004	pond_C4_MAG_00016
       1     3548  |  1394338  1397885  |     3548     3548  |   100.00  | pond_C4_MAG_00016_000000000005	pond_C4_MAG_00016
       1    13655  |  1397886  1411540  |    13655    13655  |   100.00  | pond_C4_MAG_00016_000000000006	pond_C4_MAG_00016
       1     6640  |  1411541  1418180  |     6640     6640  |   100.00  | pond_C4_MAG_00016_000000000007	pond_C4_MAG_00016
       1     8102  |  1418181  1426282  |     8102     8102  |   100.00  | pond_C4_MAG_00016_000000000008	pond_C4_MAG_00016
       1    14846  |  1426283  1441128  |    14846    14846  |   100.00  | pond_C4_MAG_00016_000000000009	pond_C4_MAG_00016
       1    38931  |  1441129  1480059  |    38931    38931  |   100.00  | pond_C4_MAG_00016_000000000010	pond_C4_MAG_00016
       1   272011  |  1480060  1752070  |   272011   272011  |   100.00  | pond_C4_MAG_00016_000000000011	pond_C4_MAG_00016
       1    43586  |  1752071  1795656  |    43586    43586  |   100.00  | pond_C4_MAG_00016_000000000012	pond_C4_MAG_00016
```

**Comment by nailabc** [comment]
I fixed the bug by editing line 59 of the 02-estimate-similarity.py script:
`        # this is tricky:
        m = []
        list(map(lambda n: m.extend([n[1]] * n[0]), matches[target_genome_name]))
`
