### ISSUE TITLE
How to set a different temp dir?

### ISSUE THREAD

**Issue by JBuongio** [merenlab/anvio#616]
Hi Meren, 
I'm running anvi-script-FASTA-to-contigs-db on a metagenome assembly that has about 180,000 contigs and keep running out of disk space on my work station. Is there a way to change the temp dir so I don't have to fill up the local machine? 

Thanks,
Joy

**Comment by meren** [comment]
In general the default temp directories anvi'o uses can be overwritten by TMPDIR, TEMP or TMP environment variables.

Apart from that, you shouldn't be using `anvi-script-FASTA-to-contigs-db` unless you are doing a quick and dirty analysis.

Instead you can use `anvi-script-reformat-fasta`, `anvi-gen-contigs-database`, `anvi-run-hmms` programs separately to make sure you have full control for every step (that script does it all for you in a quick way).
