### ISSUE TITLE
Adding collections of PCs to pan genomes

### ISSUE THREAD

**Issue by rbeinart** [merenlab/anvio#617]
Is there a way to choose and export pangenome collections via the command line? It would be very useful to be able export all PCs that are found in a certain genomes without having to highlight them via the GUI. Highlighting the PCs via the GUI is prone to error. For example, it would be excellent to be able to easily export all PCs found in genomes A,B,C; or the PCs shared by all genomes; or the PCs found in only one genome.

**Comment by meren** [comment]
Both `anvi-import-collection` and `anvi-export-collection` works with both anvi'o profile and pan datbases, but I guess what you are asking is different.

Maybe we can extend the functionality of `anvi-script-add-default-collection` (which currently only works with anvi'o profile databases) to add default collctions into pan databases. Or maybe it should be `anvi-pan-genome` (which computes the pan genome and knows all about the distribution of protein clusters) that adds a default collection..

I think `anvi-pan-genome` at the end of its running could create a collection `DEFAULT` which would contain bins for PCs that occur in all genomes (`CORE`), and individual bins for singletons for each genome (`GENOMENAME_SPECIFIC`).

Additionally `anvi-script-add-default-collection` could have a new flag, `--genomes-for-core`, which would accept a comma-separated list of genome names to determine what should be in the `CORE` bin (when it is run on a pan database), and would also add `GENOMENAME_SPECIFIC` bins for each of the genomes of interest. Although, I feel like this much responsibility on `anvi-script-add-default-collection` would require it to become a main program, such as `anvi-gen-collection`.

**Comment by rbeinart** [comment]
What you describe sounds great - a default outcome for avi-script-add-default-collection that would include the core genome (maybe separately single-copy core genes and all core genes), as well as the unique PCs for each genome, would be excellent. Then the ability to designate which genomes are included would allow the user to also get the make specific genome-to-genome comparisons.
