### ISSUE TITLE
Iterations, bootstraps and scale values on phylogenetic tree.

### ISSUE THREAD

**Issue by aliexclusive** [merenlab/anvio#618]
It would be nice to add further options for preparation of phylogenetic tree, like bootstraps values, scale, flexibility to choose different algorithms etc.

**Comment by meren** [comment]
We made some improvements to edit and work with phylogenomic trees in anvi'o `v5` which will be available soon. Improvements beyond this will take much longer since we are not experts of phylogenetic tree editing :)
