### ISSUE TITLE
Should this be in dbops?

### ISSUE THREAD

**Issue by ShaiberAlon** [merenlab/anvio#622]
@meren, right now this is only useful for MetagenomeCentricGeneClassifier, but maybe in the future some other class would access this. Should this function be transferred to dbops?

https://github.com/merenlab/anvio/blob/b803200d9f7689e95a456cb83f37a97f57ac8ec6/anvio/mcgclassifier.py#L420

**Comment by meren** [comment]
I looked into the design a bit. I think there are some ways to improve it, but after 45 minutes of coding and re-coding, I realized it is best if it stays where it is as a helper function.

Maybe we can at some point sit together and think about improving the design overall :)


Best,

**Comment by ShaiberAlon** [comment]
Sounds good!
