### ISSUE TITLE
Docker image does not have FastTree

### ISSUE THREAD

**Issue by ozcan** [merenlab/anvio#625]
Is it harder to install something later because our image does not have compiler and stuff, we should include things that required by any of our pipelines.

**Comment by meren** [comment]
Crap :( Of course. The docker is file here:

https://gist.github.com/meren/65b1f1bfea1b53e87e10f025d1e4c29a

Do you already know the line to add to this? I can update the image since it doesn't need any change in `v3` :)

**Comment by ozcan** [comment]
I use this:
`wget http://www.microbesonline.org/fasttree/FastTree -O /usr/local/bin/FastTree && chmod +x /usr/local/bin/FastTree`

**Comment by meren** [comment]
Excellent. I will start the rebuild.

**Comment by meren** [comment]
Fixed:

![image](https://user-images.githubusercontent.com/197307/32293350-cb7ae700-bf10-11e7-953c-eb326dd51409.png)

Thank you! :)
