### ISSUE TITLE
Completeness inconsistency

### ISSUE THREAD

**Issue by xvazquezc** [merenlab/anvio#627]
Hi @meren,
I was running `anvi-interactive` after generating the completeness report for a few genomes and I notice that the values reported by `anvi-script-get-collection-info` didn't match those shown in the interactive view. All of them are Archaea.
E.g. this genome shows 24.7% C / 4.3% R in `anvi-interactive` when selecting all the splits but in the completeness report is way different:
```
bins	domain	domain_confidence	percent_completion	percent_redundancy	num_splits	total_length
Smooth_498	archaea	0.72	51.85	19.75	3473	6172055
```
I also run near-complete genomes and they seem to be less affected, although C and/or R values still don't match.

Any idea what could be going on?
Xabi

Initially seen in anvio 2.4.0, stays the same after upgrading to v3 dbs from v8 to v9.
System: `x86_64 4.10.0-37-generic #41~16.04.1-Ubuntu`

**Comment by meren** [comment]
Hey @ozcan, since you are tinkering with the inconsistencies in the codebase, can you please take a look at this one too? :)

Thanks for reporting, @xvazquezc!

**Comment by xvazquezc** [comment]
@meren, @ozcan 
If it's of any help, according to my collabs, the real values should be the ones from `anvi-script-get-collection-info`, based on comparisons with CheckM.
