### ISSUE TITLE
anvi'o profile databases should support simple orders of items in addition to hierarchical orders

### ISSUE THREAD

**Issue by meren** [merenlab/anvio#628]
currently anvi'o pan and profile databases have a `clusterings` table that only supports newick formatted orders. 

``` python
clusterings_table_name               = 'clusterings'
clusterings_table_structure          = ['clustering', 'newick']
```

in contrast, the table for orders in anvi'o samples database has a much more flexible schema.

``` python
samples_order_table_name                   = 'samples_order'
samples_order_table_structure              = ['attributes', 'basic', 'newick']
```

I suggest changing the `clusterings` table in anvi'o profile database to `items_order`, and implement the same strategy we use for anvi'o samples databases. this will indeed require a profile and pan upgrade script.

**Comment by meren** [comment]
What do you think, @ozcan? :)

**Comment by ozcan** [comment]
Good plan, what if we split this table structure into two separate simple tables because if a column is bull use other one logic causes problems, can we discuss this when you come back?

**Comment by meren** [comment]
so are you suggesting that we should break the table into samples db into two tables, too?

**Comment by meren** [comment]
note, the FIXME here is waiting for this issue to be resolved: https://github.com/merenlab/anvio/commit/83d795540c82853830cc1f785b0e252c00df0a6a

**Comment by meren** [comment]
> what if we split this table structure into two separate simple tables

Would you like to take a stab at this or would you like me to try it first? I think it would be very helpful to have an intuitive sense of the design as working on this idea.

**Comment by ozcan** [comment]
I don't have a clear plan but I will try, is there any deadline on this? since it is connected to other issue

**Comment by meren** [comment]
Not really a definite deadline. I will continue in `pan_synteny` branch when this is resolved, and it can wait for sure.

I think splitting `clusterings` table into `items_order_newick` and `items_order_list` would be the start. but then there are these variables in the `self` table of profile databases:

```
available_clusterings|cov:euclidean:ward,tnf:euclidean:ward,tnf-cov:euclidean:ward
contigs_clustered|1
default_clustering|tnf-cov:euclidean:ward
```

:/

I am not sure if this is the best way to describe these information since every time we have a new order in either of those tables we need to update them as well. tables. the good news is we have a function to add new orders for our items that streamlines this; see `dbops:add_hierarchical_clustering_to_db`, so we can keep it as is. but we will need to come up with a better vocabulary.

maybe it is better if we sit together and do it together when I'm back instead of separate attempts :)
