### ISSUE TITLE
All bins from collection load automatically with empty set of splits when using anvi-refine

### ISSUE THREAD

**Issue by tdelmont** [merenlab/anvio#631]
So,

this seems to be a systematic problem with anvi-refine on the anvi'o master:

all bins from the collection load with empty set of splits when refining a bin of interest (usually only the invoked bin will load). As a result, we have to remove all bins manually before we can save the refinement efforts. This is rapidly impossible to manage as the number of bins increases....

<img width="1130" alt="screen shot 2017-11-05 at 5 30 43 pm" src="https://user-images.githubusercontent.com/8332889/32416843-db1b561c-c24f-11e7-9a5d-ddf7f492c309.png">.

Here is a link to a test project if needed:

https://www.dropbox.com/s/945kk4il9e5us4o/Archive.zip?dl=0

and the command line I used:

```
anvi-refine -c Abe_2500nt_CONTIGS.db -p PROFILE.db -C default -b Bin_1
```

Thanks for looking into this,

Tom

**Comment by meren** [comment]
Thanks for the report, Tom. This indeed seems like an issue.

**Comment by meren** [comment]
@ozcan, maybe this is also a good time to also put a new trash bin icon next to 'Red.' text, so by clicking that the user can be prompted with the question "_are you sure you want to remove all bins?_" :)

![image](https://user-images.githubusercontent.com/197307/32416967-893773c2-c217-11e7-913c-dd76c002d9a2.png)

**Comment by meren** [comment]
hey @ozcan, thank you for the new button. I confused you with the additional request, but the tom's original complaint is still there, so I'm re-opening this to make sure we don't forget about it :)

**Comment by tdelmont** [comment]
It seems the bug has been fixed, good job Ozcan!!!

**Comment by ozcan** [comment]
Hey Tom,
I have just added the delete all button. I think meren solved the bug

**Comment by meren** [comment]
I don't think I did anything relevant to this :(

**Comment by tdelmont** [comment]
hehe,

Well it seems to work now (I spend last 8 hours or so binning scaffolds).
I will re-open the issue if I see the bug again (I will use the refining program extensively in coming days).

Tom

**Comment by tdelmont** [comment]
guys, the bug came back from the dead today....

Thanks for looking into this!

Tom

**Comment by meren** [comment]
Tom, you need to help us recapitulate this. We have no idea how to investigate the error here :)

**Comment by tdelmont** [comment]
here is the command line to use:

**anvi-refine -c Mariner_2500nt_CONTIGS.db -p PROFILE.db -C MAGs_FINAL -b DEEP_ANA16C_MAG_00001**

and here the link to the anvi'o files (45 Mo zipped):

https://www.dropbox.com/s/utwylog9c5ofxbw/Archive.zip?dl=0

Tom

**Comment by tdelmont** [comment]
I am working on another assembly, where the bug does not occur.
The only difference is that for the one with the bug I did not run concoct. But even this does not make sense as I have created multiple collections downstream, and the bug still occurs on the final collection (the one for which I provided a command line).....

**Comment by ozcan** [comment]
OK Now I understand the problem Tom, If there is a collection named `default` in the database interface loads it without checking the mode. Obviously it should not load it in `refine` mode.
