### ISSUE TITLE
anvi-merge error v3: KeyError: 'total_length'

### ISSUE THREAD

**Issue by meren** [merenlab/anvio#632]
We've been hearing about the following merge error from some of our users, but we have not been able to reproduce it:

```
File "/sw/csi/anvio/3.0.0/el7_py361_anacondaenv/env/bin/anvi-merge", line 50, in <module>
merger.MultipleRuns(args).merge()
File "/sw/csi/anvio/3.0.0/el7_py361_anacondaenv/env/lib/python3.5/site-packages/anvio/merger.py", line 284, in merge
self.sanity_check()
File "/sw/csi/anvio/3.0.0/el7_py361_anacondaenv/env/lib/python3.5/site-packages/anvio/merger.py", line 160, in sanity_check
v = set([r[k] for r in list(self.profile_dbs_info_dict.values())])
File "/sw/csi/anvio/3.0.0/el7_py361_anacondaenv/env/lib/python3.5/site-packages/anvio/merger.py", line 160, in <listcomp>
v = set([r[k] for r in list(self.profile_dbs_info_dict.values())])
KeyError: 'total_length'
```

The error is likely due to trying to merge profile databases generated by an older version of anvi'o with the latest `v3` version. Usually we keep track of database changes very carefully, and we do not force our users to re-profile their data, but here we are the first time after more than a year.

Is this happening to you? **Please help us better understand the problem by answering these questions**, and we will provide you with a script that will fix your profile databases:

* Do you remember which version of anvi'o did you generate your profile databases you are trying to merge?

* Can you please run this command on one of your anvi'o profile databases you are merging and include the output to your response: `sqlite3 PATH/TO/PROFILE.db 'select * from self;'`

**Comment by jmtsuji** [comment]
I am getting the same error. All Anvi'o steps have been run in V4 (in a conda environment), although I've imported my own gene calls (prokka), functional annotations (prokka), and taxonomy information (DIAMOND blastp vs. RefSeq).

Error with example command:
```
$ anvi-merge ./*/PROFILE.db -o samples_merged -c contigs.db --skip-concoct-binning
Traceback (most recent call last):
  File "/Winnebago/jmtsuji/miniconda2/envs/anvio4/bin/anvi-merge", line 49, in <module>
    merger.MultipleRuns(args).merge()
  File "/Winnebago/jmtsuji/miniconda2/envs/anvio4/lib/python3.6/site-packages/anvio/merger.py", line 291, in merge
    self.sanity_check()
  File "/Winnebago/jmtsuji/miniconda2/envs/anvio4/lib/python3.6/site-packages/anvio/merger.py", line 166, in sanity_check
    v = set([r[k] for r in list(self.profile_dbs_info_dict.values())])
  File "/Winnebago/jmtsuji/miniconda2/envs/anvio4/lib/python3.6/site-packages/anvio/merger.py", line 166, in <listcomp>
    v = set([r[k] for r in list(self.profile_dbs_info_dict.values())])
KeyError: 'total_length'
```

Database info for mapping profile (1 of 4) created by anvi-profile (with example command):
```
$ sqlite3 PROFILE.db 'select * from self;'
version|23
db_type|profile
anvio|4
sample_id|L227_2013_6m
samples|L227_2013_6m
merged|0
blank|0
contigs_ordered|0
default_view|single
min_contig_length|2500
SNVs_profiled|1
AA_frequencies_profiled|0
min_coverage_for_variability|10
report_variability_full|0
contigs_db_hash|424b1f26
description|_No description is provided_
creation_date|1523464432.42442
num_splits|33509
num_contigs|32964
total_length|203986014
total_reads_mapped|20712414
```

Let me know if you need any additional information.

**Comment by jmtsuji** [comment]
Glad the bug report was helpful. After re-running `anvi-profile` (on 4 of 4), the database info looks good:

```
$ sqlite3 PROFILE.db 'select * from self;'
version|23
db_type|profile
anvio|4
sample_id|L227_2014_8m
samples|L227_2014_8m
merged|0
blank|0
contigs_ordered|0
default_view|single
min_contig_length|2500
SNVs_profiled|1
AA_frequencies_profiled|0
min_coverage_for_variability|10
report_variability_full|0
contigs_db_hash|424b1f26
description|_No description is provided_
creation_date|1523513733.93993
num_splits|33509
num_contigs|32964
total_length|203986014
total_reads_mapped|15130865
```

...and `anvi-merge` now works!
