### ISSUE TITLE
anvi-script-upgrade-profile-db-v20-to-v21 does not work

### ISSUE THREAD

**Issue by tdelmont** [merenlab/anvio#634]
Hi,

the recent program anvi-script-upgrade-profile-db-v20-to-v21 does not seem to work properly.

Here is the error message I got:

---
anvi-script-upgrade-profile-db-v20-to-v21 PROFILE.db

WARNING
===============================================
This script will upgrade your profile database from v20 to v21. We recently
redesigned the way we keep clustering data in anvi'o pan and profile databases.
After this everything will continue to work smootly (we hope). Well. You can
just press ENTER to continue. If you want to cancel the upgrade and think more
about it, press CTRL+C now. If you want to avoid this message the next time, use
'--just-do-it'.

Press ENTER to continue...

[07 Nov 17 21:03:26 Trying to upgrade the profile database] ...

Config Error: A value for 'available_clusterings' does not seem to be set in table 'self'.
---

It might be due to the fact that for my project I do not have a clustering (too many contigs)
Thanks for looking into this,

Tom

**Comment by meren** [comment]
I think I covered that, tom. Can you send me the profile database?

**Comment by tdelmont** [comment]
here is a link:

https://www.dropbox.com/s/l9e8s1dxwln501s/PROFILE.db?dl=0

thanks,
tom

**Comment by meren** [comment]
This should be resolved (beff5e9d9c843bebf0fa47c12ef7e0a8ae827ee4). Please update the master, and check.

Thanks!

**Comment by meren** [comment]
(you will need to re-run the upgrade script on your profile database)

**Comment by tdelmont** [comment]
worked perfectly, thanks!
