### ISSUE TITLE
Improving the genome-resolved metagenomic workflow

### ISSUE THREAD

**Issue by tdelmont** [merenlab/anvio#635]
This is for Meren:

When I follow the classic workflow for genome-resolved metagenomics, I end-up with many more bins than MAGs. At the end of the flow,  I summarize the final collection in order to extract the fasta files of the MAGs (if there is a better way, then the rest of the message is obsolete). The problem is that summarizing hundreds of bins takes time and produces a lot of files that in most cases are never used.

So, could it be possible to add a flag for the anvi-summarize program so that only bins starting with the prefix "MAG" are summarized?

I think it would be a nice contribution to a "pain-less" workflow to get MAGs from metagenomes.

Tom

**Comment by tdelmont** [comment]
Fixing error in my comment: the prefix is not MAG, but *MAG* would work.

**Comment by meren** [comment]
Hi Tom,

This is not a bad idea, but it would complicate things unnecessarily. Summary of a collection should include all bins described in it. A more explicit workflow that also allows the user to do what you suggested could go like this:

* `anvi-export-collection`
* edit the collections file (i.e., `grep 'MAG-' collection.txt > new_collection.txt`)
* `anvi-import-collection`
* `anvi-summarize`


Best,
