### ISSUE TITLE
Inspect page improvements to show functions for genes, and bins for splits.

### ISSUE THREAD

**Issue by vnsriniv** [merenlab/anvio#636]
Hi Anvio team,

As of now, the user can highlight splits containing searched functions in the main visualization page. But when the split is inspected, the highlighting doesn't show up in the inspect page. It might be convenient for the user to have the searched function to be highlighted in the inspect page too (maybe on the bottom where the synteny of the functions on the split is shown).  

*Hopefully you don't think I am just being lazy about clicking through every function to find the one I am searching for.. maybe I am...*

Thanks 
Varun

**Comment by meren** [comment]
I think this is a good idea --highlighting genes in the inspection page based on search terms used in the main display. 

In addition, the inspect page does not contain any information regarding which bin a given split may belong to. If we had a way to show that, that would have been useful, too.

Currently both @ozcan and I are very busy with some serious re-design of the codebase, but hopefully we will get back to this once we are done.

Thank you, Varun.
