### ISSUE TITLE
Error with anvi-script-snvs-to-interactive

### ISSUE THREAD

**Issue by vnsriniv** [merenlab/anvio#637]
Hi Meren,

I am sorry to be bugging you so much!!

I created a SNV profile using the anvi-gen-variability-profile using the following command

```
anvi-gen-variability-profile -c ./ecoli_bin/Ecoli/CONTIGS.db -p ./ecoli_bin/Ecoli/PROFILE.db -C DEFAULT -b ALL_SPLITS --min-coverage-in-each-sample 20 --include-split-names --quince-mode -o Ecoli-minCov20-SNVs.txt
```

I then used the following code

```anvi-script-snvs-to-interactive Ecoli-minCov20-SNVs.txt -o ecoli_snvs```

but got the following error. 

```
Num entries ..................................: 12,749
Num positions ................................: 1,159
Num samples ..................................: 11
Traceback (most recent call last):
  File "/home/vnsriniv/virtual-envs/anvio/bin/anvi-script-snvs-to-interactive", line 4, in <module>
    __import__('pkg_resources').run_script('anvio===3-master', 'anvi-script-snvs-to-interactive')
  File "/home/vnsriniv/virtual-envs/anvio/lib/python3.5/site-packages/pkg_resources/__init__.py", line 748, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/vnsriniv/virtual-envs/anvio/lib/python3.5/site-packages/pkg_resources/__init__.py", line 1517, in run_script
    exec(code, namespace, namespace)
  File "/home/vnsriniv/virtual-envs/anvio/lib/python3.5/site-packages/anvio-3_master-py3.5-linux-x86_64.egg/EGG-INFO/scripts/anvi-script-snvs-to-interactive", line 100, in <module>
    main(args)
  File "/home/vnsriniv/virtual-envs/anvio/lib/python3.5/site-packages/anvio-3_master-py3.5-linux-x86_64.egg/EGG-INFO/scripts/anvi-script-snvs-to-interactive", line 65, in main
    additional_data_dict[unique_pos_identifier]['Position in codon'] = utils.get_ordinal_from_numerical(int(entry['base_pos_in_codon']))
AttributeError: module 'anvio.utils' has no attribute 'get_ordinal_from_numerical'
```
I checked the list of attributes in the anvio.utils function using dir(anvio.utils) and found that the function name is actually get_ordinal_from_integer and not get_ordinal_from_numerical.. Is this what is causing the error?

Thanks 
Varun

**Comment by meren** [comment]
Hi Varun,

Thanks for the report. I guess you are using the `master` branch, right?

It seems 20 days ago @ekiefl has changed the name of that function (https://github.com/merenlab/anvio/commit/eae38b8ddfeda16551ec32ad66269a8ecb51ea7d) and forgot to see where else is it being called.


Best,

**Comment by ekiefl** [comment]
Hi Varun, thanks for bringing this to my attention. You diagnosed the situation perfectly. Here is the commit fixing the mistake, for your interest: https://github.com/merenlab/anvio/commit/dc5e609570438e4061e3e621a3b33f51c2c5fc4b. If you `git pull` from the master repository all should be well. Let me know if you run into more issues surrounding this.

**Comment by vnsriniv** [comment]
Thanks @ekiefl and @meren! Appreciate the quick response!
