### ISSUE TITLE
Get contigs stats without display

### ISSUE THREAD

**Issue by FCMicrobes** [merenlab/anvio#639]
Dear Anv'o guru and developpers,

As discussed on the google group.
Is there any way to get contigs stats in a text file directly when running anvi-display-contigs-stats from a bioinformatic cluster?

Thanks

Cheers,

Flo

**Comment by meren** [comment]
We can add one new flag and one new parameter to address this:

* `--report-as-text` flag (when declared it doesn't even attempt to invoke the browser. it would complain if the user used this flag, but not declared an output file path with the `--output` parameter).
* `--output` parameter (the output file path to store stats as TAB-delimited. this can be used without the `--report-as-text` flag, in which case it would both report the output as a TAB-delimited file, and invoke the browser).

Addressing this will also require us to move the N/L 50 calculations into the summary class.
