### ISSUE TITLE
Pangenome summary issue: "KeyError: 'num_genes_in_PCs'"

### ISSUE THREAD

**Issue by tdelmont** [merenlab/anvio#641]
Hi,

I could not summarize my pangenomic bins in the interface or in the terminal.
In both cases the error is: **KeyError: 'num_genes_in_PCs'**

Here is the full error:

anvi-summarize -g ../PAN-GENOMES.h5 -p Kori-PAN.db -C default -o SUMMARY_PAN
Genomes storage ..............................: Initialized (storage hash: da0ab525)
Num genomes in storage .......................: 3
Num genomes will be used .....................: 3
Pan DB .......................................: Initialized: Kori-PAN.db (v. 6)
Traceback (most recent call last):
  File "/Users/tomdelmonttdelmont/virtual-envs/anvio-master/anvio/bin/anvi-summarize", line 96, in <module>
    main(args)
  File "/Users/tomdelmonttdelmont/virtual-envs/anvio-master/anvio/bin/anvi-summarize", line 59, in main
    summary.process()
  File "/Users/tomdelmonttdelmont/virtual-envs/anvio-master/anvio/anvio/summarizer.py", line 262, in process
    ('Number of genes', pretty(int(self.p_meta['num_genes_in_PCs']))),
KeyError: 'num_genes_in_PCs'

Let me know if you need access to the entire project to test it.

And, thanks for looking into it.

Tom

**Comment by meren** [comment]
How can you get this error :/

I am confused. Can you do everything from scratch by going as back as you comfortably can in your workflow?

**Comment by tdelmont** [comment]
I had to upgrade profile and genome-storage files. 

Do you want me to run the pangenome from scratch? It is only a few genomes so I can do it, but it will not fix the bug for people in my situation later on, no?

Tom

**Comment by meren** [comment]
Let's first see whether it fixes the issue.

**Comment by tdelmont** [comment]
So, when redoing the pangenome from scratch the error is no longer there.

I think it is linked to the upgrades.

I will let Meren decide if the issue should be closed at this point.

Tom

**Comment by meren** [comment]
Can you explain how did you get this error? If I can understand at which stage it is disappears I can find a way to reproduce this and make sure it doesn't happen to anyone.

**Comment by tdelmont** [comment]
I went back to a ~4 months old pangenomic analysis, upgraded to the latest anvi'o versions when needed (profile and genome storage files) and visualized my pangenome without any problem.

On the other hand, I could not summarize my results, with the main error being  **KeyError: 'num_genes_in_PCs'**

I started over, from step one (i.e., generating contigs.db and so on), and I could summarize without any problem this time.

So, I do not know at which step this is happening.... I realize I did not help much here. Would you like me to do more analyses to help?

**Comment by meren** [comment]
This is helpful Tom. Thanks!
