### ISSUE TITLE
Config Error: db v9 versus db v8

### ISSUE THREAD

**Issue by nick-youngblut** [merenlab/anvio#643]
I got a weird error when trying to run `anvi-run-ncbi-cogs` with anvio installed with conda from the bioconda channel (running on headless server; Ubuntu 16.04.3):

```
WARNING
===============================================
Because you set the temporary directory path by hand, anvi'o will not remove its
content when it is done. But she certainly hopes that you will clean those files
later.

COG data directory ...........................: /ebio/abt3_projects/databases/anvio
Directory to store temporary files ...........: /ebio/abt3_projects/temp_data/LLMGA_33004609329/
Directory will be removed after the run ......: False


Config Error: It seems the database 'tests/output_amy/anvio/coassemble.db' was generated when
              your client was at version 9, however, your client now is at version 8. Which
              means this database file cannot be used with this client anymore and needs to be
              upgraded to the version 8 :/ That being said, you may not need to re-create this
              database if there is a script to upgrade this database from v9 to v8. Please
              feel free to get in touch with the anvi'o developers (they will be happy to hear
              from you).
```

I created the cog data directory with the following:

```
anvi-setup-ncbi-cogs --cog-data-dir /ebio/abt3_projects/databases/anvio -T 30 --reset
```

The `anvi-run-ncbi-cogs` call was:

```
anvi-run-ncbi-cogs   -c contigs.db   --cog-data-dir /ebio/abt3_projects/databases/anvio  -T 30 --temporary-dir-path /ebio/abt3_projects/temp_data/LLMGA_33004609329/  
```

The weirdest bit from the error is:

> you may not need to re-create this database if there is a script to upgrade this database from v9 to v8.

"upgrade" usually means going to a higher version.

Any idea on what's going on?

**Comment by meren** [comment]
The error is not about the COGs, but the contigs database `coassemble.db`. The error is funny, because it seems this contigs database was generated from a newer version of anvi'o, and you are using it with an older version :)

What you need to do is to upgrade your anvi'o installation.


Best,

**Comment by nick-youngblut** [comment]
I've only had one install of anvio. I just installed it yesterday and was using it for the first time. I don't understand how the same anvio install could say that the contigs database that it created is too old. This is really odd. 

I guess that I'll post an issue on bioconda for updating the anvio bioconda recipe. The current version on bioconda is v3.0.0, which I thought was the current version (according to https://github.com/merenlab/anvio/releases/tag/v3), but v3.0.0 doesn't seem to include `anvi-display-contigs-stats`

**Comment by meren** [comment]
Please type `anvi-self-test --version` to learn the version you have installed.

**Comment by nick-youngblut** [comment]
```
Anvi'o version ...............................: 2.1.0
Profile DB version ...........................: 17
Contigs DB version ...........................: 8
Pan DB version ...............................: 4
Samples information DB version ...............: 2
Genome data storage version ..................: 1
Auxiliary data storage version ...............: 3
Anvi'server users data storage version .......: 1
```

So, to provide a bit more context, I'm running these anvio steps (eg., `anvi-gen-contigs-database` and `anvi-run-hmms`) in a snakemake pipeline, which creates a conda environment for each rule in the pipeline. It should be using the same conda environment (one which includes anvio from bioconda) in all of the rules where anvio scripts are called. 

I need to to some more checking, but anvio v2.1 should have been used for everything.

**Comment by meren** [comment]
I see. This is an installation problem somewhere.

But please don't use anvi'o `v2.1.0`. It is extremely old.

**Comment by rec3141** [comment]
I'm also getting this error, after installing Eden 3.0 this week via Anaconda. I've never had another version installed.

```Config Error: It seems the database 'contigs.db' was generated when your client was at version 9, however, your client now is at version 8.```

```(anvio3) Erics-Mac-Pro:anvio cryomics$ anvi-self-test --version
Anvi'o version ...............................: 2.3.2
Profile DB version ...........................: 20
Contigs DB version ...........................: 8
Pan DB version ...............................: 5
Samples information DB version ...............: 2
Genome data storage version ..................: 1
Auxiliary data storage version ...............: 3
Anvi'server users data storage version .......: 1```

**Comment by meren** [comment]
I am very concerned about conda installations :( Your anvi'o version seems to be `2.3.2`, @rec3141.

Are you sure you installed anvi'o like this?

```
conda create -n anvio3 -c bioconda -c conda-forge python=3.5.4 gsl anvio
```

**Comment by rec3141** [comment]
Sorry, I was wrong, an old version of anvi'o WAS previously installed by homebrew, I removed the old installation and I guess it will work now.
