### ISSUE TITLE
Import taxonomy matrix - Mapping Function error

### ISSUE THREAD

**Issue by anagtz** [merenlab/anvio#647]
Hi Meren,

Thank you so much for taking a look at my data. Attached is my taxonomy matrix. I try to import it using the following command:

$ anvi-import-taxonomy -c A1_contigs.db -i A1_correct_matrix.txt -p default_matrix 

and get the following error:

Config Error: Mapping function '<type 'int'>' does not seem to be a proper Python function :/

[A1_correct_matrix.txt.gz](https://github.com/merenlab/anvio/files/1488183/A1_correct_matrix.txt.gz)

**Comment by meren** [comment]
Hi,

Can you please send the output of `anvi-interactive --version`?

I just checked the file. It is not a valid TAB-delimited file. I am not sure how you exported it, but it may be an issue even after fixing the current problem. When I run this I should get a single number, but there are many:

```
awk 'BEING{FS="\t"}{print NF}' A1_correct_matrix.txt
```

**Comment by anagtz** [comment]
```
(anvio240) ana@ceiba:~/.../Anvio/A1$ anvi-interactive --version
Anvi'o version ...............................: 2.1.0
Profile DB version ...........................: 17
Contigs DB version ...........................: 8
Pan DB version ...............................: 4
Samples information DB version ...............: 2
Genome data storage version ..................: 1
Auxiliary data storage version ...............: 3
Anvi'server users data storage version .......: 1
```


I created the file with a script. Maybe I understood something wrong. I have one gene (with their taxonomic assignation) per line. Each line has 7 fields, most of them are empty, but normally one does have a taxonomic assignation.

`awk 'BEGIN{FS="\t"}{print NR ": " NF}' A1_correct_matrix.txt | cut -f 2 -d ":" | sort | uniq`

this returns "7" as an indicator that all the lines have the same number of fields, right?

does the file looks right?

```
$ head A1_correct_matrix.txt 
gene_callers_id	t_phylum	t_class	t_order	t_family	t_genus	t_species
00002						Streptomyces griseus
00003						Desulfatibacillum alkenivorans
00005						delta proteobacterium NaphS2
00006						Xanthomonas sp. SN8
00008						Chthoniobacter flavus
00010						Microscilla marina
00012						Desulfurivibrio alkaliphilus
00013						Chloroflexus sp. isl-2
00016						delta proteobacterium PSCGC 5342

```

**Comment by meren** [comment]
Sorry! I mistakenly typed `BEING` instead of `BEGIN` in my command, and awk didn't give me an error :( Your file is fine.

Unfortunately you are using a very old version of anvi'o :/

If you upgrade your anvi'o to `v3`, you will see the problem is not there anymore (I just checked --`v3` properly parsed your file).

Best,

**Comment by anagtz** [comment]
oh, wow... ok, I'll update it and hope this solves it. Thank you for your time! :)
