### ISSUE TITLE
Export per sample functions

### ISSUE THREAD

**Issue by cyklee** [merenlab/anvio#653]
Hi team anvio!

Greetings from New Zealand. I understand that anvi'o is more for working with co-assembly and binning contigs. However, I'm wondering if **there's a way to export functions (e.g. COG classification) per sample, instead of per bin?** This would be very useful for generating something like a per sample COG heatmap.

This can be done quite easily with a per sample assembly and Prokka (instead of using the co-assembly), but I figured it would be nice to work with the same co-assembly throughout the entire study, or would you recommend working with individual assemblies instead?

Thanks!

Kevin Lee

**Comment by meren** [comment]
Hi Kevin,

I am not sure if it is possible to get 'sample-specific' functional information from a co-assembly in a reliable way. Perhaps it could be done by utilizing mapping results from each sample to the co-assembly. This is currently possible to do with anvi'o (if you run anvi-summarize by initializing gene coverages through the relevant flag, the output would contain everything necessary to understand the distribution of genes across samples).

The other option would be to work with individual assemblies.


Best,
