### ISSUE TITLE
anvi-interactive ignores distance or linkage flags with blank profile db

### ISSUE THREAD

**Issue by rbartelme** [merenlab/anvio#669]
anvi-interactive only uses default distance and linkage with blank profile db and ignores --distance --linkage flags.

**Comment by meren** [comment]
I'm sorry, just realized something. If you are using `anvi-profile` to generate blank profiles first, then you should set your distance and linkage algorithms during the `anvi-profile` stage. Does this make sense?

**Comment by rbartelme** [comment]
Yeah that makes sense.
