### ISSUE TITLE
anvi-search-functions-in-splits cannot print gene sequences for a specific function

### ISSUE THREAD

**Issue by tdelmont** [merenlab/anvio#671]
Hi,

I realized that we do not have a one-step option to extract gene sequences (ideally at either NT or AA level) for a given function (or list of functions) within anvi'o.

We only have this option for the hmm results, but not for let's say the COG annotation. 

I think we could add this in the program `anvi-search-functions-in-splits`, but I am sure Meren and Ozcan will know better.

Thanks,

Tom

**Comment by meren** [comment]
now this is possible to have DNA and AA sequences for genes to be store in the full-output:

```
anvi-search-functions -c CONTIGS.db \
                      --search-term elongation \
                      --full-report REPORT.txt \
                      --include-sequences
```
