### ISSUE TITLE
Add --gene-caller-ids and --delimiter to anvi-get-aa-sequences-for-gene-calls

### ISSUE THREAD

**Issue by brymerr921** [merenlab/anvio#677]
Hi Anvi'o team,

I noticed that `anvi-get-dna-sequences-from-gene-calls` has a nice way to request just specific genes based on a list of `--gene-caller-ids` separated by a `--delimiter`, but the same feature isn't available for `anvi-get-aa-sequences-from-gene-calls`. I'm able to (1) translate the DNA sequences FASTA file or (2) subset the amino acid sequences, but it'd be great if I could specifiy which amino acid sequences I want in my output file at the command line.

Thanks,
Bryan

**Comment by meren** [comment]
It is now in master, Bryan. Thank you!
