### ISSUE TITLE
anvi-profile stuck

### ISSUE THREAD

**Issue by Arkadiy-Garber** [merenlab/anvio#678]
anvi-profile seems to stall on a contig, such as:

Processed 1116 of 1117 contigs. Current memory usage: 1.44 GB

or 

Processed 846 of 1117 contigs. Current memory usage: 1.44 GB

and stay like that indefinitely...

Thanks,

**Comment by meren** [comment]
> If this is a technical issue, please run the command `anvi-self-test --version` in your terminal and paste the output at the beginning of your report.
> 
> It would also be very helpful if you can mention which operating system are you using, and how did you install anvi'o.

**Comment by Arkadiy-Garber** [comment]
Hey Meren, the issue seems to have resolved itself after I deleted and re-made the contigs database that I was working with, and used that new db to make the profile...I probably screwed something up at the "anvi-gen-contigs-database" step. If the issue arises again, I will run the "anvi-self-test --version" command and post the requested info.

Hope you are enjoying the holidays!
Arkadiy

**Comment by meren** [comment]
Thanks for the update :)

Still, it should have never happened, and anvi'o should have let you know about a broken contigs database.


Best,
