### ISSUE TITLE
MCGClassifier takes forever to complete when running all tests

### ISSUE THREAD

**Issue by meren** [merenlab/anvio#679]
This is probably due to figure generation step. We can either separate MCGC tests into a separate file, or we can think of a way to make it much faster if we would like to keep it within all tests.

**Comment by ShaiberAlon** [comment]
The solution in my opinion is to skip the figure generation (and I will make sure to have a separate test for that). It relates to this: https://github.com/merenlab/lab-fiesta/issues/112, which I will do once I finish restructuring MCGC completely...
