### ISSUE TITLE
Ad hoc phylogenomic tree storage in profile db code needs updatin'

### ISSUE THREAD

**Issue by meren** [merenlab/anvio#684]
Whoever gets to it first :) It is in `bottleroutes`:

![image](https://user-images.githubusercontent.com/197307/34652720-af755bfa-f3a7-11e7-89ad-d6acd87ac981.png)

**Comment by ozcan** [comment]
Please let me do this @meren :)

**Comment by meren** [comment]
sure! :)

**Comment by meren** [comment]
thank you very much in advance.

**Comment by ozcan** [comment]
Hey @meren,
It seems `skip_multiple_gene_calls` flag is removed from `write_sequences_in_gene_clusters_to_file` function, should I also remove that option from the interface?

**Comment by meren** [comment]
Hey Ozcan,

For phylogenomic analyses it will be a must. The option is not there, but there is a filter: when you set `max_num_genes_from_each_genome = 1` in that class, it will be identical to the behavior of `skip_multiple_gene_calls` :)

**Comment by ozcan** [comment]
This problem is fixed. I will open another issue for using filters like `max_num_genes_from_each_genome` from the interface
