### ISSUE TITLE
we need a way to initialization of `gene_coverage_stats_dict` for bins

### ISSUE THREAD

**Issue by ShaiberAlon** [merenlab/anvio#686]
So it shouldn’t initialize the entire profile database.

**Comment by ShaiberAlon** [comment]
I will create a test script (along with profile and contigs db with a collection) and share with you Meren.

**Comment by ShaiberAlon** [comment]
That's great Meren! And so many deletions :-)

**Comment by meren** [comment]
I know!

I hope the docstring in PanSuperClass is helpful enough to see how it can be used.
