### ISSUE TITLE
gene_coverage_values_per_nt shouldn't be under self.gene_level_coverage_stats_dict

### ISSUE THREAD

**Issue by ShaiberAlon** [merenlab/anvio#688]
This is in dbops.

For consistency reasons the current design is not good.
This is the current code:
```
self.gene_level_coverage_stats_dict[gene_callers_id][sample_name] = {'mean_coverage': mean_coverage,
                                                                      'detection': detection,
                                                                      'non_outlier_mean_coverage': non_outlier_mean_coverage,
                                                                      'non_outlier_coverage_std':  non_outlier_coverage_std}

if populate_nt_level_coverage == True:
    self.gene_level_coverage_stats_dict[gene_callers_id][sample_name]['gene_coverage_values_per_nt'] = gene_coverage_values_per_nt
    self.gene_level_coverage_stats_dict[gene_callers_id][sample_name]['non_outlier_positions'] = non_outlier_positions
```

The first four keys of `self.gene_level_coverage_stats_dict`are dict of dicts, but the last (optional) keys are numpy array.

Hence the last two keys (`gene_coverage_values_per_nt`, `non_outlier_positions`) should be in a different object.

This is specifically important for `gene-view`.

**Comment by meren** [comment]
We can certainly do this, but I am not sure if this is really necessary :) The cost here is yet another class object to describe something that can be described in a single dict object, and the gain is not clear to me besides negligible help to the programmer. I also don't like the way this dictionary looks, but since the dictionary data structure can contain mixed data types, there is nothing illegal :)

We could create a class like this and pass that one around:

``` python
class GeneLevelCoverageStats:
    """doc string that explains the type of each variable"""

    def __init__(self):
        self.mean_coverage = {}
        self.detection = {}
        self.non_outlier_mean_coverage = {}
        self.non_outlier_coverage_std = {}
        self.gene_coverage_values_per_nt = None
        self.non_outlier_positions = None

```

**Comment by ShaiberAlon** [comment]
The gain is that in `--gene-view` we allow all the values of `gene_level_coverage_stats_dict` to be views. This only works if all the values of `gene_level_coverage_stats_dict` have the same structure.
See this: https://github.com/merenlab/anvio/blob/613e50fb8e317af36b32179c9e276eda42f585a8/anvio/interactive.py#L896

**Comment by meren** [comment]
Fair enough. But how about being explicit? I.e.,

``` python
all_views = ['mean_coverage', 'detection', 'non_outlier_mean_coverage', 'non_outlier_coverage_std']
```

Too ugly?

**Comment by ShaiberAlon** [comment]
I feel like being explicit is one of those things that we could say "being
explicit is always the best option", so both solutions are probably fine,
but let's go with explocit :-)

**Comment by meren** [comment]
Do you agree with the latest commit? Can we close this? :)

**Comment by ShaiberAlon** [comment]
Yes, thank you Meren
