### ISSUE TITLE
mind-full-splitting log ambigous

### ISSUE THREAD

**Issue by SilasK** [merenlab/anvio#699]
Hello I run `anvi-gen-contigs-database -f {input} -o {output}` and in the log I read:

Splitting pays attention to gene calls? ......: False

Is mind-full-splitting now on or off?

**Comment by meren** [comment]
In theory, splitting pays attention to gene calls when mindful splitting is [ON].

But there was a bug in the reporting (it was doing the right thing in the background but saying the wrong thing in the terminal). We fixed it in the master recently and will be available in `v4`.

Apologies for the confusion.
