### ISSUE TITLE
populate layers order for gene-view

### ISSUE THREAD

**Issue by ShaiberAlon** [merenlab/anvio#705]
need to give `transpose=True` to the function that generates the newick. We will use the same matrices that we use to generate the items orders.

@meren, should the layer orders that are available in `full mode` also be available in `gene mode`? I imagine this would complicate things too much right now, but maybe this is something for the future.

This is related to #663.

**Comment by meren** [comment]
> @meren, should the layer orders that are available in full mode also be available in gene mode? I imagine this would complicate things too much right now, but maybe this is something for the future.

Yes, I think it is too much for now :) we can always bring them later.

**Comment by ShaiberAlon** [comment]
@ozcan, let me know if you want to work on this together this week.

**Comment by meren** [comment]
They are not too hard at all :)

**Comment by ShaiberAlon** [comment]
@meren, we decided to make all layers orders from full mode available. For the new orders that are created ad hoc for gene view, we added a prefix `genes_`, e.g. `genes_detection (tree)`, let us know if you have any comments. This will of course be fully described in the amazing tutorial that we will write. It will be a great tutorial, like nothing you have seen before, believe me.

**Comment by meren** [comment]
I have no comments. You guys seem to be on top of it! :) Thank you for keeping me posted.
