### ISSUE TITLE
master cannot runs full suite test

### ISSUE THREAD

**Issue by ekiefl** [merenlab/anvio#706]
```
Traceback (most recent call last):
  File "/usr/local/bin/anvi-export-gene-calls", line 61, in <module>
    main(args)
  File "/usr/local/bin/anvi-export-gene-calls", line 30, in main
    dbops.is_contigs_db(args.contigs_db)
AttributeError: module 'anvio.dbops' has no attribute 'is_contigs_db'


Config Error: It seems something went wrong while running your tests :/ Anvi'o hopes that the
              reason is clear from the lines above.
```
not sure what's going on.

**Comment by meren** [comment]
![image](https://user-images.githubusercontent.com/197307/35244516-fff47626-ff85-11e7-93d4-ce57bfd8295d.png)

You are not working with up-to-date master. If you are in a branch, run `git merge master`.

**Comment by ekiefl** [comment]
![image](https://user-images.githubusercontent.com/8688665/35246477-71a5d822-ff8c-11e7-9617-ba38fcfb747c.png)

problem persists but goes away after

![image](https://user-images.githubusercontent.com/8688665/35246682-27dcd69a-ff8d-11e7-8714-ad5c161d1dc3.png)
