### ISSUE TITLE
The statistic behind the variability view needs to be more sophisticated

### ISSUE THREAD

**Issue by meren** [merenlab/anvio#712]
The purpose of the variability view (http://merenlab.org/2017/05/08/anvio-views/#variability) was to offer a summary statistic for the amount of SNVs for a given contig in a given sample. While it is not completely useless even in its current form, it certainly does not reflect the _nature_ of the variability data in a helpful manner, and can be improved.

Basically, this is where in the data is summarized per contig in `anvio/contigops.py`:

``` python
 65 class Contig:
   (...)
 80     def get_atomic_data_dict(self):
 81         d = {'std_coverage': self.coverage.std,
 82              'mean_coverage': self.coverage.mean,
 83              'mean_coverage_Q2Q3': self.coverage.mean_Q2Q3,
 84              'max_normalized_ratio': 1.0,
 85              'relative_abundance': 1.0,
 86              'detection': self.coverage.detection,
 87              'abundance': self.abundance,
 88              'variability': sum(s.auxiliary.variation_density for s in self.splits) if not self.skip_SNV_profiling else None,
 89              '__parent__': None}
 90
 91         return d
```

And this is where the variation density is assigned per split in the same module:

``` python
120 class Split:
  (...)
134     def get_atomic_data_dict(self):
135         d = {'std_coverage': self.coverage.std,
136              'mean_coverage': self.coverage.mean,
137              'mean_coverage_Q2Q3': self.coverage.mean_Q2Q3,
138              'max_normalized_ratio': 1.0,
139              'relative_abundance': 1.0,
140              'detection': self.coverage.detection,
141              'abundance': self.abundance,
142              'variability': self.auxiliary.variation_density if self.auxiliary else None,
143              '__parent__': self.parent}
144
145         return d
```

And this is where the action takes place again in the same module:

``` python
148 class Auxiliary:
  (...)
163     def run(self, bam):
  (...)
196         # variation density = number of SNVs per kb
197         self.variation_density = len(ratios) * 1000.0 / self.split.length
  (...)
```

We still need the variation density somewhere (so we can do it better by averaging variation density per split and averaging all splits at the contig level (without summarizing as the current implementation does)). We can call this view something else than `variability`, maybe `variation_density`: the simple statistic of number of variable positions per 100 nts (instead of per 1,000 nts as it is now, so it reflects the percentage of positions that were variable).

But I think we can have a new view by creating a new metric to better understand what is going on inside a given split, a new metric that reflects not only just the occurrence of SNVs, but also their nature (i.e., their magnitude). If every SNV is about 20% is one thing, if all of them are fixed is another, and SNV density does not highlight them for an abstract overview. So this is an open ended question, and lends itself to some experimentation and creative thinking in its current loose form :)

The limitation is that this metric will not know anything about other samples. It will operate only at the level of a single split and its variants in a single sample, but the rest of the data to start playing is available in the module I mentioned above.

**Comment by ekiefl** [comment]
Small point, when you say

> without summarizing as the current implementation does

you mean  summing, right?

what do you think about a split-wide/contig-wide departure from consensus value to fulfil this metric? If a site is determined to be nonvariable then it is given a value of zero. If it is determined to be variable we calculate its departure from consensus. The degree of variation for a split and for a contig is the sum values from each site.  I prefer  consensus over reference because it emphasizes variation between reads rather than polymorphism  compared to the reference.

**Comment by meren** [comment]
> you mean summing, right?

yes :/ sorry.

> what do you think about a split-wide/contig-wide departure from consensus value to fulfil this metric?

I think this could work. I guess the first thing is to create some realistic test cases that we can try different ideas rapidly.
