### ISSUE TITLE
Highlighting or inspecting splits from description markdown

### ISSUE THREAD

**Issue by ozcan** [merenlab/anvio#715]

**Comment by ozcan** [comment]
Looks like this:
![image](https://user-images.githubusercontent.com/940884/35494718-22ecf92c-0482-11e8-8cd8-a85b143c4707.png)

usage: `<item>item_name</item>`

**Comment by ozcan** [comment]
maybe cache issue? because it works at home. did you tried cmd+shift+r?

**Comment by meren** [comment]
Yep :)

**Comment by ozcan** [comment]
Oh okay, I will stop by tomorrow for a second to see on your computer because unfortunately I can not reproduce it :(

**Comment by ozcan** [comment]
the new syntax is similar to classic markdown link syntax, example: `[click here](item://PC_00001)`

**Comment by meren** [comment]
this is much better! thank you, @ozcan.

I think we should consider writing a short blog post to encourage people using the description tab more, and demonstrate some of its capabilities.
