### ISSUE TITLE
Allow to run MCGC from gene-view

### ISSUE THREAD

**Issue by ShaiberAlon** [merenlab/anvio#720]
I want to add a flag`--run-MCGC` to `anvi-interactive`. It will only be available with `--gene-view`, and it will run the classifier, and add additional information to items and to layers from the MCGC output.

## Additional information for items (i.e. for genes)
All the columns of `gene_class_df`, i.e.:'occurence_in_positive_samples', 'occurence_in_negative_samples', 'occurence_in_positive_and_negative_samples', 'specificity', 'coverage_consistency', 'core', 'MCG_class'

## Additional information for layers
All the columns of `samples_information`, i.e.: 'presence', 'detection', 'number_of_taxon_specific_core_detected', 'non_outlier_mean_coverage', 'non_outlier_coverage_std'

@ozcan, I can try to do it myself, and if I fail I will ask for your help.

@ozcan, and @meren, let me know if you have any comments about this please.

**Comment by meren** [comment]
Sounds good to me. If everything looks alright by then, we can run MCGC by default, and add a `--skip-mcgc-analysis` flag at `v5` :)
