### ISSUE TITLE
It would be great to be able to remove custom HMM sources from a contigs db.

### ISSUE THREAD

**Issue by gvanzin** [merenlab/anvio#722]
I've run into an issue where it would be useful to remove a custom HMM source from my contigs db.  I currently can't get anvi-summarize to run, it's likely due to having a custom HMM source.    Thanks!

Gary

Anvi'o version ...............................: 3-master
Profile DB version ...........................: 23
Contigs DB version ...........................: 10
Pan DB version ...............................: 8
Genome data storage version ..................: 5
Auxiliary data storage version ...............: 2

Anvi'o installed from github, run on both Mac and Linux.

**Comment by meren** [comment]
Hi Gary,

If you update your `master`, you should find a new program, `anvi-remove-hmms`.

``` bash
$ anvi-delete-hmms -h
usage: anvi-delete-hmms [-h] -c CONTIGS_DB [--hmm-source SOURCE NAME] [-l]
                        [--just-do-it]

Remove HMM hits from an anvi'o contigs database.

optional arguments:
  -h, --help            show this help message and exit
  -c CONTIGS_DB, --contigs-db CONTIGS_DB
                        Anvi'o contigs database generated by 'anvi-gen-
                        contigs'
  --hmm-source SOURCE NAME
                        Use a specific HMM source. You can use '--list-hmm-
                        sources' flag to see a list of available resources.
                        The default is 'None'.
  -l, --list-hmm-sources
                        List available HMM sources in the contigs database and
                        quit.
  --just-do-it          Don't bother me with questions or warnings, just do
                        it.
```

I hope that serves you well :)

Thank you for the report.
