### ISSUE TITLE
Inspect crashes in master when using --report-full-variability in anvi-profile

### ISSUE THREAD

**Issue by ekiefl** [merenlab/anvio#729]
```
Anvi'o version ...............................: 3-master
Profile DB version ...........................: 23
Contigs DB version ...........................: 10
Pan DB version ...............................: 8
Genome data storage version ..................: 5
Auxiliary data storage version ...............: 2
```

[for_github.tar.gz](https://github.com/merenlab/anvio/files/1695946/for_github.tar.gz)

The tar.gz is the full working directory of the project (it's very small)

After clicking inspect, a portion of the inspect interface renders non-interactively and then:

![image](https://user-images.githubusercontent.com/8688665/35816556-9ee5f7f2-0a60-11e8-8473-0f6893534f8c.png)

**Comment by ozcan** [comment]
It works on my computer but I see why it may crash, there are simply too many insignificant SNVs. Do we have a way to filter these SNVs @ekiefl @meren?

![screen shot 2018-02-05 at 10 51 03 am](https://user-images.githubusercontent.com/940884/35817315-a6cd0bb6-0a62-11e8-8f1e-f5df70a8e523.png)
.

**Comment by ekiefl** [comment]
Yeah I guess there's just too much rendering. We discussed that report full variability should be used only in controlled circumstances when sequencing errors are known or  can be accounted for. If we decide to develop more  on this front I think a good place to start would be working on how we detect a variable position. currently it is

![image](https://user-images.githubusercontent.com/8688665/35833870-94d84ad4-0a98-11e8-80f8-58d1f927636e.png)
