### ISSUE TITLE
ModuleNotFoundError: No module named 'anvio'

### ISSUE THREAD

**Issue by xavierfe** [merenlab/anvio#731]
Hi, 
 
I had installed anvi'o using miniconda and the anvi self testt worked. Kept on scrolling down and didn't notice "installation whit various levels of pain" was the same and went and installed the individual packages. Now when I try to run the test I get this...

  File "/home/main/virtual-envs/anvio-3/bin/anvi-self-test", line 12, in <module>
    import anvio
ModuleNotFoundError: No module named 'anvio'

Thanks,

Frank

**Comment by meren** [comment]
Hi Frank,

You can start with this command:

rm -rf /home/main/virtual-envs/anvio-3/


Which should make your conda installation active again.


Best,

--

A. Murat Eren (meren)
http://merenlab.org :: twitter <https://twitter.com/merenbey> :: gpg
<https://keybase.io/meren>

**Comment by xavierfe** [comment]
Hi Meren,

It worked, thanks!

Frank
