### ISSUE TITLE
Problem with parsing "noise_cutoff_terms" for custom HMM collection

### ISSUE THREAD

**Issue by brymerr921** [merenlab/anvio#737]
Hi,

I'm using the master branch, I'm attempting to use a custom HMM collection in Anvi'o. While working with the new `noise_cutoff_terms.txt` file (see #498, #725, [Google groups thread](https://groups.google.com/forum/#!topic/anvio/0gVMSEAwuE0)), I discovered that while I can specify E-value cutoffs in  `noise_cutoff_terms.txt` such as "-E 1e-12", I am unable to specify domain evalue cutoffs, such as "--domE 1e-18". I think because the flag is not incorrectly, but I'm not sure.

For example, when  `noise_cutoff_terms.txt` contains "--domE 1e-18" and I try to run `anvi-run-hmms`, I get the following error.

Error result from `anvi-run-hmms`:
```
Config Error: Something went wrong with hmmscan, and it failed to generate the expected output
              :/ Fortunately, this log file should tell you what might be the problem:
              '/tmp/tmp5o81vgkx/00_log.txt'. Please do not forget to include this file if you
              were to ask for help.
```

The file `/tmp/tmp5o81vgkx/00_log.txt` contains the following:
```
# DATE: 05 Feb 18 16:37:35
# CMD LINE: hmmscan -o /tmp/tmp5o81vgkx/hmm.output --domE 1e-18 --cpu 16 --tblout /tmp/tmp5o81vgkx/hmm.hits.shitty /tmp/tmp5o81vgkx/hmm.txt /tmp/tmp5o81vgkx/aa_gene_sequences.fa
Failed to parse command line: No such option "--domE 1e-18".
Usage: hmmscan [-options] <hmmdb> <seqfile>

where most common options are:
  -h : show brief help on version and usage

To see more help on available options, do hmmscan -h
```

However, when I copy/paste the `CMD LINE:` command into my terminal as follows and run it:
```
hmmscan -o /tmp/tmp5o81vgkx/hmm.output --domE 1e-18 --cpu 16 --tblout /tmp/tmp5o81vgkx/hmm.hits.shitty /tmp/tmp5o81vgkx/hmm.txt /tmp/tmpd_a1d0gi/aa_gene_sequences.fa
```
It runs just fine.

Investigating the script [`anvio/drivers/hmmer.py`](https://github.com/merenlab/anvio/blob/24ae09df3a6af0e8de560d03b01216f18c39a9d7/anvio/drivers/hmmer.py), when I change `noise_cutoff_terms` in line 110 (master):
https://github.com/merenlab/anvio/blob/24ae09df3a6af0e8de560d03b01216f18c39a9d7/anvio/drivers/hmmer.py#L109-L113

 or `cut_off_flag` in line 109 (version 3):
https://github.com/merenlab/anvio/blob/938d01f8d65ca97969e2c01e793a15e0a13a2457/anvio/drivers/hmmer.py#L108-L112

 to `"--domE 1e-18"`, it fails. If I instead change it to `"--domE","1e-18"`, everything works! Not sure why... can anyone confirm whether this issue is specific to me?

Best,
Bryan

**Comment by meren** [comment]
Hi Bryan,

Sorry for the late response. It wasn't specific to you :) Just for future notes, the correct solution was to change `noise_cutoff_terms` variable to `*noise_cutoff_terms.split()` (I'm sure @ozcan would be proud of me), so every variable and their parameters represent single items in the list.

Thank you very much for reporting this.

**Comment by brymerr921** [comment]
Thanks so much! I'll give it a whirl.
