### ISSUE TITLE
Add some kind of animation to Draw button if there is no default state

### ISSUE THREAD

**Issue by ozcan** [merenlab/anvio#739]
First-time users get confused about this, this will make it clearer.

**Comment by meren** [comment]
yes. this is quite correct. maybe it could blink with a green flash every second or something if they are just staring at the empty screen :)

**Comment by ozcan** [comment]
Looks like this: https://i.imgur.com/jL1k818.gifv
Feel free to change this file for tweaking the animation: https://github.com/merenlab/anvio/blob/master/anvio/data/interactive/css/glowing-button.css

**Comment by meren** [comment]
This certainly solves this!

New issue: the Draw button is so cute, it makes people to not use default states anymore so they can see it.
