### ISSUE TITLE
make inspect load faster when layers are set to zero

### ISSUE THREAD

**Issue by ShaiberAlon** [merenlab/anvio#741]
When you set the height of some layers to zero then they don't show up in the inspect page (and that's great), but it seems like the data for these layers is still loaded when you do inspect. And so even though you might be looking only at the data from a few layers, you end up waiting a long time as the data for all layers is loaded. If it is not too complicated to change that behavior that would be great.

**Comment by ozcan** [comment]
This is brilliant @ShaiberAlon, I will try to implement this, it supposed to be simple.

**Comment by ShaiberAlon** [comment]
The credit goes to @meren, who noticed this when we were working together two weeks ago. But I will take the credit for remembering to create an issue :-)

Thank you for looking at this ozcan!!

**Comment by meren** [comment]
Meren accepts no credit: followups and responsible initiatives are much more valuable than raw ideas! Thank you both for looking into this :)
