### ISSUE TITLE
Starting with anvio

### ISSUE THREAD

**Issue by atarauzan** [merenlab/anvio#743]
Hi!

I would like to start work with anvio but Im not sure that the files that I have are OK.
For each sample that I send for sequencing I got two fasta files (R1 and R2) and I also got the the whole genome for certain bacteria that we are intrested in. 
And I wants to compere this specific bacterias between the different samples.
I hope I am clear
Thank you very much
Atara  :-)

**Comment by meren** [comment]
Hi Atara,

Maybe you can start by reading some of our tutorials listed under the pull-down menu at http://merenlab.org/software/anvio/

Also our anvi'o slack channels may be helpful to ask general questions.

What you posted is a very general question that is not quite easy to address through, or relevant to, GitHub issues.

Best wishes,
