### ISSUE TITLE
A generic resource on "how to get help"

### ISSUE THREAD

**Issue by meren** [merenlab/anvio#744]
We need a single page resource that lists all ways to get help for current and new anvi'o users of different levels.

We will likely see more and more of issues such as #743 , and if we want to help such general questions, we should be able to direct people to best resource they can access to within or outside of anvi'o.

**Comment by watsonar** [comment]
From most general to least general I can think of the following resources: website tutorials, Slack channel, github issue, emailing developers. Am I missing any?

**Comment by meren** [comment]
Not really :)

We can also start from even earlier. Metagenome a is this. Here are some papers. Genome-resolved metagenome is better. Read these if you don't believe it lol. Pangenomics is this. Here are some stuff. Etc. Anvi'o can help you with these, so can these other tools. If you want to try anvi'o but need help, here is the list of ways you can get it from most general to least.

**Comment by ShaiberAlon** [comment]
Meren, I agree with you that a general overview of key features  would be helpful (interactive interface, anvi-server, assembly-based binning and metagenomics, reference based, variability, pangenomics, phylogenomics,  meta-pan-phylo-inter-servo-genomics, etc.).

In addition, I think we should divide the software available through anvi'o into categories. And then create a pdf with the list of all programs (divided into categories so it is easier to look through) and each link would take you to the relevant help menu. This would utilize the pre-existing help menus, and would address the slack question we just got. Here are some categories I thought of:

1. database operations (all the `anvi-delete-...` `anvi-import-`, `anvi-export`)
2. interactive displays (`anvi-interactive`, `anvi-display`, `anvi-display-contigs-stats`)
3. Exploring sequences (all the `anvi-get-...-sequences`)
4. clusterings etc. (`anvi-cluster-with-concoct`, `anvi-experimental-organization`, `anvi-matrix-to-newick`)
5. Binning
6. variability
7. pangenomics
8. phylogenomics
9. functions and hmms
10. other :-)

(this is just an initial idea, and my purpose is to generate further discussion if people like this direction).

Another more complicated implementation (if we feel adventurous) is to give each program labels (like the titles above), and each program could have multiple labels, then we can use that to generate a network, where each node of the network is an anvio program, and when you click on a node it takes you to the relevant help menu. All related programs would have an edge connecting them, and would also be closer together accordingly :-)

**Comment by ShaiberAlon** [comment]
Now that anvio vignette exists can we close this issue?

**Comment by meren** [comment]
I think "how to get help" is not necessarily addressed by vignette. Vignette can serve as a resource from within that hypothetical document for one item (i.e., "if you want to see all anvi'o programs and learn about them see [link to vignette]), but it doesn't really the "how to get help" document itself :)

**Comment by ekiefl** [comment]
In addition to vignettes, we also now have http://merenlab.org/vocabulary/ and `anvi-help`. We need a wiki imo

**Comment by ekiefl** [comment]
I think we may finally be able to lay this issue to rest. At the top of the homepage for our [connected network of documentation](https://merenlab.org/software/anvio/help/main/) is a bunch of notices that provide different sources for "how to get help".

Perhaps its more suitable to move these notices to https://merenlab.org/software/anvio/#help, where one of them would link to https://merenlab.org/software/anvio/help/main/

What do you think @meren and others?

**Comment by ekiefl** [comment]
Nevermind! We have an explicit "how to get help page": https://merenlab.org/2019/10/07/getting-help/ written by @ivagljiva. Since this post summarizes every source of help, I took the liberty of this commit: febc5859f21376a708e7399467c170479c8cee45

Hope people agree with making this more accessible.

Regardless, closing this issue.

**Comment by meren** [comment]
I like this solution! Thank you, @ekiefl!
