### ISSUE TITLE
Issue combining external and internal genomes in phylogenomics pipeline (specifically, anvi-get-sequences-for-hmm-hits)

### ISSUE THREAD

**Issue by jpod1010** [merenlab/anvio#747]
I am running Ubuntu 16.04. 

```
anvi-self-test --version output:
Anvi'o version ...............................: 3
Profile DB version ...........................: 20
Contigs DB version ...........................: 9
Pan DB version ...............................: 5
Samples information DB version ...............: 2
Genome data storage version ..................: 1
Auxiliary data storage version ...............: 4
Anvi'server users data storage version .......: 1
```

when running anvi-get-sequences-for-hmm-hits, internal and external genomes cannot be combined, as the this command does not accept an --internal-genomes file. It allows either the the use of a contigs.db and profile.db, or an external-genomes file, but not both. This issue references a conversation had between Meren and user 'Justin Podowski' here: http://disq.us/t/2pewh70

Thanks!

Justin Podowski

**Comment by meren** [comment]
this feature is now available and will be a part of `v5`.

thank you for your patience!

**Comment by ShaiberAlon** [comment]
Hi Meren, I just tried to use this feature with the latest version on github, and it only gave me an output for my external genomes, and non of the internal genomes.

**Comment by ShaiberAlon** [comment]
@meren, I have managed to reproduce this problem with the following simple example:

I ran the mini test, and then used the following internal and external genomes files:
[internal-genomes.txt](https://github.com/merenlab/anvio/files/2321193/internal-genomes.txt)
[external-genomes.txt](https://github.com/merenlab/anvio/files/2321194/external-genomes.txt)

And then I ran:

```bash
anvi-get-sequences-for-hmm-hits --internal-genomes internal-genomes.txt --external-genomes external-genomes.txt --return-best-hit                  --concatenate-genes  --get-aa-sequences  --hmm-sources Campbell_et_al -o temp.txt
```

```bash
$ cat temp.txt

>g2 num_genes:2|genes:S-AdoMet_synt_C,S-AdoMet_synt_M|separator:XXX
MAELKLISAESVTEGHPDKVCDQISDAILDDMLAQDPHSHVAVETCATVGQFFVFGEVTSEGYSDIQNIVRSVVRNIGYTSSRVGLDADSCGVTVSLTEQSPEINQGVARLSGEEESKAS
REQRYEAQGAGDQGVMFGYACDETDVLMPLPIHLAHRLAYRLAEVRKSGEVPHLRPDGKTQVTIEYDDDDHPVRLDTVLVSTQHDPEVDQAWLKEQLTEHVIRPVLDDVLADRVAHGEYR
VLVNPTGSFILGGPAADAGLTGRKIIVDTYGGAAHHGGGAFSGKDPSKVDRSAAYAARWVAKNIVAAGLAHKVEVQVAYAIGVADPVSINVETYGTEIGVTREQIQQAVRKVFDLRPAAI
IDELDLKRPIYSKTAAYGHFGREDADFTWEATNMVDELKEAIKAXXXMAELKLISAESVTEGHPDKVCDQISDAILDDMLAQDPHSHVAVETCATVGQFFVFGEVTSEGYSDIQNIVRSV
VRNIGYTSSRVGLDADSCGVTVSLTEQSPEINQGVARLSGEEESKASREQRYEAQGAGDQGVMFGYACDETDVLMPLPIHLAHRLAYRLAEVRKSGEVPHLRPDGKTQVTIEYDDDDHPV
RLDTVLVSTQHDPEVDQAWLKEQLTEHVIRPVLDDVLADRVAHGEYRVLVNPTGSFILGGPAADAGLTGRKIIVDTYGGAAHHGGGAFSGKDPSKVDRSAAYAARWVAKNIVAAGLAHKV
EVQVAYAIGVADPVSINVETYGTEIGVTREQIQQAVRKVFDLRPAAIIDELDLKRPIYSKTAAYGHFGREDADFTWEATNMVDELKEAIKA
```

So as you can see this only returns the hit for external genome.

**Comment by ShaiberAlon** [comment]
Actually the above example is even more weird, because it only gives an output for the internal genome (which makes no sense because the internal genome is a subset of the external genome, since I used the same contigs database for both.... but maybe that's what causing trouble here).

**Comment by meren** [comment]
It is done.
