### ISSUE TITLE
Can't combine two different gene caller sources in 'anvi-gen-genomes-storage'

### ISSUE THREAD

**Issue by brymerr921** [merenlab/anvio#749]
Hi,

I have several genomes I'm trying to analyze in one pan-genome. Some were downloaded from NCBI and I've written a script to to import the exact gene calls using `anvi-gen-contigs-database ... --external-gene-calls`. I've named the gene call source "NCBI GenBank". I also have some genomes I've assembled from reads and annotated using Prodigal. However, when I make an external genomes file to feed to `anvi-gen-genomes-storage`, I get an error saying that the one with GenBank gene calls doesn't have any gene calls. I think it's looking for Prodigal annotations. Using the "Pro option" `--gene-caller` doesn't help either, because I can only specify one gene caller here.

 I understand that there are several good reasons for using the same annotation source for all genomes in a pan-genome analysis... but, I want to be rebellious. Mostly it's just important that the genes I'm comparing are the same as the ones that are currently described in GenBank.

Is there a way my odd request could be accommodated? For example, adding an additional column to the internal or external genomes files to specify annotation source per genome? Thanks!

Best,
Bryan

**Comment by meren** [comment]
Hi Bryan,

From a cleaner design perspective I think the best way is to create a new gene caller name "i.e., `bryans`" and use it for all gene calls to combine Prodigal and GenBank calls. Sadly this is the only viable solution I can think of :(

if you want to be rebellious, you can open your databases in the DB Browser for SQLite, and manually change them before you re-create your genomes storage.


Best,
