### ISSUE TITLE
Issue with  ‘anvi-gen-genomes-storage’

### ISSUE THREAD

**Issue by sipesk** [merenlab/anvio#751]
Not surprisingly, I’m struggling to get past the ‘anvi-gen-genomes-storage’ command.

I’ve successfully used the anvi-script-FASTA-to-contigs-db for two FASTA files. I created a .txt file for the name and the contigs_db_path of the two genomes.

This is the script

```
(anvio-3) barbara-lloydlab@lloydbarbara:~/Desktop/KBaseKatie/amini.metagenomes.annotated$ anvi-gen-genomes-storage -e external_genomes.txt -o amini-GENOMES.h5
Traceback (most recent call last):
File "/home/barbara-lloydlab/virtual-envs/anvio-3/bin/anvi-gen-genomes-storage", line 52, in <module>
pan.create_genomes_data_storage()
File "/home/barbara-lloydlab/virtual-envs/anvio-3/lib/python3.5/site-packages/anvio/genomestorage.py", line 140, in create_genomes_data_storage
self.load_genomes_descriptions()
File "/home/barbara-lloydlab/virtual-envs/anvio-3/lib/python3.5/site-packages/anvio/genomedescriptions.py", line 141, in load_genomes_descriptions
if not path.startswith('/'):
AttributeError: 'NoneType' object has no attribute ‘startswith'
```

here is the external-genomes.txt:

```
name	contigs_db_path
amini	/home/barbara-lloydlab/Desktop/KBaseKatie/amini.metagenomes.annotated/2264867188.db
148bin03	/home/barbara-lloydlab/Desktop/KBaseKatie/amini.metagenomes.annotated/PROKKA_02202018.db
```

**Comment by sipesk** [comment]
here is the link to my external genomes .txt file.
https://github.com/sipesk/anvio_pangenomic/tree/master/amini.metagenomes.annotated

**Comment by meren** [comment]
Hi,

Your file has an empty line at the end. Anvi'o catches this, but your empty line is empty with the right number of columns :) We will now catch that, too.

If you remove the last line from your file you are good to go.

Thanks for the report.
