### ISSUE TITLE
anvi-script-FASTA-to-contigs-db not recognizing .fa files

### ISSUE THREAD

**Issue by Derreckadam** [merenlab/anvio#755]
Anvi'o version ...............................: 3
Profile DB version ...........................: 20
Contigs DB version ...........................: 9
Pan DB version ...............................: 5
Samples information DB version ...............: 2
Genome data storage version ..................: 1
Auxiliary data storage version ...............: 4
Anvi'server users data storage version .......: 1

OS: High Sierra on Mac. I installed it with Homebrew.

I am having problems getting anvi-script-FASTA-to-contigs-db to accept my ncbi genomes. 
The error I get, "File name has to have an extension of '.fa'"
Anvi think's I'm not supplying a file with the .fa extension, but I promise I am. 

I converted all my genomic.fna.gz from NCBI to .fa the following way: 
gunzip *.gz
for file in *.fna; do b=$(basename $file .fna); echo $b; mv $file $b.fa; done

When I tried using the fasta files from the closely_related salmonella species in the phylo_example tutorial, I get past the initial step, but then I get a error with anvi-script-reformat-fasta: unrecognized arguments: .../Phylo_example/AnvioPhylogenomicsTutorialDataPack/closely-related/Salmonella_enterica_21170.fa .../Phylo_example/AnvioPhylogenomicsTutorialDataPack/closely-related/Salmonella_enterica_21170-clean.fa .../Phylo_example/AnvioPhylogenomicsTutorialDataPack/closely-related/Salmonella_enterica_21170-MAP.txt

I don't know if this is two issues or one. I have been able to run my own fasta files, annotated by Prokka, just not any I downloaded from NCBI, or from the tutorial. 

Okay, sorry, thanks!

**Comment by meren** [comment]
I can't reproduce this error.

Please use the programs `anvi-script-reformat-fasta`, `anvi-gen-contigs-database`, and `anvi-run-hmms` do create a contigs database instead of `anvi-script-FASTA-to-contigs-db`.

**Comment by msevi** [comment]
I had the same issue. If you run the converted fa file through anvi-script-reformat-fasta and pass the output to anvi-script-FASTA-to-contigs-db it runs without error.
