### ISSUE TITLE
Bug: Hex color code incorrect in pangenome display

### ISSUE THREAD

**Issue by rbartelme** [merenlab/anvio#758]
Anvi'o v4 master:

After coloring rings to correspond to particular clades, and saving the default view in the anvi-pangenome database. The correct colors appear next to each layer name, but when I click the color to get the hexcode to make it consistent across all figures, it displays the incorrect code. For example, one clade is magenta in color, and shows hex color code #3289c7 rather than something like, #f920e4, which would be closer to the actual color in the figure.

I don't know if this bug extends to the metagenome db display as well?

**Comment by ozcan** [comment]
Thank you for reporting this bug @rbartelme.
