### ISSUE TITLE
`--concatenate-gene-clusters` produces a _mostly_ empty file

### ISSUE THREAD

**Issue by ekiefl** [merenlab/anvio#759]
Working on the pangenome in the metapangenomics paper, when the above flag is provided the gene sequences are empty and the file looks like this:

`anvi-get-sequences-for-gene-clusters --report-DNA-sequences -p Prochlorococcus-PAN-PAN.db -g Prochlorococcus-PAN-GENOMES.db -o concatenated_alignment.fa --min-num-genomes-gene-cluster-occurs 31 --max-num-genes-from-each-genome 1 --concatenate-gene-clusters --align-with muscle`

```
Mode .........................................: Reporting alignments for all gene clusters.
Genomes storage .............................................: Initialized (storage hash: fed45e7c)
Num genomes in storage ......................................: 31
Num genomes will be used ....................................: 31
Pan DB ......................................................: Initialized: Prochlorococcus-PAN-PAN.db (v. 8)

* Gene clusters are initialized for all 7386 gene clusters in the database.


GENE CLUSTER FILTERS
==============================================================
Based on --min-num-genomes-gene-cluster-occurs 31, --max-num-genomes-gene-
cluster-occurs 31, --min-num-genes-from-each-genome 0, and --max-num-genes-from-
each-genome 1 (some of these may be default values, no need to panic).

All gene clusters (7386) ....................................: GC_00003471, GC_00007224, GC_00002325, (... 7383 more (`--debug` will show all))
Gene clusters that passed the filter (660) ..................: GC_00000659, GC_00000645, GC_00000249, (... 657 more (`--debug` will show all))
Genes clusters that filed the filter (6726) .................: GC_00003471, GC_00007224, GC_00002325, (... 6723 more (`--debug` will show all))

Sequence type ...............................................: DNA
Output file for phylogenomics ...............................: concatenated_alignment.fa
```

```
>AS9601

>CCMP1375

>EQPAC1

>GP2

>LG

>MED4

>MIT9107

>MIT9116

>MIT9123

>MIT9201

>MIT9202

>MIT9211

>MIT9215

>MIT9301

>MIT9302

>MIT9303

>MIT9311

>MIT9312

>MIT9313

>MIT9314

>MIT9321

>MIT9322

>MIT9401

>MIT9515

>NATL1A

>NATL2A

>PAC1

>SB

>SS2

>SS35

>SS51

```

--------------------------------

when I run the same command without the flag it produces the following log and the output file looks like it's supposed to:

```
Mode .........................................: Reporting alignments for all gene clusters.
Genomes storage .............................................: Initialized (storage hash: fed45e7c)
Num genomes in storage ......................................: 31
Num genomes will be used ....................................: 31
Pan DB ......................................................: Initialized: Prochlorococcus-PAN-PAN.db (v. 8)

* Gene clusters are initialized for all 7386 gene clusters in the database.


GENE CLUSTER FILTERS
==============================================================
Based on --min-num-genomes-gene-cluster-occurs 31, --max-num-genomes-gene-
cluster-occurs 31, --min-num-genes-from-each-genome 0, and --max-num-genes-from-
each-genome 1 (some of these may be default values, no need to panic).

All gene clusters (7386) ....................................: GC_00001203, GC_00004587, GC_00001891, (... 7383 more (`--debug` will show all))
Gene clusters that passed the filter (660) ..................: GC_00000554, GC_00000205, GC_00000443, (... 657 more (`--debug` will show all))
Genes clusters that filed the filter (6726) .................: GC_00001203, GC_00004587, GC_00001891, (... 6723 more (`--debug` will show all))

Sequence type ...............................................: DNA
Num sequences reported ......................................: 20,460
Output FASTA file ...........................................: concatenated_alignment.fa
```

**Comment by zhaoc1** [comment]
I have encountered into the same problem as well.

**Comment by ekiefl** [comment]
I created a test case at `/groups/merenlab/people/ekiefl/delete_when_done`

`anvi-get-sequences-for-gene-clusters --report-DNA-sequences -p Prochlorococcus-PAN-PAN.db -g Prochlorococcus-PAN-GENOMES.db -o something.fa --gene-cluster-ids-file cluster_ids --debug` produces the expected output.

`anvi-get-sequences-for-gene-clusters --report-DNA-sequences -p Prochlorococcus-PAN-PAN.db -g Prochlorococcus-PAN-GENOMES.db -o something.fa --gene-cluster-ids-file cluster_ids --align-with asdfadf --debug` produces the  Same output is above even though `asdfasdf` is not an aligner.

`anvi-get-sequences-for-gene-clusters --report-DNA-sequences -p Prochlorococcus-PAN-PAN.db -g Prochlorococcus-PAN-GENOMES.db -o nothing.fa --gene-cluster-ids-file cluster_ids --align-with muscle --concatenate --debug` produces nothing.

`anvi-get-sequences-for-gene-clusters --report-DNA-sequences -p Prochlorococcus-PAN-PAN.db -g Prochlorococcus-PAN-GENOMES.db -o nothing.fa --gene-cluster-ids-file cluster_ids --align-with asdfasdf --concatenate --debug` Also produces nothing and is not given errors that asdfasdf  is not an aligner.

**Comment by meren** [comment]
how about running it with this instead: `--align-with famsa --concatenate --debug`

**Comment by ekiefl** [comment]
> how about running it with this instead: --align-with famsa --concatenate

same thing

**Comment by vnsriniv** [comment]
Hi,

I am having the same issue. It works without the `--concatenate-gene-clusters` flag but with the flag, it outputs an empty file with just the fasta headers.. I am using v4. 

Varun

**Comment by wegnerce** [comment]
Salut,
I ran into the same issue (anvio v4) and fixed it with a python script that concatenates the sequences (output 'anvi-get-sequences-for-gene-clusters' without the concatenate flag) based on the information given in the defline. If you guys still need it I would be happy to share it.

Best

Carl-Eric

**Comment by meren** [comment]
Dear @wegnerce, @vnsriniv, @zhaoc1, and @ekiefl. I finally had a chance to look into this issue. It was quite a silly bug :(

Just adding the following line here fixed it: 

https://github.com/merenlab/anvio/commit/eb805a3e95cd0ad29b92c93eff52956fca250309#diff-953c7d64976b6497cd1638283971e459R1049

But while I was at it I improved things a bit more.  I am sorry it took this long, but things now seem to be working in `master`. Please let me know if you run into any problem, and thanks for your patience!

**Comment by vnsriniv** [comment]
Thanks Meren! Appreciate it!
