### ISSUE TITLE
Docker error on Linux Mint VM

### ISSUE THREAD

**Issue by cirodri1** [merenlab/anvio#763]
![image](https://user-images.githubusercontent.com/36938244/36823196-b7ce075c-1cb0-11e8-9310-a3c418b6bde4.png)

I downloaded a virtual machine and install Linux Mint- after that I followed the steps in here http://merenlab.org/2015/08/22/docker-image-for-anvio/ for docker installation.When running the anvi-self-test it says something went wrong while running the test.. the message says: Valueerror: source code string cannot contain null bytes

**Comment by meren** [comment]
But how.

**Comment by meren** [comment]
This is not how you report issues. If you don't fix it in 20 minutes I will block you from this organization.

**Comment by cirodri1** [comment]
This is the exact output error I receive after running the sample test in
the Linux mint virtual box with docker:





Cynthia I. Rodriguez
Ph.D. Student
Ecology and Evolutionary Biology
University of California, Irvine

**Comment by cirodri1** [comment]
![image](https://user-images.githubusercontent.com/36938244/36823086-34942948-1cb0-11e8-8ab5-f70bb94c73c6.png)

**Comment by cirodri1** [comment]
I truly apologize, I am very new at all this computer stuff, how would you like me to solve it? by deleting the message?

Again, I apologize.

**Comment by meren** [comment]
No worries :) you did fix it by providing appropriate information. Thank you.

Next time try a short title, and write the description in the description box after reading the instructions in that box.

**Comment by meren** [comment]
Cynthia, it seems people run into similar issues when they were trying to run Docker from within a virtual environment.

You don't need to run anvi'o docker image from within a virtual machine on windows. You need to install Docker tools for Windows, and use it directly from within Windows. 

Unfortunately, as far as I can see, there is nothing we can do on anvi'o side to solve this error.
