### ISSUE TITLE
error when installing anvio with Docker tools for Windows, and use it directly from within Windows

### ISSUE THREAD

**Issue by cirodri1** [merenlab/anvio#765]
![image](https://user-images.githubusercontent.com/36938244/36873612-d98630ec-1d5d-11e8-8fe1-3fd480c99c27.png)

I downloaded Docket tools for Windows and followed the steps for Anvio installation using the following link: http://merenlab.org/2015/08/22/docker-image-for-anvio/
$ docker run -p 8080:8080 -it meren/anvio:latest
$ anvi-self-test

and I obtained that configuration error.

I also tried downloading Anvio through the virtual machine and obtained the same issue.

And when I tried downloading Anvio through the long steps in the virtual machine it keeps giving me Python 2 as the version, even though I have updated and installed version 3 of Python.

Any suggestions? I need to download Anvio before the workshop that will be given at UCI.

**Comment by meren** [comment]
This is a bug on our part. We will fix that as soon as we can :)

Thank you for your patience!

**Comment by meren** [comment]
Hi!

We just recompiled the Docker image. Please remove the docker image you have, and re-download it or update it. 

Then you should be able to run the following without any issue:

``` bash
anvi-self-test --suite mini
```

Can you please let us know if this works for you?

**Comment by cirodri1** [comment]
Thank you very much, I have been trying to uninstall and install Docker toolbox so I can try it but I keep getting this message when I open Docket Quickstart:
![image](https://user-images.githubusercontent.com/36938244/36882433-b799e084-1d88-11e8-9e1a-4c289c595b46.png)

I am trying to solve this currently to see if your debugging work... thank you very much for your help!

**Comment by meren** [comment]
Great! Thanks for reporting back.

> Does this mean I am good to go to attend the workshop hosted at UC-Irvine?

Yes, certainly :)

> To access Anvio in the future how can I call it in Docker?

When you start Docker, it will be ready to run. Just like the way you typed and run `anvi-self-test`, you could have run other anvi'o commands. Go to your Docker terminal, type `anvi-` and press TAB key twice fast, and you will see all available anvi'o commands.


Best,

**Comment by meren** [comment]
interesting. what happens when you type this and press enter:

```
anvi-interactive -v
```

**Comment by cirodri1** [comment]
![image](https://user-images.githubusercontent.com/36938244/36883948-809a456a-1d92-11e8-9644-f9fed666ad97.png)

It says command not found :/

**Comment by meren** [comment]
Oh wait, this doesn't look like the anvi'o Docker. I think you are running a different Docker image somehow.

The anvi'o docker image should have a terminal that looks like this:

```
 :: anvi'o ::  / >>>
```

**Comment by cirodri1** [comment]
I have these two icon in my desktop:
![image](https://user-images.githubusercontent.com/36938244/36884215-4697fd38-1d94-11e8-9ca1-22d4ea85cd6a.png)

Then I click on DockerQuickstart Terminal and this shows up:
![image](https://user-images.githubusercontent.com/36938244/36884238-790eb6ee-1d94-11e8-9566-5c3dbdebdfcd.png)

From there I do know how how to access Anvio again...

**Comment by SchmidAbby** [comment]
Since this issue is closed I assume everything has been resolved, but I will add that to start the anvi'o Docker image, make sure you first run the command `docker run -p 8080:8080 -it meren/anvio:latest` in the Docker Quickstart Terminal. Then you should see the right terminal. 

Alternatively, if you don't want to deal with Docker and you have Windows 10, I suggest you use the Linux subsystem for Windows (https://docs.microsoft.com/en-us/windows/wsl/install-win10) and then install anvi'o like you would for Ubuntu (https://gist.github.com/meren/f1e674f774a30a209d82).

**Comment by cirodri1** [comment]
@SchmidAbby  Thank you very much for your reply! This was very useful because I thought to access anvi'o I just needed to type $ docker run --rm -it meren/anvio:latest

But with the command you send me I assume now I will be able to get the image through Chrome Browser. Thank you very much!
