### ISSUE TITLE
Running "anvi-run-ncbi-cogs", but output error.

### ISSUE THREAD

**Issue by weihongying** [merenlab/anvio#766]
Hi!

I am running the program **anvi-run-ncbi-cogs** to annotate genes in your contigs database with functions from the NCBI’s Clusters of Orthologus Groups., but output same error messages, listed below:

(anvio3) root@ip-172-31-18-202:~/why/abalone/filtered/merged/megahit_out# anvi-run-ncbi-cogs -c assembled-contigs.db --num-threads 32
COG data directory ...........................: /home/ubuntu/miniconda3/envs/anvio3/lib/python3.5/site-packages/anvio/data/misc/COG
COG data source ..............................: The anvi'o default.
COG data directory ...........................: /home/ubuntu/miniconda3/envs/anvio3/lib/python3.5/site-packages/anvio/data/misc/COG
Searching with ...............................: diamond
Directory to store temporary files ...........: /tmp/tmpuo7ubi5x
Directory will be removed after the run ......: True
Sequences ....................................: 208783 sequences reported.
FASTA ........................................: /tmp/tmpuo7ubi5x/aa_sequences.fa
DIAMOND is set to be .........................: Fast
Diamond blastp results .......................: /tmp/tmpuo7ubi5x/diamond-search-results.daa
Diamond tabular output file ..................: /tmp/tmpuo7ubi5x/diamond-search-results.txt
COG data directory ...........................: /home/ubuntu/miniconda3/envs/anvio3/lib/python3.5/site-packages/anvio/data/misc/COG
COG data source ..............................: The anvi'o default.
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/anvio3/bin/anvi-run-ncbi-cogs", line 49, in <module>
    main(args)
  File "/home/ubuntu/miniconda3/envs/anvio3/bin/anvi-run-ncbi-cogs", line 28, in main
    cogs.process()
  File "/home/ubuntu/miniconda3/envs/anvio3/lib/python3.5/site-packages/anvio/cogs.py", line 121, in process
    self.store_hits_into_contigs_db()
  File "/home/ubuntu/miniconda3/envs/anvio3/lib/python3.5/site-packages/anvio/cogs.py", line 153, in store_hits_into_contigs_db
    COG_ids = cogs_data.p_id_to_cog_id[ncbi_protein_id]
KeyError: '145301428'

I dont understand the KeyError:'145301428'. How to solve this problem？

Please reply to me as soon as possible, thank you.

**Comment by meren** [comment]
This error is fixed in `v4`.

**Comment by weihongying** [comment]
Sorry ，I can not find the solution about the issue mentioned. Can you tell me how to do or provide one links? Thank you.
