### ISSUE TITLE
running anvi-run-ncbi-cogs in anvio4, but still output error.

### ISSUE THREAD

**Issue by weihongying** [merenlab/anvio#770]
(anvio4) root@ip-172-31-18-202:~/why/abalone/filtered/merged/megahit_out# anvi-run-ncbi-cogs -c assembled-contigs.db --num-threads 32
COG data directory ...........................: /home/ubuntu/miniconda3/envs/anvio3/lib/python3.5/site-packages/anvio/data/misc/COG
COG data source ..............................: The anvi'o default.
COG data directory ...........................: /home/ubuntu/miniconda3/envs/anvio3/lib/python3.5/site-packages/anvio/data/misc/COG
Searching with ...............................: diamond
Directory to store temporary files ...........: /tmp/tmpuo7ubi5x
Directory will be removed after the run ......: True
Sequences ....................................: 208783 sequences reported.
FASTA ........................................: /tmp/tmpuo7ubi5x/aa_sequences.fa
DIAMOND is set to be .........................: Fast
Diamond blastp results .......................: /tmp/tmpuo7ubi5x/diamond-search-results.daa
Diamond tabular output file ..................: /tmp/tmpuo7ubi5x/diamond-search-results.txt
COG data directory ...........................: /home/ubuntu/miniconda3/envs/anvio3/lib/python3.5/site-packages/anvio/data/misc/COG
COG data source ..............................: The anvi'o default.
Traceback (most recent call last):
File "/home/ubuntu/miniconda3/envs/anvio3/bin/anvi-run-ncbi-cogs", line 49, in 
main(args)
File "/home/ubuntu/miniconda3/envs/anvio3/bin/anvi-run-ncbi-cogs", line 28, in main
cogs.process()
File "/home/ubuntu/miniconda3/envs/anvio3/lib/python3.5/site-packages/anvio/cogs.py", line 121, in process
self.store_hits_into_contigs_db()
File "/home/ubuntu/miniconda3/envs/anvio3/lib/python3.5/site-packages/anvio/cogs.py", line 153, in store_hits_into_contigs_db
COG_ids = cogs_data.p_id_to_cog_id[ncbi_protein_id]
KeyError: '145301428'

I am running the program anvi-run-ncbi-cogs in anvio4,  but still appear this problem. What should I do?

**Comment by meren** [comment]
> I am running the program anvi-run-ncbi-cogs in anvio4, but still appear this problem. What should I do?

It doesn't look like you are running anvi'o `v4` if you look at the import directories:

```
(...)
File "/home/ubuntu/miniconda3/envs/anvio3/lib/python3.5/site-packages/anvio/cogs.py", line 153,
(...)
```

Do you see how it says `anvio3` there? You have another installation interfering.
