### ISSUE TITLE
small issue with bins displaying >1000% redundancy

### ISSUE THREAD

**Issue by tdelmont** [merenlab/anvio#771]
Hi,

I just realized that when a bin has a redundancy 2000% it is labelled 2Kb%, and as a result when organizing bins in the summary interface based on Redundancy, the highly redundant bin is placed with bins of 2% redundancy, and not as the most redundant one.

Here an example:

<img width="897" alt="screen shot 2018-03-06 at 6 16 07 pm" src="https://user-images.githubusercontent.com/8332889/37047351-e73b841a-216a-11e8-877d-0edd02f5d9cf.png">

Tom

**Comment by ozcan** [comment]
Thanks for reporting @tdelmont :)
