### ISSUE TITLE
issue when running “anvi-run-ncbi-cogs”

### ISSUE THREAD

**Issue by liucong2016** [merenlab/anvio#773]
Hi professor，
i install the anvio4 to running "anvi-run-nvbi-cogs", but error:
anvi-run-ncbi-cogs -c contigs.db --num-threads 32
COG data directory ...........................: /home/ubuntu/miniconda3/envs/anvio4/lib/python3.5/site-packages/anvio/data/misc/COG
COG data source ..............................: The anvi'o default.
COG data directory ...........................: /home/ubuntu/miniconda3/envs/anvio4/lib/python3.5/site-packages/anvio/data/misc/COG
Searching with ...............................: diamond
Directory to store temporary files ...........: /tmp/tmpndlu4w6j
Directory will be removed after the run ......: True
Sequences ....................................: 208783 sequences reported.
FASTA ........................................: /tmp/tmpndlu4w6j/aa_sequences.fa
DIAMOND is set to be .........................: Fast
Diamond blastp results .......................: /tmp/tmpndlu4w6j/diamond-search-results.daa
Diamond tabular output file ..................: /tmp/tmpndlu4w6j/diamond-search-results.txt
COG data directory ...........................: /home/ubuntu/miniconda3/envs/anvio4/lib/python3.5/site-packages/anvio/data/misc/COG
COG data source ..............................: The anvi'o default.
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/anvio4/bin/anvi-run-ncbi-cogs", line 49, in <module>
    main(args)
  File "/home/ubuntu/miniconda3/envs/anvio4/bin/anvi-run-ncbi-cogs", line 28, in main
    cogs.process()
  File "/home/ubuntu/miniconda3/envs/anvio4/lib/python3.5/site-packages/anvio/cogs.py", line 121, in process
    self.store_hits_into_contigs_db()
  File "/home/ubuntu/miniconda3/envs/anvio4/lib/python3.5/site-packages/anvio/cogs.py", line 153, in store_hits_into_contigs_db
    COG_ids = cogs_data.p_id_to_cog_id[ncbi_protein_id]
KeyError: '145301428'

## Then i run "anvi-self-test --version",  it's show:
**Anvi'o version ...............................: 3**
Profile DB version ...........................: 20
Contigs DB version ...........................: 9
Pan DB version ...............................: 5
Samples information DB version ...............: 2
Genome data storage version ..................: 1
Auxiliary data storage version ...............: 4
Anvi'server users data storage version .......: 1

What's the problem, installed is the anvio4, why is the anvio3？ 
i used the command line "conda create -n anvio4 -c bioconda -c conda-forge python=3.5.4 gsl anvio" to install, is it  any mistake?

**Comment by meren** [comment]
Please get in touch with your local bioinformatician friend. This is an installation issue we can't help.
