### ISSUE TITLE
v4 conda installation installs anvi'o v2.1.0

### ISSUE THREAD

**Issue by maureenbug** [merenlab/anvio#780]
Hello!

I tried to install anvio v4 via the conda instructions on the website, and it installed an old version of anvi'o :(

installation command:
```
conda create -n anvio4 -c bioconda -c conda-forge anvio
```

```
$ anvi-self-test --version
Anvi'o version ...............................: 2.1.0
Profile DB version ...........................: 17
Contigs DB version ...........................: 8
Pan DB version ...............................: 4
Samples information DB version ...............: 2
Genome data storage version ..................: 1
Auxiliary data storage version ...............: 3
Anvi'server users data storage version .......: 1
```

If I try to update through conda, it thinks that 2.1.0 is the most up-to-date version.

Thanks in advance!

**Comment by meren** [comment]
Hi @maureenbug,

Today we were talking about this. Please see this conversation:

https://anvio.slack.com/archives/C8SFMGYF3/p1520956926000882

Here is a screenshot of it if you don't have access to Slack:

![image](https://user-images.githubusercontent.com/197307/37366171-b14b1826-26cd-11e8-9aeb-1b3f018b157e.png)

Please let me know if this helps. I also sent an e-mail to John Eppley.

**Comment by maureenbug** [comment]
Awesome, thanks! I'll check out the slack channel, and join the discussion if I still have the same issue after trying some of those suggestions

**Comment by jmeppley** [comment]
That's my fault. I'm still new to developing conda packages, so I'm getting the dependencies wrong.

If your conda installation is based on python2, you have to explicitly request python 3, otherwise it falls back to the most recent anvio that ran on python2. (Coiincidentally, that was anvio v2).

This should work:

`conda create -n anvio4 -c bioconda -c conda-forge python=3 anvio=4`

**Comment by meren** [comment]
I updated the installation instructions on the web via https://github.com/merenlab/web/commit/da997c5174ac8a454fb146723f8dc02a029c908c.

**Comment by maureenbug** [comment]
Thanks! I wrote this in the slack channel, but I'll also mention it here for the record. Specifying python 3 was the issue, and I could install v4 of anvio.
