### ISSUE TITLE
inspect takes a long time to load when many SNVs are present

### ISSUE THREAD

**Issue by ShaiberAlon** [merenlab/anvio#782]
Take an example project and inspect a split with lots of SNVs. It will take many minutes to load.

**Comment by meren** [comment]
Maybe we can add a command line parameter to not initialize SNV data for a given interactive call?

**Comment by ShaiberAlon** [comment]
The best solution for this would be to add another right-click menu option `inpsect without SNVs` that would skip SNV initialization.

**Comment by meren** [comment]
Yes. I think we can add an additional menu item under Inspect that is called 'Inspect (quick)', and it would not load SNVs.

@ozcan is already working with that parts of the code, so I hope he can squeeze this in there.

**Comment by ozcan** [comment]
Gene mode looks like this now:
![screen shot 2018-06-04 at 12 34 09 pm](https://user-images.githubusercontent.com/940884/40932338-9e2ca180-67f3-11e8-8722-721bf6bf26ac.png)

**Comment by meren** [comment]
Ah, this is great news, @ozcan! Thank you!

**Comment by ShaiberAlon** [comment]
Thank you @ozacn!!
