### ISSUE TITLE
call-MAGs is not working in anvi-rename-bins

### ISSUE THREAD

**Issue by watsonar** [merenlab/anvio#792]
Anvi'o version ...............................: 4-master
Profile DB version ...........................: 23
Contigs DB version ...........................: 10
Pan DB version ...............................: 8
Genome data storage version ..................: 6
Auxiliary data storage version ...............: 2

I tried `anvi-rename-bins` with the `call-MAGs` flag and it renamed bins with less than 70% completion MAGs. When I tried using the additional `--min-completion-for-MAG` flag, set to 70, it didn't make a difference.

P.S. working directory in Slack github channel.

Thank you :)

**Comment by meren** [comment]
Could it be because of the 'size' criterion?

I will assign a very large value for it by default.

**Comment by meren** [comment]
OK. I found out that there is nothing wrong. It is just a bit counter intuitive with the size default to call something a MAG. New message should clarify that for those who read :)

**Comment by watsonar** [comment]
Thank you! :)
