### ISSUE TITLE
anvi-display-pan not giving other options under Sample order

### ISSUE THREAD

**Issue by sipesk** [merenlab/anvio#794]
Hello ! 

I have been using the pangenomic workflow to compare genes between bins and downloaded external genomes. I am able to run anvi-display-pan but it is not giving me the option to sort the data by anything else under the Samples > Sample Order tab. I executed both anvi-run-ncbi-cogs and --use-ncbi-blast, when permitted, without errors. Attached is a screen shot of the interactive.
Any direction would be very appreciated.
![march26_anvio_orderbyissue](https://user-images.githubusercontent.com/25647467/37922121-b4942c94-30f9-11e8-917b-d6bdadd9650a.png)

**Comment by meren** [comment]
> Any direction would be very appreciated.

How about we start with the directions we are given when we enter new issues?

I will put a screenshot of the text you removed when you entered your issue as a reminder:

![image](https://user-images.githubusercontent.com/197307/37925225-a97d6c44-30f9-11e8-84a5-27cc619bdeda.png)

--

Spoiler:

sƃuᴉɥʇ ɹǝɥʇo ƃuoɯɐ uoᴉsɹǝʌ o,ᴉʌuɐ ǝɥʇ uoᴉʇuǝɯ oʇ ʇoƃɹoɟ no⅄

**Comment by sipesk** [comment]
So sorry, Mondays aren't good for following directions ... how embarrassing .. 

Anvi'o version ...............................: 3
Profile DB version ...........................: 20
Contigs DB version ...........................: 9
Pan DB version ...............................: 5
Samples information DB version ...............: 2
Genome data storage version ..................: 1
Auxiliary data storage version ...............: 4
Anvi'server users data storage version .......: 1


Using Ubuntu and installed anvio with the workflow on https://gist.github.com/meren/f1e674f774a30a209d82 like a zillion years ago.

**Comment by meren** [comment]
Thanks!

You should upgrade your installation to `v4`, and re-run the pangenome analysis :)
