### ISSUE TITLE
running your own hmm profiles

### ISSUE THREAD

**Issue by tdelmont** [merenlab/anvio#799]
Anvi'o version ...............................: 4
Profile DB version ...........................: 23
Contigs DB version ...........................: 10
Pan DB version ...............................: 8
Genome data storage version ..................: 6
Auxiliary data storage version ...............: 2

I have tried to follow the recipe (http://merenlab.org/2016/05/21/archaeal-single-copy-genes/) to make my own hmm profiles running with anvi'o, without success.

The errors is always this one:

```
Config Error: Each search database directory must contain following files: 'kind.txt',
              'reference.txt', 'genes.txt', 'target.txt', 'genes.hmm.gz', and
              'noise_cutoff_terms.txt'. Rinke_archaeal_HMM does not seem to be a proper
              source. See this blog post to make sure you are doing it the way it should be
              done: http://merenlab.org/2016/05/21/archaeal-single-copy-genes/
```

Since I could not run hmms using the Rinke et al. HMM reference folder (even after adding the file noise_cutoff_terms.txt containing '--cut_ga'), I am putting an issue here.

Here is a [link](https://www.dropbox.com/sh/n6g77fjwcug069r/AAAUFl17j1TFNKC2FMwpcQMDa?dl=0) to the Rinke et al. HMM reference folder I am using for testing:

Many thanks for looking into it, and my apology if this turns out to be a mistake on my side (the nul hypothesis). 

Tom

**Comment by meren** [comment]
I think we fixed it in #737. This collection is working properly with `master`.
