### ISSUE TITLE
FutureWarning when running `anvi-migrate-db -h` (coming from h5py)

### ISSUE THREAD

**Issue by ShaiberAlon** [merenlab/anvio#804]
```
$ anvi-migrate-db -h
/Users/alonshaiber/virtual-envs/anvio-dev/lib/python3.6/site-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
```

I know this isn't our fault, but should we still do something about it?

**Comment by ozcan** [comment]
@alon, I have upgraded the h5py version, so if you run `pip install -r requirements.txt` in main directory, the warning should disappear.

**Comment by meren** [comment]
aha. meanwhile I suggested importing h5py quietly. @ozcan, feel free to revert my commit. @ShaiberAlon, please check both solutions, in case @ozcan keeps my changes they don't screw things up.

**Comment by ozcan** [comment]
Suppressing also seems good to me, we do not really need h5py to print something on screen anyway.

**Comment by ShaiberAlon** [comment]
I just tested, and it looks good. Thank you both!! :-)
