### ISSUE TITLE
Predicting CPR bins in external genomes

### ISSUE THREAD

**Issue by adityabandla** [merenlab/anvio#811]
Using a bunch of external genomes, I built a genomes storage database using anvi-gen-genomes-storage. However, when I tried to predict which of these genomes are CPR using the anvi-script-predict-CPR-genomes, the command fails and asks for a collection name.

Is there a way to bypass this and run this script using only a genomes database?

**Comment by adityabandla** [comment]
Thanks Tom, probably I will shift this discussion to Slack. But just an update, I tried using the command you suggested

`anvi-export-table CONTIGS.db  -l`

However, I get an error saying that the given database does not seem to be a database generated by anvi'o

**Comment by meren** [comment]
You get these kinds of errors only when the process generating your database failed :( I think you should take a look at your  previous log files  or run anvi-gen-contigs-database again.

**Comment by adityabandla** [comment]
@meren I think this is because I ran the command on a genomes storage database and not a contigs database

**Comment by meren** [comment]
nope. genomes storage _is_ an anvi'o database. If anvi'o says "this is not an anvi'o database" the database file must be corrupt.
