### ISSUE TITLE
Anvi'o not remembering imported genes

### ISSUE THREAD

**Issue by SamanthaNicole** [merenlab/anvio#812]
Hi!

I recently asked a question through Disqus on the tutorial board about anvio not remembering my imported gene functions.  It is only remembering the last of three annotations (COGs, pfam, and interpro in that order). It was requested that I make an issue here an report the full output of my anvi-gen-storage command.

Here is my original post:
I've recently run into the problem of Anvi'o not remembering my imported gene functions. I ran COGs using the anvio script and imported PFAM and interproscan annotations using the anvi-import-functions script (in the order of COGs, pfam, then interpro). I then made the genome storage file and the pangenome (anvi-gen-genomes-storage and anvi-pan-genome scripts, respectively). When I visualize the pangenomes the only annotation I see is interpro. This is an example of the script I used to import with no errors reported:

anvi-import-functions -c xanthus_contigs.db -i protein_seqs_gene_calls/interpro_out/xanthus_aa_gene_calls_interpro.txt -p interproscan

I am not using the drop previous annotations flag, so I don't know why only the last annotation is appearing. I got this to work just fine a week or two ago for a different dataset and followed the same steps as then, with the exception of using famsa to align instead of muscle, to no avail. I even started from scratch and am getting the same issue.

I'm using anvio version 4 (according to anvi-profile -v) on a Mac High Sierra.

Any insight into what's going on would be greatly appreciated!

Here is the requested output of anvi-gen-genomes-storage:
```
anvi-gen-genomes-storage -e contig_paths_genome_storage.txt -o predator_no_S_aurantiaca-GENOMES.db

WARNING
===============================================
Good news! Anvi'o found all these functions that are common to all of your
genomes and will use them for downstream analyses and is very proud of you: ',
G, A, U, T, E, O, m, C, I, F, N, a, f, R, interproscan, _, Y, M, P'.

Internal genomes .............................: 0 have been initialized.                                                                       
External genomes .............................: 4 found.                                                                                       

PLEASE READ CAREFULLY
===============================================
Some of your genomes had gene calls identified by gene callers other than the
gene caller anvi'o used, which was set to 'prodigal' either by default, or
because you asked for it. The following genomes contained genes that were not
processed (this may be exactly what you expect to happen, but if was not, you
may need to use the `--gene-caller` flag to make sure anvi'o is using the gene
caller it should be using): M_flavescens (8 gene calls by "Ribosomal_RNAs"),
M_virescens (8 gene calls by "Ribosomal_RNAs"), M_fulvus (7 gene calls by
"Ribosomal_RNAs"), M_xanthus (8 gene calls by "Ribosomal_RNAs").

                                                                                                                                               
* M_flavescens is stored with 7,892 genes (1 of which were partial)
* M_fulvus is stored with 7,342 genes (1 of which were partial)                                                                                
* M_virescens is stored with 8,373 genes (1 of which were partial)                                                                             
* M_xanthus is stored with 7,737 genes (1 of which were partial)                                                                               

The new genomes storage ......................: predator_no_S_aurantiaca-GENOMES.db (v6, signature: 1b51d4dc)
Number of genomes ............................: 4 (internal: 0, external: 4)
Number of gene calls .........................: 31,344
Number of partial gene calls .................: 4
```

**Comment by meren** [comment]
Oh, crap. Yes Samantha, this was an issue and we resolved it here:

https://github.com/merenlab/anvio/issues/778

If you type this, you can see it yourself:

```
anvi-export-functions -c ONE_OF_YOUR_CONTIGS_DBs --list-annotation-sources
```

So it is a fixed bug, but it is not in any official release yet :/ But if you would like to 'hack' your installation a bit to avoid this issue, you can see the changes here to fix this problem, and apply it to your installed version manually:

https://github.com/merenlab/anvio/commit/794267cb342c119217c989be485eede84fab657b
