### ISSUE TITLE
Pangenome analysis feature request

### ISSUE THREAD

**Issue by weirdlobster** [merenlab/anvio#813]
Your pangenome pipeline has been amazing to work with, and I have a request that I do not believe has been implemented. I am interested in looking at overlapping functionality between genomes, and I'd like to be able to visualize genome overlap in bins. A Venn diagram output would be amazing! Or output that could be put into R for visualization? It seems like many comparative genome papers include this to quantify overlap.

Currently this is possible in excel, but it is very complicated (to me). For example, I am trying to see the overlap in "accessory genes" among 4 species (out of 14), as well as core between all.

As an additional request...and this might be a long shot...it would be nice to extend partial gene calls to truncated, frameshift, or nonsense. I'm not sure how you could implement this in anvi-pan, but some isolates I am working with have high partial genes; some of these are from failed assembly, but some are from evolution as pseudogenes form from purifying selection. Currently I have to do this by hand (but a big thanks to anvi'o for even making this possible!), but an argument for advanced gene-calls would be helpful for researchers doing comparative genomics where genomes are being changed, sometimes drastically. Or this could be added to the pan-analysis to support predictions with other genome information? 

Thank you!

**Comment by meren** [comment]
Hi!

Please see these updates to the pangenomic workflow:

http://merenlab.org/2016/11/08/pangenomics-v2/#making-some-sense-of-functions-in-your-pangenome

We do not have plans to add new kinds of visualizations at this time (i.e.,  Venn diagrams).

Advanced gene calls and categories beyond 'partial' gene calls would have been very useful. But I don't see how we could add these kinds of core features anytime soon :(


Best wishes,
