### ISSUE TITLE
anvi-migrate-db does not work with multiple databases.

### ISSUE THREAD

**Issue by ozcan** [merenlab/anvio#817]
I think `anvi-migrate-db` should be able upgrade multiple databases with single command like below
`anvi-migrate-db SAMPLE*/PROFILE.db` 
currently we depend on shell to do this, for example the command below can upgrade multiple databases, which is not handy as the command above.
`find . -iname PROFILE.db | xargs -I {} anvi-migrate-db {}`

Also if we implement this, we can also upgrade multiple databases in parallel and utilize the disk i/o to the limits and do not wait.

The only roadblock is that we have `--target-version` flag, which will be inappropriate for multiple database types.

So, I think we can accept `nargs`, check if single or multiple databases provided and raise an exception if `--target-version` flag is used with multiple databases.

**Comment by meren** [comment]
I like this idea!
