### ISSUE TITLE
Kaiju parser

### ISSUE THREAD

**Issue by jarrodscott** [merenlab/anvio#826]
Hi anvi'o team. 

This is a **feature request** to parse  `Kaiju` (https://github.com/bioinformatics-centre/kaiju) taxonomy files.  `Kaiju` will accept both paired-end files and single fasta files. To run `Kaiju` you need the formatted db (`*.fmi`) and the `nodes.dmp` file that comes along with it and you will also need `names.dmp` file if you want to add full taxonomy. See below for complete usage.

**For Parsing:** The basic (`default`) output from `Kaiju` is a tab-delimited files that has **3** columns. The 1st column reports either a `C` for `classified` or a `U` for `unclassified`. The 2nd column reports the unique `query ID`, and the 3rd column reports the NCBI `taxon ID`. 

The `-v` argument enables verbose output. This is a **7** column  tab-delimited file. From what I can tell about the `centrifuge` parser, the `Kaiju` verbose option would be more appropriate. Relevant columns are highlighted based on the `centrifuge` parser. **Output does not have a header row**.

1. `C` or `U`
2. **read ID**
3. NCBI `taxon ID`
4. **best match score**
5. **comma-separated list** of taxon IDs with best match. even in the case of a single hit the taxon ID has a comma after it.
6. accession numbers of all database sequences with the best match
7.  matching fragment sequence(s)

`Anvi'o` `anvi-import-taxonomy` parser for `centrifuge` has a hard cut off of `250` for low hit score. `Kaiju` has a default score cutoff (`-s` flag) of` 65`. So this can be changed as needed by the user or hardcoded by the `anvio` parser. *Column 4*

`Anvi'o` also has a cutoff for `too many competing hits` but I don't know what this value is. It seems the information in *Column 5* could be used for this filtering step. 

**Adding taxon names:** From this point it seems that someone who knows what they're doing could then take the NCBI `taxon ID` info in *Column 3* plus `nodes.dmp` and `names.dmp` and add the lineage info into the parser. I am not such a person but thankfully `Kaiju` has a helper script that does just this, `addTaxonNames`.

The basic usage of `addTaxonNames` takes the output of the `kaiju` classifier plus the `nodes.dmp` and `names.dmp` and throws a taxon name in the last column. Default is the lowest identified taxonomic rank--could be genus + species, genus only, or some unclassified rank like `unclassified Rhodobacteraceae`. 

There are several optional arguments that would be useful in creating a parser. 
`-u` will remove all unclassified queries. 
`-p` instead of only adding the taxa name  this flag adds the full lineage. `;` `SPACE` delimited  
`-r` same as `-p` above but allows user to specify ranks in comma separated list (e.g., `phylum,order,class,family,genus,species`)

**USAGE: Kaiju classifier**
Usage:
   `kaiju -t nodes.dmp -f kaiju_db.fmi -i reads.fastq [-j reads2.fastq]`

Mandatory arguments:
   `-t FILENAME`   Name of nodes.dmp file
   `-f FILENAME`   Name of database (.fmi) file
   `-i FILENAME`   Name of input file containing reads in FASTA or FASTQ format

Optional arguments:
   `-j FILENAME`   Name of second input file for paired-end reads
   `-o FILENAME`   Name of output file. If not specified, output will be printed to STDOUT
   `-z INT`        Number of parallel threads for classification (default: 1)
   `-a STRING`     Run mode, either "mem"  or "greedy" (default: greedy)
   `-e INT`        Number of mismatches allowed in Greedy mode (default: 3)
   `-m INT`        Minimum match length (default: 11)
   `-s INT`        Minimum match score in Greedy mode (default: 65)
   `-E FLOAT`      Minimum E-value in Greedy mode
   `-x`            Enable SEG low complexity filter (enabled by default)
   `-X`            Disable SEG low complexity filter
   `-p`            Input sequences are protein sequences
   `-v`           Enable verbose output

**USAGE: Adding taxon names**
Usage:
   `addTaxonNames -t nodes.dmp -n names.dmp -i kaiju.out -o kaiju-names.out`

Mandatory arguments:
   `-i FILENAME`   Name of input file
   `-o FILENAME`   Name of output file. If not specified, output will be printed to STDOUT.`
   `-t FILENAME`   Name of nodes.dmp file
   `-n FILENAME`   Name of names.dmp file.

Optional arguments:
   `-u`            Unclassified reads are not contained in the output.
   `-p`            Print full taxon path.
   `-r`            Print taxon path containing only ranks specified by a comma-separated list,
                 for example: superkingdom,phylum,order,class,family,genus,species
   `-v`            Enable verbose output.

**Comment by meren** [comment]
We now have one and it will be a part of `v5`:

https://github.com/merenlab/anvio/commit/624089d2dc94b65c7008705f1812e6129f47fa33#diff-00f31ea949785f10f120e52ff7781f0e

Thanks!
