### ISSUE TITLE
anvi-script-snvs-to-interactive

### ISSUE THREAD

**Issue by tkim89** [merenlab/anvio#828]
Hi!
I am having a problem with anvi-script-snvs-to-interactive.
I ran this with your infant gut dataset as well as my own metagenomic data and I am getting this issue after I run 

 ```
anvi-script-snvs-to-interactive E-faecalis-SNVs.txt -o e_faecalis_snvs
Num entries ..................................: 9,904
Num positions ................................: 1,238
Num samples ..................................: 8
[08 May 18 21:19:39 Hierarchical clustering] ..                                                                                                                    Traceback (most recent call last):
  File "/home/tk/anaconda3/envs/anvio4/bin/anvi-script-snvs-to-interactive", line 100, in <module>
    main(args)
  File "/home/tk/anaconda3/envs/anvio4/bin/anvi-script-snvs-to-interactive", line 78, in main
    g.generate()
  File "/home/tk/anaconda3/envs/anvio4/lib/python3.6/site-packages/anvio/summarizer.py", line 1689, in generate
    self.gen_clustering_of_view_data()
  File "/home/tk/anaconda3/envs/anvio4/lib/python3.6/site-packages/anvio/summarizer.py", line 1706, in gen_clustering_of_view_data
    clustering.get_newick_tree_data(data_file_path, self.tree_file_path, distance = self.distance, linkage=self.linkage)
AttributeError: module 'anvio.clustering' has no attribute 'get_newick_tree_data'
```

So, I get that error for both test (infant) and my own datasets. I was wondering what might be the problem?  I don't get any other output besides additional_view_data.txt ad view_data.txt in the output folder. Is there a software/package version problem? I'm using UBuntu 16.04.4 in a virtual machine. I installed anvio via conda.

Ted

Here is my anvi version.

`anvi-self-test --version`
Anvi'o version ...............................: 4
Profile DB version ...........................: 23
Contigs DB version ...........................: 10
Pan DB version ...............................: 8
Genome data storage version ..................: 6
Auxiliary data storage version ...............: 2

**Comment by meren** [comment]
Unfortunately this is a known bug in `v4`, and we fixed it in the `master`.

@ekiefl can you please confirm?

**Comment by ozcan** [comment]
@meren, This is also broken on `master`, I am already working on this.

**Comment by meren** [comment]
Thanks, @ozcan!

**Comment by ozcan** [comment]
Hi @tkim89,
We could finally able to update this script to make it compatible with recent changes.
If you download this script to any directory you should be able to run now.

```
wget https://raw.githubusercontent.com/merenlab/anvio/6869c96ea478c408178091e6148f052ccab731a1/sandbox/anvi-script-snvs-to-interactive -O anvi-script-snvs-to-interactive
chmod +x anvi-script-snvs-to-interactive
./anvi-script-snvs-to-interactive variability_profile.txt -o OUTPUT
```

If you forget the `./` in the beginning, it will run the one installed with `anvio`. If you prefer you can find location of that file, delete it and replace with the updated one. `which  anvi-script-snvs-to-interactive` will print the location.

Best,

**Comment by ozcan** [comment]
Please feel free to re-open this issue if you encounter any problems.
