### ISSUE TITLE
rRNA HMM hits don't show up in the refine mode

### ISSUE THREAD

**Issue by tdelmont** [merenlab/anvio#833]
Hi, using anvi'o v.4 here,

I just wanted to let the developers know that rRNA HMM hits don't show up in the anvi-refine mode (when they show-up nicely in anvi-interactvie mode). I think this "bug" has always been around. However, I apology if this has already been fixed in the master (I currently have issues using it).

Anyways, would be great to see rRNAs on the anvi-refine mode in anvi'o v.5 

Tom

**Comment by meren** [comment]
Currently refine mode does not show other HMM hits either.

Refine mode should also initialize HMM hits and item additional data.
