### ISSUE TITLE
Anvio install keeps failing in a virtual environment using python3's venv

### ISSUE THREAD

**Issue by yankeebotanist** [merenlab/anvio#838]
im new to coding and ubuntu and am trying to install anvio but im trying to do it with venv instead of virtualenv and it is not working.  I type in the codes as said on the instruction page of how to install anvio but when i get to the virtual environment that i make using python3's venv in the type pip install anvio (after the other stuff) and it goes through the installation only to end with this.

    /home/ernest/virtual-envs/anvio-4/lib/python3.6/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
     #warning "Using deprecated NumPy API, disable it by " \
      ^~~~~~~
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fdebug-prefix-map=/build/python3.6-EKG1lX/python3.6-3.6.5=. -specs=/usr/share/dpkg/no-pie-compile.specs -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/home/ernest/virtual-envs/anvio-4/lib/python3.6/site-packages/numpy/core/include -I/opt/local/include/ -I/usr/local/include/ -I/home/ernest/virtual-envs/anvio-4/include -I/usr/include/python3.6m -c ./anvio/extensions/concoct/c_vbgmm_fit.c -o build/temp.linux-x86_64-3.6/./anvio/extensions/concoct/c_vbgmm_fit.o
    ./anvio/extensions/concoct/c_vbgmm_fit.c:14:10: fatal error: gsl/gsl_vector.h: No such file or directory
     #include <gsl/gsl_vector.h>
              ^~~~~~~~~~~~~~~~~~
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    ----------------------------------------
Command "/home/ernest/virtual-envs/anvio-4/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-865ymbyw/anvio/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-uzu0mjpl-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/ernest/virtual-envs/anvio-4/include/site/python3.6/anvio" failed with error code 1 in /tmp/pip-build-865ymbyw/anvio/
(anvio-4) ernest@ernest-Latitude-E7470:~$ anvi-self-test --version
anvi-self-test: command not found

please help I have been working on this for the past 6 hours and dont know how to fix it at this point.  I am wondering if i should just do the installation with virtualenv instead because i have not done pip install virtualenv since I have venv from python3.  If you need more info let me know

**Comment by meren** [comment]
The error is there:

> gsl/gsl_vector.h: No such file or directory

The first result on Google for "install gsl ubuntu" is this:

https://askubuntu.com/questions/490465/install-gnu-scientific-library-gsl-on-ubuntu-14-04-via-terminal


I would start from here.

**Comment by yankeebotanist** [comment]
Thank you so much it worked and anvio is now install!! Thanks!!
