### ISSUE TITLE
Unexpected behavior when providing -C and -b to anvi-interactive

### ISSUE THREAD

**Issue by ekiefl** [merenlab/anvio#845]
On master, running 

`anvi-interactive -p PROFILE.db -c CONTIGS.db -C Genomes -b HIMB083` produces the unexpected behavior of entering collection mode. I was expecting that only splits belonging to `EVERYTHING` would be present. Indeed, the warning message also implies this:

![image](https://user-images.githubusercontent.com/8688665/40935872-189ea782-67ff-11e8-9bd3-d8d348ba520e.png)

**Comment by meren** [comment]
Oh, yes, the `anvi-interactive` should not allow this to happen (btw, I assume you mean `HIMB083` when you say `EVERYTHING`).
