### ISSUE TITLE
add anvi-split --pan-functions

### ISSUE THREAD

**Issue by ShaiberAlon** [merenlab/anvio#846]
We need to discuss what this would do exactly, but the main idea is to make the steps [here](http://merenlab.org/2016/11/08/pangenomics-v2/#creating-a-quick-pangenome-with-functions) seamless.

**Comment by meren** [comment]
I think one way to address this is to apply all those ad hoc steps to reduce redundancy among function names within the code prior to reporting, and adding a flag so the user can by-pass those heuristics (i.e., `--report-as-is`).

Right?

**Comment by ShaiberAlon** [comment]
Yes. I agree that it would be the first step, and relatively easy.
