### ISSUE TITLE
Issue with anvi-gen-genomes-storage

### ISSUE THREAD

**Issue by ycsong** [merenlab/anvio#848]
The following is the output of the ani-self-test --version, per request.

(anvio) s4453161@mrca001:/srv/projects2/TC1/TC1_pangenomes$ anvi-self-test --version
Anvi'o version ...............................: 2.3.2
Profile DB version ...........................: 20
Contigs DB version ...........................: 8
Pan DB version ...............................: 5
Samples information DB version ...............: 2
Genome data storage version ..................: 1
Auxiliary data storage version ...............: 3
Anvi'server users data storage version .......: 1

Now to the issues...I have been following through the pangenome analysis as described in http://merenlab.org/2016/11/08/pangenomics-v2/  .  I have generated the contigs database for all the 10 MAGs in the analysis using **anvi-script-FASTA-to-contigs-db**.  I have created the external-genomes text file.  When I first ran the **anvi-gen-genomes-storage**.  Then I got the following message:

(anvio) s4453161@mrca001:/srv/projects2/TC1/TC1_pangenomes$ anvi-gen-genomes-storage -e ./TC1_gtdb_v86_genomic_sequences_aa/external_genomes.txt -o ./TC1_gtdb_v86_genomic_sequences_aa/TC1-GENOMES.h5

WARNING
===============================================
None of your genomes seem to have any functional annotation. No biggie. Things
will continue to work. But then your genomes have no functional annotation. SAD.

Internal genomes .............................: 0 have been initialized.                                                                       
External genomes .............................: 10 found.                                                                                      

Config Error: The contigs databases you are using for this analysis are missing HMMs for     
              single-copy core genes. In other words, you don't seem to have run `anvi-run-  
              hmms` on them. Although it is perfectly legal to have anvi'o contigs databases 
              without HMMs run on SCGs, the current pangenomic workflow does not want to deal
              with this :( Sorry!

So I went back and ran the anvi-run-hmms on all the contigs db, and re-ran the genomes-storage command, and I still get the same message.  I am running this in Ubuntu 12.04.5 LTS.  Thank you

Young

**Comment by meren** [comment]
Hi,

You're using version 2.3.2.. it is quite old. Please upgrade your anvi'o installation to v4.
