### ISSUE TITLE
bad HTML issue when running anvi-display-pan

### ISSUE THREAD

**Issue by ycsong** [merenlab/anvio#852]
Hello,

I am going through the pan-genome workflow as described in http://merenlab.org/2016/11/08/pangenomics-v2/.  Everything seems to be working fine, until when I try to visualize the result with anvi-display-pan.  Below is what I see when I execute the command:

`(anvio4) s4453161@mrca001:/srv/projects2/TC1/TC1_pangenomes/anvio_pangenome_out$ anvi-display-pan -p TC1_pangenome-PAN.db -g ../TC1_genomes_nt_fasta/TC1-GENOMES.db`

![anvio_screen](https://user-images.githubusercontent.com/5509867/41133428-354395ce-6b0a-11e8-8815-c4ffd416b474.png)

I am running anvio4 in Ubuntu 12.04.5 LTS (within miniconda3 environment).  

```
(anvio4) s4453161@mrca001:/srv/projects2/TC1/TC1_pangenomes/anvio_pangenome_out$ anvi-self-test --version
Anvi'o version ...............................: 4
Profile DB version ...........................: 23
Contigs DB version ...........................: 10
Pan DB version ...............................: 8
Genome data storage version ..................: 6
Auxiliary data storage version ...............: 2
```

Your help would be much appreciated.  Thank you,

Young

**Comment by ozcan** [comment]
Hi Young,

It seems everything working fine, but it just `webbrowser` module failing to find Chrome web browser to open our web interface. In that case, this module uses text-based browsers as a fallback solution and tries to open with them and you get a weird result like in your screenshot.

If you just close that program pressing `Q`, and open a browser like Chrome, and navigate the `http://127.0.0.1:8080` (port may be different, but anvi'o prints the port it uses in green text to the terminal), you can access the web interface without problems.

Also programs like `anvi-interactive`, `anvi-display-pan` have `--server-only` parameter which disables automatic web browser opening.

Best,
