### ISSUE TITLE
Create banner that reminds people to cite snakemake when using anvi-run-workflow

### ISSUE THREAD

**Issue by ShaiberAlon** [merenlab/anvio#854]
@meren, I'm not sure what exactly you had in mind when you mentioned we could do this. @ozcan I'm including you here in case you have a suggestion.

**Comment by meren** [comment]
Something like this could be enough for now:

https://github.com/merenlab/anvio/blob/master/bin/anvi-pan-genome#L29

@ozcan and I need to think about a much more efficient and useful way to keep track of citations though.

**Comment by FlorianTrigodet** [comment]
Hi guys, 

Using the master version.
The warning message to cite snakemake has a wrong doi
```
WARNING
===============================================
If you publish results from this workflow, please do not forget to cite
snakemake (doi:10.1038/nmeth.3176)
```
It should be 10.1093/bioinformatics/bts480
