### ISSUE TITLE
anvio installation with homebrew

### ISSUE THREAD

**Issue by ycsong** [merenlab/anvio#856]
Hello,

I've just installed Anvio in the local machine (Ubuntu 16.04 LTS) using homebrew (http://merenlab.org/2016/06/26/installation-v2/).  The installation was "painless" and seemed to go well (i.e.  all the dependencies were installed without errors or warnings).  I am just wondering though, do I need to add a new path to ~/.bash_profile or ~/.bashrc after installation?  At the moment, when I try to execute the anvi-self-test command, I get "command not found" message.

Thank you,

Young

**Comment by ycsong** [comment]
Hello again, 

I've just noticed that I need to run the 'brew install anvio' command once again to have the full packages installed in my machine.

**Comment by ycsong** [comment]
Okay, so I can now definitely confirm that it required two executions of same command to have everything installed (such that my machine can recognize the commands starting with 'anvi-').  So that problem is resolved.

Apologies in advance if this looks like I am squeezing multiple issues in one thread.  Even with successful installation, I don't seem to be able to find commands such `anvi-get-enriched-functions-per-pan-group` which is used in pan-genome workflow.  Your help would be much appreciated.  Thank you again.

**Comment by ekiefl** [comment]
@ycsong I'm glad you got everything working. It surprises me it took 2 `brew install anvio`s to get things working. `anvi-get-enriched-functions-per-pan-group` is a function that will be released in the next version of anvi'o, which is due in less than 2 weeks time. Sorry for the confusion of it being in the tutorial already. We really need to have different tutorials for each version of anvi'o to solve this problem. When we announce the new release you can reinstall with brew and `anvi-get-enriched-functions-per-pan-group` should be available.

**Comment by ycsong** [comment]
Hi @ekiefl, thank you for letting me know.  I would like to ask you one more question.  I am keen to use the anvio interactive interface (http://merenlab.org/2016/02/27/the-anvio-interactive-interface//#using-the-anvio-interactive-interface).  I've already had success generating the primary visualization using the walkthrough described in the pangenome tutorial section. 

![anvio_screenshot](https://user-images.githubusercontent.com/5509867/41212373-c08b3826-6d80-11e8-967e-9ffb6c381bcb.png)

My question is, is there some sort of guide on where to find (or how to generate) the tab-delimited files (and other required files such as newick and layer files) that I need to import to the interactive interface to create the project?

**Comment by meren** [comment]
@ycsong, you may want to take a look at this:

http://merenlab.org/2017/12/11/additional-data-tables/
