### ISSUE TITLE
New stack bar data type needs improvements

### ISSUE THREAD

**Issue by meren** [merenlab/anvio#869]
Mouse menu currently is not really helpful:

![image](https://user-images.githubusercontent.com/197307/41517814-8b70bcf8-7283-11e8-8398-17cdedf7a414.png)

Legends have no batch coloring options:

![image](https://user-images.githubusercontent.com/197307/41517823-ad0f35d8-7283-11e8-80b5-00dd7e282051.png)

And Meren is also realizing that the infant gut data is the shittiest possible data pack to look into these things because in this MG everything is E. facealis.

**Comment by ozcan** [comment]
batch coloring works as expected, but sorting does not work because for categorical data we use keys (their name), for stack bar we use index (their order). I am going to fix this soon (prob tomorrow).
