### ISSUE TITLE
possible issue with anvi-refine or anvi-migrate-db in latest pull

### ISSUE THREAD

**Issue by jarrodscott** [merenlab/anvio#871]
Hi all

`Anvi'o version ...............................: rosalind (v4-master)`
`Profile DB version ...........................: 28`
`Contigs DB version ...........................: 12`
`Pan DB version ...............................: 11`
`Genome data storage version ..................: 6`
`Auxiliary data storage version ...............: 2`

on centos server

I just updated from the `master` a few days ago and for some reason `anvi-refine` no longer displays `LEN` data in the `Bins` tab when refining bins. I had to update my `PROFILE.db` because it was `v26` so maybe this is the problem? I ran the same dataset, same command on my mac with a `master` pull from a few weeks ago with the `v26` db and it worked fine. 

Anyway, I know v5 is forthcoming but I thought you should anyway. I am happy to share the `PROFILE.db` and `CONTIG.db` Oh and I just realized the `%` signs are gone.

Thanks!
Jarrod
<img width="389" alt="screen shot 2018-06-18 at 9 13 18 am" src="https://user-images.githubusercontent.com/16192182/41541449-1e2b66fc-72d8-11e8-9d8d-823339ea0094.png">
<img width="382" alt="screen shot 2018-06-18 at 9 14 47 am" src="https://user-images.githubusercontent.com/16192182/41541450-1e59c574-72d8-11e8-9a51-86c3c74d0e94.png">

**Comment by jarrodscott** [comment]
FYI I followed this recipe to update codebase:

[i-already-have-the-codebase](http://merenlab.org/2016/06/26/installation-v2/#i-already-have-the-codebase)

**Comment by meren** [comment]
excellent! thank you for the report, Jarrod. I think @ozcan will be able to quickly address this. he recently refactored the underlying code, and we expect to run into some hiccups :)

**Comment by jarrodscott** [comment]
Thanks Meren and @ozcan . FYI So I decided to do a fresh reinstall of the `master` to see if maybe simply updating had something to do with the problem. During the `self-test` (full and mini) I  got this intimidating message--I don't even want to know what anvio's business socks llok like :0

`Config Error: You did not provide a list of data keys to remove, which means you are about to `
`              delete everything in the layers additional data table. Just to be on the safe   `
  `            side, anvi'o is looking for a confirmation. If you try again with the --just-do-`
`              it flag, anvi'o will put on its business socks, and burn this table and         `
  `            everything in it to the ground.                                                 `

`Config Error: It seems something went wrong while running your tests :/ Anvi'o hopes that the
              reason is clear from the lines above.   `

**Comment by ozcan** [comment]
Thanks for catching this @jarrodscott,
I have fixed refine problem and @meren fixed the mini test issue.

Best,

**Comment by jarrodscott** [comment]
rock and roll! fresh install on a linux and mac from the master.
`anvi-self-test` worked on both :)
