### ISSUE TITLE
Trouble searching gene clusters in pangenome analysis using functions

### ISSUE THREAD

**Issue by ycsong** [merenlab/anvio#879]
Hello,

I am currently in midst of doing some pangenome analysis and have followed through the tutorials.  Prior to creating a genome storage, I've annotated the genes in my genome using `anvi-run-ncbi-cogs`.  Everything seems to be going well (i.e. generating genome storage all the way to displaying the result in the browser), except when I run the `anvi-display-pan`, I get a warning message saying that genome 'storage does not have any info about gene functions'

![anvi-pan-display](https://user-images.githubusercontent.com/5509867/41696243-6e37310a-7556-11e8-8c1d-7761c6b78d85.png)

So at this point, I cannot search the clusters using the functions.  I just executed `anvi-export-functions` to verify that the functional annotations are available in at least one of my genomes:

![anvi-export-functions](https://user-images.githubusercontent.com/5509867/41696284-9d459982-7556-11e8-9a17-8166b82289fe.png)

...and indeed the annotation procedure I've executed prior to creating the genome storage seems to have worked (ie. there is actually something in the output of `anvi-export-functions`)

'gene_callers_id	source	accession	function	e_value
0	COG_FUNCTION	COG0593	Chromosomal replication initiation ATPase DnaA	2.8e-117
0	COG_CATEGORY	L	L	0
1	COG_FUNCTION	COG0592	DNA polymerase III sliding clamp (beta) subunit, PCNA homolog	1.3e-67
1	COG_CATEGORY	L	L	0
2	COG_FUNCTION	COG1195	Recombinational DNA repair ATPase RecF	1.1e-74
2	COG_CATEGORY	L	L	0
3	COG_FUNCTION	COG0608	Single-stranded DNA-specific exonuclease, DHH superfamily, may be involved in archaeal DNA replication intiation	9.9e-75
3	COG_CATEGORY	L	L	0
4	COG_FUNCTION	COG0220	tRNA G46 methylase TrmB	7.1e-50
....'

At this point, I am wondering what need to be further done to make sure that I can search the cluster by functions.  Your help would be much appreciated.  Thank you,

Young

P.S.  The pangenome analysis was already done in the Ubuntu server in our lab...and I am doing all the visualization in the local machine that uses Ubuntu 16.04 LTS.

**Comment by meren** [comment]
Is this anvi'o stable `v4`?

**Comment by ycsong** [comment]
Oops forgot to mention that...yes both the server and my local machine use anvio v4

**Comment by meren** [comment]
Do you have the output log from `anvi-gen-genomes-storage`?

Did it tell you that anvi'o found functions for all contigs databases?

That is the only reason I can think of, and I don't seem to be able to reproduce this with `v4` :/

**Comment by ycsong** [comment]
I didn't save the output log from `anvi-gen-genomes-storage` the first time I ran it...so I just ran it again with different output name...and seems like not all the genomes have been annotated, ultimately generating the issue that I am having.

![anvi-gen-genomes-storage](https://user-images.githubusercontent.com/5509867/41697726-7616b754-755d-11e8-892c-38c2885d20ca.png)

**Comment by meren** [comment]
Well, that resolves it, then :)
