### ISSUE TITLE
feature request for anvi-run-pfam

### ISSUE THREAD

**Issue by jarrodscott** [merenlab/anvio#880]
Howdy. I have a Feature Request of sorts. Is it possible to add a `--temporary-dir-path` flag to `anvi-run-pfam`? Similar to `anvi-run-ncbi-cogs`? I think this would make running `anvi-run-pfam` possible (at least for me) on a cluster. I was having an issue with `anvi-run-ncbi-cogs` until I used this flag. But `anvi-run-hmms` seems to store `temp` files in the same fashion but runs ok on the server. 

Nice to see Pfam capabilities in anvio!

Thanks all. 
Jarrod

**Comment by ozcan** [comment]
Hey @jarrodscott,

I think what you are looking for is `--pfam-data-dir`. Both `anvi-setup-pfams` and `anvi-run-pfams` has this parameter, so you can download to custom location that you have permission to and use that location. We may add enviroment variable to make this dir permanent for user.

Best,

**Comment by meren** [comment]
besides the data directory, real temporary dirs are also being read from the environment. anvi'o uses system defaults, or the user can set an environment variable (i.e., `TMPDIR `) and anvi'o would use that to store all temporary files :)

**Comment by ozcan** [comment]
There is an example how can `TMPDIR` be used for this purpose at https://github.com/merenlab/anvio/issues/913#issuecomment-405725487
