### ISSUE TITLE
Gene mode inspection fails

### ISSUE THREAD

**Issue by meren** [merenlab/anvio#881]
Latest additions to display GC-content variation broke the gene mode inspection capabilities. Totally fixable! :p

**Comment by ozcan** [comment]
Oh sorry didn't realized you self assigned this, but i had to disable `check_names_consistency` in interactive because leaves in tree does not match with database. If you have better solution than disabling it that would be great

**Comment by meren** [comment]
I'm sorry you also spent time on this! I did the same thing basically, but also added functionality to init split sequences to focus only splits of interest.

meanwhile I realized init contig sequences need improvement as well, but I left it behind for another time :/
