### ISSUE TITLE
database is locked

### ISSUE THREAD

**Issue by JBuongio** [merenlab/anvio#891]
Hi Meren, 
I'm trying to create a contigs db with a .fa and external gene calls from Prokka and am receiving an error about sqlite:

 
(anvio-4) $ anvi-gen-contigs-database -f ../Concatenated_MAGs_simple_deflines.fa -o ../Concat061318.db --external-gene-calls Concatenated_MAGs_anvio_deflines061318_gene_calls.txt
Input FASTA file .............................: /home/barbara-lloydlab/klds1515/SVA08.16_Metagenomes/071817KLmetagenome-45705703/Bins_from_Derep_Dastool/After_sortmeRNA/Concatenated_MAGs_simple_deflines.fa

Anvi'o made things up for you
===============================================
You are generating a new anvi'o contigs database, but you are not specifying a
project name for it. FINE. Anvi'o, in desperation, will use the input file name
to set the project name for this contigs database (which is
'Concatenated_MAGs_simple_deflines'). If you are not happy with that, feel free
to kill and restart this process. If you are not happy with this name, but you
don't like killing things either, maybe next time you should either name your
FASTA files better, or use the `--project-name` parameter to set your desired
name.

Name .........................................: Concatenated_MAGs_simple_deflines
Description ..................................: No description is given
Traceback (most recent call last):
  File "/home/barbara-lloydlab/virtual-envs/anvio-4/bin/anvi-gen-contigs-database", line 50, in <module>  
    a.create(args)
  File "/home/barbara-lloydlab/virtual-envs/anvio-4/lib/python3.5/site-packages/anvio/dbops.py", line 2600, in create
    self.touch()
  File "/home/barbara-lloydlab/virtual-envs/anvio-4/lib/python3.5/site-packages/anvio/dbops.py", line 2470, in touch
    self.db = db.DB(self.db_path, anvio.__contigs__version__, new_database=True)
  File "/home/barbara-lloydlab/virtual-envs/anvio-4/lib/python3.5/site-packages/anvio/db.py", line 46, in __init__
    self.create_self()
  File "/home/barbara-lloydlab/virtual-envs/anvio-4/lib/python3.5/site-packages/anvio/db.py", line 69, in create_self
    self._exec('''CREATE TABLE self (key text, value text)''')
  File "/home/barbara-lloydlab/virtual-envs/anvio-4/lib/python3.5/site-packages/anvio/db.py", line 169, in _exec
    ret_val = self.cursor.execute(sql_query)
sqlite3.OperationalError: database is locked

___________________________________________________________________________
Do you have any suggestions?

**Comment by meren** [comment]
Hi Joy,

We just released `v5`:

https://github.com/merenlab/anvio/releases

That would be great if you can first install `v5` and try this on the new version.


Best,

**Comment by JBuongio** [comment]
No dice.

(anvio-5) $ anvi-gen-contigs-database -f Concatenated_MAGs_simple_deflines.fa -o Concatenated_MAGs_simple_deflines062418.db --external-gene-calls Concatenated_MAGs_anvio_deflines061318_gene_calls.txt --ignore-internal-stop-codons --skip-mindful-splitting
Input FASTA file .............................: /home/barbara-lloydlab/klds1515/SVA08.16_Metagenomes/071817KLmetagenome-45705703/Bins_from_Derep_Dastool/After_sortmeRNA/For_Anvio/Concatenated_MAGs_simple_deflines.fa

Anvi'o made things up for you
===============================================
You are generating a new anvi'o contigs database, but you are not specifying a
project name for it. FINE. Anvi'o, in desperation, will use the input file name
to set the project name for this contigs database (which is
'Concatenated_MAGs_simple_deflines'). If you are not happy with that, feel free
to kill and restart this process. If you are not happy with this name, but you
don't like killing things either, maybe next time you should either name your
FASTA files better, or use the `--project-name` parameter to set your desired
name.

Name .........................................: Concatenated_MAGs_simple_deflines
Description ..................................: No description is given
Traceback (most recent call last):                                                                    
  File "/home/barbara-lloydlab/virtual-envs/anvio-5/bin/anvi-gen-contigs-database", line 50, in <module>
    a.create(args)
  File "/home/barbara-lloydlab/virtual-envs/anvio-5/lib/python3.5/site-packages/anvio/dbops.py", line 2760, in create
    self.touch()
  File "/home/barbara-lloydlab/virtual-envs/anvio-5/lib/python3.5/site-packages/anvio/dbops.py", line 2631, in touch
    self.db = db.DB(self.db_path, anvio.__contigs__version__, new_database=True)
  File "/home/barbara-lloydlab/virtual-envs/anvio-5/lib/python3.5/site-packages/anvio/db.py", line 47, in __init__
    self.create_self()
  File "/home/barbara-lloydlab/virtual-envs/anvio-5/lib/python3.5/site-packages/anvio/db.py", line 70, in create_self
    self._exec('''CREATE TABLE self (key text, value text)''')
  File "/home/barbara-lloydlab/virtual-envs/anvio-5/lib/python3.5/site-packages/anvio/db.py", line 176, in _exec
    ret_val = self.cursor.execute(sql_query)
sqlite3.OperationalError: database is locked

**Comment by meren** [comment]
Thanks for sending these files, Joy,

In my `v5` everything worked beautifully:

```
$ anvi-gen-contigs-database -f Concatenated_MAGs_simple_deflines.fa \
                            -o Concat061318.db \
                            --external-gene-calls Concatenated_MAGs_anvio_deflines061318_gene_calls.txt \
                            --ignore-internal-stop-codons \
                            --skip-mindful-splitting
Input FASTA file .............................: /Users/meren/Downloads/del/Concatenated_MAGs_simple_deflines.fa

Anvi'o made things up for you
===============================================
You are generating a new anvi'o contigs database, but you are not specifying a
project name for it. FINE. Anvi'o, in desperation, will use the input file name
to set the project name for this contigs database (which is
'Concatenated_MAGs_simple_deflines'). If you are not happy with that, feel free
to kill and restart this process. If you are not happy with this name, but you
don't like killing things either, maybe next time you should either name your
FASTA files better, or use the `--project-name` parameter to set your desired
name.

Name .........................................: Concatenated_MAGs_simple_deflines
Description ..................................: No description is given
Split Length .................................: 20,000
K-mer size ...................................: 4
Skip gene calling? ...........................: False
External gene calls provided? ................: Concatenated_MAGs_anvio_deflines061318_gene_calls.txt
Ignoring internal stop codons? ...............: True
Splitting pays attention to gene calls? ......: False
External gene calls ..........................: 111487 gene calls recovered and will be processed.

WARNING
===============================================
Please read this carefully: Your external gene calls contained open reading
frames with internal stop codons, and you asked anvi'o to ignore those. Anvi'o
replaced internal stop codons with 'X' characters, and stored them in the
contigs database that way. 47657 of your genes, which corresponded to 42.75% of
the total 111487 genes, had internal stop codons. We hope you are happy.

Contigs with at least one gene call ..........: 25640 of 25825 (99.3%)
Contigs database .............................: A new database, Concat061318.db, has been created.
Number of contigs ............................: 25,825
Number of splits .............................: 25,982
Total number of nucleotides ..................: 119,298,068
Gene calling step skipped ....................: False
Splits broke genes (non-mindful mode) ........: True
Desired split length (what the user wanted) ..: 20,000
Average split length (wnat anvi'o gave back) .: 19,974
```

Perhaps you should delete the previous contig, and try again. This doesn't seem to be a problem about the codebase :(

**Comment by JBuongio** [comment]
Thank you for trying, Meren! I will have to look into my version of sqlite.
