### ISSUE TITLE
Suggestion concerning 'anvi-get-sequences-for-gene-calls'

### ISSUE THREAD

**Issue by dcourtine** [merenlab/anvio#893]
Hi anvi'o team!

I oppened this issue to suggest a new parameter for the command `anvi-get-sequences-for-gene-calls`.

This parameter would allow the user to choose a source for the gene caller (One? Multiple sources?). 

To illustrate this: I exported gene sequences from a contigs DB (1 archaeal genome), but the fasta file always contained two "extra" genes. It turned out that these two genes were rRNA, identified from `anvi-run-hmms`. With this new parameter, the user could recover the genes from the source 'prodigal', 'Ribosomal_RNAs' or 'Any other gene caller'.

I hope I was clear :)

Best,
Damien

**Comment by meren** [comment]
I was going through old issues that we didn't have time to go back to, Damien. You probably already forgot about this. This is important indeed. Addressing it properly requires us to have a 'gene caller' option built-in into the contigs database design, which is not the case at the moment. I think at some point some hero will embark upon this re-design, and then this issue will sort itself out automatically.

Thank you, and I hope all is well.
