### ISSUE TITLE
Difficulty installing anvio v5

### ISSUE THREAD

**Issue by mkhall** [merenlab/anvio#895]
I have anvio v4 installed on my computer, and I tried to install v5 with homebrew, and this is what happened:
michellehallenbeck$ brew upgrade anvio
==> Upgrading 1 outdated package, with result:
merenlab/anvio/anvio 2.3.2 -> 5
Warning: Use prodigal instead of deprecated homebrew/science/prodigal
Warning: Use hmmer instead of deprecated homebrew/science/hmmer
Warning: Use hdf5 instead of deprecated homebrew/science/hdf5
Warning: Use diamond instead of deprecated homebrew/science/diamond
Error: No available formula with the name "homebrew/science/mcl" (dependency of merenlab/anvio/anvio)

I checked to make sure I actually have v4 installed:
anvi-profile --version
Anvi'o version ...............................: 4
Profile DB version ...........................: 23
Contigs DB version ...........................: 10
Pan DB version ...............................: 8
Genome data storage version ..................: 6
Auxiliary data storage version ...............: 2

And I also checked to make sure I had MCL installed:
michellehallenbeck$ mcl --version
mcl 14-137
Copyright (c) 1999-2014, Stijn van Dongen. mcl comes with NO WARRANTY
to the extent permitted by law. You may redistribute copies of mcl under
the terms of the GNU General Public License.

I'm not really sure what's going on. Can someone help me fix this?

**Comment by Sofie8** [comment]
Hi Meren,

I was trying to install anvio5 via conda: "conda install -c bioconda -c conda-forge anvio diamond bwa", but the version it installs is anvio4. Specifying anvio=5 also didn't do it. And when I do conda update anvio, also anvio4 it shows as most recent. If I download the source file, and run pip install -r requirements.txt and then python setup.py install, it exits with many errors. Can you help me with this issue?

**Comment by Sofie8** [comment]
Yes, I tried, and I get this:

vsc31426@hpc-p-login-2 /vsc-hard-mounts/leuven-data/314/vsc31426/miniconda3/bin 16:55 $ conda install -n anvio5 -c bioconda -c conda-forge anvio=5.1.0 diamond bwa
Fetching package metadata .............
Solving package specifications:

PackageNotFoundError: Dependency missing in current linux-64 channels:
  - anvio 5.1.0* -> h5py >=2.8.0rc1 -> libgcc-ng >=4.9

Close matches found; did you mean one of these?

    libgcc-ng: libgcc

**Comment by meren** [comment]
This is unfortunately beyond me, and I will have to summon our conda guru/angel @jmeppley :(

**Comment by Sofie8** [comment]
Hi,
I also searched further and found some suggestions here: [#780](https://github.com/merenlab/anvio/issues/780)

I now specified explicitly django=2.0.2, which made it work in my case, for an hpc system.
Hope it is useful for others as well!

./conda create -y --name anvio5 python=3.6
./conda install -y --name anvio5 django=2.0.2
./conda install -y --name anvio5 -c bioconda -c conda-forge anvio=5 diamond bwa

source activate anvio5
anvi-self-test --suite mini

Thanks!

**Comment by meren** [comment]
Thank you very much, @Sofie8! You're the best. I updated the installation manual with a note.

**Comment by aschuerch** [comment]
When installing anvio with conda with

`conda install -c bioconda -c conda-forge anvio diamond bwa`

it also installed the latest hmmer version which gave the error

`Config Error: The last call did not work quite well. Most probably the version of HMMER you
              have installed is not up-to-date enough. Just to make sure what went wrong   
              please take a look at the log file                                           
              ('/tmp/7982501.1.default/tmpv182ma72/00_log.txt'). Please visit              
              http://hmmer.janelia.org/download.html to see what is the latest version     
              availalbe. You can learn which version of HMMER you have on your system by   
              typing 'hmmpress -h'   `

when running the self-test.

Downgrading to version 3.1b2 with 

 `conda install hmmer=3.1b2`

solved the problem
I put in a pull request to fix this in the recipe https://github.com/bioconda/bioconda-recipes/pull/11005

**Comment by meren** [comment]
Thank you very much for checking, @aschuerch!

**Comment by charlie-durant** [comment]
> Thank you very much, @Sofie8! You're the best. I updated the installation manual with a note.

Yes, thank you! This ended up working for me (on a Linux VM) too, but I spent a while trying to figure out why anvi'o commands couldn't be found before I saw the 'source activate anvio5' line here. Could this also be included in the [installation instructions](http://merenlab.org/2016/06/26/installation-v2/#painless-installation-with-conda)? :)

**Comment by Luyang-1987** [comment]
When installing anvio with conda followed the http://merenlab.org/2016/06/26/installation-v2/
and when came to the step:
conda install -y -c conda-forge -c bioconda anvio==6.2

it always gave the errors:

Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.

**Comment by meren** [comment]
hi @Luyang-1987, I haven't heard of this error before, but recently @AstrobioMike shared with me his solution here:

https://hackmd.io/@astrobiomike/anvio-v6-2-conda

Perhaps you should consider trying it. Please let us know re: how it goes.


Best wishes,

**Comment by AstrobioMike** [comment]
hiya, @Luyang-1987, I'll also note it's not unusual for conda to show those messages as it's checking different ways it might be able to do what it needs to do. Depending on what i'm installing and my current system, i often see those first two pop up and "fail" before moving onto the next way it is tries (which usually finishes fine).
