### ISSUE TITLE
Trouble with anvi-gen-genomes-storage

### ISSUE THREAD

**Issue by PlantDr430** [merenlab/anvio#897]
Hello again,

I am up-to-date on the latest anvio version, and have been running it pretty successfully on Ubuntu 18.04.

anvi-self-test --version
Anvi'o version ...............................: margaret (v5.1)
Profile DB version ...........................: 29
Contigs DB version ...........................: 12
Pan DB version ...............................: 12
Genome data storage version ..................: 6
Auxiliary data storage version ...............: 2
Structure DB version .........................: 1

However, I cannot figure out what element array I am trying to access that doesn't exist.

(anvio-5.1) swyka430@swyka-ubuntu:/Wyka/anvio/Exon-call-run$ anvi-gen-genomes-storage -e external-genomes.txt --gene-caller Funannotate -o Claviceps_exon-GENOMES.db

WARNING
===============================================
Good news! Anvi'o found all these functions that are common to all of your
genomes and will use them for downstream analyses and is very proud of you:
'COG_FUNCTION, Pfam, COG_CATEGORY'.

Internal genomes .............................: 0 have been initialized.                             
[29 Jun 18 20:02:54 Initializing external genomes] working on Cpasp                                 Traceback (most recent call last):
  File "/home/swyka430/virtual-envs/anvio-5.1/bin/anvi-gen-genomes-storage", line 53, in <module>
    genome_descriptions.load_genomes_descriptions()
  File "/home/swyka430/virtual-envs/anvio-5.1/lib/python3.6/site-packages/anvio/genomedescriptions.py", line 200, in load_genomes_descriptions
    self.init_external_genomes()
  File "/home/swyka430/virtual-envs/anvio-5.1/lib/python3.6/site-packages/anvio/genomedescriptions.py", line 339, in init_external_genomes
    contigs_db_summary = summarizer.ContigSummarizer(c['contigs_db_path']).get_contigs_db_info_dict(gene_caller_to_use=self.gene_caller)
  File "/home/swyka430/virtual-envs/anvio-5.1/lib/python3.6/site-packages/anvio/summarizer.py", line 1322, in get_contigs_db_info_dict
    p_completion, p_redundancy, domain, domain_confidence, results_dict = completeness.Completeness(self.contigs_db_path).get_info_for_splits(split_names if split_names else set(c.splits_basic_info.keys()))
  File "/home/swyka430/virtual-envs/anvio-5.1/lib/python3.6/site-packages/anvio/completeness.py", line 71, in __init__
    self.http_refs[source_in_db] = [h for h in info_table[source_in_db]['ref'].split() if h.startswith('http')][0]
IndexError: list index out of range

Attached is my external-genome text file I am trying to use to direct the software to the contigs.db

[external-genomes.txt](https://github.com/merenlab/anvio/files/2151328/external-genomes.txt)

Please let me know if you need any other information.

**Comment by meren** [comment]
This doesn't seem to be an issue regarding your input file. The error comes from the part of anvi'o that is trying to figure out your HMMs.

Did you run `anvi-run-hmms` with `-H` parameter pointing out to a specific HMM directory you put together?

Because that seems to be the case. More specifically, your HMM collection had a reference.txt anvi'o didn't like but didn't realize until it was too late :/

Can you please send the output of this command (that `external-genomes.txt` is your external genomes file):

```
for i in `cat external-genomes.txt | grep -v contigs_db_path | awk '{print $2}'`
do
    echo $i
    sqlite $i.db 'select ref from hmm_hits_info;'
    echo ""
done
```

Thanks,

**Comment by PlantDr430** [comment]
Yes, I did use the -H flag to point toward a specific HMM directory. That's a bummer about the reference test (I have attached the reference.txt used in my HMM directory that I created).

The output for the command is:

(anvio-5.1) swyka430@swyka-ubuntu:/Wyka/anvio/Exon-call-run$ ./hmm_ref_script.sh 
/Wyka/anvio/Exon-call-run/Cpur20.contigs.db
SQL error: no such table: hmm_hits_info

/Wyka/anvio/Exon-call-run/Cpur20.contigs.db
SQL error: no such table: hmm_hits_info

/Wyka/anvio/Exon-call-run/LM14.contigs.db
SQL error: no such table: hmm_hits_info

/Wyka/anvio/Exon-call-run/LM218.contigs.db
SQL error: no such table: hmm_hits_info

/Wyka/anvio/Exon-call-run/LM28.contigs.db
SQL error: no such table: hmm_hits_info

/Wyka/anvio/Exon-call-run/LM30.contigs.db
SQL error: no such table: hmm_hits_info

/Wyka/anvio/Exon-call-run/LM33.contigs.db
SQL error: no such table: hmm_hits_info

/Wyka/anvio/Exon-call-run/LM4.contigs.db
SQL error: no such table: hmm_hits_info

/Wyka/anvio/Exon-call-run/LM576.contigs.db
SQL error: no such table: hmm_hits_info

/Wyka/anvio/Exon-call-run/LM582.contigs.db
SQL error: no such table: hmm_hits_info

/Wyka/anvio/Exon-call-run/LM583.contigs.db
SQL error: no such table: hmm_hits_info

/Wyka/anvio/Exon-call-run/LM60.contigs.db
SQL error: no such table: hmm_hits_info

- This looks weird to me as it makes me think there were not hmm_hits, which there were and my contigs stats show that there were HMM hits (see photo below)

![screenshot from 2018-06-30 10-41-18](https://user-images.githubusercontent.com/29610303/42127274-7fcb278e-7c52-11e8-93b7-9abf76d67344.png)



[reference.txt](https://github.com/merenlab/anvio/files/2152009/reference.txt)

**Comment by meren** [comment]
Easy to fix this :) add the doi as an http:// link, and refund the HMMs. Then try again with the genome storage.

**Comment by PlantDr430** [comment]
Alright, I'll give it a try. Is there an easy way to just update the HMM tables in the contigs.db for just updating the reference.txt or do I have to re-run "anvi-run-hmms"?

**Comment by meren** [comment]
Hi @PlantDr430,

I would re-run `anvi-run-hmms` to be on the safe side.
