### ISSUE TITLE
Installing Anvi'o in virtual environment (Linux): "could not find pandas version 0.20.1"

### ISSUE THREAD

**Issue by nailabc** [merenlab/anvio#898]
Hi, I'm planning to use Anvi'o in a cluster of computers (Linux) and for working on it I was advised to install anything in a virtual environment. I was then following the instructions from "Installing the latest stable release (safe mode)" and I succeeded in all steps except the last. I get the following error message after running the command "pip install anvio":
"  Could not find a version that satisfies the requirement pandas==0.20.1 (from anvio) (from versions: 0.21.0, 0.22.0)
No matching distribution found for pandas==0.20.1 (from anvio)"

It seems that this pandas version 0.20.1 is longer available?

**Comment by nailabc** [comment]
This is the complete message:
(anvio-5.1) [nailabc@cedar1 nailabc]$ pip install anvio
Looking in links: /cvmfs/soft.computecanada.ca/custom/python/wheelhouse/avx2, /cvmfs/soft.computecanada.ca/custom/python/wheelhouse/generic
Collecting anvio
  Downloading https://files.pythonhosted.org/packages/4c/e3/2f3bddfcdde43a90574926a00261ad31c4dcff35496df511849e121641eb/anvio-5.1.tar.gz (45.1MB)
    100% |████████████████████████████████| 45.1MB 587kB/s
Requirement already satisfied: numpy in ./ENV/anvio-5.1/lib/python3.6/site-packages (from anvio) (1.14.5)
Requirement already satisfied: cython in ./ENV/anvio-5.1/lib/python3.6/site-packages (from anvio) (0.28.2)
Collecting bottle==0.12.13 (from anvio)
  Downloading https://files.pythonhosted.org/packages/bd/99/04dc59ced52a8261ee0f965a8968717a255ea84a36013e527944dbf3468c/bottle-0.12.13.tar.gz (70kB)
    100% |████████████████████████████████| 71kB 5.3MB/s
Collecting pysam==0.14.1 (from anvio)
Collecting ete3==3.1.1 (from anvio)
  Downloading https://files.pythonhosted.org/packages/21/17/3c49b7fafe10ed63bb7904ebf9764b98db726aa5fd482fb006818854bc04/ete3-3.1.1.tar.gz (10.5MB)
    100% |████████████████████████████████| 10.5MB 2.4MB/s
Requirement already satisfied: scipy>=0.13.3 in ./ENV/anvio-5.1/lib/python3.6/site-packages (from anvio) (1.1.0)
Collecting scikit-learn==0.19.1 (from anvio)
Collecting django==2.0.2 (from anvio)
  Downloading https://files.pythonhosted.org/packages/48/b1/4e4875dabd9603c89ca753313fd13f429426e4a80a0264603a30d56e0338/Django-2.0.2-py3-none-any.whl (7.1MB)
    100% |████████████████████████████████| 7.1MB 4.1MB/s
Collecting h5py>=2.8.0rc1 (from anvio)
Collecting cherrypy==8.9.1 (from anvio)
  Downloading https://files.pythonhosted.org/packages/9d/c2/8a19081b3ded7b5f497ba132055ba665188432be02512d80cd7ac93c86d6/CherryPy-8.9.1-py2.py3-none-any.whl (464kB)
    100% |████████████████████████████████| 471kB 6.5MB/s
Collecting requests>=2.10.0 (from anvio)
  Downloading https://files.pythonhosted.org/packages/65/47/7e02164a2a3db50ed6d8a6ab1d6d60b69c4c3fdf57a284257925dfc12bda/requests-2.19.1-py2.py3-none-any.whl (91kB)
    100% |████████████████████████████████| 92kB 9.2MB/s
Collecting psutil>=5.0.1 (from anvio)
  Downloading https://files.pythonhosted.org/packages/51/9e/0f8f5423ce28c9109807024f7bdde776ed0b1161de20b408875de7e030c3/psutil-5.4.6.tar.gz (418kB)
    100% |████████████████████████████████| 419kB 2.4MB/s
Collecting mistune==0.7.4 (from anvio)
  Downloading https://files.pythonhosted.org/packages/7b/ab/e71dd1ca31addcd0268c54859eaf75414a10fbc48c79078f7c3066e6ed0d/mistune-0.7.4-py2.py3-none-any.whl
Collecting six==1.11.0 (from anvio)
Collecting pandas==0.20.1 (from anvio)
  Could not find a version that satisfies the requirement pandas==0.20.1 (from anvio) (from versions: 0.21.0, 0.22.0)
No matching distribution found for pandas==0.20.1 (from anvio)

**Comment by meren** [comment]
This is weird. I can see pandas `0.20.1` on PyPI:

https://pypi.org/project/pandas/0.20.1/

And I was able to install it by running today in another virtual environment:

```
pip install pandas==0.20.1
```

Did you try to install it again? I'm afraid this is not an issue we can address :(

**Comment by nailabc** [comment]
Yes, I tried pip install pandas==0.20.1 and it doesn't find this version. I gave up and installed with conda, I didn't want to do it because they recommend to not use Anaconda in the cluster, but it worked so it's fine! Thanks for your answer :)
