### ISSUE TITLE
cannot properly install

### ISSUE THREAD

**Issue by beroe3** [merenlab/anvio#899]
Hello,

I am sure this is is trivial but I am a novice on troubleshooting python issues. After installing using brew, on Mac OS High Sierra, I am getting this on running the self test. There was a warning on dependency also. Thank you for the help :) 

mpbair:~ mpb$ brew reinstall anvio
==> Reinstalling merenlab/anvio/anvio 
==> Downloading https://data.merenlab.org/homebrew-anvio/anvio-5.1.high_sierra.b
Already downloaded: /Users/mpb/Library/Caches/Homebrew/anvio-5.1.high_sierra.bottle.tar.gz
==> Pouring anvio-5.1.high_sierra.bottle.tar.gz

Warning: merenlab/anvio/anvio dependency gcc was built with a different C++ standard
library (libstdc++ from clang). This may cause problems at runtime.
🍺  /usr/local/Cellar/anvio/5.1: 12,089 files, 219.6MB
mpbair:~ mpb$ 
mpbair:~ mpb$ anvi-self-test --suite mini
dyld: Library not loaded: @executable_path/../.Python
  Referenced from: /usr/local/Cellar/anvio/5.1/libexec/bin/python3.6
  Reason: image not found
Abort trap: 6

**Comment by meren** [comment]
Thank you for reporting this :)

@ozcan, I saw a similar issue on Slack recently. Does this make sense to you?

**Comment by beroe3** [comment]
Thank you. I was sure I was doing something wrong :). I will try coda. Thing is I installed anaconda on my laptop and now its version 3-5.2. It gives me issues too (on another machine I had anvio installed like a breeze using conda 3-5-1. I wonder if they also messed up with the new conda.

**Comment by ozcan** [comment]
Hey @beroe3,
I put some workarounds in homebrew formula, it supposed to work now. If conda fails you can give a second try to homebrew.
best,
