### ISSUE TITLE
database version 12 vs version 9 in anvio5

### ISSUE THREAD

**Issue by cam315** [merenlab/anvio#900]
Dear developers,

When I run the 'anvi-get-aa-sequences-for-gene-calls' after I updated from anvio4 to anvio5, the pipeline stopped with following information:

    Config Error: It seems the database 'contigs.db' was      
              generated when your client was at version 12, however, your client now is at   
              version 9. Which means this database file cannot be used with this client      
              anymore, but THERE MAY be a script to UPGRADE your database! Just type `anvi-  
              script-upgrade-` on your terminal, and press the TAB key twice to see all      
              available scripts. If there is nothing there to upgrade your database from v12 
              to v9, you may need to re-create it with the new anvi'o :/ Please feel free to 
              get in touch with the anvi'o developers if you are not sure, and they will help
              you figure out what is the next best step for you.

Even after I regenerated the DB with anvi-profile and anvi-merge in anvio5. There is no functions to downgrade the database from v12 to v9 in the 'anvi-script-upgrade-'. Any suggestions or solutions?

Thank you.

**Comment by meren** [comment]
We don't have the program `anvi-get-aa-sequences-for-gene-calls` in anvi'o `v5`.

There is a rogue installation on your system. You can see it by typing this:

```
which anvi-get-aa-sequences-for-gene-calls
```

In comparison, if you type this, you will see a very different source:

```
which anvi-self-test
```

You need to get rid of the older installation which is somehow interfering.

Best,
