### ISSUE TITLE
Trouble with anvi-matrix-to-newick in functional enrichment analysis workflow

### ISSUE THREAD

**Issue by mkhall** [merenlab/anvio#905]
I'm making my way through the functional enrichment analysis workflow and I'm stuck on the step where you take the output of running the script fix_functional_occurence_table.py and create trees for the interactive interface.

This is what I typed:
```
anvi-matrix-to-newick /Users/michellehallenbeck/Desktop/Thiomonas_enriched_functions/THIOMONAS_COG_occurrence-fixed.txt -o /Users/michellehallenbeck/Desktop/Thiomonas_enriched_functions/THIOMONAS_COG-tree.txt
```

And this is what happens:

```
Input matrix file ............................: /Users/michellehallenbeck/Desktop/Thiomonas_enriched_functions/THIOMONAS_COG_occurrence-fixed.txt
File/Path Error: File '/Users/michellehallenbeck/Desktop/Thiomonas_enriched_functions/THIOMONAS_C
                 OG_occurrence-fixed.txt' does not seem to have TAB characters. Did you export   
                 this file on MAC using EXCEL? :( 
```

The file THIOMONAS_COG_occurrence-fixed.txt is a tab-delimited text file. I tried re-saving it in that same format, and I still got this error. I tried opening it in Excel, saving it as an .xlsx file, and re-saving it as a tab delimited text file, and I still got the same error. I even tried re-running the fix_functional_occurence_table.py script, and using the output in anvi-matrix-to-newick, and it still tells me that exact same error. I have absolutely no idea what anvi'o wants from me here. How can a tab-delimited text file not have tab characters?

**Comment by meren** [comment]
Can you please attach the file?

**Comment by mkhall** [comment]
[THIOMONAS_COG_occurrence-fixed.txt](https://github.com/merenlab/anvio/files/2178136/THIOMONAS_COG_occurrence-fixed.txt)

**Comment by meren** [comment]
@mkhall, 

> I have absolutely no idea what anvi'o wants from me here.

The file does not have any TAB characters. Anvi'o wants from you to provide a TAB-delimited file.

Your file looks like this (with no TAB characters):

```
$ head THIOMONAS_COG_occurrence-fixed.txt
name_ACO3_ACO7_CB1_CB2_CB3_CB6_FB6_FBCd_K12_S10_T3As_X19_b6_intermediaT
name 3_deoxy_D_manno_octulosonate 8_phosphate phosphatase KdsC and related HAD superfamily phosphatases_1_1_1_1_1_1_1_1_1_1_1_1_1_1
name Creatinine amidohydrolase_Fe_II_dependent formamide hydrolase involved in riboflavin and F420 biosynthesis_1_1_1_1_0_1_0_1_0_0_1_1_1_0
name16S rRNA A1518 and A1519 N6_dimethyltransferase RsmA_KsgA_DIM1 _may also have DNA glycosylase_AP lyase activity_1_1_1_1_1_1_1_1_1_1_1_1_1_1
name16S rRNA C1402 N4_methylase RsmH_1_1_1_1_1_1_1_1_1_1_1_1_1_1
name16S rRNA C1402 _ribose_2_O_ methylase RsmI_1_1_1_1_1_1_1_1_1_1_1_1_1_1
name16S rRNA C967 or C1407 C5_methylase_ RsmB_RsmF family_1_1_1_1_1_1_1_1_1_1_1_1_1_1
name16S rRNA G527 N7_methylase RsmG _former glucose_inhibited division protein B_1_1_1_1_1_1_1_1_1_1_1_1_1_1
name16S rRNA G966 N2_methylase RsmD_1_1_1_1_1_1_1_1_1_1_1_1_1_1
name16S rRNA U1498 N3_methylase RsmE_1_1_1_1_1_1_0_0_1_1_1_0_0_1
```

CC @ShaiberAlon (just in case there is something to look at in `fix_functional_occurence_table.py`).

**Comment by mkhall** [comment]
I added a tab to the end of each line with this:
tr "\r" "\t" < THIOMONAS_COG_occurrence-fixed.txt > THIOMONAS_COG_TAB.txt

When I ran anvi-matrix-to-newick-again, I got this:
$ anvi-matrix-to-newick THIOMONAS_COG_TAB.txt -o THIOMONAS_COG-tree.txt
Input matrix file ............................: THIOMONAS_COG_TAB.txt
Traceback (most recent call last):
  File "/Users/michellehallenbeck/virtual-envs/anvio-5.1/bin/anvi-matrix-to-newick", line 50, in <module>
    main(args)
  File "/Users/michellehallenbeck/virtual-envs/anvio-5.1/bin/anvi-matrix-to-newick", line 33, in main
    distance = args.distance, transpose = args.transpose, progress = progress)
  File "/Users/michellehallenbeck/virtual-envs/anvio-5.1/lib/python3.6/site-packages/anvio/clustering.py", line 128, in create_newick_file_from_matrix_file
    newick = get_newick_from_matrix(vectors, distance, linkage, norm, id_to_sample_dict)
  File "/Users/michellehallenbeck/virtual-envs/anvio-5.1/lib/python3.6/site-packages/anvio/clustering.py", line 109, in get_newick_from_matrix
    vectors = get_normalized_vectors(vectors, norm=norm, progress=progress)
  File "/Users/michellehallenbeck/virtual-envs/anvio-5.1/lib/python3.6/site-packages/anvio/clustering.py", line 165, in get_normalized_vectors
    return normalizer.fit_transform(vectors)
  File "/Users/michellehallenbeck/virtual-envs/anvio-5.1/lib/python3.6/site-packages/sklearn/base.py", line 517, in fit_transform
    return self.fit(X, **fit_params).transform(X)
  File "/Users/michellehallenbeck/virtual-envs/anvio-5.1/lib/python3.6/site-packages/sklearn/preprocessing/data.py", line 1507, in fit
    X = check_array(X, accept_sparse='csr')
  File "/Users/michellehallenbeck/virtual-envs/anvio-5.1/lib/python3.6/site-packages/sklearn/utils/validation.py", line 441, in check_array
    "if it contains a single sample.".format(array))
ValueError: Expected 2D array, got 1D array instead:
array=[].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

**Comment by mkhall** [comment]
[THIOMONAS_COG_TAB.txt](https://github.com/merenlab/anvio/files/2178350/THIOMONAS_COG_TAB.txt)

**Comment by meren** [comment]
Your file is broken, @mkhall. Please find your local bioinformatics friend and solve this with them. This does not strike me as an anvi'o issue.

Best wishes,
