### ISSUE TITLE
anvi-run-ncbi-cogs runs out of memory

### ISSUE THREAD

**Issue by UriaMorP** [merenlab/anvio#906]
Hey there,

When running ``anvi-run-ncbi-cogs`` I get this error (log.txt file):

```bash
Processing query chunk 0, reference chunk 0, shape 11, index chunk 2.
Building reference index...  [2.32749s]
Building query index...  [1.6119s]
Building seed filter...  [0.137489s]
Searching alignments... No space left on device
Error: Error writing file /tmp/diamond-tmp-M0tx7X
terminate called after throwing an instance of 'File_write_exception'
  what():  Error writing file /tmp/diamond-tmp-M0tx7X
```
I ran ``df -s /tmp`` to see what's going on and indeed, diamond takes all 20GB available in the /tmp

version details:
```bash
(anvi) [uria@access3 ramadan_contigs_5M_all_2]$ anvi-self-test --version
Anvi'o version ...............................: 4
Profile DB version ...........................: 23
Contigs DB version ...........................: 10
Pan DB version ...............................: 8
Genome data storage version ..................: 6
Auxiliary data storage version ...............: 2
```
Thanks,
Uria

**Comment by UriaMorP** [comment]
Realized conda left me with v4 while v5.1 is out... updating and will keep you posted

**Comment by UriaMorP** [comment]
Coultn't install v5.1... see [issue 907](https://github.com/merenlab/anvio/issues/907)

**Comment by ozcan** [comment]
Hi @UriaMorP,

It seems this is related with free disk space rather than memory as it says `No space left on device`. If memory was the issue, you could limit memory usage by sacrificing computation time but I don't think the same principle applies to disk usage. If you need to create big blast/diamond search databases you need a big disk drive.

Best,

**Comment by UriaMorP** [comment]
I have > 15TB available, but as the /tmp is shared by the HPC, I cannot write more than 20 GB on it. When I tried to use --tmp-dir-path argument, it only wrote the aa sequences and log where I specified, but diamond still tries to write on the /tmp. 

When running diamond 0.9.*  outside anvio,   on (much) larger queries and  UniRef90 as reference, it never caused any such troubles. Disk space is not the issue

**Comment by meren** [comment]
Try to set a BASH environmental variable, `TMP` with the path name for temporary usage. It is your system that says where to put temp files.

**Comment by meren** [comment]
Ah, sorry! I may have misunderstood. I will read later more carefully :)

**Comment by ozcan** [comment]
Hi @UriaMorP, sorry for reacting fast,  thought this just was confusion about memory/disk usage.

It seems `--tmp-dir-path` parameter is only for the files generated by anvi'o, we do not pass that argument to diamond. But diamond takes `--tmpdir` argument too, so we need to fix our diamond driver and pass this argument to diamond.

As a workaround you can modify our driver like below:

This should print driver location:
``` python -c "import anvio.drivers.diamond as d; print(d.__file__)"```

If you open this file. At line 38, you will see `self.tmp_dir = tempfile.gettempdir()`  you can change this variable to another path like `self.tmp_dir = "/storage/xxx"`, this will get passed to diamond.

Best,

**Comment by ozcan** [comment]
Also I have just tested @meren's suggestion and it works, and I think it is more practical.

You can test like below, just enter any path that exists:
`TMPDIR=/Users/ozcan/Workspace python -c "import tempfile; print(tempfile.gettempdir())"`

If this prints same directory, you can set this `TMPDIR` environment variable inside your `.bashrc` or `export TMPDIR=/xxx` before running anvi'o programs and anvi'o and python will use that path, therefore it will pass it to diamond.

**Comment by UriaMorP** [comment]
Thanks @ozcan ,
I'll try that and keep you posted...

**Comment by UriaMorP** [comment]
WORKED.

Thanks a lot!

**Comment by AstrobioMike** [comment]
I'll just throw up a notice here in case it helps others (and so i remember next time i find myself here again).

I got an `OSError: AF_UNIX path too long` after about 15 hours of processing something :( because it seems:

>The Python mulitprocessing library appears to create sockets in $TMPDIR. If the $TMPDIR path is too long then the path to the socket extends past the length limits for socket paths.

from [here](https://github.com/broadinstitute/cromwell/issues/3647#issue-324083335)

So seems generally speaking it'd be better to set the TMPDIR higher up/closer to root when possible, rather than way down in the nested mess that i'm typically working in :)
