### ISSUE TITLE
KEGG annotation with anvi'o?

### ISSUE THREAD

**Issue by Alopias1988** [merenlab/anvio#910]
Hi there, I was wondering if there is a way to use the KEGG database instead of COG for annotating pan-genomes using the pangenome workflow. I know there is a script for using GhostKoala but its for metagenomes so I was wondering if there is way to do it for genome analysis.

Thanks!

**Comment by meren** [comment]
You can have access to KEGG annotations in the pan workflow if you import functional annotations per anvi'o contigs database before running `anvi-gen-genomes-storage`.

Best,
