### ISSUE TITLE
Exiting server before saving concoct refinement: Config Error Can't Locate Collection Name

### ISSUE THREAD

**Issue by colbyga** [merenlab/anvio#914]
###
Anvi'o version ...............................: margaret (vunknown)
Profile DB version ...........................: 29
Contigs DB version ...........................: 12
Pan DB version ...............................: 12
Genome data storage version ..................: 6
Auxiliary data storage version ...............: 2
Structure DB version .........................: 1
###

I am using anvio5, and refining my bins. I have run into the following error using anv-refine. 

As a note this is not my first bin refined, and up until now this command had been working fine.

command:
`anvi-refine -p $OUTPUT/SAMPLES-MERGED/PROFILE.db -c $OUTPUT/contigs.db -C "CONCOCT" -b Bin_74`

Output: 
```
Contigs DB ...................................: Initialized: ~/anvio_refining/contigs.db (v. 12)                                                      
Splits taxonomy ..............................: Initiated for taxonomic level for "t_genus"                                                                                      
Interactive mode .............................: refine
WARNING
===============================================
ProfileSuperClass found a collection focus, which means it will be initialized
using only the splits in the profile database that are affiliated with the
collection CONCOCT and bins "Bin_74" it describes.

Config Error: Query on collections_of_splits with the where clause of
              'collection_name="CONCOCT"' did not return anything.

```

When I went back to look if there was a problem saving the previous bin refinement I saw this. 
                                                                                                       
```
WARNING
===============================================
Previous entries for "CONCOCT" is being removed from "collections_info,
collections_of_contigs, collections_of_splits, collections_bins_info"

^C
Please wait...
===============================================
The server is being terminated.
```

It would appear that I have deleted previous entries for CONCOCT prior to it saving. Is there any possible way I can correct what seems to be a disastrous mistake? 

As an additional note, when I run 

`anvi-show-collections-and-bins -p $OUTPUT/SAMPLES-MERGED/PROFILE.db`

I see all of my bins and get the following output

```
Collection: "CONCOCT"
===============================================
Collection ID ................................: CONCOCT
Number of bins ...............................: 628
Number of splits described ...................: 297,758
```

-Graham

**Comment by colbyga** [comment]
This is the best option I can think of, is this correct? 

Use anvi-import-collection to import the CONCOCT bins that should be preserved in my SAMPLES-MERGED/PROFILE.db, again this is assuming that the CONCOCT results from my contigs.db file has been erased.

**Comment by meren** [comment]
The issue is now summarized in the report above.
