### ISSUE TITLE
no interactive interface with anvio-self-test

### ISSUE THREAD

**Issue by AudreyRose** [merenlab/anvio#918]
Hi Meren,

The anvio browser window doesn't popup when I run the anvio-self-test using the command _anvi-self-test --suite mini_. 

I've changed my default browser to chrome 
Information requested:
**Anvo'o version ...**
Anvi'o version ...............................: margaret (v5.1-master)
Profile DB version ...........................: 29
Contigs DB version ...........................: 12
Pan DB version ...............................: 12
Genome data storage version ..................: 6
Auxiliary data storage version ...............: 2
Structure DB version .........................: 1

My **operating system** is CentOS Linux release 7.4.1708 (Core). I **installed** the latest 
stable release (safe mode) mostly as per http://merenlab.org/2016/06/26/installation-v2/. I'm using my university HPC so don't have sudo permissions. I copied (cp) prodigal from the Prodigal-2.6.2 directory to ~/bin. Anvio was installed with python/3.6.3 gsl/2.4  hmmer/3.1b2-1 modules loaded. I have also read these instructions http://merenlab.org/2015/11/28/visualizing-from-a-server/

![interactive_interface_failed](https://user-images.githubusercontent.com/7211595/43077377-4154249e-8e7f-11e8-8c02-94487e1756a9.png)

I'm fairly new to this so may have easily misunderstood your instructions. Any advice is appreciated.
After playing with localhost I now think the issue may lie with my ssh permissions, however, until I can clarify this, and in case there is something else that I'm missing I will leave the issue open here.

Thanks,
Audrey

**Comment by AudreyRose** [comment]
(anvio-5.1) bt16035@frontend8 ~> pip show -f anvio > /tmp/_output && head -n 100 /tmp/_output && rm /tmp/_output # no output                                      1
Name: anvio
Version: 5.1
Summary: An interactive analysis and visualization platform for 'omics data. See https://merenlab.org/projects/anvio for more information
Home-page: https://merenlab.org/projects/anvio/
Author: anvi'o Authors
Author-email: a.murat.eren@gmail.com
License: GPLv3+
Location: /data/home/bt16035/virtual-envs/anvio-5.1/lib/python3.6/site-packages
Requires: h5py, psutil, matplotlib, six, snakemake, ete3, cython, pysam, mistune, pyani, bottle, statsmodels, numpy, cherrypy, scikit-learn, django, scipy, requests, pandas
Required-by:
Files:
  ../../../bin/00_README.txt
  ../../../bin/__pycache__/anvi-script-gen_stats_for_single_copy_genes.cpython-36.pyc
  ../../../bin/anvi-cluster-with-concoct
  ../../../bin/anvi-compute-ani
  ../../../bin/anvi-compute-completeness
  ../../../bin/anvi-db-info
  ../../../bin/anvi-delete-collection
  ../../../bin/anvi-delete-hmms
  ../../../bin/anvi-delete-misc-data
  ../../../bin/anvi-delete-state
  ../../../bin/anvi-display-contigs-stats
  ../../../bin/anvi-display-pan
  ../../../bin/anvi-display-structure
  ../../../bin/anvi-experimental-organization
  ../../../bin/anvi-export-collection
  ../../../bin/anvi-export-contigs
  ../../../bin/anvi-export-functions
  ../../../bin/anvi-export-gene-calls
  ../../../bin/anvi-export-gene-coverage-and-detection
  ../../../bin/anvi-export-locus
  ../../../bin/anvi-export-misc-data
  ../../../bin/anvi-export-splits-and-coverages
  ../../../bin/anvi-export-splits-taxonomy
  ../../../bin/anvi-export-state
  ../../../bin/anvi-export-table
  ../../../bin/anvi-gen-contigs-database
  ../../../bin/anvi-gen-gene-consensus-sequences
  ../../../bin/anvi-gen-genomes-storage
  ../../../bin/anvi-gen-network
  ../../../bin/anvi-gen-phylogenomic-tree
  ../../../bin/anvi-gen-structure-database
  ../../../bin/anvi-gen-variability-matrix
  ../../../bin/anvi-gen-variability-network
  ../../../bin/anvi-gen-variability-profile
  ../../../bin/anvi-get-aa-counts
  ../../../bin/anvi-get-codon-frequencies
  ../../../bin/anvi-get-enriched-functions-per-pan-group
  ../../../bin/anvi-get-sequences-for-gene-calls
  ../../../bin/anvi-get-sequences-for-gene-clusters
  ../../../bin/anvi-get-sequences-for-hmm-hits
  ../../../bin/anvi-get-short-reads-from-bam
  ../../../bin/anvi-get-short-reads-mapping-to-a-gene
  ../../../bin/anvi-get-split-coverages
  ../../../bin/anvi-import-collection
  ../../../bin/anvi-import-functions
  ../../../bin/anvi-import-misc-data
  ../../../bin/anvi-import-state
  ../../../bin/anvi-import-taxonomy-for-genes
  ../../../bin/anvi-import-taxonomy-for-layers
  ../../../bin/anvi-init-bam
  ../../../bin/anvi-interactive
  ../../../bin/anvi-matrix-to-newick
  ../../../bin/anvi-mcg-classifier
  ../../../bin/anvi-merge
  ../../../bin/anvi-merge-bins
  ../../../bin/anvi-meta-pan-genome
  ../../../bin/anvi-migrate-db
  ../../../bin/anvi-oligotype-linkmers
  ../../../bin/anvi-pan-genome
  ../../../bin/anvi-profile
  ../../../bin/anvi-push
  ../../../bin/anvi-refine
  ../../../bin/anvi-rename-bins
  ../../../bin/anvi-report-linkmers
  ../../../bin/anvi-run-hmms
  ../../../bin/anvi-run-ncbi-cogs
  ../../../bin/anvi-run-pfams
  ../../../bin/anvi-run-workflow
  ../../../bin/anvi-saavs-and-protein-structures-summary
  ../../../bin/anvi-script-FASTA-to-contigs-db
  ../../../bin/anvi-script-add-default-collection
  ../../../bin/anvi-script-checkm-tree-to-interactive
  ../../../bin/anvi-script-filter-fasta-by-blast
  ../../../bin/anvi-script-gen-CPR-classifier
  ../../../bin/anvi-script-gen-distribution-of-genes-in-a-bin
  ../../../bin/anvi-script-gen-hmm-hits-matrix-across-genomes
  ../../../bin/anvi-script-gen-short-reads
  ../../../bin/anvi-script-gen-vignette
  ../../../bin/anvi-script-gen_stats_for_single_copy_genes.R
  ../../../bin/anvi-script-gen_stats_for_single_copy_genes.README
  ../../../bin/anvi-script-gen_stats_for_single_copy_genes.py
  ../../../bin/anvi-script-gen_stats_for_single_copy_genes.sh
  ../../../bin/anvi-script-get-collection-info
  ../../../bin/anvi-script-merge-collections
  ../../../bin/anvi-script-predict-CPR-genomes
  ../../../bin/anvi-script-reformat-fasta
  ../../../bin/anvi-script-run-eggnog-mapper
  ../../../bin/anvi-script-snvs-to-interactive
  ../../../bin/anvi-search-functions
rm: remove regular file ‘/tmp/_output’?

**Comment by meren** [comment]
Can you go to the address http://0.0.0.0:8080 while the server is running and see the content? Because you are golden :)

It is about your operating system default browser settings, and anvi'o can't do much about it.
