### ISSUE TITLE
anvi-get-sequences-for-hmm-hits giving a new error

### ISSUE THREAD

**Issue by sipesk** [merenlab/anvio#920]
Anvi'o version ...............................: margaret (v5.1)
Profile DB version ...........................: 29
Contigs DB version ...........................: 12
Pan DB version ...............................: 12
Genome data storage version ..................: 6
Auxiliary data storage version ...............: 2
Structure DB version .........................: 1

I've been using anvio capabilites for a while now and this error is brand new to me. I havent changed anything that I have been doing previously or have changed my machine in any way. I'm unsure what I've done wrong to get this error. I follow the phylogenomics workflow very carefully and my external genomes file is in the correct format. I even restarted my computer to see if my 100 tab open were the issue. Alas, no luck

When I run
$ anvi-get-sequences-for-hmm-hits --external-genomes amini-external-genomes.txt -o concatenated-proteins-Campbell.fa --return-best-hit --get-aa-sequences --concatenate --hmm-source Campbell_et_al

I get this:
Traceback (most recent call last):
  File "/home/barbara-lloydlab/virtual-envs/anvio-5.1/bin/anvi-get-sequences-for-hmm-hits", line 275, in <module>
    main(args)
  File "/home/barbara-lloydlab/virtual-envs/anvio-5.1/bin/anvi-get-sequences-for-hmm-hits", line 101, in main
    s = hmmopswrapper.SequencesForHMMHitsWrapperForMultipleContigs(args, hmm_sources)
  File "/home/barbara-lloydlab/virtual-envs/anvio-5.1/lib/python3.5/site-packages/anvio/hmmopswrapper.py", line 33, in __init__
    self.load_genomes_descriptions(skip_functions=True, init=False)
  File "/home/barbara-lloydlab/virtual-envs/anvio-5.1/lib/python3.5/site-packages/anvio/genomedescriptions.py", line 185, in load_genomes_descriptions
    self.genomes[genome_name]['genome_hash'] = self.get_genome_hash_for_external_genome(self.genomes[genome_name])
  File "/home/barbara-lloydlab/virtual-envs/anvio-5.1/lib/python3.5/site-packages/anvio/genomedescriptions.py", line 314, in get_genome_hash_for_external_genome
    contigs_db = dbops.ContigsDatabase(entry['contigs_db_path'])
  File "/home/barbara-lloydlab/virtual-envs/anvio-5.1/lib/python3.5/site-packages/anvio/dbops.py", line 2587, in __init__
    self.init()
  File "/home/barbara-lloydlab/virtual-envs/anvio-5.1/lib/python3.5/site-packages/anvio/dbops.py", line 2598, in init
    self.meta[key] = int(self.meta[key])
KeyError: 'kmer_size'

**Comment by sipesk** [comment]
here is my external genomes file
https://github.com/sipesk/anvio_pangenomic/blob/master/amini-external-genomes.txt

**Comment by meren** [comment]
Hi @sipesk, 

I think one or more of your contigs databases are broken :/

You could run this in the directory where you have the file `amini-external-genomes.txt` to find out which one it is:

``` bash
for i in `grep -v contigs_db_path amini-external-genomes.txt | awk '{print $2}'`
do
    echo $i
    python -c "import anvio.dbops as d; d.ContigsDatabase(\"$i\")"
done
```

Best,

**Comment by sipesk** [comment]
Thanks for that code. When I run it it gives:

`Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named 'anvio'`

for all of the .db. But the same db in another directory runs fine.

Another issue that comes up is when I run:

`$ anvi-get-sequences-for-hmm-hits --external-genomes amini-external-genomes.txt -o amini-external-genomes.txt --hmm-source Campbell_et_al --return-best-hit --get-aa-sequences --concatenate
`
I get:
`Config Error: Query on hmm_hits with the where clause of 'source in ("Campbell_et_al")' did
              not return anything.`

Likewise, with any hmm source that is the error that I receive.

**Comment by meren** [comment]
I am sorry, this doesn't make much sense to me anymore, @sipesk.

If you are getting `ImportError: No module named 'anvio'` error in your terminal, then there isn't much I can do from here to investigate the problem :(

Best,

**Comment by minna-miha** [comment]
@sipesk did you ever resolve this issue? I am having the same exact issue. Thanks
