### ISSUE TITLE
question about pangenomics workflow anvi-summarize gene clusters

### ISSUE THREAD

**Issue by Alopias1988** [merenlab/anvio#921]
Hi, 

I have a question about the structure of the file when you run the anvi-summarize command resulting in a file with the annotation of the gene clusters of all genomes. In the gene function column it shows functions separated by  a "|",  I think these are function of the genes in the cluster? I am asking because when I compare it with the matrix with the presence/absence of functions not all the functions present in the summary file are also in the matrix presence/absence one. Is it because its only taking the first function and disregarding the following ones separated by "|".
Sorry if this is obvious or explained elsewhere, but I couldn't find explanation

Thanks!

**Comment by ShaiberAlon** [comment]
Hi @Alopias1988,

I think this includes the explanation your are looking for (copied from http://merenlab.org/2016/11/08/pangenomics-v2/#making-some-sense-of-functions-in-your-pangenome). I highlighted the most relevant part:

![image](https://user-images.githubusercontent.com/17661044/43409671-2dfde306-93ea-11e8-91bb-45da1babde3b.png)

Let me know if you have any more questions please.
