### ISSUE TITLE
hmm_hits query fails in anvi-summarize

### ISSUE THREAD

**Issue by ShaiberAlon** [merenlab/anvio#927]
```bash
Config Error: Query on hmm_hits with the where clause of 'source in ("BUSCO_83_Protista",
              "Ribosomal_RNAs", "Rinke_et_al", "Campbell_et_al")' did not return anything.
```

```bash
$ anvi-profile -v
Anvi'o version ...............................: margaret (v5.1-master)
Profile DB version ...........................: 29
Contigs DB version ...........................: 12
Pan DB version ...............................: 12
Genome data storage version ..................: 6
Auxiliary data storage version ...............: 2
Structure DB version .........................: 1
```

**Comment by ShaiberAlon** [comment]
Ok, so this contigs database has no hits to any of the hmm profiles, fine, but this error shouldn't occur.

**Comment by meren** [comment]
Great catch. I've been seeing it around and I didn't know how to reproduce. I will look into this :)

**Comment by sipesk** [comment]
How do I include this edit to the code in my own anvi'o version ? I'm getting the same "...Query on hmm_hits with the where clause of ..." error.

**Comment by ShaiberAlon** [comment]
I will respond here now with a relevant answer. To apply this you must work with the `master` version of anvio. This means that you have to install it this way:
http://merenlab.org/2016/06/26/installation-v2/#installing-or-updating-from-the-active-codebase-because-why-not

If you prefer to work with a stable release of anvio then you will have to wait for the next anvio release. Until then I suggest trying to delete the hmms using `anvi-delete-hmms`, and if that doesn't work, then let us know, and we will see if there is an alternative solution to re-doing your contigs database.
