### ISSUE TITLE
Cannot scroll through imported kraken data in anvi-interactive

### ISSUE THREAD

**Issue by efogarty11** [merenlab/anvio#934]
I have imported kraken data into a merged profile. db, but when I visualize it with anvi-interactive and use my mouse to hover over the list of taxonomy I can't scroll to see the rest of the kraken data. 

This is a screenshot of the list that I cannot scroll down to see the rest of. 
<img width="446" alt="screen shot 2018-08-13 at 3 08 57 pm" src="https://user-images.githubusercontent.com/38365171/44055445-07846908-9f0b-11e8-876a-e79a3a1a9709.png">

Let me know if that doesn't make sense.
Thank you! :)

**Comment by ozcan** [comment]
![screen shot 2018-09-10 at 4 38 20 pm](https://user-images.githubusercontent.com/940884/45326322-eb84ed80-b518-11e8-9896-6ac2afe01215.png)
