### ISSUE TITLE
problem with unusual character in "Simão"

### ISSUE THREAD

**Issue by tdelmont** [merenlab/anvio#940]
Hi!

Using anvi'o v5 at the Genoscope, the letter "ã" in Simão (BUSCO 83 reference citation advertised when running hmms) creates a probleme. My collaborators solved the issue by modifying "ã" with "a" in the reference file of HMMs within anvi'o.

I suggest "a" should be used in future anvi'o versions, in case this is a problem for other laboratories as well?

Tom

**Comment by meren** [comment]
It is already resolved in `v5.1` with 3e2b9addcc4da9e77a878644f380cdae8a05ae0b :)
