### ISSUE TITLE
hard-coded clang path prevents install

### ISSUE THREAD

**Issue by ggloor** [merenlab/anvio#942]
Trying to install anvil on OSX with macports using your excellent tutorial at: http://merenlab.org/2016/06/26/installation-v2/

Everything in the "Installing the latest stable release (safe mode)" works until the last command:
pip install anvio

# The following error pops up:
 error: command '/usr/bin/clang' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for pysam
  Running setup.py clean for pysam

    1 error generated.
    error: command '/usr/bin/clang' failed with exit status 1

# and the install fails with the error:

Command "/Users/ggloor/virtual-envs/anvio-5.1/bin/python3 -u -c "import setuptools, tokenize;__file__='/private/var/folders/ml/kt13wlv11411qwwmwxvbc63m0000gp/T/pip-install-iewi2sqt/pysam/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/ml/kt13wlv11411qwwmwxvbc63m0000gp/T/pip-record-vh_uvj8o/install-record.txt --single-version-externally-managed --compile --install-headers /Users/ggloor/virtual-envs/anvio-5.1/bin/../include/site/python3.6/pysam" failed with error code 1 in /private/var/folders/ml/kt13wlv11411qwwmwxvbc63m0000gp/T/pip-install-iewi2sqt/pysam/

# my clang version is:
clang --version
Apple LLVM version 9.1.0 (clang-902.0.39.2)
Target: x86_64-apple-darwin17.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

# using /usr/bin/clang 
/usr/bin/clang --version
Apple LLVM version 9.1.0 (clang-902.0.39.2)
Target: x86_64-apple-darwin17.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Comment by ggloor** [comment]
sorry, FYI, i am using fully up to data High Sierra OS, with fully up to date macports

**Comment by meren** [comment]
Unfortunately this does not seem to be an anvi'o error --there are no hard-coded paths in anvi'o. Nor it seems to be associated with clang path, in fact. I can't see the error from the output. Maybe we could help if you had the entire error output after pip install anvio (feel free to re-open the issue).

**Comment by ggloor** [comment]
so the problem is that the lzma_stub.h file on my computer cannot be found. This appears to be a bug when installing pysam versions higher than 0.13 on High Sierra. Version 0.13 builds perfectly. It is still an open bug on the pysam GitHub site.

Not sure what to do to install anvio. I cannot use home-brew and macports concurrently, and there are a number of macports only packages that I need. 

Is there a way to set a flag or modify the anvio install so that it uses pysam 0.13?

Thanks

Greg

**Comment by meren** [comment]
You could pip install anvi'o with the appropriate pip flag to force not installing pysam, and then you could manually install the version of pysam that works. Sorry for this issue!

**Comment by ggloor** [comment]
Thx. 

so installing pysam 0.13 and then running 

 pip install --no-deps anvio

seems to have worked (I got to the browser window which signals success)

I'm going to the course next week and hopefully this will work

Greg

**Comment by meren** [comment]
Thanks for putting the effort to install anvi'o before the course, Greg :) It sounds like you're golden now.


Best,
