### ISSUE TITLE
anvi-get-sequences-for-gene-calls produces empty protein sequences

### ISSUE THREAD

**Issue by johanneswerner** [merenlab/anvio#943]
Hello, 

I have been following the [metagenome workflow](http://merenlab.org/2016/06/22/anvio-tutorial-v2/#anvi-import-functions) and I wanted to add interpro annotations. Running interpro as documented [here](http://merenlab.org/2016/06/18/importing-functions/#interproscan) gave me a long traceback, but it seems to come down to this: 

```bash
java.lang.IllegalArgumentException: 'sequence' is not an amino acid sequence []
```

Checking the protein fasta file (produced with 

```bash
anvi-get-sequences-for-gene-calls -c contigs.db --get-aa-sequences -o amino-acid-sequences.fa
```

revealed that this fasta file includes empty sequences, see below

```bash
(...)
>1176155
RNGRKPDGATPRGGXSPLGRKHLLXGRKFIDVTSXIRGSXTRASRSGNTSAPSVTRIYWAXRVCRRLYXSSVKASGSTREMRRKRYNLRMQEVYGTHGVGVKSVDIMGNTESEGSKLVHS
XRXDTKARVANGIRYPSSPGPKRXLLAFRSIDPLRGEANALNNPPGXYGRKAKTQRNRRGLAQAVDHVVXFVDKRRTLPRLETVTKISRNGDPLRTAQQVMHGRRQFVIXIVPLSGVTNA
TLIACYKCQARLLPHGRGRXGXRQVSMSLDALGYTRDTMGTTTRRNTERWSKSLXRCPQFGLRSATRPHEVGIASNRRSATLRXICSRALYSPPVKSGKPGVPEVRP
>1176156
LRSMRERETTQTISXGPXIYAKLIXRSPIALTARMLAWKQPFIXRVRNSSLVERLGVDDNRAXAYYRSYGINNLLLIGRGAFQLHXSSAVRYCGAAGKENVGISNDNAGEKPAHRKTKVS
XSTLIGSGLVGSXGEPEWGSRWTTGXYSSTSNYCDGGTEXXKVRVLTEXYVEECRYIFGRKIRQICXSLIVPGIFGRTDSDPNQTSKKNLXASDNCCPYRKPTQVVEESIQRCSSESWLR
NXANXSCNFGRKDSSEQSEDAEKWPRRLFIKNIWLCKIXRXRIRPDTCPVPEGXVEMLFMLRYGEALKRSPGKRRPXLXRSXGSEIPCRVSSDLHEWCNDLGTVSAMSSVK
>1176157

>1176158

>1176159

>1176160

>1176161

>1176162
GEFDPGSGXTLAACLMHASRTVLRDSGKWVSNAXVTCPXVGDNSGKLELIPHVMAFQQNGYXNFRVLGEGLVSDXLVGEVTAHQGNDRXLVXEDDQPHWDXDTAQTPTGGSSKEYCAMGE
SLTQRRRVGDEGFRVVNPFSQGXIMTVPEEXAMANYVPAAAVIRRWRALSGIIGRKAGVGGFASQMXNLPAXPGGNIRYCEARVQQGKAEFPVXWXNAXISGGTPVAKAAFWAVTDAEVL
KRGERTGLDTLVVHAVNDGHXVWGVSTLSVPKLTHXVSRLGSTVARLKLKGIDGGPHKQRSVWFNSMQHEEPYQGLT
>1176163

(...)
```

I assume this is not intended this way. Can anyone help me out where this problem originates from and how to fix it? If any additional information is needed, I will provide it.

I don't know if this is related, but including the COG annotation with

```bash
anvi-run-ncbi-cogs -c contigs.db --num-threads 26
```

showed a warning message

```bash
WARNING
===============================================
150 entries in the sequences table had blank sequences :/ This is related to the
issue at https://github.com/merenlab/anvio/issues/565. If this is like mid-2018
and you still get this warning, please find an anvi'o developer and make them
feel embarrassed. If it is earlier than take this as a simple warning that some
gene calls in your downstream analyses may have no sequences, and that's OK.
This is a very minor issue due to on-the-fly addition of Ribosomal RNA gene
calls to the contigs database, and will likely will not affect anything major.
This warning will go away when anvi'o can seamlessly work with multiple gene
callers (which we are looking forward to implement in the future).
```

I don't know if this has anything to do with it. Thank you so much for your help.

And here is my anvi'o version: 

```bash
$ anvi-self-test --version
Anvi'o version ...............................: margaret (vunknown)
Profile DB version ...........................: 29
Contigs DB version ...........................: 12
Pan DB version ...............................: 12
Genome data storage version ..................: 6
Auxiliary data storage version ...............: 2
Structure DB version .........................: 1
```

I have installed anvio with the painless conda installation: http://merenlab.org/2016/06/26/installation-v2/#painless-installation-with-conda

**Comment by meren** [comment]
I think you should manually remove blank sequences for now :/

I have an idea where it is coming form, and yes, it has something to do with the warning message you pasted. There is another issue associated with this problem, and I will link this one to that when I have a chance.


Best wishes,

**Comment by johanneswerner** [comment]
Thank you for the quick reply. 

To anyone, who faces the same issue: 

```bash
sed '/^>/ {N; /\n$/d}' amino-acid-sequences.fa > amino-acid-sequences_clean.fa
```

**Comment by brymerr921** [comment]
I am also running into an error caused by blank sequences while trying to run GhostKoala. For example, running `anvi-get-sequences-for-gene-calls --get-aa-sequences` before running `anvi-run-hmms` produces no empty sequences and 2609 gene calls. Running anvi-get-sequences-for-gene-calls --get-aa-sequences` after `anvi-run-hmms` produces 8 additional sequences in my output file. When I run `anvi-export-gene-calls` on the same contigs database, I see that these 8 additional sequences come from `Ribosomal_RNAs`. Two of them have amino acid translation (?) and the other six are blank.

Thanks for the fix, @johanneswerner.

When specifying `anvi-get-sequences-for-gene-calls` along with `--get-aa-sequences`, perhaps all genes called by `Ribosomal_RNAs` should be skipped?

**Comment by meren** [comment]
I think we solved this but I am not sure :/ Apologies. I hope it will come back with a newer version of the codebase so we will be able to take a look at this again.

**Comment by harish0201** [comment]
Apologies that I'm reviving the thread, but manual inspection of such gene-calls on expasy translate shows that these "blank" protein calls do seem to have a ton of stops in between. Could that be the issue?

**Comment by meren** [comment]
hey @harish0201, is it true that you run into the same issue (i.e., the reporting of blank sequences) with your own contigs database and anvi'o `v5.5`? 

If that is the case, it would be very helpful if you can make your contigs db available to me for testing (i.e., through a Google Drive drive download link).

Thanks,

**Comment by harish0201** [comment]
Sorry! I wasn't getting notifications from github!

I'll check and get back to you by the weekend if that's fine by you?
