### ISSUE TITLE
anvi-import-collection error (entries are not unique in some tables)

### ISSUE THREAD

**Issue by nick-youngblut** [merenlab/anvio#945]
I'm running anvio version:

```
Anvi'o version ...............................: margaret (vunknown)
Profile DB version ...........................: 29
Contigs DB version ...........................: 12
Pan DB version ...............................: 12
Genome data storage version ..................: 6
Auxiliary data storage version ...............: 2
Structure DB version .........................: 1
(/ebio/abt3_projects/software/dev/llmga/.snakemake/conda/3b8a2f3c)
```

...and I'm getting the following error when running `anvi-import-collection` on a set of bins generated with `maxbin2`:

```
Contig/split name conversion .................: 56166 contig names converted into 56166 split names.
Item names in input ..........................: 56,166
Num bins in input ............................: 190
Items in profile database ....................: 57,501
Item names shared between input and db .......: 56,166

WARNING
===============================================
1335 item(s) that were in the database, but were not in the input file, will not
be described by any bin in the collection MaxBin2_low_prob. That is totally
fine, but anvi'o hopes that you are aware of that. This means you have more
things in your database than the number of things your input file describes.
Here is an example of something that is in your database but not in any bin in
your input file: coassemble_26409_split_00001.



Config Error: This is one of the core functions of anvi'o you never want to hear from, but
              there seems to be something wrong with the table 'collections_bins_info' that
              you are trying to read from. While there are 516 items in this table, there are
              only 326 unique keys, which means some of them are going to be overwritten when
              this function creates a final dictionary of data to return. This may be a
              programmer error when the data was being inserted into the database, but needs
              fixin' before we can continue. If you are a user, please get in touch with
              anvi'o developers about this error. If you are a programmer, you probably did
              something wrong :(
```

For generating the contig db, I used the `--skip-mindful-splitting` option, since I had already split my contigs prior to the import. The `maxbin2` binning was done on the split contigs, so all of the contig naming should be the same. As far as I can tell, none of my contigs are named with "*_split_00001" in my contigs database or in my maxbin2 bins. 

For the `anvi-import-collection` command, I'm using `--contigs-mode`, which I thought prevented renaming of the contigs. However, the log for the import states: 

```
Contig/split name conversion .................: 56166 contig names converted into 56166 split names.
```

...so it appears that `anvi-import-collection` is renaming contigs labeled such as `coassemble_26409` to `coassemble_26409_split_00001`, which results in a key mismatch between the collection contig names and the database contigs names. Is this a bug with `anvi-import-collection --contigs-mode` or am I just doing something wrong? 

I can't find a lot of documentation on `--contigs-mode`, so it's hard to tell if I'm using it wrong. The docs on `anvi-import-collection` state:

```
  --contigs-mode        Use this flag if your binning was done on contigs
                        instead of splits. Please refer to the documentation
                        for help.
```

...but where in the `documentation` should I be looking? There's a ton of documentation on the anvio website, and I don't see any search bar for finding all docs relating to `--contigs-mode`. I could only find this info at http://merenlab.org/2016/06/22/anvio-tutorial-v2/:

> But if you have contig names, you can import them using anvi-import-collection with the flag --contigs-mode.

**Comment by meren** [comment]
Hi @nick-youngblut,

Very sorry for the late response. This seems like a boring problem. Would you mind sending your contigs database and the file you are trying to import so I can take a look?

You can send a Dropbox link to my private e-mail address.


Best,

**Comment by meren** [comment]
Thanks for sending the files, @nick-youngblut.

I managed to get it to working after running these (quite destructive) commands:

```
sqlite3 PROFILE.db 'delete from collections_info;'
sqlite3 PROFILE.db 'delete from collections_bins_info;'
sqlite3 PROFILE.db 'delete from collections_of_contigs;'
sqlite3 PROFILE.db 'delete from collections_of_splits;'

anvi-import-collection -p PROFILE.db \
                       -c coassemble.db maxbin2_high_prob.scaffolds2bin \
                       -C TEST \
                       --contigs-mode
```

You may want to first export the contents of your `collections_of_splits` table using `anvi-export-table` program.

The actual problem is that this command returns a list of entires with entry ids that are not unique:

```
sqlite3 PROFILE.db 'select * from collections_bins_info;'
```

I don't know how it happened. @nick-youngblut, could it be the case that you imported these results in parallel? 

Regardless, @ozcan, we need to test whether we fail to maintain unique IDs after multiple `anvi-import-collection` calls. I have the feeling that we had addressed this before, but it seems the problem is still present.


Best,

**Comment by nick-youngblut** [comment]
Yeah, the pipeline might be importing up to 3 different collections in parallel. I adjust the "database write" resources in my pipeline so that only one cluster job imports to the database at a time. I'll give it a try now (I've just been running test datasets). Thanks for the help with this!

**Comment by meren** [comment]
Excellent. Can you please update us regarding how it went? :)

Thank you!

**Comment by meren** [comment]
Ozcan solves the issue with #989 :) Thank you for reporting, @nick-youngblut.
