### ISSUE TITLE
anvio-interactive crash on OS X 10.13.6

### ISSUE THREAD

**Issue by ggloor** [merenlab/anvio#949]
when running anvio-interactive the server crashes with the error:

+[__NSPlaceholderDate initialize] may have been in progress in another thread when fork() was called. We cannot safely call it or ignore it in the fork() child process. Crashing instead. Set a breakpoint on objc_initializeAfterForkError to debug.

fixed by setting the following environment variable following the issue and suggestions here:

http://sealiesoftware.com/blog/archive/2017/6/5/Objective-C_and_fork_in_macOS_1013.html

essentially a mismatch between the way fork() is called in Python and what is allowed in latest version of OS x

**Comment by ozcan** [comment]
Hi @ggloor,

Thank you for reporting this and linking the solution, many people experienced this problem on new OSX and this link helped us to resolve it quickly.

Best,
