### ISSUE TITLE
display pangenome analysis

### ISSUE THREAD

**Issue by floresg** [merenlab/anvio#950]
Hello, 
Version report is below:

Mac-Pro:anvio gflores$ anvi-self-test --version
Anvi'o version ...............................: margaret (v5.1)
Profile DB version ...........................: 29
Contigs DB version ...........................: 12
Pan DB version ...............................: 12
Genome data storage version ..................: 6
Auxiliary data storage version ...............: 2
Structure DB version .........................: 1

I have been using anvio for the last couple of months without any issues. Today when I tried to visualize my pangenome I get the following error:

/usr/local/Cellar/anvio/5.1/libexec/lib/python3.7/site-packages/sklearn/utils/__init__.py:4: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  from collections import Sequence
Interactive mode .............................: pan                                            
[29 Aug 18 09:40:23 Initializing the pan database superclass] Setting profile self data dict   

Config Error: This is one of the core functions of anvi'o you never want to hear from, but    
              there seems to be something wrong with the table 'states' that you are trying to
              read from. While there are 7 items in this table, there are only 6 unique keys, 
              which means some of them are going to be overwritten when this function creates 
              a final dictionary of data to return. This may be a programmer error when the   
              data was being inserted into the database, but needs fixin' before we can       
              continue. If you are a user, please get in touch with anvi'o developers about   
              this error. If you are a programmer, you probably did something wrong :(  

I had left the display of the pangenome open in Chrome for several days but quit it yesterday. Everything worked yesterday but not today? Nothing changed on my computer so I am not sure what happened. I just ran the the self test and all the Chrome displays worked. The report for the version self test is above. I installed anvio using homebrewer and my OS is Yosemite Version 10.10.5

Thanks for your help.
Gilberto Flores

**Comment by meren** [comment]
Can you find out the state name that appears twice in your pan database? `anvi-delete-state` has a `--list-states` flag.

Please send the output here as well so I can follow up with making sure whatever is causing this is fixed.


Best,

**Comment by floresg** [comment]
Hello, 

I entered the command below and got the same error. 

anvi-delete-state -p Akkermansia/Akkermansia_Pan-PAN.db --list-states


Config Error: This is one of the core functions of anvi'o you never want to hear from, but    
              there seems to be something wrong with the table 'states' that you are trying to
              read from. While there are 7 items in this table, there are only 6 unique keys, 
              which means some of them are going to be overwritten when this function creates 
              a final dictionary of data to return. This may be a programmer error when the   
              data was being inserted into the database, but needs fixin' before we can       
              continue. If you are a user, please get in touch with anvi'o developers about   
              this error. If you are a programmer, you probably did something wrong :(

**Comment by meren** [comment]
Sorry. I suggest you to rerun this analysis.
