### ISSUE TITLE
blast e-value and other parameters for gene annotation?

### ISSUE THREAD

**Issue by Alopias1988** [merenlab/anvio#951]
What are the default parameters Anvi'o uses in blast for gene functional annotation in the pangenome workflow?

Thanks

**Comment by meren** [comment]
So sorry this fell through the cracks. Although issues are not the best revenue to ask questions, I guess we could have responded: `1e-5` is default. Our strategy uses MCL to identify clusters, so a much relaxed BLAST e-value cutoff works perfectly well. Please read our metapangenomics paper for the details of the pangenomic workflow.
