### ISSUE TITLE
anvi-run-hmms: cannot set temporary directory

### ISSUE THREAD

**Issue by nick-youngblut** [merenlab/anvio#952]
It appears that there's no way to set the temporary directory for `anvi-run-hmms`. This feature would be helpful to reduce the I/O load on our main file system. The same could be said for any other anvio command that uses temporary directories but does not give the user the option to specify the temporary directory location. 

```
$ anvi-self-test --version
Anvi'o version ...............................: margaret (vunknown)
Profile DB version ...........................: 29
Contigs DB version ...........................: 12
Pan DB version ...............................: 12
Genome data storage version ..................: 6
Auxiliary data storage version ...............: 2
Structure DB version .........................: 1
```

**Comment by meren** [comment]
You can set a TMP directory as explained here:

https://github.com/merenlab/anvio/issues/906#issuecomment-403951269


Best,
