### ISSUE TITLE
"anvi-migrate-db"  not woking with hombrew installation on High Sierra

### ISSUE THREAD

**Issue by sdittami** [merenlab/anvio#958]
I am running anvio v5.1 on MacOs High sierra and used homebrew to install anvio:

Here the output of "anvi-self-test --version":
Anvi'o version ...............................: margaret (v5.1)
Profile DB version ...........................: 29
Contigs DB version ...........................: 12
Pan DB version ...............................: 12
Genome data storage version ..................: 6
Auxiliary data storage version ...............: 2
Structure DB version .........................: 1

Anvio itself seems to be working fine (as did the previous version), but "anvi-migrate-db" gives me the following error message when called (regardless of the parameters):

Traceback (most recent call last):
  File "/usr/local/bin/anvi-migrate-db", line 5, in <module>
    import h5py
  File "/usr/local/Cellar/anvio/5.1/libexec/lib/python3.7/site-packages/h5py/__init__.py", line 26, in <module>
    from . import _errors
ImportError: dlopen(/usr/local/Cellar/anvio/5.1/libexec/lib/python3.7/site-packages/h5py/_errors.cpython-37m-darwin.so, 2): Library not loaded: /usr/local/opt/hdf5/lib/libhdf5.101.dylib
  Referenced from: /usr/local/Cellar/anvio/5.1/libexec/lib/python3.7/site-packages/h5py/_errors.cpython-37m-darwin.so
  Reason: image not found

The library libhdf5.101.dylib is not present in the specified folder but libhdf5.100.dylib and libhdf5.103.dylib are.

I guess I could find a copy of version 5.101 and move it to the folder, but I figured I'd report the problem anyway. Thank you very much in advance,
Simon

**Comment by meren** [comment]
Thanks. I also run into this issue recently during a workshop. We will look into this.

**Comment by ozcan** [comment]
Hey @sdittami,
Thank you for reporting, as hdf5 version changed binaries needs to be rebuilt. I am building new binaries now, also installing from source should work as below

```
brew reinstall merenlab/anvio/anvio --build-from-source
```

**Comment by meren** [comment]
Is it OK to close this one?

**Comment by ozcan** [comment]
I think it is okay to close this one, `--build-from-source` works for now and new binaries will be up when we release 5.2.

**Comment by meren** [comment]
👍 🎊
