### ISSUE TITLE
anvi-profile performance

### ISSUE THREAD

**Issue by arivers** [merenlab/anvio#961]
# Performance issue
I am using `anvi-merge` to process sorted indexed bam files  and a contig database.  I have tested multiple samples but a typical sample looks like this:

```
input_bam ..........................: /project/gbru_fy18_rice_methane/mapping/FRCS-D1-R1-238.bam
output_dir .........................: /project/gbru_fy18_rice_methane/anvio/profiles/FRCS_D1_R1_238
total_reads_mapped .................: 6,061,299
num_contigs ........................: 2,218,523
num_contigs_after_M ................: 145,320
num_splits .........................: 147,532
total_length .......................: 1,407,546,361
```

A typical run command is
```
anvi-profile 
  -i /project/gbru_fy18_rice_methane/mapping/FRCS-D1-R1-238.bam \
  -c /project/gbru_fy18_rice_methane/anvio/contigs.db \
  --output-dir /project/gbru_fy18_rice_methane/anvio/profiles/FRCS_D1_R1_238 
  --sample-name FRCS_D1_R1_238 \
  --skip-SNV-profiling -T 2 
  --write-buffer-size 200 \
  --min-contig-length 5000
```
When I monitor the run this uses about 96GB of memory.  I cannot add more threads or I run out of memory. I've tried with a default buffer size of 500 and speeds were similar.

Contigs are processed at a rate of only about 59/min.  Smaller Bams process a little faster but these rates are at the limit of what I can process in 48 hours on a single 40 core Node with 128GB of RAM and the experiment has 100 samples.

The performance seems much slower than I would expect for the parsing of a bam file.  I was thinking there may be an issue with an underling library, for example htsliib or samtools don't  have their C parser compiled properly and are defaulting to a slower parser.

# Installation method
```
conda create -y --name anvio5 python=3.6
conda install -y --name anvio5 -c bioconda -c conda-forge anvio=5.1 diamond bwa
```
The conda environment yml file was exported and attached.

# System information
* OS CentOS Linux release 7.4.1708 (Core)
* Linux kernel: 3.10.0-693.el7.x86_64
* scheduler: SLURM
* Architecture:          x86_64
* CPU op-mode(s):        32-bit, 64-bit
* Byte Order:            Little Endian
* CPU(s):                40
* On-line CPU(s) list:   0-39
* Thread(s) per core:    2
* Core(s) per socket:    10
* Socket(s):             2
* NUMA node(s):          2
* Vendor ID:             GenuineIntel
*CPU family:            6
* Model:                 62
* Model name:            Intel(R) Xeon(R) CPU E5-2670 v2 @ 2.50GHz
* Stepping:              4
* CPU MHz:               1715.136
* CPU max MHz:           3300.0000
* CPU min MHz:           1200.0000
* BogoMIPS:              5000.09
* Virtualization:        VT-x
* L1d cache:             32K
* L1i cache:             32K
* L2 cache:              256K
* L3 cache:              25600K
* NUMA node0 CPU(s):     0-9,20-29
* NUMA node1 CPU(s):     10-19,30-39
* Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm epb tpr_shadow vnmi flexpriority ept vpid fsgsbase smep erms xsaveopt dtherm ida arat pln pts

**Comment by adriaaula** [comment]
Hello, 

This issue also happens in the snakemake `metagenomics` workflow, in which multiple `anvi-profile`s are sent, using the totality of the memory (I have a big dataset, and in a node with 750 Gb it crashed by memory limit). 

I solved it fiddling the threads parameter for avoiding multiple profiles at once, and this seem to solve the problem.

**Comment by meren** [comment]
That is the right way to address that, @adriaaula.
