### ISSUE TITLE
Negative percent redundancy in anvi-summarize output

### ISSUE THREAD

**Issue by mkhall** [merenlab/anvio#966]
The 'percent_redundancy' column of the 'default.txt' file in the 'misc_data_layers' folder of the anvi-summarize output of my pangenome has three instances where the percent redundancy is apparently -1. Since this doesn't seem plausible, could this be an indication of a problem with anvi'o or with those three genomes? None of the other numbers in that file appear to be obviously erroneous.

**Comment by meren** [comment]
This seems like a simple check somewhere :) thanks for reporting. I don’t think this suggests an error with the genomes or other analyses.

**Comment by meren** [comment]
This must be fixed by now :)

**Comment by kaiher** [comment]
I had the same problem with anvio v5.5 installed on ubuntu 18.4.1 LTS via conda. Does the negative score (-1) mean exclusively high or low redundancy?

**Comment by meren** [comment]
This does not seem to be a problem in `master`, @kaiher. It is probably fixed after `v5.5`.

> Does the negative score (-1) mean exclusively high or low redundancy?

What is the completion?

**Comment by kaiher** [comment]
Thank you for quick reply. The point is whether I should remove the data with percent redundancy = -1 from my analysis. Kind regards.

**Comment by meren** [comment]
I don't think so, @kaiher.

**Comment by kaiher** [comment]
Thus, I include that data in the following analysis. Thank you for your advise!
