### ISSUE TITLE
anvi-run-pfams maybe not removing /tmp files afterwards

### ISSUE THREAD

**Issue by AstrobioMike** [merenlab/anvio#967]
Hi all, 

Using anvi'o v5.1, `anvi-run-pfams` seems to not be removing the temporary files it's creating in /tmp. I tried looking through the codebase to find out if that's actually what's going on, but alas I'm just not talented enough yet for that :/ 

Conveniently, when /tmp fills up, anvio keeps running fine as it puts the needed tmp files in the current working directory. But of course a filled /tmp causes other problems

**Comment by ozcan** [comment]
Thank you @AstrobioMike, it should clean those now unless `--debug` parameter is given.
