### ISSUE TITLE
load state in pangenome view missarranges genomes in additional data layers

### ISSUE THREAD

**Issue by AstrobioMike** [merenlab/anvio#968]
Hiya, 

With v5.1, installed via pip in a virtual environment, for some reason the ordering of genomes in the additional data layers is not preserved after loading a state. 

For instance, clicking the order by and rearranging layers based on, say, gene cluster frequencies, rearranges everything beautifully:
![image](https://user-images.githubusercontent.com/13923308/45378921-9a760780-b5b3-11e8-96b2-e42658594b79.png)

But when saving that state and reloading it even in the same session, the genome ordering reverts to something else: 
![image](https://user-images.githubusercontent.com/13923308/45378970-b7123f80-b5b3-11e8-941c-1fdba550ba7f.png)

Exporting the state and looking at the json file it seems the order is correct in there, but something else is overriding it maybe?

**Comment by AstrobioMike** [comment]
Out of curiosity and to be sure, i checked the prochlorococcus pangenome from the [main pangenome tutorial](http://merenlab.org/2016/11/08/pangenomics-v2/#computing-the-average-nucleotide-identity-for-genomes), and the same deal happens:
![image](https://user-images.githubusercontent.com/13923308/45383185-55f06900-b5bf-11e8-8c40-00844a4525a8.png)

**Comment by meren** [comment]
Thanks for pointing this out, Mike. @ozcan and I are thinking making a new minor release, this may get resolved with that one.

**Comment by AstrobioMike** [comment]
Hey folks, sorry to bring this issue up again, but it seems to be happening still with the stable v2. 

```
anvi-interactive -v
Anvi'o version ...............................: margaret (v5.2)
Profile DB version ...........................: 30
Contigs DB version ...........................: 12
Pan DB version ...............................: 12
Genome data storage version ..................: 6
Auxiliary data storage version ...............: 2
Structure DB version .........................: 1
```

Installed via pip following the instructions page.  

Like before, the exported state json file has things in the correct order, but when loading it for some reason layers additional data layers revert to some initial order.

**Comment by AstrobioMike** [comment]
To put a face with this heartache, this is what I'm sending to collaborators:
![screen shot 2019-01-30 at 3 50 43 pm](https://user-images.githubusercontent.com/13923308/52021417-ddc10c00-24a9-11e9-88f0-4ec38ac2dd20.png)

And this is what they're getting when loading the state:
![screen shot 2019-01-30 at 4 14 59 pm](https://user-images.githubusercontent.com/13923308/52021513-53c57300-24aa-11e9-9538-77851997c821.png)

:( 

I've tried to mess with this, but java is just completely alien to me 👽

**Comment by AstrobioMike** [comment]
No, sorry, didn't mean to be ambiguous. It's not correct when I load the state either. 

Things are saved in the correct order inside the json file if you export the state. But for some reason that's not being used when loading the state. The order of the misc data seems to default to the initial configuration.

**Comment by ozcan** [comment]
Hi Mike,
Thank you for reminding this issue. It took some time but I think now this issue was fixed. We are going to release a new version pretty soon, including this fix. But the solution was simpler than I have expected, that is why I want to make sure that it is fixed before the release. 

Can you test if you have a master and confirm? If you do not have master or would like to try on 5.2, you can apply this patch directly to 5.2 and it should work.

```
cd $(dirname $(python -c "import anvio; print(anvio.__file__)"))
cd ..
wget https://github.com/merenlab/anvio/commit/3eb9fc90a1e9b3bb91caa93a6159b95c1efe0c31.diff -O /tmp/anvio_state_fix.diff
git apply /tmp/anvio_state_fix.diff
```

**Comment by AstrobioMike** [comment]
Yeppers, that seems to have fixed it @ozcan. You rock!
