### ISSUE TITLE
How to read the anvi-summarize output? What does "detection" mean?

### ISSUE THREAD

**Issue by ataravarice** [merenlab/anvio#969]
Hello everyone

After I try metagenomic part of Anvio-prochlcocccus test using Anvio 5.1 like
http://merenlab.org/data/2018_Delmont_and_Eren_Metapangenomics/#generating-a-collection

I get an anvio Prochlorococcus-SUMMARY directory containning a file named index.html, the Across Samples (1) label is like this

![image](https://user-images.githubusercontent.com/25415762/45429762-80811580-b6d6-11e8-80c7-7d93c055d7dd.png)

What does detection,or bins_across_samples/detection.txt means? 
and What does mean_coverage and mean_coverage_Q2Q3 or bins_across_samples/mean_coverage_Q2Q3.txt means ?

I tried anvi-summarize -h, it only explain what file it used to output the file. And Anvi'o User Tutorial for Metagenomic Workflow in http://merenlab.org/2016/06/22/anvio-tutorial-v2/ contain no word of "detection".

is there somewhere the index.html is interpreted?

**Comment by meren** [comment]
Hi @ataravarice,

Please take a look at this one:

http://merenlab.org/2017/05/08/anvio-views/

**Comment by ataravarice** [comment]
Thank a lot! The page is now so easy to understand. 

2018-09-12 

Huang Xingyu 



发件人："A. Murat Eren" <notifications@github.com>
发送时间：2018-09-12 22:06
主题：Re: [merenlab/anvio] How to read the anvi-summarize output? What does "detection" mean? (#969)
收件人："merenlab/anvio"<anvio@noreply.github.com>
抄送："ataravarice"<huanggreatyu@126.com>,"Mention"<mention@noreply.github.com>

Closed #969.
