### ISSUE TITLE
anvi-summarize does not accept a flag for bins, summarizing all gene clusters in a collection

### ISSUE THREAD

**Issue by scrosson73** [merenlab/anvio#970]
In trying to summarize information in a bin, the latest release of Anvio is unable to specifically extract the bin information. It seems to be summarizing all gene clusters in all bins, even though a collection is present (and specified using the -C flag).

**Comment by meren** [comment]
Yes, that is the current default behavior. All gene clusters are summarized, and the resulting output file contains a column that describes to which bin a gene gene cluster belongs.

We can add a flag to report only gene clusters affiliated with bins.

**Comment by scrosson73** [comment]
Thank you, Meren. I can operate on the "bin_name" column, which I had missed.
