### ISSUE TITLE
anvi-merge-db sqlite3 table column error for migration from version 5 to 12

### ISSUE THREAD

**Issue by seanmcallister** [merenlab/anvio#971]
Anvi'o version ...............................: margaret (v5.1)
Profile DB version ...........................: 29
Contigs DB version ...........................: 12
Pan DB version ...............................: 12
Genome data storage version ..................: 6
Auxiliary data storage version ...............: 2
Structure DB version .........................: 1

Operating system: MacOSX 10.12.6
Installation: ```brew reinstall merenlab/anvio/anvio --build-from-source```
(Note: I did it this way due to the anvi-migrate-db h5py/hdf5 error and solution in another issue.)

I ran the anvi-migrate-db on the h5 genome database file, and that worked fine. But on trying to run on the pangenome database file, got this error:

```
wifi-roaming-128-4-182-83:anvio_update sean$ anvi-migrate-db Zeta_Pangenome-PAN.db 
/usr/local/Cellar/anvio/5.1/libexec/lib/python3.7/site-packages/matplotlib/__init__.py:1067: UserWarning: Duplicate key in file "/Users/sean/.matplotlib/matplotlibrc", line #2
  (fname, cnt))
Database Path ................................: Zeta_Pangenome-PAN.db
Detected Type ................................: pan
Current Version ..............................: 5
Target Version ...............................: 12
[12 Sep 18 12:21:23 Trying to upgrade the pan database] ...                                                                                                                                                                                Traceback (most recent call last):
  File "/usr/local/bin/anvi-migrate-db", line 119, in <module>
    Migrater(args_for_single_db).process()
  File "/usr/local/bin/anvi-migrate-db", line 93, in process
    migration_scripts[self.db_type][script_name].migrate(self.db_path)
  File "/usr/local/Cellar/anvio/5.1/libexec/lib/python3.7/site-packages/anvio/migrations/pan/v5_to_v6.py", line 47, in migrate
    pan_db._exec('''INSERT INTO %s VALUES (?,?,?)''' % t.item_orders_table_name, tuple([clustering, 'newick', newick]))
  File "/usr/local/Cellar/anvio/5.1/libexec/lib/python3.7/site-packages/anvio/db.py", line 174, in _exec
    ret_val = self.cursor.execute(sql_query, value)
sqlite3.OperationalError: table item_orders has 4 columns but 3 values were supplied
```

The "matplotlibrc" error at the front shows up whenever I run an anvi command, so I don't think it is a problem (must be an environment thing I'm too lazy to fix quite yet).

It gave me this error even when just trying to upgrade to target version 6 (-t 6).

Thanks for your help!!

**Comment by meren** [comment]
Hi @seanmcallister, sorry about this :( we will look into this.

**Comment by ozcan** [comment]
This issue will be fixed in the new release, but if you need before that you can install anvi'o from the master repository or you can replace the failing upgrade script with the master version.

Link to the updated version of the upgrade script: `https://raw.githubusercontent.com/merenlab/anvio/master/anvio/migrations/pan/v5_to_v6.py`

From your error log, it seems this is the location of failing script: /usr/local/Cellar/anvio/5.1/libexec/lib/python3.7/site-packages/anvio/migrations/pan/v5_to_v6.py

**Comment by ozcan** [comment]
Also really thank you for reporting this @seanmcallister, as we upgrade our databases each release, it is hard for us to detect this kind of issues without community support.

**Comment by seanmcallister** [comment]
Do I need to do anything besides replace the v5_to_v6.py file in the folder you indicated? If not, it still has the same error after replacing with the fixed script.

**Comment by ozcan** [comment]
Ah sorry, the previous version of script tried to create the table with wrong schema. So first you need to delete it like below:
```
sqlite3 Zeta_Pangenome-PAN.db "DROP TABLE item_orders"
```

**Comment by seanmcallister** [comment]
That did it!! Worked great! Thanks!
