### ISSUE TITLE
NoneType error in --gene-mode

### ISSUE THREAD

**Issue by ekiefl** [merenlab/anvio#972]
Running the following leads to the trace back `anvi-interactive -p SAMPLES-MERGED/PROFILE.db  -c one_contig_five_genes.db --gene -C DEFAULT -b EVERYTHING`:

```
Traceback (most recent call last):
  File "/Users/evan/Software/anvio/bin/anvi-interactive", line 100, in <module>
    d = interactive.Interactive(args)
  File "/Users/evan/Software/anvio/anvio/interactive.py", line 133, in __init__
    self.layers_additional_data_keys[group_name], self.layers_additional_data_dict[group_name]) if a_db_is_found else {}
  File "/Users/evan/Software/anvio/anvio/tables/miscdata.py", line 355, in update_orders_dict_using_additional_data_dict
    sum_stackbar_items[stackbar_name][layer] += float(additional_data_dict[layer][data_key])
TypeError: float() argument must be a string or a number, not 'NoneType'
```

error can be reproduced by running in the `tests` folder 

```
bash run_structure_mock.sh new
cd sandbox/test-output
anvi-script-add-default-collection -p SAMPLES-MERGED/PROFILE.db
anvi-interactive -p SAMPLES-MERGED/PROFILE.db  -c one_contig_five_genes.db --gene -C DEFAULT -b EVERYTHING
```

**Comment by ozcan** [comment]
Thanks for the reproducible report, but it seems this problem goes deeper than the interactive interface.`SAMPLES-MERGED.db` contains samples s01-05 but s05 is missing in imported `additional_layers_data.txt`. 
To avoid this, adding checks to `anvi-import-misc-data` makes much more sense to me.

**Comment by ozcan** [comment]
After working on this issue we realized that miscdata already supports missing values but default null value for stackerbar type was None which gives trouble for calculations and sorting
