### ISSUE TITLE
anvi-summarize not working for external bins 

### ISSUE THREAD

**Issue by bonitalam** [merenlab/anvio#974]
Hello,

I've been trying to run anvi-summarize for bins that I have obtained through Metabat. After running, I get the following config error: 

Config Error: 10577 of the 17717 split names of interest does not occur in the profile
              database. Here is an example:                                           
              'Ch3T0DNA314_S10_coassemble_000000016016_split_00001'.     

I thought I could resolve this by running anvi-import-collection with the Metabat binning_results.txt using the flag --contigs-mode, since the original .txt file does not contain split names. It looks like it worked, but I get the same config error when running anvi-summarize (see image attached). 

![anvio_error](https://user-images.githubusercontent.com/11762925/45457475-eacc9280-b6a3-11e8-83e3-83ba1d8bb140.png)

Any help with this issue would be much appreciated!

Thanks,
Bonita

**Comment by meren** [comment]
Please try again by following the simple instructions that ask user to provide most basic information within their issues.
