### ISSUE TITLE
anvi-split should set then 'name' in 'self' table

### ISSUE THREAD

**Issue by ShaiberAlon** [merenlab/anvio#976]
Currently it gives the name `NO_NAME`, but I think the name should be the name of the bin.

**Comment by ozcan** [comment]
I tried to reproduce this but for me `anvi-split` puts Bin name to `bin_id` meta value.

**Comment by ShaiberAlon** [comment]
Did you check the contigs database? I forgot to mention that my problem was specifically with the contigs database.

**Comment by ozcan** [comment]
Yes you are right, contigs.db keeps old project name, what about project name like `{Bin} of {Collection}`?

**Comment by ozcan** [comment]
Now it names like `"Bin_2" of Contigs DB for anvi'o mini self-test`

**Comment by ShaiberAlon** [comment]
@ozcan, I think that just the bin name would be better. {bin}_{collection} is also good. I just think that avoiding any characters that are not letters, numbers or underscore is good.

**Comment by ozcan** [comment]
Yes, just bin name makes sense, collection name was not easy to access in this context so I have skipped it.

**Comment by meren** [comment]
This is the best solution. Collection name will be much more context-dependent (and personal) than the bin name, anyway :)

Thank you very much, Ozcan!
