### ISSUE TITLE
Consider hmmsearch instead of hmmscan for anvi-run-hmms

### ISSUE THREAD

**Issue by jmtsuji** [merenlab/anvio#978]
This is a suggestion for performance improvement rather than a bug.

# Preface: anvi'o version
I'm working with anvi'o 5 installed via conda:

```
:: Anvo'o version ...

Anvi'o version ...............................: margaret (vunknown)
Profile DB version ...........................: 29
Contigs DB version ...........................: 12
Pan DB version ...............................: 12
Genome data storage version ..................: 6
Auxiliary data storage version ...............: 2
Structure DB version .........................: 1
```

# Problem description
Currently, I find that `anvi-run-hmms` is one of the rate-limiting tools when trying to run on a 50-core system. Only a fraction (e.g., 2-10) of the threads are used.

# Possible solution
`anvio/drivers/hmmer.py`, `anvio/tables/hmmhits.py`, and ultimately `anvi-run-hmms`, rely on hmmscan to perform HMM searches. However, this tool does not parallelize well compared to hmmsearch. [This HMMER blog post](https://cryptogenomicon.org/2011/05/27/hmmscan-vs-hmmsearch-speed-the-numerology/) demonstrates how hmmscan becomes i/o limited at scale, whereas hmmsearch scales in performance much better.

Summary: perhaps hmmscan could be replaced with hmmsearch to substantially increase `anvi-run-hmms` search speed when running with multiple threads.

# Potential complications (from above blog post)
Output files of hmmsearch should be comparable to those of hmmscan. However, e-values might change, which could be a problem is these are relied upon for determining true positives.

Just a thought. Thanks again for all your work on anvi'o!

**Comment by meren** [comment]
Thank you very much for the clear report, @jmtsuji!

What do you think, @ozcan? perhaps we should make the switch between  hmmscan and hmmsearch optional through at the driver level and control it through a command line flag?


Best,

**Comment by brymerr921** [comment]
Another option might be to just split the `AA_gene_sequences.fa` file into _n_ parts with equal number of sequences where _n_ == number of cpus requested and run hmmscan on all the parts at the same time with one cpu per hmmscan instance, and then concatenate the results. That way, nothing changes.

**Comment by meren** [comment]
We have addressed the performance problems and will roll them out in `v6`.
