### ISSUE TITLE
"Highlight split on the tree" and "Highlight redundancy" do not follow-up change in clustering view 

### ISSUE THREAD

**Issue by tdelmont** [merenlab/anvio#980]
Hi,

Sorry if this bug was already reported, but I realized that with anvi'o v5.1 when I highlight splits on the Search section of the interface (e.g., using taxonomy name), those splits remain in the exact same locations when changing the clustering of splits (so they do not correspond to the same splits anylonger). I also realized the same happens when highlighting splits containing redundant HMMs for completion estimates,

Best,

Tom

**Comment by meren** [comment]
So when items order changes, highlighted search results remain the same. 

Thanks for the report, Tom.

**Comment by ozcan** [comment]
Thank you Tom, this is now fixed on master.
