### ISSUE TITLE
anvi-compute-ani with internal-genomes file reports an incomplete pairwise comparison

### ISSUE THREAD

**Issue by luuuuuuuke** [merenlab/anvio#982]
(anvio-5) lukem@BZ-CBE-BALROG ~ $ anvi-self-test --version
Anvi'o version ...............................: margaret (v5)
Profile DB version ...........................: 29
Contigs DB version ...........................: 12
Pan DB version ...............................: 12
Genome data storage version ..................: 6
Auxiliary data storage version ...............: 2
Structure DB version .........................: 1

Using linux, not sure how installed because the admin did it (but I can find out if you need me to).

Hello!
I have 5 samples that were each single-assembled. The samples are somewhat related but not related enough that I want to co-assemble. I recovered 52 high quality MAGs from all 5 samples and now I want to use ANI to identify the same MAG/s across different samples. I am using anvio v5 with the following command:

anvi-compute-ani -i internal-genomes.csv -o ANI_6 -T 20

In the resulting folder there is a file called ANIb_percentage_identity.txt, but the pairwise comparison only contains 5 of the 52 MAGs. I noticed that the 5 MAGs are the last MAG listed in the internal-genomes file for each of the 5 samples. But the other 47 MAGs are not listed.

I also tried generating a pangenome db and using that plus the internal-genomes file for anvi-compute-ani but this didn't work either. It is probably something very simple and my internal-genomes file is formatted incorrectly, but I can't figure it out so, please, halp.

Profile and contigs dbs are being shared with the anvio team via dropbox, along with internal genomes file.

THANKS :)

**Comment by meren** [comment]
Thank you for your report and providing us with files to test, Luke. Thanks to this report we found a serious mistake in the way we deal with internal genomes for ANI and @ozcan now has it fixed :)

**Comment by luuuuuuuke** [comment]
I updated anvio to v5.2 and reran this command--it works now. Thanks a billion!
