### ISSUE TITLE
running anvi-compute-ani on FASTA files

### ISSUE THREAD

**Issue by efogarty11** [merenlab/anvio#983]
It would have been a great convenience if `anvi-compute-ani` could also work with FASTA files for quick, _ad hoc_ investigations.

**Comment by meren** [comment]
@efogarty11, this is done, but not through `anvi-compute-ani`. We have a new script that does it only on a single FASTA file.

**Comment by efogarty11** [comment]
I'm not sure if I understand what you mean by this. So I won't be able to run anvi-compute-ani on those ~175 contigs that we were talking about on Monday?

**Comment by meren** [comment]
oh no, you will! :) Let's talk about it offline.
