### ISSUE TITLE
anvi-summarize for external bins not working

### ISSUE THREAD

**Issue by bonitalam** [merenlab/anvio#984]
Operating System: Linux 
Anvio install: Python virtual environment 

Anvi'o version ...............................: 4
Profile DB version ...........................: 23
Contigs DB version ...........................: 10
Pan DB version ...............................: 8
Genome data storage version ..................: 6
Auxiliary data storage version ...............: 2

Hello,

Apologies for submitting this issue before without the relevant information. I've been trying to run anvi-summarize for bins that I have obtained through Metabat. Running anvi-summarize for CONCOCT bins works fine. After running anvi-summarize for Metabat bins, I get the following config error:

Config Error: 10577 of the 17717 split names of interest does not occur in the profile
database. Here is an example:
'Ch3T0DNA314_S10_coassemble_000000016016_split_00001'.

I thought I could resolve this by running anvi-import-collection with the Metabat binning_results.txt file using the flag --contigs-mode, since the original .txt file does not contain split names. It looks like it worked, but I get the same config error when running anvi-summarize (see image attached).

![anvio_error](https://user-images.githubusercontent.com/11762925/45645892-b75c8000-ba76-11e8-8287-7337f877553a.png)

Any insight/help into this issue would be much appreciated! Thank you!

**Comment by meren** [comment]
Hi,

Please upgrade your installation to `v5.1`. We have very limited human resources and we do not give support for issues related to older versions. Apologies for the inconvenience.
