### ISSUE TITLE
--max-contig-length parameter for anvi-profile

### ISSUE THREAD

**Issue by meren** [merenlab/anvio#986]
While we have a parameter for `--min-contig-length` for `anvi-profile`, we don't have a parameter to remove contigs that are longer than a certain length. We shall have it in the name of flexibility anvi'o promises to its users (even when they want to remove their good contigs from their analyses) :(

(I will take an initial stab at this, and then will ask @ShaiberAlon's help to update our metagenomic workflow with addition of the relevant parameter).

**Comment by ShaiberAlon** [comment]
We are spoiling anvi'o users so much that now they ask for features for the sake of philosophical feature symmetry, even when it's about throwing out valuable data!?!?

**Comment by efogarty11** [comment]
No rush at all but if someone can let me know when this is ready to go that would be amazing! :)

**Comment by efogarty11** [comment]
Nevermind I see that it already is, thank you so much!!!

**Comment by meren** [comment]
thanks, @ShaiberAlon!

@efogarty11, please close this issue once you have tested it and confirmed that it is working :)
