### ISSUE TITLE
Anvi'o interactive does not load in Chrome browser

### ISSUE THREAD

**Issue by celiosantosjr** [merenlab/anvio#993]
Anvi'o version ...............................: margaret (v5.1)
Profile DB version ...........................: 29
Contigs DB version ...........................: 12
Pan DB version ...............................: 12
Genome data storage version ..................: 6
Auxiliary data storage version ...............: 2
Structure DB version .........................: 1

**Comment by ozcan** [comment]
Is this a personal computer or server environment? it seems anvi'o interactive is listening on port 8080 without any problem, Can you access `localhost:8080` or `127.0.0.1:8080` on your browser? Sometimes everything works but it just does not pop up for some reason.

If this is is running on a server you need ssh tunneling to browse it, below some links related to that.

http://merenlab.org/2015/11/28/visualizing-from-a-server/
http://merenlab.org/2018/03/07/working-with-remote-interative/

**Comment by celiosantosjr** [comment]
Hi, 

This is a personal computer. Actually, still does not work, but now i have some error messages.

```
[1:1:0926/111144.335430:ERROR:webthread_impl_for_utility_thread.cc(19)] Not implemented reached in virtual blink::ThreadScheduler *blink::scheduler::WebThreadImplForUtilityThread::Scheduler() const
[1:1:0926/111240.636601:ERROR:webthread_impl_for_utility_thread.cc(19)] Not implemented reached in virtual blink::ThreadScheduler *blink::scheduler::WebThreadImplForUtilityThread::Scheduler() const
```

**Comment by ozcan** [comment]
This kind of errors appears sometime, related to Chrome. But when you open browser by yourself can you browse `127.0.0.1:8080`?

**Comment by celiosantosjr** [comment]
I got this message:

```
This site can’t be reached
127.0.0.1 refused to connect.
Try:

Checking the connection
Checking the proxy and the firewall
ERR_CONNECTION_REFUSED
```

**Comment by ozcan** [comment]
Do you see the message below in the terminal when you try this?

```
* The server is now listening the port number "8080". When you are finished, press
CTRL+C to terminate the server.```
```

**Comment by celiosantosjr** [comment]
Yes, i did

**Comment by ozcan** [comment]
Sorry for the inconvenience, this seems really interesting. Can you try adding flags below when running `anvi-display-pan`

```
--server-only --ip-address 127.0.0.1
```

Then after seeing message
```
* The server is now listening the port number "8080". When you are finished, press
CTRL+C to terminate the server.
```

You should be able to open any browser and browse `127.0.0.1:8080`

**Comment by meren** [comment]
I assume this is addressed since it's been three days we haven't heard from @celiosantosjr :)
