### ISSUE TITLE
Discussion for a new feature "anvi-upgrade"

### ISSUE THREAD

**Issue by ozcan** [merenlab/anvio#998]
I thought about this long time ago but it was not logical to invest the time but over time we spent a good amount of time for forgetting little things in releases and having to re-release with the only couple of lines changed.

I am suggesting separating Anvi'o releases and versioning into two parts. `Environment` and `Software` and having a new program to handle software upgrades.

Environment: Environment changes when something in `requirement.txt` or other dependencies changes. Anvi'o now expects a different environment to interact. Environment version can be `major` part of the version number (i.e. `anvio5`, `anvio6`, anvio5 can use snakemake==5.3, anvio6 can use snakemake==6.7 and also new dependency called modeller). This kind of changes require reinstalling anvi'o from scratch since these are platform dependent. 

Software: Software changes are the changes we make in anvi'o code itself (i.e. bug fix in `hmmops.py` file or a new feature in interactive interface), this kind of changes does not necessarily require reinstalling anvi'o. A program in anvi'o can check tags in Github or PyPI and replace changed files with their newer version. This kind of software changes changes the `minor` part of the version (i.e. `5.2`, `5.3`, `5.4`...)

This will allow us to release more frequently without having to rebuild Homebrew binaries, Docker images. And users will have instant access to fixes for their blocking bugs.

Some code in `init.py` can check periodically if there is a software update and print a message like 

> It seems you are using anvi'o `v5.2`. anvi'o can upgrade itself to `v5.6` via `anvi-upgrade`.

or 

> It seems you are using anvio `v5.2`, anvio `v6` is released, but an automatic upgrade is not possible.

**Comment by meren** [comment]
I think this is a brilliant idea that will remove so much pain and suffering from our user's experience.

Basically, once an environment is present for any anvi'o version, upgrading it to the latest minor release of that branch will take only seconds.
